from pathlib import Path
import hashlib,json
R=Path(__file__).resolve().parents[4]; A=Path(__file__).resolve().parent
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
V=json.loads((A/'verification-output.json').read_bytes()); E=V['environment']
artifacts=[]
def artifact(i,filename,kind,description,command=None,result=None):
 d={'id':i,'kind':kind,'path':(A/filename).relative_to(R).as_posix(),'sha256':sha(A/filename),'description':description}
 if kind=='execution':d.update(command=command,result=result,environment=E)
 artifacts.append(d)
artifact('audit','verification-output.json','execution','Existing original rows independently reaggregated and rescored, data scope and training lineage checked; no model generation.','/workspace/tiny-perceptron-vlm/.venv/bin/python docs/technical-reviews/artifacts/p6-19.12/verify.py','3734 unique test rows per architecture rescored; table and boundary counts, CTC 324/324, fixed identities, LFS record hashes and 15 completed raw training receipts match.')
artifact('audit_code','verify.py','code','Actual fresh audit program.')
artifact('mechanism','mechanism-checks-output.json','execution','Bounded CPU CTC collapse, calculator chain and actual section Python fence.','/workspace/tiny-perceptron-vlm/.venv/bin/python docs/technical-reviews/artifacts/p6-19.12/mechanism-checks.py','CTC blank/repeat check gives 大大小; correct calculator arguments pass, executed wrong arguments fail complete chain; section means give 2/3 and 1/2.')
artifact('mechanism_code','mechanism-checks.py','code','Actual bounded CPU verification program.')
artifact('initial_section','19.12-initial-source.md','source_snapshot','Original UTF-8 section bytes, initial input hash; not a normalized snapshot.')
artifact('initial_chapter','19-initial-frozen-input.md','source_snapshot','Initial whole-chapter frozen input, SHA e6a4b4d0ce69ce82f1c810eb2e9c414aa0e5ea47cf4657be6bf91e5a2b463c5b; not a hash of later chapter state.')
for arch in ['moe','dense']:
 artifact(arch+'_rows',arch+'-original-test-outputs.jsonl.gz','source_snapshot','Lossless deterministic gzip of the entire original test output; decompressed original SHA and source path in audit output. No rows or annotations removed.')
 artifact(arch+'_validation',arch+'-original-training-validation-metrics.jsonl','source_snapshot','Exact original validation-event lines from training metrics; source full-file SHA and actual copy scope in accompanying provenance.')
 artifact(arch+'_validation_provenance',arch+'-validation-selection-source.json','source_snapshot','Full original training metric SHA, saved-line SHA and source locator.')
 artifact(arch+'_public_manifest',arch+'-public-inference-manifest.json','source_snapshot','Original public inference manifest downloaded at fixed HF commit; raw bytes match original freeze/test identity.')
artifact('public_bytes','public-pin-byte-verification.json','execution','Anonymous byte verification of all 8 public payload files at immutable commit, no weight loading.','python heredoc using urllib.request and concurrent.futures: GET each receipt-bound file at 979cdfacc588ad0536f1c64fff96f264571cf054; stream SHA-256 and byte counts; retain manifests/config/tokenizers; do not load weights.','All 8 byte counts and SHA-256 values equal the original test receipts; weights streamed for checksumming only.')
artifact('voice_schema','voice-original-source-schema.json','execution','Actual pinned MInDS-14 parquet schema, compared to official documented schema.','/workspace/tiny-perceptron-vlm/.venv/bin/python heredoc: pyarrow.parquet.read_schema(outputs/selftrained-v2/data/voice-sources/minds14-zh-CN.parquet), SHA-256 original bytes, save names and schema.','Original SHA cea0246e1a54afe5a3ab9d9542baa53c7cb45fc8f4e28e7872ebafefb25ba99d; six columns, no speaker/session IDs.')
for i,fn,desc in [('ctc_pdf','graves-ctc-2006.pdf','Original author-hosted ICML 2006 CTC paper.'),('ctc_text','graves-ctc-2006.txt','pdftotext -layout rendering of original CTC paper; inspected Section 3.1/3.2.'),('minds_original','minds14-official-readme.md','Official source dataset README at fixed revision; inspected zh-CN fields and Data Fields.'),('qwen_original','qwen3-vl-official-readme.md','Official Qwen model README at fixed revision; inspected image/text chat and from_pretrained API.'),('whisper_original','whisper-turbo-official-readme.md','Official OpenAI model README at fixed revision; inspected ASR and speech transcription definitions.'),('pause','pause-event.json','Actual pause record, retained unchanged.'),('classification','classification-correction.json','Coordinator classification of product card exposure and reviewer continuation; card not used as evidence.')]:artifact(i,fn,'source_snapshot',desc)
sources=[]
def repo(i,p,title,note,version=None):
 sources.append({'id':i,'kind':'repository_code','title':title,'path':p,'sha256':sha(R/p),'version':version or 'Current exact raw bytes, checked 2026-10-06','inspection_note':note,'verified':True})
for arch in ['moe','dense']:
 repo(arch+'_metrics',f'docs/selftrained/results/public-raw/{arch}/test/metrics.json',arch+' original final test aggregate','First inspected top-level keys/types. Then read /count,/split,/evaluation_complete,/expected_count,/resumed_completed_count,/checkpoint_sha256,/safe_weights_sha256,/inference_manifest_sha256,/selected_checkpoint_sha256,/teacher_forcing_used_for_generation,/thresholds,/per_task_final_reply,/stratified_final_reply,/perception/ocr,/voice_topic_continuation only. Did not read /notes. Rebuilt counts from the preserved original rows.')
 repo(arch+'_freeze',f'docs/selftrained/results/public-raw/{arch}/freeze/frozen.json',arch+' original frozen protocol','Read weight identities, /created_at,/selection,/test_once,/context,/max_new_tokens,/thresholds,/data_sha256,/code_sha256,/validation_metrics_sha256. Verified exact data/code identities and time order.')
 repo(arch+'_receipt',f'docs/selftrained/results/public-raw/{arch}/test/receipt.json',arch+' original final execution/download receipt','Read /run_id,/revision,/started_at,/finished_at,/status,/returncode,/public_export,/files. Actual public files independently fetched and checksummed at pinned revision.')
 repo(arch+'_journal',f'docs/selftrained/results/public-raw/{arch}/test/evaluation-receipt.json',arch+' original final evaluation journal receipt','Read /status,/expected_count,/completed_count,/resumed_from,/outputs_sha256. Original rows and their full raw SHA match.')
repo('evaluation','scripts/selftrained/evaluate.py','Original frozen scoring/evaluation implementation','AST located functions first. Read THRESHOLDS L39–48, score_reply L240–306, protocol_contents/validate_protocol L318–380, Generator generation/perception L383–492, summarize L495–708, actual continuation L845–921. Scoring branches and denominator construction checked; method scope statements are treated as specifications, not result verdicts. Full file SHA matches both original frozen protocols.')
repo('training','scripts/selftrained/train.py','Original train/select/export implementation','AST located functions first. Read stage_records L84–103, export_inference L235–281, validation_loss L611–628, model initialization/input split L728–764, select_and_save L882–903. Only train records update weights; validation selects best; export uses best.pt. Exact code hash matches freezes.')
repo('dataset','tiny_perceptron/selftrained/dataset.py','Original data/inference contracts','Read read_records L48–81, train_tokenizer L84–91, RecordEncoder permitted metadata and labels L108–241; tokenizer uses train messages and inference excludes final target. Full hash matches frozen protocols.')
repo('tools','tiny_perceptron/selftrained/tools.py','Original calculator executor and loop','Read CalculatorCall/parse/execute L29–89 and run_tool_loop L122–170. Executor computes requested arithmetic, same generator reads actual tool message; runtime does not substitute a final answer.')
repo('model','tiny_perceptron/selftrained/model.py','Original CTC decoder and shared model','Read SelftrainedLanguageModel L133–185, decode_ocr L285–292, LimitedAssistant L295–349. One LM receives modality embeddings; greedy CTC collapse is separate from final LM generation. Full hash matches frozen protocols.')
repo('data_manifest','docs/selftrained/v2-manifest.json','Pinned LFS data manifest','First top-key types, then /package,/records and asset counts. Verified package exact 67862431 bytes, archive SHA 0976073a3bc7c331a65cedb4c31d54f5c6e9a5014ff2443698a8e2b8cad7e78a; all 12 record-file bytes/hashes match manifest and freeze. Archive content inspected directly for splits, target lengths, fonts, public ROIs/layouts and unique recording assets.')
repo('data_archive','assets/training/selftrained-v2.tar.gz','Actual fixed LFS data archive','Read only *.jsonl required fields: /id,/group_id,/split,/task,/messages,/image,/roi,/image_layout,/audio,/supervision/{ocr_text,glyph_boxes,font_family,vision_labels,intent},/evaluation. No data generation or training data download.',version='git-lfs package revision 08761dac87a6ef360db95883d9bcd338c44fe76d; exact manifest SHA')
repo('voice_provenance','docs/selftrained/provenance/voice.json','Original voice source provenance','First top-key types, then /dataset,/config,/revision,/parquet and inference/evaluation contracts; did not use author quality/result summaries. Actual parquet bytes/hash/schema and official dataset README independently checked.')
repo('count_method','docs/selftrained/results/original-threshold-count-method/original-criterion-branches.py.txt','Original derivative threshold-count branch excerpt','Verbatim original L273–285 only. Independently reimplemented numeric comparisons. It maps unsupported_clarification to missing, unsupported and unavailable tasks, excludes tool_concept and perceptual head scores. This source supports a derivative count, not predeclaration of a complete criterion mapping.')
repo('count_provenance','docs/selftrained/results/original-threshold-count-method/provenance.json','Threshold branch extraction provenance','Checked full-source SHA and exact original line range, snippet SHA and variable contract. No original audit results or verdicts read.')
repo('natural_release','docs/natural-assistant/v4/public-release.json','Chapter 20 selected mature-model configuration','First top-key types then /selected_variant,/base_model,/asr_model only: base Qwen3-VL-2B-Instruct, ASR whisper-large-v3-turbo; did not read /reviewed or approval records.')
sources.append({'id':'audit_source','kind':'execution','title':'Fresh original-row/data/lineage audit','verified':True,'artifact_id':'audit'})
sources.append({'id':'mechanism_source','kind':'execution','title':'Actual bounded CPU mechanism checks','verified':True,'artifact_id':'mechanism'})
for i,kind,title,url,version,note,reason in [
 ('ctc_paper','paper','Connectionist Temporal Classification: Labelling Unsegmented Sequence Data with Recurrent Neural Networks','https://www.cs.toronto.edu/~graves/icml_2006.pdf','ICML 2006 author-hosted published paper','Read Sections 3.1–3.2: many-to-one B removes blanks and merges repeats; best-path decoding uses argmax at each time and is an approximation, not guaranteed best labeling. Compared directly to local decode_ocr and CPU path.','Original paper from author Alex Graves academic hosting; defines CTC collapse.'),
 ('minds_docs','official_docs','PolyAI MInDS-14 source dataset card','https://huggingface.co/datasets/PolyAI/minds14/raw/40ce77cb32a384e4d50a568e1ec39ac804019d33/README.md','revision 40ce77cb32a384e4d50a568e1ec39ac804019d33','Read zh-CN config L869–922 and Data Fields L990–998: 502 rows, address/app_error/card_issues among 14 labels; fields path,audio,transcription,english_transcription,intent_class,lang_id; no speaker/session fields. Actual parquet agrees.','Dataset owner official pinned source metadata.'),
 ('qwen_docs','official_docs','Qwen3-VL-2B-Instruct official model card','https://huggingface.co/Qwen/Qwen3-VL-2B-Instruct/raw/89644892e4d85e24eaac8bacfd4f463576704203/README.md','revision 89644892e4d85e24eaac8bacfd4f463576704203','Read repository identification and Transformers chat Quickstart L80–126; from_pretrained Qwen model, image plus text user message, model.generate. No upstream benchmark claim used.','Qwen creator official weight repository.'),
 ('whisper_docs','official_docs','Whisper large-v3-turbo official model card','https://huggingface.co/openai/whisper-large-v3-turbo/raw/41f01f3fe87f28c78e2fbf8b568835947dd65ed9/README.md','revision 41f01f3fe87f28c78e2fbf8b568835947dd65ed9','Read description L117–126 and transcription/translation distinction L208–216; ASR produces text in source language, distinct from answering a question. No quality/benchmark claim used.','OpenAI creator official weight repository.')]:
 sources.append({'id':i,'kind':kind,'title':title,'url':url,'version':version,'verified':True,'checked_original':True,'accessed_on':'2026-10-06','authority_reason':reason,'inspection_note':note})
source_map={s['id']:s for s in sources}
def ev(i,locator,supports):
 d={'source_id':i,'locator':locator,'supports':supports}
 if source_map[i].get('sha256'):d['raw_source_sha256']=source_map[i]['sha256']
 return d
claims=[]
def claim(i,kind,statement,location,evidence,scope,expected=None,observed=None,den=None,ids=None,status='verified',details=None):
 d={'id':i,'kind':kind,'statement':statement,'location':location,'status':status,'evidence':evidence,'artifact_ids':ids or ['audit'],'scope':scope}
 if kind in ['numeric','empirical','software']:
  d['verification']={'method':'executed','expected':expected or statement,'observed':observed or statement,'details':details or 'Executed independent existing-byte verification; see exact input SHA, pointers and observed output in artifacts.'}
  if kind=='numeric':d['verification']['tolerance']='Exact integer/count equality; displayed division uses Python float.'
  if kind=='empirical':d['verification']['denominators']=den or {'questions_per_architecture':3734,'split':'final test','models':2,'new_generation_runs':0}
 claims.append(d)
claim('c1','software','兩版推論權重由 validation 選定，final test 不用來訓練或挑版本。','開頭段', [ev('training','stage_records L84–103, validation_loss L611–628, select_and_save L882–903, export_inference L235–281','Train/validation split and selected-export contract.'),ev('dataset','train_tokenizer L84–91','Vocabulary uses train content.'),ev('audit_source','/architectures/{moe,dense}/best_validation_step; /training_receipts','Read original validation logs; own minima are step 1000 for both, public export identities match.')],'Only these fixed training runs and artifacts; validation loss is teacher forced, not generation capability.',observed='MoE min 0.1550097017317582, Dense min 0.1769717250097719, both step1000; all15 receipts test_used_for_selection=false.',ids=['audit','moe_validation','dense_validation','moe_validation_provenance','dense_validation_provenance','moe_public_manifest','dense_public_manifest'])
claim('c2','empirical','MoE與Dense在固定公開推論檔案與評分協定後，各完成一次3734題final test。','開頭段及完整考卷说明',[ev(a+'_freeze','/created_at,/selection,/test_once,/thresholds and identity fields','Original frozen protocol precedes execution and matches raw metrics.') for a in ['moe','dense']]+[ev(a+'_journal','/expected_count,/completed_count,/resumed_from,/outputs_sha256','3734 unique raw rows, complete journal and no resume.') for a in ['moe','dense']],'One original recorded complete final run per architecture, fixed HF pin979cdfacc588ad0536f1c64fff96f264571cf054; this audit does not independently exclude unrecorded activity.',observed='Both3734 unique test IDs and successful receipt; freeze before test; original rows/raw SHA match; all8 public-file SHA/bytes match.',ids=['audit','public_bytes','moe_rows','dense_rows'])
for j,(task,name) in enumerate([('text','有限文字與指令'),('ocr','指定區域OCR'),('vision_clothing','三類服飾'),('vision_relation','兩格位置關係'),('voice_qa','語音客服回答'),('voice_topic_continuation','真正語音後續對話'),('tool_call','真正計算器往返'),('tool_reply','已提供工具返回值'),('tool_concept','工具概念'),('tool_missing','缺少參數'),('tool_unavailable','工具未開啟'),('tool_unsupported','不支援運算')],3):
 vals={a:V['architectures'][a]['table_and_boundary_counts'][task] for a in ['moe','dense']}; den=vals['moe']['denominator']; obs='MoE '+str(vals['moe']['numerator'])+'/'+str(den)+'; Dense '+str(vals['dense']['numerator'])+'/'+str(den)
 claim('c'+str(j),'empirical',name+'的分子／分母為'+obs+'。','主表或工具邊界 details 的對應列',[ev(a+'_metrics','/per_task_final_reply/'+task+('/tool_roundtrip' if task=='tool_call' else '/semantic'),'Raw final measurement numerator and denominator; independently rebuilt from original output rows.') for a in ['moe','dense']]+[ev('evaluation','score_reply L240–306, summarize L495–595','Task scoring and question denominators verified.')], 'Fixed question-level rubric; correlated variants are not independent source assets or people. '+('Voice continuation requires actual first and final semantic/format success.' if task=='voice_topic_continuation' else 'Tool call requires correct expected request, real execution and correct returned value.' if task=='tool_call' else 'Tool reply already supplies the tool message.' if task=='tool_reply' else 'No general natural-language quality inference beyond this exact/keyword rubric.'),observed=obs,den={'scored_questions_per_architecture':den,'split':'final test','new_model_generations':0,'models':2},ids=['audit','moe_rows','dense_rows'])
claim('c15','software','真正工具往返要求正確工具與參數、真執行、真回填後回答；已提供返回值只測讀回，不可補完整往返。','主表之後兩段',[ev('evaluation','score_reply L278–297','Complete roundtrip conjunction and tool_reply scoring are different.'),ev('tools','run_tool_loop L122–170, execute_tool_call L76–89','Actual execution uses requested operands, then same generator reads returned tool message.')],'A valid/executed wrong calculator request can have a correct answer to its own returned value while failing the requested problem. Original MoE114 executions/110 returned-value matches yield0 correct full chains; Dense102/97 yield7.',observed='CPU correct arguments yield roundtrip=true; wrong arguments execute and final=true but roundtrip=false. Original chain metrics agree.',ids=['audit','mechanism'])
claim('c16','software','語音後續對話用實際第一輪生成歷史；第一輪錯即使第二輪格式正確仍不算整鏈成功。','工具與語音區分段',[ev('evaluation','main L845–921, summarize continuation L670–690','Second prompt includes first_output, not first_reference, and end_to_end_success is a conjunction.')],'Only60 existing continuation rows per architecture; not a generic memory or speaker-generalization test.',observed='All60 actual second histories per model contain the true first output; end_to_end predicate matches every raw row.',ids=['audit','moe_rows','dense_rows'])
claim('c17','concept','CTC將欄位預測的 blank／重複標籤折疊成讀字字串，與LM最後生成判準分開。','CTC反例段',[ev('ctc_paper','Sections3.1–3.2, B mapping and best-path equation(4)','CTC map and greedy decoding definition; does not guarantee maximum labeling probability.'),ev('model','decode_ocr L285–292','This implementation performs argmax, blank removal and adjacent-repeat collapse.')],'Greedy CTC is the local decoder; mature CTC definition does not prove downstream LM fidelity or unrestricted OCR.',ids=['ctc_pdf','ctc_text','mechanism'])
claim('c18','empirical','兩版CTC入口完整辨對324/324，但LM最終OCR字串為252/324與281/324。','CTC反例段',[ev(a+'_metrics','/perception/ocr and /per_task_final_reply/ocr','Distinct intermediate and final measurements.') for a in ['moe','dense']]+[ev('audit_source','/architectures/{moe,dense}/ctc_exact; /table_and_boundary_counts/ocr','Independently compared all324 original CTC prediction strings and final replies to gold.')],'Same fixed324 scored ROI questions; two different scoring objects. This supports a local downstream failure, not a theorem about OCR quality generally.',observed='CTC324/324 each, final252/324 and281/324.',den={'ocr_questions_per_architecture':324,'ocr_images':174,'source_groups':99,'models':2},ids=['audit','moe_rows','dense_rows'])
claim('c19','empirical','OCR只有12字、已提供连续1–4字ROI，Sans與Serif均已在training出現；圖片是三類服飾和已提供兩格layout。','能力材料範圍段',[ev('data_manifest','/package,/records','Exact archive and every record-file SHA checked.'),ev('data_archive','ocr-{train,validation,test}.jsonl /roi,/supervision/{ocr_text,glyph_boxes,font_family}; vision-test.jsonl /image_layout,/supervision/vision_labels','Own counts confirm vocabulary12, lengths1–4, both fonts in train/test, 3labels,2slots.')],'No automatic text-box detection, unseen font, arbitrary photo or unrestricted Chinese OCR test. Target glyph boxes fit the continuous ROI in all rows.',observed='All3splits contain12 characters, lengths1–4, Sans+Serif; allprovidedROI andtargetglyphsinside. Vision test1800 rows, label IDs0–2,2slots.',den={'ocr_test_questions':324,'ocr_training_questions':4716,'vision_clothing_questions':360,'vision_relation_questions':1440,'record_files_verified':12},ids=['audit'])
claim('c20','empirical','最後語音問題由30份同來源錄音衍生；source沒有speaker/session ID，因此沒有驗收說話者隔離泛化。','能力材料範圍段',[ev('voice_provenance','/dataset,/config,/revision,/parquet','Pinned source is PolyAI/minds14 zh-CN.'),ev('minds_docs','zh-CN config L869–922, Data Fields L990–998','Official schema has audio/transcriptions/intent/lang and no speaker/session metadata.'),ev('data_archive','voice-test.jsonl /audio,/group_id,/task,/supervision/intent','Own unique counts30assets/30groups,90QA+60continuation.')],'Recording-asset disjoint split does not establish speaker independence; repeated question variants are not30 new people. No source-data download or new speech recognition run in this audit.',observed='150testquestion rows use30wav assets for3intents; actual originalparquetSHA matches source andschema contains6columns withno speaker/sessionIDs.',den={'test_recordings':30,'test_voice_questions':150,'voice_qa_questions':90,'continuation_questions':60,'source_recordings':502},ids=['audit','voice_schema','minds_original'])
claim('c21','numeric','凍結原數值門檻含文字逐意圖80%、OCR整串80%、工具真正往返95%，兩版仍有必須獨立通過的未達門檻。','原判準段',[ev(a+'_freeze','/thresholds','Beforetest fixed values .8,.8,.95; unchanged in test aggregate.') for a in ['moe','dense']]+[ev('audit_source','/architectures/*/direct_text_voice_threshold_failures and /table_and_boundary_counts/tool_call','Own rate comparisons show clear task-specific failures independent of total score.')],'Project-defined finite acceptance thresholds; no external general capability guarantee. At least true toolroundtrip failure suffices to refute passing all requirements.',observed='Both toolroundtrip0/276 and7/276 below.95; several textintent and all6voiceintent strata below.8; MoE OCR252/324 below.8.',ids=['audit'])
claim('c22','numeric','MoE有15項、Dense有12項「原數值判準」未達。','原判準段句子 MoE仍有15項、Dense有12項',[ev('count_method','Original excerpt L273–285','Derivative numeric-count method is reproducible; maps one unsupported_clarification threshold to3tooltasks.'),ev('count_provenance','/scope,/variable_contract','Archived extraction explicitly does not establish full criterion mapping as predeclared.'),ev('audit_source','/architectures/{moe,dense}/derived_threshold_count and derived_threshold_failures','Own branch reconstruction produces15/12 without reading prior findings.')],'Counts are reproducible under this derivative grouping, but frozen protocol lists8 threshold values and does not enumerate the full counted mapping. Calling the15/12 a pre-existing original criterion count lacks a verified predeclaration source.',observed='Derivative counts15/12 match numerically; source does not establish the counted full mapping as originally declared.',status='unresolved',ids=['audit'],details='This is a support-range issue, not incorrect addition: counting includes tool_missing and tool_unavailable at unsupported_clarification=.8 while excludes tool_concept. No prior complete mapping in frozen protocol was supplied or located.')
claim('c23','numeric','人工算例按題合計是2/3，每類等權重是1/2；改同類題數會改前者比重。','Python fence及之後段落',[ev('mechanism_source','/actual_section_python_fence,/means','Actually executed exact current section fence,12/18 and(1+0)/2.')],'Artificial transparent arithmetic; none of these values is a model score. Task-weighted aggregation only has this meaning when task boundaries and weights are explicit.',observed='by_question=0.6666666666666666; by_task=0.5.',ids=['mechanism'])
claim('c24','software','訓練、公開下載與最後評測完成，與全部能力通過是不同結論；本模型從隨機元件分階段訓練。','原判準段及結尾主線',[ev('training','main L728–764; stage_records and export_inference','Initial model constructed locally; subsequent sources restricted to own checkpoint schema.'),ev('model','LimitedAssistant L295–302','Shared LM plus custom encoders constructed as neural modules.'),ev('audit_source','/training_receipts and /architectures/*','All15 completed raw training receipts retain random origin; final public bytes and tests complete, toolcriterionfails.')],'Recorded execution/lineage of this pipeline; no retraining or capability upgrade was performed in the review. Completion does not logically satisfy unrelated measured thresholds.',observed='15 originalcompletedtrainingreceipts,2 completedtestjournals,all8anonymousfixedfiles match; both true-toolrate below95%.',ids=['audit','public_bytes'])
claim('c25','concept','第20章接手Qwen圖文權重，由Whisper做語音轉寫，是成熟模型應用，不是本MoE接續訓練。','結尾第20章導覽',[ev('qwen_docs','Quickstart L80–126','Qwen official pretrained model consumes image/text andgenerateschat.'),ev('whisper_docs','Description L117–126; transcription L208–216','Whisper is pretrainedASR; producestranscribedtext.'),ev('natural_release','/selected_variant,/base_model,/asr_model','Current chapter20config selectsbase andofficialQwen/Whisperpins, independentofthefromscratchMoE.')],'Navigation/configuration claim only; this report does not audit chapter20 ability scores or establish upstream benchmarks.',ids=['qwen_original','whisper_original'])
report={'schema_version':1,'review_stage':'technical','lesson_id':'19.12','source':'course/chapters/19.md#19.12','reviewer_task':'/root/p6_fact_19_12','reviewer_context':'fresh','source_sha256':V['section_sha256'],'figure_sha256':{},'verdict':'revise','claims':claims,'sources':sources,'artifacts':artifacts,'issues':[{'claim_id':'c22','status':'unresolved','details':'15/12 numerically reproduce a derivative count, but full predeclared original criterion mapping is not established. The frozen source contains8 values; the count-method maps unsupported_clarification onto missing/unavailable tasks. This can make the acceptance unit sound more originally specified than evidence proves.','suggestion':'Remove the15/12 count clause and state directly that both fail required task thresholds, with true toolroundtrip below95% as a concrete example; keep separate completion and capability conclusions.'}],'checks':{'factual_accuracy':{'status':'revise','details':'All substantive table, chain, scope and completion claims verified except c22 original-criterion attribution.','claim_ids':[c['id'] for c in claims]},'numeric_verification':{'status':'revise','details':'7468 original rows rescored; all12 task numerators/denominators, CTC and arithmetic match.15/12 is correct only under documented derivative counting.','claim_ids':['c'+str(i) for i in list(range(3,15))+[18,21,22,23]]},'figure_consistency':{'status':'not_applicable','details':'19.12 contains no image or SVG reference.','claim_ids':[]},'source_verification':{'status':'revise','details':'Original bytes, method code and official original sources checked with SHA and locators; full predeclared criterion mapping for c22 remains unsupported.','claim_ids':['c1','c2','c17','c19','c20','c21','c22','c24','c25']},'limitations':{'status':'revise','details':'Finite materials, correlated questions, recordedexecution andcapability scope are separated. c22 requires limitingthederivativecountattribution.','claim_ids':['c15','c16','c18','c19','c20','c21','c22','c24','c25']}},'inspection_record':{'actually_read_course':['course/chapters/19.md#19.12','course/chapters/20.md introduction and20.1/20.2 navigation configuration'],'initial_frozen_input_artifact_id':'initial_chapter','source_hash_definition':'Raw UTF-8 bytes from19.12heading to next##; no normalization.','evidence_policy':'Top-key/types before named measurement/method/provenance pointers; old reader/technical conclusions and aggregate notes/review/scope_correction not read. Productmodelcardreadwaspausedandclassifiedasclaimunderreview; card never usedas evidence.','pause_and_classification_artifact_ids':['pause','classification'],'retraining':False,'new_heldout_generation':False,'paid_calls':False}}
out=json.dumps(report,ensure_ascii=False,indent=2)+'\n';(R/'docs/technical-reviews/19.12.json').write_text(out);(A/'initial-report.json').write_text(out)
print('new independent revise report written; initial preserved',len(claims),'claims')
