from pathlib import Path
import hashlib,json
out=Path(__file__).resolve().parent;root=out.parents[3]
v=json.loads((out/'verification.json').read_text());add=json.loads((out/'additional-result.json').read_text());render=json.loads((out/'render-result.json').read_text())
def sha(path):return hashlib.sha256(Path(path).read_bytes()).hexdigest()
def rel(path):return str(Path(path).relative_to(root))
artifacts=[]
def artifact(identifier,path,kind,description,**extra):
    path=out/path
    artifacts.append(dict(id=identifier,kind=kind,path=rel(path),sha256=sha(path),description=description,**extra))
env=v['environment']
artifact('a_check','verification.json','execution','有界CPU：固定素材、原碼AST定位、原始CPU JSON pointers、模態形狀、語音head、token解碼、真history、archive與訓練原紀錄指紋。',command='/workspace/tiny-perceptron-vlm/.venv/bin/python docs/technical-reviews/artifacts/p6-19.6/check.py',result='exit 0；四個公開輸入前處理與原prompt_ids相符，原token IDs解碼吻合，音訊head確實錯分。沒有訓練或完整evaluation。',environment=env)
artifact('a_add','additional-result.json','execution','原來源錄音計數、兩個字型指紋、字卡像素重建、官方Fashion源hash及各訓練階段真command。',command='/workspace/tiny-perceptron-vlm/.venv/bin/python docs/technical-reviews/artifacts/p6-19.6/additional.py',result='exit 0；107原錄音分62/15/30，496份增強不算新錄音，OCR像素重建完全相同，原始預訓練argv未載入外部checkpoint。',environment=env)
artifact('a_render','render-result.json','execution','三張SVG在640與360 viewport的實際Chromium渲染紀錄。',command='python3 docs/technical-reviews/artifacts/p6-19.6/render.py',result='exit 0；六張PNG已真實render且逐一view_image查看，圖與正文/素材/原碼一致。',environment=render['environment'])
artifact('a_inspect','inspection.md','source_snapshot','本人實際閱讀、圖像觀察、支持範圍、工具失敗與版本差異記錄。')
artifact('a_rows','selected-fixed-records.json','source_snapshot','來自manifest吻合之原始JSONL的必要原record：三張素材、公開聲音、兩字體train/val/test樣本；包含原始supervision作查核而未作推論輸入。')
artifact('a_stage','public-model-stage-provenance.json','source_snapshot','最後公開native/weighted模型之原始freeze、origin、stage_history及真argv指標；只讀具名原始provenance。')
for i,f in enumerate(['check.py','additional.py','render.py','check.stdout.txt','check.stderr.txt','additional.stdout.txt','additional.stderr.txt','render.stdout.txt','render.stderr.txt']):
    artifact('a_tool_'+str(i),f,'code' if f.endswith('.py') else 'source_snapshot','本人檢查程式或當次原始命令輸出；失敗嘗試另保存。')
for name in ['fashion','ocr','voice']:
    for width in [640,360]:artifact('a_'+name+'_'+str(width),'renders/'+f'{name}-{width}.png','figure_render',f'{name}圖在{width}px viewport的實際render；已查看素材位置、字樣、箭頭、範圍及尺度。')
for i,path in enumerate(sorted((out/'inputs').rglob('*'))):
    if path.is_file():artifact('a_input_'+str(i),path.relative_to(out),'source_snapshot','原始輸入全檔保留與SHA；實際閱讀欄位/函式見verification.json、additional-result.json及inspection.md。')
for i,path in enumerate(sorted((out/'assets').rglob('*'))):
    if path.is_file():artifact('a_media_'+str(i),path.relative_to(out),'source_snapshot','已查核原素材、來源像素小片或字卡重建；原件與副本SHA/像素相符。')
for i,path in enumerate(sorted((out/'official').glob('*'))):
    if path.is_file():artifact('a_official_'+str(i),path.relative_to(out),'source_snapshot','親自取得並閱讀的原始官方來源，或含URL/version/SHA與實際HTTP結果的fetch紀錄。')

sources=[]
def code(identifier,path,note):
    p=out/'inputs'/path
    sources.append(dict(id=identifier,kind='repository_code',title=path,path=rel(p),sha256=sha(p),version='2026-10-06 frozen working-tree source; original SHA and AST ranges in verification.json',verified=True,inspection_note=note))
code('s_data','tiny_perceptron/selftrained/dataset.py','讀constants、RecordEncoder._modality 118–172、encode 174–220、batch 222–235；不輸入supervision，保留歷史，ROI/image slots及完整波形前處理。')
code('s_model','tiny_perceptron/selftrained/model.py','AST後讀VisionEncoder 188–214、OCREncoder 217–244、AudioEncoder 247–282、LimitedAssistant 295–419；避開description結果評語。')
code('s_infer','tiny_perceptron/selftrained/inference.py','_public_history 139–173、attach_public_metadata 176–212、InferenceAssistant 218–328、ChatSession 331–342；檢查完整safe權重及合法公開prompt。')
code('s_train','scripts/selftrained/train.py','PERCEPTION_BRIDGE_PREFIXES 48–61、set_trainable 284–296、初始化及own-stage載入分支約723–789；只讀方法，沒有跑訓練。')
code('s_vision','scripts/selftrained/prepare_vision_ocr.py','原來源revision/hash/class mapping 31–52、acquire95–129、scene生產167–293、draw_line313–326、OCR框與字卡329–355；沒有執行prepare/download/train。')
code('s_voice','scripts/selftrained/prepare_voice.py','原source revision及SELECTED35–74、source parquet讀取與audit308–430；原transcription只用於資料分組，非推論ASR路徑。')
code('s_augment_ocr','scripts/selftrained/augment_ocr_v2.py','style55–83、augment150–191；兩個訓練font family及固定hash，不讀作者result摘要。')
code('s_augment_voice','scripts/selftrained/augment_voice_v2.py','resample_speed138–152、transform165–215、原parent/asset/record交接316–355；增強不是新增獨立錄音。')
code('s_chat','scripts/selftrained/chat.py','pixel_roi27–34、parser37–64、main67–110：從純messages輸入生成後save實際continued messages。')
code('s_append','docs/selftrained/examples/v2/append-voice-continuation.py','整支單純history append腳本；只讀保存的真history，加入唯一user請求。')
code('s_mel','tiny_perceptron/multimodal.py','mel_filter_bank49–59、log_mel62–69：mel三角濾波、功率谱取log，STFT窗隨時間滑動。')
code('s_eval','scripts/selftrained/evaluate.py','AST定位Generator.perception460–492：獨立head的argmax/CTC計分來源，並非最終文字回答。')
def official(identifier,title,url,version,note):
    sources.append(dict(id=identifier,kind='official_source',title=title,url=url,version=version,verified=True,checked_original=True,accessed_on='2026-10-06',authority_reason='原作者/維護者官方上游原始文件或原碼，已直接取回與閱讀定位內容。',inspection_note=note))
official('s_softmax','PyTorch original functional.softmax','https://raw.githubusercontent.com/pytorch/pytorch/v2.9.0/torch/nn/functional.py','upstream v2.9.0; installed CPU torch 2.14.1+cpu tested separately','保存pytorch-functional-v2.9.0.py；lines2096–2136：exp(x_i)/sum_j exp(x_j)，[0,1]並沿dim和為1。web docs403，因此改核實原上游碼，沒有把其版本說成installed版本。')
official('s_stft','PyTorch original functional.stft','https://raw.githubusercontent.com/pytorch/pytorch/v2.9.0/torch/functional.py','upstream v2.9.0; installed CPU torch 2.14.1+cpu tested separately','保存pytorch-torch-functional-v2.9.0.py；lines508–595：隨時間滑動重疊窗及變動頻率成分、hop/center/window契約。只支持STFT方法，40 bands與16token由專案原碼及CPU檢查支持。')
official('s_fashion','Fashion-MNIST original README and embedded MIT LICENSE','https://raw.githubusercontent.com/zalandoresearch/fashion-mnist/b2617bb6d3ffa2e429640350f613e3291e10b141/README.md','commit b2617bb6d3ffa2e429640350f613e3291e10b141','讀README labels表lines69/76/77、Citation258–270、MIT LICENSE275–283，另直接取得同revision的LICENSE並讀全內容；來源像素檔hash對上官方固定producer pins。')
official('s_noto','Noto CJK original SIL OFL 1.1','https://raw.githubusercontent.com/notofonts/noto-cjk/f8d157532fbfaeda587e826d4cd5b21a49186f7c/Sans/LICENSE','commit f8d157532fbfaeda587e826d4cd5b21a49186f7c; SIL OFL 1.1 (2007-02-26)','直接讀Sans及同revision Serif/LICENSE；兩份相同SHA6a73f954...；許可1.1與Permission & Conditions允許使用/嵌入，字卡文件不繼承字型license。實際font檔hash與producer pins吻合。')
official('s_minds','PolyAI MInDS-14 fixed original dataset card','https://huggingface.co/datasets/PolyAI/minds14/raw/40ce77cb32a384e4d50a568e1ec39ac804019d33/README.md','commit 40ce77cb32a384e4d50a568e1ec39ac804019d33','讀front metadata22–23 cc-by-4.0、zh-CN schema約870–927：8kHz、source intents1/2/6及lang13、502 rows；描述933–934 banking intent資料；Data Fields990–1000無speaker/session。原始parquet schema和所用WAV bytes另已CPU親查；不把source transcript當人工gold。')
sources.append(dict(id='s_exec',kind='execution',title='Fresh bounded CPU input/head/history verification',verified=True,artifact_id='a_check'))
sources.append(dict(id='s_add',kind='execution',title='Fresh original-source counting and pixel reconstruction',verified=True,artifact_id='a_add'))
sources.append(dict(id='s_mean',kind='derivation',title='無位置資訊的平均摘要在左右交換下不變',verified=True,details='給物件特徵a,b且不含位置：m=(a+b)/2。交換後m′=(b+a)/2=m（向量加法交換律），所以兩種左右配置交給同一確定性解碼器時不能由該摘要區分。實算a=[1,0,0],b=[0,1,0]，兩次均[0.5,0.5,0]。只有當位置已進入特徵或額外保留時，平均摘要可能仍含位置；本節講的是「只留下有褲子有包」的摘要。'))

claims=[]
def claim(identifier,kind,statement,location,scope,evidence,ids,expected=None,observed=None,details=None,denominators=None):
    c=dict(id=identifier,kind=kind,statement=statement,location=location,status='verified',scope=scope,evidence=[dict(source_id=s,locator=l,supports=support) for s,l,support in evidence],artifact_ids=ids)
    if kind!='concept':
        c['verification']=dict(method='executed',expected=expected,observed=observed,details=details)
        if kind=='numeric':c['verification']['tolerance']='數量、座標、hash與像素要求精確相等；浮點logits僅用最大值判別，不要求跨版本逐位相等。'
        if denominators:c['verification']['denominators']=denominators
    claims.append(c)
claim('c1','empirical','公開CPU真商品圖的兩個模型回答是「這是短靴。」與「左邊是褲子。」','首段、fashion圖中兩次CPU回答','只核對這兩個固定公開例；不把兩個正確回答外推成任意照片或完整test能力。',[('s_exec','verification.json /public_cpu/vision_clothing-1、vision_relation-1；/fashion_pixel_matches','原argv、stdout answer/generated_ids和原28x28来源标签/像素共同支持兩次公開實測。')],['a_check','a_rows','a_fashion_640','a_fashion_360'],expected='短靴例回答這是短靴；兩格圖左褲右包且問左邊時回答褲子。',observed='原stdout精確吻合；原generated_ids使用同tokenizer解碼吻合；來源labels9、1、8，畫面及像素patch都相符。',details='原stdout SHA對上原result；不讀saved_GPU_validation_answer或author比較欄位。',denominators={'public_examples':2,'generation_per_example':1,'model_sha256':v['public_cpu']['vision_clothing-1']['model_sha256']})
claim('c2','software','服飾只涵蓋褲子、包、短靴三類；兩格由公開幾何座標裁切，座標沒有類別答案。','第三段「服飾入口只學…」','固定Fashion灰階場景和兩格介面；不是自主物件偵測。',[('s_vision','FASHION_CLASSES31–52，prepare_vision167–293','local0/1/2映射original1/8/9及真場景來源。'),('s_data','RecordEncoder._modality151–169','只從slots取像素和centers，supervision不進payload。'),('s_infer','_public_history139–173','公開layout只接受axis和兩個pixel boxes。')],['a_check','a_rows'],expected='輸入two public cells且資料class僅0/1/2；公開prompt與layout沒有gold labels。',observed='前處理[2,1,32,32]、centers[[.25,.5],[.75,.5]]；三份vision JSONL非blank label僅0/1/2；prompt keys僅公開輸入。',details='已manifest驗九份模態JSONL和四素材；公開argv/stdout prompt和實際encoder逐ID相符。')
claim('c3','software','圖片特徵、整組soft scores、格位中心及slot順序一起接成兩個圖片向量交給同一文字核心。','第四段「圖片入口算出…」','檢查表示保留位置的機制；不保證模型已學會每一次搬移後正確答題。',[('s_model','VisionEncoder207–214；LimitedAssistant._embeddings308–355','features+symbol_projection(softmax)+coordinates+slot_position並替換兩個reserved slots。')],['a_check'],expected='2個圖片slots，pixel和coordinate tensor都參與token。',observed='公開模型tokens[2,256]，logits[2,3]，reserved_slots=2；原碼未把兩格先平均掉。',details='使用已驗safe模型跑bounded encoder.forward，核對形狀並比較真prompt_ids。')
claim('c4','numeric','只留下不含位置的「有褲子、有包」平均摘要不足以分辨左右。','第四段最後一句','僅不含位置的物件特徵平均；若feature本來含座標則不能套用此不變性。',[('s_mean','m=(a+b)/2=(b+a)/2；追加CPU positionless_mean','交換左右後摘要仍相同，因此不能由摘要區分兩個相反位置。')],['a_add'],expected='[1,0,0]和[0,1,0]交换後平均完全相同。',observed='forward=swapped=[0.5,0.5,0.0]。',details='透明代入算例獨立執行；不當作模型accuracy測試。')
claim('c5','empirical','公开OCR原图ROI [18,50,90,86]只包含下方「大小」，该次CPU生成「大小」。','第五段、OCR图及其图注','固定示範字卡和caller ROI；不能推出任意OCR品質。',[('s_exec','/public_cpu/ocr-1；/payloads/ocr-1','原argv/actual generated IDs、ROI以及字卡原像素相符。'),('s_add','additional-result.json /ocr_pixels_recreated_exactly','指定Serif24字型、原兩行字與glyph boxes精確重建原卡。')],['a_check','a_add','a_rows','a_ocr_640','a_ocr_360'],expected='ROI避开口大口且讀大小，框線按與圖像相同2.5比例變換。',observed='原generated_ids解碼為大小；原字卡像素重建完全相同；綠框x85/y238/w180/h90對上原ROI。',details='讀原source PNG、raw label/glyph boxes、原stdout，不把ROI當字形標註送入模型。',denominators={'public_examples':1,'characters':2,'source_image_pixels':'192x96'})
claim('c6','software','OCR先公開ROI裁切、等比縮放至高32且右側補白，再保留由左到右的32個輸入向量。','OCR圖後第一段','本實作固定canvas [1,32,128]及sequence32；裁切只決定可見像素，不執行字形辨識。',[('s_data','RecordEncoder._modality132–149','pixel ROI裁切、按幾何定寬、bilinear resize、白色letterbox。'),('s_model','OCREncoder236–244','按width維排列CNN列特徵，GRU後接column_position和共享core。')],['a_check'],expected='36高72寬ROI縮成32高64寬，補到128寬並出32 tokens。',observed='payload[1,32,128]；resized_width64；右64column全1；tokens[32,256]、head[32,13]、reserved32。',details='完整使用原RecordEncoder及已驗模型OCR encoder forward；對shape和白邊做CPU assert。')
claim('c7','numeric','OCR字表12字，有限ROI是1–4字格；Sans與Serif兩種字體都已出現在訓練。','OCR字表與字體段','只支持該字表與已見字體；test可檢查字串/素材/版面，不能宣稱unseen-font。',[('s_data','OCR_CHARACTERS15–17','固定字表大小。'),('s_augment_ocr','style55–83','V2訓練style含兩個family。'),('s_add','additional-result.json /font_sha256','实际两个font文件SHA吻合固定producer pins。')],['a_check','a_add','a_rows'],expected='12個指定字、1–4字長，train含Sans/Serif。',observed='ocr train4716行：Sans2749/Serif1967；val232、test324行；各split目標長1–4且字集合正好12；test留出字串查核。',details='計數manifest匹配的原JSONL /supervision/ocr_text與font_family，不使用歷史condition=unseen_font作V2證據。')
claim('c8','software','公開語音輸入是完整真WAV加「請回答這段語音問題。」；逐字稿和意圖標籤未進prompt，推論未載入ASR。','聲音公開例段、最後訓練段','來源資料有既有transcript欄位且準備資料會用於分組；本claim只說模型聲音推論路徑並未先做ASR。',[('s_data','_modality118–131及encode174–220','直接read WAV→logmel；metadata與conversation決定prompt，沒有讀transcription。'),('s_infer','InferenceAssistant218–313','只載完整本模型safe tensors，public history不接受label/transcript欄位。'),('s_minds','zh-CN schema870–927與Data Fields990–1000','來源確為8kHz中文銀行intent音訊資料，speaker/session欄位不存在。')],['a_check','a_rows'],expected='公開user文字只說請回答語音問題，真音訊在user index3，無ASR/text target。',observed='原argv與raw prompt確實如此；WAV SHA與original APP_ERROR parquet row bytes精確相同；parquet source intent_class2/lang13，local intent1。',details='原來源parquet固定SHAcea0246e…；只讀path/audio/intent/lang而不把source transcript當人工gold；CPU音訊數63488。')
claim('c9','software','固定完整log-mel产生按时间排列的40頻帶；語音入口卷積/GRU後出16個有順序的區間向量。','log-mel段及voice圖上半段','仅该whole-wave transform和有序pooled feature机制；不保证一般语音理解或未见长录音外推。',[('s_mel','log_mel62–69及mel_filter_bank49–59','功率STFT经40band mel filters取log；参数由RecordEncoder给定。'),('s_stft','upstream functional.stft508–595','重疊時間窗保留時變頻率分量。'),('s_model','AudioEncoder263–282','時間卷積和bidirectional GRU後adaptive_avg_pool到16，加入time_position。')],['a_check'],expected='完整7.936s/8kHz錄音→[time,40]→[16,width]。',observed='63488samples、794frames、40bands；tokens[16,256]且reserved16。',details='实际原WAV经原函数执行，32msFFT/10ms hop，没有裁掉真实录音；window center边界padding不算舍弃声音。')
claim('c10','concept','本節soft bridge保留每類/字形整組softmax分數比例再投影；没有先argmax分類再查固定回答表。','三種入口soft bridge段、voice圖接頭標籤','soft bridge是此專案接頭的描述名稱；分數不是已校準的正確機率，沒有外推為特定研究方法效益。',[('s_softmax','upstream functional.softmax2096–2136','公式exp/sumexp支持整組候選比例，而非取argmax。'),('s_model','VisionEncoder211；OCREncoder243；AudioEncoder281；LimitedAssistant.generate384–419','三條symbol_projection(logits.softmax(-1))與感知features一起進共享自回歸文字生成。')],['a_check'],expected=None,observed=None,details=None)
claim('c11','empirical','公開App例最後文字回答正確，但獨立感知分類頭選錯類別。','soft bridge段最後一句','單公開樣本，僅依原source意圖與專案短回答目標查核；不能換成整體accuracy或證明分類頭無用。',[('s_exec','verification.json /payloads/voice_qa-1；/voice_expected_intent_id；/public_cpu/voice_qa-1','实际同hash公開權重encoder head forward與原raw text generation分開對照。'),('s_eval','Generator.perception460–492','分類指標取head argmax而非從最後文字反推。')],['a_check','a_rows'],expected='source APP_ERROR localid1，最後回答App提示；head最大score為其他類。',observed='head logits[-1.39172494,.82449245,.89152932]，argmax2=card_issues；原stdout「先檢查網路並重新啟動App，仍失敗再詢問官方客服。」與source target相符。',details='只新增一個有界CPU head forward，權重SHA與原CPU stdout一致；分開記模型生成和獨立head。',denominators={'public_audio_examples':1,'head_classes':3,'independent_encoder_forwards':1})
claim('c12','empirical','公開CPU續聊第一輪生成一句App提示，第二輪沿用該真回答並生成兩點改寫。','續聊表格及其後段','核對這一次真history鏈；不由保存功能推斷所有續聊都能成功。',[('s_exec','verification.json /public_cpu/voice_topic_continuation-1、-3；/history_verified','first stdout.messages精確等於second argv及generated prompt的前綴；音訊保留在原index3。'),('s_chat','main67–110','history-output保存result messages。'),('s_append','原append腳本全檔','只從真歷史檔讀assistant，再加入user新要求。'),('s_infer','reply315–328；ChatSession338–342','continued加真trace.final_output，不用教材答案替換。')],['a_check'],expected='原第一輪回答及原音訊留在歷史；下一輪只添請將剛才的答覆改成兩點。',observed='原first stdout與next argv/prompt前綴精確一致；第2輪生成1.先檢查網路並重新啟動App。/2.仍失敗再詢問官方客服。；兩輪原tokens解碼吻合。',details='檢查原argv、result stdout SHA、raw messages/生成ids並使用真encoder比對；第二輪argv沒有新--audio。',denominators={'independent_audio_examples':1,'generated_turns':2,'history_chain':1})
claim('c13','software','先各別訓練感知入口，再joint固定骨幹/分類頭而更新文字核心與接頭；所有權重沿用隨機初始化的本專案鏈。','最後訓練段','原紀錄與原碼支持from-scratch權重provenance和freeze契約；此審閱未重新訓練，也不把metadata當品質證明。',[('s_train','PERCEPTION_BRIDGE_PREFIXES48–61、set_trainable284–296、main約723–789','新LimitedAssistant隨機nn初始化；僅載own schema stage checkpoints；joint凍結感知head/骨幹而允許core及接頭。'),('s_model','各nn constructor188–302','不存在from_pretrained/ASR權重入口。'),('s_add','additional-result.json /stage_commands；原native/weighted stage provenance','root pretrain argv無init/resume，後續階段載own checkpoint；公開後續native/weighted同樣freeze。')],['a_check','a_add','a_stage'],expected='vision/ocr/audio分階段，joint freeze head與骨幹；origin all-neural-weights-random。',observed='兩架構原stage順序及各原execution符合；兩架構joint freeze true；小模型set_trainable實際assert固定head/骨幹並保留core/bridge；公開safe origin同random種子鏈。',details='引用原requested完成紀錄而不是重訓；stage init/checkpoint provenance和实际参数requires_grad分开查。')
claim('c14','software','三張真素材的服飾來源是Fashion-MNIST，字卡由本專案用Noto CJK渲染；对应MIT與SIL OFL1.1來源聲明正確。','details素材來源段','仅核實原像素/字型來源和许可证名称，不对第三方任意重发行给出法律结论。',[('s_fashion','labels69/76/77；Citation258–270；License275–283','Han Xiao/Kashif Rasul/Roland Vollgraf、2017 Zalando、MIT及三label。'),('s_noto','兩份原LICENSE title及Permission & Conditions','Noto CJK TC所用两font files的SIL OFL1.1。'),('s_vision','acquire95–129与draw_line313–326','固定源hash、来源场景合成与项目字卡渲染。')],['a_check','a_add','a_rows'],expected='原Fashion像素未经替代，图只嵌入三真PNG；字型源和OFL匹配。',observed='Fashion三个28x28 patch逐像素吻合固定来源index，sourcegz SHA匹配官方producer pins；Serif24完整卡精确重建，两font SHA正确；SVG嵌入3PNG原bytes相同。',details='直接读取官方固定revision README/许可证，archive原metadata留存；cache notice不作为证据。')
claim('c15','numeric','PolyAI MInDS-14 zh-CN来源采CC BY4.0；107段来源錄音按62/15/30分開且無speaker ID可作跨說話者保證。','details語音來源段','數量是原錄音不是人數；同一源107录音、30test，不宣称speaker-independent或generic ASR/TTS。',[('s_minds','card front22–23，zh-CN schema870–927及Data Fields990–1000','license cc-by-4.0、中文8kHz source columns无speaker ID。'),('s_add','additional-result.json /voice及/original_source_recordings_total','去除derivative并验证原WAV SHA在固定original parquet；不是按processed files算人数。'),('s_augment_voice','parent/record交接316–355','496训练衍生资产各对应已有parent，不增加独立人类录音。')],['a_check','a_add'],expected='107=62+15+30原来源录音，source无speaker字段。',observed='original train62、validation15、test30；train另496derived audio files，共processed603；parquet columns path/audio/transcription/english_transcription/intent_class/lang_id。',details='原archive包SHA/size及各voice JSONL hash吻合manifest；以source bytes哈希和augmentation父素材核对。')
claim('c16','software','三張圖的像素、ROI、位置、16向量示意、soft接頭、共享生成與真歷史流程均與正文及原碼一致。','三張引用SVG全圖、alt和標籤','波形/色塊明示為流程示意；不當作音訊波形實測或模型性能可視化。',[('s_exec','verification.json /figures；/payloads；/history_verified','fashion与OCR内嵌bytes和原素材一致，slot/ROI位置和流程对应真实函数。'),('s_model','AudioEncoder263–282及LimitedAssistant308–419','16區間vector與soft scores接入共享core。')],['a_check','a_render','a_inspect','a_fashion_640','a_fashion_360','a_ocr_640','a_ocr_360','a_voice_640','a_voice_360'],expected='640/360真render，素材/綠框/箭頭/16blocks/回答与正文一致。',observed='六张图全部实际view；无素材替换、左右倒置或OCR框位不符；voice图清楚标示schematic。',details='Chromium/Playwright实际生成PNG；不是只查SVG文字；具体观察记录在inspection.md。')
claim('c17','software','这些入口只支持有限类、指定框和三种银行需求的短文字提示；不宣称自动检测、未知字体、通用听写/语音输出或实际账户操作。','入口範圍段、OCR字體段、logmel段、最後範圍段','没有本节之外的能力推断；原test aggregate只用于确认文字与head分开计分，不用于追加成功宣告。',[('s_vision','FASHION_CLASSES和public scene boxes','三类和几何预设。'),('s_voice','SELECTED及ANSWERS45–74','仅地址/App/卡片三类提示，不执行银行账户API。'),('s_data','OCR_CHARACTERS及_modality','指定ROI而没有OCR locator。'),('s_infer','reply267–328','输出是共享核心文字生成而非语音合成。')],['a_check','a_add'],expected='有限任务和公开几何/字体/字表，测量最终文字与head分别记录。',observed='data/encoder/API范围吻合；原dense/moe test aggregates分别记perception与final generation；source speaker metadata缺失且本节主动保留限制。',details='没有重跑aggregate evaluation，不把已有completion当所有能力达标；这里只支持本节明确的有限接口与示例。')

for c in claims:
    if c['id']=='c12':
        c['artifact_ids'].append('a_add')
        c['evidence'].append(dict(source_id='s_add',locator='additional-result.json /history_token_checks/voice_topic_continuation-1、-3',supports='兩輪都用原encoder逐ID重算prompt並用原tokenizer解碼實際生成IDs，與各自raw stdout精確相符；safe model hash也相同。'))
report=dict(schema_version=1,review_stage='technical',lesson_id='19.6',source='course/chapters/19.md#19.6',reviewer_task='/root/p6_fact_19_6',reviewer_context='fresh',source_sha256=v['section_sha256'],figure_sha256={f'course/figures/p6-19-modal-{n}.svg':v['figures'][n]['sha256'] for n in ['fashion','ocr','voice']},verdict='pass',claims=claims,sources=sources,artifacts=artifacts,issues=[])
report['read_scope']='19.6正文及其3圖；必要AST定位的实现和固定原始资料；两份方法与checker。未读旧reader/technical reports、作者额外结果摘要、notes/review/scope_correction字段。实际pointers、冻结整章版本及来源SHA见永久artifact。'
report['checks']={
 'factual_accuracy':{'status':'pass','details':'逐主張核對公開原始stdout/token IDs、入口與共享core接口、真history、分類頭、凍結與隨機來源鏈；未用作者勝敗解釋。','claim_ids':[c['id'] for c in claims]},
 'numeric_verification':{'status':'pass','details':'CPU實算slots2/32/16、logmel40、ROI64宽padding、12字/1–4長與兩訓練字體；107原錄音62/15/30另排除496增強；單例head錯分與最終文字獨立查核。','claim_ids':['c1','c4','c5','c7','c11','c12','c15']},
 'figure_consistency':{'status':'pass','details':'三圖6份640/360 Chromium PNG已全部实际查看；原embedded bytes/pixels匹配，左右與ROI2.5倍變換正確，voice16blocks與schematic聲明及箭頭吻合。','claim_ids':['c1','c5','c16']},
 'source_verification':{'status':'pass','details':'原官方固定revision Fashion MIT/作者/label、Noto OFL1.1、MInDS CC-BY4.0/schema親讀；PyTorch web403改讀上游v2.9.0原碼，實際CPU版本2.14.1+cpu另驗。固定archive和每个实际data/asset SHA獨立核對。','claim_ids':['c2','c8','c9','c10','c14','c15']},
 'limitations':{'status':'pass','details':'逐claim保留支持範圍：有限三服飾/12字/兩已見字體/三銀行需求，公开图和录音分别属于固定examples；no speaker identity、schematic波形、head與文字分開，未外推至universal ASR/TTS/自主检测。','claim_ids':[c['id'] for c in claims]}}
(root/'docs/technical-reviews/19.6.json').write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n')
print('wrote own fresh review: 19.6 pass; claims',len(claims),'sources',len(sources),'artifacts',len(artifacts))
