from build_report import *
BASE=M['baseline_commit']; WD=ROOT/'reviewer-work/technical-learning'; ED=WD/'evidence'
def sha(p):return hashlib.sha256(pathlib.Path(p).read_bytes()).hexdigest()
assigned=M['groups']['learning']['pages'];assert len(pages)==len(assigned)==79;assert {p['page_id'] for p in pages}==set(assigned)
ordered=[next(p for p in pages if p['page_id']==pid) for pid in assigned]
for p in ordered:
 s=(ROOT/'freeze/sources'/f"{p['page_id']}.md").read_text();assert p['source_sha256']==sha(ROOT/'freeze/sources'/f"{p['page_id']}.md")
 for q in p['quoted_basis']:assert q['quote'] in s
 p['checks']['short_program_execution']='未逐頁執行；固定算例依正文／相稱手算核查。固定logits與已存ID另有一個無訓練核算，見execution_scope。'
 if p['page_id'] in ['5.4','6.5']:p['source_judgment']+=' 完整英文名稱有可選小補，見issues；不影响已教機制。'
# 原始JSON只取baseline內容，不取review結論。逐份列實際回查範圍和分母。
specs={
 'text_foundation':(['5.1','5.7','5.8','5.9','5.13'],['results.data','results.training','results.before/after.validation','results.resume','results.scaling_data','results.scaling.*.training/evaluation/parameters','metadata/version/timing'], 'toy9/1/2記錄；驗證35有效目標；scaling共同val8記錄274目標、test8記錄276目標。', '主600步width64layers2；scaling150步batch4，w16/w32與16/64train；同更新和筆數，曝光20765/20623不相等；單seed42。', '未重跑、未讀每份完整原文。text/common腳本與凍結不同，已提取當次revision核hash並讀text205–344與common1–309；TinyLM/data/training/alignment/attention hash一致。'),
 'real_text':(['5.8','5.10','5.11','5.12','6.1'],['results.runs.*.source_records/deduplicated_records/data/training/before/after.validation and test aggregates','tinystories.after.validation.samples[1],[7];after.test.samples[2]','chinese-poetry.after.validation.samples[7]','source_revision/license/split_warning/scope','metadata/code_sha256'], 'stories409/51/52原文、poetry292/36/37；storiesval42453有效含EOS；切窗後examples不是原文篇數。', '兩run各800步width64layers2max128、batch16；同run前後固定卷，非Stories與Poetry公平優劣比較。', '未下載資料包或重訓；未讀全部生成。原始來源upstreamtrain，近重複未聚類；frozen text/common/model/data/training必要hash與JSON一致。'),
 'tokenizer':(['6.3','6.4','6.5','6.6','6.8'],['results.data','results.roundtrip','results.runs.*.parameters/config/validation_text_token_lengths','results.runs.*.before/after.validation and test aggregates','results.matched_budget/raw_document_schedule_sha256/scope','metadata/code_sha256'], '153train19val20test原文片段；valtext3894/2112token、EOS後3913/2131target；test4193rawbyte，4213/2503target。', '逐byte264與BPE512，width32layer1C384；400步batch8lr.003seed42，同664759rawbytes曝光；參數41824/57696，token數及FLOP未匹配。', '未下載tokenizer資產重建或重跑；roundtrip只3指定例；全部生成未逐條讀。必要frozen text/common/tokenization/model/data hash與記錄一致。'),
 'sft':(['7.11','7.12','7.13'],['results.data/training/before/after.validation and test','results.after.validation.samples[0]','results.pretrain_then_sft','results.ultrachat_pilot source/prepared/data/training/evaluation/license/scope','metadata/code_sha256'], 'toy45train9families/5val1family/10test2families；direct5/10test、val1/5；EOS各全；UltraChat100→80/10/10。', 'direct900SFT101091有效；另同base250文章+900SFT101091，test1/10→7/10；額外預訓練預算不控制。UltraChat80步width32layer1C256。', '未下載模型／UltraChat或重跑；UltraChat新題exact0/10兩側，EOS分開；必要frozen text/common/data/model hash一致。'),
 'sft_ablation':(['5.16','7.14','7.15','7.16'],['results.data','results.before','results.runs.b-only/replay/clean/noisy training and evaluation aggregates','results.corruptions/matched_budget/scope','metadata/code_sha256'], 'A45/5/10屬性；B49/8/7加法，交換加數同family；噪音4/45=8.9%；所有原定test均作分母。', 'B-only/replay500步batch16lr.003；18453vs36384有效曝光不匹配。clean/noisy300步同45筆與33733目標，single seed42；只4標注改動。', '未重訓；核四指定corruption與聚合，未逐條讀全部生成；必要frozen text/common/data/model hash一致。'),
 'style':(['8.1','8.2','8.3','8.4','8.5','8.6'],['results.arithmetic_data/content_training/content_evaluation','results.default_style_runs.*.training/evaluation','results.data/training/after.validation and test rubric + samples','results.prompt_only_comparison_same_weights','all stored generated_ids for control-ID short check','metadata/code_sha256'], 'arithmetic49/8/7；conditional185train28val27test=3styles arithmetic147/24/21+dates38/4/6；eachteststyle7/7但numeric0/7；missingdate3/3known0/3。', 'contentbase1000步，兩default450步同basebatch16但曝光16591vs318991；conditional1000步同model；prompt-only同greedy換已教style。', '未重新生成或重訓。historical_behavior含較舊rubric，已核hash和完整diff：後版新增control-ID守衛；206保存生成beforeEOS無control，所以未改現有成功數。風格只固定模板不等於創意。'),
 'lora':(['8.8','8.9','8.13'],['results.base_sha256/base_parameters/rank/alpha/scaling','results.runs.* layer lists/trainable_parameters/training/initial_gradients/base_unchanged/evaluation','results.full_sft','results.a_b_a_max_difference/adapter_a_b_logit_difference/merge_max_difference/scope','all stored generated_ids for control-ID short check','metadata/code_sha256'], '11linears9504/141568可學約6.7%；styleval8/test7；concise7/7test、vivid6/7、full7/7，numeric全0/7。', '兩adapter與full450步；r4alpha4scale1；full/vivid318991targets、concise16591；merge容差1e-4測得6.67572e-6，ABA0。', '未下載／切換實際adapter重演。historical_behavior版本hash與diff已核，45保存生成beforeEOS無control，新增rubric守衛不影響這些成功；未保證任意基模／設備逐位一致。'),
 'safety':(['9.1','9.2','9.3','9.4','9.5','9.6','9.7','9.8'],['results.data/before/runs.*.training/evaluation/audit','specific original unknown/premise/permission/injection samples and six held_out_wording samples','results.pku_pilot aggregate training/evaluation/license/scope/public_evidence_note','metadata/code_sha256'], '去重136＝102train6families/17val1family/17test1family；每test拒3正常14；only15/17mix16/17，newwording0/6；PKU100→60safe選48/6/6，僅公有aggregate。', '兩run900步batch16single seed42；only102資料曝光394888，mixed151曝光275389，不匹配監督量；正文不當廣泛安全分數；PKU80步低資源窄pilot。', '未取私有PKU原文或權重、未重訓；字串無法提供及rawexact僅toy規則。historicalsafety_behavior版本hash/diff已核：familyID%8與凍結一致，style-rubric新增守衛與安全audit無关。'),
 'encoders':(['9.9','9.10'],['results.vision/audio.calibration method/scope/grid/selection/chosen_temperature/validation/test complete logits labels probabilities confidence bins aggregates','results.vision/audio.data/config/classes','audio.test.data record index11 frequency320 amplitude.5 seconds.12','metadata/code_sha256'], 'visionval6/test6類，test6/6；audio val8/test14，test11/14；logits每題原值與labels固定，ECE5等寬bins、Brier每class平方和再樣本平均。', '只validationNLL在[.5,.75,1,1.5,2,3,5]選T=.5，兩側test固定；不更新分類器。視覺offset切分，音訊frequency切分；不可把分類置信外推生成答案或安全。', '完整校準原值已讀並用math重算、metrics差<2e-6。frozenmodalities/common/multimodal/modal_data/model必要hash與記錄一致；未重跑音像編碼器訓練。')}
registry=[]
for name,(pids,read,den,budget,limits) in specs.items():
 j=json.load(open(ED/(name+'.json')))
 registry.append({'evidence_id':name,'source':'baseline original docs/course-experiments/results/'+name+'.json','baseline':BASE,'snapshot':str(ED/(name+'.json')),'sha256':sha(ED/(name+'.json')),'recorded_revision':j['revision'],'actual_read_paths':read,'denominators':den,'comparison_settings':budget,'metadata':{k:j.get(k) for k in ('seed','device','torch_version','python_version','gpu','evidence_status','status','timing_scope')},'limits_and_historical_code':limits})
 for p in ordered:
  if p['page_id'] in pids:p['checks'].setdefault('evidence_ids',[]).append(name)
external_specs=[
 ('instructgpt','https://arxiv.org/pdf/2203.02155v1','36–97,288–329,455–485,636–677','文章續寫與需求、SFT/RM/PPO材料、分項metadata；非一般安全保證'),
 ('r1','https://arxiv.org/pdf/2501.12948v1','229–238,277–305,431–466','R1-Zero无SFT与规则reward、R1冷啟動示範；非小模型收益承諾'),
 ('mtp','https://arxiv.org/pdf/2404.19737v1','45–175','平行head共享核心、不同距離CE、推論丟head／speculation；非本課提升實測'),
 ('v3','https://arxiv.org/pdf/2412.19437v2','532–606,1190–1207','順序MTP式21–25與D=1；玩具圖兩extra不是實際設定'),
 ('flan','https://arxiv.org/pdf/2109.01652v5','154–204,217–254,491–513','指令template與target、heldouttaskclusters與instructionablation；非簡化告示學會證據'),
 ('ifeval','https://arxiv.org/pdf/2311.07911v1','210–251,439–451','strict/loose及instruction/prompt-level；不是自然EOS檢查器'),
 ('guo','https://proceedings.mlr.press/v70/guo17a/guo17a.pdf','151–207,380–461','ECE weightedbins與T>0、valNLL、argmax不變；本課grid僅原理簡化')]
external=[]
for name,url,lines,scope in external_specs:
 external.append({'evidence_id':name,'original_url':url,'saved_pdf':str(ED/(name+'.pdf')),'pdf_sha256':sha(ED/(name+'.pdf')),'saved_layout_text':str(ED/(name+'.txt')),'text_sha256':sha(ED/(name+'.txt')),'actual_layout_text_lines_read':lines,'scope':scope})
for file,url,lines,scope in [
 ('generationconfig.py','https://raw.githubusercontent.com/huggingface/transformers/v4.57.1/src/transformers/generation/configuration_utils.py','102–115,206–217,267–275','newtoken排除prompt、总长度、EOS與forcedEOS'),
 ('vllmconfig.py','https://raw.githubusercontent.com/vllm-project/vllm/v0.8.5/vllm/config.py','232–241','model maxlen包含prompt+output'),
 ('ifeval_instructions.py','https://raw.githubusercontent.com/google-research/google-research/e49bbfe381c9c0e564b937f1c4e163a2273c65cc/instruction_following_eval/instructions.py','873–909','JsonFormat剥指定Markdown后json.loads，不检查本页schema或EOS'),
 ('pku_readme.md','https://huggingface.co/datasets/PKU-Alignment/PKU-SafeRLHF/raw/main/README.md','全文','官方current卡许可與兩維排名；mutable main查於2026-10-08，保存hash，非聲稱與過去dataset版本相同')]:
 external.append({'evidence_id':file,'original_url':url,'snapshot':str(ED/file),'sha256':sha(ED/file),'actual_lines_read':lines,'scope':scope})
implementation=[
 ('tiny_perceptron/model.py','1–125','Config/TinyLM forward positional IDs/loss_sum/生成起始'),('tiny_perceptron/training.py','1–117','checkpoint/RNG/optimizer與learningrate'),('tiny_perceptron/data.py','全文','bytes/roles/render_chat/pad/split/fingerprint'),('tiny_perceptron/tokenization.py','全文','BPE普通內容/控制ID、原JSON與hash綁定'),('tiny_perceptron/attention.py','全文','causal+valid/segment、空合法key讀出'),('tiny_perceptron/alignment.py','全文','LoRA/分箱與輔助對照'),('scripts/course_experiments/text.py','205–712','resume/text/BPE/SFT/ablation'),('scripts/course_experiments/common.py','243–309','完整SFTrawID評測與文本UTF8safeprefix'),('scripts/course_experiments/behavior.py','全文','style/LoRA/safety/PKU'),('scripts/course_experiments/modalities.py','446–542','classification calibration/logits/valchooseT/test')]
imp=[{'source':x,'sha256':sha(ROOT/'freeze/implementation'/x),'actual_lines_read':lines,'purpose':purpose} for x,lines,purpose in implementation]
prereqs=[]
for pid,purpose in [('1.8','負對數評分與正確機率，用於5.2/6.5'),('1.12','更新順序與重算loss，用於5.1/5.14'),('1.13','grad累加與動量歷史區分，用於5.3'),('2.1','embedding列與ID查表，用於5.1/7.5'),('4.8','模型計算接口與軸，用於5.1/7.11')]:
 prereqs.append({'page_id':pid,'source_sha256':sha(ROOT/'freeze/sources'/f'{pid}.md'),'actual_scope':'完整凍結來源，包含details','purpose':purpose})
figures={}
for pid in assigned:
 for f,h in INVENTORY[pid]['figures_sha256'].items():figures.setdefault(f,{'original_sha256':h,'pages':[]})['pages'].append(pid)
assert len(figures)==19
visual=[]
for path,data in figures.items():
 stem=pathlib.Path(path).stem;png=ROOT/'renders'/f'{stem}-640.png';assert png.exists()
 visual.append({'figure':path,**data,'viewed_png':str(png),'png_sha256':sha(png),'actual_scope':'以view_image實際取得640px靜態圖，下一工具回合後才作圖判斷','unverified':'未看360px或實際網站/折疊/跳轉'})
issues=[]
for pid,quote,name,full,meaning in [('5.4','Adam再參考每格「過去通常多大」的梯度，用大小歷史調整方向的尺度。','Adam','Adaptive Moment Estimation','自適應矩估計'),('6.5','正確token的負對數機率加總叫 NLL。','NLL','Negative Log-Likelihood','負對數似然')]:
 issues.append({'issue_id':'technical-learning-name-'+pid,'page_id':pid,'quoted_basis':quote,'already_taught':'機制、中文功能與當下用途已具體教清；不是方法介紹缺失。','minimum_missing_relation':'依criteria要求重要縮寫給完整名稱，這裡可補'+name+'的完整英文名稱。','current_effect':'閱讀算例不受阻；查論文/工具名稱時少一個名稱對照。','severity':'optional','minimum_fix':f'首用附近加「{name}（{full}，{meaning}）」即可，不擴写算法。','rewrite_scale':'paragraph','discovery_stage':'source_independent_technical_initial','independence_basis':'只從自己的完整凍結正文與criteria讀取發現，未看任何reader/technical/continuity歷史或他人初判。','unverified':'未聲稱真人讀者遇到負擔；名稱補齊不改技術結論。'})
report={'schema_version':1,'reviewer':'/root/technical_learning','role':'technical','group':'learning','review_kind':'全教材診斷來源独立技術輪，非發布驗收或真人學生測試','baseline_commit':BASE,'created_at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'criteria_sha256':{k:M['criteria_sha256'][k] for k in ['SKILL.md','references/review-protocol.md','references/calibration.md','references/project-context.md']},'criteria_actual_scope':'四份凍結規準全文已讀；截斷的初次combined read以分段讀取補完。README/UPSTREAM未作判斷來源。','actual_prerequisites':prereqs,'pages':ordered,'issues':issues,'coverage':{'assigned_count':79,'actually_full_read_count':79,'individually_noted_count':79,'page_ids':assigned,'unread_page_ids':[],'actual_reading_batches':['chapter05+5.1–5.17','chapter06+6.1–6.9','chapter07+7.1–7.22','chapter08+8.1–8.16','chapter09+9.1–9.10'],'method':'每份凍結頁正文與details真正完整讀取後逐頁作具體判斷；封存前檢查79不同pageID/引文存在/hash一致，非标题或搜索命中替代。','source_characters':sum(len((ROOT/'freeze/sources'/f'{pid}.md').read_text()) for pid in assigned)},'visual_scope':{'referenced_unique_figures':19,'actually_viewed_unique_figures':19,'figures':visual,'limits':'只19張640靜態PNG；360/桌面手機網站/折疊互動與路徑未驗證。'},'execution_scope':{'long_training_run':False,'curriculum_modified':False,'short_checks':[{'script':str(WD/'recompute.py'),'script_sha256':sha(WD/'recompute.py'),'results':str(ED/'recompute-results.json'),'results_sha256':sha(ED/'recompute-results.json'),'scope':'全部校準val/test固定logits：vision6+6、audio8+14；math核softmax/NLL/Brier/5binsECE、validationgridT、argmax不變。另遍歷style206與LoRA45保存生成beforefirstEOS是否有controlID。','result':'各原記metrics重算誤差<2e-6，T.5同選，style/LoRA251份均無非法controlID。','unverified':'未重跑訓練、tokenizertrain或模型生成；保存樣本不等於所有未記錄輸出。'}],'manual_scope':'逐頁固定算例相稱手算/公式/靜態程式追蹤，未宣稱79短程式逐一執行。','implementation_reads':imp,'original_evidence':registry,'external_original_sources':external,'historical_implementation_snapshots':[{'path':str(p),'sha256':sha(p),'scope':'原始實作版本，不是審閱結論；hash已與相應原JSON匹配。'} for p in sorted(ED.glob('historical-*.py'))],'limits':['未下載全部資料、模型、adapter或私有PKU素材。','沒有長訓練重跑；既有數字依原JSON與匹配歷史／凍結來源回查。','未逐條人工讀9JSON全部生成／所有資料，actual_read_paths逐項限定。','不把toy設計/手寫反例缺實測當缺陷，也不加教材未承諾的任務。']},'independence':{'other_initial_reviews_read':False,'historical_review_conclusions_read':False,'forbidden_notes_traces_synthesis_human_judgments_read':False,'allowed_source_only':'manifest、凍結criteria/sources/implementation、指定原始結果JSON、官方文件/論文；自己的work可保留。','initial_report_frozen_before_cross_review':True},'repair_assessment':{'blocker_count':0,'burden_count':0,'optional_count':2,'unverified_issue_count':0,'necessary_rewrite_scale':'沒有已確認必要重寫；多處實測／介面邊界有具體來源支持。','optional_rewrite_scale':'5.4與6.5各首用附近補完整名稱，一小句即可；不需page/chapter/order改動。','limits':'未驗證範圍保留在各頁與execution/visual_scope，不等於全部未驗都判教材錯；此判斷只涵蓋learning79頁。'},'working_notes':{'draft':str(DRAFT),'draft_sha256':sha(DRAFT),'recording_scripts':[str(WD/f) for f in ['batch01.py','batch02.py','batch03.py','batch04.py','build_report.py','recompute.py','finalize.py']]}}
# 確實覆蓋後才落封存；禁止封存後改初判。
out=ROOT/'reports/technical-learning-initial.json';seal=ROOT/'reports/technical-learning-initial.seal.json';assert not out.exists();assert not seal.exists();out.parent.mkdir(exist_ok=True)
out.write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n');digest=sha(out)
seal.write_text(json.dumps({'schema_version':1,'reviewer':'/root/technical_learning','role':'technical','group':'learning','report':str(out),'report_sha256':digest,'sealed_at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'baseline_commit':BASE,'coverage_count':79,'independence':'source-independent initial frozen before access to any other initial/old judgments','criteria_sha256':report['criteria_sha256'],'working_notes_sha256':sha(DRAFT)},ensure_ascii=False,indent=2)+'\n')
print(json.dumps({'report':str(out),'sha256':digest,'seal':str(seal),'coverage':79,'figures':19,'necessary':0,'optional':2,'scope':'no page/chapter/order rewrite confirmed; 2 paragraph-name additions'},ensure_ascii=False,indent=2))
