from pathlib import Path
import hashlib,json,sys
ROOT=Path(__file__).resolve().parents[4];BASE=Path(__file__).resolve().parent
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
frozen=json.loads((BASE/'initial-input/manifest.json').read_text())[:6]
artdefs=[
('training','training-raw-derived.json','15 original execution/training/outer receipts, file SHA bindings and selected parent histories'),
('finals','final-raw-derived.json','Original fixed validation freeze and test aggregate/count/threshold/control measurements'),
('cpu-original','cpu-raw-derived.json','Original nine invocation argv/stdout/result observations and exact nonpath parameter comparisons'),
('inputs','public-input-equality.json','Current public JSONs equal original preexecution public inputs'),
('gpu-match','gpu-cpu-comparison.json','Each original CPU call matched the same original GPU task, assets, prompt, generated IDs and raw output'),
('gpu-excerpts','gpu-validation-original-excerpts.json','Durable original raw matched validation rows plus full original journal SHA; no commentary'),
('archive','archive-model-derived.json','Actual frozen tar entity, Git pointer, every declared bytes/SHA, split counts, vocabulary and instantiated model counts'),
('data-extra','data-extra-derived.json','Original recordings excluding augmented derivatives, train fonts, full public example content'),
('ocr','ocr-contract-derived.json','Actual original target lengths 1-4 and the fixed twelve-character alphabet'),
('release','hf-release-derived.json','Anonymous fixed HF metadata 16 files/81501640 bytes and four original inference manifests'),
('cpu-current','actual-cpu-summary.json','Two known validation inputs through current CLI; manifest/revision/history/name rejections; exact RNG/sampler restoration'),
('engineering','engineering-raw-derived.json','Genuine width16 CPU execution/training receipts: completed stages, child failure, SIGTERM incomplete and own-latest resume'),
('legacy','legacy-derived.json','30 fixed index links compared with original current HF root card; legacy test record recount and 11 exports'),
('legacy-availability','hf-legacy-120-availability.json','Anonymous original/current metadata establishes all 120 pinned model archives; preserves six current-main differences'),
('v4','v4-raw-derived.json','Original validation variants and final test scored case counts recomputed from decisions'),
('v4-training','v4-training-derived.json','Original completed 2077-step LoRA run: exact trainable/optimizer parameter names and frozen samples'),
('v4-training-original','v4-training-original.json','Original cached training JSON saved byte-identically; full source and copy SHA in derived artifact'),
('v4-data','v4-data-derived.json','Original v4 training task types and validation/test-only nonsynthetic audio rows'),
('normalization','normalization-probe-output.json','Executed counterexample: literal strings differ yet original text/OCR exact predicate passes'),
('audit','input-audit.json','SHA/topkeys/explicit pointers inspected for original raw receipts'),
('audit-extra','extra-input-audit.json','SHA/topkeys/explicit pointers inspected for release, legacy, v4 and CPU originals'),
('code-manifest','code-source-manifest.json','Full source hashes, durable exact snapshots and actually inspected line ranges'),
('environment','environment.json','Actual installed CPU dependencies')]
artifacts=[{'id':i,'kind':'source_snapshot','path':str((BASE/n).relative_to(ROOT)),'sha256':sha(BASE/n),'description':desc} for i,n,desc in artdefs]
env={'python':'3.13.5','torch':'2.14.1+cpu','device':'cpu'}
for a in artifacts:
 if a['id']=='cpu-current':a.update(kind='execution',command='/workspace/tiny-perceptron-vlm/.venv/bin/python docs/technical-reviews/artifacts/p6-public-b/actual-cpu.py > docs/technical-reviews/artifacts/p6-public-b/actual-cpu.stdout 2> docs/technical-reviews/artifacts/p6-public-b/actual-cpu.stderr',result='exit 0; current text/tool known validation examples match saved answers; all eight contract cases passed',environment=env)
 if a['id']=='normalization':a.update(kind='execution',command='/workspace/tiny-perceptron-vlm/.venv/bin/python docs/technical-reviews/artifacts/p6-public-b/normalization-probe.py > docs/technical-reviews/artifacts/p6-public-b/normalization-probe-output.json',result='text and OCR exact true despite literal string mismatch; OCR errors 0 / target characters 2',environment=env)
sources=[]
for x in json.loads((BASE/'code-source-manifest.json').read_text()):sources.append({'id':x['path'],'kind':'repository_code','title':x['path'],'path':x['path'],'sha256':x['sha256'],'version':'current inspected source; exact snapshot '+x['snapshot'],'verified':True,'inspection_note':'Inspected lines '+', '.join(x['inspected_line_ranges'])+'; calculation, interface, selection or provenance contracts only.'})
fetches=[]
for p in (BASE/'official').glob('fetch*-record.json'):fetches+=json.loads(p.read_text())
for x in fetches:
 if x.get('status')!=200:continue
 sources.append({'id':x['name'],'kind':'official_source','title':x['name'],'url':x['url'],'version':'retrieved source bytes SHA256 '+x['sha256'],'verified':True,'checked_original':True,'accessed_on':'2026-10-06','authority_reason':'Original upstream maintainer or original public artifact service, accessed anonymously with TLS verification','inspection_note':'Checked the original relevant license/API/initialization/index/release fields; the exact original snapshot is '+str((BASE/'official'/x['name']).relative_to(ROOT))})

def c(i,k,s,loc,arts,ev,scope,status='verified',verification=None):
 d={'id':i,'kind':k,'statement':s,'location':loc,'status':status,'artifact_ids':arts,'evidence':ev,'scope':scope}
 if verification:d['verification']=verification
 return d
def e(source,locator,supports):return {'source_id':source,'locator':locator,'supports':supports}
def code(source,lines,supports):return e(source,'lines '+lines,supports)
files=[]
def add(index,claims):
 x=frozen[index];status='revise' if any(c['status']!='verified' for c in claims) else 'pass'
 files.append({'source':x['path'],'source_sha256':x['scope_sha256'],'full_file_sha256':x['full_sha256'],'scope':x['scope'],'frozen_input':x['frozen_path'],'source_version':'initial frozen input, inspected independently','verdict':status,'figure_sha256':{},'claims':claims,'checks':{'factual_accuracy':{'status':status,'details':'Independently checked each listed claim against original source and raw evidence'},'numeric_verification':{'status':status,'details':'Numbers recomputed from original counts/receipts or actual CPU contracts, as individually scoped'},'figure_consistency':{'status':'not_applicable','details':'No embedded figures in this assigned scope'},'source_verification':{'status':'pass','details':'Original source, anonymous release metadata and raw pointers personally inspected; no previous reviewer conclusions'},'limitations':{'status':'pass','details':'Fixed finite tasks, selected validation demonstrations, original production receipts and CPU engineering checks remain separate'}}})

add(0,[
 c('cpu-setup','software','The root-directory Git/LFS/uv sequence selects the v2 code, CPU + safetensors extras, and only the named data archive; unpacker is checksum and expansion bound.','lines 7-43',['archive','code-manifest'],[code('pyproject.toml','1-40','CPU and selftrained extras exist'),code('scripts/selftrained/hf_transport.py','238-300','Archive/package constraints and exact Git pointer checks'),e('git-lfs-pull.txt','description and include/exclude options','Pull filters downloads to named archive'),e('uv-sync-official.md','Syncing optional dependencies','--extra selects optional dependency groups')],'Checked current source, archive and installed uv semantics; no fresh clone or full dependency reinstall claimed.'),
 c('cpu-public','software','chat fetches four safe files anonymously at the explicit immutable revision and pinned manifest; joint selected1000 comes from completed4000.','lines 45-47',['release','training','cpu-current'],[code('tiny_perceptron/selftrained/inference.py','74-136','token=False, immutable revision, exact three payload hashes'),code('scripts/selftrained/train.py','235-281','Only selected best is safe-exported')],'Anonymous small metadata/manifests downloaded; existing exact public model cache used, no full model download.'),
 c('cpu-inputs','software','Ten example JSONs contain public prompts/prior format confirmations/geometry, no current answer, score labels or model output.','line49 and all message/layout paths',['inputs','data-extra'],[],'All ten JSONs personally inspected; prior assistant format confirmation is visible history, distinct from the current target.'),
 c('cpu-smoke','empirical','Seven selected validation situations produced eight successful chats and one append, and every documented answer equals the same saved GPU validation generation.','line3 and answer table 210-222',['cpu-original','gpu-match','gpu-excerpts','inputs'],[],'Exact original asset path, role/content prompt, generated token IDs and raw text compared; nine original returncodes0. This is historical evidence, not eight new runs or heldout success rate.'),
 c('cpu-history','software','First voice answer is actually generated; append reads that saved history, adds the public user request, and retains audio on its original message.','lines156-197',['cpu-original','gpu-match'],[code('scripts/selftrained/chat.py','67-108','Actual returned messages saved by history-output'),code('docs/selftrained/examples/v2/append-voice-continuation.py','1-24','Only reads history and appends public user request'),code('tiny_perceptron/selftrained/inference.py','176-212','Audio remains on the original user message')],'Original second-call generation prompt equals first-call actual messages plus user request; no demonstrated first answer substitution.'),
 c('cpu-calculator','software','The model generated a legal26*16 call, a real executor returned416, and a second generation answered結果是416。','line224',['cpu-original','cpu-current','gpu-excerpts'],[code('tiny_perceptron/selftrained/tools.py','122-170','Executor uses the model call, then passes true result to the same generator')],'Only this selected validation calculator instance; no question-to-answer parser exists in the inspected path.'),
 c('cpu-output','software','Output JSON exposes answer, actual messages, generation logs, tool trace, selected model hashes/config and disabled-auth public source.','lines199-208',['cpu-original','cpu-current'],[code('scripts/selftrained/chat.py','92-110','Outputs and optional save paths'),code('tiny_perceptron/selftrained/inference.py','251-328','Receipt and actual generator trace fields')],'Observed current text and tool output plus all original eight raw stdout JSONs.'),
 c('cpu-limits','empirical','Selected smoke success does not change heldout MoE roundtrip0/276, voice42/90, continuation26/60; demonstration voice head differs from gold.','lines5,226-229',['finals','gpu-excerpts','archive'],[code('tiny_perceptron/selftrained/dataset.py','118-171','Direct log-mel feature route and public ROI/slot geometry, no ASR transcript')],'Original test aggregates and original selected voice row: head prediction2 versus intent1. Limited image/OCR/voice tasks remain distinct from general ASR/TTS.'),
])

add(1,[
 c('train-random','software','Current pipeline constructs every neural module from scratch and later stages load the user’s own chain; no pretrained neural loader is present.','lines3-7',['training','archive'],[code('scripts/selftrained/train.py','726-779','LimitedAssistant constructor, own schema/data checked checkpoint load and origin'),code('tiny_perceptron/selftrained/model.py','133-282,295-306','Fresh LM, vision, OCR and audio constructors'),e('PyTorch-linear-official.py','Linear.__init__/reset_parameters','Standard random parameter initialization')],'From scratch means no pretrained neural weights; standard PyTorch constant bias/norm initialization remains allowed.'),
 c('train-tokenizer','software','The character vocabulary is created from train messages (plus fixed syntax/OCR alphabet), then inherited from the own parent checkpoint.','line7,53',['archive'],[code('tiny_perceptron/selftrained/dataset.py','84-91','Only split=train content enters vocabulary'),code('scripts/selftrained/train.py','736-748','Own checkpoint tokenizer reused and fingerprint checked')],'All static required OCR characters occur in actual train labels; computed vocab550. No vocabulary fit to validation/test.'),
 c('train-safe','software','Public safetensors are inference output without optimizer/RNG/sampler and currently cannot serve as training init or exact resume.','line7,139',['cpu-current','release'],[code('scripts/selftrained/train.py','235-281,733-755','Export only model tensors; training source uses full checkpoint schema and states')],'151 public neural tensor keys inspected in the true safe file; only own trusted pickle checkpoints support full state.'),
 c('train-package','numeric','Manifest3443... binds commit08761... tar67862431 bytes/SHA097607..., unpacked127161811 bytes,12 JSONL+8950 assets=8962 frozen files.','lines22-47',['archive'],[code('scripts/selftrained/hf_transport.py','238-300','Actual materialization/unpack checks')],'Actual tar entity and Git pointer inspected locally, every declared member hash independently computed; no data download or training rerun.'),
 c('train-data-gate','software','Each invocation verifies all declarations and each referenced image/audio SHA, uses trainer train/validation selection and excludes test from checkpoint choice.','lines47,51',['archive','training','engineering'],[code('scripts/selftrained/train_local_stage.py','118-185','All declaration and referenced asset checks; managed arguments and full parser names'),code('scripts/selftrained/train.py','84-103,611-628','Explicit split filtering and validation-only selection')],'All original training receipts test_used_for_selection=false; existing width16 raw executions plus current code contract.'),
 c('train-objectives','software','Pretrain predicts next tokens, SFT supervises assistant tokens, perception stages optimize own heads, and joint mixes tasks; weighted/native alter training weights while frozen backbones/heads stay fixed.','lines53,66,80-82',['training','engineering'],[code('tiny_perceptron/selftrained/dataset.py','173-241','Shifted pretrain versus assistant-only labels'),code('scripts/selftrained/train.py','284-451,519-628','Trainable prefixes, weighted language loss and unchanged validation objective')],'Native remains direct audio features to generated text, not ASR. Joint bridge parameters and LM remain trainable.'),
 c('train-recipe','software','The stage table’s steps/LR/eval/save/objective/freeze/family settings match the actual original jobs; Dense has its own seven-stage chain and ends weighted.','lines86-115',['training'],[code('scripts/selftrained/train.py','474-516,689-755','Fixed native4/1/4 and inherited source solver options')],'Current local recipe normalizes storage/output paths and device; it does not reuse private Volume or MoE checkpoint for Dense.'),
 c('train-parent-native','software','Native fresh init requires actual completed own4/4/1 joint selectedbest plus matching execution/training/outer/export metadata and inherited options.','line115',['training','engineering'],[code('scripts/selftrained/train_local_stage.py','52-85','Genuine local source and completion validation'),code('scripts/selftrained/modal_runner.py','727-854','Loaded file, source/export identity, objective, architecture and solver checks'),code('scripts/selftrained/train.py','474-516','Actual loaded checkpoint tied to full source evidence')],'Original native binds selected3000 parent best from completed10000; native source latest10000 is not used for objective change.'),
 c('train-resume','software','New stage uses best and resets optimizer/RNG/sampler/steps/tokens; exact same-stage resume uses latest and restores state, with steps the total goal.','lines119-135',['engineering','cpu-current'],[code('scripts/selftrained/train.py','375-377,779-918','State restoration versus explicit fresh initialization and selected snapshot preservation'),code('scripts/selftrained/train_local_stage.py','52-85','Best/latest filename contract and incomplete promotion rejection')],'Exact continuation permits step-goal extension, retains objective/config/solver; current RNG and task-family sampler roundtrip verified independently without training.'),
 c('train-attempt','software','Each attempt requires a nonexistent output dir and records command/options/source/manifest/parent/log/exit/time/bytes/SHA; graceful incomplete exit0 is failed and cannot promote.','lines137-139',['engineering'],[code('scripts/selftrained/train_local_stage.py','185-251','Output creation, signal forwarding and true completion receipt'),code('scripts/selftrained/train.py','847-854,900-1004','Step-boundary stop and incomplete training receipt')],'Original invalid-zero-step child1, SIGTERM child0/failed/steps1, own-latest resumed8 observed. Wrapper has no wall timer; forcible termination is not completion.'),
 c('train-selection-table','empirical','Completed and selected steps match all15 original production stages, including MoE native4000/1000 and Dense weighted10000/1000.','lines141-156',['training','release'],[code('scripts/selftrained/train.py','611-628,872-899','Unweighted teacher-forced validation loss selects best')],'Own raw parent histories cross-bound to outer best SHA; terminal selections independently bound to fixed public manifests. Selected step is stage-local and not generation success.'),
 c('train-cpu-scope','empirical','Width16 true batch16/context512 engineering smoke covered three one-step joint stages, failure, interrupt and own-latest resume; it did not rerun production or establish model capability.','line158',['engineering','finals'],[],'Original genuine local subprocess receipts personally inspected; current review ran inference/contracts only. Original final model test aggregates each3734 still fail some original thresholds.'),
])

mc=[
 c('card-origin','software','V2 is from-scratch LM plus three modality encoders and bridges, completed/exported/tested but neither architecture passed all original criteria.','lines19-21',['training','finals','archive'],[code('tiny_perceptron/selftrained/model.py','188-306','Fresh neural entry modules and shared LM')],'Completed execution and fixed limited test are separate from passing capabilities; upstream v4 capabilities are not credited to v2.'),
 c('card-exports','numeric','The fixed public release is four groups/16 files/81501640 bytes with documented manifests and completed/selected steps1000/250,8000/8000,4000/1000,10000/1000.','lines25-36',['release','training'],[],'Anonymous original API size metadata and four exact manifest hashes independently matched outer raw receipts; no full weight download.'),
 c('card-params','numeric','Both configs use550 tokens,width256,4 layers,4Q/2KV,hidden512,context512; total/LM/active/perception parameter tables match direct instantiated tensors.','lines40-49',['archive'],[code('tiny_perceptron/selftrained/model.py','25-53,56-185,433-455','Config, top2 routing and count convention')],'Computed MoE5447107/5140224/3036928 and Dense2288067/1981184/1981184; encoders91907/126829/88147. Counts include shared full matrices and selectedFFNs, not FLOPs or timings.'),
 c('card-limited-tasks','software','Fashion-MNIST three labels/public slot relations, twelve-character ROI OCR1-4 with both fonts in train, and three MInDS intents are finite tasks; voice input has no ASR.','lines51-57',['archive','data-extra','ocr'],[code('tiny_perceptron/selftrained/dataset.py','118-171','Pixels/public crop geometry or complete log-mel, not labels/transcripts'),code('tiny_perceptron/selftrained/model.py','188-282','3-class vision,13-symbol OCRhead and3-class audio head')],'Actual labels and train fonts checked. Field unseen_font is historical naming; no unseen-font or speaker/general world claim supported.'),
 c('card-generation','software','Renderer-only0,1,3-9 IDs are masked, EOS2 and visibleUNK10 remain; no target lookup or tool argument extraction is used.','line59',['cpu-current'],[code('tiny_perceptron/selftrained/model.py','381-426','Logit mask and model token generation'),code('tiny_perceptron/selftrained/inference.py','273-328','Only public prompt metadata to RecordEncoder and bounded tool loop')],'Inspected runtime path and original/current calculator generations; ROI/slot geometry are visible input.'),
 c('card-data','numeric','Frozen package and file counts match; split counts28876/2435/3734 and original recordings62/15/30 are accurate and are not independent source counts.','lines63-65',['archive','data-extra'],[],'Audio train558 materialized derivatives include62 originals; counts exclude augmented derivatives when describing original recordings. No speaker keys exist in v2 records.'),
 c('card-licenses','concept','Project outputs are MIT; Fashion-MNIST MIT, MInDS Chinese recordingsCC-BY4.0, NotoCJK fontsOFL1.1, and upstream licenses remain separate.','lines67,179',['code-manifest'],[e('Fashion-MNIST-LICENSE','copyright and MIT permission text','Original dataset MIT grant and named authors'),e('MInDS14-README.md','YAMLlicense and dataset citation','Pinned upstream CC-BY4.0 and PolyAI provenance'),e('Noto-Sans-LICENSE','lines1-8,50-76','SIL OFL1.1 font terms'),e('Noto-Serif-LICENSE','lines1-8,50-76','Same font license'),code('LICENSE','1-21','Project MIT declaration')],'Licenses apply to named components; MIT model/output declaration does not replace source data/font conditions.'),
 c('card-frozen-test','empirical','Each architecture froze on2435 validation and has one complete3734 test receipt using the same selected safe/checkpoint/manifest identities.','lines71,86',['finals'],[],'Raw frozen.json/test receipts and aggregate sums checked; supports the archived fixed runs/protocol, not a claim about any unseen external runs.'),
]
metric_rows=[('text-semantic','text','semantic',464,429,560,'75'),('text-exact','text','exact',454,419,560,'76'),('text-format','text','format',553,553,560,'77'),('clothing','vision_clothing','semantic',357,356,360,'78'),('relation','vision_relation','semantic',1427,1426,1440,'79'),('ocr','ocr','semantic',252,281,324,'80'),('tool-roundtrip','tool_call','tool_roundtrip',0,7,276,'81'),('tool-result','tool_reply','semantic',551,468,552,'82'),('voice','voice_qa','semantic',42,37,90,'83'),('voice-continuation','voice_topic_continuation','semantic',26,24,60,'84')]
for ident,task,key,moe,dense,den,line in metric_rows:
 bad=ident in ['text-exact','ocr']
 mc.append(c('card-'+ident,'empirical',f'Documented {ident} row reports MoE{moe}/{den},Dense{dense}/{den}; exact predicates are normalization based, not literal string identity.','line'+line,['finals']+(['normalization'] if bad else []),[code('scripts/selftrained/evaluate.py','197-306,499-536','Original predicate and denominator aggregation')],f'Original /per_task_final_reply/{task}/{key}; shared-task columns use overlapping records and are not additive.',status='contradicted' if bad else 'verified'))
mc.extend([
 c('card-continuation','software','Two-round voice test uses actual first model generation and scores both first and final response; it does not paste a reference first response.','line86',['gpu-excerpts','finals'],[code('scripts/selftrained/evaluate.py','855-920','First_output inserted into second generation messages, reference only for scoring')],'Archived validation example and original test end-to-end counts26/60,24/60; no new heldout generation.'),
 c('card-cer-thresholds','numeric','CER is target-character-normalized edits:72/984=7.32% MoE,43/984=4.37%Dense; stratified original thresholds remain unmet.','line88',['finals'],[code('scripts/selftrained/evaluate.py','39-48,215-224,526-531','Original thresholds/edit distance/character denominator')],'Case composition and single-character strata are disjoint960+24 characters; CER uses normalized prediction. Text/voiceper-intent and exactOCR/tool criteria cannot be replaced by mean.'),
 c('card-controls','empirical','Original paired controls cover position,ROI,tool result and history; changed outputs do not imply both members are correct.','line90',['finals'],[],'Raw paired all_correct and output_changed_when_gold_changed counters inspected; only fixed finite materials supported.'),
 c('card-cpu-train','software','CPU download and known demonstration procedure, own training stage chain/best/latest receipts and width16 smoke limitations match actual contracts.','lines94-126',['cpu-original','inputs','gpu-match','cpu-current','engineering','training'],[code('scripts/selftrained/chat.py','67-110','Documented public inference interface'),code('scripts/selftrained/train_local_stage.py','52-251','Own local training provenance and completion contract')],'Shared verification with CPU and TRAINING files; no fullrecipe or production training rerun.'),
 c('card-v4-route','software','SeparatePython3.12/torch2.8QwenVL+Whisperturbo application sends image/text to Qwen and transcribed voice to the same text history.','line130',['v4','v4-data'],[code('tiny_perceptron/natural_assistant.py','118-154,263-306,687-731','Image/text processor and separate Chinese ASR path'),code('scripts/modal_natural.py','656-658','OriginalPython3.12/torch2.8 worker spec'),e('Qwen-upstream-README.md','YAML and Qwen3-VL model description','Original pretrained multimodal model'),e('Whisper-upstream-README.md','model identity and transcription examples','Original pretrained ASR model')],'Original result versions2.8.0+cu128 and fixed IDs matched; current review CPU environment is separate3.13/2.14.'),
 c('card-v4-selected','empirical','Validation retains base without LoRA; Qwen2127532032 and ASR808878080 parameters and two-filepublic v4 bundle retain upstream licenses.','line132',['v4','v4-training','v4-data'],[e('Qwen-upstream-README.md','YAMLlicense:apache-2.0','Qwen license'),e('Whisper-upstream-README.md','YAMLlicense:mit','Whisper license')],'Raw integer criterion base53277/75600 exceeds two candidates52285,52705; both candidates fail completion/voice gates. Original public tree contains only README/provenance, not upstream tensors.'),
 c('card-v4-test','empirical','Final v4 reported25/42 photo summaries,58/84facts,8/10OCR,1/3orderedOCR,2/13textchat and2/4actualASRchat match original case decisions.','line134',['v4'],[],'Recounted original scored case-level booleans and denominators. Does not regrade every natural image or reopen fullv4 pages, nor compare v4 to v2 across tasks.'),
 c('card-old-index','software','Thirty immutable original model-card links and120 model archives remain retrievable; old11 exports8+3 and oldscores78/90,78/90,62/90,61/90 are preserved.','lines138-175',['legacy','legacy-availability'],[e('hf-current-root-README.md','original30-entry index rows only','Original fixed IDs/revisions preserved independently')],'All120 .pt bytes/SHA match anonymous current/pinned metadata; six main text_foundation files changed but documented immutable revision retains original hashes. Legacy raw records independently recounted; no weight download.'),
 c('card-old-size','numeric','Historical synthetic language core328k differs from complete v2MoE5447107.','line140',['archive'],[{'source_id':'legacy-size','locator':'/results/parameters','supports':'Original legacy core328128 at width64/layers2'}],'328k is rounded328128 language parameters; it is not v2’s parameter count or final capability evidence.'),
])
sources.append({'id':'legacy-size','kind':'repository_code','title':'Original capstone joint measurement','path':'docs/course-experiments/results/capstone_joint.json','sha256':sha(ROOT/'docs/course-experiments/results/capstone_joint.json'),'version':'original archived experiment result','verified':True,'inspection_note':'Topkeys first, /results/parameters only; config and parameter328128 inspected; no notes/review/author summaries.'})
add(2,mc)
for index,prefix in [(3,'student'),(4,'data'),(5,'training')]:
 cs=[c('v4-'+prefix+'-route','software','The deployed v4 route uses fixed pretrainedQwenVL plus Whisperturbo, no selected LoRA, shared image/text chat history and ASR-to-text voice.','opening lines1-10',['v4','v4-data'],[code('tiny_perceptron/natural_assistant.py','118-154,263-306,687-731','Actual pretrained image/text and ASR route')],'Limited to the assigned first10lines; base retained by archived validation, not a fullv4 technical review.'),c('v4-'+prefix+'-separate','software','V2 uses its own from-scratch finite image/OCR/three-intent voice data and complete own checkpoint chain rather than natural material or Whisperturbo.','opening lines7-10',['archive','ocr','data-extra','training'],[code('tiny_perceptron/selftrained/dataset.py','118-171','Separate direct audio/pixel feature route')],'Cross-link/source boundary only; no new fullv4 reader or continuity verdict.')]
 if prefix in ['data','training']:cs.append(c('v4-'+prefix+'-lora','concept','LoRA candidates update only low-rank language attentionq/v repairs on full pretrainedQwen; audio is validation/test only and Whisper is not retrained.','opening lines3-7',['v4-training','v4-data'],[e('LoRA-original.md','lines14,81-115','Original method freezes original weights and trains rank-decomposition matrices'),code('tiny_perceptron/natural_assistant.py','263-306','Freeze base and target language attentionLoRA')],'Original completed2077-step run optimizer names are exclusivelylanguageattentionLoRA; frozen samples unchanged and112adaptertensors changed. Candidate adoption is separate from completed training.'))
 add(index,cs)

issues=[{'claim_id':'card-text-exact','file':frozen[2]['path'],'status':'unresolved','details':'Initial line76 says 完全符合目標字串, but original normalize removes all whitespace and strips boundary punctuation/quotes before exact comparison. Executed output大 小！ versus target大小 passes exact. This overstates raw string identity.','suggestion':'Name normalization explicitly and state its whitespace/boundary punctuation rule; format remains a separate metric.'},{'claim_id':'card-ocr','file':frozen[2]['path'],'status':'unresolved','details':'Initial line80 says 指定區域整段完全正確 but OCRexact/CER normalize the generated text first; the same counterexample passes with0edits.','suggestion':'Describe normalization-based exact OCR rather than literal byte/string equality.'}]
report={'schema_version':1,'schema':'public-pages-independent-factual-v1','review_stage':'technical','reviewer_task':'/root/p6_fact_public_b','reviewer_context':'fresh','reviewed_on':'2026-10-06','verdict':'revise','scope':'Full docs/selftrained/v2-public-cpu-commands.md, TRAINING.md and model-cards/repository-README.md; ONLY currentopening lines1-10 of v4STUDENT/DATA/TRAINING. No fullv4 re-review.','independence':{'old_reader_or_technical_conclusions_read':False,'author_extra_results_notes_read':False,'raw_topkeys_then_named_pointers':True,'originals_preserved':True,'current_public_docs_treated_as_claims_not_evidence':True},'files':files,'sources':sources,'artifacts':artifacts,'issues':issues,'commands':[{'command':'/workspace/tiny-perceptron-vlm/.venv/bin/python docs/technical-reviews/artifacts/p6-public-b/'+x,'result':r} for x,r in [('probe.py','exit0 after own first fixture directory-iteration correction; original first failure recorded below'),('probe-extra.py','exit0'),('gpu-match.py','exit0; oneexact same-asset originalGPU match perCPU chat'),('actual-cpu.py','exit0 after supplying allfivefamilies in own sampler fixture; firstattemptstderr preserved'),('normalization-probe.py','exit0; text/OCRnormalization counterexample')]],'method_events':[{'event':'ownprobe initial directory iteration includedindex.json','result':'NotADirectoryError before any verdict; corrected to directories only, rerun successful.'},{'event':'ownpure sampler fixture initially suppliedthreefamilies','result':'Original sampler correctly rejected incompletefivefamilydata; firststderr retained, suppliedfivefamilies and exactstatecheckpassed.'},{'event':'anonymous officialsource discovery','result':'Noto rootLICENSE404 and uvweb403; genuine officialSans/SerifLICENSE and uvsource fallback returned200 with TLSenabled; fetchrecords preserve attempts.'},{'event':'currentHFmain differs for sixlegacytext_foundationarchives','result':'Preserved initial metadata difference; all six exist byte/SHA-matched at documented immutable revision. Scope is retained original version, not identicalmain.'}],'limitations':['No paid compute, training, upload, model weight downloads, complete shell recipe, or regeneration of heldout questions performed.','Two current CPU known validation examples and pure contracts cannot establish general model capability or all-platform installation.','Original raw production lineage/aggregates were checked, not production training rerun.','V4 raw summary numbers and opening cross-links checked; fullv4 pages or annotation quality were not re-reviewed.','No previous technical/reader reports or author note/review/scope_correction result commentary read.'], 'review_history':[{'phase':'initial','verdict':'revise','source_manifest':str((BASE/'initial-input/manifest.json').relative_to(ROOT)),'issues':['card-text-exact','card-ocr'],'body_edits_by_reviewer':False}]}
dest=BASE/'initial-report.json';dest.write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n')
(ROOT/'docs/technical-reviews/public-pages-p6-b.json').write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n')
print(json.dumps({'files':len(files),'claims':sum(len(f['claims']) for f in files),'verdict':report['verdict'],'initial_report_sha256':sha(dest)}))
