"""Bounded CPU check of B.5's hand-labelled policy, not learned capability."""
import ast
import contextlib
import copy
import hashlib
import io
import json
import os
import platform
import sys
from pathlib import Path

ART = Path(__file__).resolve().parent
ROOT = ART.parents[3]
sys.path.insert(0, str(ROOT))
os.environ.update(CUDA_VISIBLE_DEVICES="", HF_HUB_OFFLINE="1", HF_DATASETS_OFFLINE="1", TRANSFORMERS_OFFLINE="1")

def sha(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()

fence = ART / "original-fence/fence-1.py"
namespace = {}
stream = io.StringIO()
with contextlib.redirect_stdout(stream):
    exec(compile(fence.read_bytes(), str(fence), "exec"), namespace)
rows = namespace["examples"]
actions = [row["action"] for row in rows]
assert len(rows) == 5 and actions == ["TOOL", "DIRECT", "DIRECT", "ASK", "ASK"]
assert rows[0]["question"] == rows[-1]["question"]
assert rows[0]["calculator"] is True and rows[-1]["calculator"] is False

# Read and execute only the original task method, without run/result commentary.
method_path = ART / "frozen-input/scripts/course_experiments/tool_choice.py"
tree = ast.parse(method_path.read_bytes())
method = next(node for node in tree.body if isinstance(node, ast.FunctionDef) and node.name == "_expected_action")
method_space = {}
exec(compile(ast.Module(body=[method], type_ignores=[]), str(method_path), "exec"), method_space)
policy = method_space["_expected_action"]
intents = ["numerical_addition", "explanation", "copy", "missing_quantity", "numerical_addition"]
expected = [policy(intent, row["calculator"]) for intent, row in zip(intents, rows, strict=True)]
assert expected == actions
changed = copy.deepcopy(rows)
changed[0]["calculator"] = False
variant_stream = io.StringIO()
with contextlib.redirect_stdout(variant_stream):
    for row in changed:
        print(row["question"], "計算器可用", row["calculator"], "→", row["action"])
assert changed[0]["action"] == "TOOL"
assert variant_stream.getvalue().splitlines()[0] == "1加2等於多少？ 計算器可用 False → TOOL"
assert policy(intents[0], changed[0]["calculator"]) == "ASK"
changed[0]["action"] = "ASK"
assert [policy(intent, row["calculator"]) for intent, row in zip(intents, changed, strict=True)] == [row["action"] for row in changed]
policy_cases = []
for intent, wanted in [("numerical_addition", ("ASK", "TOOL")), ("explanation", ("DIRECT", "DIRECT")), ("copy", ("DIRECT", "DIRECT")), ("missing_quantity", ("ASK", "ASK"))]:
    for available, expected_action in zip((False, True), wanted, strict=True):
        observed = policy(intent, available)
        assert observed == expected_action
        policy_cases.append({"intent": intent, "calculator_available": available, "expected": expected_action, "observed": observed})

# Label strings use the same ByteTokenizer contract as normal text. No model,
# weights, training or model score is generated by this check.
from tiny_perceptron.data import ByteTokenizer
tokenizer = ByteTokenizer()
labels = {label: {"ids": tokenizer.encode(label), "decoded": tokenizer.decode(tokenizer.encode(label))} for label in ("DIRECT", "TOOL", "ASK")}
assert all(item["decoded"] == label for label, item in labels.items())
assert {label: len(item["ids"]) for label, item in labels.items()} == {"DIRECT": 6, "TOOL": 4, "ASK": 3}
import torch
assert torch.version.cuda is None and not torch.cuda.is_available()

report = {
    "kind": "bounded_original_and_variant_execution",
    "purpose": "Check literal labels, controlled availability change and text encoding; no learned capability measurement.",
    "environment": {"python": platform.python_version(), "torch": str(torch.__version__), "cuda_build": str(torch.version.cuda), "device": "cpu", "tokenizer": "repository ByteTokenizer; 264 vocabulary entries"},
    "original_fence_sha256": sha(fence),
    "original_stdout": stream.getvalue(),
    "human_label_count": len(rows),
    "ordered_actions": actions,
    "policy_expected": expected,
    "availability_only_variant_stdout": variant_stream.getvalue(),
    "availability_only_variant_first_row": {"stored_action": "TOOL", "policy_action": "ASK", "mismatch": True},
    "reconciled_first_action": changed[0]["action"],
    "eight_policy_cases": policy_cases,
    "label_text_encoding": labels,
    "fence_ast_calls": [ast.unparse(node.func) for node in ast.walk(ast.parse(fence.read_bytes())) if isinstance(node, ast.Call)],
    "method_locator": f"_expected_action lines {method.lineno}-{method.end_lineno}",
    "limitations": "Five manual records and eight deterministic rule cases; neither is a held-out model test denominator. There is no calculator call, final arithmetic answer, backward or optimizer update in the original fence.",
}
assert report["fence_ast_calls"] == ["print"]
(ART / "bounded-results.json").write_text(json.dumps(report, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
print(json.dumps({"checked": "original fence plus availability-only and reconciled variants", "manual_rows": len(rows), "policy_cases": len(policy_cases), "ordered_actions": actions, "stale_label_variant": "False still prints TOOL; required label ASK", "label_token_lengths": {label: len(item["ids"]) for label, item in labels.items()}, "device": "cpu", "assertions": "all passed"}, ensure_ascii=False))
