import hashlib,json,platform,subprocess
from pathlib import Path
from collections import Counter
root=Path.cwd();out=root/'docs/technical-reviews/artifacts/natural-v4-supplemental/site-environment-storage';base=root/'docs/natural-assistant/evidence/v4-research/student-selected-public-ui/actual-ui'
obs=[json.loads(s) for s in (base/'observer.jsonl').read_text().splitlines()];browser=json.loads((base/'browser/report.json').read_text());trial=json.loads((base/'report.json').read_text());disk=json.loads((base/'disk-observation.json').read_text())
r={'scope':'Own recomputation of original one-run records. No model execution, cache audit, minimum hardware inference, quality scoring or GPU replication. Aggregate pass/status fields ignored.','environment':{'python':platform.python_version(),'device':'CPU record inspection only'},'original_hashes':{str(p.relative_to(root)):hashlib.sha256(p.read_bytes()).hexdigest() for p in [base/'observer.jsonl',base/'browser/report.json',base/'browser/requests.json',base/'report.json',base/'disk-observation.json']}}
r['events_by_kind']=dict(Counter(x['kind'] for x in obs));r['denominators']={'linux_cpu_runs':1,'chat_generations':r['events_by_kind']['generate_end'],'asr_calls':r['events_by_kind']['transcribe_end'],'core_loads':r['events_by_kind']['load_core_end'],'asr_loads':r['events_by_kind']['load_asr_end'],'browser_chat_requests':sum(x['route']=='/api/chat' for x in browser['requests']),'browser_asr_requests':sum(x['route']=='/api/transcribe' for x in browser['requests'])}
r['load_options']=[x['options'] for x in obs if x['kind'] in ['load_core_begin','load_asr_begin']];r['server_memory_kib']=[x['maximum_resident_set_kib'] for x in obs if x['kind']=='process_resources'];r['server_memory_GiB']=[x/2**20 for x in r['server_memory_kib']];r['recorded_startup_seconds']=trial['ready_seconds'];r['recorded_full_trial_seconds']=trial['wall_seconds'];r['recorded_browser_chat_seconds']=browser['chat_seconds'];r['recorded_browser_asr_seconds']=browser['asr_seconds_including_load'];r['core_load_elapsed_from_monotonic']=next(x['monotonic'] for x in obs if x['kind']=='load_core_end')-next(x['monotonic'] for x in obs if x['kind']=='load_core_begin');r['disk_record_bytes']=disk['official_cache']['unique_regular_file_bytes'];r['disk_record_GiB']=r['disk_record_bytes']/2**30;r['official_cache_download_repeated']=False;r['threads']=next({k:x[k] for k in ['torch_threads','torch_interop_threads']} for x in obs if x['kind']=='observer_ready');r['generated_inputs']=[{'mode':x['row'].get('mode'), 'images':len(x['assets']),'history_turns':len(x['row'].get('history',[]))} for x in obs if x['kind']=='generate_begin'];r['requests_recomputed']=dict(Counter(x['route'] for x in browser['requests']));r['reset_observed_states']=[x['state'] for x in obs if x['kind']=='operation_end' and x['route']=='/api/reset']
# Small environment checks; no models imported or loaded.
c=['.venv-natural/bin/python','-c',"import platform,importlib.metadata,json;print(json.dumps({'python':platform.python_version(),'packages':{k:importlib.metadata.version(k) for k in ['torch','torchvision','transformers','peft','numpy','pillow','soundfile']}}))"]
p=subprocess.run(c,capture_output=True,text=True,timeout=15);r['own_natural_metadata']={'command':c,'exit_code':p.returncode,'stdout':p.stdout,'stderr':p.stderr}
# check_env emits HF_ENDPOINT, which is configuration outside this review; redact that unrelated line from durable output.
p=subprocess.run(['.venv/bin/python','scripts/check_env.py'],capture_output=True,text=True,timeout=30);r['check_env']={'command':['.venv/bin/python','scripts/check_env.py'],'exit_code':p.returncode,'stdout':'\n'.join('[HF_ENDPOINT line redacted as unrelated configuration]' if s.startswith('HF_ENDPOINT') else s for s in p.stdout.splitlines())+'\n','stderr':p.stderr}
(out/'record-recomputation.json').write_text(json.dumps(r,ensure_ascii=False,indent=2)+'\n');print(json.dumps(r,ensure_ascii=False,indent=2))
