import hashlib,json
from pathlib import Path
root=Path.cwd();folder=Path('docs/technical-reviews/artifacts/natural-v4-supplemental/site-environment-storage');probe=json.loads((folder/'probe-output.json').read_text());emp=json.loads((folder/'record-recomputation.json').read_text());browser=json.loads((folder/'browser-receipt.json').read_text());receipts=json.loads((folder/'original-retrieval-receipts.json').read_text());lookup={s['id']:s for s in receipts}
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
S=[]
def official(i,title,version,locator,note,kind='official_docs'):
 r=lookup[i];S.append(dict(id=i,kind=kind,title=title,url=r['url'],version=version,verified=True,checked_original=True,accessed_on='2026-10-04',authority_reason='Original documentation or source supplied by the organization maintaining this API, file format, service or model.',locator=locator,inspection_note=note,own_summary=note,retrieval_sha256=r['retrieval_sha256']))
official('uv-sync','Astral uv: Locking and syncing','live official documentation retrieved 2026-10-04; local uv command also exercised','Automatic lock and sync; Syncing optional dependencies; Syncing development dependencies','uv run locks/syncs before invoking commands; --frozen reads the existing lock without freshness checks; extras are not enabled by default; --extra and --group select optional dependencies and groups. Exact uv sync can remove extraneous packages. These are installation semantics, not task accuracy evidence.')
official('git-lfs-pointer','Git LFS Specification','git-lfs v3.7.0','The Pointer; Intercepting Git','Git stores a small UTF-8 pointer with version, sha256 oid and byte size. Clean/smudge filters store or obtain the original content separately; pointer content is not compressed archive content. Uploading objects and committing pointers are separate operations.','official_source')
official('git-lfs-config','Git LFS configuration manual','git-lfs v3.7.0','GIT_LFS_SKIP_SMUDGE environment variable','Value 1 skips converting checked-out pointers to objects in smudge/filter-process. Thus the documented clone command can obtain source without downloading LFS content; it presumes Git LFS support is installed as its linked prerequisite explains.','official_source')
official('github-lfs-billing','GitHub: Git LFS billing','live policy retrieved 2026-10-04','Working in a public or private repository with Git LFS; Examples of how usage is measured','A changed version counts the entire new file in owner storage and downloads count against owner bandwidth. The document correctly avoids promising a permanent quota or treating LFS as compression.')
official('hf-storage','Hugging Face Hub storage limits','live policy retrieved 2026-10-04','Storage plans; Repository limitations; Sharing large volumes of models','Account quotas, repository/file recommendations and public-storage reuse/abuse policy apply. Private backups are possible within account plans; public storage is not unrestricted personal backup. No numeric quota is asserted in the assigned text.')
official('pytorch-previous','PyTorch previous versions installation instructions','v2.8.0 section of live page retrieved 2026-10-04','v2.8.0 / Wheel / Linux and Windows / CUDA 12.8 and CPU only','The official commands pair torch 2.8.0 with torchvision 0.23.0 and list separate CPU and cu128 indexes. This supports the student-toolchain instructions, not the separate small-model environment version.')
official('nvidia-compat','NVIDIA CUDA minor version compatibility','CUDA Compatibility documentation retrieved 2026-10-04','CUDA 11 and Later Defaults to Minor Version Compatibility; Table 1; Application Considerations for Minor Version Compatibility','CUDA major families have minimum-driver and feature restrictions; matching driver/runtime/GPU conditions matter. The page gives no blanket claim that GPU identity or a later CUDA index proves task completion. No GPU was available for execution here.')
official('pytorch-checkpoint','PyTorch saving and loading models tutorial','live official tutorial retrieved 2026-10-04; actual probe Torch 2.14.1+cpu','Saving & Loading Model for Inference; Saving & Loading a General Checkpoint for Inference and/or Resuming Training','Inference can restore model state_dict; resuming training needs optimizer state and progress as well. Original project save_checkpoint additionally preserves Python/Torch/device RNG and training_state, so inference-only weights cannot guarantee identical resumed updates.')
official('peft-checkpoint-raw','PEFT checkpoint format','PEFT v0.18.1 source tag','PEFT files, paragraphs and adapter_model/adapter_config entries','PEFT saves adapter parameters rather than base weights; the original base remains required, and adapter config records its pairing. The versioned rendered URL returned 404; this original tagged documentation source was retrieved and personally read instead.','official_source')
official('qwen-card','Qwen3-VL-2B-Instruct original model card','89644892e4d85e24eaac8bacfd4f463576704203','weight repository identification; Quickstart / Using Transformers to Chat','The official pinned repository is an image/text-to-text model. Its Qwen3VLForConditionalGeneration and AutoProcessor example supplies image and text messages to the same model. I use this to verify identity/roles, not the card’s performance marketing.','official_source')
official('whisper-card','OpenAI Whisper-large-v3-turbo original model card','41f01f3fe87f28c78e2fbf8b568835947dd65ed9','Whisper introduction; Usage; transcription task explanation','The official pinned model is automatic speech recognition, with processor/features and decoding to text. Current project transcribe uses language=chinese/task=transcribe and hands text to the Qwen chat route; it does not retrain Whisper.','official_source')
def repo(i,path,locator,note):
 S.append(dict(id=i,kind='repository_code',title=path,path=path,sha256=sha(path),version='current working-tree bytes personally inspected 2026-10-04',verified=True,locator=locator,inspection_note=note))
repo('project','pyproject.toml','project.requires-python; optional-dependencies; dependency-groups; tool.uv.conflicts/sources/index','Python >=3.11; CPU/cu126/cu130 mutually exclusive extras and explicit PyTorch indexes; notebook group includes JupyterLab and ipykernel.')
repo('lock','uv.lock','TOML package entries named torch','Personally parsed all torch entries: current lock pins 2.14.1/2.14.1+cpu/+cu126/+cu130 with platform markers and explicit registries. Actual .venv version checked independently.')
repo('python-pin','.python-version','entire file','Default project interpreter pin is 3.13.')
repo('natural-requirements','requirements-natural.txt','entire file','Eleven package==version pins include torch2.8.0/torchvision0.23.0, transformers4.57.6 and peft0.18.1; separate Python3.12 route stated in comments and runtime guard.')
repo('env-check','scripts/check_env.py','PACKAGES; pick_device; main','Reports actual packages, CUDA/MPS/CPU availability and runs 256x256 matrix forward/backward. Does not test learned model quality. Stale cu128 example in this script’s docstring is outside assigned page; current page/config use cu126/cu130 correctly.')
repo('attrs','.gitattributes','/assets/training/*.tar.gz entry','LFS tracking is attached to all fixed training tar.gz archives; source/config/manifest remain ordinary text.')
repo('ignore','.gitignore','virtualenvs and /data,/checkpoints,/outputs,/runs entries','Environment, data/cache/weights/checkpoints and local outputs are ignored. Ignoring is a storage policy, not deletion or a guarantee of backup.')
repo('data-generators','tiny_perceptron/data.py','split_documents; toy_documents; toy_conversations','Tiny rule-based text and conversation fixtures are reproducible from code and deterministic split seed rather than downloaded natural-language corpus.')
repo('modal-reader','tiny_perceptron/modal_data.py','modal_example lines17–29','Pillow opens/converts/resizes images; soundfile reads audio; tensors are passed to the project’s own small-model encoders. Audio input is explicitly nonempty 16kHz mono.')
repo('natural-core','tiny_perceptron/natural_assistant.py','load_core; encode_training_row; run_train; load_asr; transcribe','Pinned AutoProcessor/Qwen model, optional PEFT adapter, frozen base and selected LoRA-only optimizer. run_train reads manifest.rows train subset, never audio_rows. Whisper processor/model convert finite bounded waveform into Chinese transcription.')
repo('natural-fetch','scripts/fetch_natural_release.py','validate_manifest; verify_release; fetch_release; check_runtime; student_options','Manifest allowlist distinguishes base and adapter files. Base variant has README/provenance only, Qwen/Whisper original pins, zero adapter params. Runtime guard enforces Python3.12/package pins and code hashes; model loading occurs through service, not a copy of official weights into the two public project files.')
repo('natural-release','docs/natural-assistant/v4/public-release.json','base_model; asr_model; selected_variant; runtime; files','Base selected, no adapter parameters; two project files total9,262bytes; full original official model revisions supplied separately. Reviewed/anonymous_download_verified flags were seen as configuration gating only, not independent proof.')
repo('training-fetch','scripts/fetch_training_assets.py','main','--asset all uses the eight entries in assets/training/manifest.json; it does not select v4 natural-data archives. Pointer detection triggers selected LFS pull; no all-data fetch was executed.')
repo('asset-check','tiny_perceptron/assets.py','sha256; unpack_asset','Checks complete archive byte size/hash and each extracted member byte/hash before copying into target. Existing different content stops. Does not score labels or model responses.')
repo('training-manifest','assets/training/manifest.json','assets/archive_bytes/archive/files','Eight IDs and each archive byte count and per-file SHA/bytes; directly compared to stat sizes in own probe.')
repo('natural-manifest','docs/natural-assistant/v4/manifest.json','archives; files; rows; audio_rows','Three v4 archives plus individually declared members; own computation finds2077 training rows and38 audio rows only on validation/test. Counts metadata not used as calculation source.')
repo('natural-data-fetch','scripts/fetch_natural_data.py','validate_manifest; summary; download_checked; extract_checked; verify_directory; main','V4’s independent entry uses exact manifest/revision, three known archive paths and file-level checks; --list executes offline with no data download. Full package download/extraction not repeated.')
repo('experiment-plan','docs/course-experiments/plan.json','sequence IDs/assets vs supporting_experiments','Personally counted30 unique formal sequence IDs; nine supplements are separate, so the table’s30 formal experiments is accurate without claiming the repo has only30 total experiments.')
repo('checkpoint-code','tiny_perceptron/training.py','save_checkpoint; restore_checkpoint_rng; load_checkpoint','Training checkpoint stores optimizer/step/RNG/training_state alongside config/weights; actual tiny CPU save/load round-trip retained weights and state fields.')
repo('model-code','tiny_perceptron/model.py','ModelConfig; TinyLM.forward','Own tiny model used actual width/heads/layers/max_length config and logits dictionary. First probe’s invented d_model fields were corrected after reading this source; no product correction was needed.')
repo('course-release-code','scripts/course_release.py','inference_payload; validate_export','Inference export fields omit optimizer/progress/RNG; custom format loaders explicitly reconstruct project models including simple/LoRA/encoder/multimodal formats.')
repo('course-public','docs/course-experiments/public-models.json','models[id,repo,revision,files]','Per-model pinned Hugging Face commits and export filenames; personally counted30 entries and inspected representative simple-model fields. No full release audit or weight download.')
repo('capstone-public','docs/course-experiments/capstone-public.json','repo/revision/models/format_version/files','Separate11-stage capstone manifest with capstone-v1 and quantized formats, CPU custom loader and matching companions. No model compatibility with generic chat UI promised.')
repo('course-fetch','scripts/fetch_course_models.py','fetch_model; main','Chosen ID only, pinned40hex revision and exact SHA/size verification before file copying; no implicit all-model download.')
repo('capstone-fetch','scripts/fetch_capstone.py','fetch_capstone; main','Selected stage pinned revision, file size/hash and format checks. Custom payload loading supports the assigned page’s warning that project weights are not universally generic chat formats.')
A=[]
def artifact(i,file,kind,description,command=None,result=None,environment=None):
 p=str(folder/file);d=dict(id=i,kind=kind,path=p,sha256=sha(p),description=description)
 if kind=='execution':d.update(command=command,result=result,environment=environment)
 A.append(d)
artifact('probe','probe-output.json','execution','Own numeric/stat/manifest, package-selection, image/audio decode, tiny checkpoint and backward computations. Includes subprocess exact commands/stdout/stderr.','.venv/bin/python '+str(folder/'probe.py'),'Exit0;11 stat sizes equal manifest;8/3 sums and30 formal count match; media exact decode and checkpoint equality; offline dry-run and Jupyter version exit0.',probe['environment'])
artifact('probe-code','probe.py','code','Corrected bounded CPU probe code.')
artifact('record-probe','record-recomputation.json','execution','Own recomputation of raw CPU record events/configuration/memory conversions; separate installed metadata and check_env output.','.venv/bin/python '+str(folder/'recompute_records.py'),'Exit0;4 generate pairs,1 ASR pair,1 load of each, correct CPU float32 pins/threads; server maxRSS conversion; actual check_env CPU compute OK.',emp['environment'])
artifact('record-code','recompute_records.py','code','Raw record recomputation code; ignores aggregate status/pass fields.')
artifact('browser','browser-receipt.json','execution','Personally executed Chromium inspections of both current assigned pages, authored next link click, exact frozen Git blob comparison.','python '+str(folder/'inspect_browser.py'),'Exit0; HTTP200 both pages; full article headings/links captured; actual next-link click lands on asset-storage; both original frozen source blobs byte-equal current snapshots.',browser['environment'])
artifact('browser-code','inspect_browser.py','code','Actual Chromium and read-only assigned blob inspection code.')
for name in ['environment','asset-storage']:
 artifact(name+'-screenshot',name+'-browser.png','source_snapshot','Actual assigned browser screenshot personally viewed; prose, tables and commands rendered. No SVG diagram in these documents.')
 artifact(name+'-visible',name+'-visible.txt','source_snapshot','Actual browser article visible text personally read alongside the canonical full-file read.')
 artifact(name+'-current',f'reviewed-{name}.md','source_snapshot','Full unnormalized UTF-8 assigned current canonical source snapshot.')
 artifact(name+'-frozen',f'{name}-frozen-source.md','source_snapshot','Exact original committed assigned source bytes from preview build-info freeze; independently compared with current file.')
artifact('original-receipts','original-retrieval-receipts.json','source_snapshot','Small original authority retrieval URLs/date/status/SHA receipts. Full third-party texts/HTML remain ignored research only;404 attempt preserved.')
artifact('failed-probe-code','probe-first.py','code','Unchanged first probe containing erroneous own ModelConfig field names; preserved before correction.')
artifact('failed-probe','probe-first.stderr.txt','execution','Genuine first probe TypeError, captured again unchanged before correcting own probe.','.venv/bin/python '+str(folder/'probe-first.py'),'Exit1: ModelConfig.__init__ got unexpected keyword argument d_model; corrected to actual width/heads/layers/max_length and logits key.',probe['environment'])
C=[]
def claim(i,kind,statement,location,refs,arts,scope,expected=None,observed=None,details=None,denominators=None):
 d=dict(id=i,kind=kind,statement=statement,location=location,status='verified',evidence=[{'source_id':sid,'locator':loc,'supports':sup} for sid,loc,sup in refs],artifact_ids=arts,scope=scope)
 if kind in ['software','numeric','empirical']:
  d['verification']=dict(method='executed',expected=expected,observed=observed,details=details)
  if kind=='numeric':d['verification']['tolerance']='Exact integer counts/bytes; decimal MB rounded to2 decimals.'
  if denominators:d['verification']['denominators']=denominators
 C.append(d)
claim('c1','software','Reading the static course uses a browser; short local code uses Python/CPU, while full student inference and training have their own environment/hardware route.','environment introduction and hardware table', [('project','project/dependency-groups','Small-model Python/CPU/notebook toolchain'),('env-check','main forward/backward','Basic CPU computation is independently exercised')],['browser','probe','record-probe'],'The hardware table is an entry guide, not a claim that every full experiment or any GPU/platform has been reproduced in this review. Colab remote service was not launched.','Both assigned static pages render in browser and basic local CPU compute succeeds.','Both HTTP200; Chromium headings/tables visible; check_env compute OK(cpu); tiny differentiable matrix check gives expected gradient6.','Actual browser and bounded CPU execution, separate from model quality.')
claim('c2','software','uv uses pyproject/uv.lock, frozen sync retains the lock choices, run normally synchronizes, and CPU/notebook selections must be retained in each command; JupyterLab is a notebook tool.','environment section2 commands and run explanation',[('uv-sync','Automatic lock and sync; extras/groups','Original uv command semantics'),('project','requires-python; dependencies; extras/groups','Actual project configuration'),('lock','torch package pins','Current resolved CPU version'),('python-pin','entirefile','Default interpreter pin')],['probe','record-probe'],'Installation/startup commands were checked by source, offline dry-run and installed tools; no installation or live Jupyter service was performed. uv sync exact behavior may remove unrelated local tools; dry-run records this without mutation.','Frozen CPU/notebook selection parses offline; installed Jupyter available and check_env works.','uv sync --frozen --extra cpu --group notebook --offline --dry-run exit0; JupyterLab4.6.4; check_env exit0 on Torch2.14.1+cpu.','Official semantics personally read; exact current TOML/lock inspected; dry-run output explicitly says would download1/install1/uninstall10 rather than an executed install.')
claim('c3','software','The Chapter20 student route is a separate Python3.12/Torch2.8.0 environment with requirements-natural fixed packages rather than the small-model uv.lock.','environment section2 finalparagraph and section3 finalparagraph',[('natural-requirements','entirefile','Fixed package pairs'),('natural-fetch','check_runtime','Python/dependency guard'),('pytorch-previous','v2.8.0 CPU/cu128','Official version/index pairing')],['record-probe','probe'],'Verified package metadata/current source only; did not install the student environment or load any full model. CPU build local suffix is compatible with base2.8.0 pin.','Distinct actual environments conform to their respective documented versions.','Own metadata: .venv Python3.13.5/Torch2.14.1+cpu; .venv-natural Python3.12.14/Torch2.8.0+cpu, torchvision0.23.0+cpu, transformers4.57.6, peft0.18.1.','Read exact pins/guard and executed small metadata command without model imports.')
claim('c4','software','cpu/cu126/cu130 are mutually exclusive PyTorch source selections; CUDA index, NVIDIA driver and device compatibility must be checked independently of availability and task completion.','environment section3 table, prose and cu126 command',[('project','tool.uv.conflicts/sources/index','Actual mutual exclusion and source mappings'),('nvidia-compat','Table1 and application caveats','Driver/runtime conditions'),('pytorch-previous','CUDA indexes','Official explicit binary-index choices')],['probe','record-probe'],'GPU selections were not installed/executed; no NVIDIA device or nvidia-smi executable exists here. No claim of speed ordering, GPU/MPS compatibility or general hardware minima.','Three explicit mutually exclusive extras; CPU check reports CUDA unavailable.','Parsed conflict tuple and mappings cpu/cu126/cu130; actual torch.version.cuda=None and cuda_available=False.','Configuration verified by actual TOML parsing and CPU runtime; NVIDIA original conditions checked separately.')
claim('c5','software','Small model media uses Pillow/soundfile and its own tensors; Chapter20 keeps pretrained processors, with Whisper speech transcription passed as text into the same image/text chat model.','environment section4',[('modal-reader','modal_example','Pillow/soundfile conversion'),('natural-core','load_core; load_asr; transcribe','Actual processor and ASR split'),('qwen-card','Quickstart','Official image/text role'),('whisper-card','Usage/transcription','Official ASR-to-text role')],['probe','record-probe'],'Own2x3image/four-sampleWAV decode checks only local media tools. Full Qwen/Whisper not loaded by reviewer. The course’s local audio mechanism demos do not establish trained general ASR ability.','Read/write exact tiny media and project routing agrees with originals.','Pillow size2x3 pixel(15,30,45); soundfile16000Hz exact four samples; code transcribe task=transcribe; original record1Whisper and4Qwen calls.','Bounded deterministic media probe plus personally inspected original code/cards and raw invocation logs.')
claim('c6','empirical','Chapter20 can execute on the recorded Linux CPU setup; the linked student guide records disk/memory/wait observations for one machine, without measuring universal minimum requirements or validating other backends.','environment section1 CPU paragraph',[('natural-core','load_core CPUfloat32; load_asr','Implementation supports explicit CPU path')],['record-probe'],'This is independent recomputation/interpretation of original records, not own replication of full-model inference. Cache bytes/memory/latencies are recorded observations; no full cache or weight audit. Windows/MPS/otherGPU paths are unverified.','One CPUfloat32 run with4chat generations and1ASR plus actual recorded resource/timing fields.','Raw observer has4generate_begin/end,1transcribe_begin/end,1coreload/1ASRload; options cpu/float32/local_files_only; resource13,496,104KiB=12.8708878GiB; recorded24.2428s startup and170.3322s full trial; four chat latencies3.4217/42.8712/36.5841/37.1102s.','Counted event pairs and browser request routes, inspected original observing/measurement code, converted bytes/KiB directly; ignored aggregate pass/status. 5torchthreads and1interop; cache reused; no new weight download.',emp['denominators'])
claim('c7','software','This project stores code/source/config/manifests in Git, reconstructible toy data by generator/seed, fixed archives under Git LFS, public inference milestones in HF manifests, and local cache/checkpoint/output directories outside ordinary Git.','asset-storage section1 table; section2 tracking path; environment section5',[('attrs','archive LFS pattern','Current archive path contract'),('ignore','localdata/checkpoint/output rules','Local ignored destinations'),('data-generators','toy/split functions','Reproducible toy fixture rules'),('training-manifest','assets and files','Fixedarchive metadata'),('course-public','models manifests','Inference HF pins')],['probe'],'Repository storage/configuration rules checked; no new Git clone/pull/push, upload, release audit or private backup performed. Ignored files remain user-managed local artifacts.','Declared archive paths/configuration and separate list entries agree.','EightfoundationIDs andthreev4archivepaths; project ignore/data/cache/output directories; actual --list commands succeed and formal model manifest contains30 entries.','Direct actual file/config parsing, exact archive stat and safe offline list commands; toy generator source read.')
claim('c8','concept','LFS keeps a small Git pointer containing content hash/byte size and separate full objects; skipping smudge leaves pointers. LFS does not compress content, and changed versions/storage/download bandwidth accrue under provider policy.','asset-storage section2 including clone command',[('git-lfs-pointer','The Pointer; Intercepting Git','Original pointer/content/file-filter contract'),('git-lfs-config','GIT_LFS_SKIP_SMUDGE','Value1 skips downloading checked-out object'),('github-lfs-billing','Working in public/private repository; examples','Whole version storage and owner download-bandwidth billing')],[],'The Bash clone snippet’s semantics follow original Git LFS docs with installed LFS prerequisite in linked assets README. It was not cloned/executed here. No permanent quota/cost amount asserted; compression of tar.gz is distinct from LFS storage.')
claim('c9','numeric','The first8compressed packages total30,854,837bytes≈30.85MB and accompany30formal experiments; Chapter20’s3packages total146,543,309bytes≈146.54MB, with its own data scope and download entry.','asset-storage section3 table and scopeparagraph',[('training-manifest','all8 archive_bytes','Foundation summands'),('natural-manifest','all3 archives bytes','V4 summands'),('experiment-plan','sequence vs supporting_experiments','30formal IDs'),('training-fetch','main selected list','--asset all excludesv4')],['probe'],'Bytes measured by stat on already present archives and independently compared to manifest; no full archive hash/extraction repeated. DecimalMB is10^6bytes; full model/package/RAM costs excluded.30is formal sequence only, not all supplements.','8sum30,854,837bytes;3sum146,543,309bytes;30unique formal IDs.','8stat/manifest30,854,837=30.854837MB→30.85;3stat/manifest146,543,309=146.543309MB→146.54;30unique formal entries;9separate supplements.','Actualstat sizeeacharchive and integer summation from independentcurrent manifest parsing; counts from explicitsequence list, not claimed countmetadata.')
claim('c10','software','Chapter20 publicly provides configuration/provenance with official Qwen and Whisper pinned identities, rather than repackaged custom copies of the two base weight sets; LoRA adapters still need their paired base. Voice recordings are evaluation data, excluded from LoRA updates.','asset-storage section1 finalparagraph and section3 audio sentence; environment section5 finalparagraph',[('natural-release','selected_variant/base_model/asr_model/files','Current base-only2file release with original model pins'),('natural-fetch','fetch_release; student_options','Official model options supplied separately from projectfiles'),('natural-core','run_train rowsfilter/optimizer; load_core; transcribe','Audio_rows never enters trainingrows; paired base remains loaded'),('peft-checkpoint-raw','PEFTfiles','Adapters omit baseweights')],['probe','record-probe'],'Checks selected manifest/file allowlist and actual list/configuration, not all public model-repo objects or full downloads. No empirical model-selection/performance verdict adopted.','Base selected/zeroadapterparams;two project documents;audio_rows onlyvalidation/test and trainupdates drawrows only.','Actual list selected_variant=base with Qwen89644892…/Whisper41f01f3f…;twofile manifest9262bytes;38audiorows=16validation+22test,0train;trainrows2077.','Executed manifest validation/list/split counting and source inspection of run_train data path plus PEFToriginal pairing requirements.')
claim('c11','concept','Inference configuration/weights/processors differ from a resumption checkpoint: continuing the same update trajectory also needs optimizer, step/progress and random state. Project public weights have custom formats/loaders; HF backups/public milestones remain subject to storage policies.','asset-storage section4',[('pytorch-checkpoint','Saving/loading inference and generalcheckpoint','Inference modelstate versus optimizer/progress'),('peft-checkpoint-raw','PEFTfiles','Paired config/adapter/base requirements'),('hf-storage','Storage plans; large model policies','Backup/storage policy conditions')],['probe'],'The tiny checkpoint round-trip confirms current projectfields and model equality; it is not an exact training-resume certification for every public architecture. Current code explicitly refuses quantified inference resumes; user text correctly says inferenceweights alone cannot guarantee identical updates.')
claim('c12','software','Manifests fix version, filenames, byte/hash identity and paired components; successful file checking confirms matching content, while data appropriateness and response correctness require separate evaluation. The assigned preview preserves these meanings and the next-page link works.','asset-storage section5 and ending; environment finalnextpage',[('asset-check','unpack_asset','Content checks versus task grading'),('natural-data-fetch','download_checked/extract_checked/verify_directory','Exact archive/memberidentity'),('natural-fetch','verify_release/fetch_release','Pinnedproject files checked beforeuse'),('course-fetch','fetch_model','ChosenimmutableHFrevision andSHA/bytes')],['browser','probe'],'The manifest checklist and publication sequence are recommendations, not evidence of a publication completed by this reviewer. No freshness/cache download quality score is inferred; reading-time metadata remains unfinalized. No publishing page correction used as authority.','Pinnedfile checks validatecontent;browsernextlink reachesassetpage withsameprose.','Originalcode checksfullcontentSHA/size and list-onlyprobe preservesmodel/data distinction; browserauthorednextlink reachesasset-storage.html withvisiblecorrecth1 andsourcefreeze matchesbothfiles.','Direct codecontract inspection, actual boundedlist command and actualChromiumclick/visibletext plusbytecomparison.')
allids=[c['id'] for c in C]
readorder=[
 {'order':1,'path':'cloud-environment-onboarding:setup SKILL.md and onboarding reference','scope':'Full skill and reference read; no environment changes needed or made.'},
 {'order':2,'path':'docs/environment.md','scope':'Complete95line? Full5958byte UTF8file read from firsttitle through finalnextlink; allprose/tables/commands/limitations.'},
 {'order':3,'path':'docs/asset-storage.md','scope':'Complete5805byte UTF8file read from firsttitle through finalpublishinglink; allprose/tables/commands/checklist/limitations.'},
 {'order':4,'path':'outputs/natural-v4/review-plan/supplemental-factual-contract.md; docs/technical-review-guide.md','scope':'Fullrole/schema read.'},
 {'order':5,'path':'pyproject.toml; requirements-natural.txt; .python-version; .gitattributes; .gitignore; scripts/check_env.py','scope':'Fullconfiguration/environmentchecker read.'},
 {'order':6,'path':'docs/natural-assistant/v4/STUDENT.md; docs/natural-assistant/v4/DATA.md; assets/training/README.md','scope':'FullSTUDENT andDATA read; fulltrainingassetsREADME read. Oneinitialcombinedreadtruncated, followedbysuccessfulseparatereads.'},
 {'order':7,'path':'scripts/check_technical_reviews.py','scope':'Readunchanged_artifacts/_sources/_claims and_validationrules; no numberedlessonfabrication.'},
 {'order':8,'path':'scripts/fetch_training_assets.py; scripts/fetch_natural_data.py; scripts/fetch_natural_release.py; tiny_perceptron/natural_assistant.py; tiny_perceptron/training.py','scope':'Fullfirsttwo fetchscripts; relevantexactmanifestvalidation/verification/runtime/load/train/ASR/checkpointfunctions of remainingimplementation.'},
 {'order':9,'path':'assets/training/manifest.json; docs/natural-assistant/v4/manifest.json; docs/natural-assistant/v4/public-release.json; docs/course-experiments/plan.json; public-models.json; capstone-public.json','scope':'Personallyparsed/countedsizes/IDs/splits/declarations; inspectedidentity/pairing/customformatentries. Noaggregateverdictaccepted.'},
 {'order':10,'path':'docs/natural-assistant/v4/TRAINING.md; docs/course-experiments/README.md','scope':'TRAININGlines1–95 hardware/data/selectedtrainingroute; full54linecourseexperimentREADME read asentry/rolecontext, notreviewauthority.'},
 {'order':11,'path':'original student-selected-public-ui actual-ui records and executed-harness observer/browserclient','scope':'Personallyreadrawrequests,observerJSONL/resource/disk/browsermetrics and relevantmeasurementcode; independentlycountedrawevents. Aggregatepassfieldsignored.'},
 {'order':12,'path':'original official authority URLs in sources','scope':'Originaldownload then personalread of the specificrecordedsections; fulltexts keptignored. OneversionedPEFT404preserved; originalv0.18.1tag sourceverified.'},
 {'order':13,'path':'tiny_perceptron/model.py; modal_data.py; assets.py; data.py; scripts/course_release.py; fetch_course_models.py; fetch_capstone.py; uv.lock','scope':'Readcitedcurrentfunctions/loaderexportfields; parsedTorchlockentries. ActualModelConfigsourcecorrectedownfailedprobe.'},
 {'order':14,'path':'course/first-steps.md#W.1; scripts/export_course.py','scope':'W.1activation/kernel/orderedcellprerequisite; exporterDOCUMENTSroute map only. ReadcommandalsoincidentallyreturnedW.2–W.5currentprerequisiteprose, nojudgments.'},
 {'order':15,'path':'http://127.0.0.1:8787/environment.html; /asset-storage.html and exactlythetwoassignedGitblobs','scope':'ActualChromiuminspection,screenshotsvisibletext/nextlinkclick; personalimageviewbothscreenshots; read-onlygitshowexactpreviewfreezeassignedtwo paths; originalsbyte-equal.'}
]
readorder[1]['scope']='Complete5958byte UTF8file read from firsttitle through finalnextlink; allprose/tables/commands/limitations.'
r=dict(schema_version=1,review_stage='technical',review_kind='nonnumbered_complete_document_supplement',reviewer_task='/root/v4_review_coordinator/factual_site_environment_storage',reviewer_context='fresh',assigned_document_scope=['docs/environment.md','docs/asset-storage.md'],complete_documents=['docs/environment.md','docs/asset-storage.md'],current_document_sha256={p:sha(p) for p in ['docs/environment.md','docs/asset-storage.md']},source_reading_order=readorder,figure_sha256={},figure_inspection={'necessary_svgs':[],'rendered_svgs':[],'reason':'Neither assigned full document references any SVG/image. Original modelcard performance graphics were not necessary to establish the stated processor/identity roles, so none was rendered or claimed viewed. Both actual browser screenshots personally viewed.'},verdict='pass',first_verdict='pass',claims=C,sources=S,artifacts=A,issues=[],checks={
 'factual_accuracy':dict(status='pass',details='Completeassigneddocs independentlychecked through12connectedsubstantiveclaims. No unresolved or contradictedassignedclaimfound.',claim_ids=allids),
 'numeric_verification':dict(status='pass',details='Ownstat-versus-manifest sums for11archives and30formalIDcount; rawCPUeventdenominators/resourceconversion verified. Rounded decimalMBcorrect; empiricalrecords remainoneoriginalrun.',claim_ids=['c6','c9','c10']),
 'figure_consistency':dict(status='not_applicable',details='No SVG or otherfigure appears in eitherassigned fullfile. Actualbrowserprose/tables inspected separately; no necessarySVG rendering.',claim_ids=[]),
 'source_verification':dict(status='pass',details='Originaluv/GitLFS/GitHub/HF/PyTorch/NVIDIA/PEFT/Qwen/Whisper authorities personallyread at exactsections/versionpins withretrievalSHAreceipts. Currentprojectcode/config/rawrecords independentlyinspected; nopeerverdictused.',claim_ids=allids),
 'limitations':dict(status='pass',details='Reading, basiccomputation, contentidentity, modelquality, deviceavailability and end-to-end completion remain distinct. CPUrecordscope, cache reuse and memory/timing denominators preserved; noGPU/MPS/windows/minimumhardware/generalquality extrapolation.',claim_ids=allids)},
 prior_report_status=json.loads((folder/'prior-report-status.json').read_text()),
 incidental_exposure=[{'scope':'Initial rg --files filename discovery under repo returned names of earlier reader/technical/factual artifact paths and old source snapshots; no contents opened. Later path discovery under necessary empirical/prerequisite roots returned author-receipt/review-dispatch filenames only.','use':'Discovery-only; not evidence or verdictauthority.'},{'scope':'Current public-release.json exposes reviewed/anonymous_download_verified booleans. Necessary docs/course-experiments/README.md exposes progress/review-policy prose. Original actual-ui/report.json and browser/report.json expose passed/status/infrastructure aggregate fields while reading raw measurementrecords.','use':'Only package/pin/file declarations, rawevent/request/timing/resource data and sourcefunctions used. All aggregatepass/approval/readerclaims ignored. No prior assignedfactual/reader report conclusions or authorcorrection/history read.'}],
 failed_attempts=[{'command':'cat /workspace/AGENTS.md /workspace/tiny-perceptron-vlm/AGENTS.md','result':'Bothabsent; no rootAGENT instructions available.'},{'command':'rg --files on guessed src/configs/tiny_vlm paths','result':'Pathsabsent; correcteddiscoverytorepository scripts/tiny_perceptron without any productchanges.'},{'command':'GET https://huggingface.co/docs/peft/v0.18.1/en/developer_guides/checkpoint','result':'404; receiptpreserved; exactoriginaltaggedsourceusedinstead.'},{'command':'.venv/bin/python '+str(folder/'probe.py'),'result':'InitialownprobeTypeError for invented d_model field; unchangedfirstscript/stderr replaypreserved. Corrected ownprobe to sourceModelConfig fields and logitskey. Subsequentprobe exit0; no assigneddocumentissue.'}],
 execution_limits=['No installation, package/environment mutations, heavy data/model download or fullcache/release audit.','NoGPU, longtraining, allbookkernels, fulltest suite, sitebuild orpublication. Onlytinyone-updatecheckpoint stateprobe andrepresentative forward/backward/media/list checks.','uv installation commands checked by originalsemantics/configuration and offline dry-run only; actualsync/run lifecycle withfreshinstall/Jupyter/Colab notexecuted.','OriginalCPUfull-modelrecordrecomputed; fullQwen/Whisper inference notreplicated byreviewer.','Gitusedread-onlyonlyfor exactassignedtwooriginalblobs at suppliedpreviewfreeze; nohistorysearch/checkout/staging/write.','Writes restrictedtoownartifactgroup plusignoredresearch/temp. Fullthirdpartytexts remain ignored.','No subagents. Readingtimemetadata remainsunfinalized; this is factualreview, notpublicationapproval.'],
 preview={'url':'http://127.0.0.1:8787/','sourcefreeze':browser['build_info']['revision'],'exact_assigned_blob_comparison':browser['source_provenance'],'browser_meaning':'Bothfullarticles personallyread inactualChromium; package/table/code andstorage roles preserved. Authoredenvironmentnextlinkclick arrivesatassetstorage. The screenshot stickyheader partially overlays top title, so title also verified fromactualDOM; no claim of a newsitebuild orpublication.'},validation={'method':'unchanged checker components _artifacts/_sources/_claims imported read-only plus own nonnumbered fullfile/identity/figure/fivechecks validator','receipt_path':str(folder/'checker-receipt.json'),'scope':'Nofabricatedlesson_id; numbereddispatch exclusivity/globalreaderownership checks are inapplicable to thiswholefilegroup and were not invoked.'})
(folder/'report.json').write_text(json.dumps(r,ensure_ascii=False,indent=2)+'\n');(folder/'report.first-verdict.json').write_bytes((folder/'report.json').read_bytes());print('report bytes', (folder/'report.json').stat().st_size, 'sha256',sha(folder/'report.json'))
