import json,hashlib
from pathlib import Path
R=Path.cwd();A=R/'docs/technical-reviews/artifacts/phase4-13_15-independent';p=R/'docs/technical-reviews/13.15.json';j=json.loads(p.read_text())
coverage={
'representation':{'experiment':'Original build_records constructs the four feature values, Python-computed candidate text and ideal action from the mode.','helper':'The actual small policy takes four numeric features and returns four logits; reward model combines numeric context with candidate identity, not Chinese text.','cpu':'Executed data construction confirms the 1+2 feature vector, all four prewritten candidates and ideal action 0.'},
'ppo-cycle':{'ppo':'Equations 6–7 define the same-action new/rollout-old probability ratio and clipped minimum surrogate; Algorithm 1 reuses a fixed collected batch over multiple optimization epochs. Equation 12 reduces to reward minus baseline for a terminal one-step task.','helper':'bandit_advantage detaches reward-minus-old-value and the PPO helper detaches old log probabilities and advantage before constructing the negative mean minimum surrogate.','cpu':'The actual pre-step ratio was 1; after the same step it was 0.9300719499588013. All three recorded rollout quantities had requires_grad=False.'},
'reference-value':{'instructgpt':'The RL paragraph and equation 2 support the conceptual RM reward with a fixed SFT-reference penalty. They do not prove this finite recipe is identical to token-level InstructGPT.','ppo':'Equation 9 explicitly includes a squared value-target error term alongside the policy surrogate.','helper':'exact_kl sums p*(log p-log q) over all four candidates and detaches reference logits; the value network takes only context.','experiment':'The original PPO loop adds its fixed-reference KL to policy loss, while the critic separately targets sampled normalized RM reward.'},
'autograd-apis':{'categorical':'Categorical normalizes logits on the last candidate axis, samples category indices and gathers their normalized log probabilities.','gather':'The original gather contract selects along axis 1 with [batch,1] indices, producing [batch,1] chosen rewards before squeeze.','nograd':'no_grad disables graph recording for the collection arithmetic used here, so these computed rollout values stay fixed.','freeze':'Module.requires_grad_ sets module parameter flags in place; applying False freezes RM/reference gradients.','backward':'Tensor.backward computes and accumulates graph-leaf gradients; its contract does not claim parameter updates.','zero':'Optimizer.zero_grad resets gradients only for tensors in the optimizer groups.','sgd':'SGD.step updates the parameters and gradients collected from its own groups; excluded RM/reference parameters are not optimized.','cpu':'Direct snapshots of all four networks prove policy and critic changed in both tested contexts, while RM/reference did not.'},
'seed-output':{'cpu':'True stdout and assertions from the exact fence match every stated output in the installed CPU environment.','arithmetic':'The shapes have one batch row and four features or four candidates; the initial ratio compares identical action probabilities before any update.'},
'feature-variation':{'experiment':'Mode explain makes feature three 1 and rule_best_action chooses card 1; the four-feature/four-candidate contract is unchanged.','cpu':'The meaningful one-feature variation executed successfully with unchanged shapes, while its random card was 0 and the independently generated ideal was 1.'},
'smoothing':{'smooth':'The official cross_entropy contract says label_smoothing mixes the original target and a uniform distribution.','smooth-impl':'The original native implementation divides the smoothing mass by the number of classes, which is four here.','arithmetic':'Independent target arithmetic yields .8*[1,0,0,0]+.2/4=[.85,.05,.05,.05]; derivative p-target gives positive target mass to the other cards rather than forcing model output equality.','cpu':'The float64 smoothed-loss and explicit soft-target calculations differ by less than 1e-12, and their gradient matches p-target.'},
'sft-meaning':{'instructgpt':'The original SFT stage fine-tunes a pretrained GPT-3 model on labeler demonstrations.','experiment':'The finite policy is newly constructed before the demonstration cross-entropy loop, so this example starts from random initialization.'},
'split-data':{'experiment':'Canonical a<=b operand loops construct 55 families; splitting assigns complete families, and all SFT/RM/PPO indices use only train. Final evaluation follows all updates.','raw':'The original saved split family lists and context counts, demonstration count and unique preference-pair count match 44/5/6, 132/15/18, 44 and 660.','cpu':'Executed data construction independently reproduces the counts and disjoint family sets, including reserved 1+2 only in test.','measure':'Rechecked the original saved family sets for disjointness and the saved test sample mode/expected-action fields; no checkpoint inference was run.'},
'parameters':{'helper':'The actual Linear layer widths and biases determine the three counts; the candidate identity is registered as a buffer.','arithmetic':'Separate weight-and-bias products sum to 148 policy, 241 RM and 97 critic parameters.','cpu':'Actual sum(p.numel()) over each model parameter iterator exactly reproduces 148, 241 and 97.'},
'draws-units':{'experiment':'Original CONFIG values and loops establish batch sizes, update counts and three optimization epochs per unchanged 64-action rollout; the task never trains token sequences.','raw':'Original saved configuration, final histories and count fields report completed 60/300/120 schedules, 360 updates per PPO network, 7,680 fresh actions, 23,040 reused records and zero effective tokens.','measure':'Own assertions recheck the count fields, final histories and three raw trace epochs; old probabilities, values, rewards and advantages stay unchanged across the 64-record reuse.','arithmetic':'Independent multiplication verifies 60*32=1,920, 300*64=19,200, 120*64=7,680, 120*3=360, and 7,680*3=23,040; draws and tokens are distinct units.'},
'saved-success':{'experiment':'The original evaluator chooses probability argmax and compares it to an independent mode rule; the denominator is the number of test contexts. This supports the criterion, not the measured success count by itself.','raw':'The original 18 saved sample outputs for each policy and corresponding greedy aggregate preserve the measured 6/18 and 12/18 results.','measure':'Own code checks all saved probability vectors, argmax actions and independent mode-rule successes, then recomputes the two numerators and denominator 18.'},
'recipe':{'runner':'The original CLI accepts experiment/device arguments and dispatches the plan-selected posttraining module/function from the repository workflow.','experiment':'The original method enforces CPU and full fixed schedule before work; its later DPO loop is part of the complete recipe.','recipe':'Actual help output, plan dispatch and early CPU/step-scale rejection checks pass without entering training.'},
'recorded-timing':{'raw':'Original saved elapsed_seconds, cpu_threads and PPO seconds provide this one measured timing and runtime configuration.','runner':'The real elapsed timer wraps the experiment invocation and does not include installation of the Python environment.','experiment':'Personally read PPO start/end timers and the DPO branch/timer within the same complete experiment.','measure':'Own rounding of 2.1226681080000276 and 0.6570014490000062 to two decimals yields 2.12 and 0.66.'}}
for c in j['claims']:
 for ev in c['evidence']:ev['supports']=coverage[c['id']][ev['source_id']]
fp=Path(__file__);j['artifacts'].append({'id':'source-support-code','kind':'code','path':str(fp.relative_to(R)),'sha256':hashlib.sha256(fp.read_bytes()).hexdigest(),'description':'Explicit per-claim, per-source support statements from this reviewer own inspected evidence; no verdict or measurement change.'})
p.write_text(json.dumps(j,ensure_ascii=False,indent=2,allow_nan=False)+'\n');saved=json.loads(p.read_text());assert len(saved['claims'])==14
print(json.dumps({'canonical_generated_and_confirmed':True,'source_sha256':saved['source_sha256'],'report_sha256':hashlib.sha256(p.read_bytes()).hexdigest()},indent=2))
