import json,hashlib
from pathlib import Path
R=Path.cwd(); A=R/'docs/technical-reviews/artifacts/phase4-13_15-independent'; p=R/'docs/technical-reviews/13.15.json'; report=json.loads(p.read_text())
phrases={
'representation':('Four structured features encode operands divided by 10 and the explain/missing indicators. Python prewrites the cards; the policy selects a card rather than reading Chinese, computing addition, or generating tokens.','Finite template-generated card task only.','Expected features [0.1,0.2,0,0], four prewritten candidates and ideal action 0.','The generated example and network input/output matched exactly.','No tokenizer or generation call occurs. Python constructs the candidate sums before model input.'),
'ppo-cycle':('Collect an action, its old log probability, reward, value and fixed advantage; recompute the same action with the current policy; optimize the PPO clipped surrogate and value prediction. The ratio is 1 before the first update.','A terminal, one-step contextual card recipe. This does not describe every detail of token-level RLHF.',None,None,None),
'reference-value':('This recipe adds exact KL(policy || fixed reference) to the policy loss and MSE to the critic loss. Reward and reference stay frozen; critic estimates RM reward.','An explicitly specified finite-card recipe. Its fixed SFT reference differs from the old rollout policy; LLM implementations can treat rewards and value targets differently.',None,None,None),
'autograd-apis':('Categorical(logits) supplies card sampling and log probabilities; gather selects the chosen reward. no_grad fixes rollout records. zero_grad clears gradients, backward computes them, and SGD.step updates only the policy and critic parameters in its groups.','Grouped sampling/indexing and autograd/optimizer contracts on installed PyTorch 2.14.1+cpu.','Policy and critic change; reward and reference do not; rollout records have no gradients.','Both the base example and third-feature variant matched these assertions; the optimizer contains eight parameter tensors.','Executed the original fence verbatim. The instrumented variants snapshot all four networks before the same update. Personally read the core API contracts at the installed upstream commit.'),
'seed-output':('With seed 42, the selected action is 0, pre-update ratio is 1, policy change is True, reward/reference gradients are False, and context/logit shapes are both [1,4].','Python 3.13.5 and PyTorch 2.14.1+cpu in the current environment; no cross-platform random-seed guarantee.','0, 1, True, False, False, [1,4], [1,4].','Every stated value matched the original fence stdout.','The ratio compares the identical policy before step. It becomes 0.9300719499588013 after the update, so clipping did not lock it to 1.'),
'feature-variation':('Setting context feature three to 1 preserves [1,4] shapes but changes the ideal card to 1. The random example does not guarantee that choice.','The structured explain-mode rule; no claim that one random update improves task success.','Third feature 1; ideal card 1; unchanged input/output shapes.','The ideal card was 1, while the random example still sampled 0. Policy and critic changed; both shapes remained [1,4].','This variation changes only the requested format. Parameter updates and correct task behavior require separate checks.'),
'smoothing':('For four cards, label smoothing 0.2 mixes 80% of the original one-hot target with 20% uniform mass, producing [0.85,0.05,0.05,0.05]. This is a training target rather than a guaranteed prediction.','PyTorch uniform-mixture smoothing in this experiment. It is optional for SFT and does not guarantee exact output probabilities.','The target is [0.85,0.05,0.05,0.05]; the smoothed loss equals the explicit soft-target loss.','Losses were 1.4667025112751417 and 1.4667025112751413. The gradient matched softmax minus the smoothed target.','Used a nonuniform prediction to distinguish target from model output. Independently calculated 80% one-hot plus 5% for each class.'),
'sft-meaning':('The finite policy starts randomly and learns from demonstrations by supervised training. LLM SFT continues a pretrained model on demonstrations.','A distinction between this finite supervised example and LLM fine-tuning; the finite policy is not pretrained.',None,None,None),
'split-data':('The 55 unordered operand families split into 44/5/6 families. Three modes per family give 132/15/18 contexts, 44 numeric demonstrations and 660 unique training preferences. Test families do not enter updates.','Canonical a<=b templates and disjoint family sets. Reversal refers to unordered family identity, not additional sampled reversed examples.','55 families, split 44/5/6; contexts 132/15/18; 44 demonstrations; 660 training pairs.','All counts matched exactly and the family sets were disjoint.','There are 10*11/2 families and three modes per family. Each family has 6+6+3 preference pairs. Every training loop uses x constructed from train; evaluations occur after updates. No training rerun.'),
'parameters':('The default finite policy, reward model and critic have 148, 241 and 97 trainable parameters respectively.','Default widths/features/actions. The registered candidate identity matrix is a buffer, not a trainable parameter.','148, 241, 97.','Actual parameter counts matched 148, 241, 97 exactly.','Policy: 4*16+16+16*4+4. RM: 8*24+24+24+1. Critic: 4*16+16+16+1. The identity buffer is excluded.'),
'draws-units':('SFT uses 60 updates of 32 draws. RM uses 300 updates of 64 pairs, or 19,200 pair draws. PPO collects 120 batches of 64 fresh actions, or 7,680, and reuses each for three epochs: 360 policy updates, 360 critic updates and 23,040 reused action records. effective_tokens is 0 because this is a card task.','The original completed finite-card run. Resampled or reused records are distinguished from unique examples and fresh answers.','1,920 SFT draws; 19,200 pair draws; 7,680 fresh actions; 360 updates for each network; 23,040 reused action records; 0 token training units.','All exact counts matched. Final logged steps were SFT 60, RM 300 and PPO rollout 120. The first trace contains three epochs of the same 64 records.','The maximum advantage error is 5.9605e-8 and ratio error 6.0840e-8, both below 2e-7. Old logs, values, rewards, advantages and hashes stay fixed across the reuse epochs.'),
'saved-success':('Of 18 held-out contexts, the saved starting SFT policy meets the full request on 6; the saved PPO policy does so on 12.','Saved greedy finite-card evaluation only; not stochastic accuracy, a newly trained result, or language-generation capability.','SFT 6/18 and PPO 12/18.','SFT: number 6/6, explain 0/6, missing 0/6. PPO: number 6/6, explain 0/6, missing 6/6. Totals are 6/18 and 12/18.','Checked all 18 saved outputs per policy. Each chosen action matches probability argmax; success matches the independently specified mode rule. Probability sums agree within 2e-7; aggregate rates within 4e-8. Existing weights were never loaded.'),
'recipe':('The root module recipe dispatches the CPU posttraining experiment, including its DPO branch; the project Python environment must be active.','CLI and dispatch contract checked. The whole training recipe was not run; the original one-update example supplies a bounded functional check.','CLI accepts --experiment posttraining --device cpu; dispatch selects posttraining.run_posttraining with no assets; the full experiment contains DPO.','The exact dispatch and CLI help passed. Non-CPU device and shortened step scale were rejected before training. The DPO branch was read.','Imported the module, ran CLI help and exercised early precondition rejections. The full recipe was deliberately left unrun because this review excludes complete training.'),
'recorded-timing':('The recorded full CPU run with two threads took approximately 2.12 seconds, including DPO; its PPO segment took approximately 0.66 seconds. Environment installation is not included.','One specified original timing measurement, not a rerun or cross-machine performance forecast.','Rounded total 2.12 s and PPO 0.66 s; two CPU threads; no installation time.','Raw total 2.1226681080000276 s and PPO 0.6570014490000062 s round to 2.12 and 0.66. The recorded thread count is 2.','Read the actual timer boundaries and rounded the saved elapsed values. The timer wraps experiment execution, not Python installation. No benchmark rerun.')}
for c in report['claims']:
 statement,scope,expected,observed,details=phrases[c['id']]; c['statement']=statement;c['scope']=scope
 c['location']='13.15: '+{'representation':'opening two paragraphs','ppo-cycle':'four-step list and ratio explanation','reference-value':'steps 2–4 and value_loss/loss code','autograd-apis':'original Python fence and its explanation','seed-output':'printed output explanation','feature-variation':'practice paragraph','smoothing':'supplementary label-smoothing paragraph','sft-meaning':'supplementary SFT clarification','split-data':'saved-experiment and supplementary split paragraphs','parameters':'supplementary network details','draws-units':'supplementary schedules and units paragraph','saved-success':'saved test-success paragraphs','recipe':'bash fence and surrounding instructions','recorded-timing':'final supplementary timing paragraph'}[c['id']]
 if 'verification' in c:
  c['verification'].update(expected=expected,observed=observed,details=details)
  if c['kind']=='numeric' and c['id']!='smoothing':c['verification']['tolerance']='Exact integer, shape, boolean or stated ratio equality in this pinned runtime.'
 for ev in c['evidence']:
  ev['supports']='Personally checked the cited original locator for this claim: '+statement+' Supporting scope is limited to '+scope
report['checks']['factual_accuracy']['details']='All 14 substantive claims were individually checked against personally read primary sources, original implementation and bounded execution. No unresolved factual claim remains. Exact read scopes are recorded in own-inspection.'
report['checks']['numeric_verification']['details']='Executed the original fence and meaningful third-feature variation; checked parameters, target arithmetic, family counts, draw units, all 18 saved test samples and original rollout trace. Integer and axis checks are exact; float tolerances are explicit. No complete training or checkpoint inference.'
report['checks']['figure_consistency']['details']='13.15 has no image/SVG references. Actually viewed the exact section standalone Chromium render at desktop and mobile sizes, plus the necessary 13.13 clipping and 13.14 roles SVGs rendered with Inkscape. Labels agree with the original method. Actual exported course-site styling was not validated.'
report['checks']['source_verification']['details']='Fetched versioned PPO v2 and InstructGPT v1 papers plus official PyTorch source at the installed git SHA. Personally read exact original passages and APIs. Immutable public result JSON equals the complete local original; provenance, code fingerprints and named raw pointers match. The source locator index was used only to find originals.'
report['checks']['limitations']['details']='Finite prewritten cards do not demonstrate Chinese reading, addition or token generation. The random example checks update mechanics; the saved 6/18 and 12/18 greedy outcomes remain separate. Full recipe contract only: no GPU, complete training or checkpoint evaluation. Timing is one original run. Initial helper tempfile failure and Chromium file-URL blocking were retained truthfully; standalone rendering is not site or reader acceptance.'
for s in report['sources']:
 if s['id']=='arithmetic':s['details']='Batch shape [1,4] represents one context with four features or four candidate logits. Smoothing: 0.8*onehot+0.2/4 gives [0.85,0.05,0.05,0.05], and its logit gradient is p-target. Parameter formulas give 148, 241 and 97. There are 10*11/2=55 families and three modes per family; 44/5/6 families give 132/15/18 contexts. Each training family contributes 6+6+3=15 preference pairs, totaling 660. Draw arithmetic: 300*64=19,200; 120*64=7,680; 120*3=360 updates; 7,680*3=23,040 reused records. Saved greedy outputs were independently compared to the number/explain/missing rule.'
report['claims'][6]['verification']['tolerance']='Absolute tolerance 1e-12 for float64 loss and gradient; the target arithmetic agrees exactly up to floating-point representation.'
# Record the additional explicit timer line read after the initial report generation.
inspection_path=A/'sources/own-inspection.json'; inspection=json.loads(inspection_path.read_text()); inspection['read_scope'].append('scripts/course_experiments/posttraining.py:390: explicitly read PPO elapsed timer after initial report generation')
inspection_path.write_text(json.dumps(inspection,ensure_ascii=False,indent=2)+'\n'); report['actual_read_scope']=inspection['read_scope']
for artifact in report['artifacts']:
 if artifact['id']=='inspection':artifact['sha256']=hashlib.sha256(inspection_path.read_bytes()).hexdigest()
report['artifacts'].append({'id':'report-format-code','kind':'code','path':str(Path(__file__).relative_to(R)),'sha256':hashlib.sha256(Path(__file__).read_bytes()).hexdigest(),'description':'Makes this new reviewer report readable; changes no verdict, source, measurement or claim coverage.'})
p.write_text(json.dumps(report,ensure_ascii=False,indent=2,allow_nan=False)+'\n'); saved=json.loads(p.read_text());assert len(saved['claims'])==14 and saved['reviewer_task']=='/root/phase4_factual_coordinator/factual_13_15'
print(json.dumps({'canonical_generated_and_confirmed':True,'source_sha256':saved['source_sha256'],'report_sha256':hashlib.sha256(p.read_bytes()).hexdigest()},indent=2))
