from pathlib import Path
from datetime import datetime, UTC
import hashlib
import importlib.metadata
import importlib.util
import json
import shutil
import subprocess
import sys

ROOT = Path(__file__).resolve().parents[4]
A = Path(__file__).resolve().parent
REL = A.relative_to(ROOT).as_posix()
def sha(path): return hashlib.sha256(path.read_bytes()).hexdigest()
def write(path, value): path.write_text(json.dumps(value, ensure_ascii=False, indent=2, allow_nan=False) + "\n")
spec = importlib.util.spec_from_file_location("section_facts", ROOT / "docs/review-tools/section_facts.py")
sf = importlib.util.module_from_spec(spec); spec.loader.exec_module(sf)
current, whole, line = sf.original_section(ROOT / "course/chapters/13.md", "13.16")
assert current == (A / "section.md").read_bytes()
assert sha(A / "posttraining-original.json") == sha(A / "posttraining-public-1df3353.json")
for lesson in ["13.12", "13.13", "13.14", "13.15"]:
    body, _, first = sf.original_section(A / "chapter13-frozen-input.md", lesson)
    (A / (lesson + "-prerequisite.md")).write_bytes(body)
environment = {"python": sys.version, "torch": importlib.metadata.version("torch"), "markdown": importlib.metadata.version("Markdown"), "playwright": importlib.metadata.version("playwright"), "chromium": subprocess.run(["chromium", "--version"], capture_output=True, text=True, check=True).stdout.strip(), "device": "cpu", "cuda_used": "False"}
write(A / "review-environment.json", environment)
commands = [
 {"command": ".venv/bin/python docs/review-tools/section_facts.py course/chapters/13.md#13.16 --output /tmp/phase4-13_16-independent-input", "exit_code": 0, "purpose": "original UTF-8 extraction"},
 {"command": ".venv/bin/python docs/review-tools/section_facts.py course/chapters/13.md#13.16 --output /tmp/phase4-13_16-independent-run --execute --timeout 45", "exit_code": 0, "stdout": "original-stdout.txt", "stderr": "original-stderr.txt", "execution": "original-execution.json"},
 {"command": "PYTHONDONTWRITEBYTECODE=1 .venv/bin/python docs/technical-reviews/artifacts/phase4-13_16-independent/audit.py > docs/technical-reviews/artifacts/phase4-13_16-independent/audit-stdout.txt 2> docs/technical-reviews/artifacts/phase4-13_16-independent/audit-stderr.txt", "exit_code": 1, "attempt": "initial", "saved_code": "audit-initial-code.py", "saved_stderr": "audit-initial-stderr.txt", "diagnosis": "reviewer compared output field against pre-evaluation inputs; KeyError, not a lesson error"},
 {"command": "PYTHONDONTWRITEBYTECODE=1 .venv/bin/python docs/technical-reviews/artifacts/phase4-13_16-independent/audit.py > docs/technical-reviews/artifacts/phase4-13_16-independent/audit-stdout.txt 2> docs/technical-reviews/artifacts/phase4-13_16-independent/audit-stderr.txt", "exit_code": 0, "attempt": "corrected ten input-field range", "stdout": "audit-stdout.txt", "stderr": "audit-stderr.txt", "measurements": "measurement-audit.json"},
 {"command": "PYTHONPATH=. PYTHONDONTWRITEBYTECODE=1 CUDA_VISIBLE_DEVICES='' .venv/bin/python docs/technical-reviews/artifacts/phase4-13_16-independent/variants.py > docs/technical-reviews/artifacts/phase4-13_16-independent/variants-stdout.txt 2> docs/technical-reviews/artifacts/phase4-13_16-independent/variants-stderr.txt", "exit_code": 0, "stdout": "variants-stdout.txt", "stderr": "variants-stderr.txt"},
 {"command": "timeout 40s .venv/bin/python docs/technical-reviews/artifacts/phase4-13_16-independent/render.py > docs/technical-reviews/artifacts/phase4-13_16-independent/render-stdout.txt 2> docs/technical-reviews/artifacts/phase4-13_16-independent/render-stderr.txt", "exit_code": 1, "attempt": "file URL", "saved_code": "render-fileurl-code.py", "saved_stderr": "render-fileurl-stderr.txt", "diagnosis": "ERR_BLOCKED_BY_ADMINISTRATOR; no timeout"},
 {"command": "timeout 40s .venv/bin/python docs/technical-reviews/artifacts/phase4-13_16-independent/render.py > docs/technical-reviews/artifacts/phase4-13_16-independent/render-stdout.txt 2> docs/technical-reviews/artifacts/phase4-13_16-independent/render-stderr.txt", "exit_code": 0, "attempt": "same HTML via set_content", "stdout": "render-stdout.txt", "stderr": "render-stderr.txt", "personally_viewed": ["desktop.png", "mobile.png"]},
]
for url, filename, seconds in [("https://arxiv.org/pdf/1606.06565v2", "concrete-problems-v2-original.pdf", 45), ("https://docs.python.org/3.13/library/functions.html", "python313-builtins-original.html", 40), ("https://docs.python.org/3.13/library/stdtypes.html", "python313-stdtypes-original.html", 35), ("https://raw.githubusercontent.com/birdhackor/tiny-perceptron-vlm/1df335318bda03fd771807f66976953231d5a00b/docs/course-experiments/results/posttraining.json", "posttraining-public-1df3353.json", 35)]:
    commands.append({"command": "curl --fail --location --max-time " + str(seconds) + " --output " + REL + "/" + filename + " " + url, "exit_code": 0, "snapshot": filename, "sha256": sha(A / filename)})
write(A / "commands.json", {"cwd": str(ROOT), "recorded_on": datetime.now(UTC).isoformat(), "commands": commands})
manifest = {"source": "course/chapters/13.md#13.16", "source_sha256": hashlib.sha256(current).hexdigest(), "raw_bytes_policy": "original UTF-8 section bytes, no stripping/newline normalization", "frozen_whole_chapter_input": {"snapshot": REL + "/chapter13-frozen-input.md", "sha256": sha(A / "chapter13-frozen-input.md"), "meaning": "frozen input at first section extraction; not future current whole-chapter version; read scopes below"}, "read_scopes": {"course/chapters/13.md": ["13.16 complete incl details, first line 579", "13.12–13.15 complete as prerequisites"], "scripts/course_experiments/posttraining.py": ["AST definitions first", "1–162", "188–253", "256–389", "414–460; result interpretation dictionary not read"], "tiny_perceptron/posttraining.py": ["AST first; 1–65"]}, "figure_references": [], "raw_measurement_snapshot": {"path": REL + "/posttraining-original.json", "sha256": sha(A / "posttraining-original.json"), "pointers_file": REL + "/measurement-audit.json"}}
write(A / "input-manifest.json", manifest)
artifacts = []
execution_names = {"original-execution.json": ("original-fence-execution", commands[1]["command"], "exit 0; original fence chose incorrect long response, task check False"), "audit-stdout.txt": ("measurement-execution", commands[3]["command"], "exit 0; raw rows/denominators/table/provenance recomputed; saved public file identical"), "variants-stdout.txt": ("variants-execution", commands[4]["command"], "exit 0; original [1,14], exercise [1,0]; exact equality limitation; bounded KL/PPO counterexample"), "render-stdout.txt": ("render-execution", commands[6]["command"], "exit 0; desktop/mobile saved and personally viewed")}
for path in sorted(A.iterdir()):
    assert path.is_file() and not path.is_symlink()
    assert path.suffix.lower() not in {".pt", ".pth", ".safetensors", ".zip", ".gz", ".tar"}
    if path.name in execution_names:
        identifier, command, result = execution_names[path.name]
        item = {"id": identifier, "kind": "execution", "command": command, "result": result, "environment": environment}
    else:
        identifier = path.name.replace(".", "-")
        kind = "figure_render" if path.suffix == ".png" else "code" if path.suffix == ".py" else "derivation" if path.name in {"source-inspection.md", "input-manifest.json", "measurement-audit.json"} else "source_snapshot"
        item = {"id": identifier, "kind": kind}
    item.update(path=path.relative_to(ROOT).as_posix(), sha256=sha(path), description="13.16 independent evidence: " + path.name)
    artifacts.append(item)
sources = []
def external(identifier, kind, title, url, version, why, inspection):
    sources.append({"id": identifier, "kind": kind, "title": title, "url": url, "version": version, "authority_reason": why, "verified": True, "checked_original": True, "accessed_on": "2026-10-05", "inspection_note": inspection})
external("reward-hacking", "paper", "Concrete Problems in AI Safety", "https://arxiv.org/pdf/1606.06565v2", "arXiv 1606.06565v2, 25 Jul 2016", "Original authors' paper from arXiv", "Personally checked first-page identifier and sec4 pp7–8; original saved concrete-problems-v2-original.pdf; source-inspection.md records own support.")
external("ppo", "paper", "Proximal Policy Optimization Algorithms", "https://arxiv.org/pdf/1707.06347v2", "arXiv 1707.06347v2, 28 Aug 2017", "Original PPO authors' paper", "Personally read sec3 eq6–7 and Figure1; original version checked from first page, copied from immutable locator without reading old report.")
external("dpo", "paper", "Direct Preference Optimization", "https://arxiv.org/pdf/2305.18290v3", "arXiv 2305.18290v3, 29 Jul 2024", "Original DPO authors' paper", "Personally read sec3 eq3 and sec4 eq4; version checked; bounded reward/KL inference documented in variants.py and source-inspection.md.")
external("instructgpt", "paper", "Training language models to follow instructions with human feedback", "https://arxiv.org/pdf/2203.02155v1", "arXiv 2203.02155v1, 4 Mar 2022", "Original InstructGPT authors' paper", "Personally read sec3.5 RL objective eq2 and KL mitigation statement, version checked from first page.")
external("python-functions", "official_docs", "Python built-in functions", "https://docs.python.org/3.13/library/functions.html", "Python 3.13 documentation; runtime CPython 3.13.5", "Official Python Software Foundation documentation", "Personally checked len/max/int exact original anchors and saved original HTML plus excerpts; list comprehension/range behavior additionally executed.")
external("python-types", "official_docs", "Python built-in types", "https://docs.python.org/3.13/library/stdtypes.html", "Python 3.13 documentation; runtime CPython 3.13.5", "Official Python Software Foundation documentation", "Personally checked str Unicode sequences/constructor, comparisons and bool/int; saved original HTML plus inspected excerpts.")
for identifier, path, inspection in [("experiment-code", "scripts/course_experiments/posttraining.py", "AST first; read 1–162,188–253,256–389,414–460. Read data/rule/split/evaluation and updates; skipped result interpretation dictionary. Exact ranges and source SHA in input-manifest.json."), ("ppo-helper", "tiny_perceptron/posttraining.py", "AST first; read lines1–65 for ppo_clipped_objective and exact_kl contracts; bounded gradient executed, no training.")]:
    sources.append({"id": identifier, "kind": "repository_code", "title": path, "path": path, "sha256": sha(ROOT / path), "version": "Original implementation hash matches recorded run /code_sha256; frozen snapshot retained", "verified": True, "inspection_note": inspection})
sources += [{"id": "raw-audit", "kind": "execution", "title": "Independent arithmetic audit of saved raw records", "verified": True, "artifact_id": "measurement-execution"}, {"id": "short-checks", "kind": "execution", "title": "Literal fence, exercise and bounded counterexamples", "verified": True, "artifact_id": "variants-execution"}]
claims = []
def evidence(source, locator, support): return {"source_id": source, "locator": locator, "supports": support}
def add(identifier, kind, statement, location, scope, ev, arts, verification=None):
    c = {"id": identifier, "kind": kind, "statement": statement, "location": location, "scope": scope, "status": "verified", "evidence": ev, "artifact_ids": arts}
    if verification: c["verification"] = verification
    claims.append(c)
def verification(expected, observed, details, denominators=None, tolerance=None):
    v = {"method": "executed", "expected": expected, "observed": observed, "details": details}
    if denominators: v["denominators"] = denominators
    if tolerance: v["tolerance"] = tolerance
    return v
add("reward-hack-definition", "concept", "A strategy can receive a high score while failing the intended task by exploiting the reward criterion; no human deception intention is needed for this mechanistic example.", "13.16 opening paragraph", "Concept definition; deterministic selector is an illustrative score exploit, not evidence that a trained policy hacked a learned RM.", [evidence("reward-hacking", "sec4 pp7–8 opening paragraphs and Goodhart's Law", "Formal objective can be gamed by solutions that fail intended task; examples include optimization systems without a human psychology claim.")], ["concrete-problems-v2-original-pdf", "source-inspection-md", "variants-execution"])
add("literal-fence-and-exercise", "software", "len scores the two strings [1,14]; max(key=scores) selects the incorrect long answer and exact task check is False. The prescribed int(exact equality) exercise selects 3 and True.", "13.16 Python fence and exercise", "CPython 3.13.5 on these literal strings; length counts Unicode code points and is not a universal grapheme count.", [evidence("python-functions", "#len, #max, #int", "Length/ordering/explicit bool-to-int behavior."), evidence("python-types", "#text-sequence-type-str; #boolean-type-bool; #comparisons", "String representation, Unicode sequence and equality semantics."), evidence("short-checks", "variants.py literal original exec and exact prescribed replacement", "Both original and exercise actually run.")], ["original-fence-execution", "variants-execution", "fence-1-py", "exercise-literal-py", "variants-py"], verification("Original chooses long sentence/False; exercise chooses 3/True", "Exactly those outputs; original scores[1,14], exercise[1,0]", "Original fence unmodified via helper exit0, no guard events; exercise replaced one expression and retained comprehension/range/key/lambda."))
add("constraints-do-not-correct-reward", "concept", "A fixed reference or PPO clipping does not itself replace a wrong reward criterion with task correctness.", "13.16 paragraph after Python fence", "A claim about what the objective/constraint specifies, not that KL/clipping can never mitigate overoptimization or accidentally improve outputs.", [evidence("ppo", "sec3 eq7, Figure1", "Clipping modifies advantage-based incentive, with no new truth/format reward."), evidence("dpo", "sec3 eq3 and sec4 eq4", "Reward-minus-reference-KL and closed-form policy retain supplied reward."), evidence("instructgpt", "sec3.5 eq2", "KL described as mitigation of RM overoptimization, not a ground-truth criterion.")], ["variants-execution", "variants-py", "dpo-v3-original-pdf", "ppo-v2-original-pdf", "instructgpt-v1-original-pdf"], None)
add("finite-task-contract", "empirical", "The saved experiment selects prewritten cards; final18 contexts are held out as6 families with6 examples per condition. Success is the independently fixed full-request action.", "13.16 paragraph introducing table", "Finite template-generated selector, not learned Chinese reading, arithmetic, or token generation; no new training performed.", [evidence("experiment-code", "rule_best_action58–60; build_records63–106; split_records109–121; _evaluate188–253", "Independent mode/action rule, templates, family split and greedy success contract."), evidence("raw-audit", "audit.py and measurement-audit.json /splits/test", "Recomputes cardinalities and verifies no family overlaps; compares raw samples to original templates.")], ["measurement-execution", "audit-py", "measurement-audit-json", "posttraining-original-json"], verification("18 test contexts,6 in each mode; family-disjoint split44/5/6", "Exact counts match and independent full-request rule agrees with all saved labels", "Recomputed from preserved raw records; task checker uses mode and candidate contract, not learned reward. Final evaluation occurs after branch weights fixed at original lines448–451.", {"test_contexts":18,"test_families":6,"contexts_per_condition":6,"train_families":44,"validation_families":5}))
add("test-results-table", "empirical", "Table per-mode results are start6/6,0/6,0/6; PPO and DPO6/6,0/6,6/6. Overall success is6/18,12/18,12/18.", "13.16 table", "Greedy highest-probability card under finite full-request rule; ratios are correct-context counts, not tokens or generated answers.", [evidence("raw-audit", "/results/evaluations/test/rows/*/policies; audit.py successes and by_mode comparison", "Each saved probability vector re-argmaxed and checked against independent desired action; table totals recomputed."), evidence("experiment-code", "_evaluate lines204–230", "Greedy candidate success numerator/denominator and per-mode aggregation.")], ["measurement-execution", "measurement-audit-json", "audit-py", "posttraining-original-json", "desktop-png", "mobile-png"], verification("Exact table counts", "All12 table cells match re-argmaxed raw rows; totals6,12,12 over18", "No model run; probability-sum tolerance2e-7; integer numerators and denominators exact.", {"test_contexts":18,"per_mode":6,"policies":3}))
add("rm90-distinct-from-policy", "empirical", "Reward model ranks all last90 preference pairs correctly while policies fail some full requirements;90/90 reward ranking is not90/90 policy task success.", "13.16 paragraphs after table and details", "90 binary comparisons across18 prompts; four candidates generate6 pairs for number/explain and3 for missing, giving6×(6+6+3)=90.", [evidence("raw-audit", "/results/evaluations/test/rows/*/preference_pairs and reward_model_raw_scores; audit.py pair loop", "Strict raw reward>winner/loser recomputation gives90/90."), evidence("experiment-code", "build_records63–106 and _evaluate188–230", "Pairwise metric and independent greedy task metric use distinct units.")], ["measurement-execution", "audit-py", "measurement-audit-json", "posttraining-original-json"], verification("90 strict correctly ordered pairs; incomplete policy success", "90/90 correct reward pairs and6/18,12/18,12/18 task success", "Pairs recomputed from candidates for all18 saved rows. Two distinct denominators retained.", {"preference_pairs":90,"contexts":18,"candidate_actions_per_context":4}))
add("explanation-failure-scope", "empirical", "Both branches fail the finite explanation condition even on training0/44; recorded failures do not show a learned-RM reward exploit.", "13.16 no-observed-hacking paragraph and expanded details", "Observation restricted to saved finite train/validation/test rows; no statement that hacking is impossible elsewhere, nor diagnosis of why optimization failed.", [evidence("raw-audit", "/results/evaluations/train/rows/*/mode, policies, reward_model_raw_scores; analogous test rows", "Both trained greedy explanation successes0/44; every observed RM-best card meets rule, and failed explanation card is lower scoring than sentence."), evidence("experiment-code", "_evaluate188–253 and original training loops256–389,414–430", "Fixed recipe separates trained reward ranking from trained selector success.")], ["measurement-execution", "measurement-audit-json", "audit-py"], verification("train explanation0/44 for both branches; no observed reward rank inversion", "Exact0/44 for PPO,DPO and test0/6; all raw RM top choices match independent full-request card", "Data support condition not learned in this fixed run, including training side; not merely unseen-family failure. No trained model was rerun.", {"training_explanation_contexts":44,"test_explanation_contexts":6,"trained_branches":2}))
add("one-plus-two-raw-example", "numeric", "For explanation1+2, raw reward sentence≈13.5565 and short≈8.7679; PPO short≈0.7928 and sentence≈0.2014, so greedy still selects3.", "13.16 expanded details first paragraph", "One preserved test sample; scores are unnormalized RM scalars, probabilities refer to separate four-card PPO distribution.", [evidence("raw-audit", "/results/evaluations/test/rows/4/reward_model_raw_scores and /policies/ppo/probabilities", "Exact values13.556549072265625,8.767887115478516,.7928321957588196,.2014310657978058; chosen_response3."), evidence("experiment-code", "_evaluate235–251", "Saved raw score/probability/chosen response interpretation.")], ["measurement-execution", "measurement-audit-json", "audit-py"], verification("Each approximation within5e-5; short probability exceeds sentence", "All four within5e-5; chosen action0,response3; content correct True/full request False", "Original indices0=short,1=sentence checked against saved candidates; sum of all four probs within2e-7 of1. No mixing RM score scale and policy probabilities.", tolerance="Absolute tolerance0.00005 for displayed four-decimal approximations; integer action/response exact."))
add("independent-task-evaluation", "concept", "Task completion should be checked against task truth, scope, format and necessary information rather than assuming the same reward scorer certifies success.", "13.16 task-check paragraphs", "Method recommendation illustrated by finite independent rule and saved raw responses; no broad empirical superiority claim.", [evidence("reward-hacking", "sec4 pp7–8 imperfect objectives and Goodhart's Law", "A proxy score need not mean intended objective completed."), evidence("experiment-code", "rule_best_action58–60 and _evaluate188–253", "Concrete independent finite task rule and retained chosen_response.")], ["source-inspection-md", "measurement-execution", "concrete-problems-v2-original-pdf"])
add("exact-match-and-explanation-limits", "concept", "Exact string equality is suitable for this canonical numeric answer but cannot directly grade open explanations with multiple valid phrasings; the finite sentence-card criterion does not measure explanation depth.", "13.16 exercise and both details paragraphs", "Canonical3 only in this prescribed numeric task. The explanation score is explicitly bounded to fixed equation/result sentence selection.", [evidence("python-types", "#text-sequence-type-str and #comparisons", "String values/equality do not implement semantic equivalence."), evidence("experiment-code", "build_records lines85–104; rule_best_action58–60", "Sentence candidate fixed arithmetic/result template, full request checks only best card id."), evidence("short-checks", "variants.py paraphrases check", "Two valid explanation strings both fail literal equality to3; illustrative bound.")], ["variants-execution", "source-inspection-md", "python313-stdtypes-excerpts-txt"])
report = {"schema_version":1,"review_stage":"technical","lesson_id":"13.16","source":"course/chapters/13.md#13.16","source_sha256":hashlib.sha256(current).hexdigest(),"verdict":"pass","reviewer_task":"/root/phase4_factual_coordinator/factual_13_16","reviewer_context":"fresh","reviewed_on":"2026-10-05","figure_sha256":{},"frozen_input":manifest["frozen_whole_chapter_input"],"read_scope":manifest["read_scopes"],"claims":claims,"sources":sources,"artifacts":artifacts,"issues":[],"checks":{
 "factual_accuracy":{"status":"pass","details":"Personally checked reward hacking definition, reward/constraint roles, finite task and independent task metric. Every substantive claim listed separately; no unknown/counterevidenced claim retained as verified.","claim_ids":[c["id"] for c in claims]},
 "numeric_verification":{"status":"pass","details":"Executed raw JSON arithmetic for all rows, all pairs, all table denominators,train0/44 and sample scores/probabilities; no model training or scoring rerun. Four-decimal approximation tolerance5e-5; integer counts exact.","claim_ids":["test-results-table","rm90-distinct-from-policy","explanation-failure-scope","one-plus-two-raw-example"]},
 "figure_consistency":{"status":"not_applicable","details":"No referenced figures. Isolated section HTML including table/details actually rendered and personally viewed at1280×800 and390×844; labels/counts agree with text/raw measurements. This is not a published-site styling test.","claim_ids":["test-results-table"]},
 "source_verification":{"status":"pass","details":"Personally inspected authoritative exact-version original PDFs and Python3.13 docs; own locations/support recorded. Original raw experiment file and immutable public commit are byte-identical; implementation provenance hashes match. Old review summaries unused.","claim_ids":[c["id"] for c in claims]},
 "limitations":{"status":"pass","details":"Manual length counterexample is separated from existing policy measurement; finite prewritten-card/greedy criterion and explanation-depth limit preserved. No observed hacking is bounded to saved rows, not absence everywhere. No full training/GPU/data/weight loading/model-run rerun. Chromium file URL policy block preserved; same HTML set_content succeeded; first reviewer-audit KeyError retained and fixed before successful audit.","claim_ids":["reward-hack-definition","constraints-do-not-correct-reward","finite-task-contract","explanation-failure-scope","exact-match-and-explanation-limits"]}}}
target = ROOT / "docs/technical-reviews/13.16.json"
write(target,report)
confirmation = json.loads(target.read_bytes())
assert confirmation["reviewer_task"] == report["reviewer_task"] and confirmation["source_sha256"] == report["source_sha256"]
print(json.dumps({"canonical_report":target.relative_to(ROOT).as_posix(),"source_sha256":report["source_sha256"],"report_sha256":sha(target),"verdict":report["verdict"],"claims":len(claims),"artifacts":len(artifacts),"canonical_confirmed":True},ensure_ascii=False))
