"""Build only this reviewer's 19.12 report from genuine local evidence."""
import hashlib
import json
import shlex
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[5]
ART = Path(__file__).resolve().parent
def sha(p):
    return hashlib.sha256(p.read_bytes()).hexdigest()
def relative(p):
    return p.relative_to(ROOT).as_posix()

r = json.loads((ART / "probe.stdout.json").read_text())
environment = r["environment"]
artifacts = []
def artifact(id, kind, path, description, **extra):
    p = ROOT / path
    artifacts.append(dict(id=id, kind=kind, path=path, sha256=sha(p), description=description, **extra))
prefix = relative(ART) + "/"
artifact("a_probe", "execution", prefix + "probe.stdout.json", "Independent CPU raw-ID/EOS/tool rescoring of fixed official GPU records, table arithmetic, pair comparisons and timing medians; current dataset and architecture execution.", command=".venv/bin/python " + prefix + "probe.py", result="Exit 0; every independently reconstructed action/final answer/summary matches original records. All 19.12 tables, swaps, changes and medians agree.", environment=environment)
artifact("a_probe_code", "code", prefix + "probe.py", "Own independently written bounded CPU probe; no official-weight inference or training.")
artifact("a_probe_stderr", "source_snapshot", prefix + "probe.stderr.txt", "Genuine empty stderr of the successful CPU probe.")
artifact("a_probe_command", "source_snapshot", prefix + "probe-command.json", "Actual command, return code and Python version from subprocess wrapper.")
artifact("a_snippet", "execution", prefix + "lesson-snippet.stdout.txt", "Exact unmodified lesson Counter code executed using current build_dataset; prints the 12 task counts and total 90.", command=".venv/bin/python -c " + shlex.quote((ART / "lesson-snippet.py").read_text()), result="Exit 0; audio 6, calculator 12, concept 6, image_color 9, image_shape 9, joint 18, missing 3, rag 3, safety 3, style 3, tool_return 6, unavailable 12; sum 90.", environment=environment)
artifact("a_snippet_code", "code", prefix + "lesson-snippet.py", "Exact Python block extracted from the assigned current raw section.")
artifact("a_snippet_stderr", "source_snapshot", prefix + "lesson-snippet.stderr.txt", "Genuine empty stderr of exact lesson code.")
artifact("a_original_receipt", "source_snapshot", prefix + "original-retrieval.json", "Actual original HTTPS URLs, document versions encoded in URLs, retrieval method, original-byte SHA and sizes; full third-party texts remain ignored.")
artifact("a_original_analysis", "derivation", prefix + "original-inspection.md", "Own exact original locators, source interpretation, micro/macro arithmetic, pooling collision argument and limits.")
artifact("a_section", "source_snapshot", prefix + "reviewed-section.md", "Full current assigned raw UTF-8 section including all blank lines.")
artifact("a_prerequisites", "source_snapshot", prefix + "prerequisite-receipt.json", "Actually read necessary prerequisite sections, exact raw section SHAs, introduction NA and no used SVG.")
artifact("a_prerequisites_first", "source_snapshot", prefix + "prerequisite-receipt-first-read.json", "Preserved first-read prerequisite receipt before 19.10's later source update; no previous review judgment read.")
artifact("a_prerequisite_old_body", "source_snapshot", prefix + "prerequisite-19.10-first-read.md", "Exact original-only pre-edit 19.10 bytes whose hash matches my preserved first-read receipt; no donor judgment supplied.")
artifact("a_code_binding", "source_snapshot", prefix + "code-version-binding.json", "Actual current full-file SHAs equal corresponding frozen official deployment run code SHAs for inspected core/scoring/training/compression functions.")
artifact("a_training_scope", "source_snapshot", prefix + "training-scope.json", "Own direct inspection and CPU hash/JSON checks of four original GPU stage records: complete 300/1400/600/100 schedules, seed 42, effective positions, and exact parent/export SHA links. No GPU replication.")
artifact("a_prerequisite_current", "source_snapshot", prefix + "prerequisite-19.10-current.md", "Full revised 19.10 personally reread after genuine current-reader closure, including all blank lines.")
artifact("a_rms_context", "source_snapshot", prefix + "prerequisite-14.2-current.md", "Full newly linked 14.2 normalization context personally read; its separate empirical results do not become 19.12 claims.")
artifact("a_reassessment", "derivation", prefix + "prerequisite-reassessment.json", "Own substantive recheck of changed RMSNorm definition, actual current source bytes, affected compression/student claims, and personally viewed prerequisite SVG.")
artifact("a_svg_render", "figure_render", prefix + "normalization-context.png", "Personally viewed the feature-only normalization context: arrows, [1,2,3] input, distinct LN/RMS rules, gamma/LN-only beta and same-shape output agree with current 14.2 text.")
artifact("a_svg_render_receipt", "execution", prefix + "render-context.stdout.json", "Genuine Chromium rasterization and original/render SHA receipt for the newly linked prerequisite SVG.", command="python " + prefix + "render_context.py", result="Exit 0; personally viewed rendered PNG with view_image after this command. Initial file-URL navigation was blocked; supported inline SVG rendering succeeded with no policy/configuration change.", environment={"python":"3.12.14","playwright":"1.62.0","browser":"Chromium 151.0.7922.173","device":"cpu","viewport":"800x330, reduced motion"})
artifact("a_svg_render_code", "code", prefix + "render_context.py", "Own actual inline-SVG Chromium rendering code; uses existing installed browser without downloads.")
input_ids = {}
for i, path in enumerate(r["inputs"], 1):
    assert sha(ROOT/path) == r["inputs"][path]["sha256"], "An original probe input changed: " + path
    id = f"a_input_{i}"
    input_ids[path] = id
    artifact(id, "source_snapshot", path, "Original first-party run/data/selection input personally inspected and independently processed; SHA also recorded by own probe. Not a prior technical/reader review.")

sources = []
def code(id, path, note):
    sources.append(dict(id=id, kind="repository_code", title=path, path=path, sha256=sha(ROOT/path), version="Current exact checkout bytes; full-file SHA in this source record", verified=True, inspection_note=note))
code("s_core", "tiny_perceptron/capstone.py", "Read default_config/CapstoneModel lines34–121, build_dataset139–282, modality_tensors285–296, encode_record308–320, preference_pairs/loss341–377, generate/evaluate/parse/runtime379–608. Fixed byte protocol, pooled inputs, exact first/final scoring and synthetic data.")
code("s_data", "tiny_perceptron/data.py", "Read ByteTokenizer lines14–28: eight specials, EOS ID2, bytes shifted by8; independently decoded original raw IDs in CPU probe.")
code("s_train", "scripts/course_experiments/capstone.py", "Read train_stage and update loop lines69–216: immediate predecessor loading, pretrain/SFT text rows, joint all rows, frozen DPO comparison branch and objective.")
code("s_deploy", "scripts/course_experiments/capstone_deployment.py", "Read cache_consistency83–143, benchmark_generation203–271, run273–390, plus image_counterfactuals imported in executed probe: preselected validation IDs, synchronized FP32 timing and reloaded PTQ evaluation.")
code("s_student", "scripts/course_experiments/capstone_student.py", "Read _train_student34–148 and run150–225: same Dense random start, DPO teacher path frozen/eval, CE vs KD,350 updates, saved/reloaded4-bit student and test evaluations.")
code("s_alignment", "tiny_perceptron/alignment.py", "Read distillation_kl45–55 and distillation_loss58–64: teacher detached, valid answer targets, temperature-softened distribution and T²; CE teacher-independent, KD mixed.")
code("s_quant", "tiny_perceptron/capstone_quantization.py", "Read quantizable_weights21–26, quantize_capstone37–115 and restoration117–178: nonrouter Linear packing, serialized reload and FP32 reconstruction. No low-bit speed inference.")
code("s_modern", "tiny_perceptron/modern.py", "Read MoEFFN56–89: all expert modules stored in ModuleList, top-k dispatch only chosen rows. After prerequisite correction also read RMSNorm8–16: reciprocal root-mean-square scaling without mean subtraction. No code changed.")
code("s_natural", "tiny_perceptron/natural_assistant.py", "Read load_core263–289, load_asr687–696, actual transcript routing859–877 and915–940: upstream Qwen model separate from capstone, optional LoRA, frozen Whisper -> same core.")
receipts = {x["id"]: x for x in json.loads((ART/"original-retrieval.json").read_text())}
def original(id, kind, title, receipt, version, authority, note):
    rr = receipts[receipt]
    sources.append(dict(id=id, kind=kind, title=title, url=rr["url"], version=version, verified=True, checked_original=True, accessed_on="2026-10-04", authority_reason=authority, inspection_note=note, original_byte_sha256=rr["sha256"]))
original("s_sft", "paper", "Training language models to follow instructions with human feedback", "instructgpt", "arXiv2203.02155v1,4March2022", "Original authors' version from arXiv original PDF.", "Personally read printed p2 next-token objective and p6 §3.1 Step1 supervised demonstrations. Supports stage definitions, not capstone performance.")
original("s_dpo", "paper", "Direct Preference Optimization: Your Language Model is Secretly a Reward Model", "dpo", "arXiv2305.18290v3,29July2024", "Original DPO authors' arXiv version.", "Personally read §3 pp3 and §4 pp4–5 Eq7/gradient explanation: same-prompt preferred/dispreferred completion relative to fixed reference. Synthetic preferences and capstone mixed objective remain explicit limits.")
original("s_kd", "paper", "Distilling the Knowledge in a Neural Network", "distilling", "arXiv1503.02531v1,9March2015", "Original Hinton/Vinyals/Dean distillation paper.", "Personally read §2 pp2–3 Eq1 and hard/soft weighted objectives with temperature/T². Teacher distribution teaching is a method, not a guarantee of retained ability.")
original("s_switch", "paper", "Switch Transformers: Scaling to Trillion Parameter Models with Simple and Efficient Sparsity", "switch", "JMLR23(120),2022 publisher final PDF,publishedApril2022", "Original peer-reviewed publisher article by MoE authors.", "Personally read §2.1 pp3–5 Eqs1–2 and §5 pp18–21, particularly5.2/5.5. Sparse selected computation retains total expert weights; sharding changes residency. Does not guarantee this Python implementation is faster.")
original("s_bias", "paper", "On Over-fitting in Model Selection and Subsequent Selection Bias in Performance Evaluation", "selectionbias", "JMLR11,2010,2079–2107 publisher final", "Original Cawley/Talbot publisher paper on evaluation selection bias.", "Personally read abstract and §5/5.1 pp2094–2095: treat model selection as fitting and avoid selection leakage into final performance estimates. Historical sequencing established only by project records.")
original("s_qwen_card", "official_docs", "Qwen3-VL-2B-Instruct original model card", "qwenreadme", "modelrevision89644892e4d85e24eaac8bacfd4f463576704203", "Official upstream Qwen model publisher.", "Read introduction, Key Enhancements pretraining and repository identity; confirms upstream pretrained image-text model. Marketing performance claims are not adopted as evidence.")
original("s_qwen_config", "official_source", "Qwen3-VL-2B-Instruct original config", "qwenconfig", "modelrevision89644892e4d85e24eaac8bacfd4f463576704203", "Official publisher's machine-readable pinned architecture configuration.", "Read full1505-byte config: Qwen3VLForConditionalGeneration/qwen3_vl_text,28layers,width2048; distinct from capstone MoE.")
original("s_qwen_code", "official_source", "Transformers Qwen3VL Dense MLP implementation", "qwensource", "Transformersv4.57.0", "Official Transformers source for pinned Qwen3VL architecture type.", "Personally read modeling_qwen3_vl.py460–485: dense gate/up/down projections applied to every input and instantiated by decoder; no expert dispatch. Used for architecture identity only, not a claim of executing this older library version.")
sources.append(dict(id="s_cpu", kind="execution", title="Own CPU fixed-record rescoring and current-code probe", verified=True, artifact_id="a_probe"))
sources.append(dict(id="s_weighting", kind="derivation", title="Micro and equal-task weighting", verified=True, details="If task j has n_j rows and c_j correct, micro=sum_j c_j/sum_j n_j and equal-task=mean_j(c_j/n_j). Changing n_j changes the micro weight n_j/sum n. With12 current joint tasks,78/90=0.8666666667 while equal-task=(10/12+1+5/6+1+1+0+1+1+1+1+1+1)/12=0.8888888889. CPU independently executes both; no additional course metric is claimed."))
claims = []
def evidence(id, locator, supports):
    return dict(source_id=id, locator=locator, supports=supports)
def claim(id, kind, statement, location, ev, scope, artifact_ids=None, expected=None, observed=None, details=None, denominators=None, tolerance=None):
    c=dict(id=id, kind=kind, statement=statement, location=location, status="verified", evidence=ev, artifact_ids=artifact_ids or [], scope=scope)
    if kind != "concept":
        c["verification"]=dict(method="executed", expected=expected, observed=observed, details=details)
        if denominators is not None: c["verification"]["denominators"]=denominators
        if tolerance: c["verification"]["tolerance"]=tolerance
    claims.append(c)
def inputs(*paths):
    return ["a_probe"]+[input_ids[p] for p in paths]
base="docs/course-experiments/capstone-evidence/"
claim("c1", "software", "The Counter example only counts fixed test tasks, totaling90; rag is provided-context QA, tool_return a provided calculator return, unavailable disabled-calculator questions.", "19.md:630–642", [evidence("s_core", "build_dataset139–282", "Actual task construction and split."),evidence("s_cpu", "counts; manifest_sha", "Current dataset equals saved official original inputs.")], "Dataset inventory, not generated accuracy;552/84/90 family-disjoint rows,seed42,capstone-small-world-v2.", ["a_snippet","a_snippet_code","a_probe",input_ids[base+"deployment/data.json"]], "12 task counts total90", "Exact lesson code prints12 tasks,total90; current splits equal saved originals", "Run exact extracted code and current build_dataset; no model generation.")
claim("c2", "numeric", "Row-weighted and equal-task averages have different weights; a frequent successful task can mask failures in another task.", "19.md:624,642", [evidence("s_weighting", "micro and equal-task formulas", "Complete arithmetic showing weighting difference.")], "Transparent arithmetic for this table, not a statistical claim about unseen inputs.", ["a_probe","a_original_analysis"], "Micro78/90 differs from equal-task mean", "0.8666666666666667 versus0.8888888888888888", "Sum successes/counts versus mean12 task ratios.", tolerance="Exact rational identity; Python double values within1e-12.")
claim("c3", "concept", "Pretraining learns next text units, SFT learns demonstrated answers; this project's joint trains text/image/audio/tool tasks; DPO compares preferred answers for the same prompt.", "19.md:626", [evidence("s_sft", "p2 andp6 §3.1Step1", "Next-token versus supervised demonstrations."),evidence("s_dpo", "§4 Eq7 pp4–5", "Same-prompt preference comparison."),evidence("s_train", "train_stage,text_rows/rows andpairs lines117–121", "Project-defined joint and DPO stage scope.")], "Byte-level small-world stages; project DPO is synthetic and includes CE/router terms, not an RLHF completion claim.", ["a_original_analysis"])
claim("c4", "concept", "Choose weights using a predeclared validation rule, then keep test independent; final equal scores do not erase previous validation regression.", "19.md:626,683,708", [evidence("s_bias", "§5/5.1 pp2094–2095", "Selection belongs to fitting, so selection-set maxima cannot serve as independent final performance.")], "Evaluation design rule; historical project decisions separately validated against original selection/run records.", ["a_original_analysis"])
claim("c5", "software", "action_correct requires first generated EOS and exact complete expected_action, including toolname/ordered args or DIRECT/ASK content; end_to_end also requires exact final truth, with a second generation only for successful tool execution.", "19.md:646–648,668", [evidence("s_core", "evaluate_rows499–546;parse_action550–561;calculator_runtime564–574", "Exact scoring and final EOS requirement through parsing."),evidence("s_data", "ByteTokenizer14–28", "EOS and raw byte decoding."),evidence("s_cpu", "record_rescoring; joint_failures", "Independently decoded/parsed first and final sequences plus runtime arithmetic.")], "This project's exact protocol differs from B.7 marker-only classification; final answer parsing rejects missing EOS.", inputs(base+"deployment/test-joint.json"), "DIRECT:circle differs fromDIRECT:square; DIRECT:0 differs fromDIRECT:1 despite legal syntax/EOS", "Derived flags match all stored records; two calculator first-action successes fail final answers0 and111 for truth1", "Decode IDs subtract8, derive EOS2, independently parse raw text, verify source/followup prompts, calculate runtime and compare exact strings.")
joint_tasks=r["record_rescoring"]["joint"]["by_task"]
claim("c6", "empirical", "Joint's complete per-task table is80/90 first actions and78/90 end-to-end, with calculator12/12→10/12, tool_return5/6, green color9/9, shapes0/9, joint18/18 and audio6/6; other rows exactly match the table and narrow limitations.", "19.md:644–664", [evidence("s_cpu", "record_rescoring.joint; joint_failures; labels", "Full table reconstructed from raw IDs and original questions/material specifications."),evidence("s_core", "build_dataset139–210;modality_tensors285–296", "Only RGB shapes, two tone groups, fixed templates and addition calculator.")], "Original seed42 L4 run records only; no own GPU training/inference. Fixed synthetic test cannot establish natural photos/OCR/human speech/web search/general safety/calibration. Constant labels are explicitly limited.", inputs(base+"deployment/test-joint.json",base+"deployment/data.json","docs/course-experiments/results/capstone_deployment.json"), "Per-task table and totals as written", "All12 task numerator/denominator entries match;80 first actions,78 completed;9 shapes allDIRECT:circle;two tool results1 read as0/111", "Independent row rescoring, labels and failures; no original accuracy flags trusted without recomputation.", {"test_rows":90,"seed":42,"split":"test, family-disjoint","task_counts":r["counts"],"joint_train_updates":600,"gpu_record_device":"NVIDIA L4"})
claim("c7", "empirical", "Outside3 successful password refusals,87 rows never produce that refusal sentence and75/87 finish correctly.", "19.md:666 first sentence", [evidence("s_cpu", "nonrefusal; joint_failures", "87 nonsafety rows and their actual first/final output contents.")], "Excludes that exact refusal pattern on this fixed test only; no universal false-refusal estimate.", inputs(base+"deployment/test-joint.json"), "3/3 refusals; no sentence on87 other rows;75/87 correct", "Matches exactly; incorrect tool finals are numeric0/111, all other failurescircle/0", "Subset by originaltask; inspect generated refusal occurrences and independently derived success.", {"safety_rows":3,"other_rows":87,"seed":42,"split":"same frozen test"})
claim("c8", "empirical", "Joint image pairs require both original and replacement correct:27/36 pairs, color9/9 shape0/9 joint18/18;18 audio-swap pairs all correct.", "19.md:666 remainder", [evidence("s_cpu", "image_pairs;audio_pairs", "ID-linked original/replacement success conjunction recomputed.")], "36 image pairs and18 overlapping joint audio pairs on synthetic heldout material; original wrong/replacement right shape is not success.", inputs(base+"deployment/test-joint-image-swaps.json",base+"deployment/test-joint-image-pairs.json",base+"deployment/test-joint-audio-swaps.json"), "27/36 imagepairs and18/18 audio pairs", "Exactly9/9 color,0/9shape,18/18joint;18/18audio", "Reconstruct replacement truth from original material specs, decode raw ID records, conjoin original and new correctness.", {"image_pairs":36,"image_color_pairs":9,"image_shape_pairs":9,"joint_image_pairs":18,"joint_audio_pairs":18,"seed":42,"split":"counterfactuals of frozen test,not independent new families"})
claim("c9", "empirical", "Same90-question final test: untrained0,pretrain300steps0,SFT45,joint78,DPO78,joint4/8-bit78each,DPO4/8-bit78each,CE62,KD61,KD4-bit61; equal scores do not imply equal generated IDs.", "19.md:668–683", [evidence("s_cpu", "record_rescoring;id_changes", "All12 raw-record versions independently rescored; both first/final ID differences counted."),evidence("s_quant", "quantize_capstone andrestore_quantized_payload", "Stored/reloaded versions are FP32-reconstructed quantized weights.")], "Same fixed90 rows,seed42 original GPU records; neither universal compression guarantee nor token identity. Pretrain300-step completion from original train report.", ["a_probe"]+[input_ids[p] for p in input_ids if "/test-" in p and "swaps" not in p and "pairs" not in p]+[input_ids[base+"pretrain/train-report.json"]], "All final version totals as published", "0,0,45,78,78,78,78,78,78,62,61,61; joint4-bit1changed,DPO4-bit2changed,8-bit0 observed", "Rescore same IDs/source questions/EOS/final tool output; independently compare action and final generated arrays.", {"test_rows_per_version":90,"versions":12,"seed":42,"pretrain_updates":300,"student_updates_per_branch":350,"split":"same frozen heldout test"})
claim("c10", "empirical", "Recommendation joint was recorded before test;joint75/84validation beatsDPO71/84,while their final test is78/90 each;DPO remains the precommitted student teacher.", "19.md:683,687", [evidence("s_cpu", "validation;selection;inputs capstone-selection.json", "Recomputed validation raw-output scores and read immutable choice fields."),evidence("s_student", "run150–176", "Teacher loaded explicitly from DPO dependency.")], "History supported by original selection/run records and frozen-source binding, not direct observation of past run order; own probe does not retrain/select on test.", inputs("docs/course-experiments/capstone-selection.json",base+"joint/validation.json",base+"dpo/validation.json","docs/course-experiments/results/capstone_student.json"), "Joint75/84,DPO71/84;selectedjoint;studentteacherDPO", "Exact validation sums;selectionflag true;studentteacher SHA equals DPO'sb2428be8… and differs fromjoint", "Independently rescore84validation rows, match selected checkpoint SHA and teacher provenance, inspect pretest selection decision.", {"validation_rows":84,"test_rows":90,"seed":42,"teacher_branch":"DPO,notjoint"})
claim("c11", "empirical", "12 preselected validation-task full/cache raw generated IDs match;one L4 short-copy generation has full/cache median68.054/59.978ms and no measured generation peak memory.", "19.md:685", [evidence("s_cpu", "cache_raw_ids_equal;timing", "ID equality and median recomputed from individual measurements."),evidence("s_deploy", "cache_consistency83–143;benchmark_generation203–271", "Selection,timing boundaries,synchronization and exclusions.")], "Recorded L4 FP32 measurements;not current CPU speed replication or universal speedup. Cache logit tensors unavailable;the lesson only claims raw ID equality. Does not add capability points.", inputs(base+"deployment/cache-consistency.json",base+"deployment/generation-benchmark.json","docs/course-experiments/results/capstone_deployment.json"), "12 matching sequences;medians68.054/59.978ms", "12/12 equal IDs/stops;unrounded68.05368149999858/59.97750799999935ms", "Check firstvalidation row per12 tasks,decode ID traces,recompute10 measured samples' median per mode excluding3 warmups;look at explicit no-memory measurement scope.", {"cache_task_inputs":12,"max_new_ids":16,"timing_prompts":1,"warmups_per_mode":3,"measured_per_mode":10,"generated_ids_including_EOS":10,"seed":42,"gpu":"NVIDIA L4","dtype":"FP32"})
claim("c12", "numeric", "The small Dense student has79,920parameters and capstone MoE328,128;these are distinct architectures.", "19.md:687,704", [evidence("s_core", "default_config34–48;CapstoneModel84–121", "Model construction and total parameter definition."),evidence("s_student", "run168–177", "Width48,Dense random student construction.")], "Current architecture counts verified on CPU;random construction does not validate trained quality.", ["a_probe"], "Dense79,920 andMoE328,128", "sum(numel) exactly79,920 and328,128", "Instantiate current configurations onCPU and sum all parameters,no training.", tolerance="Exact integer equality.")
claim("c13", "concept", "CE student learns gold answers;KD also learns the teacher's next-unit probability distribution.", "19.md:668", [evidence("s_kd", "§2 pp2–3 Eq1 andweighted hard/soft objectives", "Soft-target distillation alongside correct labels."),evidence("s_alignment", "distillation_kl45–55;distillation_loss58–64", "Current implementation matches detached next-byte distributions on valid answer positions.")], "T2 and equal CE/KD weights described in actually read19.10 prerequisite;teacher fixed. No claim KD must outperformCE or preserve all tasks.", ["a_original_analysis"])
claim("c14", "empirical", "Student table matches CE62/90,KD61/90,KD4-bit61/90;calculator1/12 versus0/12;tool_return1/6;shape0/9 andstyle0/3;other listedtasks pass. KD'sextra failure1+8 requests1+9 then reads10as11;4-bit has6changed raw generations,all already wrong.", "19.md:687–700", [evidence("s_cpu", "record_rescoring.ce/kd/kd-ptq4;ce_kd_difference;id_changes", "Complete per-task numerators and error/quantized ID comparison."),evidence("s_student", "run178–225", "Frozen350-step branches,serializedstudent reloaded for evaluation;no student modalityswap branch.")], "Same90original test rows;constantgreen9/9 and mainmodel swapchecks do not establish students' modality dependence. No own student training,inference,timing or memory replication.", inputs(base+"student/test-ce.json",base+"student/test-kd.json",base+"student/test-kd-ptq4.json",base+"student/ce/train-report.json",base+"student/kd/train-report.json"), "Published student table and6changedKD4-bit records", "All12 task entries perstudent match;CEonly correct1+8;KDwrongorderedargs/finalread;6/90changedallpreviouslywrong", "Decode all270raw records and finaltool records;reconstruct actions and compare IDs across saved/reloaded compression version.", {"test_rows_per_student":90,"student_versions":3,"calculator_rows":12,"tool_return_rows":6,"shape_rows":9,"style_rows":3,"seed":42,"updates_per_branch":350,"effective_answer_positions_per_branch":145163,"student_swap_pairs":"notmeasured"})
claim("c15", "software", "Chapter20 uses a separate upstream pretrained Qwen3VL Dense image-text base,optional course fine-tuning candidates,selected base withoutLoRA,and Whisper transcript routed into the same core;it is not enlargement/continuation of capstone MoE.", "19.md:704–706", [evidence("s_qwen_card", "introduction/KeyEnhancements/pretraining", "Upstream trainedimage-text model identity."),evidence("s_qwen_config", "architectures/model_type/text_config", "Independent Dense-modelconfiguration."),evidence("s_qwen_code", "Qwen3VLTextMLP460–485", "Dense per-layerprojection."),evidence("s_natural", "load_core263–289;load_asr687–696;915–940", "Separate pretrained loader and actualASR routing."),evidence("s_cpu", "selection natural/asr;inputs selection.json", "Directly read chosenbase and fixedWhisper configuration.")], "Architecture/configuration facts and documented projectdecision;no newupstreammodel download or inference and no marketingcapability guarantees. Candidate quality lives in its own evidence.", inputs("docs/natural-assistant/v4/selection.json","docs/natural-assistant/v4/asr-selection.json"), "QwenDensebase+Whisper;selectedbase", "PinnedQwen3VLconfiganddenseMLP;selected_variant=base;ASR=openai/whisper-large-v3-turbo", "Inspect originalpublisherconfig/upstreamcode,currentloader/transcriptpath,and executeconfigurationrecord assertions.")
claim("c16", "software", "Increasing downstream model parameters cannot automatically restore details discarded by originalimage/audio summaries.", "19.md:702,704", [evidence("s_core", "CapstoneModel90–107;modality_tensors285–296", "4x4averageimage andtime-averagedlogmel summaries."),evidence("s_cpu", "pooling_collision", "Two differentpixels yieldidentical pooledsummary.")], "Many-to-oneinputrepresentation:larger downstreamfunction receives identicalvectors. Priors mayguess,or a newencoder maypreserve details;no claimimprovement is impossible.", ["a_probe","a_original_analysis"], "Distinct pixelpositionsin samepoolcell cancollide", "torch.equal summaries=True whileoriginal imagesdiffer", "Place onepixel in column0versus1of same4x4cell;pool both16x16inputs;any downstreamdeterministic functionreceives identicalsummary. Timeaveraging likewise losesorder.")
claim("c17", "concept", "Sparse MoE can compute only selected experts,but all experts' weights generally still require storage;active parameters alone do not determine weak-hardware feasibility.", "19.md:706", [evidence("s_switch", "§2.1 pp3–5 Eqs1–2;§5.2p19 and§5.5p21", "Sparse routing decouples per-tokenwork from totalweights,with sharding/memory tradeoffs."),evidence("s_modern", "MoEFFN56–89", "All localexperts are stored,but selectedrows alone execute.")], "Totalstorage distinction;sharding/offload can change residency. No claims of dedicatedGPUkernels,current speedups,or minimumhardware requirements.", ["a_original_analysis"])

clean = {
"c9": {
    "statement": "Every version uses the same 90-question final test: untrained 0, pretrain after 300 steps 0, SFT 45, joint 78, DPO 78, joint 4/8-bit 78 each, DPO 4/8-bit 78 each, CE 62, KD 61, and KD 4-bit 61. Equal scores do not imply equal generated IDs.",
    "scope": "Original GPU records on the same fixed 90 rows, seed 42. This is neither a universal compression guarantee nor a claim of token identity. The original train report records the complete 300-step pretraining schedule."
},
"c10": {
    "statement": "The recommendation of joint was recorded before test: joint scored 75/84 on validation versus DPO 71/84, while both later scored 78/90 on test. DPO remained the student branch's precommitted teacher.",
    "scope": "Historical sequence is supported by original project selection/run records and matching frozen code, without direct observation of those past runs. This CPU probe neither trains nor selects weights on test."
},
"c11": {
    "statement": "Full/cache raw generated IDs match on 12 preselected validation-task inputs. One short-copy generation on L4 has full/cache medians of 68.054/59.978 ms; no generation memory peak was measured.",
    "scope": "Recalculation of recorded L4 FP32 measurements, without CPU speed replication or a universal speed claim. Full cache logit tensors are unavailable; this section's narrower raw-ID equality is independently checked."
},
"c12": {
    "statement": "The small Dense student has 79,920 parameters and the capstone MoE has 328,128; their architectures differ.",
    "scope": "Current architecture counts verified on CPU. Random model construction does not validate trained quality."
},
"c14": {
    "statement": "The student table matches CE 62/90, KD 61/90 and KD 4-bit 61/90, including calculator 1/12 versus 0/12, tool_return 1/6, shape 0/9, style 0/3 and success on the other listed tasks. KD's extra failure at 1+8 requests 1+9, then reads 10 as 11. Six KD 4-bit raw generations change, all on previously wrong rows.",
    "scope": "Same 90 original test rows. Constant green answers scoring 9/9 and the main model's swap checks do not establish the students' modality dependence. No student GPU training, inference, timing or memory replication was performed."
},
"c15": {
    "statement": "Chapter 20 uses a separate upstream pretrained Qwen3VL Dense image-text base, course fine-tuning candidates, a selected base without LoRA, and Whisper transcripts routed into the same core. It is not enlargement or continuation of the capstone MoE.",
    "scope": "Architecture, configuration and recorded project choice only. No upstream model was downloaded or run, and no marketing capability claims are adopted. Candidate quality has separate evidence."
},
"c16": {
    "statement": "Adding downstream parameters cannot automatically restore information discarded by the original image/audio summaries.",
    "scope": "For a many-to-one representation, the downstream function receives identical vectors for distinct inputs. Priors can guess missing details, or a new encoder can retain them; the claim does not say improvement is impossible."
},
"c17": {
    "statement": "Sparse MoE can compute only selected experts, while all expert weights generally still require storage. Active parameters alone do not establish whether weak hardware can support a model.",
    "scope": "Total storage distinction. Sharding and offloading can change residency; this does not establish dedicated kernels, a speedup, or minimum hardware requirements."
}}
for c in claims:
    c.update(clean.get(c["id"], {}))
    if c["id"] in {"c3", "c6", "c9", "c10"}:
        c["artifact_ids"].append("a_training_scope")
body=(ART/"reviewed-section.md").read_bytes()
current=(ROOT/"course/chapters/19.md").read_text().split("## 19.12 ",1)[1]
assert b"## 19.12 "+current.encode()==body
report=dict(schema_version=1,review_stage="technical",lesson_id="19.12",source="course/chapters/19.md#19.12",reviewer_task="/root/v4_review_coordinator/factual_v4_19_12",reviewer_context="fresh",source_sha256=hashlib.sha256(body).hexdigest(),figure_sha256={"course/figures/normalization.svg":sha(ROOT/"course/figures/normalization.svg")},verdict="pass",claims=claims,sources=sources,artifacts=artifacts,issues=[],introduction_applicability="not_applicable; 19.12 is not the first numbered section",direct_figure_sha256={},checks={
"factual_accuracy":dict(status="pass",details="Personally read the full current section, all blank lines and necessary prerequisites. Seventeen related substantive claim groups checked against original papers/source, current code and independently rescored raw records; no inherited verdict.",claim_ids=[c["id"] for c in claims]),
"numeric_verification":dict(status="pass",details="Executed the exact Counter code. Independently recomputed every score table, paired conjunction, the 87-row refusal subset, parameter counts, 12 cache ID pairs and timing median rounding. Actual Torch 2.14.1+cpu; original GPU records inspected without GPU replication.",claim_ids=[c["id"] for c in claims if c["kind"] in ["numeric","empirical","software"]]),
"figure_consistency":dict(status="pass",details="Assigned 19.12 has no direct SVG references. Personally rendered and viewed the newly linked 14.2 normalization prerequisite: left-to-right arrows, one token's [1,2,3] features, distinct LN/RMS rules, gamma/LN-only beta and same-shape output match the text. Direct figure map is empty; the inspected prerequisite SVG is hashed separately in the full map.",claim_ids=[]),
"source_verification":dict(status="pass",details="Personally read original versioned PDFs and pinned Qwen config/source; saved original URLs, versions, locators and SHA receipts. Inspected current capstone code full-file SHAs match the official frozen run sources. Original inputs are registered as hashed snapshot artifacts.",claim_ids=[c["id"] for c in claims]),
"limitations":dict(status="pass",details="Respected fixed synthetic families, constant labels, subset denominators, record-only GPU validation, timing/memory scope, compression differences, absent student swap checks and separate upstream base. No general natural-input, safety, calibration or speed guarantee, and no full cache-logit replication claimed.",claim_ids=[c["id"] for c in claims])})
destination=Path(sys.argv[1]) if len(sys.argv)>1 else ROOT/"docs/technical-reviews/19.12.json"
destination.parent.mkdir(parents=True,exist_ok=True)
destination.write_text(json.dumps(report,ensure_ascii=False,indent=2)+"\n")
print(json.dumps({"path":str(destination),"report_sha256":sha(destination),"source_sha256":report["source_sha256"],"claim_groups":len(claims),"sources":len(sources),"artifacts":len(artifacts),"verdict":report["verdict"]},indent=2))
