"""Serialize this review's own findings; no previous report is read."""
from pathlib import Path
import hashlib
import json

root = Path(__file__).resolve().parents[5]
own = Path(__file__).parent
relative = own.relative_to(root).as_posix()
probe = json.loads((own / "cpu.stdout.json").read_text())
retrievals = {r["id"]: r for r in json.loads((own / "original-retrievals.json").read_text())}
sources, artifacts, claims = [], [], []

def digest(path):
    return hashlib.sha256((root / path).read_bytes()).hexdigest()

def repo(identifier, path, note, version="Current bytes inspected; relevant program bytes equal student commit 59a1eda4ed7b6e8609892ec2b9013c821ac93e69"):
    sources.append(dict(id=identifier, kind="repository_code", title=path, path=path, sha256=digest(path), version=version, inspection_note=note, verified=True))

def original(identifier, retrieval_id, title, version, note):
    r = retrievals[retrieval_id]
    assert r["status"] == 200
    sources.append(dict(id=identifier, kind="official_source", title=title, url=r["url"], version=version, verified=True, checked_original=True, accessed_on="2026-10-04", authority_reason="Original project/publisher documentation or original source implementing the cited interface", inspection_note=note, retrieved_sha256=r["sha256"]))

def artifact(identifier, path, kind, description, **extra):
    artifacts.append(dict(id=identifier, kind=kind, path=path, sha256=digest(path), description=description, **extra))

def evidence(source, locator, supports):
    return dict(source_id=source, locator=locator, supports=supports)

def claim(identifier, kind, statement, location, refs, scope, expected=None, observed=None, details=None, denominators=None, aids=None, tolerance=None):
    c = dict(id=identifier, kind=kind, statement=statement, location=location, status="verified", evidence=refs, artifact_ids=aids or ["cpu", "inspection"], scope=scope)
    if kind != "concept":
        c["verification"] = dict(method="executed", expected=expected, observed=observed, details=details)
        if denominators is not None:
            c["verification"]["denominators"] = denominators
        if tolerance is not None:
            c["verification"]["tolerance"] = tolerance
    claims.append(c)

repo("fetch", "scripts/fetch_natural_release.py", "Read validate_manifest lines 88–190, verify_provenance 278–321, verify_release 323–349, fetch_release 352–376, check_runtime 379–404, student_options 407–432, main 435–506; bounded native list/fetch/verify, tamper and option probes executed.")
repo("core", "tiny_perceptron/natural_assistant.py", "Read messages_for/encode_messages lines 112–155, load_core 263–306, generate 315–369, load_asr 687–698, transcribe 701–774: revision/cache/local-only propagation, no adapter for base, frozen eval inference, image/history inputs and separate CPU Whisper ASR.")
repo("ui", "tiny_perceptron/natural_ui.py", "Read upload validators 38–93, NaturalServer initialization/close 96–115, operation 131–212, loopback create_server and serve 317–352, complete product HTML/JavaScript 355–end. Executed injected state and native serve-interrupt cleanup probes.")
repo("manifest", "docs/natural-assistant/v4/public-release.json", "Read whole manifest: base variant, zero adapter parameters, both exact official revisions, Python 3.12/runtime limits, eleven dependency pins, exact code hashes and two document entries. Native manifest/provenance verification executed.")
repo("requirements", "requirements-natural.txt", "Read all eleven exact dependency pins; independently parsed equality with manifest dependency_versions and exact requirements_sha256.")
repo("notebook", "notebooks/20/20.2.ipynb", "Read notebook JSON cell_type values; two Markdown cells and no executable code cells, explaining why displayed Bash does not automatically download.", "Current full notebook inspected")
repo("attributes", ".gitattributes", "Read complete file: /assets/training/*.tar.gz uses filter=lfs, diff=lfs, merge=lfs.", "Current complete .gitattributes")
repo("student", "docs/natural-assistant/v4/STUDENT.md", "Read complete linked guide sections 1–7; exact CPU route, scoped cached CPU observations, formats and bounds, local-only cache option, transcript correction, cleanup, and explicit lack of complete cross-platform/GPU validation. It is the claimed guide being checked, not independent authority for the underlying model facts.", "Current whole guide read")
original("git_clone", "git-clone-source", "Git clone original manual", "Git v2.43.0 source documentation; installed Git 2.52.0", "Read OPTIONS lines 153–155: --no-checkout performs no checkout after clone. Source fallback from git-scm 403 to original versioned Git repository was successful.")
original("git_checkout", "git-checkout-source", "Git checkout original manual", "Git v2.43.0 source documentation; installed Git 2.52.0", "Read description lines 68–80 and --detach lines 209–214: a specified commit updates working tree/index with HEAD detached.")
original("lfs", "git-lfs", "Git LFS smudge original manual", "git-lfs v3.7.0", "Read DESCRIPTION and OPTIONS: smudge replaces pointers with large content; GIT_LFS_SKIP_SMUDGE disables the smudging process.")
original("venv", "python-venv", "Python virtual environments", "Python 3.12.15 documentation, retrieved 2026-10-04", "Read Creating virtual environments and How venvs work: isolation by default, POSIX bin/python, explicit interpreter paths do not require activation.")
original("torch_install", "pytorch-versions", "PyTorch official previous-version installation", "Live official page read 2026-10-04, v2.8.0 section", "Read v2.8.0 / Linux and Windows: CPU wheel index pairs torch 2.8.0 with torchvision 0.23.0; CUDA cu128 option matches linked guide. This review did not install that environment.")
original("qwen", "qwen-card", "Official Qwen3-VL-2B-Instruct model card", "89644892e4d85e24eaac8bacfd4f463576704203", "Read model identity and Quickstart / Using Transformers to Chat: pretrained Qwen3VLForConditionalGeneration, AutoProcessor, image/text message and decoded generated text. Also read anonymous official revision API at the same pin: private=false/gated=false, one 4,255,140,312-byte weight file, SHA matching original prepare metadata. No capability marketing adopted.")
original("whisper", "whisper-card", "Official Whisper-large-v3-turbo model card", "41f01f3fe87f28c78e2fbf8b568835947dd65ed9", "Read Usage lines 130–176 and 208–220 (transcription), Chunked Long-Form 304–309 (30-second receptive field and explicit long-form handling), Performance and Limitations 500–508 (recognition errors/hallucinations). Anonymous official revision API at the pin is public and ungated; 1,617,824,864-byte weight SHA matches original prepare metadata.")
original("hub", "hf-hub-source", "Hugging Face Hub download original source", "huggingface_hub v0.36.2", "Read hf_hub_download signature/docs lines 816–913: exact revision may be a commit hash; cache_dir and local_files_only semantics.")
original("headers", "hf-headers-source", "Hugging Face Hub authentication header original source", "huggingface_hub v0.36.2", "Read build_hf_headers/get_token_to_send lines 125–152: token=False returns None and does not add an Authorization header.")
original("transformers", "transformers-source", "Transformers pretrained model loading original source", "Transformers v4.57.6", "Read from_pretrained lines 4384–4400, 4415–4480: pretrained weight/model ID, cache directory, force_download default false, local-only and commit revision arguments.")
sources.append(dict(id="execution", kind="execution", title="Own bounded CPU execution and original-record recomputation", verified=True, artifact_id="cpu"))
sources.append(dict(id="units", kind="derivation", title="Byte, KiB and timing conversions independently recomputed", verified=True, details="Public documents 8,722+540=9,262 bytes; original 23 snapshot entries sum 5,889,111,977 bytes, divided by 2^30=5.484662928618491 GiB (5.4847 rounded). Server 13,496,104 KiB divided by 2^20=12.870887756347656 GiB (12.8709 rounded). Original timing values rounded to nearest 0.01 second. 8 MiB=8*2^20=8,388,608 bytes=8.388608 decimal MB (8.39 rounded). These storage and process RSS observations have different scopes."))
artifact("cpu_code", relative + "/run_cpu.py", "code", "Own bounded assertion script; no model load/install/training; explicit synthetic UI injection and raw original trial audit")
artifact("cpu", relative + "/cpu.stdout.json", "execution", "Actual CPU stdout: native list, anonymous document fetch/verify, state/lifecycle probes, exact source pins and independently recomputed original run", command=".venv/bin/python docs/technical-reviews/artifacts/natural-v4-factual/20.2/run_cpu.py > docs/technical-reviews/artifacts/natural-v4-factual/20.2/cpu.stdout.json 2> docs/technical-reviews/artifacts/natural-v4-factual/20.2/cpu.stderr.txt", result=probe["result"], environment=probe["environment"])
artifact("stderr", relative + "/cpu.stderr.txt", "source_snapshot", "Actual CPU execution stderr was empty; execution exited 0")
artifact("inspection", relative + "/inspection.md", "derivation", "Own exact original read locators, source inspection, arithmetic and actual screenshot observation; limits stated")
artifact("retrievals", relative + "/original-retrievals.json", "source_snapshot", "Own original HTTPS URLs/retrieval SHA receipts; full originals only in ignored research, including resolved Git docs access fallback")
artifact("metadata", relative + "/upstream-metadata.json", "source_snapshot", "Own small original API analysis: exact public ungated official revisions and inert weight metadata; no downloaded weights")
artifact("raw_source", relative + "/reviewed-section.raw.md", "source_snapshot", "Complete current UTF-8 assigned body including trailing blank lines")
artifact("record_index", relative + "/original-records.json", "source_snapshot", "Own record locator/byte/SHA index for actual inspected original raw run and harness files")
base = "docs/natural-assistant/evidence/v4-research/student-selected-public-ui/"
for aid, path, description in [
    ("original_observer", base+"actual-ui/observer.jsonl", "Original native model/ASR/event log, personally read and independently recomputed"),
    ("original_browser", base+"actual-ui/browser/report.json", "Original Chromium control/network request and timing record; independently cross-checked against model events"),
    ("original_trial", base+"actual-ui/report.json", "Original command/source/config/inputs/timing and shutdown record; not the reviewer's own model run"),
    ("original_http", base+"anonymous-fetch/fetch.http.json", "Original anonymous HTTP request methods/status/authentication-header record"),
    ("original_prepare", "docs/natural-assistant/evidence/v4-research/student-local-cache-prepare/actual-prepare/result.json", "Original official-cache snapshot file sizes and SHA entries; independently summed without reading or copying weights"),
]:
    artifact(aid,path,"source_snapshot",description)

claim("c1", "concept", "The finished route reuses pretrained Qwen3-VL-2B-Instruct for image/text and Whisper-large-v3-turbo for separate speech transcription, without activating this course's fine-tuning adapter or retraining before use.", "Chapter 20.2 lines 41–43, 75–87; linked STUDENT introduction", [evidence("qwen", "Pinned model card: identity and Quickstart / Using Transformers to Chat", "Pretrained image/text inference to decoded text"), evidence("whisper", "Pinned model card: Usage lines 130–176 and 208–220", "Speech transcription returns text and is a distinct model task"), evidence("manifest", "selected_variant, adapter_parameters, base_model, asr_model", "Exact selected base/ASR pins and zero adapter parameters"), evidence("fetch", "student_options lines 407–432", "Base selection maps to adapter=None"), evidence("core", "load_core 263–306; load_asr 687–698; transcribe 701–774", "No train call or adapter load for this inference route; distinct frozen ASR")], "This course adds no correction adapter in the selected release; the official models were previously trained by their publishers. No claim that pretrained capability is guaranteed for a new query.")
claim("c2", "software", "The clone/no-checkout and detached 59a1eda commit commands select the tested source in a new folder while disabling LFS smudging of large training archives.", "Chapter 20.2 lines 43–55, first Bash block", [evidence("git_clone", "OPTIONS lines 153–155", "No automatic working-tree checkout"), evidence("git_checkout", "Description 68–80, --detach 209–214", "Exact commit selection with detached HEAD"), evidence("lfs", "DESCRIPTION and OPTIONS GIT_LFS_SKIP_SMUDGE", "Disables LFS content smudging"), evidence("attributes", "Final LFS rule /assets/training/*.tar.gz", "Large training tarballs use LFS")], "Git option semantics and current source identity verified. Review did not clone/checkout or mutate Git; a new absent destination is assumed. LFS skip affects LFS objects, not ordinary source files.", "Valid Bash; prescribed commit contains the current release program and manifest", "Four Bash blocks parsed; Git 2.52.0 and Python 3.12.14 found; all five selected source/manifest/requirements files exactly equal pinned commit bytes", "Read original Git/LFS manuals and current attributes; executed bash -n, tool versions and read-only git show byte comparison.")
claim("c3", "software", "The Linux instructions use a separate Python 3.12 venv, explicit interpreter paths, matched Torch 2.8.0/torchvision 0.23.0 CPU packages and eleven fixed requirements; notebook Bash blocks are Markdown instructions.", "Chapter 20.2 lines 43 and 53–66; linked STUDENT sections 1–2", [evidence("venv", "Creating virtual environments; How venvs work", "Independent environment and explicit POSIX interpreter invocation"), evidence("torch_install", "v2.8.0 / Linux and Windows / CPU only", "Official paired CPU versions/index; cu128 option in linked guide"), evidence("requirements", "Whole file", "Eleven exact dependency pins"), evidence("fetch", "check_runtime 379–404", "Requires Python 3.12 and matching dependency/code bytes"), evidence("notebook", "All cell_type values", "Two Markdown cells and no executable cells")], "Package installation was not rerun. The review environment is Python 3.13.5/Torch 2.14.1+cpu and is correctly rejected for model serving; the original student run records Torch 2.8.0+cpu and its exact required dependencies. No complete GPU or other-platform trial is inferred.", "Manifest and requirements agree; runtime protects the separate student environment; notebook does not run shell downloads", "All eleven versions and requirements SHA agree; current check_runtime rejected the teaching venv with the Python 3.12 instruction; notebook has two Markdown cells", "Native static contract parsing, bash syntax and explicit current-runtime gate executed; original PyTorch/Python instructions actually read.")
claim("c4", "software", "The public manifest fixes both official model revisions; list only displays pins, initial fetch retrieves two small project documents with exact size/SHA and anonymous access, and verify rechecks those documents rather than downloading full weights.", "Chapter 20.2 lines 67–81, download/list/verify commands", [evidence("manifest", "files; model revisions; selected_variant", "Two project documents only, no adapter/model weights"), evidence("fetch", "main 435–506, fetch_release 352–376, verify_release 323–349 and verify_provenance 278–321", "Anonymous token=False, byte/hash checks and existing receipt validation"), evidence("hub", "hf_hub_download 816–913", "Immutable revision and caching API"), evidence("headers", "get_token_to_send 144–152", "token=False suppresses authorization")], "Own native fetch API used a minimal urllib downloader for just 9,262 project-document bytes; native list and verify CLI executed. Original student record confirms the actual v0.36.2 Hub CLI workflow. Full models remain separate; no own model-weight download.", "Exact base pins, README 8,722 bytes and provenance 540 bytes; tampering rejected", "Native list/verify exit 0, both live anonymous GETs 200 with manifest SHA/size, modified README rejected", "Executed validated native API using manifest-bound URLs/token=False, native CLI and intentional document modification; read original Hub source.")
claim("c5", "software", "Serving eagerly loads the fixed image/text base; ASR is loaded only on first transcription, cached versions can be reused, the default UI is loopback 127.0.0.1:8766, and Ctrl+C closes the service and removes uploaded conversation files while leaving model caches reusable.", "Chapter 20.2 lines 81–83 and 89; linked STUDENT sections 4 and 7", [evidence("ui", "serve 338–352; create_server 317–335; operation 166–175; server_close 113–115", "Load order, loopback/default port, lazy ASR and upload cleanup"), evidence("core", "load_core 263–280 and load_asr 687–698", "Exact revision/cache/local-only propagated to both loaders"), evidence("transformers", "from_pretrained 4384–4400 and 4453–4480", "Pretrained cached retrieval and local-only/revision semantics")], "UI server must continue running to answer loopback requests. GitHub Pages is the book delivery site, while this process serves the assistant. Own lifecycle probe injects model loading and interrupt; cache retention uses a synthetic sentinel. Original real trial used complete existing caches offline, so first weight-download duration was not measured.", "One delayed ASR load, loopback default 8766, real finally/close cleanup after interrupt, cache content outside uploads preserved", "Injected native state probe recorded one ASR load; loopback bind was 127.0.0.1; native serve returned on KeyboardInterrupt and removed uploads; separate cache sentinel retained", "Executed native create_server, operation, server_close and native serve interrupt path with explicitly injected lightweight runners; audited original one-load-per-model events.")
claim("c6", "software", "The four UI steps preserve earlier photos/history, transcribe without chatting, show an original transcript and editable text, send the final corrected prompt to chat, and clear conversation state/assets on new dialogue.", "Chapter 20.2 lines 85–89, numbered operating steps; linked STUDENT sections 5–6", [evidence("ui", "operation 131–212 and HTML/JavaScript 375–451", "Separate APIs, editable prompt, original note, history append and reset"), evidence("core", "messages_for/encode_messages 112–155", "Prior message image assets enter later model inputs")], "Own synthetic runners verify product wiring and deletion; they do not establish actual image understanding or speech accuracy. Format limits are project-specific: PNG/JPEG/WebP, WAV/FLAC/MP3/OGG, 8 MiB, 16 million image pixels, 30 seconds audio. The section's quality pointer remains appropriate.", "Transcription alone makes no chat call; corrected prompt differs from preserved original; photo persists; reset clears history/assets/transcriptions", "Four synthetic chat calls and one ASR load; history 0/2/4/6; submitted 我不吃辣, original 我吃辣; photo retained; reset empty; 30-second audio accepted, one extra sample rejected", "Ran native operations with tiny synthetic PNG/WAV and explicit injected generation/transcription, then inspected native HTML handlers and original real records.")
claim("c7", "empirical", "The stated operation-connected claim is supported by an existing actual Chromium/Linux CPU trial covering text, photo, ASR, corrected speech submission, follow-up and reset, without scoring answer quality.", "Chapter 20.2 final paragraph; linked STUDENT section 2 trial scope", [evidence("execution", "cpu.stdout.json original_trial_audit", "Own independently recomputed original request/model event consistency"), evidence("ui", "operation and browser handlers", "Current product route matches observed calls")], "Audit of an existing original native trial, not the reviewer's own model/browser replication or a human usability study. Original CPU FP32 uses an existing official cache offline. Zero scored test examples; no inference-quality, minimum-resource, GPU or cross-platform conclusion.", "Four serial native chat generations plus one ASR; final text preserved, historical image retained, reset empties state", "Raw observer/browser counts independently agree: 4 chats, 1 ASR, history lengths 0/2/4/6, source/input SHA consistent, reset history/assets/transcriptions empty and all browser API statuses 200", "Own executed audit cross-checks native generation outputs against browser responses, corrections against model prompt, photo asset SHA across later calls and raw reset event; read delegating observer/browser harnesses and personally viewed original turn-3 screenshot.", denominators={"original_trials":1,"native_chat_requests":4,"native_asr_requests":1,"photos":1,"photo_split":"DOCCI train_07076, original train split","audio_examples":1,"audio_split":"AISHELL project validation BAC009S0005W0205","audio_seconds":3.1529375,"chat_input_tokens":[16,535,599,651],"chat_generated_tokens_including_eos":[3,41,32,29],"asr_generated_tokens_including_eos":14,"scored_test_examples":0,"seed":"Manifest seed 42; actual generation uses do_sample=False; no multiple-seed comparison","original_threads":5,"original_interop_threads":1}, aids=["cpu","inspection","original_observer","original_browser","original_trial"])
claim("c8", "empirical", "The multi-GB storage and separate runtime-memory statement matches the linked CPU record: two documents 9,262 bytes, 23 model-snapshot files 5,889,111,977 bytes≈5.4847 GiB, server peak 13,496,104 KiB≈12.8709 GiB, with all displayed times rounded to the original measured scope.", "Chapter 20.2 line 43 and linked STUDENT section 2 resource table", [evidence("units", "Independent arithmetic in source details and inspection.md", "Transparent sums, binary units and timing rounding"), evidence("execution", "cpu.stdout.json original_trial_audit", "Actual recomputation from original cache/browser/observer records")], "These observed cached weights/snapshot bytes and server-only RSS are separate accounting units. They exclude Python environment, additional caches/filesystem overhead and browser/driver. One existing cached machine/input trial cannot establish minimum RAM/disk or universal speed. No new benchmark or model inference executed.", "9,262 document bytes; 23 snapshot entries and 5.4847 GiB; 12.8709 GiB server RSS; ready 24.24 s, chats 3.42/42.87/36.58/37.11 s, first ASR 18.03 s, whole task 170.33 s", "Exact sums and unrounded conversions 5.484662928618491 and 12.870887756347656 GiB; all timing values round to the printed table", "Summed all original prepare snapshot entries; recomputed RSS from raw process_resources, browser/chat/ASR waits from original browser record, and ready/whole-task fields from original trial. No source summary verdict used.", denominators={"original_trials":1,"startup_observations":1,"chat_wait_observations":4,"asr_wait_observations":1,"public_documents":2,"model_snapshot_files":23,"server_rss_observations":1,"warmup":"No repeated benchmark warmup; cache already complete; first ASR includes lazy loading","original_device":"Linux CPU float32","torch_threads":5,"interop_threads":1,"seed":"Manifest 42; greedy generation do_sample=False","samples":"One DOCCI train photo and one AISHELL validation utterance; zero scored test rows"}, aids=["cpu","inspection","original_prepare","original_observer","original_browser","original_trial"], tolerance="Exact integer totals; GiB rounding within 0.00005 and time rounding within 0.005 second")
report = dict(schema_version=1, review_stage="technical", lesson_id="20.2", source="course/chapters/20.md#20.2", reviewer_task="/root/v4_review_coordinator/factual_v4_20_2", reviewer_context="fresh", source_sha256=digest(relative+"/reviewed-section.raw.md"), introduction_sha256=None, figure_sha256={}, verdict="pass", claims=claims, sources=sources, artifacts=artifacts, issues=[], checks={
    "factual_accuracy":dict(status="pass", details="All eight grouped substantive claims checked against original authorities/current program and bounded probes; no contradiction found.", claim_ids=[c["id"] for c in claims]),
    "numeric_verification":dict(status="pass", details="Executed integer sums, binary unit conversions and rounding against original scoped records; exact package, revision, port and upload limits inspected/probed.", claim_ids=["c2","c3","c4","c5","c6","c7","c8"]),
    "figure_consistency":dict(status="not_applicable", details="No SVG in the whole assigned operating section or needed prerequisite; personally viewed original UI screenshot as recorded in inspection.md.", claim_ids=[]),
    "source_verification":dict(status="pass", details="Actually read versioned original Git/LFS/Python/PyTorch/model/Hub/Transformers sources, recorded URLs/SHA/read locators, registered current program hashes and original raw execution evidence. Git rendered-doc 403 resolved with original Git repository manuals.", claim_ids=[c["id"] for c in claims]),
    "limitations":dict(status="pass", details="Own current Torch 2.14.1+cpu bounded wiring probes distinguished from student Torch 2.8.0+cpu original native trial. No model download/install/GPU/train/quality replication; cached single-run timing/resource and synthetic output limits preserved.", claim_ids=[c["id"] for c in claims])})
(root / "docs/technical-reviews/20.2.json").write_text(json.dumps(report, ensure_ascii=False, indent=2)+"\n")
if not (own / "first-report.json").exists():
    (own / "first-report.json").write_text(json.dumps(report, ensure_ascii=False, indent=2)+"\n")
print(report["verdict"], report["source_sha256"], len(claims), len(sources), len(artifacts))
