from pathlib import Path
import json,hashlib
root=Path(__file__).resolve().parents[5];out=Path(__file__).resolve().parent
H=lambda p:hashlib.sha256((root/p).read_bytes()).hexdigest()
receipts={r['id']:r for r in json.loads((out/'original-retrieval-receipts.json').read_text())}
scope=json.loads((out/'source-scope-receipt.json').read_text());cpu=json.loads((out/'cpu-result.json').read_text());figs=json.loads((out/'figure-render-receipt.json').read_text())
sources=[]
def original(id,title,kind,version,locator,note,authority):
 r=receipts[id]
 sources.append({'id':'s_'+id,'title':title,'kind':kind,'url':r['url'],'version':version,'verified':True,'checked_original':True,'accessed_on':'2026-10-04','authority_reason':authority,'inspection_note':locator+'. '+note,'retrieval_sha256':r['sha256']})
original('moe','Outrageously Large Neural Networks: The Sparsely-Gated Mixture-of-Experts Layer','paper','arXiv:1701.06538v1, 23 Jan 2017','Sections 1.1–1.2, 2, 2.1; equations 1–5','Read sparse gates, separately parameterized experts and per-example activation; zero gate permits skipping expert execution while all experts remain model parameters.','Original authors introduce the sparse conditional-computation mechanism.')
original('cache','Transformers Caching','official_docs','Hugging Face Transformers v4.57.1','Caching introduction; Attention matrices and per-layer K/V append equations','Personally read causal invariance, cached past K/V and newly appended K/V; mechanism is inference with fixed weights and consistent positions.','Maintainer documentation describes the Transformer cache mechanism.')
original('flash','FlashAttention: Fast and Memory-Efficient Exact Attention with IO-Awareness','paper','arXiv:2205.14135v2, 23 Jun 2022','Abstract, Figure 1, section 3.1, Algorithm 1, Theorem 1, section 3.2/Theorem 2','Read tiling, online normalization and recomputation; avoid quadratic intermediate HBM materialization and reduce memory transfers, retaining full attention mathematics.','Original algorithm authors and original complexity analysis.')
original('quant','Quantization and Training of Neural Networks for Efficient Integer-Arithmetic-Only Inference','paper','arXiv:1712.05877v1, 15 Dec 2017','Introduction; section 2.1, equation 1','Read lower-bit representation and affine scale/zero-point mapping; the introduction separates storage-focused quantization from demonstrated hardware latency gains.','Original quantization scheme and explicit hardware conditions.')
original('hinton','Distilling the Knowledge in a Neural Network','paper','arXiv:1503.02531v1, 9 Mar 2015','Sections 1–2; soft targets; equation 1','Read transfer from cumbersome teacher to small student using teacher probabilities; student quality requires validation.','Original knowledge-distillation authors.')
original('minillm','MiniLLM: On-Policy Distillation of Large Language Models','paper','arXiv:2306.08543v6','Section 1 Introduction, black-box and white-box KD paragraphs','Read generated-text supervision versus accessible output distributions/hidden states; this supports the glossary signal distinction, not adoption of MiniLLM optimization.','Original LLM distillation paper directly defines both signal-access cases.')
original('instruct','Training language models to follow instructions with human feedback','paper','arXiv:2203.02155v1, 4 Mar 2022','Section 3.1, steps 1–3 and Figure 2','Personally read human demonstrations/comparisons, reward-model prediction, scalar rewards and PPO policy optimization. PPO does not determine feedback provenance.','Original InstructGPT authors document their RLHF procedure.')
original('ppo','Proximal Policy Optimization Algorithms','paper','arXiv:1707.06347v2, 28 Aug 2017','Section 2.1 equation 1; section 3 equations 6–7/Figure 1; section 5 equations 9–12/Algorithm 1','Read stochastic policy, collection-policy probability ratio, advantage, learned value and sampling/update cycle. Clipping changes the surrogate incentive rather than hard constraining all ratios.','Original PPO authors define the clipped objective and actor-critic algorithm.')
original('dpo','Direct Preference Optimization: Your Language Model is Secretly a Reward Model','paper','arXiv:2305.18290v3, 29 Jul 2024','Section 3 equations 1–3; section 4 equations 4–7 and DPO outline','Read pairwise RM loss, KL to base SFT reference, and direct preference policy loss without separately fitting an explicit reward model.','Original DPO derivation and explicit reference-policy formulation.')
original('safety','OpenAI Model Spec','official_docs','Archived revision 2025-12-18','Assume best intentions; Stay in bounds / Do not facilitate or encourage illicit behavior; Consider uncertainty, state assumptions, and ask clarifying questions when appropriate','Read contextual help/clarification/refusal targets. These specify desired behavior and do not prove reliable safety behavior in a tiny model.','Publisher specifies assistant behavior and safety boundaries; used as a behavioral target, not empirical certification.')
original('rag','Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks','paper','arXiv:2005.11401v4, 12 Apr 2021','Section 2; section 2.1; section 2.3 Generator: BART','Read retrieval of documents followed by document-conditioned generation, including concatenation with input; glossary abstraction does not assert equivalence to lexical toy architecture.','Original RAG method authors.')
original('tool','Function calling','official_docs','Original OpenAI developer guide retrieved 2026-10-04; mutable page bound by retrieval SHA','How it works; Tool calls; Functions versus tools; The tool calling flow steps 1–5','Read model-proposed requests, application-side execution and return of actual tool output; the repository independently supplies allowlist/schema validation. No remote API call was made.','API publisher describes model/application responsibilities.')
def repo(id,path,title,note):
 sources.append({'id':id,'kind':'repository_code','title':title,'path':path,'sha256':H(path),'version':'Current working-tree bytes independently hashed; dispatch revision 25ca4bf5f8f8dc0a9e88aa6cd70caeb4c2f419e8','verified':True,'inspection_note':note})
repo('r_post','tiny_perceptron/posttraining.py','Finite policy/reward/value models and PPO helpers','Read entire file; finite policy accepts four structured features and emits four card logits; RM consumes context and card identity; value consumes context; clipped objective uses frozen collection probabilities and advantage.')
repo('r_exp','scripts/course_experiments/posttraining.py','Current finite-card experiment implementation','Personally inspected CONFIG, rule_best_action, build_records, split_records, reference construction and PPO rollout/update blocks; Python precomputes answer cards and preference rules before finite-index sampling. No token decoder is used in the PPO loop.')
repo('r_run','docs/course-experiments/results/posttraining.json','Original posttraining experiment result record','Directly inspected original configuration, split family lists and record fingerprints; independently rebuilding 165 contexts matched all train/validation/test fingerprints. This is record validation, not training or quality/timing replication.')
repo('r_model','tiny_perceptron/model.py','TinyLM cache integration','Read entire file; each layer reuses cache and position offset is cached prefix length. Own CPU probe compares same model full and cached paths.')
repo('r_attn','tiny_perceptron/attention.py','Current causal K/V cache source','Read entire file; append cached K/V, causal masking, per-layer state and cache restrictions for unpadded/unpacked batches.')
repo('r_align','tiny_perceptron/alignment.py','Current DPO and distillation source','Read entire file; DPO loss compares preferred/rejected log-probability gaps relative to fixed reference; distillation uses detached teacher distributions.')
repo('r_retrieval','tiny_perceptron/retrieval.py','Current lexical retrieval and tool execution source','Read entire file; query term scoring retrieves documents, while call_tool parses and validates exact fields, tool names and numeric types before add/multiply execution.')
repo('r_modern','tiny_perceptron/modern.py','Current DenseFFN and MoEFFN source','Personally read lines 35–84; Dense applies shared full FFN; MoE retains every expert module and executes only selected token rows for each expert.')
repo('r_common','scripts/course_experiments/common.py','Canonical record fingerprint calculation','Personally inspected records_sha256 lines 73–74; canonical sorted-key JSON with UTF-8 preservation is hashed and own rebuild uses the same published data fingerprint convention.')
artifacts=[]
def artifact(id,kind,name,desc,**extra):
 path=str((out/name).relative_to(root));artifacts.append({'id':id,'kind':kind,'path':path,'sha256':H(path),'description':desc,**extra})
artifact('a_main','source_snapshot','section.raw.md','Complete assigned current UTF-8 G.4 bytes through EOF with blank lines, no owned introduction.')
artifact('a_scope','source_snapshot','source-scope-receipt.json','Assigned and necessary prerequisite section hashes, inspected repository fullfile hashes and honest no-code/no-image applicability.')
artifact('a_originals','source_snapshot','original-retrieval-receipts.json','Original HTTPS/version/access-date/SHA receipts; complete external documents remain in ignored research.')
artifact('a_notes','derivation','inspection-notes.md','Independent substantive source summaries, conditions, personally viewed figure comparisons and scope limits.')
artifact('a_probe','code','cpu_probe.py','Own bounded CPU probe; no training, model generation or GPU benchmark.')
artifact('a_cpu','execution','cpu-run.txt','Actual own CPU stdout with environment, inputs and results; independently rebuilt original split hashes.',command='.venv/bin/python docs/technical-reviews/artifacts/natural-v4-factual/G.4/cpu_probe.py > docs/technical-reviews/artifacts/natural-v4-factual/G.4/cpu-run.txt 2>&1',result='Exit 0; all assertions passed; all three original record fingerprints matched; zero training updates/GPU operations/model-generation calls.',environment=cpu['environment'])
artifact('a_result','source_snapshot','cpu-result.json','Structured actual inputs, results, seed, denominators and runtime from the bounded own CPU execution.')
artifact('a_render_receipt','source_snapshot','figure-render-receipt.json','Nine unchanged prerequisite SVG source hashes and their actual successful render paths.')
artifact('a_render_code','code','render_figures.py','Successful SVG rendering code; browser page.set_content uses current unchanged SVG bytes.')
artifact('a_render_failure','source_snapshot','render-first-failure.txt','Honest preserved first browser file-navigation failure, transcribed from actual terminal output; next attempt changed navigation mechanism.')
artifact('a_render_first','code','render_figures.first-failed.py','Preserved first genuinely failed renderer.')
artifact('a_render_run','execution','render-run.txt','Actual successful render stdout and current source SHA map.',command='.venv/bin/python docs/technical-reviews/artifacts/natural-v4-factual/G.4/render_figures.py > docs/technical-reviews/artifacts/natural-v4-factual/G.4/render-run.txt 2>&1',result='Exit 0; rendered all nine necessary SVGs and captured current strict preview; all outputs personally viewed.',environment={'python':cpu['environment']['python'],'device':'CPU Chromium via installed Playwright'})
for row in figs:
 name=Path(row['render']).stem
 artifact('f_'+name,'figure_render',name+'.png','Personally viewed unchanged prerequisite '+row['source']+'; individual comparison is recorded in inspection-notes.md.')
artifact('a_preview','figure_render','preview-G.4.png','Personally viewed current strict preview G.4 table; target itself has no figure or code.')
claims=[]
def claim(id,kind,statement,location,source_specs,arts,scope,verification=None):
 d={'id':id,'kind':kind,'statement':statement,'location':location,'status':'verified','evidence':[{'source_id':s,'locator':l,'supports':v} for s,l,v in source_specs],'artifact_ids':arts,'scope':scope}
 if verification:d['verification']=verification
 claims.append(d)
claim('c1','concept','Dense applies a shared complete computation block; sparse MoE selects only a few expert blocks for each token, while retaining the experts as model parameters.','Table Dense/MoE row; first prose example after table',[('s_moe','Sections 1.1–1.2, 2 and 2.1; equations 1–5','Conditional execution skips zero-gated experts without eliminating their parameters.'),('r_modern','DenseFFN and MoEFFN, lines 35–84','Linked project convention is shared FFN versus sparse selected-expert dispatch.')],['a_notes','a_scope'],'Dense/MoE meaning is the linked FFN comparison. Routing savings require skipping unselected execution; storage, communication and actual latency remain separate quantities.')
claim('c2','concept','During autoregressive generation, KV cache retains previously computed per-layer keys and values to reduce recomputation.','Table KV cache row; first prose example after table',[('s_cache','Caching introduction and Attention matrices, K/V append equations','Causal past K/V can be retained and reused for subsequent tokens.'),('r_model','TinyLM.forward, cache-length offset and layer states','Current cache path preserves position offset and layer cache.'),('r_attn','CausalAttention.forward','Current implementation concatenates previous K/V with new K/V.')],['a_cpu','a_probe','f_cache','a_notes'],'Fixed causal prefix/weights/position rules and compatible batch inputs; new query/projection/attention work remains. No broad speed guarantee.',{'method':'executed','expected':'Same-model full-prefix and cached last-position logits differ by at most 1e-6 on the fixed input.','observed':'Maximum difference 2.384185791015625e-7; cache lengths 3 then 4; shape [1,264].','tolerance':'Absolute tolerance 1e-6, rtol=0.','details':'Seed 0, width 8, CPU FP32, eval/no_grad, IDs [1,2,3,4]; mechanism check only.'})
claim('c3','concept','FlashAttention tiles attention computation to reduce large intermediate table storage and data transfers.','Table Flash Attention row',[('s_flash','Section 3.1 Algorithm 1/Theorem 1 and section 3.2 Theorem 2','IO-aware tiling, online normalization and recomputation avoid quadratic attention-table materialization in HBM.')],['a_notes','a_cpu','f_architecture_online_softmax','f_flash_allocated_memory'],'Full attention is retained mathematically. Own CPU scalar calculation is only a normalization mechanism check; no GPU kernel, L4 timing or memory benchmark was rerun.')
claim('c4','concept','Quantization uses fewer representational levels to record numbers and reduce storage needs; a smaller file alone does not ensure faster execution on every hardware platform.','Table quantization row; first prose example after table',[('s_quant','Introduction; section 2.1 equation 1','Low-bit integer mapping uses scale and zero-point; storage and efficient arithmetic/hardware latency are separate concerns.')],['a_notes','a_cpu','f_architecture_quantize_grid'],'Lossy reconstruction needs scale/metadata; quality, serialization overhead and device speed require their own checks. Tensor-payload probe is not a complete file-compression measurement.')
claim('c5','concept','Distillation can train a smaller student using teacher-generated answers or teacher distributions.','Table distillation row; first prose example after table',[('s_hinton','Sections 1–2, equation 1','A small student learns teacher soft-target probabilities.'),('s_minillm','Section 1 Introduction, black-box/white-box KD distinction','Teacher-generated text and accessible teacher distributions are distinct supervision types.')],['a_notes'],'Distillation is a learning process, not an automatic file conversion or accuracy guarantee; the teacher can be wrong and the student requires validation.')
claim('c6','concept','RLHF describes reinforcement learning guided by human judgments; a typical reward-model route first learns answer comparisons and then estimates a score for a response.','Table RLHF and reward model rows; second prose paragraph',[('s_instruct','Section 3.1 steps 1–3','Human comparisons train a reward model, whose scalar reward guides PPO policy optimization.'),('s_dpo','Section 3 equations 1–2','Pairwise preference fitting learns relative answer rewards.')],['a_notes','f_posttrain_signals'],'PPO does not make automatically generated labels human feedback. Reward scores estimate preferences and are not calibrated correctness probabilities; this is a typical route rather than a universal requirement.')
claim('c7','concept','A policy supplies response-selection probabilities; PPO compares current probabilities with collection-policy probabilities and uses a clipped surrogate. A value/critic estimates expected return as a baseline, while a fixed reference retains the posttraining starting model for measuring policy deviation.','Table PPO, policy, value model/critic/baseline and fixed reference rows',[('s_ppo','Section 2.1 equation 1; section 3 equations 6–7; section 5 equations 9–12 and Algorithm 1','Defines stochastic policy, frozen collection-policy ratio, clipped surrogate, learned value and sampling/update cycle.'),('s_dpo','Section 3 equation 3 and reference-policy paragraph','KL reference is the base SFT policy, distinct from the PPO per-batch old policy.'),('r_post','FiniteResponsePolicy, FiniteValueModel, bandit_advantage and ppo_clipped_objective','Linked one-step task emits card probabilities and estimates context expected reward.')],['a_notes','a_cpu','f_ppo_clip','f_ppo_roles'],'Glossary value description is exact for the contextual-bandit task; a multi-step critic estimates return. Clipping does not hard bound all ratios. Old collection policy refreshes, whereas the described reference stays fixed.')
claim('c8','concept','Safety alignment teaches contextual boundaries for requests that can be completed, requests that need clarification and requests that should be refused.','Table safety alignment row',[('s_safety','Assume best intentions; Stay in bounds; Consider uncertainty, state assumptions, and ask clarifying questions when appropriate','Publisher specifies help, clarification and refusal as context-dependent target behaviors.')],['a_notes'],'This is a behavioral teaching goal. Linked 9.1/9.4 restrict toy authorization fields and labels; glossary does not claim real-world safety certification or success from a keyword rule.')
claim('c9','concept','RAG retrieves external information and provides relevant content to a model for generation.','Table RAG row',[('s_rag','Section 2; sections 2.1 and 2.3','Retriever selects documents, generator conditions on question and retrieved content.'),('r_retrieval','retrieve and lexical_terms','Linked toy retrieval performs literal term matching and returns document text.')],['a_notes','a_cpu','f_rag'],'Retrieval relevance, source trust and generation correctness are separate. Retrieved data need not alter weights; the lexical toy is not equivalent to the original jointly trained RAG architecture.')
claim('c10','concept','In tool calling, the model proposes a tool request, while application code checks it and actually executes the tool.','Table tool call row',[('s_tool','Tool calls; Functions versus tools; The tool calling flow steps 1–5','Model request is distinct from application-side execution and resulting output.'),('r_retrieval','call_tool','Repository validates fields, allowlist and exact numeric argument types before executing arithmetic.')],['a_notes','a_cpu'],'A legal request can still use incorrect arguments; a request alone does not prove execution or model tool competence. Own probe exercised only local arithmetic/validation, not a remote API.')
claim('c11','software','The chapter 13 PPO experiment selects complete prewritten answer cards using labels supplied by program rules; it does not use human scoring or generate the answer token by token.','Second prose paragraph after table',[('r_exp','build_records, rule_best_action, split_records and run_posttraining PPO rollout/update blocks','Candidate text and preference pairs are computed by Python; PPO samples finite action indices.'),('r_post','FiniteResponsePolicy and FiniteRewardModel','Finite feature-to-card output and context/card-identity score model contain no autoregressive text decoder.'),('r_run','results.config and results.splits','Original run fingerprints match independently regenerated program-rule records.')],['a_notes','a_probe','a_cpu','a_result'],'Own CPU execution rebuilds and validates record provenance/model shapes; it does not retrain PPO or replicate its reported quality/timing. The inspected/rebuilt corpus has no human rating records.',{'method':'executed','expected':'Four precomputed cards per context and identical current train/validation/test record fingerprints to the original experiment report.','observed':'165 contexts rebuilt; 132/15/18 contexts across 44/5/6 families; all three official SHA-256 fingerprints match; policy output shape [1,4].','details':'Inspect actual Python arithmetic/templates/rankings and finite-index PPO path; independently call build_records/split_records and compare all canonical split hashes. Own forward shape checks only; no optimizer updates.','denominators':{'all_contexts':165,'cards_per_context':4,'modes':3,'contexts_per_mode':55,'split_contexts':{'train':132,'validation':15,'test':18},'split_families':{'train':44,'validation':5,'test':6},'record_split_seed':42,'probe_training_updates':0,'probe_model_generation_calls':0,'human_rating_records_in_rebuilt_corpus':0}})
claim('c12','concept','DPO directly updates a policy from preferred/rejected response pairs.','Second prose paragraph, final sentence linking to G.2',[('s_dpo','Section 4 equation 7 and DPO outline','Direct pairwise policy loss replaces a separately fitted explicit reward-model/RL loop.'),('r_align','dpo_loss','Current helper computes policy preference gap relative to fixed reference.')],['a_notes','a_cpu','f_ppo_dpo_routes'],'Direct preference data and fixed reference are still required; no claim of guaranteed quality or equivalence to arbitrary PPO training.')
allids=[c['id'] for c in claims]
report={'schema_version':1,'review_stage':'technical','lesson_id':'G.4','source':'course/glossary.md#G.4','reviewer_task':'/root/v4_review_coordinator/factual_v4_g_4','reviewer_context':'fresh','source_sha256':scope['assigned_section_sha256'],'figure_sha256':{r['source']:r['source_sha256'] for r in figs},'verdict':'pass','claims':claims,'sources':sources,'artifacts':artifacts,'issues':[],'checks':{
'factual_accuracy':{'status':'pass','details':'All fourteen table rows and substantive surrounding limits checked in twelve connected claims against personally read originals, current prerequisites and own bounded source/probe evidence.','claim_ids':allids},
'numeric_verification':{'status':'not_applicable','details':'G.4 states no numerical result, equation, quality score, measured latency or memory quantity. Supplementary prerequisite mechanism calculations and record denominators were actually executed and saved, without treating them as new glossary performance claims.','claim_ids':[]},
'figure_consistency':{'status':'pass','details':'G.4 has no figure/code. All nine SVGs in the genuinely needed prerequisites were rendered and personally viewed; positions, arrows, roles and numeric labels were compared with text and relevant mechanisms. Figure hashes include these nine current originals.','claim_ids':['c2','c3','c4','c6','c7','c9','c12']},
'source_verification':{'status':'pass','details':'Personally read and located original paper/document sections, independently hashed retrieved bytes, inspected and fully hashed registered repository files, and rebuilt original experiment record fingerprints. Source catalog was navigation to original PDFs only.','claim_ids':allids},
'limitations':{'status':'pass','details':'Separates storage from latency and activated from stored parameters; distinguishes RLHF provenance from PPO method, fixed reference from old policy, contextual bandit from token generation, target safety behavior from demonstrated safety, and retrieval/tool requests from correct final answers. No GPU/quality/timing replication claimed.','claim_ids':allids}},'scope_limits':['Only complete current G.4 and necessary explicit prerequisites; no owned introduction.','No training, GPU benchmark, API-model call, heavy data/model download or installation; no full chapter or release audit.','Original empirical posttraining record fingerprints validated; training quality and elapsed times not replicated.','Original papers and full HTML remain only in ignored research; public artifacts retain own analysis and retrieval receipts.','Native checker validates schema and current provenance, not factual truth.'],'independence':{'previous_assigned_report_preserved_unread':True,'prior_substantive_judgment_read':False,'incidental_exposure':'Initial rg --files printed unrelated artifact filenames only. No prior report/draft contents or judgments were read; shared catalog supplied original PDF bytes only.'},'necessary_prerequisite_sections':scope['necessary_prerequisite_sections']}
(root/'docs/technical-reviews/G.4.json').write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n')
print('Wrote G.4 independent report; verdict pass; claims',len(claims),'original sources',len(receipts),'figures',len(figs))
