from pathlib import Path
import hashlib,json

root=Path.cwd();out=root/'docs/technical-reviews/artifacts/natural-v4-factual/T.8'
def sha(path):return hashlib.sha256(path.read_bytes()).hexdigest()
env={'python':'3.13.5','torch':'2.14.1+cpu','device':'cpu; CUDA unavailable'}
artifacts=[]
def artifact(id,name,kind,description,**extra):
 p=out/name;artifacts.append(dict(id=id,kind=kind,path=str(p.relative_to(root)),sha256=sha(p),description=description,**extra))
artifact('section','section.raw.md','source_snapshot','Complete assigned raw UTF-8 T.8 including blank lines; no owned introduction.')
artifact('inspection','inspection.json','source_snapshot','Own original-source summaries, complete prerequisite SHA map, personal figure notes, independence disclosure and limits.')
artifact('probe_code','verify.py','code','Own bounded CPU recipes, counts, raw-ID and original GPU record arithmetic audit.')
artifact('probe','verify.third.stdout.txt','execution','Successful own probes and original-record recomputation; this is not GPU replication.',command='PYTHONPATH=. .venv/bin/python docs/technical-reviews/artifacts/natural-v4-factual/T.8/verify.py',result='Native exit 0; all assertions completed; three actual toy 200-step CPU recipes completed.',environment=env)
artifact('probe_stderr','verify.third.stderr.txt','source_snapshot','Actual successful probe stderr, including CPU profiler messages.')
artifact('probe_receipt','verify.third.execution.json','source_snapshot','Actual successful command, native exit and environment receipt.')
artifact('supplement_code','supplement.py','code','Own fixed-checkpoint artifact SHA identity, SFT answer-ID recount, CLI switches and toy-family probe.')
artifact('supplement','supplement.stdout.txt','execution','Own supplementary original-record and CLI checks.',command='PYTHONPATH=. .venv/bin/python docs/technical-reviews/artifacts/natural-v4-factual/T.8/supplement.py',result='Native exit 0; four fixed checkpoint copies match; SFT 5/10; all declared CLI switches forward; toy 9/1/2.',environment=env)
artifact('supplement_stderr','supplement.stderr.txt','source_snapshot','Actual supplementary stderr (empty).')
artifact('retrieval','authority-retrieval.json','source_snapshot','Genuine original retrieval SHA receipts and direct PyTorch 2.14 documentation HTTP 403 failures; complete papers remain ignored.')
artifact('fallback','authority-source-fallback.json','source_snapshot','Genuine exact-version original PyTorch source retrieval SHA and .rst 404 attempts.')
artifact('markdown','authority-markdown-fallback.json','source_snapshot','Successful exact-version CUDA and AMP .md source retrieval SHA receipts.')
artifact('historical','original-code-retrieval.json','source_snapshot','Read-only original run revision source retrieval; architecture hashes match original measured records.')
artifact('adam_receipt','adam-source-retrieval.json','source_snapshot','Original Adam implementation retrieval SHA matches installed exact-version source.')
artifact('tied_receipt','tied-source-retrieval.json','source_snapshot','Original Press/Wolf v3 PDF retrieval receipt, full PDF retained only in ignored research.')
figures={}
for name in ['flash_allocated_memory','cache','architecture_gqa_cache','normalization','rope']:
 figures[f'course/figures/{name}.svg']=sha(root/f'course/figures/{name}.svg')
 artifact('fig_'+name,name+'.png','figure_render','Personally viewed Chromium render of current necessary prerequisite SVG; specific consistency notes in inspection.json.')
artifact('render_receipt','render.execution.json','source_snapshot','Actual existing-Chromium rendering command, native exit 0 and environment; previous render failures remain preserved.')

sources=[]
def repo(id,path,note,title=None,version=None):
 p=root/path;sources.append(dict(id=id,kind='repository_code',title=title or path,path=path,sha256=sha(p),version=version or 'Working tree inspected 2026-10-04 at assigned source revision 25ca4bf5f8f8dc0a9e88aa6cd70caeb4c2f419e8',verified=True,inspection_note=note))
repo('arch','scripts/course_experiments/architecture.py','Read dataset, matched initializers, training, branch memory reset/timing, modern/MoE fixed export, cache/SDPA/packing/accumulation/checkpoint, independent compile, precision and Flash paths. Historical architecture bytes independently retrieved at each recorded revision and match original code_sha256.')
repo('common','scripts/course_experiments/common.py','Read Context dependency, family splitting, SHA serialization, byte-window targets, complete heldout NLL and first-eight generation.')
repo('runner','scripts/course_experiments/run.py','Read execute/main: explicit CUDA guard, dependency/output defaults, step-scale smoke status, outer peak scope and result serialization.')
repo('model','tiny_perceptron/model.py','Read ModelConfig, pre-norm Blocks, learned/rotary positions, true tying, loss_sum and generation limits.')
repo('modern_code','tiny_perceptron/modern.py','Read RMSNorm, paired RoPE, ReLU²/SiLU gate, dropless selected-only expert dispatch, top-1 original probability and top-2 renormalization.')
repo('attention','tiny_perceptron/attention.py','Read causal/PAD/segment visibility, scale, GQA unexpanded cache, repeat at computation and SDPA call.')
repo('train','scripts/train.py','Read parser/defaults, prepare_examples direct --data windows with no extra split, training loop, 0.01 MoE auxiliary, actual checkpoint/sidecar report writes.')
repo('evaluate','scripts/evaluate.py','Read text[:4] prompt, new-only generated IDs, complete per-row next-token/EOS loss, row/skipped/null text exact-match and mean_token_nll output.')
repo('prepare','scripts/prepare_data.py','Read complete toy and attribute generators and deterministic family assignment; actual toy CLI executed.')
repo('data','tiny_perceptron/data.py','Read ByteTokenizer, shifted targets, assistant/EOS labels, PAD and IGNORE handling.')
repo('saving','tiny_perceptron/training.py','Read seed/device choice and checkpoint save/load; no dtype conversion during saving.')
repo('fetch','scripts/fetch_training_assets.py','Read asset-specific LFS fetch/extraction CLI; not executed to download new assets.')
for name in ['modern','moe','efficiency','flash_probe','precision','sft']:
 d=json.loads((root/f'docs/course-experiments/results/{name}.json').read_text())
 repo('record_'+name,f'docs/course-experiments/results/{name}.json','Original measured run record personally inspected; inputs/configuration, effective target counts, schedules, raw generated IDs, measurement scopes and applicable original timings/bytes audited by own verify.py/supplement.py. This source is an original project empirical record, not another review verdict.',title='Original '+name+' L4 empirical record',version='Original run revision '+d['revision'])

receipts={r['id']:r for name in ['authority-retrieval.json','authority-source-fallback.json','authority-markdown-fallback.json'] for r in json.loads((out/name).read_text()) if 'sha256' in r}
commit='5c4886908584029761b579af026dcfb627c84070'
def external(id,title,kind,version,note,receipt=None):
 r=receipt or receipts[id]
 sources.append(dict(id=id,title=title,kind=kind,url=r['url'],version=version,verified=True,checked_original=True,accessed_on='2026-10-04',retrieval_sha256=r['sha256'],authority_reason='Original author paper or official publisher source; exact version actually retrieved and relevant definitions read.',inspection_note=note))
for id,title,ver,note in [
 ('rope','RoFormer','arXiv 2104.09864v5','§3.2, Eq14-16: paired rotations and relative Q/K dot-product; no extrapolation guarantee.'),
 ('rms','Root Mean Square Layer Normalization','arXiv 1910.07467v1','§4 Eq4: RMS scaling without centering; original speed results are model/hardware specific.'),
 ('swiglu','GLU Variants Improve Transformer','arXiv 2002.05202v1','§2 Eq5-6: Swish/SiLU gate, three matrices; original matched design shrinks hidden width to 2/3.'),
 ('switch','Switch Transformers','arXiv 2101.03961v3','§2.2 Eq4-6: selected expert routing, discrete f and differentiable mean probability P. Repository top-2 denominator extension is explicit.'),
 ('gqa','GQA: Training Generalized Multi-Query Transformer Models','arXiv 2305.13245v3','§2.1-2.2: Q groups share KV; MQA endpoint; original uptraining mean-pools existing KV, unlike this repository documented reinitialization.'),
 ('flash','FlashAttention','arXiv 2205.14135v2','§3.1 Algorithm1/Theorem1 and §3.2 Theorem2: exact mathematical attention, tiled SRAM/reduced HBM IO, backward recomputation; no bitwise equality guarantee.')]:external(id,title,'paper',ver,note)
external('tied','Using the Output Embedding to Improve Language Models','paper','arXiv 1608.05859v3','§3: U=V=S, shared input/output embedding and sum of role gradients.',json.loads((out/'tied-source-retrieval.json').read_text()))
notes={
 'memory_source':'torch/cuda/memory.py L381-397, L525-590: tensor allocated bytes, peak since program start or last reset, current device/default, reserved allocator total. Literal docs/2.14/generated/torch.cuda.memory.max_memory_allocated.html retrieval returned 403; exact official implementation supplies its definition.',
 'cuda_md':'docs/source/notes/cuda.md L68-122 TF32 10-bit mantissa input rounding and FP32 accumulation; L505-521 allocated tensor space versus reserved unused cache.',
 'amp_md':'docs/source/amp.md L25-39 op-specific precision; L123-145 gradient scaling/unscale and limited FP16 range. No automatic quality or speed guarantee.',
 'autocast_source':'torch/amp/autocast_mode.py L53-90: default precision model/optimizer, op-specific execution dtype, forward context and backward outside.',
 'scaler_source':'torch/amp/grad_scaler.py L53-101: unscale before optimizer, inf/NaN detection skips underlying update, not every attempted step succeeds.',
 'functional_source':'torch/nn/functional.py L6367-6482: SDPA scale, True visibility, explicit dropout, automatic dispatch/input restrictions, backend numerical differences and GQA constraints.',
 'checkpoint_source':'torch/utils/checkpoint.py L435-488: computation-for-memory trade; explicit use_reentrant=False; changed backward invocation can break equivalence.',
 'compile_source':'torch/__init__.py L3050-3103: compile cache, fullgraph, static dynamic=False and Inductor backend; does not promise speed.',
 'sdp_source':'aten/.../cuda/sdp_utils.cpp L413-470, L906-918, L1040-1077: Flash build, CUDA device, SM range, low precision dtype and shape/mask/head/gradient constraints.',
}
for id,note in notes.items():external(id,'PyTorch original '+id,'official_source','PyTorch 2.14.1 commit '+commit,note)
external('adam','PyTorch Adam original implementation','official_source','PyTorch 2.14.1 commit '+commit,'torch/optim/adam.py L160-185 initializes FP32 parameters historical exp_avg/exp_avg_sq with zeros_like; original file hash equals installed source.',json.loads((out/'adam-source-retrieval.json').read_text()))
external('nvidia','NVIDIA CUDA GPU capability table','official_docs','Live original table retrieved 2026-10-04','L4 appears in compute capability 8.9 group; eligibility still depends on actual build/input/runtime.')
sources.append(dict(id='derivation',kind='derivation',title='Own parameter and measurement arithmetic',verified=True,details='RoPE 141568−128×64=133376; RMSNorm 141568−5×64=141248; tied 141568−264×64=124672; SwiGLU 141568+2×(64×256+256)=174848. Two-layer expert total 264704 plus router512 plus other75392=340608; selected proxy non-expert75904 plus half experts132352=208256. MiB=2^20=1048576 bytes. Every reported peak increase is original peak minus baseline; nine-sample median independently recomputed. See own executable audit output.'))
claims=[]
def claim(id,kind,statement,location,refs,scope,expected=None,observed=None,details=None,denominators=None):
 c=dict(id=id,kind=kind,statement=statement,location=location,status='verified',evidence=[dict(source_id=s,locator=l,supports=support) for s,l,support in refs],artifact_ids=['inspection'],scope=scope)
 if kind in ['numeric','software','empirical']:
  c['artifact_ids']+=['probe','supplement'];c['verification']=dict(method='executed',expected=expected,observed=observed,details=details)
  if kind=='numeric':c['verification']['tolerance']='Exact integer counts; reported NLL rounded to five decimals and ms/MiB at printed precision.'
  if denominators:c['verification']['denominators']=denominators
 claims.append(c)
claim('c1','concept','RoPE rotates paired Q/K; RMSNorm uses RMS without centering; ReLU² squares retained positive values; SwiGLU uses a SiLU content gate; true input/output tying shares one parameter. Their fixed-width comparison can change parameters and initialization.','Modern architecture paragraphs and switch descriptions',[('rope','§3.2 Eq14-16','Position mechanism'),('rms','§4 Eq4','Normalization'),('swiglu','§2 Eq5-6 and matched hidden-size discussion','Gating and parameter matching'),('tied','§3 U=V=S','Shared table'),('modern_code','RMSNorm/rope/DenseFFN','Exact ReLU² and implemented mechanisms'),('model','TinyLM.__init__','Actual tied Parameter')],'Mechanisms and storage facts; original empirical quality is separately scoped below.')
claim('c2','software','The toy commands split families first, train only the supplied train file, and save parameter/time sidecars; evaluate text uses four-character prompts, new-only generated IDs, per-row samples/skips and valid next-byte/EOS NLL. Architecture/backend/head flags reach the actual model.','Initial toy commands and evaluation instructions',[('prepare','generate_records/main','Seeded 9/1/2 split'),('train','parser/prepare_examples/main','Direct file, flags, sidecar'),('evaluate','evaluate/main','Prompt, row, generated, denominators'),('data','ByteTokenizer/shifted','Byte units')],'Actual CLI recipes ran on CPU with only output locations and device set explicitly. This validates workflow, not GPU speed or convergence.','Three complete 200-step toy CPU commands; one 35-target validation row per model; supported switch forward.','All three native exits 0; validation effective_tokens=35, row=0, prompt=colo, no skipped; sidecar parameters 33632/33536/58816. Combined switches yield [1,3,264].','Own verify.py executes actual prepare/train/evaluate CLIs and supplement.py exercises remaining flags; NLL remains a continuation metric.')
claim('c3','numeric','Modern parameters are 141568/133376/141248/141568/174848/124672. MoE total 340608 and top-2 capacity proxy 208256; closest Dense 207680 or 329888 are approximate matches, not exact per-token weight access/FLOPs.','Modern table and MoE resource comparison',[('derivation','Parameter formulas in details','Transparent counts'),('arch','_parameter_budget/_matched_width','Full non-expert tables included'),('model','description/parameters','Actual model counts')],'Storage/proxy accounting only. No FLOPs claim or equal-parameter guarantee.','All integer counts and matching gaps stated in T.8.','Own instantiated counts exactly match; Dense width80 gap−576, width104 gap−10720; model FP32 weights 566272 bytes.','Count unique Parameters and inspect proxy inclusion of whole embedding/position tables; derive architectural differences.')
claim('c4','empirical','The six modern rows use 512 complete stories split 409/51/52 by complete-content hash, width64/layers2/heads4/max128, byte vocabulary, same seed42/batch16/lr0.003/240 updates and 452102 targets. All table NLL/count/time values and poor first continuations match original records.','Modern recipe, six-row table, initial-table and continuation paragraphs',[('record_modern','results.dataset/variants/runtime/artifacts','Original metrics and configuration'),('common','split_records/text_examples/evaluate_lm','Full story split, windows, loss and first-eight generation'),('arch','run_modern/_train/_copy_matching','Schedules and starting tables')],'Audited original L4 FP32 run, not own GPU training. 51/52 full-loss records versus only first-eight samples; one seed/short run, no length extrapolation or FLOPs measurement.','Six displayed rows and denominators.','All six parameter/NLL/ms rows exact at printed precision; original sample byte IDs decode to quoted baseline/RoPE text.','Recreated original split from existing input SHA, independently summed targets and replayed random batch choices; divided NLL sums by tokens.',{'seed':42,'story_records':512,'train_validation_test':[409,51,52],'updates_per_variant':240,'batch_windows':16,'training_targets_per_variant':452102,'validation_targets':39256,'test_targets':41914,'generation_samples_per_heldout_side':8})
claim('c5','empirical','Seven MoE comparisons reuse that split but each has 180 updates/337761 targets; top-2 aux0.01 test2.30170 and 27.242ms compares with Dense2.30906/11.965ms or 2.24943/14.054ms. Router statistics and imperfect generation are recorded separately.','MoE training and resource/timing paragraphs',[('record_moe','results.variants/dataset/teacher_variant','Original seven schedules and comparisons'),('arch','run_moe/_parameter_budget/_routing','Fixed proxy matching and route statistics'),('switch','§2.2 Eq4-6','Expert routing/auxiliary conditions')],'Original fixed L4 run audit. Capacity proxy includes all non-expert parameters; neither equal FLOPs nor a GPU speed guarantee; 180 updates differ from modern240.','Quoted MoE/Dense table, same split and seven complete schedules.','All seven 180-update counts/targets match; selected three costs/times match and per-layer dispatch counts total token×top-k.','Independent parameter construction, sampler replay, NLL sum division and raw generation ID decode.',{'seed':42,'variants':7,'train_validation_test':[409,51,52],'updates_per_variant':180,'training_targets_per_variant':337761,'validation_targets':39256,'test_targets':41914,'experts_per_layer':4,'top_k':[1,2]})
claim('c6','software','Full experiment commands use explicit CUDA and SFT dependencies; named output files and fixed model.pt copies are those stated, without best-score selection. Smaller step-scale means a smoke run. Compile payload and Flash fixture are not ordinary model checkpoints.','Full modern/MoE/efficiency/Flash/precision entry and output paragraphs',[('runner','execute/main','CUDA guard, output/dependency defaults, smoke scope'),('arch','run_modern/run_moe/run_efficiency/run_precision/run_flash_probe/_compile_probe','Named saves and fixed copies; payload/fixture formats'),('fetch','main','Specific asset acquisition'),('saving','load_checkpoint','Accepted model format')],'No new assets or weights downloaded. Artifact manifests and implementation establish copy identity; own CPU execution establishes explicit CUDA refusal.','Model copies baseline/top2_aux0.01/ordinary/fp32 and CUDA-only refusal.','All original model.pt artifact SHAs equal fixed target; execute(cuda) raises A GPU experiment must not silently fall back to CPU before execution.','Own supplement recounts manifests and verifies CLI flags; inspect raw compile and fixture dictionaries against accepted checkpoint format.')
claim('c7','concept','CUDA timing must complete device work at interval boundaries, distinguish warmup/update/inference scopes, and use per-branch allocator tensor-byte peaks after reset. Reserved unused space, driver and separate Inductor-worker allocations are excluded; MiB=2^20 bytes. TF32 can round FP32 multiplication inputs while accumulating FP32.','Optional efficiency measurement conditions and max_memory paragraphs',[('memory_source','L381-397 and L525-590','Official peak/current/reserved definitions and reset origin'),('cuda_md','L68-122 and L505-521','TF32 precision and cached memory distinctions'),('arch','_sync/_benchmark/_train/_flash_measure/_compile_probe','Actual synchronized boundaries/reset/worker scopes')],'Literal official 2.14 memory URL returned403; exact2.14.1 official source definitions verified. Allocator metrics do not measure whole-device usage or combined independent processes. Timing intervals are specific to their functions.')
claim('c8','empirical','Efficiency starts from direct SFT (45/5/10, original test5/10), trains MHA/GQA100 times and four update branches40 times from MHA with equal targets; padded/packed40 train a changed assistant-text objective, test1/10, without three branch memory fields. FP32 profiler selected memory-efficient SDPA. Inductor compiled one static FFN, first7.717s, slower steady-state, no break-even.','Efficiency, mechanisms, packing and compilation paragraphs',[('record_efficiency','results.models/update_variants/packing/manual_vs_sdpa/compile','Original scopes, results and raw times'),('record_sft','results.after/data','Original source dataset and 5/10'),('checkpoint_source','L435-488','Recomputation contracts'),('compile_source','L3050-3103','Compile settings')],'Original CUDA audit, supported by independent bounded CPU gradient tests. No own GPU benchmark; packing changes task, no packing memory comparison; no full-model compilation claim.','100/40/40 schedules, correct denominators, explicit memory field absence, memory-efficient profile,7.717s.','Counts11278/2328/845 match; padded and packed each test1/10; six major branches have correct peak-minus-baseline bytes. Compile nine-sample medians recompute and compiled is slower.','Rebuild SFT split and target schedules, recount all heldout raw IDs and medians; own CPU checkpoint output/gradient errors0, accumulation error4.47e−8 with7+13 denominator20, SDPA close.',{'seed':42,'train_validation_test_questions':[45,5,10],'mha_gqa_updates':100,'mha_gqa_training_targets':11278,'main_update_branch_updates':40,'main_branch_training_targets':2328,'packing_updates':40,'packing_training_targets':845,'validation_answer_targets':36,'test_answer_targets':69,'inference_warmup':3,'inference_measurements':9})
claim('c9','empirical','Flash supplement uses only fixed [2,4,512,32] Q/K/V, FP16/BF16, forced CUDA Flash, finite close outputs/QKV gradients and real forward/backward kernels. Original L4/cu126/CUDA12.6/driver580.95.05/revision382604 run gives FB1.689/0.503ms and1.502/0.458ms; common65MiB baseline plus32.75/2.032MiB yields97.75/67.032MiB.','Flash recipe and measured cost paragraphs',[('record_flash_probe','results.configuration/runtime/routes','Original actual kernel, numerics, environment and nine samples'),('sdp_source','L413-470/L906-918/L1040-1077','Exact build/input eligibility'),('nvidia','Compute capability 8.9 group','L4 hardware classification'),('flash','§3.1 Algorithm1/Theorem1; §3.2 Theorem2','Component mechanism, not quality guarantee')],'Original fixed-core GPU record audit only. No loss/optimizer/full-model training or quality, no full-device savings ratio. Both precision routes use same declared fixture/upstream and fixed tolerances.','Declared kernel/numerical/timing and memory values.','All routes finite/within tolerance; profiles contain actual flash_fwd and flash_bwd CUDA kernels; original nine-sample medians and byte conversions match every printed value.','Independently recompute each median and peak delta; inspect original reference arithmetic, output/gradient thresholds and profiler operator/kernel records; personally view flash memory SVG.',{'seed':42,'QKV_shape':[2,4,512,32],'dtypes':['fp16','bf16'],'warmup_calls_per_route':3,'timed_calls_per_route':9,'baseline_MiB':65,'model_updates':0})
claim('c10','concept','AMP selects op dtype rather than statically halving stored weights; this FP32-model Adam recipe retains FP32 parameter/history state. FP16 GradScaler can skip updates on inf/NaN; completed attempts require separate update/skip counts.','Precision AMP and update-count paragraphs',[('amp_md','L25-39/L123-145','Op precision and scaling'),('autocast_source','L53-90','Default parameter dtype and context'),('scaler_source','L53-101','Gradient-finite skip rules'),('adam','L160-185','FP32 zeros_like moment states'),('arch','_train/run_precision','Actual copy/AMP/scaler placement')],'Specific default FP32 recipe; AMP does not promise speed, half storage, perfect quality or every update succeeding. Own BF16 CPU optimizer-state check supports implementation, not CUDA FP16 replication.')
claim('c11','empirical','Precision reloads original single-head SFT independently for FP32/BF16/FP16; each completes200 attempts/200 updates/0 skips. Test matches7/10,6/10,4/10, finite parameters/logits, FP32 weights, and neither AMP route is faster in this measured training/inference scope.','Final precision command/results paragraph',[('record_precision','results.variants/runtime/source/dataset','Original schedules, dtypes, raw IDs, costs and memory'),('record_sft','results.after.test','Original single-head5/10'),('arch','run_precision/_train','Independent starting copies and counts')],'Original small single-seed L4 audit; no own GPU replication, larger-model extrapolation or claims of uniform AMP memory savings. Branch baselines differ and peak deltas are not activation-only savings.','200/0 counts and7/6/4 test answers; exact source split and dtype/speed bounds.','All raw-ID recounts match; 22493 training targets each; weights FP32/566272 bytes and logits FP32/BF16/FP16; AMP update/forward medians exceed FP32.','Reconstruct SFT questions/splits, replay seed42 batches, compare original timings, dtype/finite flags, scaler history and raw IDs; recompute branch memory bytes independently.',{'seed':42,'train_validation_test_questions':[45,5,10],'attempts_per_variant':200,'successful_updates_per_variant':200,'skipped_updates_per_variant':0,'training_targets_per_variant':22493,'validation_targets':36,'test_targets':69,'forward_warmup':3,'forward_samples':9})

ids=[c['id'] for c in claims]
checks={
 'factual_accuracy':dict(status='pass',details='Complete T.8 and necessary linked prerequisite sections read; all substantive architecture/API/data/measurement/empirical groups independently verified against originals.',claim_ids=ids),
 'numeric_verification':dict(status='pass',details='Actual model counts/proxy gaps, split SHA/target totals, schedules, raw-ID matches, all quoted NLL/ms/MiB and median/peak arithmetic recomputed. Three actual small 200-step CPU CLI runs and two-step AMP/gradient probes passed.',claim_ids=['c2','c3','c4','c5','c6','c8','c9','c11']),
 'figure_consistency':dict(status='pass',details='T.8 has no direct SVG. Five necessary linked canonical SVGs were actually rendered and personally viewed; cache positions, GQA connections/bytes, LN/RMS feature scope, RoPE relative angle and Flash baseline/scale/numbers match text.',claim_ids=['c1','c3','c7','c9']),
 'source_verification':dict(status='pass',details='Original versioned papers and exact PyTorch2.14.1 source retrieved/read. Literal 2.14 memory-path docs403 preserved, definitions verified from exact official memory.py. Historical experiment source hashes match original code manifests; current code registered with full SHA.',claim_ids=ids),
 'limitations':dict(status='pass',details='Audited original GPU results are explicitly separate from own CPU execution. Single seed, small fixed data, short training, changed packing objective, approximate capacity proxy, per-reset/process tensor memory and component-only Flash/compile scopes respected; no GPU replication or full-device/general quality/speed claim.',claim_ids=ids)
}
report=dict(schema_version=1,review_stage='technical',lesson_id='T.8',source='course/training.md#T.8',reviewer_task='/root/v4_review_coordinator/factual_v4_t_8',reviewer_context='fresh',source_sha256=sha(out/'section.raw.md'),figure_sha256=figures,verdict='pass',claims=claims,sources=sources,artifacts=artifacts,issues=[],checks=checks,prerequisite_sha256=json.loads((out/'inspection.json').read_text())['prerequisites'],scope='Complete assigned section; no owned introduction; exact code/API/source and original fixed empirical records audited. Own CPU execution only.',independence=json.loads((out/'inspection.json').read_text())['independence'])
target=root/'docs/technical-reviews/T.8.json';target.write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n');print('Own report written',sha(target),'claims',len(claims),'sources',len(sources))
