"""Write this reviewer's new report without opening the canonical prior report."""
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[4]
OUT = Path(__file__).resolve().parent
PREFIX = OUT.relative_to(ROOT).as_posix() + '/'
TASK = '/root/phase4_factual_coordinator/factual_15_1'
freeze = json.loads((OUT / 'freeze-metadata.json').read_bytes())
audit = json.loads((OUT / 'cpu-verification.json').read_bytes())
assert audit['all_assertions_passed'] and audit['environment']['reviewer_task'] == TASK
env = {'python': '3.13.5', 'torch': '2.14.1+cpu', 'torch_git_version': '5c4886908584029761b579af026dcfb627c84070', 'device': 'CPU', 'threads': '1'}


def digest(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def artifact(identifier, filename, kind, description, **extra):
    return {'id': identifier, 'path': PREFIX + filename, 'sha256': digest(OUT / filename), 'kind': kind, 'description': description, **extra}


artifacts = [
    artifact('frozen-chapter', 'frozen-chapter-15.md', 'source_snapshot', 'Actual full Markdown frozen input read at dispatch; SHA is not an assertion about a later whole chapter.'),
    artifact('section', 'original-section-15_1.md', 'source_snapshot', 'Exact original UTF-8 bytes of 15.1, no newline normalization.'),
    artifact('intro', 'original-intro-15.md', 'source_snapshot', 'Exact chapter introduction personally read; independent summary in freeze metadata and report.'),
    artifact('freeze', 'freeze-metadata.json', 'source_snapshot', 'Raw section/intro/full frozen-input fingerprints and own introduction summary.'),
    artifact('prior-4_4', 'necessary-prior-4_4.md', 'source_snapshot', 'Personally read linked preceding FFN section; no figures in that section.'),
    artifact('original-fence', 'original-execution/fence-1.py', 'code', 'Unmodified original Python fence extracted from raw 15.1.'),
    artifact('original-run', 'original-execution/execution.json', 'execution', 'Actual CPU run of original fence through the section helper; worker command and stdout hashes retained.', command='.venv/bin/python docs/review-tools/section_facts.py course/chapters/15.md#15.1 --output /tmp/factual-15_1-20261005-original --execute --timeout 60', result='Exit 0; one fence attempted; outputs [[4.0,5.0],[5.0,4.0]] and duplicate rows, token counts 2/4 and weight count 12/12; no guard failures.', environment=env),
    artifact('original-stdout', 'original-execution/stdout.txt', 'source_snapshot', 'Real original program stdout.'),
    artifact('original-env', 'original-execution/environment.json', 'source_snapshot', 'Real helper Python/PyTorch/CPU versions and attempted-fence list.'),
    artifact('original-extraction', 'original-execution/extraction.json', 'source_snapshot', 'Raw extraction provenance; zero referenced SVGs.'),
    artifact('cpu-code', 'verify_cpu_and_measurements.py', 'code', 'Bounded original replay, scalar arithmetic, negative/zero and single-row variants, width variant, parameter counts and named raw JSON pointers.'),
    artifact('cpu-run', 'cpu-verification.json', 'execution', 'Actual independent CPU assertions and exact inspected measurement/provenance pointers.', command='.venv/bin/python docs/technical-reviews/artifacts/phase4-15_1-independent/verify_cpu_and_measurements.py > docs/technical-reviews/artifacts/phase4-15_1-independent/cpu-stdout.txt 2> docs/technical-reviews/artifacts/phase4-15_1-independent/cpu-stderr.txt', result='Exit 0; all arithmetic, row-independence, count, 180-update-record, token-denominator and rounding assertions passed. No training/model reevaluation was executed.', environment=env),
    artifact('cpu-stdout', 'cpu-stdout.txt', 'source_snapshot', 'Real stdout with named observed values; stderr separately retained and empty.'),
    artifact('raw-result', 'moe-original-result.json', 'source_snapshot', 'Unmodified complete original moe.json retained including unread annotations; only pointers listed in CPU audit inspected for evidence.'),
    artifact('primary-manifest', 'primary-source-manifest.json', 'source_snapshot', 'Personally checked original version, upstream SHA, URL, AST locators and exact primary snapshot hashes.'),
    artifact('collect-code', 'collect_primary_snapshots.py', 'code', 'Exact source-snapshot collection operations; copies only authority originals and AST-selected primary excerpts.'),
    artifact('report-code', 'write_report.py', 'code', 'Fresh report generation code; does not read any old canonical report.'),
]
for identifier, filename, description in [
    ('transformer-original', 'transformer-v7.pdf', 'Original arXiv 1706.03762v7 personally checked; section 3.3 equation (2), p.5.'),
    ('moe-original', 'sparsely-gated-moe-v1.pdf', 'Original arXiv 1701.06538v1 personally checked; sections 1.2 and 2, equation (1).'),
    ('torch-ops-original', 'pytorch-tensor-operations.txt', 'Exact upstream torch.tensor/cat/matmul/numel documentation nodes at installed immutable commit.'),
    ('torch-methods-original', 'pytorch-tensor-methods.txt', 'Exact upstream Tensor.numel and Tensor.tolist documentation nodes.'),
    ('torch-length-original', 'pytorch-tensor-length.txt', 'Exact upstream Tensor.__len__ implementation node.'),
    ('torch-relu-original', 'pytorch-relu.txt', 'Exact upstream functional.relu implementation dispatching elementwise torch.relu.'),
    ('torch-linear-original', 'pytorch-linear.txt', 'Exact upstream nn.Linear class with weight/bias shape and constructor contract.'),
]:
    artifacts.append(artifact(identifier, 'primary-snapshots/' + filename, 'source_snapshot', description))
for identifier, filename in [('modern-code','modern.py'), ('model-code','model.py'), ('attention-code','attention.py'), ('common-code','common.py'), ('architecture-code','architecture-experiment-revision.py')]:
    artifacts.append(artifact(identifier, 'repository/' + filename, 'code', 'Unmodified repository original; precise personally read locators and historical version recorded in source.'))


def authority(identifier, kind, title, url, version, inspection, reason):
    return {'id': identifier, 'kind': kind, 'title': title, 'url': url, 'version': version, 'verified': True, 'checked_original': True, 'accessed_on': '2026-10-05', 'authority_reason': reason, 'inspection_note': inspection}


sources = [
    authority('transformer', 'paper', 'Attention Is All You Need', 'https://arxiv.org/pdf/1706.03762v7', 'arXiv:1706.03762v7, 2 Aug 2023; personally checked title/version page', 'Personally read original title/version, first-page and introduction context, section 3.2.3 attention-position discussion and section 3.3 p.5 equation (2): same FFN at each position; two affine transforms with ReLU. Retained exact PDF and precise excerpt. No translation-result conclusions used.', 'Original Transformer authors describe the position-wise FFN structure and formula.'),
    authority('moe', 'paper', 'Outrageously Large Neural Networks: The Sparsely-Gated Mixture-of-Experts Layer', 'https://arxiv.org/pdf/1701.06538v1', 'arXiv:1701.06538v1, 23 Jan 2017; personally checked first-page identifier', 'Personally read original pp.1-4, especially section 1.2 pp.2-3, section 2 p.3 equation (1) and section 2.1 p.4. Separate FFN experts, token/position-wise sparse selection, and zero gates allowing skipped expert evaluation. Paper performance numbers are not used to infer this repo performance.', 'Original sparse MoE paper directly defines the experts, sparse gate and conditional evaluation.'),
]
commit = '5c4886908584029761b579af026dcfb627c84070'
for identifier, filename, title, note in [
    ('torch-ops', 'torch/_torch_docs.py', 'PyTorch tensor operation contracts', 'Personally read AST-selected torch.tensor L9582-9635, torch.cat L2531-2577, torch.matmul L7908-7990 and torch.numel L8814-8834; exact cached upstream original SHA personally verified against locator and retained in primary manifest. Covers tensor construction without autograd history, 2-D matrix product, concatenation dimension, and total element count.'),
    ('torch-methods', 'torch/_tensor_docs.py', 'PyTorch tensor method contracts', 'Personally read AST-selected Tensor.numel L3622-3629 and Tensor.tolist L5445-5465; original complete SHA checked, precise excerpt retained. numel delegates to total-element-count documentation and tolist returns nested ordinary lists.'),
    ('torch-length', 'torch/_tensor.py', 'PyTorch Tensor.__len__ original implementation', 'Personally read AST-selected Tensor.__len__ L1189-1203: rejects scalar tensors and otherwise returns shape[0]. Initial guessed cached filename caused a sed missing-file error; corrected by using actual locator path. No source evidence was inferred from that failed read.'),
    ('torch-relu', 'torch/nn/functional.py', 'PyTorch functional.relu original implementation', 'Personally read AST-selected relu L1766-1778: elementwise ReLU and non-inplace path dispatches torch.relu. Mathematical max(0,x) definition separately checked in Transformer equation (2) and independent negative/zero CPU cases.'),
    ('torch-linear', 'torch/nn/modules/linear.py', 'PyTorch nn.Linear original shape and bias contract', 'Personally read AST-selected Linear L53-140: affine y=xA^T+b; weight shape [out_features,in_features], default bias=True and bias length out_features; other input axes preserved. Retained exact class excerpt and original SHA.'),
]:
    sources.append(authority(identifier, 'official_source', title, 'https://raw.githubusercontent.com/pytorch/pytorch/' + commit + '/' + filename, 'PyTorch immutable upstream commit ' + commit + '; installed execution 2.14.1+cpu matches torch.version.git_version', note, 'PyTorch project upstream original source at immutable commit matching installed runtime; original cached source personally checked, locator index used only to locate it.'))


def repository(identifier, filename, title, note, version='Original experiment Git revision 48a4f3e912b483d70aee57c42c2aac226534a9a6; full bytes match recorded code_sha256'):
    return {'id': identifier, 'kind': 'repository_code', 'title': title, 'path': PREFIX + filename, 'sha256': digest(OUT / filename), 'version': version, 'verified': True, 'inspection_note': note}


sources.extend([
    repository('modern', 'repository/modern.py', 'Original DenseFFN implementation', 'AST localized class DenseFFN L35-53; personally read original L1-53 including nearby RMSNorm/rope context. width*4 hidden default, bias-bearing Linear pairs, GELU for this recorded config; no MoEFFN result comments read.'),
    repository('model', 'repository/model.py', 'Original ModelConfig, Block, TinyLM and loss_sum', 'AST localized constructors and loss; personally read L15-105. Block attention precedes FFN; FFN chosen by experts flag; model constructs two blocks for recorded config. loss_sum L92-100 uses reduction=sum, ignore_index and count of non-ignored target labels.'),
    repository('attention', 'repository/attention.py', 'Original attention parameter constructor', 'AST localized CausalAttention.__init__; personally read L32-46 only: four bias-free projection matrices; used only for total parameter formula, no attention accuracy claim.'),
    repository('common', 'repository/common.py', 'Original token-weighted evaluation and chunking methods', 'AST localized functions; personally read text_examples L77-97, _nll L106-119 and evaluate_lm L243-304. Text chunks share preceding input only; next-token labels are counted once; _nll aggregates summed loss / non-ignored target count. evaluate_lm separately reports number of source records and qualitative samples.'),
    repository('architecture', 'repository/architecture-experiment-revision.py', 'Exact experiment-revision training and report methods', 'Retrieved using git show 48a4f3e912b483d70aee57c42c2aac226534a9a6:scripts/course_experiments/architecture.py, raw SHA 1ad0b0789318236d5e1a8fc1117cb65758bbd6e3ad62dc2d646a111ae1ea37a3 equals raw report /code_sha256. AST then precise reads: _description L47-48, dataset methods L72-94, _train L152-284, _heldout L287-288, _parameter_budget L331-346, run_moe computation L428-477. Excluded run_moe return L478-491 extra comparison/auxiliary/limitations commentary. Ordinary initialization_note, memory_note and fixed-seed docstring read as method/measurement scope, not empirical verdict.'),
    repository('result', 'moe-original-result.json', 'Unmodified original moe empirical report', 'Top keys/types inspected first, followed by named model, training, heldout, dataset and provenance JSON pointers listed in cpu-verification.json. Did not inspect /results/comparison, /results/auxiliary_note, /results/limitations or result-status explanation values. Complete original file retained; recomputed aggregates from raw nll_sum and effective_tokens.', 'Original moe report at experiment revision 48a4f3e912b483d70aee57c42c2aac226534a9a6; unmodified full-file SHA in cpu-verification.json'),
    {'id':'original-execution', 'kind':'execution', 'title':'Actual original-fence CPU execution', 'verified':True, 'artifact_id':'original-run'},
    {'id':'cpu-execution', 'kind':'execution', 'title':'Independent bounded CPU checks and original aggregate reaggregation', 'verified':True, 'artifact_id':'cpu-run'},
    {'id':'derivation', 'kind':'derivation', 'title':'Independent arithmetic, shape and parameter derivations', 'verified':True, 'details':'For one row [a,b], up gives [a,b,a+b], ReLU acts separately, down gives [relu(a)+relu(a+b),relu(b)+relu(a+b)]. For positive [1,2]/[2,1], outputs [4,5]/[5,4]. No-bias d=2,h=3 tables contain dh+hd=12 scalars independent of N rows; explicit scalar arithmetic uses 12 multiplies,7 adds,3 ReLU comparisons per row (no wall-clock claim). h=4 changes both matrix shapes and gives16 scalars. Biased d=64,h=256 FFN:64*256+256+256*64+64=33088 per layer. Total=264*64+128*64+2*(4*64*64+4*64+33088)+2*64+264*64=141568. Effective-target-token NLL:90288.34326171875/39256=2.2999883651344697 and97279.35034179688/41914=2.320927383256117; prose rounds to5 decimals.'},
])


def evidence(source, locator, supports):
    return {'source_id':source, 'locator':locator, 'supports':supports}


claims = [
    {'id':'dense-positionwise-and-sparse-contrast', 'kind':'concept', 'statement':'本章 Dense FFN 對每個 token 完整套用同一套權重；前後線性變換與中間非線性逐位置加工。增加輸入位置不複製 FFN 權重，但增加逐列運算；稀疏 MoE 則有多組獨立專家並可選少數計算。', 'location':'15.1 開場、Dense 定義、共享參數及 MoE 過渡段', 'scope':'FFN 的位置共享與稀疏 expert 結構；不主張所有 Dense 架構只有兩矩陣或都用 ReLU，不推論整個注意力成本或真實執行速度。', 'status':'verified', 'evidence':[evidence('transformer','section3.2.3 and3.3, p.5 eq.(2)','原文 says position-wise separately and identically, same transforms across positions, different parameters across layers; ReLU between two affine transforms.'), evidence('moe','section1.2 pp.2-3; section2 p.3 eq.(1)','Independent same-shaped FFN experts, per-position sparse expert choice; zero gate permits skipping unselected expert computation.'), evidence('model','Block.__init__/forward L32-50','實作把注意力與逐位置 FFN 分開；experts=0 使用 DenseFFN。')], 'artifact_ids':['transformer-original','moe-original','model-code']},
    {'id':'original-program-api-coverage', 'kind':'software', 'statement':'固定 tensor 的兩次 @ 與 torch.relu 執行示範 FFN；torch.cat(dim=0) 增加列，len 數第一軸，numel 數兩張表元素，tolist 顯示巢狀輸出；本程式沒有訓練或參數更新。', 'location':'15.1 唯一 Python fence 及緊接的 API 解說段', 'scope':'同組 API 的 coverage 是 tensor 建立、二維矩陣乘法、逐元素 ReLU、沿列串接、列/元素計數及顯示；矩陣是固定 tensor，不是已訓練專家。', 'status':'verified', 'evidence':[evidence('torch-ops','torch.tensor L9582-9635;matmul L7908-7990;cat L2531-2577;numel L8814-8834','固定 tensor creation、2-D乘法、dim串接與總元素契約。'), evidence('torch-methods','Tensor.numel L3622-3629;tolist L5445-5465','numel method 與巢狀 list 顯示契約。'), evidence('torch-length','Tensor.__len__ L1189-1203','len 返回第一軸長度。'), evidence('torch-relu','functional.relu L1766-1778','逐元素 ReLU dispatch至 torch.relu。'), evidence('original-execution','one original fence; stdout and environment retained','原碼實際 CPU 執行，無 optimizer、backward 或更新。')], 'artifact_ids':['original-fence','original-run','original-stdout','original-env','cpu-run'], 'verification':{'method':'executed','expected':'兩列輸出[[4,5],[5,4]]；串接後四列重複，token2/4、表元素12/12。負值/零變體以ReLU先截零，再乘down。','observed':'原始 stdout 完全相符；[-1,2]→[1,3]、[-2,-1]→[0,0]、[0,0]→[0,0]；只改第二列不改第一列輸出。','details':'原 fence原樣 helper執行exit0，另CPU標量計算與負值/零及逐列獨立性变體通过；PyTorch2.14.1+cpu/原官方commit精確相符。'}},
    {'id':'toy-arithmetic-and-work', 'kind':'numeric', 'statement':'2×3與3×2共12個無bias權重；[1,2]經[1,2,3]得到[4,5]，第二列得到[5,4]；重複三遍共六列仍12權重。增加中間寬度須改兩張表形狀。', 'location':'15.1 12權重算例、手算段及練習', 'scope':'固定N列、d=2,h=3無bias的矩陣算例；運算量是逐列標量算術，無速度量測或全模型FLOP估计。','status':'verified','evidence':[evidence('derivation','row formula; d*h+h*d; per-row multiplication/addition count','獨立逐項算式與軸/參數量解讀。'),evidence('cpu-execution','checks repetition, relu-and-row-independence, hidden-width-change','N=2/4/6結果、負值/零分支與h=4兩張表維度實查。')], 'artifact_ids':['cpu-code','cpu-run','cpu-stdout'], 'verification':{'method':'executed','expected':'N=2/4/6輸出分別重複1/2/3次且表元素都是12；h=4則up[2,4],down[4,2]共16。','observed':'全與標量獨立計算精確一致；每列12乘法、7加法、3次ReLU，N=2/4/6分別24/48/72乘法。','details':'PyTorchfloat32輸入是可精確表示的小整數；逐列独立输出比对及宽度变体不涉及训练。','tolerance':'本算例整數算術及shape/元素數精確相等；沒有依賴近似輸出。'}},
    {'id':'recorded-dense-capacity', 'kind':'numeric', 'statement':'選讀基準dense_active_top1寬度64、兩層、每層FFN中間256；含bias每層33,088參數，兩層FFN合計66,176，整模型141,568。', 'location':'15.1 選讀框首句', 'scope':'33,088是每層FFN，並非兩層合計；原實報指定config為GELU、vocab264、heads4、max_length128、untied，與12元素無bias的ReLU算例分開。', 'status':'verified', 'evidence':[evidence('result','/results/variants/dense_active_top1/model/config and /model/parameters','原始基準config及總參數原數。'),evidence('modern','DenseFFN L35-53','hidden default4*width，兩個default-bias=True的Linear。'),evidence('torch-linear','Linear class L53-140','weight[out,in]、bias[out]及保留前置軸的官方shape契約。'),evidence('model','ModelConfig,Block,TinyLM L15-89','embedding/position/blocks/final_norm/output結構與是否共享輸出權重。'),evidence('attention','CausalAttention.__init__ L32-46','四張64×64 bias-free projection。'),evidence('cpu-execution','check dense-parameter-count','僅初始化CPU模型並數參數，無訓練/前向/完整評測。')], 'artifact_ids':['cpu-run','modern-code','model-code','attention-code','torch-linear-original','raw-result'], 'verification':{'method':'executed','expected':'每層64*256+256+256*64+64=33088；兩層66176；總公式141568。','observed':'ffn_hidden=[256,256]；per_layer_ffn=[33088,33088]；model.parameters()合計141568，原始JSON相同。','details':'以實報config創建CPU模型，獨立總公式包括token/position embedding、四張attention projection、兩次LayerNorm、FFN、final_norm、untied output。','tolerance':'參數元素、整數公式與原始JSON精確相等。'}},
    {'id':'recorded-updates-and-heldout-nll', 'kind':'empirical', 'statement':'原Dense基準完成180次有效更新；51篇驗證及52篇測試的token平均NLL分別2.29999、2.32093。', 'location':'15.1 選讀框180更新、故事數與代價', 'scope':'只核對原GPU實報的記錄、量測方法、分母及四捨五入；未重訓或重新評測模型。51/52是故事record數，損失分母實為39256/41914有效next-token目標，非每篇故事平均；不據此宣稱泛化能力已驗收或MoE優於Dense。', 'status':'verified', 'evidence':[evidence('result','/results/variants/dense_active_top1/training/{steps,optimizer_updates,skipped_updates,effective_tokens};/heldout/{validation,test}/{nll,nll_sum,effective_tokens,examples,records};/results/dataset/{validation,test}','原測量180更新0skip、原NLL總和、有效目標token及record分母。'),evidence('architecture','historical _train L152-284,_heldout L287-288,_data_report L93-94,run_moe L428-477;raw SHA1ad0b078...','exact實驗版本optimizer update計数、180排程、留出評估、record计数；此腳本僅閱讀。'),evidence('common','text_examples L77-97,_nll L106-119,evaluate_lm L243-304','chunking target不重複；逐batch累加loss_sum及有效targets，分開记录records；不使用生成samples作NLL分母。'),evidence('model','loss_sum L92-100','cross_entropy(reduction=sum,ignore_index=IGNORE)和有效label計數。'),evidence('cpu-execution','checks recorded-training-updates and recorded-heldout-validation/test','執行原JSON指定pointer的再彙總与版本fingerprint比對，不執行训练/全模型評測。')], 'artifact_ids':['cpu-run','raw-result','architecture-code','common-code','model-code'], 'verification':{'method':'executed','expected':'successful updates180、skip0；90288.34326171875/39256及97279.35034179688/41914的五位小数是2.29999/2.32093；records51/52。','observed':'updates=steps=requested_steps=180，skip0，statuscompleted；重算NLL2.2999883651344697/2.320927383256117，records51/52相符。','details':'保留完整original JSON SHA并仅检查具名raw pointers。原实测GPU L4、PyTorch2.14.1+cu126、Python3.13.3、seed42；本次审查CPU/PyTorch2.14.1+cpu仅读取原记录、再算分母與初始化数参数。','denominators':{'validation_records':51,'test_records':52,'validation_chunks':334,'test_chunks':352,'validation_effective_target_tokens':39256,'test_effective_target_tokens':41914,'training_effective_tokens':337761,'optimizer_updates':180,'skipped_updates':0,'seed':42},'tolerance':'原聚合比值误差≤1e-12；正文5位小数四舍五入误差≤5e-6。'}},
]

report = {'schema_version':1,'review_stage':'technical','lesson_id':'15.1','source':freeze['source'],'source_sha256':freeze['source_sha256'],'verdict':'pass','reviewer_task':TASK,'reviewer_context':'fresh','figure_sha256':{},'intro_sha256':freeze['intro_sha256'],'intro_summary':freeze['intro_summary'],'intro_snapshot':PREFIX+'original-intro-15.md','frozen_input':{'whole_chapter_sha256':freeze['frozen_input_whole_chapter_sha256'],'snapshot':PREFIX+'frozen-chapter-15.md','meaning':'当次原始冻结输入；不冒充后续整章版本'},'artifacts':artifacts,'sources':sources,'claims':claims,'issues':[{'id':'historical-method-provenance','status':'resolved','resolution':'当前architecture.py SHA7d91f0bc...不同於實報記錄，未把当前实现當成原run證據；git-show取回revision48a4f3e...，完整SHA1ad0b0789318236d5e1a8fc1117cb65758bbd6e3ad62dc2d646a111ae1ea37a3與raw /code_sha256相等，並親讀必要原方法。教材无需修改。'}],'checks':{'factual_accuracy':{'status':'pass','details':'逐位置FFN共享、完整Dense及稀疏MoE过渡概念由原Transformer/MoE论文核对；原程序API组合实际CPU执行并核对准确commit官方契约。','claim_ids':['dense-positionwise-and-sparse-contrast','original-program-api-coverage']},'numeric_verification':{'status':'pass','details':'手算和短CPU变体确认12权重、2/4/6列输出与宽度轴；64→256→64 FFN33088每层、两层66176及整模型141568；原NLL以有效target token数再彙总，5位四舍五入一致。','claim_ids':['toy-arithmetic-and-work','recorded-dense-capacity','recorded-updates-and-heldout-nll']},'figure_consistency':{'status':'not_applicable','details':'亲读15.1和必要4.4均无图或截图引用；section helper提取SVG数0且figure_sha256={}。没有需要渲染的图；未做页面视觉/可读性验收，也未声称已做。','claim_ids':[]},'source_verification':{'status':'pass','details':'权威原文的arXiv v7/v1版本标记与相关段落本人亲读，官方PyTorch精确commit原文节点本人核对；原JSON pointer和exact experiment git源码SHA独立核验，locator索引只用于定位。','claim_ids':[c['id'] for c in claims]},'limitations':{'status':'pass','details':'12权重示范没有训练；工作量计数不等於实际速度；Dense定义限本章FFN。实报只一个seed、短排程的记录；NLL分母是有效target tokens而非故事数；本轮没有训练、GPU、完整模型评测、模型/数据下载、成品验收。','claim_ids':[c['id'] for c in claims]}},'actual_read_scope':{'markdown':'chapter15 original lines1-130 read: introduction, entire15.1, context15.2/15.3 and opening15.4 through its first fence opening; independently adjudicated15.1 only. Entire linked4.4 personally read. Full15.md raw bytes frozen but not claimed fully read.','implementation':'AST定位后必要节点精读范围见每个repository source的inspection_note；记录current architecture先读及其exact historical version重新亲读，ordinary docstring/初始化控制/measurement memory_note属于方法范围。','raw_measurements':'top-levelkey/type reconnaissance plus named pointers in cpu-verification.json; full original raw JSON retained without printing or searching all values. /artifacts key/type and dataset.json path locator also inspected, no artifact weights loaded.','external_primary':'原Transformer PDF首5页抽取中本人读标题/版本、导言和注意力/FFN相关段落；原MoE PDF首4页亲读。官方上游源码先AST定位再精读原节点。','independence':'本task为新的单节technical reviewer；未读取旧technical/reader报告正文、作者review或额外结果解读/修正摘要。普通方法scope不被误分类为污染。未spawn、改正文/图、commit或push。','unperformed':'没有需要查看的本节图；未网页渲染、未重新训练/载入权重/模型重评。原始数据语料和模型性能未重新复现，核對范围为原raw实测记录及方法支持。'},'unresolved_questions':[]}
dest = ROOT / 'docs/technical-reviews/15.1.json'
dest.write_text(json.dumps(report,ensure_ascii=False,indent=2,allow_nan=False)+'\n')
owned = json.loads(dest.read_bytes())
assert owned['reviewer_task'] == TASK and owned['source_sha256'] == freeze['source_sha256']
print(json.dumps({'verdict':owned['verdict'],'reviewer_task':owned['reviewer_task'],'source_sha256':owned['source_sha256'],'intro_sha256':owned['intro_sha256'],'report_sha256':digest(dest),'report':str(dest.relative_to(ROOT)),'artifacts':len(artifacts),'claims':len(claims)},ensure_ascii=False,indent=2))
