import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[4]
OUT = Path(__file__).resolve().parent
BASE = OUT.relative_to(ROOT).as_posix()
def digest(path): return hashlib.sha256(path.read_bytes()).hexdigest()
def local(name): return f'{BASE}/{name}'
environment = json.loads((OUT/'probe.environment.json').read_text())
env = {k:str(environment[k]) for k in ('python','python_executable','torch','tokenizers','device','cuda_build','cuda_available','cwd')}
artifacts=[]
artifact_ids={}
for index,path in enumerate(sorted(OUT.rglob('*'))):
 if not path.is_file() or path.name.startswith('checker') or path.name in ('manifest.json','report-write.stdout.json','report-write.stderr.txt'):
  continue
 relative=path.relative_to(OUT).as_posix()
 aid='a-'+str(index)
 artifact_ids[relative]=aid
 kind='source_snapshot'
 if path.suffix=='.py': kind='code'
 if relative=='inspection-notes.md': kind='derivation'
 entry={'id':aid,'kind':kind,'path':path.relative_to(ROOT).as_posix(),'sha256':digest(path),'description':f'親自核對／實際產生的永久證據：{relative}；用途見 inspection-notes.md 和 input-provenance.json。'}
 if relative in ('original-run/execution.json','probe.results.json','prepare.stdout.json','fetch.stdout.json'):
  entry['kind']='execution'
  entry['environment']=env
  if relative=='original-run/execution.json':
   entry['command']='.venv/bin/python docs/review-tools/section_facts.py course/chapters/06.md#6.8 --output /tmp/phase4-6_8-independent-original --execute --timeout 60'
   entry['result']='exit 0; one original fence executed; starts 0/3/6 each give three inputs and three labels; no model or parameter update.'
  elif relative=='probe.results.json':
   entry['command']=f'.venv/bin/python {BASE}/probe.py > {BASE}/probe.stdout.json 2> {BASE}/probe.stderr.txt'
   entry['result']='exit 0; original and two context=4 variants executed; expected AssertionError captured; unique targets, masks/PAD/BOS/EOS/tails, original inputs and schedule assertions all passed. No training/model scoring.'
  elif relative=='prepare.stdout.json':
   entry['command']=f'.venv/bin/python {BASE}/prepare_evidence.py > {BASE}/prepare.stdout.json 2> {BASE}/prepare.stderr.txt'
   entry['result']='exit 0; 25 original snapshots copied; four historical code hashes and six original input hashes matched result record.'
  else:
   entry['command']=f'.venv/bin/python {BASE}/fetch_sources.py > {BASE}/fetch.stdout.json 2> {BASE}/fetch.stderr.txt'
   entry['result']='exit 0; eight original authoritative sources fetched with TLS verification and saved HTTP/URL/SHA receipts.'
 artifacts.append(entry)
sources=[]
def external(sid,kind,file,title,version,authority,note):
 receipt=next(r for r in json.loads((OUT/'sources/acquisition.json').read_text()) if r['file']==file)
 sources.append({'id':sid,'kind':kind,'title':title,'verified':True,'url':receipt['url'],'version':version,'accessed_on':'2026-10-05','authority_reason':authority,'checked_original':True,'inspection_note':note,'artifact_id':artifact_ids['sources/'+file]})
external('hf-clm','official_docs','hf-causal-lm-v4.57.1.md','Hugging Face Transformers causal language modeling tutorial','v4.57.1','Maintainer-authored original documentation in the official transformers repository.','親讀 lines 137–198 的 tokenizer preprocess / group_texts / tail drop-or-pad；其 model內部shift不同於本課外部shift，只用來支持先tokenize再group及尾段契約。')
external('hf-context','official_docs','hf-perplexity-v4.57.1.md','Hugging Face Transformers finite context and sliding window likelihood','v4.57.1','Official original documentation of fixed-context causal language model evaluation.','親讀 lines 38–70 的有限前文與窗口及92–136的context-only -100；未採用此版本例碼的num_valid_tokens-batch_size作本課count，實際有效count在外部shift後親數。')
external('sk-group','official_docs','sklearn-group-split-1.7.2.rst','scikit-learn grouped cross-validation','1.7.2','Official maintainer documentation explaining dependent samples and group separation.','親讀 lines 628–660：domain-specific dependent groups must remain absent from paired validation/training; does not define a high-overlap percentage threshold.')
external('sk-leak','official_docs','sklearn-pitfalls-1.7.2.rst','scikit-learn common pitfalls: data leakage','1.7.2','Official scikit-learn source documentation.','親讀 lines 77–110：held-out data must not influence fitted transformations; split before preprocessing/fitting. Scope is leakage prevention, not proof all near duplicates are removed.')
external('python','official_docs','python-3.13-sequence.rst','CPython common sequence operations and range','CPython v3.13.5','Original language documentation in official CPython repository, matching installed Python.','親讀 lines 1056–1066 index i<=k<j and clamp to len; lines1394–1432 range defaults and exact list(range(10)) example.')
external('tolist','official_source','pytorch-tolist-v2.9.0.py','PyTorch Tensor.tolist original API docstring','v2.9.0 reference; installed runtime 2.14.1+cpu','Original API documentation source in official PyTorch repository.','親讀 lines 5513–5533 returns tensor as Python nested list; reference version is older than installed CPU runtime; same API behavior independently executed in original fence.')
external('bpe','official_source','hf-tokenizers-bpe-v0.22.1.rs','Hugging Face tokenizers original BPE implementation','v0.22.1 reference; installed tokenizers 0.23.2','Original maintained implementation in official Hugging Face tokenizers repository.','親讀 merge_word lines389–466, word_to_tokens/tokenize lines469–526：unit IDs merged before producing tokens. Fixed raw-byte and token budgets differ; no inference that all tokenizers/text must compress. Original saved JSON executed without training.')
external('gpt3','paper','gpt3-arxiv-v1.pdf','Brown et al., Language Models are Few-Shot Learners','arXiv:2005.14165v1, 2020','Original authors paper deposited on arXiv; direct original PDF, not a search summary.','親讀 Appendix B PDF p42 / text lines1971–1976 (page verified using form-feed count)：packed documents delimited by special end-of-text, without special masking. Supports deliberately marked exception, not universal ban on document packing.')
def repository(sid,name,version,note):
 path=OUT/name
 sources.append({'id':sid,'kind':'repository_code','title':name,'verified':True,'path':path.relative_to(ROOT).as_posix(),'sha256':digest(path),'version':version,'inspection_note':note})
repository('data','inputs/current/tiny_perceptron/data.py','review-time SHA; same historical data.py hash in original experiment','親讀 shifted46–51, pad_batch71–86, structural tokenizer11–28；shift only once, min two IDs, attention-valid and loss-ignore distinct.')
repository('hist-common','inputs/historical/scripts/course_experiments/common.py','a253d1262bf5f361f9ac4e19232ae752f0ecc7a3; recorded code hash matches','親讀 split_records50–70, text_examples77–97；whole family split, per-document BOS/content/EOS, stride=max_length shares input boundary without duplicate next-ID labels.')
repository('hist-text','inputs/historical/scripts/course_experiments/text.py','a253d1262bf5f361f9ac4e19232ae752f0ecc7a3; recorded code hash matches','親讀 _BPE, utf8prefix374–375, evaluation378–405, run_tokenizer409–520；split before UTF8 excerpt/tokenizer, <=256 byte, max_length384, same400*8 schedule. No training entrypoint executed.')
repository('hist-model','inputs/historical/tiny_perceptron/model.py','a253d1262bf5f361f9ac4e19232ae752f0ecc7a3; recorded code hash matches','親讀 TinyLM forward position bound, loss_sum/masked_loss；sequence length must fit configured maximum, labels=-100 excluded, count effective labels.')
repository('result','inputs/current/docs/course-experiments/results/tokenizer.json','original complete_run at a253d1262bf5f361f9ac4e19232ae752f0ecc7a3','親讀 JSON metadata, results.data, results.runs[*].training/raw exposure, result artifacts/code_sha256；原CUDA測量僅查本節預處理/窗口/曝光契約，不重新評測loss或載入checkpoint.')
sources += [
 {'id':'original-run','kind':'execution','title':'Original 6.8 Python fence executed on CPU','verified':True,'artifact_id':artifact_ids['original-run/execution.json']},
 {'id':'probe','kind':'execution','title':'Independent bounded variants and original-input audit','verified':True,'artifact_id':artifact_ids['probe.results.json']},
 {'id':'derive','kind':'derivation','title':'Adjacent-pair and boundary-count derivation','verified':True,'details':'N known IDs define max(N-1,0) adjacent pairs. Full explicit C-position X/Y needs C+1 known IDs. Starts0/3/6, C3 yield 3*3=9 labels1..9 each once; adjacent raw windows overlap at exactly1/4 ID, no shared next-ID targets. C4 at start6 gets4 raw IDs ->3 pairs. BOS+N content+EOS -> N+1 X/Y positions, EOS is one target; padding/context-only labels=-100 do not increase valid loss count.'},
]
def ev(s,loc,support): return {'source_id':s,'locator':loc,'supports':support}
def verification(expected,observed,details,tolerance=None,denominators=None):
 value={'method':'executed','expected':expected,'observed':observed,'details':details}
 if tolerance is not None:value['tolerance']=tolerance
 if denominators is not None:value['denominators']=denominators
 return value
probe_ids=[artifact_ids['probe.py'],artifact_ids['probe.results.json'],artifact_ids['probe.environment.json'],artifact_ids['probe.stdout.json']]
claims=[
 {'id':'c1','kind':'concept','statement':'Tokenization establishes the ID sequence before this training-window slicing; the window selects available context without changing ID meanings.','location':'6.8 opening and second paragraph, chapter06 lines268–270','scope':'This section slices already encoded IDs; it does not claim that slicing raw text before encoding is equivalent (covered in6.9). A window is this data-loader sample convention.','status':'verified','evidence':[ev('hf-clm','v4.57.1 lines137–186 preprocess_function then group_texts','Official workflow tokenizes before dividing resulting ID sequences into chunks.'),ev('hf-context','v4.57.1 lines38–70','Finite input windows restrict conditioning context.'),ev('hist-common','text_examples lines87–92','Actual course source encodes complete text/BOS/EOS before slicing fixed IDs.')],'artifact_ids':probe_ids},
 {'id':'c2','kind':'numeric','statement':'Plain explicit-shift examples with C inputs and C next-ID labels require C+1 known IDs; C3 starts0/3/6 yield three four-ID segments and nine unique targets.','location':'6.8 lines268–284','scope':'All labels in this plain example are counted, no padding or context-only masks. Does not assert that every masked sample has C effective loss targets. X[t] predicts original segment[t+1] with causal preceding input.','status':'verified','evidence':[ev('data','shifted lines46–51','Contract returns ids[:-1],ids[1:] exactly once.'),ev('python','v3.13.5 lines1056–1066 and1394–1432','Python range0..9 and excluded upper slice endpoint.'),ev('derive','N-1 adjacent-pair derivation','4-1=3 pairs per complete window.'),ev('probe','probe.results.json c3_windows and unique_adjacent_pairs','Actually confirmed all three arrays and9 unique targets.')],'artifact_ids':probe_ids,'verification':verification('Three windows; X andY length3; targets1..9 exactly once.','Exactly those arrays; unique_adjacent_pairs=9.','Counts positions along sequence axis, integer ID units; count denominator3 windows and9 adjacent events.','Exact integer/list equality.')},
 {'id':'c3','kind':'software','statement':'range(10), list slicing, shifted, tolist, and length assertions implement the displayed window demonstration; no model training is required.','location':'6.8 only Python fence and explanation, lines273–284; recipe note297','scope':'Original code is a CPU tensor/data demonstration. Referenced CUDA training recipe was inspected as a long-run contract, not executed.','status':'verified','evidence':[ev('python','v3.13.5 range/list slicing locators','range and clamp behavior match printed original arrays.'),ev('tolist','Tensor.tolist docstring lines5513–5533','Returns Python list for one-dimensional tensors.'),ev('data','shifted lines46–51','No fitting, optimizer or model is called.'),ev('original-run','original-run/execution.json, stdout.txt, environment.json','The actual original fence ran successfully in installed Python3.13.5/PyTorch2.14.1+cpu.')],'artifact_ids':[artifact_ids['original-run/execution.json'],artifact_ids['original-run/fence-1.py'],artifact_ids['original-run/stdout.txt'],artifact_ids['original-run/environment.json']],'verification':verification('exit0; all printed arrays match paragraph; each length3.','exit0; starts0/3/6 give exact displayed3 input/3 answer IDs.','Installed torch2.14.1+cpu, reference PyTorch docs2.9.0; direct execution confirms API. No model/gradient/parameter update.')},
 {'id':'c4','kind':'concept','statement':'同一文件取「這些高度重疊窗口」的說法，將本例邊界共用連到高度重疊片段的洩漏例。','location':'6.8 lines286: 不能先從同一文件取這些高度重疊窗口，再隨機分訓練與驗證','scope':'The source-group split recommendation is correct, but the original adjective/referent is not established by this boundary-only example. No arbitrary quantitative threshold for 高度 is assumed.','status':'unverified','evidence':[ev('sk-group','1.7.2 lines628–660','Dependent source-group separation is justified independently of any high-overlap adjective.'),ev('derive','c3 adjacent-window intersections and targets','Adjacent four-ID segments share one boundaryID only; labels1..9 occur once, not overlapping supervised targets.'),ev('probe','probe.results.json c3_windows,unique_adjacent_pairs and overlap_check','Separately executed genuinely overlapping [0,1,2,3]/[1,2,3,4] to show duplicate next-ID targets2,3 versus original zero duplicates.')],'artifact_ids':probe_ids+[artifact_ids['inspection-notes.md']]},
 {'id':'c5','kind':'concept','statement':'Split complete documents/families before taking windows; avoid implicitly predicting across unrelated document boundaries unless deliberately designed and marked.','location':'6.8 lines286–288','scope':'For unseen-source validation, grouping is domain-specific and near-duplicate handling still matters. Marked document packing is permitted; EOS delimiters need not imply attention masking.','status':'verified','evidence':[ev('sk-group','1.7.2 grouped-data/GroupKFold lines628–660','Held-out dependent groups cannot also be represented in training.'),ev('sk-leak','1.7.2 Data leakage lines77–110','Split before fitting transformations to preserve held-out separation.'),ev('gpt3','arXiv2005.14165v1 AppendixB PDFp42 lines1971–1976','Explicit end-of-text delimiters allow designed multi-document packing without special masking.'),ev('hist-common','split_records50–70 andtext_examples87–92','Original course preserves family split and independent per-document BOS/EOS windows.'),ev('probe','separate_documents_with_BOS_EOS','Seven next-ID targets in two docs, no EOS-to-next-BOS/cross-document pair.')],'artifact_ids':probe_ids},
 {'id':'c6','kind':'numeric','statement':'Changing context to4 with original starts fails only at start6 because four remaining IDs yield three pairs; starts[0,4] produce two five-ID segments with four pairs each.','location':'6.8 exercise line290 and tail paragraph288','scope':'The exercise does not claim the second start list covers all nine original transitions; target9 is outside these two complete windows. Tail windows with>=2 IDs have N-1 pairs; shifted rejects N<2. Drop/pad handling must be explicit, and PAD is not a true next-ID target.','status':'verified','evidence':[ev('python','sequence slicing note4 lines1060–1066','Upper bounds clamp to10, so ids[6:11] contains6..9.'),ev('data','shifted46–51 andpad_batch71–86','Tail shift returnsN-1 only ifN>=2; padding ignores loss labels.'),ev('hf-clm','group_texts lines170–173','Dropping or padding remainder is an explicit preprocessing choice.'),ev('hf-context','context-only discussion92–99','Extra context positions need not count as supervised loss targets.'),ev('probe','variants andtail_lengths/padding/overlap_check','Both requested modifications and bounded mask/tail examples ran.')],'artifact_ids':probe_ids+[artifact_ids['variant-context4_original_starts.py'],artifact_ids['variant-context4_starts0_4.py']],'verification':verification('C4 starts0/3/6:4,4,3; last assertion fails. Starts0/4:4,4 each, pass.','Exact arrays; captured AssertionError only last original start. Revised starts pass;8 events. Tail0/1 rejected.','Sequence axis position count; context-only example six attention positions but four effective loss labels; short padded batch has four true labels, not six.','Exact integer/list equality; expected exception type exact.')},
 {'id':'c7','kind':'empirical','statement':'The original comparison split complete documents first, used the same<=256 byte excerpts for both encoders, and max_length384 gave one window per excerpt with identical raw-text exposure.','location':'6.8 supplemental paragraph295','scope':'Audits original result/historical code and hash-matched inputs only; no retraining, model weights, or loss/BPB re-evaluation. Identical raw exposure does not match effective tokens, parameters, compute, or tokenizer performance.','status':'verified','evidence':[ev('hist-text','run_tokenizer409–520,_utf8_prefix374–375','Source split precedes excerpting/encoding; one shared sampling schedule and max_length384 are explicitly configured.'),ev('hist-common','text_examples87–92','BOS+content+EOS shift makes contentLength+1 input/target positions.'),ev('hist-model','TinyLM.forward position bound; loss_sum','384 is the model input-position ceiling and effective targets exclude-100.'),ev('result','results.data, runs[*].training/raw exposure, artifacts, code_sha256','Complete_run records153/19/20 originals,400 steps, original code/input fingerprints and664759 exposure.'),ev('probe','original_input_checks andoriginal_schedule','Hash-matched saved BPE/splits re-encoded on CPU; all192 excerpts fit one window and original schedule matches.')],'artifact_ids':probe_ids+[artifact_ids['prepare.stdout.json'],artifact_ids['input-provenance.json'],artifact_ids['inputs/original-experiment/tokenizer-bpe512.json'],artifact_ids['inputs/original-experiment/data/train.jsonl'],artifact_ids['inputs/original-experiment/data/validation.jsonl'],artifact_ids['inputs/original-experiment/data/test.jsonl']],'verification':verification('192 excerpts <=256 bytes, each encoder<=384 input positions; shared original exposure schedule.','153/19/20 family-disjoint records; maxbyte input257; maxBPE input198; each one window;3,200 draws and664759 bytes; schedule SHA matches.','Four historical code and six tokenizer/input hashes matched original. Plain-text EOS is one target/document, BOS first input; byte/bpe effective targets train32123/17663,validation3913/2131,test4213/2503. No checkpoint use.','Exact counts and SHA equality.',{'documents':192,'train_documents':153,'validation_documents':19,'test_documents':20,'training_steps':400,'documents_per_step':8,'document_draws':3200,'raw_utf8_byte_exposures':664759,'max_raw_bytes_per_excerpt':256,'model_max_input_positions':384})},
 {'id':'c8','kind':'concept','statement':'Holding a raw-byte excerpt budget fixed differs from holding a token window fixed; learned byte-level BPE merges can cover more raw text within the same token budget.','location':'6.8 lines288 and295','scope':'Conditional on tokenizer/text. Here original saved BPE has fewer ordinary tokens on same original inputs; no universal compression ratio, language-model quality, or compute saving is inferred.','status':'verified','evidence':[ev('bpe','merge_word389–466,word_to_tokens469–473,tokenize509–526','Learned merges combine initial units into token IDs, allowing variable raw byte spans.'),ev('hist-text','_BPE.encode; run_tokenizer same excerpts420,464','Original comparison fixes raw UTF8 fragments before using each tokenizer.'),ev('probe','original_input_checks','Same31970/3894/4193 raw bytes yield byte tokens samecounts and BPE17510/2112/2483; does not expand original excerpt to fill384.')],'artifact_ids':probe_ids},
]
issue={'id':'i1','status':'open','original_claim':'不能先從同一文件取這些高度重疊窗口，再隨機分訓練與驗證','location':'course/chapters/06.md#6.8 line286','evidence':'Original C3 raw windows each4ID; adjacent intersection1ID (1/4 of either raw window), zero common X positions andzero common Y targets. All nine next-ID events occur once. Group split is independently justified by dependent-source generalization, not by an undefined high-overlap threshold.','impact':'The demonstrative 這些 calls a boundary-only example highly overlapping, making readers conflate shared input boundary with duplicated supervised targets and the substantial overlapping-span leakage example in1.2. No numeric definition of 高度 was invented.','recommendation':'Use 同一來源的窗口 or clearly distinguish this single-boundary example from a separate highly overlapping-span example; retain document/family grouping guidance. Optionally explicitly state nine targets occur once.','resolution':'Unresolved; coordinator must make a local source correction and this same reviewer must actually re-read/recheck before pass.'}
section=(OUT/'original-run/section.md').read_bytes()
report={'schema_version':1,'review_stage':'technical','lesson_id':'6.8','source':'course/chapters/06.md#6.8','source_sha256':hashlib.sha256(section).hexdigest(),'verdict':'revise','reviewer_task':'/root/phase4_factual_coordinator/factual_6_8','reviewer_context':'fresh','author_tasks':[],'reviewed_on':'2026-10-05','review_scope':'親讀完整6.8、所連1.2/1.3/6.5/6.6與T.4、原source/歷史code/原結果JSON/六檔hash-matched inputs，八個原權威來源相關段落；未讀任何舊review結論。','chapter_intro':{'status':'not_applicable','reason':'6.8 is not chapter first section.'},'figure_sha256':{},'artifacts':artifacts,'sources':sources,'claims':claims,'issues':[issue],'checks':{
 'factual_accuracy':{'status':'revise','details':'Tokenization/window/shift/source split and deliberate document-boundary exception verified. c4 remains unresolved because original wording calls the boundary-only example 高度重疊; no invented threshold or concealed original claim.','claim_ids':['c1','c2','c4','c5','c6','c8']},
 'numeric_verification':{'status':'pass','details':'Original C3 pairs; both C4 variants; tail min2; valid/masked/PAD counts; all192<=256 raw bytes, max257 byte/198BPE input positions<384; original schedule3200 draws/664759 bytes audited, no training.','claim_ids':['c2','c6','c7']},
 'figure_consistency':{'status':'not_applicable','details':'Original extraction and whole section contain zero figures/image references; therefore no section SVG exists to render/view. Explicit ID arrays suffice to verify this section arithmetic. Linked6.5 figures not used as6.8 evidence.','claim_ids':[]},
 'source_verification':{'status':'pass','details':'Eight original authority files fetched; their relevant full passages were directly read and recorded with URL/version/locators/scope. Four historical code hashes and six input hashes match original record. c4 uncertainty retained openly, no borrowed review verdict.','claim_ids':['c1','c2','c3','c4','c5','c6','c7','c8']},
 'limitations':{'status':'pass','details':'Plain unmasked C+1 convention distinguished from padding/context-only targets and library-internal shift. Shared raw exposure audited, without matched compute/effective token/parameter claim or general tokenizer superiority. CPU only; no model weights/training/data preparation/download/paid work.','claim_ids':['c2','c3','c5','c6','c7','c8']},
}}
path=ROOT/'docs/technical-reviews/6.8.json'
path.write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n')
manifest={'reviewer_task':report['reviewer_task'],'source_sha256':report['source_sha256'],'artifacts':[{'path':a['path'],'sha256':a['sha256']} for a in artifacts]}
(OUT/'manifest.json').write_text(json.dumps(manifest,ensure_ascii=False,indent=2)+'\n')
print(json.dumps({'report':str(path.relative_to(ROOT)),'report_sha256':digest(path),'source_sha256':report['source_sha256'],'verdict':report['verdict'],'claim_count':len(claims),'artifact_count':len(artifacts),'unresolved_issue':'i1'},ensure_ascii=False,indent=2))
