import pathlib,json,hashlib,datetime
R=pathlib.Path('/workspace/work/tutorial-audit-20261008');M=json.loads((R/'manifest.json').read_text());INV={p['page_id']:p for p in M['inventory']['pages']};E=R/'technical-foundations-evidence';S=json.loads((E/'snippet-results.json').read_text());RUN={p['page_id']:p for p in S['pages']};P=[];MISSING=[]

def add(pid,quotes,judgment,methods,prerequisites=(),extra_checks=(),unverified=()):
 source=(R/'freeze/sources'/f'{pid}.md').read_text();qb=[]
 for q in quotes:
  if q not in source:
   MISSING.append((pid,q));continue
  qb.append({'quote':q,'source':f'freeze/sources/{pid}.md','line':source[:source.index(q)].count('\n')+1})
 checks=[]
 for name,mechanism,need in methods:
  checks.append({'focus':name,'mechanism_property':{'judgment':'已足夠於本頁承諾範圍','basis':mechanism},'need_use':{'judgment':'已足夠於本頁承諾範圍' if need!='導覽／參考，詳細機制合理待教' else '合理待教','basis':need}})
 if RUN[pid]['cells']:
  checks.append({'focus':'原位置 authored Python cells','status':'passed','cells':RUN[pid]['cells'],'evidence':'technical-foundations-evidence/snippet-results.json#/pages/'+str(S['pages'].index(RUN[pid])),'scope':'本頁各 Python cell 順序執行；frozen implementation imports；CPU；不含安裝、Notebook bootstrap 或 UI；不是長訓練驗收'})
 checks.extend(extra_checks)
 figs=list(INV[pid]['figures_sha256'])
 if pid=='2.5':figs.append('course/figures/window_training.svg')
 if figs:checks.append({'focus':'圖文技術對應','status':'inspected','figures':figs,'scope':'全部本頁列出的640px PNG已由view_image親看；後回合記錄判斷；逐圖內容見 working-log.md。未檢實際網站或360px版面。'})
 P.append({'page_id':pid,'source_sha256':INV[pid]['source_sha256'],'source_read':{'complete':True,'route':'full-page technical read, authored main text and details','line_count':source.count('\n')+1},'source_judgment':judgment,'quoted_basis':qb,'actual_prerequisites':list(prerequisites),'checks':checks,'unverified':list(unverified)+(['實際網站圖文位置、mobile/desktop閱讀路徑及折疊互動未驗'] if figs else []),'issues':[]})

add('index',['可以先當書讀：程式下方已有實際結果，不必先安裝工具或準備 GPU。','每節下方都有 Colab 入口與 Notebook 下載，想動手改程式時再開啟即可。'],'任務入口與書讀／動手分工清楚；本組小型程式確實可用CPU核算，未把網站入口或公開Colab可用性假裝已實測。',[('路線導覽','接字表、數字、短程式是預告而不是此頁已完成的模型訓練。','導覽／參考，詳細機制合理待教')],unverified=['目前公開網站搜尋、287小節索引、Colab連結與下載UI未操作'])
add('course',['它的價值是把機制看清楚；真正訓練時，再用許多例子反覆更新，並留下不參與更新的題目檢查能力。','這兩種v2模型已完成訓練、公開推論權重與固定最後測試，仍未通過全部原定能力判準。'],'導覽有任務、局部例與整合成品的證據分界。v2的from-zero、MoE/Dense、公開推論材料與未全面通過之預告可對到原始結果指定metadata，沒有將小算例當成功訓練。',[('局部機制與整合驗收','小數字例用于追蹤；多例更新與留出題用于實際能力。','先理解零件，才用第19章有限任務判成品；此頁沒有承諾推導各架構全部內部。'),('多模態入口與接頭','圖片/聲音轉特徵，接頭轉核心向量，文字核心生成是角色預告。','導覽／參考，詳細機制合理待教')],extra_checks=[{'focus':'成品主張對原始JSON','status':'raw_metadata_supported','evidence':'technical-foundations-evidence/v2-final-public-results-raw.json','selectors':['scope','data_scope','hf_repo','hf_revision','architectures.*.capacity.initialization','architectures.*.selected_source','architectures.*.safe_weights','architectures.*.final_test.{run_id,revision,evaluation_complete,count,protocol}','architectures.*.capability_acceptance_passed'],'finding':'both from scratch；both evaluation_complete=True,count3734；both acceptanceFalse；publicHF revision979cdfacc588ad0536f1c64fff96f264571cf054。只讀原始metadata，未開其中independent_review_path。'}],unverified=['未下載公開v2權重、核HF遠端當下可用性，未重新審第19章全部任務或訓練lineage；入口技術預告僅對原始metadata'])
add('first-steps',['平均跨過哪個軸，結果就不再保留那個軸。','Linear 儲存的權重形狀是 `[輸出數, 輸入數]`，與上例相反；轉置 `.T` 把列欄交換，才配得上輸入。','但呼叫 `backward()` 之後，w 還是 1，它只算出方向，沒有真的調旋鈕。'],'暖身所有數學與狀態示例一致：兩軸平均、矩陣與Linear轉置/偏移、log代價、梯度與更新分開。7個Python cells實跑通過，CPU依賴設定與Notebook bootstrap作靜態核對。',[('list/dictionary/function','索引0起、key查值、for縮排、assert與函式輸入輸出明確。','動物清單需要依位置與欄位取出，以及重複顯示。'),('tensor/axes/mean/reshape','2×3成績跨dim1留2，跨dim0留3；reshape不改數值並需相等總格數。','要保留每人或每次考試分組，軸區別直接改變問題的答案。'),('log loss與softmax/CE邊界','-ln.9/.5/.1=.105/.693/2.303；獨立兩題.25 ->1.386；CE接logits。','以正確答案可信程度衡量猜法，并可加總多題代價。'),('@/nn.Linear/bias','[2,3]@[3,2]結果[[40,1],[80,6]]；Linear複製轉置與bias後[[45,1],[85,6]]。','同時算兩店兩指標，保留店別；固定杯成本用偏移表示。'),('autograd與梯度下降','L=(w-3)^2,w1梯度-4，lr.1->w1.4,L2.56；求導不改w，更新后重算才改loss。','很多可調值不能每次人工試方向；附近敏感度提供小步方向，步長需重評。'),('Notebook/kernel/路徑狀態','前格名字保留，Restart Run All清狀態；相對路徑以cwd為起點；安裝選cpu與notebook group在pyproject存在。','改輸入要重跑依賴格；檔案不見先查起點和kernel，防止把所有错误當工具壞。')],extra_checks=[{'focus':'環境/開啟指令靜態核對','status':'static_supported','sources':['freeze/implementation/pyproject.toml','freeze/implementation/scripts/check_env.py','freeze/implementation/scripts/build_course.py:BOOTSTRAP'],'finding':'cpu extra/notebook group存在；check_env compute只在forward/backward成功后印OK；bootstrap回到repo根並sys.path加入。'}],unverified=['uv全新安裝、Git遠端下載、Windows PowerShell與ipykernel/JupyterUI未實測','Colab當下介面/CPU連線/網路下載未實測'])
add('chapter-01',['最後把猜出的字接回去，看看一個接字規則怎樣變成一段新文字。'],'導覽只承諾字/編號、問題/答案、可調表及接回新字，後續各節確有對應操作；不要求此頁先訓練。',[('猜字主線預告','依已給字替下一字候選打分，更新後反覆選字接回。','導覽／參考，詳細機制合理待教')])
add('1.1',['希望程式既能記錄這些字，又能在猜完後把結果寫回人能讀的文字，所以需要一張雙向對照表。','這個檢查證明記錄可還原，不表示程式懂了貓或狗。'],'Unicode排序字表、[3,2,1,4,1,2,3,0]與原句雙向一致；ID是索引，不冒稱語意或學習。',[('字表/編解碼','固定唯一字->整數并同表查回；repeated貓3/狗1，程序還原assert通過。','讓程式保存且把候選寫回人可讀字，需要雙向一致的约定。')],['first-steps'])
add('1.2',['**訓練資料**用來調整模型內的可調數字','專案的 `split_documents` 先移除完全一樣的文字，再打亂與分組。','所以通常先按完整來源分組，再在各組內切片；同一篇的改寫、同一段對話的版本也應一起分。'],'五筆去重成4、split_documents實跑2/1/1；訓練/驗證/測試用途與完全重复檢查的限制有區別。',[('訓練/驗證/測試分組','split_documents由完整字符串去重後seed打亂；4unique文件算2/1/1，源實作一致。','練過同句不能當新材料檢查；驗證選設定，測試留最後。'),('來源洩漏與去重界線','assert只查train/validation完全交集，不能自動檢近重疊；正文另教先source分組。','避免重疊窗口共享連續內容被當新題；共同字母/漢字本身允許。')],['first-steps'],unverified=['未執行全語料近重複偵測；此頁未宣稱已做到'])
add('1.3',['句號後沒有提供下一字，因此本例不把句號當問題。','若誤把 `y` 也寫成 `s[:-1]`，題目就變成「貓→貓、看→看、狗→狗」；長度仍正確，學的工作卻變了。'],'x去尾/y去頭對應三題下一字；圖和zip嚴格配對一致，長度檢查不被當語意對齊證明。',[('shift答案對齊','[貓,看,狗] ->[看,狗,。]；strict要求等長但不保證目標正确。','需要猜下一字而不是照抄當前字，最後位置沒有後字就不作題。')],['1.1','first-steps'])
add('1.4',['這張分配沒有收到前文。','計算分配與使用分配是兩步，這裡先完成第一步。'],'unigram3/5,.2,.2与改分母3/7一致；基準完全不看前文、機率和取最高/抽樣分開。',[('unigram分配','Counter計頻率，各count/總5；candidate分配總和1。','不讀前文仍可偏向常見字，作后續比較起點；沒有前后字條件能力宣稱。')],['1.1','1.2','first-steps'])
add('1.5',['本例字表有七種字，因此貓列的總數是七份起始支援加兩次觀察，共 9。','每列機率加總為 1，整張表卻不是總和為 1：它包含七道不同的「目前字」問題。'],'bigram列目前/欄下一字、count初始化1与貓->看兩次一致；normalize軸與廣播正确，.1平滑2.1/2.7一致。',[('條件行分配','依目前字選列，行sumdim1除，p看|貓=3/9其他1/9。','讀前一字就應利用貓后兩次看的關係；每列是一道不同條件問題。'),('加一平滑','先每候選支援1再加觀察，V7,N2 ->分母9，改.1->2.7。','少材料未見組合不意味不可能，保留正機率；示意未被當實測效果。')],['1.1','1.3','1.4','first-steps'])
add('1.6',['ID 對照固定，訓練時要改的是表格裡的分數。','查表之後並沒有做參數更新，這裡所有偏好都由我們指定。'],'Embedding(3,3)直接作候選logits表；新ID明示、輸入0/2查同表、V²與只看末字限制正确。',[('可調查表/手動初始化','weight[[0,2,0],[0,0,0],[0,0,0]]，output查0及2列；zero_/assign是設初值。','可按答案調分數而不是每次重新計數；固定ID保留编碼约定。')],['1.1','1.5','first-steps'])
add('1.7',['原分數有負數、總和不為 1，不能直接當機率。','softmax 只整理偏好，沒有讀正確答案。'],'exp正權重、正規化、shift不變与max穩定化正确；候選軸各題分配互不共享，所列兩組概率核算一致。',[('softmax與減最高','[1,2,-1] ->[.2595,.7054,.0351]；同常數加成公因子抵消。','保留分數次序又得到可抽選、sum1且無負数的比例；并不驗答案正确。')],['1.6','first-steps'])
add('1.8',['只算「第一名有沒有對」會把它們當一樣；訓練時我們希望第二份付出的代價較低，才能看出微調分數是否有幫助。','若交入機率，機率又被當成分數轉換一次，會算成另一個代價。'],'正確答案NLL與平均交叉熵范围表達精確；[0,2,0]看p.7870 loss.2395；改答案貓2.2395而分數不動。',[('NLL/交叉熵與介面','F.cross_entropy(logits,targetID)與手算-lnsoftmax一致；rawscores[1,3],target[1]。','同argmax仍可有不同答案信任度，微調要可見連續代價；分數與答案共同決定好壞。')],['1.6','1.7','first-steps'])
add('1.9',['它描述微小改變，不能保證跳很遠也變好。','程式只測敏感度，w 還沒有被更新。'],'一維平方距離與中心有限差分正确；符號/大小/附近范围分开，w5梯度4/w3梯度0手算一致。',[('導數/有限差分','(Lw+h-Lw-h)/(2h)在w1,h.001=-4，公式2(w-3)相符。','代價高不提供參數方向，用小變動推近敏感度，供后續小步規則。')],['1.8','first-steps'])
add('1.10',['每段的敏感度相乘，就是**鏈式法則**','現在 w 仍是 3：`backward()` 算出影響量，沒有把參數搬到新位置。'],'兩段w3->u6->L36與導數12×2=24一致；autograd记運算而非有限差分；detach/item仅顯示不動w。',[('鏈式法則','局部du/dw2，dL/du12相乘24；u3w变化后合54不是只旧梯度×1.5。','參數到loss隔多步仍需算影響；局部敏感度相乘连到原參數。'),('autograd/backward','requires_grad留下graph，backward往回按導數把24存grad。','大型參數不能逐格试左右；本頁仅核敏感度，更新另步。')],['1.7','1.8','1.9','first-steps'])
add('1.11',['它與參數形狀相同，每格敏感度都有自己的參數可對應。','總代價 6 本身沒有這些方向資訊，不能拿 6 當成每格共同的更新量。'],'偏導與半份權重都核正；总loss6梯度[-4,2]有各自對應，係数2时12/[-4,8]。',[('偏導與梯度表','固定其餘參數，平方距離2d再乘成本權重；w0-4/w1+2。','總代價不能指出兩參數各自方向，计算图沿各自影響路回算。')],['1.9','1.10'])
add('1.12',['舊的 `before` 儲存的是原來算出的 4，不會因為 w 改了就自動變 2.56。','平均訓練代價由 3.7733 降到 1.0568。'],'梯度下降真改w、新forward重算loss清楚；单次1->1.4与lr2->9反例正確；實測3.7733/1.0568對raw post-update fields，不宣称新句品質。',[('更新/no_grad/再前向','w -=.1grad在no_grad改leaf，after用新w算2.56，before保原4。','求梯度只給方向，需要實際小步與重新評分；lr太大可能失敗。'),('接字表多次更新證據','raw simple_models.runs.bigram200步,before_nll.train3.7732658->after_nll.train1.0567632，分母103有效目标。','仅支持同訓練题猜法改变；生成和保留材料另驗，不等同泛化。')],['1.6','1.9','1.11'],[{'focus':'正文實測数字','status':'raw_values_and_data_hash_verified','evidence':'technical-foundations-evidence/simple_models-raw.json','selectors':['results.data','results.runs.bigram.before_nll','results.runs.bigram.after_nll_same_post_update_time','results.runs.bigram.steps'],'version':'26f34ebb5d1e237611567697d2b3ea4d64669331; CPU/seed42/PyTorch2.14.1+cu126','denominator':'9docs,103character/boundary targets; 12 totaldocs split9/1/2','data_evidence':'technical-foundations-evidence/local-raw-artifact-checks.json'}],['原始長訓練不重跑；本地checkpoint hashes不同于raw artifact，故沒有冒稱原checkpoint重評測'])
add('1.13',['每次 `w.square()` 都重新做一份前向計算','w 一直是 2，所以變的是記錄方式。'],'重复backward累计桶4->8、None后4及w2一致；clone副本与每次重建graph明示，未當敏感度改变。',[('grad累積/清除/optimizer狀態','每次新derivative4加桶，None后不帶前值；zero_grad/step分工预告。','每轮若只想用當前题更新，先清旧grad；不清反覆求导不代表w已改。')],['1.10','1.12'])
add('1.14',['為了只觀察這個流程，我們手動指定四字機率表，沒有訓練。','它接出 `三角。`，合起來是「顏色=三角。」：三角是形狀，填錯欄位。'],'手工四字機率生成每次换current列、+12共13字、句號不停完全對应；實測greedy欄位錯誤與相同末字限制有原始樣本佐證。',[('生成/抽樣/current更新','torch.multinomial按目前列選一ID，item/append并令新ID為下一current；13字assert通過。','無真答案時重复分配/選字/接回；示意只展示循環，并由次數止。'),('一字模型欄位限制','raw bigram prompt顏色= generated三角。，相同末字=必選同一列。','下降trainloss不保证欄位内容合适；需要增加可见上下文才能區分。')],['1.5','1.6','1.7','1.12'],[{'focus':'實測生成样本','status':'raw_sample_supported','evidence':'technical-foundations-evidence/simple_models-raw.json#/results/runs/bigram/samples/0','criterion':'greedy argmax，prompt顏色=，boundaryID0结束，与手工采样/12步例明确不同'}],['未重放原checkpoint生成；本地checkpointhash不同，未當原artifact使用','跨PyTorch版本/裝置抽樣序列未驗，正文已有条件'])
add('1.15',['用任何正溫度都不改分數排序，所以本例 greedy 仍選貓。','更新參數才是訓練。'],'greedy/sampling/temperature分工正确；.5/1/2最高機率.980/.844/.629和新狗分數2的.867/.665/.506核算一致。',[('greedy與sampling','argmax取最高ID0；抽样容低概率出现，无權重改變。','相同模型可用兩种選字规则，需要分清推論與訓練。'),('temperature縮放','正T除分数後softmax改尖锐但不改排序，T0除法不可直接用。','改抽样多样性/集中度，与正确性不同；模型比較固定解碼條件。')],['1.7','1.14'])
add('chapter-02',['我們會分清「線索已經送進去」與「模型真的用好線索」。'],'從同末字=的歧义引出更多前文，導覽限定线索可見不等於已学會，與2.5實測結論一致。',[('更多上下文預告','每字embedding按位置拼接，再配方算候选。','導覽／參考，詳細機制合理待教')],['1.6','1.14'])
add('2.1',['另外存一排參數，才讓訓練能改「這個字提供哪些數字」，又不改編碼約定。','這裡只是說明數字如何影響預測，沒有用這個假設證明訓練已成功。'],'五列新ID映射明示、lookup[1,2,1]->[1,3,3]重复貓同向量；额外共有配方正确地連到候选分數而非假實測。',[('中間embedding','ID索引可调V×D参数表，再经输出配方；本例D3不同候选数5。','保持ID定位固定而让字提供的線索可调，供多个字共同預测。'),('共享候選配方','狗分數=2feature1+feature3，貓2/看0；貓feature1->1.5使分数3。','字表与後续配方可分别改变候选分數，梯度回傳實際使用列；仅机制示意。')],['1.1','1.6','1.10','1.12','first-steps'])
add('2.2',['數字沒有相加，順序沒有丟掉。','三字與五字長卡無法直接交給同一個固定輸入大小的配方。'],'拼接保留三位置及order，reshape(2,-1)到[2,6]正确，不互混batch；固定context成本约定明示。',[('按位置拼接/reshape','[B,C,D]->[B,C×D]保持每笔原顺序；反向词序得不同長卡。','讓多个字共同送後续配方且各位置乘數可不同，保留order；需要固定C才尺寸吻合。')],['2.1','first-steps'])
add('2.3',['Linear 只沿最後一個特徵軸計算。','方形表即使寫錯，也可能不報錯而算出另一套配方。'],'Linear存[2,3]配方、bias与10/2正確；手动@转置一致；位置独立与先拼接才能混前文界線清楚。',[('線性配方/transpose/bias','x[1,3]@W.T[3,2]+bias->10/2，改一權重增4。','拼接只是保存，需加权让多个格共同影响新特征；各笔仍分開。')],['2.2','first-steps'])
add('2.4',['單一加權公式 `y=k*x+b` 是一直線，無法同時透過這三點。','本節手動填配方，只展示「算得出什麼」。'],'相同两Linear对照无ReLU=0/加入=absx，展示非线性改变斜率；合法模型表示性不变成训练成功宣称。',[('兩套Linear合成','bWa權重0 ->三样本全0；一般加權/偏移仍合成仿射。','多接Linear不能完成独立目标离零多遠的三点规则。'),('ReLU非线性','先[x,-x]，负清0后sum ->2/0/2，多段不同斜率。','用可见转折补直线表示限制；保持同weights控制是哪個机制改变。')],['2.3','first-steps'])
add('2.5',['相同輸入只能得到相同候選分配','視窗變長時參數也增加，驗證只有一篇，這份結果不能證明所有任務三字最好。'],'手工颜色/形状答案假設明示，五字才可区分；MLP raw counts833/1345/1857和三组post-update NLL一致；公平比較與1验证篇限制已教。',[('可見窗口','近1是/近3物體是/近4色物體是同，两题近5始分红蓝，8字练习同理。','沒有关键颜色输入无法条件分辨两题；可见只是学会机会。'),('拼接成本','H×C×D weights，C增影响一侧，MLPtotal833->1345->1857。','多線索有成本，主張只用于固定其他部分的配方计数。'),('MLP非线性与实测比較','embedding+flatten+hidden+tanh+output 与 frozenContextMLP一致；200steps同9/1documents。','可见增多不保证留出好；三字后五字train更低valid更高，不能选成普遍最优。')],['1.12','1.14','2.1','2.2','2.3','2.4'],[{'focus':'三模型原始比較設定','status':'raw_values_and_data_hash_verified','evidence':'technical-foundations-evidence/simple_models-raw.json#/results/runs','selectors':['mlp1','mlp3','mlp5'],'denominator':'9 train docs103targets,1validationdoc11targets；after_nll_same_post_update_time字段；seed42,width16,200steps；参数随C变化','data_evidence':'technical-foundations-evidence/local-raw-artifact-checks.json','interpretation':'same cases/budget, different parameter count; descriptive observation not isolated causal evidence'}],['未重跑200steps；原權重實際重評測未做，局部資料與manifesthash已核'])
add('chapter-03',['分清「提出需求、匹配位置、取回內容」三個角色'],'固定视窗可用线索后引入内容读法，Q/K/V基本角色预告合理；不把不同读法当天然语意。',[('注意力阶段预告','先比例混合，后内容匹配，因果许可與多头。','導覽／參考，詳細機制合理待教')],['2.5'])
add('3.1',['比例較大也不直接代表帶回數值較大。','本例兩張都有參與。'],'非负sum1加权混合得[1.8,.4]及反读[.2,3.6]正确，沒有把大权重当贡献/理解或可无损还原。',[('加權平均讀取','weights@[sourcepositions,features]给一张同宽output；两卡各乘自己比例。','想多用第一卡时.9/.1改变读法并保特征宽度；不等于拼接保每卡。')],['2.2','2.3','first-steps'])
add('3.2',['候選位置沒有改，偏好已因需求改變；這就是用內容決定讀法。','它不是只量方向的相似度'],'q/key点积取正负matching再沿候选softmax；q换维导致第二候选最多，向量大小影响分数限定准确。',[('q/key/dot score/比例','q[1,0]dotKs->[1,0,-1] ->.665/.245/.090，q[0,1]使第二最多。','让比例随目前需求而改，source卡不动；手工机制不主张学习成功。')],['1.7','3.1','first-steps'])
add('3.3',['query 表示提出需求，key 表示提供匹配線索','查詢數與候選數不必相等，但兩邊的匹配特徵數要相同。'],'Q/K区别来自role与独立配方，非文法标签；矩形Q[2,2]K.T[2,3]给[2,3]正确，行问题/列candidate与自注意来源界線清楚。',[('獨立query/key投影','同源X可各经不同Linear，示意保留/交换[1,2]为不同表示；QK.T不改变角色。','一个位置要提出需求也要供他位匹配，两工作允许独立配方而不用绑同数；不主张同配方不能完成所有任务。'),('多query矩形score','每query一行，候选一欄，Dk相同才dot；查询和候选数量可不同。','一次给每问者自己的全candidate分数；softmax行内分配不能互抢比例。')],['2.3','3.1','3.2'])
add('3.4',['左比例乘左 V，右比例乘右 V','本節仍用未縮放的透明算例；完整縮放規則在下一節。'],'matching2维/values3维和source行顺序正确；[7.0416,14.0833,21.1249]数值一致；QKV来自sameX讲明但示意直接填不同query/candidate数，不混成已训练self-attention。',[('K/V角色与对应','K提供定位数，V实际带回内容，weights[1,2]@V[2,3]->output[1,3]。','书目和内容可不同宽，匹配定位后需取相应source内容；调V不调K所以比例不变。'),('QKV全路與來源','sameX独立三个Linear可训；例无实际projection，仅softmax(QK.T)V。','分开需求、匹配和带回，避免把matching向量宽度当output宽度；缩放合理待下一节。')],['2.3','3.1','3.2','3.3'])
add('3.5',['對 D 個獨立、平均為 0、變異數為 1 的格子，加總變異數為 D，標準差為 √D。','除以 √D 不保證分數永遠同樣大。'],'独立±1乘积条件明确，sumvarianceD/sqrtD推導正确；1000sample短检标准差接近2/8再缩1，非训练/普遍不變性證明。',[('点积缩放','Rademacher q/k products var1独立，sumstd√D；scores/√D控制dimension起伏。','只增特征数不希望无意使softmax大幅集中；减弱这种尺度变化，不能抵消q/k全部变化。')],['1.7','1.15','3.2','3.3','3.4'])
add('3.6',['位置 i 只准讀位置 j≤i','若只是把分數設成普通 0，softmax 仍會給它機會，不能排除。'],'tril True许可、-inf屏蔽、B/H/T/D轴与均匀前缀读回一致；未来卡+100前三output无变assert实跑通过。',[('因果mask与query/key坐标','allowed[1,1,4,4]行query列key，i读j<=i；遮后score=-inf使exp0。','完整训练材料已有答案但生成没有，挡未来避免拿答案猜答案；自身当前允许因目标是右邻。'),('未来扰动实际检查','均匀allowed各行1,1/2,1/3,1/4；改Vposition3只可影响query3。','不仅看三角图，要看未来改动是否改变过去out；与shift任务配对分别核。')],['1.3','1.7','3.4','3.5'])
add('3.7',['兩頭都讀整串允許的位置','K 的最後軸是特徵，不是讀取比例表的候選位置'],'各头完整前文/独立特征与输出拼接正确；指定手算不同於实际随机輸入，cache[1,2,4,4]和改4头[1,4,4,2]静态符合。',[('multi-head/QKV split','total8 split2×4，先[1,4,2,4]transpose[1,2,4,4]，每头四位置，各拼8经outLinear。','同位置可能需几种读法；自由度允许多个matching/内容配方，不预设语意或声称更准。'),('cache输出','保存K/V与out共同返回；K最后特征dim4而非候选数。','以后逐字重用旧K/V基本角色已给，本页仅shape检查，无需提前缓存完整算法。')],['2.2','2.3','3.3','3.4','3.5','3.6'])
add('chapter-04',['核對輸入、答案與求導，再談增加層數會改變什麼。'],'把position/attention/per-position transform/output路线组完整的任务预告合理；Dense是本章配置，不提前宣称语言能力。',[('整體Transformer预告','重复同宽block并候选打分，后核任务到gradient。','導覽／參考，詳細機制合理待教')],['2.1','3.7'])
add('4.1',['同一個字放不同位置','加入位置使線索可用，後面的計算還要學會使用它，不代表相加後已懂語序。'],'absolute learnable position table三格逐加與same字不同向量正确；capacity5只索引0..4、causal约定与position用途有別。',[('位置表与逐格加','e(ID)+p(index)同宽，貓position0[1,0,0]/2[1.2,.4,.6]不同。','ID仅字同就同起始向量，额外position数字让位置可见；没有已用好语序或超长度泛化宣称。')],['2.1','3.6'])
add('4.2',['不讓原表示必須整份透過新分支','它不保證訓練永不失敗，也不表示所有原文能完整還原'],'residualx+f(x)same-shape、direct与branch同源、各路derivative相加机制准确；sum只测试敏感度未当文字loss。',[('殘差直接路','x[1,2]+2x ->[3,6]；sum反传each3，zero分支仍信息x、gradient1。','在已有表示加修正同时留直通信息/梯度，来源中让不全靠新branch的需要明确。')],['1.10','1.11','3.4'])
add('4.3',['不是沿兩個位置一起算','LN 是先整理再可調，最終不必永遠零平均。'],'LN最后轴population variance/epsilon/gamma/beta正確，整体平移allclose/单格修改差异对位；跨位置误标准化会泄漏的界线有效。',[('per-position LN','每position自mean/var，[1,2,3]与10倍各近[-1.225,0,1.225]，samepos全部+100近不变。','后续配方前抑制任意尺度；各位置独立才能保因果前文边界。'),('epsilon与affine params','sqrt(v+eps)防零除；每feature共享gamma,beta，设2/1后mean1var近4。','相同格输入需数值可算，保留后续可调尺度而不是永久mean0假保证。')],['3.5','3.6','first-steps'])
add('4.4',['擴張的是特徵，不是文字位置；縮回則讓結果能加到四格的殘差主路。','共享配方不等於位置互相讀取'],'DenseFFN4->16->4和GELU匹配frozen implementation；per-position相同输入给同输出，Dense完整配方与跨位置attention分工不混。',[('FFN扩张/GELU/缩回','up[16,4],down[4,16]，非线性夹中间，最后返回same4features。','attention读回后需卡内特征组合；扩张给中间表示再收回同宽可残差，16是当前示例设置而非最优性论证。'),('Dense共享位置配方','相同two-position input用同weights给相同values；Linear/GELU无位置混合。','区别各卡内部加工和跨卡交流，Dense不用按字选一部分FFN。')],['2.3','2.4','3.7','4.2'])
add('4.5',['主路沒有被 LN 永久替換；LN 在分支中。','不是答案 loss 為 0'],'pre-norm两段x+AttentionLN/u+FFNLN与Block.forward一致；out与cache与aux各分清，auxDense0不是零答案代价。',[('pre-norm block/两残差','保主x/u，branchLN先整理再attention/FFN后相加；sameB/T/D。','沿前文残差保已有表示，同时分支处理尺度；希望可反复同宽接下一层。没有承诺证明胜过post-norm。'),('返回状态/auxiliary','y,cache,auxiliary三项，Denseaux初始化scalar0，不用答案。','代码检查连线/shape时不把aux0误当语言任务loss0或学习完成。')],['3.7','4.2','4.3','4.4'])
add('4.6',['續寫只先用最後那排選新 ID，再把它接回輸入重算','本次初始化的平均代價約 3.336。'],'LM head每position8->20候选、末LN与logits字典、next-target flatten顺序正确；初始化实跑3.335639匹配3.336，不代表训练。',[('输出层/hidden/logits轴','TinyLM最后LN+LinearbiasFalse；[1,3,20]每position20候选，argmax-1->[1,3]。','内部8features不是候选分数；需每候选自己的配方，并与attention head术语区分。'),('生成取最后与loss整题flatten','续写只拿最后候选行；三题CE把logits[1,3,20]->[3,20],targets[1,3]->[3]保持对应2/3/4。','生成增一字而训练可已知三答案一次评分；不把所有position预测一次串起。')],['1.7','1.8','1.14','4.1','4.5'])
add('4.7',['它不會再幫你 shift。','模型尚未學會這段序列'],'shifted与masked_loss接口唯一shift一致；完整序列任务、因果input范围与三题loss/gradient给定，代码没有step；原实测causal0对raw字段。',[('完整序列对齐/损失','[1,2,3,4]x前三/y后三；scores[1,3,5]flatten后sameposition target；masked_loss仅ignore+mean。','三道next-ID题可同时评分但不读未来；重shift/复制会改任务，必须先对题。'),('backward无update','loss.backward累参数grad，本页无step或手改。','核数据->模型->代价->梯度通路，不误称训练成功。'),('额外实测防偷看','text_foundation结果causal_max_difference0，probe最后13->14，比较前三以前四位置全部候选。','需要检查未来输入不改变过去logits，loss下降不能代答；与当前短cells不同层证据。')],['1.3','1.10','1.13','3.6','4.6'],[{'focus':'原始causal_max_difference','status':'raw_field_supported','evidence':'technical-foundations-evidence/text_foundation-raw.json#/results/causal_max_difference','version':'b52935d99f58b694cd932ac158c10c4d8d92d4c2; cuda/seed42/PyTorch2.14.1+cu126','scope':'仅引用的未来扰动最大差0.0；data9/1/2与training141568/600steps metadata核对；其他scaling/resume结果不审','implementation':'frozen scripts/course_experiments/text.py run_text_foundation probe；model.py/attention.py静态逻辑与小cells实跑','boundary':'原始runner SHA不同于currentfreeze；不宣称这个baseline重新产生原CUDA结果'}],['原始CUDA训练及历史runner完整重放未做；原artifact远端与整个训练datasetmanifest未重新下载'])
add('4.8',['總數為 `1360+深度×840`。','沒有另做同預算一層對照，不能用來證明兩層更好。'],'1/2/3层2200/3040/3880実数符合独立block840+shared入口出口1360，明细attention无bias/FFN有bias正确；额外raw141568配置计数成立而非效果比較。',[('depth/独立block','第2层读第1更新表示而非每次原x；各block840，入口出口1360共存一份。','更多层增新的组合与运算/存储，不保持对所有量同一倍率；本页仅结构计数。'),('参数计数与宽度成本','W8时QKV/out4×64=256，FFN512+40，LN32；W64trained42112+2×49728=141568。','数清多层代价，并限制更多参数非更准证明；需要真正同预算留出比较才评质量。')],['2.1','2.3','3.7','4.3','4.4','4.5','4.6'],[{'focus':'额外trained模型配置数字','status':'raw_and_static_count_verified','evidence':['technical-foundations-evidence/text_foundation-raw.json#/results/training/parameters','technical-foundations-evidence/simple-checkpoint-evaluation.json#/text_foundation_config_count'],'scope':'vocab264,width64,layers2,max_length128 static count141568；不重跑训练、不读scaling实验成果'}])
add('glossary',['編號與向量是兩個步驟，不能混為一談。','幾種「遮罩」也要分開：不讓模型看未來，與不把某些位置列入考題，是不同工作。','檔案變小不等於所有硬體上都變快'],'参考入口的ID/embedding、softmax/NLL、mask与loss位置、cache、参数容量与計算以及后训练来源/方法区分技术合理。后段诸方法只审本页角色预告，未假称所有链接章节/实例已审。',[('编碼与embedding参考','本地例狗0看1猫2，序列[2,1,0]；vector为查回数字，与主章ID不同但本页重新约定。','让查词者回具体例，而不是认为ID大小有语意。'),('概率/学习/保存参考','[2,1,0]softmax约.665/.245/.090；grad单独敏感度；checkpoint續训需更新状态/进度。','查loss先问哪些题/位置，避免当所有能力总分。'),('QKV/attention/masks参考','同源特征三配方匹配/混合；可看提示和不计loss的答案位置不同。','分开读谁与需答谁，图/词比喻不假装实际理解。'),('后段方法参考','cache重用KV，Flash减少中间储搬，量化storage，蒸馏老师信号；RLHF来源与PPO更新区分。','導覽／參考，詳細機制合理待教')],['1.1','1.7','1.8','1.9','2.1','3.3','3.4','3.6','4.2','4.3','4.4'],unverified=['各后段链接章节不属本technical-foundations范围，未逐一审其实现、正式效益或全部术语展开'])

assert not MISSING,MISSING
assert [x['page_id'] for x in P]==M['groups']['foundations']['pages']
assert sum(x['source_read']['complete'] for x in P)==43
report={
 'schema_version':1,'kind':'AI-assisted independent technical source diagnosis; not first-reader study or publication acceptance','reviewer':'/root/technical_foundations','role':'technical','group':'foundations','created_at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'baseline_commit':M['baseline_commit'],'criteria_sha256':M['criteria_sha256'],
 'independence':{'instruction_source':'independent-review-instructions.md','source_initial_judgments_sealed_before_cross_review':True,'other_reviewer_conclusions_read':False,'historical_review_conclusions_read':False,'forbidden_dirs_read':False,'not_first_reader':True,'metadata_disclosure':'Manifest包含角色名稱、project-context与pyproject有历史review路径但没有开其内容；v2原始JSON包含independent_review路径/hash字段，仅见metadata键，不读取任何相应review判断。'},
 'actual_prerequisites':{'assigned_route_fully_read':M['groups']['foundations']['pages'],'additional_authored_source_sections':[{'page_id':'training','sections':['T.3','T.4'],'purpose':'本文直接引用的实验配方与raw JSON定位；只读这些bounded sections，非学习者已懂先备'}],'criteria_read':['SKILL.md full in1–134/135–193 bounded reads','references/review-protocol.md full','references/calibration.md full','references/project-context.md full'],'implementation_actual_read':{'full':['pyproject.toml','tiny_perceptron/data.py','tiny_perceptron/simple.py','tiny_perceptron/attention.py','tiny_perceptron/model.py','scripts/train_simple.py','scripts/check_env.py'],'bounded':['tiny_perceptron/modern.py lines1–105 (needed DenseFFN)','scripts/course_experiments/text.py lines1–200 and255–316 (simple_models and causal probe)','scripts/prepare_data.py lines20–42 toy-text generator','scripts/course_experiments/common.py lines30–60 new_lm','scripts/build_course.py lines1–115 BOOTSTRAP']}},
 'pages':P,'issues':[],
 'unverified_questions':[
  {'id':'TF-U1','pages':['index','first-steps'],'severity':'unverified','quoted_basis':'每節下方都有 Colab 入口與 Notebook 下載，想動手改程式時再開啟即可。','already_taught':'打开/kernel状态/环境工具與CPU配置已说明，静态API与小cells核对。','minimum_missing_relation':'当下公开链接可用性及全新Colab/Windows/Jupyter/uv安装执行没有实际操作。','impact_now':'不能宣称全平台操作已验；不证成教材缺陷。','minimal_repair':'若以后验出具体入口错误才按该指令或连结修；当前仅保留未驗。','rewrite_scale':'paragraph','finding_time':'initial independent technical scope review','source_independence':'source-only initial, no prior reviewer conclusion'},
  {'id':'TF-U2','pages':['1.12','1.14','2.5','4.7'],'severity':'unverified','quoted_basis':'完整切分、重做命令與另兩篇最後檢查見 [T.3](../training.md#T.3)。','already_taught':'simple raw数字/样本和数据SHA已核；text rawcausal字段已核；代码短机制实跑。','minimum_missing_relation':'原始長訓練、同版本checkpoint 重新評測与original CUDA runner没有重放；本地四simple checkpoints SHA均不匹配原artifact，故跳过。','impact_now':'独立核算和原始纪录支持正文范围；不能宣稱复现历史训练/所有能力。','minimal_repair':'核实要重评测时取hash-matched历史artifact；无需因本地不同文件改正文。','rewrite_scale':'paragraph','finding_time':'initial hash guard before checkpoint load; own simple-checkpoint-evaluation.json preserves failure/skips','source_independence':'raw evidence only, no old reviewer notes'},
  {'id':'TF-U3','pages':['course'],'severity':'unverified','quoted_basis':'公開推論權重與固定最後測試','already_taught':'原始v2metadata给HFrevision、from-zero初始化、final-test完整3734和acceptanceFalse。','minimum_missing_relation':'本轮未下载远端权重、重新查看全训练lineage/全部评分源；只读入口相称预告。','impact_now':'不能把入口metadata核对称整合成品全验。','minimal_repair':'维持已限定预告；若开展整合证据复核再查指定模型/data；此scope无已证缺陷。','rewrite_scale':'paragraph','finding_time':'initial raw-v2 bounded selectors','source_independence':'source/raw metadata only'},
  {'id':'TF-U4','pages':[x['page_id'] for x in P if INV[x['page_id']]['figures_sha256']],'severity':'unverified','quoted_basis':'網站的說明、程式與結果放在同一個位置，可以直接閱讀。','already_taught':'16inline图与补充曲线原图SHA核，17unique640PNG亲看各对象/公式/颜色对应。','minimum_missing_relation':'未看实际网站整页mobile/desktop位置、折叠、滚动/放大路径；未看360PNG。','impact_now':'不宣称版面/真实阅读路径通过，也不从没看推出缺陷。','minimal_repair':'由视觉/衔接role按真实页核；若具体读不清再修图或位置。','rewrite_scale':'page','finding_time':'initial visual scope record after actual view_image','source_independence':'own visual record, no other reviewer conclusion'}
 ],
 'coverage':{'expected_pages':43,'full_source_pages_read':43,'full_source_coverage':1.0,'page_ids':[p['page_id'] for p in P],'page_quotes_validated':43,'method_mechanism_and_need_saved_separately':True,'code_bearing_pages':36,'python_cells_executed':44,'code_cell_error_pages':0,'not_claimed':'不是287全小节或全教材all-role合格，非逐段首读/真人学生测试。'},
 'visual_scope':{'inspected_unique_inline_figures':16,'inspected_supplemental_figures':1,'actual_view_method':'view_image640 renderedPNG; results recorded following turn','all_assigned_figures_inspected':True,'fingerprints_checked':True,'website_desktop_mobile_layout':'unverified','360_png_readability':'unverified','finding_log':'technical-foundations-evidence/working-log.md'},
 'execution_scope':{'python':S['python'],'torch':S['torch'],'device':'cpu','exact_authored_cells':44,'frozen_imports':True,'no_training_updates_except_authored_one_step_w_examples':True,'long_training_rerun':False,'notebook_bootstrap_and_cloud_ui':'unverified','raw_training_sources':[{'path':'docs/course-experiments/results/simple_models.json','frozen_at':M['baseline_commit'],'evidence_copy':'technical-foundations-evidence/simple_models-raw.json','scope':'full raw JSON read, numbers/config/samples and historical data/vocab hashes verified; no long training rerun; no mismatch checkpoint loaded'},{'path':'docs/course-experiments/results/text_foundation.json','frozen_at':M['baseline_commit'],'evidence_copy':'technical-foundations-evidence/text_foundation-raw.json','scope':'bounded selectors metadata/results.data/results.training excluding history/results.causal_max_difference; scaling/resume out of scope, not full raw read'},{'path':'docs/selftrained/results/v2-final-public-results.json','frozen_at':M['baseline_commit'],'evidence_copy':'technical-foundations-evidence/v2-final-public-results-raw.json','scope':'course preview metadata/from-zero/final-test acceptance only; not full raw read or full integration audit'}],'evidence_files':['technical-foundations-evidence/check_snippets.py','technical-foundations-evidence/snippet-results.json','technical-foundations-evidence/verify_raw_simple.py','technical-foundations-evidence/simple-checkpoint-evaluation.json','technical-foundations-evidence/local-raw-artifact-checks.json','technical-foundations-evidence/working-log.md'],'truncation_disclosure':'首次合并criteria输出和首次text/v2 raw大输出被工具截断；criteria全部bounded重读；text/v2只按所需selectorbounded重读，因此未计full raw read。全部43正文无截断读取。'},
 'diagnostic_summary':{'necessary_blocker':0,'necessary_burden':0,'optional':0,'unverified_scope_questions':4,'source_scope_conclusion':'43頁技術來源讀完，在此角色與相稱主張範圍沒有核實的必要技術/證據缺陷。主要方法的運算、介面與用途各有具體來源；它們的小機制例與實測邊界不可擴大為全角色教材通過。','rewrite_scale':'目前不支持因technical-foundations結果要求章級或排序改寫；沒有已證必要修補。未驗項先核實，若證實局部指令/圖文問題才另裁定paragraph/page。'}
}
for u in report['unverified_questions']:
 qpid={'TF-U1':'index','TF-U2':'2.5','TF-U3':'course','TF-U4':'course'}[u['id']]
 qs=(R/'freeze/sources'/f'{qpid}.md').read_text();assert u['quoted_basis'] in qs
 u['quoted_basis_source']={'page_id':qpid,'line':qs[:qs.index(u['quoted_basis'])].count('\n')+1}

# Verify every source fingerprint at final record time without reading any other report.
for p in P:
 actual=hashlib.sha256((R/'freeze/sources'/f"{p['page_id']}.md").read_bytes()).hexdigest();assert actual==p['source_sha256']
path=R/'reports/technical-foundations-initial.json';path.parent.mkdir(exist_ok=True);path.write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n')
print('wrote',path,'pages',len(P),'methods',sum(sum('mechanism_property' in c for c in p['checks']) for p in P),'bytes',path.stat().st_size)
