from pathlib import Path
import hashlib,json,subprocess
R=Path.cwd();A=R/'docs/technical-reviews/artifacts/p6-19.7'
h=lambda p:hashlib.sha256((R/p).read_bytes()).hexdigest()
rel=lambda p:str(p.relative_to(R))
version=subprocess.check_output(['git','rev-parse','HEAD'],text=True).strip()
env={'python':'3.13.5','torch':'2.14.1+cpu','device':'cpu','neural_generation':'not performed'}
cmd='/workspace/tiny-perceptron-vlm/.venv/bin/python docs/technical-reviews/artifacts/p6-19.7/verify.py > docs/technical-reviews/artifacts/p6-19.7/verification-output.txt 2>&1'
art=[]
def artifact(id,name,kind,description,**kwargs):
 p=A/name;art.append(dict(id=id,kind=kind,path=rel(p),sha256=h(rel(p)),description=description,**kwargs))
artifact('a_probe','verification-output.txt','execution','短CPU原fence、算例、邊界/違規小變化、原始CPU往返與token解碼、原始工具aggregate的真正執行結果。callback replay明記不是神經生成。',command=cmd,result='exit 0；原例416，合法25×16為400；边界與拒絕分支、原始兩次EOS/相同模型SHA/回填歷史、選例validation provenance、0/276<0.95均通過。',environment=env)
artifact('a_code','verify.py','code','本審閱者寫的有界核對程式；不訓練、不新作神經生成、不重跑test。')
artifact('a_section','inputs/19.7.md','source_snapshot','初次讀取19.7原始UTF-8 section，未正規化換行。')
artifact('a_frozen','inputs/course/chapters/19.md','source_snapshot','初次frozen整章輸入；只讀19.7及19.8標題附近，不把全章SHA當目前sectionSHA。')
artifact('a_session','review-session.json','source_snapshot','真實讀取範圍、keys-first與pointers、圖實render/view命令/環境及來源查證紀錄。')
artifact('a_provenance','input-provenance.json','source_snapshot','原檔/副本全檔SHA核對與當次Git版本。')
artifact('a_argv','raw/tool_call-1-argv.json','source_snapshot','原始CPU argv/cwd/公開歷史，原樣保存。')
artifact('a_stdout','raw/tool_call-1-stdout.txt','source_snapshot','原始CPU stdout，包含真正兩次generations及tool_trace；全檔SHA與原result記錄相符。')
artifact('a_result','raw/tool_call-1-result.json','source_snapshot','原始CPU execution result，保留全檔；只讀執行/provenance/原輸出具名pointers，不讀author scope評論。')
artifact('a_stderr','raw/tool_call-1-stderr.txt','source_snapshot','原始CPU stderr（空檔），SHA與原result記錄相符。')
artifact('a_tokenizer','raw/tokenizer.json','source_snapshot','原公開export tokenizer原樣副本；hash符合CPU stdout /model/files/tokenizer.json，實際解碼59/8個tokens。')
artifact('a_metrics','raw/moe-test-metrics.json','source_snapshot','原test metrics原樣副本；僅讀/thresholds/tool_roundtrip、/per_task_final_reply/tool_call、/split；不讀notes，不重新評測。')
artifact('a_selection','raw/selection-catalog.json','source_snapshot','原始展示選例catalog原樣保存，僅讀/examples/4的record/trace/provenance pointers；selection_note與limits未讀。')
artifact('a_validation','raw/validation-tool_call.jsonl','source_snapshot','選例的原validation output原行；全檔含終止newline SHA符合catalog /examples/4/source_line_sha256。只核對該例與CPU輸入的一致性。')
artifact('a_rfc','authority/rfc8259.txt','source_snapshot','亲取得RFC Editor原始RFC8259（December 2017），讀§1/3/4/12。')
artifact('a_api','authority/function-calling.html','source_snapshot','親取得OpenAI官方Function calling原頁，2026-10-06 live snapshot。')
artifact('a_api_text','authority/function-calling.txt','source_snapshot','從官方原HTML排除script/style後抽出原頁文字；核對Tool calling flow、Best practices、Strict mode。')
artifact('a_fetch','authority/fetch-log.json','source_snapshot','官方來源HTTPS fetch狀態、URL、字數與全檔SHA記錄。')
for width in (640,360):artifact('a_figure'+str(width),'figure-'+str(width)+'.png','figure_render',f'實際Inkscape 1.4輸出寬{width}px並view_image查看；JSON參數/416/兩次模型/下向箭頭一致，無文字裁切。')
for f in ('tools.py','inference.py','model.py','dataset.py','tokenizer.py'):
 artifact('a_source_'+f[:-3],'inputs/tiny_perceptron/selftrained/'+f,'source_snapshot','完整原碼快照；AST定位後只精讀必要函式，不用描述性結果字串作答案。')
for f in ('chat.py','prepare_text_tools.py','evaluate.py'):
 artifact('a_source_'+f[:-3],'inputs/scripts/selftrained/'+f,'source_snapshot','完整原碼快照；精讀CLI/示範建構/工具評分與aggregate函式定位。')
artifact('a_commandpage','inputs/docs/selftrained/v2-public-cpu-commands.md','source_snapshot','操作頁完整原樣副本；僅讀heading與tool_call CLI fence（line123），沒有執行下載recipe。')
artifact('a_input','inputs/docs/selftrained/examples/v2/tool_call.messages.json','source_snapshot','操作頁tool_call輸入JSON，實際與原CPU argv的4則公開歷史完全一致。')
sources=[]
def code(id,path,title,note):sources.append(dict(id=id,kind='repository_code',title=title,path=path,sha256=h(path),version=version,verified=True,inspection_note=note))
code('s_tools','tiny_perceptron/selftrained/tools.py','Bounded calculator and one-hop model/tool/model runtime','AST先定位；精讀lines1–170：schema/constants、_unique_object38–44、_validate_call47–54、parse57–69、execute76–89、serialize92–103、run_tool_loop122–170。')
code('s_infer','tiny_perceptron/selftrained/inference.py','Same-checkpoint public inference runtime','AST先定位；精讀_public_history139–173、InferenceAssistant215–328與內部generate277–313，確認self.model.generate、公開history、記錄generation IDs、EOS與兩次回填。')
code('s_model','tiny_perceptron/selftrained/model.py','Autoregressive neural generator','AST先定位；精讀LimitedAssistant.generate384–419：forward logits、argmax、EOS停止；末尾generate460–461轉呼叫；不是答案lookup。')
code('s_data','tiny_perceptron/selftrained/dataset.py','Public history record encoder','AST先定位；精讀RecordEncoder.encode174–220：role/content被編碼成完整prompt IDs，generation只追加assistant role，不附當題gold target。')
code('s_token','tiny_perceptron/selftrained/tokenizer.py','Character decoding and generation report','AST先定位；精讀decode43–55、load76–77、generation_report80–95；用符合manifest SHA的tokenizer實際核對原兩次IDs。')
code('s_demos','scripts/selftrained/prepare_text_tools.py','Tool demonstration and counterfactual replay construction','AST先定位；精讀style_history486–494與tool_records635–782：call/reply示範、test-only replacement、工具不可用/缺參數/超範圍規約；未重跑prepare或training。')
code('s_eval','scripts/selftrained/evaluate.py','Tool scoring and aggregate computation','AST先定位；精讀score_reply240–306、Generator383–492、summarize495–590；tool_parameters比較expected_call，tool_final比較真result，roundtrip是參數/執行/終答的合取，rate=sum(values)/len(values)。未重評test。')
code('s_cli','scripts/selftrained/chat.py','Public CPU inference CLI','AST先定位；精讀parser37–64/main67–110；--device/--tools傳給同一InferenceAssistant.reply。')
sources += [
 dict(id='s_rfc',kind='official_docs',title='RFC 8259: The JavaScript Object Notation (JSON) Data Interchange Format',url='https://www.rfc-editor.org/rfc/rfc8259.txt',version='RFC8259, December 2017; original snapshot SHA256 61a5378f4255c720beb2a4b4a63b29540147c140f36988bf086291989b4cd2d7',verified=True,checked_original=True,accessed_on='2026-10-06',authority_reason='RFC Editor發布的IETF標準原文，定义JSON資料格式。',inspection_note='親讀§1（原文lines147–167）、§3/4（296–345）、§12（625–640）。只支持JSON物件/值/唯一key與eval風險；四key與0–99是本repo额外契约。'),
 dict(id='s_api',kind='official_docs',title='OpenAI API: Function calling',url='https://developers.openai.com/api/docs/guides/function-calling',version='Live official guide accessed2026-10-06; HTML SHA256 0f4274f620f0eab01b8d568aafbb558eb7c70317a2a92750e871aed689043f96',verified=True,checked_original=True,accessed_on='2026-10-06',authority_reason='API提供者官方指南原頁，直接描述模型请求→应用执行→回传→模型回答。',inspection_note='親讀Tools/Tool calls/Tool outputs與The tool calling flow（text846–927）、Best practices2827–2845、Strict mode4463–4486。local runtime是自製協定，沒有聲稱實作OpenAI API或strict mode。'),
 dict(id='s_execution',kind='execution',title='Independent CPU arithmetic and raw-record verification',artifact_id='a_probe',verified=True),
 dict(id='s_calc',kind='derivation',title='Transparent arithmetic and legality counterexample',verified=True,details='26×16=(20+6)×16=320+96=416；25×16=400。25及16仍在[0,99]，合法parser/executor返回400；但原題參數是26及16，所以請求合法不蘊含原題參數正確。單一已選成功輸入不給未見輸入分母，不能推出未見算式/問法成功率。')]
def ev(s,l,t):return dict(source_id=s,locator=l,supports=t)
claims=[]
def claim(id,kind,statement,location,scope,evidence,ids,expected=None,observed=None,details=None,den=None):
 c=dict(id=id,kind=kind,statement=statement,location=location,status='verified',scope=scope,evidence=evidence,artifact_ids=ids)
 if kind!='concept':
  c['verification']=dict(method='executed',expected=expected,observed=observed,details=details)
  if kind=='numeric':c['verification']['tolerance']='整數精確相等；沒有四捨五入或浮點容忍差。'
  if kind=='empirical':c['verification']['denominators']=den
 claims.append(c)
claim('c1','concept','工具往返由模型提出含參數的請求、應用程式執行、回傳結果給模型生成最終答覆。','19.7開頭、第1表與圖', '工具呼叫的一般分工；本節採一hop自製JSON協定，不主張遵循OpenAI wire API。',[ev('s_api','The tool calling flow；原抽取text920–926','五步含接收模型呼叫、application-side execution、second request與final response。')],['a_api_text'])
claim('c2','concept','JSON以命名欄位序列化結構化資料，可以明確解析工具名與參數；JSON資料不需透過eval執行。','19.7 JSON段與執行器段','RFC支援資料格式/物件與eval風險；exact四keys、整數0–99與運算集合是本repo的更窄契約。',[ev('s_rfc','§1、§3/4、§12（lines147–167/296–345/625–640）','JSON名稱/值物件、數字與boolean分別是值類型，直接解析比eval型式安全。'),ev('s_tools','parse_tool_call57–69；execute76–89','本程式實用json.loads後限定欄位並直接整數運算。')],['a_rfc','a_source_tools'])
claim('c3','software','執行器只接受calculator的add/subtract/multiply與0–99整數參數，拒絕重複、額外或缺少keys以及bool/float，直接作加減乘。','19.7「只支援0–99」及「先檢查欄位」','0–99限制的是輸入operand；減法結果可為負數，乘法結果可到9801。未測所有任意JSON攻擊，只核對契約分支與列明小變化。',[ev('s_tools','constants12–15、_unique_object38–44、validate47–54、parse57–69、execute76–89','精確的呼叫契約與計算。'),ev('s_execution','VALID_VARIANT/INVALID_VARIANT','四個合法邊界/變化及十個非法小變化的實跑。')],['a_probe','a_code','a_source_tools'], '26×16=416，25×16=400；0/99界可接受；越界/非整數/結構不符拒絕。','合法例均得預期值；十個非法例均ToolCallError。','逐parse/execute驗證；execute也重驗證CalculatorCall。')
claim('c4','numeric','26×16=416；若合法請求改為25×16則為400，偏離原題。','19.7算例、表、code fence與合法≠正確段','純確定性整數算術，無神經品質推論。',[ev('s_calc','26×16與25×16完整推導','416與400及原題operand差異。'),ev('s_execution','ORIGINAL_FENCE/HAND_CALCULATION/VALID_VARIANT different_legal_parameters','實際執行原fence與小變化。')],['a_probe','a_code'],'416與400精確相等。','416與400精確相等。','直接代入原parse/execute並核對(20+6)×16。')
claim('c5','empirical','已存公開MoE CPU例第一次實際生成指定multiply26/16 JSON，真工具result416，第二次生成「結果是416。」；兩段都正常EOS。','19.7開頭、表、EOS段與圖','一個挑選出的已知成功例；本審閱驗證既有原紀錄，不宣稱重新神經生成，也不外推未見題穩定性。',[ev('s_execution','ARCHIVED_GENERATION1/2與原stdout /generations/0/1、/tool_trace','逐token解碼、EOS/control檢查、模型SHA、executor結果與最後文本。'),ev('s_cli','parser37–64/main67–110','--device cpu與--tools走公開inference。')],['a_probe','a_argv','a_stdout','a_result','a_tokenizer'],'原argv為CPU/tool enabled，兩次同模型生成與真executor416。','returncode0；CPU argv與stdout哈希一致；architecture=moe；兩段59/8 tokens末尾EOS2；文字/416精確一致。','SHA釘選原revision979cdfacc588ad0536f1c64fff96f264571cf054、model26102d2edbd4574bef6733cba9e0dfd039118b206babdc66dbd16d1e57032d8c；tokenizer hash matches；未重新測神經模型。',{'selected_inputs':1,'neural_generations_in_original_record':2,'first_generated_tokens_including_EOS':59,'second_generated_tokens_including_EOS':8})
claim('c6','software','runtime用同一個generate callback呼叫兩次，第二次完整加入原assistant請求與真tool結果；不抽原題補算式，不代寫中文答案。','19.7「程式沒有先從問題抽出」及最后details','同一self.model與encoder；原histories讓416可被讀到，這不等於已藉干預證明神經回答依賴416。',[ev('s_tools','run_tool_loop122–170','initial=generate(prompt)；parse後execute；再generate(prompt+原assistant+tool)。'),ev('s_infer','generate277–313/reply315–328','同一self.model.generate產生tokens/raw_output並保存history。'),ev('s_model','LimitedAssistant.generate384–419','logits逐token生成與EOS停止。'),ev('s_data','RecordEncoder.encode174–220','給定完整公開history編碼；generation追加assistant role而無gold target。'),ev('s_execution','ARCHIVED_GENERATION2/CALLBACK_PROTOCOL_ONLY','精確對比第二prompt与兩次callback runtime replay。')],['a_probe','a_stdout','a_source_tools','a_source_inference','a_source_model','a_source_dataset'],'原第二prompt=原公開歷史+assistant raw JSON+tool serialized真416；同callback兩次。','精確列表相等；相同model SHA；callback replay兩次。','新callback是明記的非神經protocol replay，神經事實只由原raw紀錄支持。')
claim('c7','software','正文CPU code fence只解析手工raw字串並真正執行，輸出result416，沒有神經呼叫也沒有第二次模型回答。','19.7 code fence及其后段','手工parser/executor示範，不作神經生成或品質證據。',[ev('s_tools','parse57–69/execute76–89','兩helper僅JSON驗證與算術。'),ev('s_execution','ORIGINAL_FENCE與相鄰兩行輸出','執行從原section直接擷取的fence，不用自己重寫替代原例。')],['a_probe','a_code'],'合法請求字典與真執行字典result416。','合法請求與真執行字典result416，無模型call。','compile/exec原section唯一python fence，imports只有tools helpers。')
claim('c8','concept','請求可執行與參數符合原題應分開判定；合法calculator也會依錯的參數算出錯題答案。','19.7「合法也不一定正確」','反例是25×16仍合法但非26×16；只說明驗證層次，不宣稱executor可自行知道使用者意圖。',[ev('s_api','Tool calls/Tool call outputs與flow text863–906/920–926','model提出輸入、應用程式依輸入執行、model負責最後回答的分工。'),ev('s_calc','25×16反例','合法範圍與原題operand不一致。'),ev('s_eval','score_reply277–292','expected_call與valid/executed/final/roundtrip分開記分。')],['a_probe','a_api_text','a_source_evaluate'])
claim('c9','concept','該工具選擇是在明示system格式/範圍與工具示範規則下生成；一例不能被解讀為可靠的數學信心估計。','19.7第3段最後两句','核對prompt/示範機制及沒有confidence估測介面；未作training因果ablation或重新審training lineage，不推斷模型內在原因。',[ev('s_api','Best practices for defining functions text2827–2840','system說何時/何時不用工具、明確參數描述、示例與edge cases。'),ev('s_tools','TOOLS_SCHEMA16–21','0–99/operation/缺參數詢問及結果後回答規則。'),ev('s_demos','style_history486–494與tool_records635–674/696–782','工具call/reply、不可用與缺參數示範的資料方法。'),ev('s_infer','reply267–328','無信心測量或原題解析fallback；只有生成→工具→生成。')],['a_api_text','a_stdout','a_source_prepare_text_tools','a_source_inference'])
claim('c10','software','原方法允許test-only替換返回值檢查讀回依賴；正常roundtrip成功率依真executor結果記分。','19.7「另可在測試回放中替換返回值」','核對方法与串行表示能力，不宣稱此次神經模型的反事實依賴測試已達標。',[ev('s_demos','tool_records675–694','only split=test產生actual±1 counterfactual，用replay_kind隔離。'),ev('s_tools','serialize_tool_result92–103','允許表示範圍內整數結果供回放。'),ev('s_eval','score_reply277–292','tool_final根據trace真返回值，正常roundtrip合取參數、真執行与final。'),ev('s_execution','COUNTERFACTUAL_SERIALIZATION_ONLY','417成功序列化，清楚標成test-only替換，無神經因果結論。')],['a_probe','a_source_prepare_text_tools','a_source_evaluate'],'合法417可供回放，與真26×16結果416不同。','417序列化成功；正常真executor仍416。','只小範圍執行serialize helper；以原分支確認test-only隔離，未重跑資料製造或測試。')
claim('c11','software','工具未開或缺參數需說明條件或詢問；executor返回結構結果/明確錯誤而非代寫最終中文答案。','19.7工具往返要求及最後details','這是system/示範與runtime錯誤路徑的規約；不宣稱模型所有缺參數/不可用題均成功。',[ev('s_tools','TOOLS_SCHEMA16–21/run_tool_loop147–167','無效call返回invalid_call；未開返回unavailable；再次generate產生最後文字。'),ev('s_demos','tool_records696–782','不可用、缺參數、unsupported的預期目標規約。'),ev('s_execution','INVALID_VARIANT missing_parameter/CALLBACK_PROTOCOL_ONLY false','缺參數拒絕、未開不執行且第二callback讀到結構unavailable。')],['a_probe','a_source_tools','a_source_prepare_text_tools'],'缺a或b不可執行，未開工具不執行，錯誤由第二生成處理。','缺b為ToolCallError；disabled trace.executed=False/status=unavailable；仍有第二callback。','使用同runtime小變化，callback中文答案是明記非神經fixture。')
claim('c12','empirical','26×16展示例源自既有validation成功輸出，被挑選後以同一公開歷史在CPU往返；單例不能證明未見算式/問法穩定。','19.7最後正文段「挑選出的已知驗證成功例」','僅核對該一例的原始選例provenance與兩份raw的一致性；未重新審資料切分或選版，沒有讀catalog selection_note/limits。',[ev('s_execution','SELECTED_RAW_VALIDATION_PROVENANCE；catalog /examples/4/record/split/messages/supervision/expected_call/expected_result；原line /record/trace','split=validation，source raw line hash、公開歷史、multiply26/16與416/最後回答皆相符。'),ev('s_calc','單一選例沒有未見輸入分母的限制','只證明該流程可運作，沒有未見族群成功率的證據。')],['a_probe','a_selection','a_validation','a_argv'],'原split=validation，CPU公開歷史與原record去除assistant target完全一致。','split validation；record txt-066e89ca6cd19afb77919f12；原證據line hash ab275fec922d76851902935c3c1c2b73f256e875c2621f5b20073c4a553e23f1匹配；答案416相同。','先keys再named pointers；原catalog或score不替代自身算術與history比對。',{'selected_validation_records':1,'CPU_demonstration_records':1,'unseen_generalization_denominator':'not measured by this demonstration'})
claim('c13','empirical','既有MoE最後工具tool_call題未達tool_roundtrip驗收門檻。','19.7最后正文段指向19.12的失敗範圍聲明','只核對公開原test aggregate tool_call row與threshold，不重評全heldout、不重新做test推論；其他task/全章能力不在本節判定範圍。',[ev('s_eval','score_reply277–292/summarize495–534','tool_roundtrip判準與numerator/denominator/rate計算。'),ev('s_execution','ARCHIVED_AGGREGATE_ONLY；原metrics /per_task_final_reply/tool_call/tool_roundtrip 與 /thresholds/tool_roundtrip','0/276=0.0，低於0.95；合法114/276与正確參數0/276明確分開。')],['a_probe','a_metrics','a_source_evaluate'],'原tool_roundtrip rate與numerator/denominator一致且低於threshold。','0/276=0.0<0.95；tool_valid=tool_executed=114/276；parameters=0/276；final=110/276。','程式對具名tool row分母及rate重算；未查看其他能力raw樣本或重做evaluate。',{'tool_call_samples':276,'tool_call_source_groups':24,'tool_roundtrip_numerator':0,'threshold':0.95})
allids=[c['id'] for c in claims]
report=dict(schema_version=1,review_stage='technical',lesson_id='19.7',source='course/chapters/19.md#19.7',reviewer_task='/root/p6_fact_19_7',reviewer_context='fresh',source_sha256=h(rel(A/'inputs/19.7.md')),figure_sha256={'course/figures/p6-19-modal-tool.svg':h('course/figures/p6-19-modal-tool.svg')},verdict='pass',claims=claims,sources=sources,artifacts=art,issues=[],checks={
'factual_accuracy':dict(status='pass',details='逐核實一般工具流程、JSON與本repo窄契約、真正模型生成與手工parser示範的差異；沒有把合法等同正確或把prompt含416當作神經因果依賴實證。',claim_ids=allids),
'numeric_verification':dict(status='pass',details='原fence416与合法反例400精確；0/99界與−99结果核對；原兩次tokens59/8含EOS，test工具aggregate0/276與0.95門檻核對。',claim_ids=['c4','c5','c12','c13']),
'figure_consistency':dict(status='pass',details='Inkscape1.4實render640×963與360×542並view_image查看，用户26×16→JSONmultiply a26 b16→真416 tool→同核心第二結果是416，向下箭頭/模型SHA与原stdout吻合，无裁切。',claim_ids=['c1','c4','c5','c6']),
'source_verification':dict(status='pass',details='親下載並讀RFC8259原文§1/3/4/12、OpenAI官方Function calling flow/best practices/strict mode；本repo原碼先AST定位精讀；具名raw pointers/原樣副本与源SHA保存。未讀舊reader/technical或作者結果摘要。',claim_ids=allids),
'limitations':dict(status='pass',details='既有CPU選例只證明流程；手工fence/callback/417 serialization明確不是新神經生成/因果品質證據；輸入0–99不限制減法結果非負；原test只查工具aggregate，未重評heldout/training、未GPU/付費/上傳/改正文。',claim_ids=allids)})
(R/'docs/technical-reviews/19.7.json').write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n')
print('wrote own fresh report',len(claims),'claims',len(art),'artifacts')
