import json,hashlib,shutil
from pathlib import Path
base=Path(__file__).resolve().parents[1];sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest()
p=Path("docs/natural-assistant/v4/data/ocr-labels.jsonl");records=[json.loads(l) for l in p.read_text().splitlines()];idx,row=next((i,r) for i,r in enumerate(records,1) if r.get("synthetic"));line=p.read_bytes().splitlines(keepends=True)[idx-1];(base/"sources/nvidia-selected-label-original.jsonl").write_bytes(line)
annotation=Path("docs/natural-assistant/evidence/v4-research/ocr/nvidia/nvidia-zhhant-train000-page-00001.annotations.json");o=json.loads(annotation.read_text());pairs=[(i,r) for i,r in enumerate(o["line_bboxes"]) if r["text"]==row["text"]];assert len(pairs)==1 and row["answer"]==row["text"] and row["view"]=="crop";target=base/"sources/nvidia-page00001-original.annotations.json";shutil.copyfile(annotation,target);assert sha(annotation)==sha(target)
src=Path(row["image"]);dest=base/"sources/nvidia-selected-crop-original.png";shutil.copyfile(src,dest);assert sha(src)==row["image_sha256"]==sha(dest)
chat=Path("docs/natural-assistant/v4/data/chat-labels.jsonl");labels=[json.loads(l) for l in chat.read_text().splitlines()];oasst=[r for r in labels if r.get("source_tree_id")];up=Path("docs/natural-assistant/evidence/v4-research/chat-speech/oasst2-selected-original-messages.jsonl");originals=[json.loads(l) for l in up.read_text().splitlines()];byid={r["message_id"]:r for r in originals};families={};splitfamilies={}
for r in oasst:
 assert r["family"]=="oasst2-"+r["source_tree_id"];assert all(byid[i]["source_tree_id"]==r["source_tree_id"] and byid[i]["lang"]=="zh" for i in r["source_message_ids"]);assert r["family"] not in splitfamilies or splitfamilies[r["family"]]==r["split"];splitfamilies[r["family"]]=r["split"]
 families.setdefault(r["source_tree_id"],set()).add(r["family"])
assert all(len(s)==1 for s in families.values())
# Preserve the exact first original conversation records only, not arbitrary community-result summaries.
r=oasst[0];needed=set(r["source_message_ids"]);lines=[b for b in up.read_bytes().splitlines(keepends=True) if json.loads(b)["message_id"] in needed];(base/"sources/oasst-first-conversation-original.jsonl").write_bytes(b"".join(lines));raw=chat.read_bytes().splitlines(keepends=True)[0];(base/"sources/oasst-first-label-original.jsonl").write_bytes(raw)
print(json.dumps({"nvidia_label_line":idx,"nvidia_original_label_file_sha256":sha(p),"nvidia_original_annotation_pointer":"/line_bboxes/"+str(pairs[0][0])+"/text","nvidia_annotation_original_sha256":sha(annotation),"nvidia_annotation_permacopy_sha256":sha(target),"nvidia_crop_original_sha256":sha(src),"nvidia_crop_permacopy_sha256":sha(dest),"nvidia_answer_exact_source_text":True,"oasst_rows_checked":len(oasst),"oasst_tree_family_one_to_one":True,"oasst_source_ids_language_zh":True,"oasst_original_messages_file_sha256":sha(up),"oasst_raw_label_file_sha256":sha(chat),"scope":"NVIDIA one representative source-transcription crop checked; all64 OASST source tree/id/family fields checked, not all semantic answers or histories."},ensure_ascii=False,indent=2))
