import hashlib,json,re
from pathlib import Path
ROOT=Path.cwd(); BASE=ROOT/'docs/technical-reviews/artifacts/p6-19.8'; REL=BASE.relative_to(ROOT).as_posix()
def digest(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def artifact(i,kind,path,description,**extra):return {'id':i,'kind':kind,'path':path.relative_to(ROOT).as_posix(),'sha256':digest(path),'description':description,**extra}
raw=(ROOT/'course/chapters/19.md').read_bytes();start=re.search(rb'^## 19\.8 ',raw,re.M);nxt=re.search(rb'^## ',raw[start.end():],re.M);body=raw[start.start():start.end()+nxt.start()]
assert body==(BASE/'section-19.8.md').read_bytes(), '19.8 changed during review; reinspection required'
execution=json.loads((BASE/'verification-output.json').read_bytes()); env=execution['environment']
command='/workspace/tiny-perceptron-vlm/.venv/bin/python docs/technical-reviews/artifacts/p6-19.8/verify.py > docs/technical-reviews/artifacts/p6-19.8/verification-stdout.txt'
artifacts=[artifact('a_check','execution',BASE/'verification-output.json','本人實際CPU核對15段原始收據、資料包記帳、實際encoder/forward、weighted CE值與梯度；沒有optimizer step或留出題評分。',command=command,result='PASS: 15 completed run receipts, every predecessor best.pt SHA matches, all train/validation counts match original data; mask, state-load, forward CE and 2 weighted-CE/gradient assertions pass.',environment=env),artifact('a_stdout','execution',BASE/'verification-stdout.txt','同一實際執行的精簡stdout，結果PASS。',command=command,result='PASS; exit code 0.',environment=env),artifact('a_verify','code',BASE/'verify.py','本人的有界核對原碼，可重查每項assertion及原始資料pointers。'),artifact('a_section','source_snapshot',BASE/'section-19.8.md','最初讀取的19.8 UTF-8原始bytes；末尾換行未正規化。'),artifact('a_keys','source_snapshot',BASE/'receipt-top-keys.json','首次僅列45個原始收據和index的top-level keys/types，未用附加解釋判定。'),artifact('a_ast','source_snapshot',BASE/'ast-locators.json','首次AST定位相關原函式／類別；避免列印結果解釋字串。')]
sources=[]
papers=[('s_instruct','instructgpt-2203.02155v1','Training language models to follow instructions with human feedback','2203.02155v1','OpenAI作者的InstructGPT原論文，直接定義demonstration SFT、human preference RM和PPO流程。','親讀引言，§3.1三步驟，§3.5 SFT/RL與Eq.2，Table 3／§3.6評價維度，§4.4 alignment tax，§6 discussion。下一token與user objective不同；SFT沿預訓練模型；RM是代理；訓練loss與任務成功不同。'),('s_ppo','ppo-1707.06347v2','Proximal Policy Optimization Algorithms','1707.06347v2','Schulman等作者提出PPO的原始論文。','親讀§1、§5 Eq.9-12與Algorithm 1；PPO alternates policy sampling and surrogate optimization，不等於人類回饋資料或必經後訓練階段。'),('s_dpo','dpo-2305.18290v3','Direct Preference Optimization: Your Language Model is Secretly a Reward Model','2305.18290v3','Rafailov等作者提出DPO的原始論文，本文第13章連結的同一v3。','親讀§3 SFT/RM/RL分工、§4 Eq.3-7與gradient/DPO outline、Appendix B loss pseudocode、§7限制；固定πref與offline preference pairs直接optimize πθ，省略獨立RM及RL取樣迴圈。'),('s_flash','flashattention-2205.14135v1','FlashAttention: Fast and Memory-Efficient Exact Attention with IO-Awareness','2205.14135v1','Dao等作者提出IO-aware exact attention的原始論文。','親讀Abstract、§1、§3.1 Algorithm 1／Theorem 1。存在改運算安排而保留理想attention函數的加速方法；未使用論文速度數字來宣稱本成品加速，也不將exact arithmetic理解為浮點逐bit相同。')]
for sid,name,title,version,authority,inspection in papers:
 for ext in ('pdf','txt'):
  artifacts.append(artifact('a_'+name+'_'+ext,'source_snapshot',BASE/(name+'.'+ext),'原始HTTPS PDF bytes。' if ext=='pdf' else '由該PDF以pdftotext -layout產生的定位文字；是原文轉錄，不是他人摘要。'))
 sources.append({'id':sid,'kind':'paper','title':title,'url':'https://arxiv.org/pdf/'+version,'version':'arXiv '+version,'verified':True,'checked_original':True,'accessed_on':'2026-10-06','authority_reason':authority,'inspection_note':inspection,'raw_bytes_path':f'{REL}/{name}.pdf','raw_bytes_sha256':digest(BASE/(name+'.pdf')),'snapshot_artifact_id':'a_'+name+'_pdf','extracted_text_sha256':digest(BASE/(name+'.txt'))})
code=[('s_train','scripts/selftrained/train.py','stage_records L84-103; set_trainable L284-296; weights/objective L299-347,380-451,519-628; main init/load L689-817; selection/update/receipt L850-1004; export L235-281。親讀實際分支，不採用metadata字串作研究概念權威。'),('s_dataset','tiny_perceptron/selftrained/dataset.py','train_tokenizer L84-91; RecordEncoder L108-116,174-235; perception_loss L244-271；監督位置、資料形状與stage各入口loss契約。'),('s_model','tiny_perceptron/selftrained/model.py','SelftrainedConfig L25-53; LM forward L153-185; LimitedAssistant init L295-302; embeddings L313-355; forward L357-382。未讀description結果解釋。'),('s_tokenizer','tiny_perceptron/selftrained/tokenizer.py','CharacterTokenizer L12-41，原字元字表與special roles。'),('s_finite','tiny_perceptron/posttraining.py','FiniteResponsePolicy／RewardModel／ValueModel L53-86；人工4features、4候選的模型契約。'),('s_runner','scripts/course_experiments/posttraining.py','AST定位後讀imports L1-36、run_posttraining L256-287的有限候選SFT起點；未讀或引用該程式的預寫結果評語。')]
for sid,name,inspection in code:
 p=BASE/'frozen-input'/name
 artifacts.append(artifact('a_'+sid,'code',p,'查核時保留的完整原實作bytes，定位與实际读到范围见来源。'))
 sources.append({'id':sid,'kind':'repository_code','title':name+' frozen implementation','path':p.relative_to(ROOT).as_posix(),'sha256':digest(p),'version':'frozen working tree at HEAD b3a6684a1af47f1086c1b9e56ed090ff6699220a, inspected 2026-10-06','verified':True,'inspection_note':inspection})
sources.append({'id':'s_exec','kind':'execution','title':'本人的15段收據與CPU有界檢查','verified':True,'artifact_id':'a_check'})
for run in ('moe-pretrain','moe-sft','moe-vision','moe-ocr','moe-audio','moe-joint','moe-weighted','moe-native'):
 for suffix,name in (('outer','receipt.json'),('execution','raw/execution.json'),('train','raw/train-receipt.json')):
  p=BASE/'raw'/run/name; orig=ROOT/'docs/selftrained/results/training-raw'/run/name
  assert digest(p)==digest(orig)
  artifacts.append(artifact('a_'+run.replace('-','_')+'_'+suffix,'source_snapshot',p,'原始'+run+' '+name+'完整副本，與原件SHA相同；只讀具名測量/規約/provenance pointers。'))
for p in sorted(BASE.glob('data-sample-*.jsonl')):
 artifacts.append(artifact('a_'+p.stem.replace('-','_'),'source_snapshot',p,'固定LFS tar之原始train record行bytes；parent member SHA和line定位見a_check/data_accounting/raw_samples。'))
for name in ('course/chapters/19.md','course/chapters/07.md','course/chapters/13.md','docs/selftrained/TRAINING.md','docs/review-tools/factual-reviewer-instructions.md','docs/technical-review-guide.md','scripts/check_technical_reviews.py'):
 p=BASE/'frozen-input'/name
 artifacts.append(artifact('a_input_'+name.replace('/','_').replace('.','_'),'source_snapshot',p,'當次frozen input；實際讀取範圍另列，不把整檔保存等同於全文閱讀。'))
def ev(s,locator,supports):return {'source_id':s,'locator':locator,'supports':supports}
def claim(i,kind,statement,location,evidence,scope,ids=None,verification=None):
 d={'id':i,'kind':kind,'statement':statement,'location':location,'status':'verified','evidence':evidence,'artifact_ids':ids or [],'scope':scope}
 if verification:d['verification']=verification
 return d
def executed(expected,observed,details,denom=None):
 d={'method':'executed','expected':expected,'observed':observed,'details':details}
 if denom:d['denominators']=denom
 return d
claims=[
claim('c1','concept','缺少條件或格式的理想示範時，補相應示範提供SFT學習訊號；已有相對選好材料時可考慮偏好方法。','19.8 L3',[ev('s_instruct','§3.1 Step 1-2','demonstrations與comparison labels是不同訊號。'),ev('s_dpo','§3 preference dataset／§4 DPO outline','同prompt、preferred/dispreferred的標籤可直接形成偏好訓練資料。')],'是App兩點場景中的條件性選法建議，沒有證明哪種方法最優；DPO原方法並不要求兩個回答均正確，也不要求SFT先達某正確率。'),
claim('c2','concept','自回歸文字預訓練的下一token目標與SFT以示範回應教指令作答有不同資料用途。','19.8 L5',[ev('s_instruct','引言 p2 L73-101／§3.1 Step 1','next-token webpage objective不同於follow user instructions，接預訓練GPT-3用理想示範微調。')],'限本段所說的大型自回歸語言模型常見分工；不是所有pretraining objective都必為下一token，不宣稱SFT只教禮貌或格式。'),
claim('c3','empirical','本輪預訓練使用固定有限文字資料，不能稱為已讀完整網路。','19.8 L5',[ev('s_exec','verification-output.json/data_accounting/counts/pretrain and receipt_checks[moe-pretrain,dense-pretrain]','親自從實體tar讀12個JSONL，經原stage_records核對有限train/validation計數。'),ev('s_train','L84-103 stage_records','pretrain只選train split之text/text_pretrain、排除模態及evaluation_only。')],'有限資料包的數量與流程證據；沒有重新pretrain，資料筆數不能證明廣泛知識。',['a_check','a_moe_pretrain_train','a_data_sample_text_pretrain'],executed('收據的pretrain資料筆數應等於固定資料包stage filter。','兩版均2060 train、280 validation；archive SHA0976073…7e78a與固定包一致。','直接原JSONL計帳，完整member SHA、原始train樣本行保留。',{'architectures':2,'train_records':2060,'validation_records':280,'steps_per_run':1000,'seed':20261006})),
claim('c4','software','SFT沿自己的前段權重接續，改監督位置，不清空前段學到的參數。','19.8 L5',[ev('s_train','L742-792 init checkpoint/model.load_state_dict/set_trainable','先載入own checkpoint，設trainable，重建optimizer；沒有重置model權重。'),ev('s_dataset','L174-220 encode','pretrain全部文字及role/eos有labels，SFT只assistant文字/eos，labels已shift。'),ev('s_exec','mask_and_continuation and receipt_checks[moe-sft,dense-sft]','實際forward與state-load、production predecessor SHA核對。')],'沿權重微調不等於所有舊能力永遠保留；只確認本實作初始化與mask。',['a_check','a_moe_sft_train'],executed('載入state後逐張量相同；SFT助理答案mask；前段best SHA一致。','exact_state_load=true；synthetic pretrain9與SFT4 target tokens；兩條production chain都匹配。','使用實際LimitedAssistant.load_state_dict、RecordEncoder和objective，無optimizer更新。')),
claim('c5','empirical','本輪已完成文字pretrain、SFT、vision/OCR/audio入口、joint及後續joint調整的自身接續主線。','19.8 L7',[ev('s_exec','receipt_checks[all 15 runs]','核對45個原始receipt/execution/train-receipt的完成、步數、origin、predecessor best SHA及原資料計数。'),ev('s_train','L84-103／L519-559／L742-817','各stage選資料、入口head objective與後段共享核心接續。')],'完成執行與階段承接，沒有把它判成能力驗收；Dense停weighted，MoE另有native。',['a_check','a_moe_native_train','a_moe_native_execution'],executed('兩architecture應各沿own chain完成requested steps，前段best.pt SHA和history應一致。','15/15完成，exit0，completed_requested_steps=true、interrupted=false；MoE8段，Dense7段。','外層收據比對raw檔SHA，execution job init比對前段best，stage_history比對實際承接。',{'moe_runs':8,'dense_runs':7,'seed':20261006,'steps_by_stage':'pretrain1000,sft8000,vision1200,ocr3000,audio1000,joint6000,weighted10000,MoE-native4000'})),
claim('c6','software','後段共同訓練調整既有工具與原生語音示範的CE比重，使相應答案位置相對得到更大更新權重。','19.8 L7',[ev('s_train','L380-451 weights／weighted_language_loss','特定tool row/numeric target/native voice row乘weights，除sum(weight)，忽略labels權重0。'),ev('s_exec','weighted_ce and receipt_checks[moe-weighted,moe-native]','實際weights矩陣、代價與gradient一致；production weights分別4/4/1和4/1/4。')],'加重目標的相對梯度訊號，不是保證成功率變好；native只限非augmented、非fixture的train voice_qa/topic_continuation。',['a_check','a_moe_weighted_train','a_moe_native_train'],executed('實際加權應匹配手列weight矩陣與独立weighted CE及梯度。','兩組weight、value、gradient assertions通過；忽略位置=0、augmented voice沒有native4加重。','實際labels和records，對float32 CE值rtol1e-6/atol1e-6、梯度rtol1e-5/atol1e-7，無optimizer step。')),
claim('c7','software','本成品後段仍使用既有示範targets，不是PPO或DPO，也沒有依序跑兩者。','19.8 L7、L17',[ev('s_train','L519-563 objective／L904-939 training loop','前段labels經forward得到CE、weighted CE與perception/router項，再backprop；無reward/advantage/relative-reference objective。'),ev('s_exec','mask_and_continuation/losses and weighted_ce','真實objective輸出與獨立CE相同；所有production stage/weights對應此流程。'),ev('s_dpo','§4 Eq.7','DPO需要chosen/rejected與πref的相對logratio，此pipeline沒有該訊號。'),ev('s_ppo','§5 Algorithm 1','PPO會由policy取樣並估advantage更新surrogate，此pipeline沒有該循環。')],'指這份15段production lineage；不以章13局部實驗、別的repo結果補入成品。',['a_check','a_moe_native_train'],executed('synthetic pretrain/SFT/joint應為CE，後段仍是demonstration weighted CE。','三stage finite loss與獨立cross_entropy一致，2種weighted CE值/梯度一致。','親讀objective與main分支、核對全部stage job，短CPU只做forward/gradient，不重新train。')),
claim('c8','software','公開MoE從validation loss選best checkpoint；全部更新完成不保證最後一步最佳。','19.8 L7',[ev('s_train','L611-628 validation_loss／L878-901 select_and_save／L235-281 export','驗證用未加權original objective，strict loss下降才改best；公開export讀best.pt。'),ev('s_exec','receipt_checks[moe-pretrain,moe-audio,moe-joint,moe-weighted]','完成1000/1000/6000/10000，但child載入selected step分別250/200/2000/3000。')],'teacher-forced驗證代價是選版標準，不是生成任務成功率；不是聲稱每階段最後一步都差。',['a_check','a_moe_native_train','a_moe_weighted_outer'],executed('best是validation選定，後段承接可早於requested終點。','四個MoE已完成階段有較早selected step且best SHA與child history一致；所有收據test_used_for_selection=false。','核對production history與best文件SHA、原export與validation分支；未重做validation。')),
claim('c9','concept','SFT以理想回答為監督，提高示範回答在相應前文下的機率。','19.8 table L13',[ev('s_instruct','§3.1 Step 1／§3.5 SFT','pretrained GPT-3在demonstration上supervised fine-tuning。'),ev('s_dpo','§3 SFT／§4 DPO outline末段argmax Ex,yw logπ(yw|x)','supervised likelihood tuning所用preferred completion形式。')],'描述最小化negative loglikelihood的目標與梯度方向，不保證每個訓練樣本在任何有限、多任務更新後均單調改善。'),
claim('c10','concept','DPO直接用同題preferred/dispreferred偏好對和固定參考模型，調整policy相對偏好。','19.8 table L14',[ev('s_dpo','§4 Eq.7／gradient／DPO outline','LDPO(πθ;πref)對θ最佳化；資料(x,yw,yl)，πref是給定分布，沒有獨立RM。')],'原始offline DPO；並不保證與任意PPO實作得相同模型，或偏好對能驗收所有任務。'),
claim('c11','concept','PPO等RL方法可從policy產生新回答、取得評分，再以策略訊號更新。','19.8 table L15',[ev('s_ppo','§5 Algorithm 1、Eq.9-12','policy rollout→advantage估計→surrogate優化的交替流程。'),ev('s_instruct','§3.1 Step3／§3.5 RL Eq.2','LLM以prompt產生response、RM scalar reward、KL及PPO fine-tuning。')],'PPO本身不指定人類回饋或RM；必須有可信reward。產生新回答仍不自動證明任務成功。'),
claim('c12','concept','評分和回饋必須檢查是否代表任務成功，不能只追代理分數。','19.8 table L15',[ev('s_instruct','§3.5 RL／§3.6 evaluation','KL用來減輕RM over-optimization；labeler preference可能與user intention不同，還獨立檢查truthfulness等。'),ev('s_dpo','§7 limitations','judge winrate會受prompt影響，reward over-optimization仍需研究。')],'任務定義和適用評分器之限制；本文沒有驗證任意新reward或給出最適評分公式。'),
claim('c13','concept','RLHF指人類回饋的訓練流程，PPO是策略更新方法，DPO是直接偏好最佳化的替代路線，不是四道必經工序。','19.8 L17',[ev('s_instruct','引言／§3.1／Figure2文字','SFT、RM、人類比較與PPO共同構成所用RLHF流程；RLHF不另作PPO前的一種objective。'),ev('s_ppo','§1／§5 Algorithm1','PPO是general policy optimization algorithm。'),ev('s_dpo','§3／§4 Eq.7／§7','DPO直接從偏好訓練、無RL loop，與reward+PPO為不同路線。')],'採原论文所述典型RLHF分工；不是把所有使用真人示範的SFT都一概叫強化學習，也不將DPO說成需要先跑PPO。'),
claim('c14','concept','比較改善兩點格式時應保持題目和內容正確性；主題答錯是另一能力差異，不能只叫風格。','19.8 L19',[ev('s_instruct','Table3／§4.1 Figure4旁文字','分別評correct instruction/task、explicit constraints、hallucination；格式限制與主題/內容能力可分開觀察。')],'是針對本例的比較設計，沒有聲稱此matched pair就是全預算因果實驗，也不禁止偏好資料同時改善內容。'),
claim('c15','concept','後訓練改善新行為可能伴隨既有能力退步，需檢查原任務。','19.8 L19',[ev('s_instruct','§4.4 alignment tax／§6 discussion','PPO在原NLP任務有regressions；混pretraining gradients可減輕但未完全消除。')],'原论文反例支持可能退步和需另評測，不外推每次更新必退步，亦不以本次CPU測試證明多模態能力。'),
claim('c16','concept','更多更新、較低訓練代價或較晚存檔都不能代替目標行為及原能力的比較。','19.8 L19',[ev('s_instruct','§3.5 SFT','validation loss過擬合與RM/human preference變好可同時出現，loss不是任務表現的同義詞。'),ev('s_dpo','§7 limitations','偏好/代理evaluation與OOD generalization仍須另查。')],'否定的是自動等同／保證，並不否定loss是訓練和選版可用指標。'),
claim('c17','software','第13章偏好小實驗的模型和訓練分支不屬於這份公開多模態production成品，不能補其能力表。','19.8 L21',[ev('s_finite','L53-86 FiniteResponsePolicy/Reward/Value','有限人工feature→四候選模型。'),ev('s_runner','L18-27 imports／L256-287','局部runner初始化FiniteResponsePolicy，獨立SFT更新。'),ev('s_train','L729-792','公開trainer初始化LimitedAssistant並只讀own production checkpoint。'),ev('s_exec','separate_models／receipt_checks','實際兩類forward輸出不同；15段own chain沒有chapter13來源。')],'只查 provenance與model契約，未重跑章13訓練或引用其勝敗數字；不能用局部機制示範當本成品能力證據。',['a_check'],executed('局部4候選政策與公開字元LM應為不同模型/流程。','FiniteResponsePolicy output[1,4]；LimitedAssistant輸出字元vocab；same_instance=false；15段own chain完整。','實際CPU短forward與production init來源核對，不做兩者品質比較。')),
claim('c18','concept','改運算安排可能提高效率，但交付時仍需核對相同輸入/歷史/答案語義。','19.8 L23',[ev('s_flash','Abstract／§3.1 Algorithm1／Theorem1','存在IO-aware運算重排：回傳理想O=softmax(QK^T)V，减少memory IO；exact computation與加速可以並存。')],'本節只是下一節導入，不含本成品速度數字或已驗收加速宣稱；論文GPU特定benchmark不能代替本成品CPU測量。理想實數函數相同不要求浮點bit完全相同。')]
report={'schema_version':1,'review_stage':'technical','lesson_id':'19.8','source':'course/chapters/19.md#19.8','reviewer_task':'/root/p6_fact_19_8','reviewer_context':'fresh','source_sha256':hashlib.sha256(body).hexdigest(),'figure_sha256':{},'verdict':'pass','claims':claims,'sources':sources,'artifacts':artifacts,'issues':[],
'checks':{'factual_accuracy':{'status':'pass','details':'18項主張按一般方法、成品實際目標/流程與適用範圍分開核對；原論文證明概念，原始收據/實碼與CPU短檢證明本成品流程。','claim_ids':[c['id'] for c in claims]},'numeric_verification':{'status':'pass','details':'本節無算例或能力數字；含完成訓練及有限資料事實。親核15段requested/completed steps、原始data counts、checkpoint SHA chain；未重訓/重新評測。','claim_ids':['c3','c5']},'figure_consistency':{'status':'not_applicable','details':'19.8沒有引用圖或SVG；必要前文的圖未作本節證據。','claim_ids':[]},'source_verification':{'status':'pass','details':'本人直接下载并讀4份指定版本原論文，保存原PDF與其raw SHA、原文定位；保存原碼與原始MoE收據副本；其餘原收據SHA在實際執行output中，未採用舊reader/technical判定或作者額外結果評語。','claim_ids':[c['id'] for c in claims]},'limitations':{'status':'pass','details':'分清pretraining common recipe與一般所有模型、SFT目標與效果、DPO/PPO替代關係、weighted CE與RLHF、execution complete與generation能力達標。格式示例不是DPO適用的必要條件。','claim_ids':[c['id'] for c in claims]}},
'inspection':{'read_scope':['course/chapters/19.md#19.8','course/chapters/07.md#7.17 (context text/fence; figure not inspected)','course/chapters/13.md#13.17 (context text/fence; empirical outcomes not used)','course/chapters/19.md#19.12 (only linked evaluation purpose/context, no review of its task counts)','docs/selftrained/TRAINING.md (current linked operational claims; not used as proof of past outcomes)','docs/review-tools/factual-reviewer-instructions.md','docs/technical-review-guide.md','scripts/check_technical_reviews.py',*[c[1] for c in code]],'receipt_pointer_policy':'First list top keys/types. For all15 runs read outer /status,/returncode,/files/*/(path,bytes,sha256); execution /status,/returncode,/stage,/command,/job/(steps,init_checkpoint,loss weights); train /stage,/architecture,/steps,/tokens,/target_tokens,/train_records,/validation_records,/test_used_for_selection,/seed,/selection,/completed_requested_steps,/interrupted,/tokenizer_sha256,/origin/kind,/stage_history/*/(stage,step,checkpoint_sha256,selection), weight scalars and objective metadata method rules. No notes/review/*scope_correction values used. Output generator ignores extra author interpretations.','original_data_inspection':'Read JSONL records from actual frozen tar; count train/validation using original stage_records; retain three original train lines and parent member SHA/line in a_check. No held-out answer scoring, no assets/model loading, no training.','initial_frozen_chapter':{'path':f'{REL}/frozen-input/course/chapters/19.md','sha256':digest(BASE/'frozen-input/course/chapters/19.md'),'meaning':'當次frozen整章bytes，僅記初始snapshot；正式source_sha256是19.8 rawbytes，非目前整章版本。'},'summary':'19.8正確區分缺少demonstration與偏好訊號、典型pretrain/SFT接續、PPO/DPO不同objective。實際成品走own pretrain→SFT→perception→joint/weighted/native demonstration訓練，並用未加權validation loss選版；本文沒有把執行完成或章13局部機制實驗誤稱能力達標。'},'reviewed_on':'2026-10-06'}
(ROOT/'docs/technical-reviews/19.8.json').write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
print(json.dumps({'claims':len(claims),'artifacts':len(artifacts),'source_sha256':report['source_sha256'],'verdict':report['verdict']},ensure_ascii=False))
