import hashlib,json
from pathlib import Path
base=Path('docs/technical-reviews/artifacts/natural-v4-factual/T.6')
p=json.loads((base/'probe-output.json').read_text());extra=json.loads((base/'supplement-output.json').read_text());env=p['environment']
def sha(path):return hashlib.sha256(Path(path).read_bytes()).hexdigest()
artifacts=[]
def artifact(id,kind,name,description,command=None,result=None):
 path=base/name;a=dict(id=id,kind=kind,path=str(path),sha256=sha(path),description=description)
 if kind=='execution':a.update(command=command,result=result,environment=env)
 artifacts.append(a)
artifact('probe','execution','probe-output.json','Own CPU behavior checks, source hashes and complete original-record arithmetic audit.','PYTHONPATH=. .venv/bin/python docs/technical-reviews/artifacts/natural-v4-factual/T.6/probe.py > docs/technical-reviews/artifacts/natural-v4-factual/T.6/probe-output.json 2> docs/technical-reviews/artifacts/natural-v4-factual/T.6/probe-stderr.txt','Exit 0. Counts/masks/audio headers/parameter arithmetic match; three public media outputs reproduced; bounded resume tensors exactly equal.')
artifact('supplement','execution','supplement-output.json','Independent per-step sample budgets, RGB/audio input behavior, actual OCR ablations and expected resume rejection receipts.','PYTHONPATH=. .venv/bin/python docs/technical-reviews/artifacts/natural-v4-factual/T.6/supplement.py > docs/technical-reviews/artifacts/natural-v4-factual/T.6/supplement-output.json 2> docs/technical-reviews/artifacts/natural-v4-factual/T.6/supplement-stderr.txt','Exit 0. Every original sampled target count reconstructed exactly; three-row ablations execute; all three invalid resumes rejected.')
artifact('runtime','execution','runtime-original-source-check.json','Official original source versus installed runtime source identity.','.venv/bin/python docs/technical-reviews/artifacts/natural-v4-factual/T.6/runtime_check.py > docs/technical-reviews/artifacts/natural-v4-factual/T.6/runtime-original-source-check.json','Exit 0. All three original-source files are byte-identical to installed runtime files.')
artifact('pretrain','execution','pretrain-output.json','One actual update per practice pretraining CLI to verify train mode,holdout denominator and save-format fields.','.venv/bin/python docs/technical-reviews/artifacts/natural-v4-factual/T.6/pretrain_check.py > docs/technical-reviews/artifacts/natural-v4-factual/T.6/pretrain-output.json 2> docs/technical-reviews/artifacts/natural-v4-factual/T.6/pretrain-stderr.txt','Exit 0. Both real CLI calls report train mode and two holdout examples; output saves encoder/classifier/report. One update is not a300-step quality rerun.')
for id,name,desc in [('analysis','analysis.md','Own substantive reasoning, figure inspection, provenance and limitations.'),('raw-section','source-original.md','Own original complete current raw section snapshot, preserved before verdict.'),('retrieval','authority-retrieval.json','Original authority URLs, retrieval SHA receipts and genuine 403 failures.'),('fallback','authority-fallback-retrieval.json','Original official API source retrieval URLs and exact SHA receipts.')]:artifact(id,'source_snapshot',name,desc)
for name in ['probe.py','supplement.py','retrieve_sources.py','fallback_sources.py','runtime_check.py','pretrain_check.py']:artifact('code-'+name,'code',name,'Own reproducible bounded verification code.')
for name in ['probe-attempt1.py','supplement-attempt1.py','supplement-attempt2.py']:artifact('failure-code-'+name,'code',name,'Preserved original reviewer probe code before correcting its genuine failure.')
for name in ['probe-attempt1-stderr.txt','supplement-attempt1-stderr.txt','supplement-attempt2-stderr.txt']:artifact('failure-'+name,'source_snapshot',name,'Preserved genuine reviewer-script failure; diagnosis and correction in analysis.md.')
for id,name,desc in [('fig-fsdd','fsdd-render.png','Personally viewed prerequisite FSDD SVG: speaker splits, scores, EOS, rightward 8-to-16 kHz arrow and unchanged duration.'),('fig-retention','retention-render.png','Personally viewed prerequisite retention SVG: all eight bars share 0–100% scale and match original counts.')]:artifact(id,'figure_render',name,desc)

receipts={x['id']:x for x in json.loads((base/'authority-retrieval.json').read_text())+json.loads((base/'authority-fallback-retrieval.json').read_text()) if 'retrieval_sha256' in x}
sources=[]
authority_specs=[
 ('llava','paper','Visual Instruction Tuning','arXiv 2304.08485v2','Authors original paper; projector/feature alignment and assistant-answer objective.','Personally read §§4.1–4.2, Eq. (1), Table 2, Eq. (3), Stage 1 and Stage 2. Linear projection matches embedding dimensions; frozen pretrained encoders/LLM still need supervised alignment; answer and stop tokens form the training objective. This does not establish toy-model success.'),
 ('torch-normalization-source','official_source','PyTorch LayerNorm original source','main snapshot retrieved 2026-10-04; byte-identical installed PyTorch 2.14.1+cpu source','PyTorch project owns the API and implementation.','Personally read normalization.py lines 105–171 and constructor/forward. Statistics run over normalized_shape, correction=0, epsilon inside square root, per-feature affine parameters. Runtime file SHA is identical to retrieved official original.'),
 ('torch-functional-source','official_source','PyTorch STFT original source','main snapshot retrieved 2026-10-04; byte-identical installed PyTorch 2.14.1+cpu source','PyTorch project owns STFT API and documented behavior.','Personally read functional.py stft signature, mathematical definition, centered reflect padding, normalized=False and frame-count rules (lines 507–652). Real centered 1600-sample waveform at hop 160 yields 11 frames. No peak/energy normalization is implied.'),
 ('soundfile-source','official_source','python-soundfile original read API','master source __version__ 0.14.0; byte-identical installed soundfile 0.14.0','Maintainer original API source for libsndfile-backed decoding.','Personally read source __version__, read() signature and dtype/channel return contract, lines 225–275. Mono returns one dimension; dtype float32 decodes integer PCM through libsndfile. A floating WAV read as integers is a different conversion.'),
 ('libsndfile','official_docs','libsndfile API','Page declares libsndfile 1.2.2','Library owner specifies PCM/FLOAT formats and integer-to-float decoding.','Personally read SF_FORMAT_PCM_16 and SF_FORMAT_FLOAT subtype tables, read/write conversion Note 1 and Note 2. PCM16 stores signed 16-bit samples, FLOAT stores 32-bit floating samples; integer files read as float normalize their representational range, distinct from gain/energy normalization.'),
 ('fsdd','official_source','Free Spoken Digit Dataset original README','commit 26eb9aaf76e81b692f806f9140c2d2777410d7a1','Dataset owner specifies sampling rate, organization and official splits.','Personally read description, Organization, Contributions and Usage. Audio is 8 kHz mono, filename encodes digit/speaker/index; official test indices are 0–4 and train 5–49. This project uses a separate 5/6 speaker holdout.'),
 ('fashion','official_source','Fashion-MNIST original README','master snapshot retrieved 2026-10-04','Original dataset owner specifies source images/classes and official train/test.','Personally read opening dataset specification and class labels. Images are 28×28 grayscale with ten labels; this project uses 50 upstream training images and its own 30/10/10 split, rather than the official test benchmark.')]
for id,kind,title,version,reason,note in authority_specs:
 r=receipts[id];sources.append(dict(id=id,kind=kind,title=title,url=r['url'],version=version,verified=True,checked_original=True,accessed_on='2026-10-04',authority_reason=reason,inspection_note=note,retrieval_sha256=r['retrieval_sha256']))
code_notes={
 'scripts/pretrain_encoders.py':'Personally read complete CLI. Synthetic tasks, shape labels, >500 Hz pitch labels, exact two held-out items, train-only optimizer stepping/checkpoint and actual JSON fields.',
 'scripts/train.py':'Read parser, modal_loss, training_metadata and complete modal initialization/freeze/resume/update/save branches. First+last CLI blocks, two projectors, data/hash/schedule checks, full checkpoint loading and total-step semantics.',
 'tiny_perceptron/training.py':'Read complete save_checkpoint/load_checkpoint/restore_checkpoint_rng and learning_rate. Native multimodal-v1 full state and tokenizer/task/modal configuration differ from weight-only snapshots.',
 'tiny_perceptron/multimodal.py':'Read complete module. Patch/image/log-mel processing, learned LayerNorm, expand-before-shift answer labels, absent modality gradients and deterministic generation.',
 'tiny_perceptron/modal_data.py':'Read complete modal_example: paths relative to JSONL, RGB resize/div255, 16 kHz mono/nonempty rejection without resampling, answer+EOS labels.',
 'scripts/evaluate.py':'Read full evaluate API, loss/generation/raw-ID matches, limits/skips, metric denominators and no-grad/model-mode restoration.',
 'scripts/infer_modal.py':'Read complete task-aware loader, real media/resample flag handling, fixed prompts and generation JSON fields.',
 'scripts/prepare_ocr.py':'Read complete fixed-font draw and seed-42 string-family split/generation, 240/30/30 records.',
 'scripts/evaluate_modal.py':'Read complete CLI. Same selected records/model/generation length; zero-image blank, cyclic deranged shuffled donors and original-target stripped-decoded exact_match.',
 'scripts/audio_utils.py':'Read complete validation and chunked radius-16 windowed-sinc resampler; no hidden extra gain/clipping, explicit real resampling flag.',
 'scripts/course_experiments/modalities.py':'Read _fit, _vision_records, _audio_records, _media, _sequence, _loss_fn, _evaluate, _modal, _freeze, run_encoders/projector/vqa/ocr/real_modal and fixed sinc conversion. Original-record source SHA matches current full file.',
 'scripts/course_experiments/common.py':'Read split_records and dependency/output handling used by fixed experiments; grouped record order and family split reproduced.',
 'scripts/prepare_data.py':'Read complete generator/family split and inspected SFT original generation. Reconstructed raw replay input SHA exactly matches original SFT manifest.',
 'scripts/course_experiments/text.py':'Read split serialization and run_sft input generation/initialization. Used original SFT manifest to verify exact replay reconstruction.'}
code_notes['scripts/course_experiments/run.py']='Personally read complete module and parser: default output root, per-experiment subdirectory, dependencies root default/output override, explicit CUDA failure rather than fallback and actual run timing/source provenance. No full experiment executed.'
for i,(path,note) in enumerate(code_notes.items(),1):sources.append(dict(id='repo-'+str(i),kind='repository_code',title=path,path=path,sha256=sha(path),version='current frozen assignment 25ca4bf5f8f8dc0a9e88aa6cd70caeb4c2f419e8; full-file SHA verified',verified=True,inspection_note=note))
repoid={s['path']:s['id'] for s in sources if s['kind']=='repository_code'}
for name in ['encoders','projector','vqa','real_modal','ocr','sft']:
 path=f'docs/course-experiments/results/{name}.json';raw=json.loads(Path(path).read_text());sources.append(dict(id='record-'+name,kind='repository_code',title='Original '+name+' GPU run record',path=path,sha256=sha(path),version='original run '+raw['revision']+'; PyTorch '+raw['torch_version'],verified=True,inspection_note='Personally audited original inputs/configuration and raw predictions/history applicable to T.6. My CPU scripts independently recompute denominators and arithmetic; no original GPU-training replication claim.'))
sources.append(dict(id='record-media',kind='repository_code',title='Original media CPU command/stdout record',path='docs/course-experiments/student-checks/media-and-raw-adapter-cli.json',sha256=sha('docs/course-experiments/student-checks/media-and-raw-adapter-cli.json'),version='Original checked_at record; directly executed its first three media commands again',verified=True,inspection_note='Inspected first three command arrays, input-selection fingerprints, raw stdout and outputs. Compared raw stdout hashes and personally reproduced 42/Ankle boot/8. Did not use status metadata as proof.'))
sources.append(dict(id='record-format',kind='repository_code',title='Original FSDD format/conversion receipt',path='docs/course-experiments/student-checks/fsdd-format-and-resampling.json',sha256=sha('docs/course-experiments/student-checks/fsdd-format-and-resampling.json'),version='Original CPU receipt checked2026-10-03; formal real_modal record SHA450ab9f82d9c3116b42ccbab7bd63f9f14c633259d14bf5ed88bbdb65dd4ac93',verified=True,inspection_note='Personally inspected original run metadata,function,environment and first raw conversion receipt. Own first-waveform conversion payload SHA matches that receipt. Original fresh-file full-SHA failure is retained in the original record; I do not claim own replication of its60 historical timestamp reconstructions.'))
sources.append(dict(id='own-calculation',kind='derivation',title='Independent counts and information-loss reasoning',verified=True,details='Answer budget sums len(UTF-8 answer bytes)+1 EOS after modality expansion; independent seed+step sampling matches each history. 14408+3830=18238; direct 18256 exceeds by18. 4591/8000=9182/16000=0.573875. Context ceil(12148/160)+100=176 and48*64=3072. PCM16 int/32768 equality verified. LN first-card variance is2/3 and normalized variance=(2/3)/(2/3+1e-5), not exactly1. A deterministic encoder/projector cannot distinguish two inputs mapped to identical features; training more cannot reconstruct a distinction removed by resize/encoding. Tiny holdouts only establish those observed cases.'))

claims=[]
def claim(id,kind,statement,location,refs,artifact_ids,scope,observed=None,expected=None,den=None):
 c=dict(id=id,kind=kind,statement=statement,location=location,status='verified',evidence=[dict(source_id=s,locator=loc,supports=support) for s,loc,support in refs],artifact_ids=artifact_ids,scope=scope)
 if kind!='concept':
  c['verification']=dict(method='executed',expected=expected or statement,observed=observed,details='Personally inspected the cited originals and executed the saved bounded CPU scripts; original GPU scores were recomputed from original run inputs/results, not rerun by me.')
  if kind=='empirical':c['verification']['denominators']=den
  if kind=='numeric':c['verification']['tolerance']='Exact integer arithmetic; displayed floating values approximate within1e-6.'
 claims.append(c)
def ref(path,loc,support):return (repoid[path],loc,support)
claim('alignment','concept','A projector maps feature dimensions; dimensional compatibility and random feature sensitivity do not themselves establish semantic answering. Supervised encoder tasks and later alignment require separate held-out checks.','Opening and synthetic encoder-stage explanation',[('llava','§4.1 Eq.(1); §4.2 Stage1/Stage2','Learned projection connects pretrained visual features and embeddings; supervised alignment is a separate training stage.'),('own-calculation','Information-loss argument','A collapsed input distinction cannot be recovered downstream.')],['analysis'],'This is conditional workflow guidance, not a claim that random features contain no information or every trained encoder guarantees understanding.')
claim('encoder-cli','software','Practice pretraining uses shape classification and >500 Hz low/high tones, holding out blue offset1 square/circle and180/1000 Hz. Its JSON reports mode, two holdout examples and their fraction; 0.5 means one correct,1.0 two.300 steps is a recipe, not a guarantee.','First two commands and holdout paragraph',[ref('scripts/pretrain_encoders.py','main: items/training/holdout/update/report','Exact task, held-out items and train gate.')],['probe','pretrain'],'No300-step quality rerun; personally executed one actual CPU update per CLI and checked both reports/saved formats,plus exact construction/count arithmetic.',str(p['cli_encoder_holdout'])+'; actual CLI one-update reports both train mode,holdout_examples2 and encoder/classifier/report save fields.')
claim('practice-questions','software','Practice train/infer task routing uses shape?,pitch?,joint? and targets circle,high,square,low for the supplied inputs; answer is generated output and task is checkpoint metadata.','Three train commands and three infer_modal commands',[ref('scripts/train.py','modal_loss','Practice synthetic supervision uses circle/square and880/220 Hz high/low.'),ref('scripts/infer_modal.py','load_modal_checkpoint/main question and JSON','Task and actual answer fields.')],['probe'],'These are target definitions;500-step practice outcomes are explicitly unmeasured.', 'Code routes vision/audio/joint to shape/pitch/joint targets; own public-media inference confirms task/answer JSON semantics.')
claim('freeze','software','CLI projector opens both projectors; CLI partial also opens first/last language blocks while embeddings/output remain frozen. Fixed VQA partial opens image projector plus only last block. Unused audio has no gradients on image-only input.','Freeze paragraph and partial comparison table',[ref('scripts/train.py','main requires_grad branches','CLI trainable scope.'),ref('scripts/course_experiments/modalities.py','_freeze','Fixed experiment scope.')],['probe'],'Verified with a two-block CPU model; requires_grad eligibility does not imply an update on every input.',str(p['partial_scopes'])+'; '+str(p['mask_and_gradient']))
claim('native-resume','software','Native multimodal-v1 saves the language/encoders/projectors/config, optimizer, RNG, step and trainable names. Resume restores the remaining original total schedule, checks recipe and scope, and rejects encoder reload; weight-only/inference and fixed encoder formats do not provide this CLI exact-resume route.','Checkpoint and resume paragraphs plus resume command',[ref('tiny_perceptron/training.py','save_checkpoint/load_checkpoint/restore_checkpoint_rng','Full save and reconstruction contract.'),ref('scripts/train.py','main resume metadata/optimizer/names/start-end checks','Same recipe and total steps.'),ref('scripts/course_experiments/modalities.py','run_encoders/_fit','Fixed encoder payload is a separate format.')],['probe','supplement'],'Own proof is a three-update CPU schedule with exact model-tensor equality; cross-device or arbitrary-format exact resume is not claimed.', 'Interrupted at1 of3 updates; resumed2; step3 and all model tensors equal uninterrupted. Completed schedule, encoder reload and changed LR each reject.')
claim('language-evaluation','software','load_checkpoint returns model and payload; evaluating after.language on the same SFT records and24-new-token cap uses the language path without images or weight updates and provides row-level answers, exact-match denominators and EOS.','Python before/after evaluation block',[ref('scripts/evaluate.py','evaluate and metric_denominators','Language-only no-grad evaluation and actual denominator semantics.'),ref('tiny_perceptron/training.py','load_checkpoint return','Tuple model/payload.')],['probe'],'Own one-record behavior probe, not a claim about the unrun practice checkpoints or all language abilities.',str(p['language_evaluation']))
claim('fixed-encoders','empirical','The separate fixed encoders update250 times: visual test6/6 and audio11/14; these test sets differ from the practice CLI two-item holdout.','Formal encoder paragraph',[('record-encoders','results.vision/audio.training/data/validation/test','Original recorded fixed configuration and all raw classification samples.'),ref('scripts/course_experiments/modalities.py','run_encoders/_vision_records/_audio_records','Exact position/frequency grouped tasks.')],['probe'],'Single original GPU run, known synthetic classes/held-out positions or frequencies; no natural-image/ASR inference.', 'Raw predictions yield visual6/6 and audio11/14;250 updates,8 examples each.',den={'seed':42,'updates_each':250,'batch_examples':8,'vision_train_validation_test':[18,6,6],'audio_train_validation_test':[16,8,14]})
claim('fixed-vqa','empirical','The fixed300-step description alignment and160-step VQA variants use their own starting point. Last-block partial tests12/12; two-stage budget18238 versus direct18256 yields9/12 versus10/12. Replay0.5 selects complete text examples probabilistically and is not half the answer targets. Direct VQA lacks a text-retention measurement.','Fixed experiment recipe, partial table, replay and budget paragraphs',[('record-projector','results.training/data/test','Original alignment starting point,14408 targets and300 steps.'),('record-vqa','results.variants and direct_vs_two_stage_budget','All raw VQA scores/configurations and budget.'),ref('scripts/course_experiments/modalities.py','run_vqa/_loss_fn','Same initial wrapper,160-update comparisons,example probability, and direct variant no text-after evaluation.')],['probe','supplement','fig-retention'],'Original single-seed GPU record audit. The direct/two-stage score difference does not establish a winner for unmeasured language retention.', '14408+3830=18238; direct762 updates sum18256. Partial12/12; all9/12; direct10/12. Replay332 text versus308 image examples,2373 versus1841 targets.',den={'seed':42,'alignment_updates':300,'alignment_targets':14408,'vqa_updates':160,'batch_examples':4,'vqa_test_examples':12,'text_retention_examples':10,'direct_updates':762,'direct_targets':18256,'replay_targets':4214})
claim('real-modal','empirical','Fresh real-data encoders attach to direct SFT and update all eligible parts250 times at four examples per update. Fashion30/10/10 gives4/10 validation,3/10 test and7528 targets,145664 parameters. FSDD20/20/20 speaker holdout gives5/20,3/20 and2000 targets,148736 parameters.','Real-data run paragraph',[('record-real_modal','results.fashion-mnist/fsdd.training/data/validation/test','Original dataset records, update history and raw generated IDs.'),('fsdd','Usage/Organization','Original training indices and speaker file identity.'),('fashion','Opening dataset specification','Original grayscale images and ten categories.')],['probe','supplement','fig-fsdd'],'Custom tiny upstream-training subsets; scores are not official Fashion/FSDD benchmarks and do not establish general capability.', 'All raw-ID scores and independently sampled target sums match.12148 maximum resampled samples require176 context;48*64 extra position parameters=3072.',den={'seed':42,'updates_each':250,'batch_examples':4,'fashion_train_validation_test':[30,10,10],'fsdd_train_validation_test':[20,20,20],'fashion_targets':7528,'fsdd_targets':2000})
claim('media-inputs','software','Real fashion inputs convert28×28 grayscale to RGB,resize16×16 anddivide255. Original8kHz PCM16 is truly resampled to16kHz FLOAT for the fixed experiment. No extra per-image mean/std or per-recording peak/energy normalization occurs.','Input preprocessing paragraph and custom JSONL paragraph',[ref('scripts/course_experiments/modalities.py','_media/run_real_modal/_resample_8_to_16','Exact preprocessing and original/derived format.'),ref('tiny_perceptron/modal_data.py','modal_example','Relative paths and strict16kHz nonempty mono custom-data gate.'),('soundfile-source','read dtype/channel contract lines225–275','PCM decoding and mono shape.'),('libsndfile','Subtype table and conversion Note1','PCM16 signed integer storage,FLOAT32 and integer-to-float range conversion.'),('record-format','records[0] and original_run_metadata','Original first-waveform audio payload provenance.')],['probe','supplement'],'Input-format conversion is distinct from gain normalization; only one derived WAV was written and all60 existing source headers read-only.', '60 original hashes/PCM16 mono8k headers match. One4591→9182 FLOAT16k example retains0.573875s; float samples=int16/32768; generic/fixed resamplers equal. Image pixels exactly match RGB resize/div255. Custom8k input rejects.')
claim('feature-normalization','concept','Feature LayerNorm is a learned model layer along each position’s feature axis, with biased variance,epsilon and affine parameters; it does not replace documenting raw input amplitude/pixel preprocessing.','LayerNorm link in preprocessing paragraph; actual4.3 prerequisite',[('torch-normalization-source','LayerNorm lines105–171','Normalized_shape,biased variance,epsilon,per-feature affine.'),('libsndfile','Conversion Note1','Input PCM representation conversion is a separate operation.')],['probe','runtime'],'The4.3 numerical outputs are approximate: output variance approaches1; learned affine transforms may alter mean/variance. This is distinct from waveform or per-image preprocessing.')
claim('public-media','empirical','The cited existing public checkpoints actually yield42 for the digit image,Ankle boot for first fashion test image,and8 withEOS for original8kHz digit0 audio passed with explicit resampling.','Public weights and CPU media paragraph',[('record-media','commands[0:3],input_selection_evidence,raw stdout','Original command/input/result provenance.'),ref('scripts/infer_modal.py','main real-media handling and JSON','Actual CPU input and output path.')],['probe'],'Personally reproduced three individual CPU outputs. One wrong audio answer remains wrong despiteEOS; no dataset quality replication.', 'All three commands exit0 and outputs match42,Ankle boot,8; original stdout SHA receipts agree.',den={'individual_image_examples':2,'individual_audio_examples':1,'audio_target':'0','audio_generated':'8','device':'cpu','training_updates_replicated':0})
claim('ocr-cli','software','OCR generator groups three offsets of each digit string in one split; seed42 validation has30 rows. Normal/blank/shuffle evaluate the same selected data/model/cap; shuffle changes media and preserves original question/target, saving donor_row. Original-target exact_match can fail when the donor image is read correctly.','OCR preparation/evaluation commands and donor-row interpretation',[ref('scripts/prepare_ocr.py','main/draw_digits','Fixed glyph generator and string-family split.'),ref('scripts/evaluate_modal.py','main donor map and samples','Zero image,deranged media pairing and original target scoring.')],['supplement'],'Own actual ablation is a three-row fixture from validation families using an existing public OCR model; no claim about the unrun500-step practice CLI. Blank has no taught ideal response. Resize can remove distinctions downstream training cannot recover.', 'Reconstructed80/10/10 families→240/30/30 rows. Actual none targets64/29/27 generate64/23/27;blank9/9/9;shuffle27/64/23 with donors2/0/1; original-target scores remain false.')
claim('formal-ocr','empirical','The separate fixed OCR run uses direct SFT,pretrained visual weights,batch8 and500 updates: validation9/30,test2/30,40 edits over57 reference characters,andEOS30/30. These are distinct from practice commands and stopping is distinct from correct OCR.','Formal OCR result paragraph',[('record-ocr','results.training/data/validation/test','Original fixed schedule,all raw generated IDs and references.'),ref('scripts/course_experiments/modalities.py','run_ocr/_evaluate','500-step full-model run and edit-distance/CER rule.')],['probe','supplement'],'Single fixed-font one/two-digit run; ten held-out string families per side. No handwriting/document-quality or practice-CLI performance inference.', 'All raw-ID matches recomputed; independent dynamic-programming edit sums40 and reference lengths57→0.7017543859649122;EOS30/30;sampled targets11584.',den={'seed':42,'updates':500,'batch_examples':8,'train_validation_test_rows':[240,30,30],'validation_test_families':[10,10],'effective_training_targets':11584,'test_strings':30,'reference_characters':57})

allids=[c['id'] for c in claims]
report=dict(schema_version=1,review_stage='technical',lesson_id='T.6',source='course/training.md#T.6',reviewer_task='/root/v4_review_coordinator/factual_v4_t_6',reviewer_context='fresh',source_sha256=p['source_hashes']['course/training.md#T.6'],figure_sha256={path:sha(path) for path in ['course/figures/fsdd_speaker_holdout.svg','course/figures/vqa_text_retention.svg']},verdict='pass',claims=claims,sources=sources,artifacts=artifacts,issues=[],checks={
 'factual_accuracy':dict(status='pass',details='Complete substantive section and canonical prerequisites read; all claims checked against original methods/API sources,current code,raw runrecords and own bounded execution.',claim_ids=allids),
 'numeric_verification':dict(status='pass',details='Recomputed every cited dataset score/budget from raw predictions and histories; independently sampled answer budgets and exact parameter/audio-duration arithmetic. Own CPU scope remains separate from recorded GPU training.',claim_ids=[c['id'] for c in claims if c['kind']=='empirical']),
 'figure_consistency':dict(status='pass',details='T.6 contains no direct SVG. Personally rendered/viewed needed FSDD and retention prerequisite figures; speaker splits,arrow,sample counts,duration,percentages,EOS and eight shared-scale bars match text/original records.',claim_ids=['fixed-vqa','real-modal','media-inputs']),
 'source_verification':dict(status='pass',details='Original LLaVA/FSDD/Fashion/libsndfile read at exact locators; official PyTorch/soundfile raw API sources retrieved and byte-identical installed sources. 403 documentation attempts retained. Full code/record/section/render hashes retained.',claim_ids=allids),
 'limitations':dict(status='pass',details='Practice CLI,formal GPU training and own CPU checks are distinct. Tiny custom splits/single seed,unmeasured direct-VQA language retention,blank/shuffle interpretation,weight-only resume limits and no300/500-step quality guarantees are explicit.',claim_ids=allids)},prerequisite_sha256={k:v for k,v in p['source_hashes'].items() if not k.endswith('#T.6')},independence_note='Existing report copied unread. Initial rg --files incidentally exposed prior review artifact filenames only; no author/peer substantive conclusions read. See analysis.md. No subagents used.',execution_limits='No GPU or long training,heavy downloads,model installs/full release/all-book runs. Existing inputs/checkpoints used read-only. One small ignored derived WAV;3-update toy CPU resume and3-row OCR ablations only. Original formal run quality audited,not replicated.')
Path('docs/technical-reviews/T.6.json').write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n')
print(json.dumps({'report_sha256':sha('docs/technical-reviews/T.6.json'),'source_sha256':report['source_sha256'],'claims':len(claims),'verdict':report['verdict']},indent=2))
