"""This owner's supplied judgments; metadata binding uses page-record.py."""
import hashlib,json,subprocess,sys
from pathlib import Path
R=Path(__file__).resolve().parents[4]
F=R/'docs/technical-reviews/artifacts/p7_technical_f'
def repo(i,p,n):
 return dict(id=i,kind='repository_code',title=p,path=p,verified=True,inspection_note=n)
def original(i,p,url,rev,n):
 return dict(id=i,kind='official_source',title=p,url=url,version=rev,sha256=hashlib.sha256((R/p).read_bytes()).hexdigest(),verified=True,authority_reason='Original publisher repository or official university course; checked the specified original content.',checked_original=True,inspection_note=n,accessed_on='2026-10-07')
def artifact(i,p,n):
 return dict(id=i,kind='execution',path='docs/technical-reviews/artifacts/p7_technical_f/'+p+'.json',description=n,result=n)
def ev(s,l,n):return dict(source_id=s,locator=l,supports=n)
def claim(i,k,s,l,scope,e,a,observed=None,den=None):
 d=dict(id=i,kind=k,statement=s,location=l,scope=scope,status='verified',evidence=e,artifact_ids=a)
 if k in ('numeric','software','empirical'):
  d['verification']=dict(method='executed',expected=s,observed=observed,details=scope)
  if k=='numeric':d['verification']['tolerance']='Integer counts exact; floating point 1e-6 in synthetic formula probes.'
  if k=='empirical':d['denominators']=den
 return d
def save(d):
 q=subprocess.run([sys.executable,str(F/'page-record.py')],input=json.dumps(d,ensure_ascii=False),text=True,cwd=R,capture_output=True)
 print(q.stdout,end='');print(q.stderr,end='',file=sys.stderr);assert q.returncode==0

if sys.argv[1]=='curriculum':
 training=json.loads((F/'page-training.json').read_text());guides=json.loads((F/'source-additions-guides.json').read_text())
 sources=[s for s in training['sources'] if s['id'] in ['moe-original','distill-original','dpo-original','lora','torch-autograd','causal','split']]+[guides[k] for k in ['quantization-original','attention','mtp','speculative']]
 specs=[
 ('nano-gpt','nanochat-sources/nanochat/gpt.py','karpathy/nanochat','92d63d4e8bb4df75c3b71618f31ddde2378b2bcd','nanochat/gpt.py','131–153 Dense ReLU squared MLP; 174/177 independent embedding/output.'),
 ('nano-bpb','nanochat-sources/nanochat/loss_eval.py','karpathy/nanochat','92d63d4e8bb4df75c3b71618f31ddde2378b2bcd','nanochat/loss_eval.py','9–65 total nats/(ln2 target bytes), ignored/special excluded.'),
 ('nano-mask','nanochat-sources/nanochat/tokenizer.py','karpathy/nanochat','92d63d4e8bb4df75c3b71618f31ddde2378b2bcd','nanochat/tokenizer.py','180–238 user/tool output unsupervised, assistant/end supervised, colored display.'),
 ('nano-engine','nanochat-sources/nanochat/engine.py','karpathy/nanochat','92d63d4e8bb4df75c3b71618f31ddde2378b2bcd','nanochat/engine.py','82–125 allocation/position; 194–218 one prompt prefill then cloned cache.'),
 ('nano-backend','nanochat-sources/nanochat/flash_attention.py','karpathy/nanochat','92d63d4e8bb4df75c3b71618f31ddde2378b2bcd','nanochat/flash_attention.py','25–69 availability and dtype select FA3 or SDPA.'),
 ('nano-run','nanochat-sources/runs/speedrun.sh','karpathy/nanochat','92d63d4e8bb4df75c3b71618f31ddde2378b2bcd','runs/speedrun.sh','45–76 tokenizer/pretrain/eval/SFT commands; not executed.'),
 ('miniv-model','minimind-v-sources/model/model_vlm.py','jingyaogong/minimind-v','1862b633fc082a723e78dbead9777545f09d960c','model/model_vlm.py','46–95 pretrained frozen Siglip and vision projection/placeholder replacement.'),
 ('miniv-labels','minimind-v-sources/dataset/lm_dataset.py','jingyaogong/minimind-v','1862b633fc082a723e78dbead9777545f09d960c','dataset/lm_dataset.py','75–91 only assistant answer through EOS; other labels -100.'),
 ('miniv-freeze','minimind-v-sources/trainer/trainer_utils.py','jingyaogong/minimind-v','1862b633fc082a723e78dbead9777545f09d960c','trainer/trainer_utils.py','76–92 freeze0/1/2; 106–155 export vs resume checkpoint.'),
 ('miniv-pretrain','miniv-sources/trainer/train_pretrain_vlm.py','jingyaogong/minimind-v','1862b633fc082a723e78dbead9777545f09d960c','trainer/train_pretrain_vlm.py','99–103 default freeze2 projector-only.'),
 ('miniv-demo','miniv-sources/scripts/web_demo_vlm.py','jingyaogong/minimind-v','1862b633fc082a723e78dbead9777545f09d960c','scripts/web_demo_vlm.py','68–105 image features to generate; 141–146 Gradio widgets; not served.'),
 ('mini-model','minimind-sources/model/model_minimind.py','jingyaogong/minimind','f659b55761b754d306bd140573493a6543cafd7f','model/model_minimind.py','12–45 defaults tied/SiLU; 136–181 FFN and sparse top-k/aux; 247 tie assignment.'),
 ('mini-dpo','minimind-sources/trainer/train_dpo.py','jingyaogong/minimind','f659b55761b754d306bd140573493a6543cafd7f','trainer/train_dpo.py','34–50 masked sequence preference log-ratio relative to reference.'),
 ('mini-kd','minimind-sources/trainer/train_distillation.py','jingyaogong/minimind','f659b55761b754d306bd140573493a6543cafd7f','trainer/train_distillation.py','25–36 detached teacher temperature/T² KL; 49/67–94 CE+KL masked targets.'),
 ('torchao-overview','torchao-sources/docs/source/contributing/quantization_overview.rst','pytorch/ao','a701b6a6058720c21f95908b7ae4a24bf0cae1b6','docs/source/contributing/quantization_overview.rst','1–20/40–66/72–103 values, packing and kernels separated.'),
 ('torchao-qat','torchao-sources/docs/source/workflows/qat.md','pytorch/ao','a701b6a6058720c21f95908b7ae4a24bf0cae1b6','docs/source/workflows/qat.md','22–27/97–105 prepare fake quant then train then convert deployment quantization.'),
 ]
 for i,p,re,rev,f,n in specs:sources.append(original(i,'outputs/p7_technical_f/source-cache/'+p,f'https://raw.githubusercontent.com/{re}/{rev}/{f}',rev,n))
 sources += [
 original('cs336','outputs/p7_technical_f/source-cache/official-courses/cs336-current.html','https://raw.githubusercontent.com/stanford-cs336/stanford-cs336.github.io/25d740fd9060cc6613163b5b88ca88a5f64138ff/index.html','25d740fd9060cc6613163b5b88ca88a5f64138ff','771–842 course schedule evaluation/data/alignment-multimodality; not full lectures.'),
 original('mit-style','outputs/p7_technical_f/source-cache/official-courses/mit-lab3.ipynb','https://raw.githubusercontent.com/MITDeepLearning/introtodeeplearning/535e0862f52c81288258fae0516c40968d07f603/lab3/LLM_Finetuning.ipynb','535e0862f52c81288258fae0516c40968d07f603','Markdown cells 2/5/36: fine-tuning style and style evaluation; no lab execution.'),
 original('mit-cv','outputs/p7_technical_f/source-cache/official-courses/mit-lab2.ipynb','https://raw.githubusercontent.com/MITDeepLearning/introtodeeplearning/535e0862f52c81288258fae0516c40968d07f603/lab2/PT_Part2_Debiasing.ipynb','535e0862f52c81288258fae0516c40968d07f603','cell52 four demographic groups compare CNN/DB-VAE evaluation; not reproduced.'),
 original('harvard','outputs/p7_technical_f/source-cache/official-courses/harvard-week06.md','https://raw.githubusercontent.com/Harvard-IACS/2025-AC215/a0d3ed05aa749aa46c95c70a2f519db0eef2bb30/_modules/week-06.md','a0d3ed05aa749aa46c95c70a2f519db0eef2bb30','Oct7 RAGs/Agents, Oct9 Agents schedule; full original 330 bytes read.'),
 original('ntu25','docs/technical-reviews/artifacts/p6-public-a/originals/speech.ee.ntu.edu.tw__~hylee__ml__2025-spring.php','https://speech.ee.ntu.edu.tw/~hylee/ml/2025-spring.php','official archived snapshot SHA','Extracted text134–180 schedule Post-training and Forgetting / Reasoning. Only original cache, not prior review.'),
 original('ntu26','docs/technical-reviews/artifacts/p6-public-a/originals/speech.ee.ntu.edu.tw__~hylee__ml__2026-spring.php','https://speech.ee.ntu.edu.tw/~hylee/ml/2026-spring.php','official archived snapshot SHA','Extracted text95–111 AI Agent/OpenClaw operating principles; tools as curriculum clue, no full video/source mechanics claim.'),
 repo('v2-model','tiny_perceptron/selftrained/model.py','PaddingSafeMoE 75–108 and Dense/MoE blocks 109–131 actual routing/parameters, no speed guarantee.'),
 repo('v2manifest','docs/selftrained/v2-manifest.json','scope/config finite Fashion/ROI OCR/MInDS and from random initialization.'),
 repo('index','course/lesson-index.json','Only specified 25 title/notebook metadata and existence, no unread chapter bodies.'),
 repo('builder','scripts/build_course.py','Notebook and site pair from common text source.'),
 repo('kernel','scripts/check_notebooks.py','Fresh NotebookClient kernel per notebook; did not execute all287.'),
 ]
 arts=[artifact('historical','curriculum-legacy-raw-result-counts','Own original legacy counts/by_task aggregation, not new grading.'),artifact('nano-contracts','curriculum-nanochat-contracts','AST7 Python files/bash-n2 shell files; did not train upstream.'),artifact('reference-contracts','curriculum-reference-source-contracts','AST10 original files; only source contract.'),artifact('formula-probes','curriculum-pinned-cpu-functions','Own narrow original generate_labels/DPO/KL CPU probes.'),artifact('one-update','curriculum-one-update-flow','Synthetic one parameter real SGD update; no model quality.'),artifact('mapping','curriculum-lesson-mapping','25 specified title/notebook entries mechanically matched.'),artifact('inventory','readme-inventory-counts','287/313 actual inventory.'),artifact('parameters','readme-v2-actual-config-parameter-count','True550 vocab CPU parameters.'),artifact('test-raw','validation-historical-counts-and-wrapper','Original v2 test counts from raw fields.'),artifact('archive','asset-v2-actual-archive-counts','Actual v2 tar count/hash.'),artifact('release','readme-historical-release-and-runtime','Raw historical stage/public manifest selected/completed boundaries.')]
 cs=[
 claim('counts','numeric','287 notebooks/313 numbered sections; MoE5447107/Dense2288067; train28876/val2435/test3734 each.','intro','Own CPU inventories/actual550 vocab/tar JSONL counts; no new complete training.',[ev('v2manifest','model_config/scope','finite data/model identity')],['inventory','parameters','archive'],'Exact287/313/5447107/2288067/28876/2435/3734'),
 claim('legacy','empirical','Stored legacy deployment joint/DPO each78/90; student CE62/90,KD61/90; these are separate finite synthetic historical evaluations.','intro legacy comparison','Read original per-task raw counts and summed; no semantic regrade or v2 replacement.',[ev('split','train/validation/test handling','Separate finite evaluation scope')],['historical'],'Counts/sums90/78,90/62,90/61',{'deployment_each':90,'student_each':90}),
 claim('purpose','concept','LoRA changes trainable branches, MoE sparse active experts, quantization storage/kernels, distillation smaller student architecture/signals solve different questions.','reference comparison/table','Definitions and conditions only; course/upstream quality not guaranteed.',[ev('lora','§3–4','low rank adaptation'),ev('moe-original','§1.2/2.1','sparse routing vs total experts'),ev('quantization-original','§2.1 Eq1','quantized mapping'),ev('distill-original','§2','temperature teacher targets')],[]),
 claim('pinned-implementations','software','Fixed originals contain nanochat BPB/mask/cache/backend, MiniMind-V vision/projector/freeze, MiniMind DPO/MoE/CE+KL and TorchAO prepare/convert.','13-row comparison/reference links','Personally located source contracts; AST and narrow formulas only, not full upstream training/serving/kernel speed.',[ev('nano-bpb','9–65','nats/bytes'),ev('nano-mask','180–238','supervised masks'),ev('nano-engine','194–218','prefill clone'),ev('nano-backend','25–69','FA3 conditions'),ev('miniv-model','46–95','pretrained vision projection'),ev('miniv-freeze','76–92/106–155','freeze and checkpoint'),ev('miniv-pretrain','99–103','default freeze2'),ev('mini-dpo','34–50','preference objective'),ev('mini-model','148–181','topk/aux'),ev('mini-kd','25–36/67–94','CE+KL'),ev('torchao-qat','22–27/97–105','prepare/convert'),ev('torchao-overview','72–103','packing/kernels')],['nano-contracts','reference-contracts','formula-probes'],'7/10 original Python files parse; two shell syntax checks; labels mask true, DPO ln2/.673347, KL1.19e-7 teachergradNone'),
 claim('architecture-comparison','concept','nanochat ReLU² and untied input/output differ from MiniMind-V defaults SiLU gate and tied weights; comparisons need actual matched conditions.','after comparison table','Source defaults at pinned revisions, not every possible config or fair v2 MoE/Dense quality comparison.',[ev('nano-gpt','131–153/174/177','Dense activation/independent modules'),ev('mini-model','12–45/136–146/247','defaults and tie'),ev('moe-original','§2','active paths condition')],[]),
 claim('learning-flow','software','Readable context mask and scored labels differ; single nonaccumulating update can clear old gradients after forward/loss and before backward/step.','learning-flow SVG','One real synthetic SGD update and original causal/autograd contracts; no text learning result.',[ev('causal','ignored targets/shift','X/Y scoring'),ev('torch-autograd','accumulation/zero_grad','clear before new backward')],['one-update'],'loss4; oldgrad3→None→8; w1→.1999999881'),
 claim('route','software','Specified 25 route IDs map to matching index titles and existing notebooks.','10-row learning route table','Metadata/title only, not semantic review of unread chapters.',[ev('index','25 selected entries','IDs/title/path')],['mapping'],'25 of25 unique entries and paths'),
 claim('official-topics','concept','Original university schedules/labs contain the stated evaluation/data/multimodality, style/CV, RAG/Agents and forgetting/reasoning/agent topic clues.','recent public courses','Only original schedules and necessary lab text; no whole lectures/video review or pedagogical effectiveness claim.',[ev('cs336','771–842','topics'),ev('mit-style','cells2/5/36','style/evaluation'),ev('mit-cv','cell52','CV groups'),ev('harvard','Oct7/9','RAG/Agents'),ev('ntu25','schedule134–180 extracted','forgetting/reasoning'),ev('ntu26','schedule95–111 extracted','AIagent principles clue')],[]),
 ]
 checks={k:dict(status='pass',details=n,claim_ids=ids) for k,n,ids in [('factual_accuracy','Six pinned project mechanisms and separate goals match actual source definitions.',['purpose','pinned-implementations','architecture-comparison']),('numeric_verification','Own raw aggregation/counts and 1e-6 formula tolerance; legacy counts retained as historical.',['counts','legacy']),('figure_consistency','Original SVG640/360 and20 real desktop/mobile captures show masks, nonaccumulation and all4 tables.',['learning-flow','route']),('source_verification','Original fixed sources/university schedules checked at precise locations; no author review used.',['official-topics','pinned-implementations']),('limitations','No full upstream training, GPU speed, whole lecture or unseen chapter validation; toy updates and source contracts clearly scoped.',['learning-flow','architecture-comparison','legacy'])]}
 save(dict(page_id='curriculum',verdict='pass',sources=sources,artifacts=arts,claims=cs,checks=checks,issues=[],page_receipt='docs/technical-reviews/artifacts/p7_technical_f/page-curriculum-view.json',page_view_details='All20 selected screenshots personally viewed; four tables13/5/6/10 rows and long three-stage figure, both viewports.',provenance_notes=['Raw capstone interpretation/limitation metadata incidentally exposed at unit1; excluded as evidence.','Source full files/PDF/text stay cache; official metadata binds URL/revision/SHA and narrow personally checked locator.','University topic location was pending at unit9/14, resolved through original official sources supplied as paths/URLs; no author public-course-review read.']))
