"""Create only this independent review and an evidence inventory from actual files."""
from pathlib import Path
import hashlib, json

BASE = Path(__file__).resolve().parent
ROOT = BASE.parents[3]
rel = lambda p: p.relative_to(ROOT).as_posix()
sha = lambda p: hashlib.sha256(p.read_bytes()).hexdigest()
extraction = json.loads((BASE/"original/extraction.json").read_text())
v = json.loads((BASE/"verification.json").read_text())
env = json.loads((BASE/"environment.json").read_text())
environment = {k:str(env[k]) for k in ["python","torch","device","threads","cuda_build","cuda_available"]}
artifact_names = {
    "verification.json":"bounded-cpu",
    "helper-run/execution.json":"original-fence-run",
    "figure.png":"figure-render",
    "checks-receipt.json":"command-receipt",
    "inspection.md":"inspection",
    "sources/transformer-v7.pdf":"transformer-pdf",
    "text_foundation.json":"archived-result",
}
artifacts = []
for n,path in enumerate(sorted(BASE.rglob("*")),1):
    if not path.is_file() or path.name in {"manifest.json","checker-receipt.json","checker.stdout.txt","checker.stderr.txt"}:
        continue
    short = path.relative_to(BASE).as_posix()
    kind = "code" if path.suffix == ".py" else "source_snapshot"
    if short.startswith("sources/"):
        kind = "source_snapshot"
    if short == "inspection.md":
        kind = "derivation"
    if short == "figure.png":
        kind = "figure_render"
    item = {"id":artifact_names.get(short,f"evidence-file-{n}"),"path":rel(path),"sha256":sha(path),"kind":kind,"description":f"4.7 本輪永久證據：{short}；用途與命令、來源定位見 inspection.md 及 receipts。"}
    if short in ["verification.json","helper-run/execution.json","checks-receipt.json"]:
        item.update(kind="execution",environment=environment)
        if short == "verification.json":
            item.update(command=".venv/bin/python docs/technical-reviews/artifacts/phase4-4_7-independent/verify.py",result="exit 0；原 fence、CE 分母、梯度不更新、前綴/因果/未遮罩正控制、錯 shift、延長練習、原結果計數及版本核對全部通過。")
        elif short == "helper-run/execution.json":
            item.update(command=".venv/bin/python docs/review-tools/section_facts.py course/chapters/04.md#4.7 --output /tmp/phase4-4_7-independent-run --execute --timeout 30",result="exit 0；原 fence 印三對與 [1,3,5]，CE 1.8268028497695923；guard_events=[]。worker 實際 argv、stdout/stderr、env 永久保存。")
        else:
            item.update(command=".venv/bin/python docs/technical-reviews/artifacts/phase4-4_7-independent/run_checks.py",result="verify、Inkscape render、Inkscape version 三項 exit 0；每項 argv/cwd/timeout/stdout/stderr/output hash 在此 receipt；SVG renderer 為 Inkscape 1.4。")
    artifacts.append(item)
(BASE/"manifest.json").write_text(json.dumps({"scope":"4.7 pre-checker permanent evidence inventory; no model/data downloads or training; initial failed audit preserved", "files":[{"path":a["path"],"sha256":a["sha256"]} for a in artifacts]},ensure_ascii=False,indent=2)+"\n")
artifacts.append({"id":"manifest","path":rel(BASE/"manifest.json"),"sha256":sha(BASE/"manifest.json"),"kind":"source_snapshot","description":"本節永久證據檔案的實際 SHA-256 inventory；checker 執行後另存 checker receipt。"})

def official(identifier,title,url,version,note):
    return {"id":identifier,"kind":"paper" if identifier=="transformer" else "official_source","title":title,"url":url,"version":version,"accessed_on":"2026-10-05","authority_reason":"原作者研究論文的原始 arXiv PDF" if identifier=="transformer" else "PyTorch 官方 pytorch/pytorch repository 的明確 release tag 原始實作及內嵌 API 文件","verified":True,"checked_original":True,"inspection_note":note}
def repo(identifier,path,note,version=None):
    p=ROOT/path
    return {"id":identifier,"kind":"repository_code","title":path,"path":path,"sha256":sha(p),"version":version or "working tree ae8b2795c918b70773e664b6d6731c054ecff74e; exact file SHA-256 saved","verified":True,"inspection_note":note}
sources = [
    official("transformer","Attention Is All You Need","https://arxiv.org/pdf/1706.03762v7","arXiv:1706.03762v7", "我親讀原 PDF pp.2–5 的 §§3,3.1,3.2.3,3.3,3.4。§3.1 明確把一次 offset 與後格遮罩合起來；§3.2.3 允許自身與先前位置；§3 說明生成依序消費已生成字。只支持 masked decoder 原理，沒有把 encoder-decoder 原架構等同 TinyLM。"),
    official("torch-ce","PyTorch cross_entropy original source","https://raw.githubusercontent.com/pytorch/pytorch/v2.9.0/torch/nn/functional.py","PyTorch v2.9.0", "我親讀 cross_entropy L3375–3465，核對 logits、class-index target、ignore_index、sum/mean 與 [0,C)；未見任何 shift。官方快照 v2.9.0 不等同安裝 2.14.1+cpu；本輪用安裝版本另做 CE/ignore 實測。"),
    official("torch-backward","PyTorch Tensor.backward original source","https://raw.githubusercontent.com/pytorch/pytorch/v2.9.0/torch/_tensor.py","PyTorch v2.9.0", "我親讀 Tensor.backward L570–638，尤其 leaf grad 累積 L573–582、610–613 與 autograd 呼叫。支持 backward 計算並累積梯度；原 fence 參數不變由原碼及安裝版直接比對支持。"),
    official("torch-embedding","PyTorch Embedding original source","https://raw.githubusercontent.com/pytorch/pytorch/v2.9.0/torch/nn/modules/sparse.py","PyTorch v2.9.0", "我親讀 Embedding L15–44、135–199；固定字表大小、weights 軸、LongTensor index input 與保持 input 軸/附加 embedding width。與當前 TinyLM vocab=5 的 local code 合用，沒有宣稱兩個 PyTorch 版本一致。"),
    repo("data","tiny_perceptron/data.py","親讀 L46–51 shifted 的原始切片、長度檢查及 long dtype；也核對 IGNORE=-100。"),
    repo("model","tiny_perceptron/model.py","親讀 ModelConfig L15–28；Block/TinyLM L31–86；loss_sum/masked_loss L92–105；generate L108–131。逐項核對 token/vocab 軸、未傳 y 進 forward、沒有內部 shift、平均有效 labels 與逐字生成。"),
    repo("attention","tiny_perceptron/attention.py","親讀 L10–28、48–74；True 可讀、key<=query、-inf遮罩、softmax、因果 attention 呼叫。"),
    repo("ffn","tiny_perceptron/modern.py","亲讀 DenseFFN L35–53；Linear/GELU 只處理最後 width 軸，沒有繞過遮罩的跨 token 路徑。"),
    repo("generator","scripts/prepare_data.py","亲讀 generate_records L22–29；3 colors×2 shapes×2 sides 產生12則英文短文；與記錄 revision 的此段無差異。"),
    repo("recorded-text",rel(BASE/"recorded-revision/scripts/course_experiments/text.py"),"我從 local git show 取得原結果 revision 的實作，親讀 L262–278 的資料/訓練/探測。整檔 SHA 與 JSON code_sha256 相同；探測精確取前四位置所有候選。", "b52935d99f58b694cd932ac158c10c4d8d92d4c2; original Git blob snapshot"),
    repo("recorded-common",rel(BASE/"recorded-revision/scripts/course_experiments/common.py"),"我從 local git show 取得記錄版，親讀 split_records L50–70、records_sha256 L73–74、text_examples L77–97、fit_lm L122–202；600步 loop 包含 optimizer.step。整檔 SHA 與原 JSON 相同；所審函式 AST 和當前完全一致。", "b52935d99f58b694cd932ac158c10c4d8d92d4c2; original Git blob snapshot"),
    repo("archived-report","docs/course-experiments/results/text_foundation.json","我親自解析原 JSON 的 revision/device/status/evidence_status、results.data、results.training、results.causal_max_difference、code_sha256；只核對本節實測，未讀其他技術報告。", "recorded revision b52935d99f58b694cd932ac158c10c4d8d92d4c2; run gha-37038665524-1; raw SHA a81dfcbc0cdac92e3d21956e0857eeb34cc5aad32fdaa5d979988decbb53d2b0"),
    {"id":"cpu-execution","kind":"execution","title":"4.7 bounded independent CPU execution","verified":True,"artifact_id":"bounded-cpu"},
    {"id":"original-execution","kind":"execution","title":"4.7 original fence helper execution","verified":True,"artifact_id":"original-fence-run"},
]
def ev(source,locator,supports): return {"source_id":source,"locator":locator,"supports":supports}
def verification(expected,observed,details,tolerance=None,denominators=None):
    obj={"method":"executed","expected":expected,"observed":observed,"details":details}
    if tolerance: obj["tolerance"]=tolerance
    if denominators: obj["denominators"]=denominators
    return obj
claims=[
    {"id":"alignment-causal-parallel","kind":"concept","statement":"完整 [1,2,3,4] 一次 shift 成 x=[1,2,3],y=[2,3,4]；每位置只能使用自身及以前輸入，以對應的下一字為目標。已知训练資料/評分答案容許一次算三個已知前綴，但不給每題讀未來的權限；自回歸生成仍逐字接長。", "location":"4.7 首兩段、圖與圖後解釋", "scope":"本節 default TinyLM 及通常 causal next-token 原理。已知 targets 並不單獨保證平行性；本節模型的非遞迴 attention/逐位置操作與已知 x/y 一起支持一次整段。生成限本節普通 autoregressive 路線。", "status":"verified", "evidence":[ev("transformer","PDF pp.2–5, §3; §3.1 decoder; §3.2.3 masked self-attention; extracted L115–116,140–143,234–238","offset 與 causal mask 合作；自身及先前可讀，生成使用先前生成字。"),ev("data","shifted L46–51","資料只切一次 x=ids[:-1], y=ids[1:]。"),ev("attention","attention_mask/manual_attention L10–28; forward L64–70","每 query 只能讀 key<=query，未來在 softmax 前排除。"),ev("model","forward L68–86; generate L108–131","targets 沒傳進 forward；所有時間位置一起回傳分數，生成按最後 logits 接一字。"),ev("ffn","DenseFFN.forward L45–53","逐位置 FFN 不引入未來路徑。"),ev("cpu-execution","verification.json causal_and_parallel, generation","整段/前綴 tol1e-6，一改後格前格差0；拿掉mask正控制差0.1955；生成forward長1/2/3。")],"artifact_ids":["bounded-cpu","figure-render","inspection","transformer-pdf"]},
    {"id":"api-shapes-loss","kind":"software","statement":"shifted x/y 各3格；x[None]是[1,3]，vocab=5 的 TinyLM logits=[1,3,5]、合法class ID0..4。印出的三對是位置/target對應；masked_loss 同位置比較、不再 shift，本例以3個未忽略 target 的 CE 平均。", "location":"4.7 Python fence、其後兩個 API/輸出說明段", "scope":"原始 fence 的 CPU 執行，官方 API 與所列本地 helper；不主張其他 causal-LM 套件也不內部 shift。", "status":"verified","evidence":[ev("data","shifted L46–51","精確輸入/target與切片長度。"),ev("model","ModelConfig L15–28; TinyLM L60–64,68–86; loss_sum/masked_loss L92–105","width=8內部；最終vocab軸5；flatten只對相同位置，sum除count。"),ev("torch-embedding","Embedding L15–44,135–199","字表lookup保持input軸再加width；結合output層得到B,T,V。"),ev("torch-ce","cross_entropy L3385–3418,3456–3465","logits/classindices的同位置分類比較、[0,C)與ignore/sum契約，没有shift。"),ev("original-execution","helper-run stdout.txt,execution.json","原 fence 真實印三對與[1,3,5]、CE1.8268028497695923；exit0。"),ev("cpu-execution","verification.json original_fence","logsumexp-targetlogit三項相加除3與helper一致；忽略中間label變除2。")],"artifact_ids":["bounded-cpu","original-fence-run","inspection"],"verification":verification("三對(1,2),(2,3),(3,4)，shape [1,3,5]，同位置未shift CE=三項均值。","各CE(nats)=[1.9949963092803955,1.343278408050537,2.1421337127685547]，mean=1.8268028497695923，count=3；忽略中項count=2。","原 fence 和必要變化均實跑；CE獨立按logsumexp-targetscore計算，絕對容忍1e-7；labels shape/dtype與合法ID檢查精確。")},
    {"id":"backward-not-update","kind":"software","statement":"loss.backward() 計算並存葉參數梯度；本 fence 沒有 step 或手動更新，因此是把資料→模型→代價→梯度接通的未更新示範，不能當已學會序列的成績。", "location":"4.7 fence最後行與 loss.backward 解釋段", "scope":"這個 fresh seed-42 原 fence。沒有聲稱 random model 絕不可能偶然猜對某字；確認沒有由此程式進行參數學習。", "status":"verified","evidence":[ev("torch-backward","Tensor.backward L570–638，特別L573–582,610–613","對 graph leaves 求梯度並累積在grad。"),ev("original-execution","helper-run/fence-1.py 完整432 bytes; stdout.txt","原碼有backward，沒有optimizer/manual update；完整路徑成功。"),ev("cpu-execution","verification.json original_fence.gradient_norms,parameter_max_change_after_backward","17個參數tensor有限gradient；與同seed初始狀態逐tensor bitwise相等，最大更新0。")],"artifact_ids":["bounded-cpu","original-fence-run","inspection"],"verification":verification("backward後有有限非零gradient、参数值不變。","17個參數tensor有有限gradient，至少一個非零；所有state_dict與重建seed42初始值bitwise相同，max change=0。","執行完整原 fence 後另重建相同初始化以逐tensor核對；未做optimizer.step。")},
    {"id":"misalignment-pitfalls","kind":"software","statement":"已shift的 labels 若在模型內再作通常的 logits[:-1]/labels[1:] 對齊，看1的分數會比3；若 y=x.clone() 則改為目前可讀字的複製目標。這些錯目標仍可有匹配shape與正loss，應先逐題確認對應。", "location":"4.7 若工具已shift 段", "scope":"典型額外一次shift的具體反例，及本地masked_loss的unshifted變化。描述是目標錯置，不是已訓練出複製能力。", "status":"verified","evidence":[ev("transformer","§3.1 decoder, PDF p.3, extracted L140–143","一次offset配因果mask建立nexttoken，應維持這個對應。"),ev("data","shifted L46–51","原 helper 已經完成一次target offset。"),ev("model","loss_sum/masked_loss L92–105","不阻擋語意錯誤但shape合法的labels；不自動修正目標。"),ev("cpu-execution","verification.json misalignment","extra shift pairs[(1,3),(2,4)] CE2.332240104675293；copy pairs[(1,1),(2,2),(3,3)] CE1.5898919105529785，均有限正值。")],"artifact_ids":["bounded-cpu","inspection"],"verification":verification("額外通常shift得到(1,3),(2,4)；copy得到(1,1),(2,2),(3,3)，程式仍可算loss。","兩變化實際運算成功，CE分別2.332240104675293及1.5898919105529785，均>0。","必要小變化各自執行，沒有學習更新；原文反例成立，不用loss正數推知alignment正確。")},
    {"id":"extended-exercise","kind":"numeric","statement":"原序列延長成 [1,2,3,4,0] 時有4組 (1,2),(2,3),(3,4),(4,0)，shape=[1,4,5]。", "location":"4.7 練習延長 段", "scope":"精確索引/格數/軸檢查；0在此是合法class，未被忽略。", "status":"verified","evidence":[ev("data","shifted L46–51","5格原序列兩個切片各4格。"),ev("model","TinyLM.forward L68–86; ModelConfig vocab_size; loss_sum L94–98","新增batch軸1、時間軸4、候選軸5；ignore值為-100而非0。"),ev("torch-ce","cross_entropy Shape L3414–3418","C=5時class ID0合法。"),ev("cpu-execution","verification.json exercise","實際四對與模型[1,4,5]完全吻合。")],"artifact_ids":["bounded-cpu","inspection"],"verification":verification("原長5→4對；輸入[1,4]→logits[1,4,5]。","四對與[1,4,5]均精確相同。","用原shifted與同一TinyLM實跑；3軸依序batch/token/class，没有單位換算或四捨五入。","pairs/count/shape exact equality")},
    {"id":"existing-training-probe","kind":"empirical","statement":"本節補充的原始 text_foundation 實報使用12篇color/shape/side短文，split9/1/2且實際更新。最後ID13改14，比较前四位置全部候選logits，results.causal_max_difference=0.0；這是指定探測，不可由loss下降代替。", "location":"4.7 補充與重做 details唯一段", "scope":"核對既有run gha-37038665524-1的結果與原實作，不是重訓或重新測該trained checkpoint；CPU小機制驗證另列。0.0僅確認此probe的前面分數不變，廣泛因果性另由code/paper支持。", "status":"verified","evidence":[ev("archived-report","revision,status,evidence_status,results.data.train/validation/test,results.training.steps/history/effective_tokens,results.causal_max_difference,code_sha256","原JSON已完成、9/1/2、600步及探測0.0，環境/版本可追溯。"),ev("generator","generate_records L22–29","3×2×2=12個具體英文text文檔。"),ev("recorded-text","b52935d original run_text_foundation L262–278","用split後train訓練；probe[1,10,11,12,13]改末字14，[:, :-1]比較前4所有class，max abs。"),ev("recorded-common","split_records L50–70; text_examples L77–97; fit_lm L122–202,尤其L133–144","完整family切分；訓練optimizer.step；tokencount來自未忽略label。"),ev("cpu-execution","verification.json archived_measurement; recorded-vs-current.diff","重建小文档/seeded split 3個SHA和trainrecordsSHA吻合；只重播sampler count=342462；保留recorded原碼hash及相關函式AST一致。")],"artifact_ids":["bounded-cpu","archived-result","inspection"],"verification":verification("原始資料共12、train/val/test9/1/2，600步更新，所述探測0.0；相關版本及分母可以核對。","12=3×2×2、split9/1/2、所有split/records hashes吻合；history最後600；token重計342462；JSON probe=0.0；原實作比較[1,4,264]=1056個scalar。","親讀原JSON與原Git版本helper；沒有下載/讀取權重或重訓。初始audit whole-file-hash假設失敗已保存，後親讀原版本及diff確認本節所用contracts未變。",denominators={"documents_total":12,"split_documents":{"train":9,"validation":1,"test":2},"optimizer_steps":600,"batch_size":16,"effective_training_targets":342462,"probe_sequences":2,"tokens_per_probe":5,"compared_positions":4,"candidate_classes":264,"compared_scalar_scores":1056})},
]
report={"schema_version":1,"review_stage":"technical","lesson_id":"4.7","source":"course/chapters/04.md#4.7","source_sha256":extraction["source_sha256"],"figure_sha256":extraction["figure_sha256"],"reviewer_task":"/root/phase4_factual_coordinator/factual_4_7","reviewer_context":"fresh","author_tasks":[],"reviewed_on":"2026-10-05","verdict":"pass","actual_reading_scope":{"section":"4.7 only; original UTF-8 section begins source line264","chapter_intro_read":False,"other_section_text_read":[],"old_reviews_read":False,"implementation_read":["data.py shifted","model.py config/block/forward/loss/generate","attention.py mask/manual/forward","modern.py DenseFFN","prepare_data.py toy-text","recorded revision text.py run_text_foundation","recorded revision common.py split/text_examples/fit_lm"],"primary_sources":"Own PDF/official-source snapshots and inspection in artifacts; no copied review judgments","figure_visual_check":"Inkscape 1.4 native640×905 PNG rendered, then view_image inspected; no browser/responsive-layout claim"},"sources":sources,"claims":claims,"artifacts":artifacts,"issues":[],"checks":{"factual_accuracy":{"status":"pass","details":"原稿/圖/原implementation/原paper對齊；shift target、causal permission、training parallel vs sequential generation、無更新示範及兩個錯alignment反例核實。","claim_ids":["alignment-causal-parallel","api-shapes-loss","backward-not-update","misalignment-pitfalls"]},"numeric_verification":{"status":"pass","details":"CE按logsumexp-target重計平均3；ignore變除2。4對/shape精確；既有split、步數、tokens、probe scalar count均從原JSON/實作及有界重計核實。","claim_ids":["api-shapes-loss","extended-exercise","existing-training-probe"]},"figure_consistency":{"status":"pass","details":"唯一SVG已實際render/view，x/y及3個可讀prefix和score-target ID2/3/4與原碼/段落一致；只確認圖，不宣稱網頁響應layout通過。","claim_ids":["alignment-causal-parallel","api-shapes-loss"]},"source_verification":{"status":"pass","details":"親讀原arXiv PDF v7及PyTorch official v2.9.0 sources精確行；官方version與本機2.14.1+cpu明記不同；原run b52935d helper從Git blob取得/hash驗證並親讀，沒有沿用舊review。","claim_ids":[c["id"] for c in claims]},"limitations":{"status":"pass","details":"原fence只計梯度未更新；CPUtoy不能證明訓練模型泛化；既有0.0只是一個指定probe；完整方法由原paper+實作支持。無重訓/權重/資料下載。Inkscape成功但有Pango/GTK警告，browser/desktop/mobile頁面未檢查。原audit hash假設失敗已保存並用原revision契約核對修正，不是正文issue。","claim_ids":["alignment-causal-parallel","backward-not-update","misalignment-pitfalls","existing-training-probe"]}}}
(ROOT/"docs/technical-reviews/4.7.json").write_text(json.dumps(report,ensure_ascii=False,indent=2)+"\n")
print("Wrote 4.7.json with",len(claims),"claims and",len(artifacts),"permanent hashed artifacts")
