"""The independent reviewer's authored judgment, with live evidence hashes."""
import hashlib
import json
from pathlib import Path

ROOT=Path(__file__).resolve().parents[5]
OUT=Path(__file__).resolve().parent
DOC="docs/natural-assistant/v4/STUDENT.md"
FIG="course/figures/natural_shared_chat.svg"
def sha(path):return hashlib.sha256((ROOT/path).read_bytes()).hexdigest()
PREFIX=str(OUT.relative_to(ROOT))+"/"
E="docs/natural-assistant/evidence/v4-research/student-selected-public-ui/"
CPU=json.loads((OUT/"cpu.stdout.json").read_text())
LIB=json.loads((OUT/"probe-library-versions.json").read_text())
ENV={**CPU["environment"],**LIB}
assert sha(DOC)=="6732af69f9505ef1842c42d10eac86e60b1a54fb0c62a6c26a67798b8d1ddb7c"
assert (ROOT/DOC).read_bytes()==(OUT/"STUDENT.initial-fullfile.md").read_bytes()

artifacts=[]
def art(id,kind,path,description,**extra):
    artifacts.append(dict(id=id,kind=kind,path=path,sha256=sha(path),description=description,**extra))
art("a_raw","source_snapshot",PREFIX+"STUDENT.initial-fullfile.md","Exact initial/current complete 150-line UTF-8 guide; no normalization.")
art("a_notes","source_snapshot",PREFIX+"inspection-notes.md","My actual original-authority reading, interpretation, limitations, figure view and failures.")
for id,file in [("a_retrieval","authority-retrieval.json"),("a_threads","authority-retrieval-threads.json"),("a_extra","authority-retrieval-extra.json"),("a_command_retrieval","authority-retrieval-command.json")]:
    art(id,"source_snapshot",PREFIX+file,"Actual original HTTPS retrieval receipt; full thirdparty originals are retained only in ignored outputs.")
art("a_cpu","execution",PREFIX+"cpu.stdout.json","Personally executed bounded offline numeric, release-verifier and UI-state probe, plus original empirical record arithmetic.",command="PYTHONDONTWRITEBYTECODE=1 .venv/bin/python "+PREFIX+"cpu_probe.py > "+PREFIX+"cpu.stdout.json 2> "+PREFIX+"cpu.stderr.txt",result="Exit 0, all explicit assertions passed. Original trial records audited; injected runner tests wiring only; no real inference.",environment=ENV,stderr_path=PREFIX+"cpu.stderr.txt",stderr_sha256=sha(PREFIX+"cpu.stderr.txt"),executed_by_reviewer=True)
art("a_cpu_code","code",PREFIX+"cpu_probe.py","Actual executed CPU probe including inputs, assertions, injected callbacks and independent arithmetic.")
art("a_environment","source_snapshot",PREFIX+"probe-library-versions.json","Actual local probe library versions, distinct from delivered Python 3.12 and dependencies.")
command_output=json.loads((OUT/"command-contract.stdout.json").read_text())
art("a_command","execution",PREFIX+"command-contract.stdout.json","Actual PEP 440 local-version comparison and git version check; no installation.",command="PYTHONDONTWRITEBYTECODE=1 .venv/bin/python "+PREFIX+"command_contract_probe.py > "+PREFIX+"command-contract.stdout.json 2> "+PREFIX+"command-contract.stderr.txt",result="Exit 0. ==2.8.0 accepts both 2.8.0+cpu and 2.8.0+cu128; git 2.52.0.",environment=command_output["environment"],stderr_path=PREFIX+"command-contract.stderr.txt",stderr_sha256=sha(PREFIX+"command-contract.stderr.txt"),executed_by_reviewer=True)
art("a_command_code","code",PREFIX+"command_contract_probe.py","Executed small comparison probe.")
art("a_browser","execution",PREFIX+"browser-inspection.json","Personally executed actual Chromium guide navigation and prerequisite SVG rendering, with current-byte provenance.",command=".venv/bin/python "+PREFIX+"browser_inspect.py > "+PREFIX+"browser.stdout.txt 2> "+PREFIX+"browser.stderr.txt",result="Exit 0. Actual root/guide/20.1 visited, seven guide sections read through EOF; actual referenced SVG retrieved and rendered. Screenshots personally viewed with view_image.",environment={"python":"3.13.5","browser":"Chromium 151.0.7922.173","playwright":"1.63.0","device":"cpu"},stderr_path=PREFIX+"browser.stderr.txt",stderr_sha256=sha(PREFIX+"browser.stderr.txt"),executed_by_reviewer=True)
art("a_browser_code","code",PREFIX+"browser_inspect.py","Actual final browser script. The raw source read precedes browser inspection; hashes/HTTP are provenance only.")
art("a_browser_visible","source_snapshot",PREFIX+"browser-guide-visible.txt","Actual visible article inner text, personally read from opening through all seven sections and EOF.")
art("a_browser_top","source_snapshot",PREFIX+"browser-guide-top.png","Actual browser guide top screenshot, personally viewed.")
art("a_browser_table","source_snapshot",PREFIX+"browser-guide-measurements.png","Actual browser guide measurement table screenshot, personally viewed and compared with source and arithmetic.")
art("a_figure","figure_render",PREFIX+"natural_shared_chat.render.png","Current prerequisite SVG rendered in Chromium and personally view_image-inspected: typed input bypasses ASR, spoken transcript joins shared history, photo enters core, output is text.",source_path=FIG,source_sha256=sha(FIG),render_command="Chromium render of personally retrieved current SVG bytes in browser_inspect.py",view_method="functions tools.view_image; direct personal inspection",viewed_by_reviewer=True)
for id,file,desc in [("a_trial","actual-ui/report.json","Original recorded CPU startup/workflow timing/configuration; read and audited, not re-executed by this reviewer."),("a_trial_browser","actual-ui/browser/report.json","Original real Chromium routes, per-chat and initial-ASR timing/input responses; record audit only."),("a_observer","actual-ui/observer.jsonl","Original unchanged-call observer; server-only RUSAGE_SELF, actual model load counts, history/reset state."),("a_original_disk","actual-ui/disk-observation.json","Original disk accounting, distinct allocated bytes and payload/snapshot bytes."),("a_anonymous","anonymous-fetch/receipt.json","Original anonymous small-public-file list/fetch/verify operation; not a new network download by this reviewer.")]:
    art(id,"source_snapshot",E+file,desc)
art("a_cache","source_snapshot","docs/natural-assistant/evidence/v4-research/student-local-cache-prepare/cache-prepare-receipt.json","Original exact two snapshot inventories. Independently summed all 23 file sizes; not new model-weight retrieval.")
for id,file,description in [("a_browser_failure1","browser-first-failure.raw.stderr.txt","Actual first hidden-sidebar click timeout preserved from tool output."),("a_browser_failure2","browser-second-failure.stderr.txt","Actual exported-page h2 locator timeout; correct page is h1."),("a_browser_failure3","browser-third-failure.stderr.txt","Actual standalone SVG full-page screenshot timeout."),("a_cpu_failure1","cpu-first-failure.stderr.txt","Actual first probe error reading call_count from a directly injected function."),("a_write_failure","evidence-write-failure.txt","Actual atomic evidence-only patch failure and corrected hunk order.")]:
    art(id,"source_snapshot",PREFIX+file,description)

retrieval={}
for file in ["authority-retrieval.json","authority-retrieval-threads.json","authority-retrieval-extra.json","authority-retrieval-command.json"]:
    for r in json.loads((OUT/file).read_text()):retrieval[r["id"]]=r
sources=[]
def original(id,key,kind,title,version,authority,inspection):
    r=retrieval[key]
    assert r["status_code"]==200
    sources.append(dict(id=id,kind=kind,title=title,url=r["url"],version=version,verified=True,checked_original=True,accessed_on=r["accessed_on"][:10],authority_reason=authority,inspection_note=inspection,retrieval_sha256=r["sha256"],retrieval_bytes=r["bytes"],ignored_original_path=r["path"]))
original("s_git_clone","git-clone","official_docs","Git clone manual","current original page: last changed 2.54.0; inspected 2026-10-04","Git project's original command reference","OPTIONS --no-checkout, readable lines 576–580; cloning does not check out HEAD. No clone performed.")
original("s_git_checkout","git-checkout","official_docs","Git checkout manual","current original page: last changed 2.55.0; inspected 2026-10-04","Git project's original command reference","--detach [<branch>] / <commit>, readable lines 470–494 and 777–786; HEAD points at the fixed commit.")
original("s_lfs","git-lfs","official_source","Git LFS skip-smudge configuration","Git LFS v3.7.1 docs/man/git-lfs-config.adoc","Original Git LFS repository","Lines 396–403: GIT_LFS_SKIP_SMUDGE=1 skips LFS pointer expansion in smudge/filter-process; does not skip ordinary Git objects.")
original("s_venv","python-venv","official_docs","Python venv","Python 3.12.15 documentation, last updated Oct 1 2026","CPython original library reference","Introduction, Creating virtual environments, How venvs work: readable lines 55–89,105–161,246–260,284–355. Separate default package sets, POSIX bin path and explicit interpreter do not require activation.")
original("s_pytorch_install","pytorch-install","official_docs","PyTorch previous version installation table","v2.8.0 subsection of official page retrieved 2026-10-04","PyTorch's original version-specific installation table","v2.8.0 → Wheel → Linux and Windows, readable lines 180–194: torch 2.8.0/torchvision 0.23.0, CPU and CUDA 12.8 indexes. Hardware driver/memory still conditional.")
original("s_torch_cuda","torch-cuda","official_source","PyTorch CUDA availability and bfloat16 support","PyTorch v2.8.0 torch/cuda/__init__.py","PyTorch project's tagged original implementation","is_available lines 163–182; is_bf16_supported lines185–216, includes emulation by default. Valid capability checks; no latency/capacity guarantee.")
original("s_intra","set_num_threads","official_docs","PyTorch set_num_threads","PyTorch 2.8 API docs","Original versioned PyTorch API reference","API description sets intra-op CPU parallelism; must be configured before eager/JIT/autograd work. Supports the original run's 5-thread setting, not proof every operation used all 5.")
original("s_inter","set_num_interop_threads","official_docs","PyTorch set_num_interop_threads","PyTorch 2.8 API docs","Original versioned PyTorch API reference","API description sets CPU inter-op parallelism, e.g. JIT; once only before work. Original observer config sets 1.")
original("s_nvidia","nvidia-smi","official_docs","NVIDIA System Management Interface","Original unversioned manual retrieved 2026-10-04","NVIDIA's own utility manual","SUMMARY OPTIONS readable41–45 and GPU ATTRIBUTES readable521–546 list connected GPUs/driver versions and distinguish driver-supported CUDA from installed toolkit. No device was run here.")
original("s_qwen","qwen-card","official_docs","Qwen3-VL-2B-Instruct original model card","revision 89644892e4d85e24eaac8bacfd4f463576704203","Qwen's official pinned weight repository","README lines11–18,53,77–130: model identity, common image/text messages, decoded text. Did not adopt its benchmark marketing or mutable source-install recommendation.")
original("s_whisper","whisper-card","official_docs","Whisper-large-v3-turbo original model card","revision 41f01f3fe87f28c78e2fbf8b568835947dd65ed9","OpenAI's official pinned weight repository","README Usage, lines111–179 and206–231: ASR transcript and known-language/transcribe versus translate task. CPU placement and explicit Chinese setting are separately checked in project code.")
original("s_hf_download","hf-download","official_source","HF Hub cache/download implementation","huggingface_hub v0.36.2 file_download.py","Original version-tagged HF Hub repository","hf_hub_download API lines817–832,906–913; cached-file/missing-cache behavior1092–1121; offline metadata branch1517–1548. Original commit revision and local_files_only semantics actually read.")
original("s_hf_headers","hf-headers","official_source","HF Hub authentication-header implementation","huggingface_hub v0.36.2 utils/_headers.py","Original version-tagged HF Hub repository","build_hf_headers lines55–84: token=False suppresses authorization. Actual project fetch uses token=False.")
original("s_transformers","transformers-modeling","official_source","Transformers pretrained model loader","Transformers v4.57.6 modeling_utils.py","Original version-tagged Transformers repository","from_pretrained lines4384–4412,4472–4481,4508–4532: evaluation/pretrained loading, commit revision, local files only, explicit dtype. Does not establish model accuracy or sufficient memory.")
original("s_hashlib","python-hashlib","official_docs","Python hashlib","Python 3.12.15 documentation","CPython original library reference","Usage and Hash objects: byte input/update concatenation and digest/hexdigest. Supports full file-content fingerprint; no quality conclusion.")
original("s_loopback","rfc1122","official_docs","Requirements for Internet Hosts — Communication Layers","RFC 1122, October 1989","Original RFC Editor publication","Section3.2.1.3(g), rawtext1783–1786: 127/8 internal host loopback, must not appear outside a host. Hence phone loopback does not address desktop.")
original("s_versions","version-specifiers","official_docs","Python packaging version specifiers","Current PyPA version-specifier specification retrieved 2026-10-04","Python Packaging Authority's original normative specification","Version matching, readable1148–1157: when specifier is public, ignore candidate local label. Applied to torch==2.8.0 accepting CPU/CUDA local builds; independently executed with packaging26.3.")
for id,path,title,note in [
    ("s_manifest","docs/natural-assistant/v4/public-release.json","Selected public release manifest","Read complete file: base-only, adapter_parameters0, immutable model and project pins, 2 allowed public files, runtime/dependency limits."),
    ("s_requirements","requirements-natural.txt","Natural assistant dependency pins","Read complete file. Python3.12 separate route; matched exact dependency versions and manifest SHA; fixed checkout bytes identical."),
    ("s_fetch","scripts/fetch_natural_release.py","Actual release CLI, verifier and options","Read validate_manifest88–187, verify_provenance287–320, verify_release323–349, fetch_release352–376, check_runtime379–404, student_options407–433, main436–497. Independently exercised applicable paths offline."),
    ("s_core","tiny_perceptron/natural_assistant.py","Actual common core and ASR functions","Read messages_for/encode_messages118–154, load_core263–306, generate315–341, load_asr687–698, transcribe701 onward. Same selected core gets text/history/images; separate CPU ASR; dtype/pins/cache passed to pretrained loaders."),
    ("s_ui","tiny_perceptron/natural_ui.py","Actual upload, session and UI implementation","Read constants25–35, upload_contents38–93, NaturalServer96–213, create_server317–335, serve338–352 and PAGE355–end. Lazy ASR, edited prompts, retained images, reset/close cleanup; DOM labels match guide."),
    ("s_lfs_attributes",".gitattributes","Project training archive LFS attributes","Read complete file. /assets/training/*.tar.gz uses filter=lfs, consistent with skip-smudge instruction."),
    ("s_observer_code",E+"executed-harness/ui_observer.py.source.txt","Original server measurement observer","Read full137-line source. Sets intraop5/interop1; original callbacks delegated unchanged; RUSAGE_SELF at exit is server-only."),
    ("s_trial_code",E+"executed-harness/run_ui_smoke.py.source.txt","Original CPU operation runner/timers","Read required runner/control/timing scopes: lines1–110,199–277,345–403. Starts timer before subprocess launch, readiness after UI served; ends after shutdown; distinct RUSAGE_CHILDREN vs server observer."),
    ("s_browser_trial_code",E+"executed-harness/browser_ui_client.py.source.txt","Original Chromium operation/timers","Read lines30–35,66–194. chat timer encompasses click/response/settled DOM; ASR timer includes lazy load; real controls edit prompt and reset. No benchmark scoring."),
]:
    sources.append(dict(id=id,kind="repository_code",title=title,path=path,sha256=sha(path),version="current source bytes personally checked; operation harness is preserved original executed source" if "executed-harness" in path else "current bytes; relevant product files equal fixed 59a1eda4ed7b6e8609892ec2b9013c821ac93e69 checkout",verified=True,inspection_note=note))
sources.append(dict(id="s_record_audit",kind="execution",title="Personally executed arithmetic/state probes and original operation-record audit",artifact_id="a_cpu",verified=True,inspection_note="Actual bounded offline execution in current 3.13.5/2.14.1+cpu. Original primary records a_trial/a_trial_browser/a_observer/a_cache/a_anonymous were read and independently recomputed; not a new real-model or GPU run."))
sources.append(dict(id="s_task_reasoning",kind="derivation",title="Task-completion and resource distinctions",verified=True,details="A verbatim request requires every requested character, so knowing one name cannot entail complete transcription. A summary may paraphrase and therefore has a different target. Identical submitted requests need equivalent requirement satisfaction, not identical wording. File hashing compares bytes; a UI connection proves routing, not semantic quality. Storage payload excludes runtime states and workspaces, so file bytes cannot logically establish a minimum RAM/VRAM capacity. No numeric model-quality theorem is inferred."))

def evidence(source,locator,supports):return {"source_id":source,"locator":locator,"supports":supports}
def claim(id,kind,statement,location,evidences,artifact_ids,scope,verification=None):
    c=dict(id=id,kind=kind,statement=statement,location=location,status="verified",evidence=evidences,artifact_ids=artifact_ids,scope=scope)
    if verification is not None:c["verification"]=verification
    return c
claims=[
claim("c_architecture","concept","Selected product uses Qwen3-VL-2B-Instruct for text and images plus separate Whisper-large-v3-turbo transcription; no added adapter, and replies are text.","STUDENT lines3–7,79,138–140",[evidence("s_qwen","pinned README77–130","Official image/text common model → decoded text"),evidence("s_whisper","pinned README Usage and transcription task206–231","Separate ASR produces transcript"),evidence("s_manifest","selected_variant, adapter_parameters, base_model/asr_model","Actual chosen no-adapter model pins"),evidence("s_core","load_core263–306 and load_asr687–698","Full pinned pretrained core and independent ASR")],["a_cpu","a_figure"],"Project selected base-only route; official upstream broad capability/benchmark claims are not endorsed. No TTS component or new fine-tuning success is implied."),
claim("c_checkout","software","The Linux Git command sequence avoids initial checkout/LFS training archive expansion and checks out the fixed program/manifest revision.","STUDENT lines11–22",[evidence("s_git_clone","OPTIONS --no-checkout","No initial HEAD checkout"),evidence("s_git_checkout","--detach <commit>","Commit checkout without a branch"),evidence("s_lfs","git-lfs-config.adoc396–403","Skip smudge on checkout"),evidence("s_lfs_attributes","/assets/training/*.tar.gz filter=lfs","Training archives are LFS"),evidence("s_fetch","current vs pinned full-file bytes","Guide revision's actual software binding")],["a_cpu","a_command"],"Git/clone installation and a new clone were not executed. Existing objects were read using git show; byte equality of script/core/UI/requirements/manifest was asserted. Ordinary Git objects are still acquired."),
claim("c_environment","software","A separate Python3.12 venv and explicitly named POSIX interpreter isolate the assistant dependency set; the product enforces Python3.12 and exact package/code pins.","STUDENT lines11–20,26–39,46–48",[evidence("s_venv","Creating virtual environments and How venvs work","Separate environment and full interpreter path"),evidence("s_requirements","complete pinned requirements","Separate actual dependency set"),evidence("s_fetch","check_runtime379–404","Runtime and exact SHA/package enforcement")],["a_cpu","a_environment"],"Installation commands were not run. Current .venv3.13.5 correctly rejects the3.12 product guard. Distro Python3.12/venv availability remains the documented user prerequisite."),
claim("c_torch_install","software","Torch2.8.0/torchvision0.23.0 CPU and cu128 install options match the original official table; GPU availability/bfloat16 tests correspond to the default CUDA dtype and float16 fallback.","STUDENT lines38–51,100–104,118–124",[evidence("s_pytorch_install","v2.8.0 Linux and Windows CPU/CUDA12.8","Exact version/index pair"),evidence("s_torch_cuda","is_available163–182, is_bf16_supported185–216","Capability boolean checks, including emulation by default"),evidence("s_nvidia","SUMMARY OPTIONS/GPU ATTRIBUTES","GPU/driver visibility"),evidence("s_versions","Version matching public-version equality1148–1157","Requirements preserve accepted local CPU/cu128 build labels"),evidence("s_fetch","student_options407–433, main483–486","CPUfloat32/CUDAbfloat16/float16 and checks")],["a_cpu","a_command"],"No GPU, installation or CUDA execution was performed. Both booleans True do not guarantee sufficient memory or fast execution; guide explicitly requires each NVIDIA setup to be checked on its own equipment."),
claim("c_resources","concept","Full core weights are loaded for both routes, while ASR remains on CPU; storage byte counts alone omit runtime states and cannot specify minimum RAM/VRAM. Intra-op5/inter-op1 are the recorded settings.","STUDENT lines53–55,67–69,124",[evidence("s_transformers","from_pretrained4384–4412,dtype4508–4532","Pretrained/dtype loading contract"),evidence("s_core","load_core263–306/load_asr687–698","Full core to selected device; ASR stays CPUfloat32"),evidence("s_intra","torch.set_num_threads API","Intra-op configuration"),evidence("s_inter","torch.set_num_interop_threads API","Inter-op configuration"),evidence("s_observer_code","top-level settings and RUSAGE_SELF","Actual run configuration"),evidence("s_task_reasoning","storage/runtime distinction","No memory-minimum conclusion from file bytes")],["a_observer","a_cpu"],"Thread settings are not measurements of actual per-operation utilization. One core plus separate ASR, activations/images/history/workspace; no minimum-device requirement is asserted."),
claim("c_capacity_record","empirical","Original recorded payload is2 public files totaling9,262bytes, two official snapshots with23 files totaling5,889,111,977bytes≈5.4847GiB, and server peak13,496,104KiB≈12.8709GiB.","STUDENT table lines59–61",[evidence("s_manifest","files[0:2].bytes","8722+540 public payload"),evidence("s_record_audit","a_cache.prepared_snapshots[*].files; a_observer.process_resources; a_trial.server_cpu_resources","Original snapshot inventory and server-only maximum RSS independently summed/compared")],["a_cpu","a_cache","a_original_disk","a_observer","a_trial"],"Original record audit only: one Linux CPU service, existing pinned model cache; excludes Python/browser and unrelated caches. Actual filesystem allocated bytes differ from payload bytes. Not new model retrieval or memory measurement.",{"method":"executed","expected":{"public_files":2,"public_bytes":9262,"snapshot_files":23,"snapshot_bytes":5889111977,"snapshot_GiB":5.4847,"server_peak_KiB":13496104,"server_peak_GiB":12.8709},"observed":{k:CPU["record_audit_recalculation"][k] for k in ["public_files","public_bytes","snapshot_files","snapshot_bytes","snapshot_GiB","server_peak_KiB","server_peak_GiB"]},"tolerance":"Exact integer totals; GiB rounded to4 decimals as printed.","details":"Sum every listed snapshot file, divide bytes by1024^3; convert KiB toGiB by1024^2; compare server-only observer to record.","denominators":{"original_cpu_workflows":1,"public_files":2,"official_snapshots":2,"snapshot_files":23,"model_server_processes":1}}),
claim("c_timing_record","empirical","Original recorded startup24.24s, four browser chats3.42/42.87/36.58/37.11s, initial transcription18.03s, complete launch-through-shutdown workflow170.33s agree with the guide.","STUDENT table lines62–67",[evidence("s_trial_code","started199,ready268,finally371","Overall and readiness timing boundaries"),evidence("s_browser_trial_code","chat77–94,ASR114–128","Browser waiting periods; ASR includes first load"),evidence("s_record_audit","a_trial.ready_seconds/wall_seconds; a_trial_browser.chat_seconds/asr_seconds_including_load","Actual recorded values independently rounded")],["a_cpu","a_trial","a_trial_browser","a_observer"],"Record audit only. Existing model cache; CPUfloat32, intraop5/inter-op1, max_pixels524288, total-token budget2048,new-token cap384. One photo and one AISHELL read recording, not quality-scored. No hardware-wide or per-answer latency guarantee.",{"method":"executed","expected":{"ready_seconds":24.24,"chat_seconds":[3.42,42.87,36.58,37.11],"first_asr_seconds":18.03,"workflow_seconds":170.33},"observed":{k:CPU["record_audit_recalculation"][k] for k in ["ready_seconds","chat_seconds","first_asr_seconds","workflow_seconds"]},"tolerance":"Original monotonic second values rounded to0.01s exactly match printed values.","details":"Browser chat timers end after response/settled rendered output; ASR first includes model load; overall timer ends after close. Did not replace workflow time with sum of generation times.","denominators":{"original_linux_cpu_workflows":1,"chat_requests":4,"transcribe_requests":1,"input_photos":1,"input_recordings":1,"reset_requests":1,"core_loads":1,"asr_loads":1,"warmup_runs":0,"manifest_configured_seed":42}}),
claim("c_manifest_fetch","software","--list displays fixed model pins without downloading; base release downloads/verifies only two small public files, authenticates anonymously, checks complete SHA/size, and creates the final directory after complete verification.","STUDENT lines75–88",[evidence("s_manifest","selected_variant/base_model/asr_model/files","Exact selected pair and two-file allowlist"),evidence("s_fetch","sha25651–56,verify_release323–349,fetch_release352–376,main454–466","List early return, full digest/size, staging-to-final rename"),evidence("s_hf_headers","build_hf_headers55–84","token=False suppresses authentication"),evidence("s_hashlib","Usage/Hash objects","Digest of all content bytes")],["a_cpu","a_anonymous"],"Personally executed actual --list and offline fixture verifier. Original anonymous download receipt audited; no new guide download command/model-weight download was run. File matching is not answer-quality verification."),
claim("c_retry_integrity","software","Interrupted staged fetching is retryable; existing final directories are preserved/rejected, and --verify rejects changed, missing or extra files including user uploads.","STUDENT lines88–90,148",[evidence("s_fetch","verify_release323–349,fetch_release352–376","Temporary-directory staging, final existence guard, exact file-set/hash checks")],["a_cpu"],"Existing-directory/extras/corruption checks actually exercised with small copied original public fixtures. Fresh network interruption was not generated. Verification never edits manifest hashes or deletes an existing final release."),
claim("c_startup_lazy","software","--serve verifies release/runtime then loads the pinned common core; ASR is loaded only at first transcription. CPU usesfloat32 and CUDA defaults tobfloat16 with explicit float16 option.","STUDENT lines94–106,118–122",[evidence("s_fetch","student_options407–433,main466–489","Verify/runtime/device/dtype/serve ordering"),evidence("s_core","load_core263–306/load_asr687–698","Pinned processor/core/ASR loaders"),evidence("s_ui","operation168–175,serve338–352","On-demand ASR vs immediate core startup"),evidence("s_hf_download","hf_hub_download/cache contract","Same revision cache can be reused")],["a_cpu","a_trial","a_observer"],"Actual options/lazy-state tests use injected model callbacks. Original one core/one ASR loads audited. No new real-model startup, download or NVIDIA route was executed."),
claim("c_loopback","concept","127.0.0.1:8766 reaches the running service on that host; a phone's loopback points at the phone, and a static course site is a separate service.","STUDENT lines108–114",[evidence("s_loopback","RFC1122§3.2.1.3(g)","127/8 internal host address"),evidence("s_ui","create_server317–335/serve338–352","Loopback-only default port8766 and active process lifecycle")],["a_browser","a_cpu"],"Loopback semantics on the same machine; no remote/mobile network publication or production service claim. Browser inspection is the separate course preview at8782, not a newly started model service at8766."),
claim("c_upload_limits","numeric","Upload byte cap is8MiB=8,388,608bytes≈8.39decimalMB; image cap16,000,000pixels and audio cap30s. Float32 elements occupy32bits andfloat16 elements16bits.","STUDENT lines55,124,128,136",[evidence("s_ui","constants25–35/upload_contents38–93","8*1024^2,16million pixels and frame/rate ≤30"),evidence("s_record_audit","actual WAV boundary and tensor element_size probes","30s accepted,30s+1sample rejected; element size measured")],["a_cpu"],"Actual bounded16kHz WAV and small tensor probes; no oversized image allocation or model inference. 8MiB is binary storage,8.39MB is decimal rounded conversion.",{"method":"executed","expected":{"8_MiB_bytes":8388608,"8_MiB_decimal_MB":8.39,"float32_element_bits":32,"float16_element_bits":16,"audio_480000_at16000":"accepted","audio_480001_at16000":"rejected"},"observed":{"8_MiB_bytes":CPU["record_audit_recalculation"]["8_MiB_bytes"],"8_MiB_decimal_MB":CPU["record_audit_recalculation"]["8_MiB_decimal_MB"],"float32_element_bits":32,"float16_element_bits":16,"audio_480000_at16000":"accepted","audio_480001_at16000":"rejected"},"tolerance":"Exact byte/bit/sample boundary; decimalMB rounded to2 places.","details":"8*1024^2/10^6; actual element_size()*8;480000/16000=30 and480001/16000=30.0000625. Pixel limit read in original actual code."}),
claim("c_upload_formats","software","UI accepts PNG/JPEG/WebP only as a single static image, and WAV/FLAC/MP3/OGG audio subject to readable content checks.","STUDENT lines128,136,148",[evidence("s_ui","IMAGE_TYPES/AUDIO_TYPES34–35,upload_contents38–93","Allowed suffix/actual image format/frame/content and audio information checks"),evidence("s_core","transcribe701–716","Downmix/resample processing and bounded waveform")],["a_cpu"],"Actual small staticPNG/JPEG/WebP accepted; animatedWebP rejected; WAV actually decoded. FLAC/MP3/OGG support read in original allowlist; codec/system differences remain as documented, not all newly decoded here."),
claim("c_history_transcript","software","Photo/history persist across follow-up turns; transcription alone does not ask the core for an answer, and submission uses edited text while preserving a separate original transcript.","STUDENT lines126–140",[evidence("s_ui","NaturalServer.operation168–213 and PAGE transcript/send handlers","Lazy ASR produces record; edited prompt and original are separate; history retains image"),evidence("s_core","messages_for118–138/encode_messages140–154","Historical images and current question enter same common core")],["a_cpu","a_trial_browser","a_observer"],"Direct actual session operations with explicit injected callbacks, plus original actual-browser record audit. The example我不吃辣→我吃辣 illustrates a possible error, not a measured transcript of that sentence."),
claim("c_cleanup_offline","software","New dialogue clears history/uploads; graceful Ctrl+C closes the server and deletes session uploads while keeping caches. --local-files-only passes to both model routes and missing files do not trigger download.","STUDENT lines132,144–148",[evidence("s_ui","reset150–154,server_close113–115,serve347–352","Reset and graceful close cleanup"),evidence("s_fetch","student_options407–433/serve verify path","Offline option propagates after local release verification"),evidence("s_core","load_core269–280/load_asr690–698","Same local-files-only option for core/processor/ASR"),evidence("s_hf_download","cache branch1092–1121/offline1517–1548","Offline missing-cache failure"),evidence("s_transformers","from_pretrained local_files_only4472–4474","Model loader only looks locally")],["a_cpu","a_observer"],"Actual reset/server_close delete temporary files; current-HF1.33 offline-missing probe makes0 network calls. PinnedHF0.36.2 source independently read. Graceful documented shutdown, not power loss/SIGKILL; cache files remain outside upload directory."),
claim("c_task_limits","concept","Verbatim reading, summary and stage-specific ASR/chat completion require different checks; one UI smoke and file hash do not establish general answer accuracy or minimum equipment needs.","STUDENT lines67–69,130,138–140,146–150",[evidence("s_task_reasoning","complete task/metric and storage derivation","Different targets, stages and evidence implications"),evidence("s_record_audit","one-workflow original scope and requests","Operation fixture has no answer scoring or quality denominator")],["a_notes","a_trial","a_trial_browser"],"20.13 capability card read only for guide context; its entire benchmark was not rerun/regraded here. No unrestricted OCR, long spontaneous speech/chat, cross-platform or universal latency/capacity conclusion."),
claim("c_browser_document","software","Actual executed preview shows the complete current guide and its20.1 link opens the intended prerequisite section; necessary shared-chat SVG matches current bytes and text.","STUDENT complete document/line7 link; prerequisite20.1 SVG",[],["a_browser","a_browser_visible","a_browser_top","a_browser_table","a_figure","a_raw"],"Actual Chromium interaction/read/view, not HTTP alone. Guide bytes exactly match literal307c325; older preview does not establish later10.8/11.2 revision content. Navigation locations of other links were observed but not all clicked. Reading-time metadata unfinalized; no publication approval."),
]
report={
    "schema_version":1,"review_stage":"technical","review_type":"supplemental_whole_document_factual",
    "source":DOC,"source_sha256":sha(DOC),
    "reviewer_task":"/root/v4_review_coordinator/factual_guide_student","reviewer_context":"fresh",
    "assigned_document_scope":"Exactly docs/natural-assistant/v4/STUDENT.md, complete150 lines from heading/opening toEOF; linked necessary20.1/20.3/20.13 read for context, not substituted for another whole-document assignment.",
    "complete_documents":[{"path":DOC,"sha256":sha(DOC),"bytes":len((ROOT/DOC).read_bytes()),"lines":len((ROOT/DOC).read_bytes().splitlines()),"read_scope":"All150 lines personally read in current raw source; complete visible article throughEOF personally read in actual Chromium."}],
    "current_document_sha256":{DOC:sha(DOC)},"figure_sha256":{FIG:sha(FIG)},
    "source_read_order":[{"scope":"outputs/natural-v4/review-plan/supplemental-factual-contract.md and docs/technical-review-guide.md","method":"Complete contract/role/schema reading; no old reports."},{"scope":DOC,"method":"Complete numbered rawsource output lines1–150 and rawbytes snapshot."},{"scope":"requirements-natural.txt, v4/public-release.json, current fetch/core/UI functions named in sources","method":"Actual source reading plus immutable checkout comparison."},{"scope":"course/chapters/20.md#20.1,#20.3,#20.13;20.1 SVG","method":"Actual complete linked subsection text, SVG source and later personal rendered view; other subsection metrics are context only."},{"scope":"Original selected-public-ui operation/browser/observer/disk/anonymous records and corresponding actual harness; local-cache-prepare snapshot inventory","method":"Direct reading of required fields/configuration/timing code followed by independent recomputation; no previous factual/reader report or author conclusion consulted."},{"scope":"Original official sources enumerated with locators/versions/retrievalSHA","method":"Personally read necessary original model cards/docs/source/API contracts; full downloads stay ignored."},{"scope":"Actual http://127.0.0.1:8782/natural-v4-student.html and20.1 browser click","method":"Actual Chromium rendered reading and personal screenshot/SVG view, tied to current-byte provenance."}],
    "prerequisites_read":[{"source":"course/chapters/20.md#20.1","scope":"Complete subsection; common chat/ASR/input diagram"},{"source":"course/chapters/20.md#20.3","scope":"Complete subsection; weights versus runtime footprint distinction; no extra benchmark replication"},{"source":"course/chapters/20.md#20.13","scope":"Complete subsection; capability limits/context only; metrics not regraded as part of this guide review"}],
    "applicability":{"substantive_claims":True,"reason":"Complete operating guide includes installation/serve/verify/offline commands, upload limits, architecture and empirical measurements; whole-document NA is inappropriate."},
    "claims":claims,"sources":sources,"artifacts":artifacts,"issues":[],
    "checks":{
        "factual_accuracy":{"status":"pass","details":"All17 substantive grouped guide claims checked in original authorities/code/records. Selected architecture, command contracts, UI state and task limits agree. Pure navigation sentences were not individually duplicated.","claim_ids":[c["id"] for c in claims]},
        "numeric_verification":{"status":"pass","details":"Actually recomputed all table counts/conversions/roundedtimes;8MiB and float element bits; meaningful30s boundary probe. Empirical records have explicit denominator dicts and single-run configuration. This was record arithmetic, not newly measured model latency.","claim_ids":["c_capacity_record","c_timing_record","c_upload_limits"]},
        "figure_consistency":{"status":"pass","details":"Guide has no directly embeddedSVG. Necessary20.1 natural_shared_chat.svg was personally raw-read, actual-preview-retrieved, byte-compared, Chromium-rendered and view_image-inspected. Arrows/image merge/textoutput/optional correction match the contextual route; selected guide is base-only.","claim_ids":["c_architecture","c_browser_document"]},
        "source_verification":{"status":"pass","details":"Original official pinned/versioned APIs/model cards, Git/Python/PyTorch/PyPA/NVIDIA/RFC originals were actually read at recorded locators. TLS/checksums retained; URLs/date/versions/retrievalSHA saved. Original empirical files/harness inspected directly; candidate summaries/old reviews did not serve as authority.","claim_ids":[c["id"] for c in claims if c["evidence"]]},
        "limitations":{"status":"pass","details":"Guide and report retain oneLinuxCPU-existingcache scope, storage versus memory, incompleteGPU/cross-platform checks, operation versus quality, original/edited transcript and graceful/offline conditions. Actual probe uses3.13.5/Torch2.14.1+cpu and newerHF/Pillow/SoundFile; deliveredpinnedruntime source and priorrecords checked separately. No new heavy download/install/realinference/GPU/training/fullbenchmarkrun.","claim_ids":[c["id"] for c in claims]},
    },
    "verdict":"pass","remaining_issues":[],
    "execution_limits":{"personally_executed":"Bounded offline CPUsoftware/numeric probes; actual Chromium course-preview reading/navigation/SVG render and personal view_image.","original_empirical_workflow":"Records only:1 LinuxCPU float32 workflow,4 chat requests,1 ASR request,existingtwoofficialsnapshots,5 intraop/1 interop. No new latency or quality measurement by reviewer.","not_executed":"Guide installation/download/serve commands, realmodelinference,newmodels/data,GPU,longtraining,fullbenchmarkreplication.","current_environment":ENV,"preview_revision":"literal307c325","current_guide_equals_preview_revision":True,"reading_times_finalized":False,"publication_approval":False},
    "reviewer_harness_failures":[{"artifact_ids":["a_browser_failure1"],"status":"resolved","resolution":"Observed sidebar href navigated in real browser instead of clicking its hidden element; originalfirstscript preserved."},{"artifact_ids":["a_browser_failure2"],"status":"resolved","resolution":"Actual exported20.1 page usesh1; browser diagnostic confirmed correct page, then inspected actualh1."},{"artifact_ids":["a_browser_failure3"],"status":"resolved","resolution":"Current SVG bytes retrieved from actualpreview and rendered in ordinaryChromiumHTML; personally viewed successfulPNG. Originalthirdscript preserved."},{"artifact_ids":["a_cpu_failure1"],"status":"resolved","resolution":"Use mock side_effect for callcount without changing actual productpath or fixturebehavior; originalfirstCPUscript preserved."},{"artifact_ids":["a_write_failure"],"status":"resolved","resolution":"Reordered evidence-only patchhunks; no productfile mutation."}],
    "first_report_preservation":"report.initial.json is the unchanged first authored report. No assigned report existed at first inspection; no old report was read.",
}
payload=(json.dumps(report,ensure_ascii=False,indent=2)+"\n").encode()
(OUT/"report.json").write_bytes(payload)
first=OUT/"report.initial.json"
if first.exists():raise RuntimeError("Do not overwrite a first report")
first.write_bytes(payload)
print(json.dumps({"report":PREFIX+"report.json","sha256":hashlib.sha256(payload).hexdigest(),"verdict":report["verdict"],"claims":len(claims),"sources":len(sources),"artifacts":len(artifacts),"issues":len(report["issues"])}))
