from pathlib import Path
import hashlib
import json
import re
import subprocess

ROOT=Path(__file__).resolve().parents[4]
BASE=Path(__file__).resolve().parent
PREFIX=BASE.relative_to(ROOT).as_posix()
def digest(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
revision=subprocess.run(['git','rev-parse','HEAD'],cwd=ROOT,capture_output=True,text=True,check=True).stdout.strip()
raw=json.loads((BASE/'raw-audit.json').read_text())
probe=json.loads((BASE/'cpu-probe.json').read_text())
stages={r['stage_key']:r for r in raw['stage_rows']}
artifacts=[]

def artifact(identifier,path,kind,description,command=None,result=None,environment=None):
    value={'id':identifier,'kind':kind,'path':PREFIX+'/'+path,'sha256':digest(BASE/path),'description':description}
    if kind=='execution':value.update(command=command,result=result,environment=environment or probe['environment'])
    artifacts.append(value)
    return identifier

python='/workspace/tiny-perceptron-vlm/.venv/bin/python'
artifact('a_raw','raw-audit.json','execution','親自逐檔 SHA/bytes 核對十五段三種原始回執、十五份原始 inference manifest 與13條新段父 best 鏈；依原始 native metrics 重算選定步數。',python+' '+PREFIX+'/audit_raw.py > '+PREFIX+'/raw-audit.log 2>&1','exit 0；十五段 completed、十三條 parent best 鏈一致；native 完成4000、選定1000。',raw['environment'])
artifact('a_cpu','cpu-probe.json','execution','七個真實本機 wrapper 的有界合成算例；checkpoint/optimizer/RNG/sampler 精確比較、fresh reset、native來源、heads及loss權重。',python+' '+PREFIX+'/cpu_probe.py > '+PREFIX+'/cpu-probe.log 2>&1','exit 0；不中斷3步與1步後resume總計3步逐張量完全一致；fresh stage計數重建；本機native正例與四個拒絕案例成立。')
artifact('a_gate','gate-probe.json','execution','追加核對 native 架構不符及 checkpoint bytes/SHA 改變兩種來源拒絕。',python+' '+PREFIX+'/gate_probe.py > '+PREFIX+'/gate-probe.log 2>&1','exit 0；兩項均由真實 helper 拒絕，之後恢復自己的合成測試檔。')
artifact('a_contract','command-contract.json','execution','原稿兩個完整 shell recipe 的確切 CLI 解析、manifest pin 與 uv 版本；不執行全量訓練。',python+' '+PREFIX+'/command_contract.py > '+PREFIX+'/command-contract.log 2>&1','exit 0；兩個原命令均可用無縮寫 parser 解析；64字元 manifest SHA完全相等。')
artifact('a_notebook','notebook-cwd-probe.json','execution','從 notebooks/19 工作目錄原樣執行本節 Python fence，只讀指定 JSON pointers。',python+' '+PREFIX+'/notebook_cwd_probe.py > '+PREFIX+'/notebook-cwd-probe.log 2>&1','exit 0；七行輸出與教材相同；最後為 moe-native 完成 4000 選定 1000。',{'python':probe['environment']['python'],'device':'cpu / JSON-only','cwd':'notebooks/19'})
artifact('a_public','publication-audit.json','execution','核對原始公開發布 execution、outer receipt 與 hf-receipt 的來源 SHA，保存原件。',python+' '+PREFIX+'/audit_publication.py > '+PREFIX+'/publication-audit.log 2>&1','exit 0；公開提交979cdfacc588ad0536f1c64fff96f264571cf054的MoE取native best、Dense取weighted best，與原訓練run及receipt SHA相符。',{'python':probe['environment']['python'],'device':'cpu / existing receipts only'})
artifact('a_history','historical-source-audit.json','execution','從每個原始 execution.revision 取得真正歷史trainer，AST定位必要目標、凍結及驗證分支。',python+' '+PREFIX+'/historical_audit.py > '+PREFIX+'/historical-audit.log 2>&1','exit 0；十五個訓練版本的freeze與validation函式與親讀現碼AST相同；所有原default objective與親读的07a6bc2e版相同。',{'python':probe['environment']['python'],'device':'cpu / local Git only','git_revision':revision})
artifact('a_external','external/source-provenance.json','execution','親自取得PyTorch官方原始教程與v2.11.0 autograd文件，保存HTTPS URL、版本、日期、內容定位、SHA。',python+' '+PREFIX+'/official_sources.py > '+PREFIX+'/official-sources.log 2>&1','exit 0；兩份官方原文已以預設TLS驗證取得並保存。',{'python':probe['environment']['python'],'device':'cpu / HTTPS source retrieval'})
artifact('a_render','render-svg.log','execution','使用環境既有librsvg及Cairo真正渲染本節SVG為640與360寬度。',python+' '+PREFIX+'/render_svg.py > '+PREFIX+'/render-svg.log 2>&1','exit 0；輸出640x884與360x497 PNG，均已實際view_image查看。',{'python':probe['environment']['python'],'device':'cpu','renderer':'system librsvg via Cairo','cairo':'1.18.4'})
artifact('a_figure640','lineage-640.png','figure_render','實際查看640px圖；八個MoE階段順序、箭頭、best載入及新段重建標籤與原始鏈相符。')
artifact('a_figure360','lineage-360.png','figure_render','實際查看360px圖；階段順序及箭頭未因缩放改變，沒有裁去尾段或關鍵標籤。')
artifact('a_provenance','raw-provenance.json','source_snapshot','所有原件/原始永久archive/本輪副本的完整SHA、bytes及來源路徑；未刪改或閱讀附加作者摘要。')
artifact('a_keys','json-key-inventory.json','source_snapshot','先列頂層key與型別的真實紀錄；指向後續只讀必要pointers的方法。')
artifact('a_nested_keys','raw-key-inventory.json','source_snapshot','原始inference manifest及native validation metric rows之key/type紀錄。')
for folder in ['raw','publication','historical-code','inputs','external']:
    for index,p in enumerate(sorted((BASE/folder).rglob('*'))):
        if p.is_file() and p.name!='source-provenance.json':
            relative=p.relative_to(BASE).as_posix()
            identifier='snapshot_'+folder.replace('-','_')+'_'+str(index)
            artifact(identifier,relative,'code' if p.suffix=='.py' else 'source_snapshot','保存完整原件bytes與SHA；實際讀取範圍見本報告inspection與raw-audit的pointers。'+relative)
for index,p in enumerate(sorted(BASE.glob('*.py'))):
    if p.name!='write_report.py':artifact('probe_code_'+str(index),p.name,'code','本輪實際執行的核對/渲染程式，與execution artifact中命令相對應。')
for index,p in enumerate(sorted(BASE.glob('probe-*.log'))):artifact('child_log_'+str(index),p.name,'source_snapshot','七個有界真實wrapper child之一的完整stdout/stderr；不是教材原始訓練品質。')
for name in ['raw-audit.log','cpu-probe.log','gate-probe.log','command-contract.log','notebook-cwd-probe.log','publication-audit.log','historical-audit.log','official-sources.log']:
    artifact('log_'+name.split('.')[0].replace('-','_'),name,'source_snapshot','實際命令完整輸出：'+name)

sources=[]
def code(identifier,title,path,note,version=None):
    sources.append({'id':identifier,'kind':'repository_code','title':title,'path':path,'sha256':digest(ROOT/path),'version':version or revision,'verified':True,'inspection_note':note})
code('s_train','真正使用的本機trainer契約','scripts/selftrained/train.py','AST定位後親讀84-232、284-628、631-686及689-1004：stage資料過濾、目標、trainable prefixes、sampler/RNG、init/resume、CLI與checkpoint/export。未讀舊review或作者結果摘要。')
code('s_wrapper','本機wrapper來源及回執契約','scripts/selftrained/train_local_stage.py','親讀36-85、88-115與118-251：文件bytes/SHA、best/latest、來源completed/failed、manifest管理參數、新output、真實subprocess及outer receipt。')
code('s_model','有限模態模型實際encoder/head','tiny_perceptron/selftrained/model.py','AST定位親讀25-53、133-185、188-282及295-302：隨機constructor、vision3、OCR序列及音訊完整時間輸入3-intent head、bridge。避開description結果解釋字串。')
code('s_dataset','原始資料編碼與目標損失','tiny_perceptron/selftrained/dataset.py','親讀48-91、174-235及244-271：train-only字表、assistant/pretrain next-token標籤、ROI要求、vision/audio CE與OCR字序loss。')
code('s_tokenizer','OCR字元表與tokenizer','tiny_perceptron/selftrained/tokenizer.py','AST定位頂層OCR_CHARACTERS="大小上下左右開關入出人口"，12個字元；CharacterTokenizer建構供有界weights算例使用。')
code('s_nativegate','native真正完成來源的原始gate','scripts/selftrained/modal_runner.py','AST定位親讀646-854：原始completed execution/receipt、同架構4/4/1、best+safe export SHA、selected_step、config/data/options及origin一致；不呼叫付費runner。')
code('s_base_model','文字核心從零constructor','tiny_perceptron/model.py','AST定位親讀TinyLM.__init__ 54-66：nn.Embedding、Block、norm與nn.Linear原生建構；沒有成熟權重載入。')
code('s_historical_base','原pretrain/default目標原件',PREFIX+'/historical-code/07a6bc2e2dd1b0d7ee3634a0829e2fea5a86053a/train.py','親讀objective296-322；與所有其他default-stage歷史objective完全AST相同，freeze281-293及validation326-343亦與現契約相同。','Git 07a6bc2e2dd1b0d7ee3634a0829e2fea5a86053a')
code('s_historical_weighted','原MoE weighted目標原件',PREFIX+'/historical-code/b485b3a6d085bc64b31be7077d5f23c723bf2f74/train.py','親讀numeric mask361-371、weights374-383、weighted reduction386-399及objective422-461；validation465-482是原未加語言權重分支。','Git b485b3a6d085bc64b31be7077d5f23c723bf2f74')
sources.append({'id':'s_checkpoint','kind':'official_source','title':'PyTorch官方 Saving & Loading Models 教程原文','url':'https://raw.githubusercontent.com/pytorch/tutorials/main/beginner_source/saving_loading_models.py','version':'pytorch/tutorials main fetched 2026-10-06; frozen file SHA256 '+digest(BASE/'external/saving_loading_models.py'),'verified':True,'checked_original':True,'accessed_on':'2026-10-06','authority_reason':'PyTorch官方教程repository的原始教程檔，直接說明模型與optimizer checkpoint的保存/恢復。','inspection_note':'親讀187-193及256-307：best state應保存獨立副本；resuming需要model之外的optimizer與epoch等。這份教程不自行證明本案RNG/sampler恢復，該部分另讀trainer並實跑。'})
sources.append({'id':'s_freeze','kind':'official_source','title':'PyTorch v2.11.0 Autograd mechanics 原文','url':'https://raw.githubusercontent.com/pytorch/pytorch/v2.11.0/docs/source/notes/autograd.rst','version':'PyTorch v2.11.0; frozen SHA256 '+digest(BASE/'external/autograd-v2.11.0.rst'),'verified':True,'checked_original':True,'accessed_on':'2026-10-06','authority_reason':'PyTorch官方原始碼repository的版本化autograd文件，直接定義requires_grad與凍結參數。','inspection_note':'親讀178-215：leaf parameters requires_grad=False排除梯度累積；module.requires_grad_作用於其參數。本機執行版本2.14.1+cpu；一般機制由v2.11.0權威原文支持，本專案API行為另由本機有界執行驗證，未聲稱兩版所有後端相同。'})

claims=[]
def ref(source,locator,supports):return {'source_id':source,'locator':locator,'supports':supports}
def claim(identifier,kind,statement,location,evidence,artifact_ids,scope,expected=None,observed=None,denominators=None):
    c={'id':identifier,'kind':kind,'statement':statement,'location':location,'status':'verified','evidence':evidence,'artifact_ids':artifact_ids,'scope':scope}
    if kind in ['software','numeric','empirical']:
        c['verification']={'method':'executed','expected':expected or statement,'observed':observed or '指定實際核對命令exit 0；對應artifact保有原命令、輸入、assertions及真實結果。','details':scope+' 個別來源定位與artifact保留可追溯核對。'}
        if kind=='numeric':c['verification']['tolerance']='精確相等'
        if kind=='empirical':c['verification']['denominators']=denominators
    claims.append(c)

claim('c01','concept','檢查點除了權重，可保存optimizer、步數與抽樣狀態；單靠同名權重檔不會建立接續關係。','course/chapters/19.md:161',[ref('s_checkpoint','原文256-307','支持一般checkpoint保存model/optimizer/epoch及初始化後恢復的契約。'),ref('s_train','212-232、779-804及849-878','支持本案真的另保存/恢復RNG、sampler、step及token。')],['a_cpu'],'一般checkpoint的可包含狀態；本案保存種類與exact續跑另由實作及CPU算例支持，檔名本身不是內容證据。')
claim('c02','empirical','MoE由自己的從零pretrain依序承接SFT、vision、OCR、audio、joint、weighted及native，七條新段箭頭均載入父段驗證best。','course/chapters/19.md:163、165、226、248',[ref('s_train','720-804、805-835','from-random無source分支與fresh stage父SHA記錄。'),ref('s_model','133-151、188-282、295-302','從零建立文字及感知模組。'),ref('s_base_model','TinyLM.__init__54-66','文字核心沒有成熟權重載入。')],['a_raw','a_provenance','a_history','a_figure640','a_figure360'],'八個既有MoE訓練段、同一凍結資料與seed的可追溯權重鏈。沒有重訓或重新評測；指紋链不能推出生成能力達標。',observed='8個MoE completed execution、7條新段parentSHA逐一等於父best；兩次必要history支援續跑後保留原new-stage來源。',denominators={'stages':'8','parent_edges':'7','seed':'20261006','data_split':'各段原train/validation；test_used_for_selection=false','details':'每段完成步數、選定步數、records及tokens見raw-audit.json/stage_rows'})
claim('c03','empirical','Dense保持自己的完整七段鏈並止於weighted；公開Dense由該weighted best取得，未混入MoE檢查點。','course/chapters/19.md:163、244',[],['a_raw','a_public','a_provenance'],'七個Dense原始訓練段與公開發布來源，不代表Dense通過完整生成考卷。',observed='7個Dense completed execution、6條parent best SHA一致；公開dense-joint來源gha-37438263501-1的weighted best 44391ee57a3d6374a7c6a37e1f864314f586c0b4377ad2a895212ffef5c77aaf。',denominators={'stages':'7','parent_edges':'6','seed':'20261006','publication':'979cdfacc588ad0536f1c64fff96f264571cf054','data_split':'各段原train/validation；未使用test選版'})
claim('c04','software','pretrain使用有限純文字next-token目標且只更新文字核心。','course/chapters/19.md:171',[ref('s_train','84-103、284-296及519-560','純文字stage filtering、LM-only trainable、pretrain encoder目標。'),ref('s_dataset','174-220','pretrain全內容labels向下一個token對齊。'),ref('s_historical_base','296-322','原pretrain實際採用同一分支。')],['a_cpu','a_history'],'這是本案pretrain的訓練目標，不是聊天能力的驗收；有界算例僅3次更新。',observed='pretrain trainable root只有lm；實際wrapper完成3步；label shift及stage filter已親讀。')
claim('c05','software','SFT在助理示範答案位置訓練回答及工具請求，只更新文字核心。','course/chapters/19.md:172',[ref('s_train','84-103、284-296、519-560','SFT排除圖/聲音但保留工具文字示範，LM-only trainable。'),ref('s_dataset','174-220','非pretrain只監督assistant內容與EOS；next-token對齊。')],['a_cpu','a_history'],'目標與允許更新的模組；不宣稱示範已完全學會或工具真正執行。',observed='SFT trainable root只有lm；真實fresh SFT wrapper一步成功；encoder把非assistant位置設為-100。')
claim('c06','software','vision入口從商品像素訓練三類辨識，文字核心在該段凍結。','course/chapters/19.md:173',[ref('s_model','188-214','兩個像素cell經CNN/projection得到3類head logits。'),ref('s_dataset','244-256','vision_labels在head的cross_entropy中監督。'),ref('s_train','284-296、532-551','只更新vision_encoder，感知stage不使用language labels。')],['a_cpu','a_history'],'3是實際head類別数；合成probe確認shape/trainable，不是商品辨識率。',observed='vision head.out_features=3；vision stage trainable roots=[vision_encoder]。')
claim('c07','software','OCR入口要求指定ROI，辨識12個已知字元及字序；文字核心在OCR段凍結。','course/chapters/19.md:174',[ref('s_model','217-244','固定ROI payload與順序columns/GRU/logits。'),ref('s_dataset','189-201、261-270','沒有ROI會拒絕，ocr_text字序作序列loss目標。'),ref('s_tokenizer','頂層OCR_CHARACTERS','實際12字母表。'),ref('s_train','284-296、532-551','只更新OCR入口，不監督文字輸出。')],['a_cpu','a_history'],'12是已知字元表大小，head另外包含blank，所以輸出13類；不支持開放字表OCR或未知字體外推。',observed='len(OCR_CHARACTERS)=12；OCR head=13含blank；OCR stage只更新ocr_encoder。')
claim('c08','software','audio入口保留完整声學時間序列並學三類意圖；該段凍結LM，也沒有新增逐字稿ASR目標。','course/chapters/19.md:175、180',[ref('s_model','247-282','完整[time,40]輸入、只trim声明padding，時序CNN/GRU後3類intent head。'),ref('s_dataset','256-260','監督intent_id單一類別CE，沒有transcript loss。'),ref('s_train','284-296、532-551','只更新audio_encoder且language labels=None。')],['a_cpu','a_history'],'本專案有限三意圖入口；没有一般ASR/轉寫能力的主張。',observed='audio head.out_features=3；audio stage trainable root只有audio_encoder；完整時間輸入與intent監督分支已親讀。')
claim('c09','concept','凍結指保留感知骨幹與head參數；本章joint只允許共同LM及指定感知bridge更新。','course/chapters/19.md:167、176',[ref('s_freeze','autograd.rst178-215','支持requires_grad=False作參數凍結的原理。'),ref('s_train','44-57、284-296及765-766','確切bridge prefixes、排除所有backbone/head，optimizer只接trainable參數。'),ref('s_model','188-282','區分feature backbone、打分類的head與交給LM的bridge。')],['a_cpu','a_raw','a_history'],'本章原始joint與兩個加權段均帶freeze=true；一般trainer若不加該旗標，joint可更新其他模組，原文所談的是這條成品配置。')
claim('c10','software','weighted joint對真實工具示範及指定數字run位置分別使用4與4的語言loss倍率。','course/chapters/19.md:177',[ref('s_train','380-451','工具row eligibility、数字/負號/終止位置mask、倍率相乘及加權CE質量歸一。'),ref('s_historical_weighted','361-399、422-461','原weighted訓練的實際4/4分支與還原方式。')],['a_cpu','a_raw','a_history'],'倍率作用於既有assistant targets；不是把錯誤率乘4，也不是所有驗證位置一律加權。',observed='兩個原weighted receipt的tool=4 numeric=4；CPU -12x算例真工具row每個supervised位置=16，其他row=4，ignored=0。')
claim('c11','software','MoE native的語言目標是tool4/numeric1/native4，native倍率僅給未增強的train voice_qa與voice_topic_continuation列。','course/chapters/19.md:178、189、234-238',[ref('s_train','313-347、389-396、412-451、689-711','确切系数、無augmentation key的eligibility及固定native CLI。')],['a_cpu','a_raw'],'本案有限語音問答及續聊的訓練語言位置；增強row、evaluation_only及protocol fixture排除；不支持語音逐字轉寫或品質提升的普遍结论。',observed='原native receipt=4/1/4；CPU未增強voice row權重4、有augmentation key voice row權重1；真實local native fresh一步成功。')
claim('c12','empirical','末兩個加權joint段沿用來源的模型配置、tokenizer及凍結record/asset資料，不新增成熟模型或新的ASR零件。','course/chapters/19.md:180',[],['a_raw','a_provenance'],'同一模型指架構/config與承接的權重鏈，權重值繼續學習。只改比重描述其目標差異；不表示steps、LR、eval/save interval或新段optimizer狀態全不變，這些另外在命令及表格列明。',observed='MoE joint→weighted→native及Dense joint→weighted的config/data_sha256/asset_sha256相等；tokenizer相同；原native继承weighted配置。',denominators={'comparisons':'MoE joint-weighted、MoE weighted-native、Dense joint-weighted，3個相邻比較','seed':'20261006','train_records':str(stages['moe-native']['train_records']),'validation_records':str(stages['moe-native']['validation_records']),'scope':'固定JSONL與assets SHA；不以source-selection作者說明作证据'})
claim('c13','software','驗證及best選版仍用原未加工具/數字/native倍率的teacher-forced目標，較低loss或早期best不是生成考卷通過的證據。','course/chapters/19.md:180、208',[ref('s_train','611-628、878-900','validation只傳原六個目標參數，select_and_save按该loss是否下降選best。'),ref('s_historical_base','326-343','原default validation。'),ref('s_historical_weighted','465-482','原weighted validation仍未傳language倍率。')],['a_cpu','a_raw','a_history'],'teacher-forced loss選權重的契約；沒有把此核驗當生成或能力重評，且本輪未使用heldout重新測。',observed='validation objective call恰6個位置參數，沒有加權系數；15個歷史validation AST一致；native原validation metrics選1000。')
claim('c14','software','--init-checkpoint使用自己完成父段的best；新建optimizer，以新段seed建RNG/sampler，step與token從零開始。','course/chapters/19.md:186、226',[ref('s_wrapper','52-85','只接受best且要求completed genuine local metadata及文件指紋。'),ref('s_train','719-720、762-804、805-835','載入模型、新建AdamW/sampler、零計數；fresh初始化記錄reset state。')],['a_cpu','a_raw'],'自有完整PT checkpoint的fresh stage契約；通用trainer允許其他init來源的分支，教材命令明確經更嚴格local wrapper。',observed='fresh SFT一步後step1、sampler draws2、所有optimizer step=1；hist父SHA與父best相等；latest不能作fresh來源。')
claim('c15','software','--resume使用同段latest並恢復optimizer/RNG/sampler/計數；改變原4/4目標為4/1/4不能稱精確續跑。','course/chapters/19.md:187、189、242',[ref('s_wrapper','52-85','resume只接受latest及completed/failed genuine metadata。'),ref('s_train','375-377、749-804','鎖objective/stage/config、optimizer及sampling設定，載入全部training state。')],['a_cpu'],'本機CPU有界合成三步的精確state等式，加上原始程式的求解設定锁；未推斷任何GPU跨backend逐bit保證。',observed='連續3步与1步後resume到總3步：模型、optimizer、torch RNG及sampler逐tensor相同；改4/4/1→4/1/4被拒絕；best不能冒latest。')
claim('c16','software','續跑的--steps是該段總目標步數，而非追加步數。','course/chapters/19.md:189',[ref('s_train','638、904及930','while saved step < args.steps；每更新加一。')],['a_cpu'],'總步數可高於保存step；不保證把已超過的checkpoint降回較早step，wrapper还核對完成step等於请求。',observed='prefix已1步，--resume --steps 3的最終step是3、sample draws6；沒有變成4。')
claim('c17','empirical','MoE native真正完成4,000步；公開模型取驗證選定的第1,000步，而非第4,000步latest。','course/chapters/19.md:191、208',[],['a_raw','a_public','a_provenance'],'原始native execution/training/outer/inference/validation metrics與原始公開hf receipt交叉核對；不重訓、不重新生成評測。',observed='train.steps=4000且completed=true；原native metrics最低validation_loss在1000；inference.selected_step=1000且best SHA=a734088abe31ba30d7fa09a1d28548497b9cef1d02939e5404d578212f40d057；发布hf receipt指向同SHA。',denominators={'completed_updates':'4000','selected_update':'1000','batch_size':'16','seed':'20261006','train_records':str(stages['moe-native']['train_records']),'validation_records':str(stages['moe-native']['validation_records']),'input_tokens':str(stages['moe-native']['tokens']),'target_tokens':str(stages['moe-native']['target_tokens']),'validation_metric_rows':str(len(raw['native_validation'])),'test_used_for_selection':'false'})
claim('c18','software','短Python程式只離線讀既有紀錄，先列六個MoE baseline階段，最後印native完成4000選定1000；不用權重下載或訓練。','course/chapters/19.md:193-208',[],['a_raw','a_notebook'],'實際在repo根目錄與notebooks/19工作目錄原樣執行。它展示的index欄位另外追到raw來源，沒有把作者source-selection說明當证据。',observed='兩個cwd都印相同七行；只import json與pathlib，沒有checkpoint load/網路/訓練呼叫。')
claim('c19','software','兩個全量shell recipe可由本機wrapper的現有CLI接受：固定manifest/data、指定CPU參數、新輸出目錄；pretrain無父checkpoint，native開新段承接自己的weighted best。','course/chapters/19.md:213-240',[ref('s_wrapper','118-175','wrapper-managed資料/config/export、精確参数、manifest/data指纹、exist_ok=False及实际trainer命令。'),ref('s_train','631-686、689-714','各旗標的實際parser與native固定配置。')],['a_contract','a_cpu'],'原全量recipe只做确切解析與manifest pin验证；另外七個合成有界wrapper驗證真實执行契约。不宣稱本輪重做1000/4000或其他全量訓練；需要操作页的完整固定資料前提。',observed='原兩個命令無縮寫解析成功，manifest SHA=3443e3d32ff1e63f8126c2327011be541238765824623af9c8fdcff6b056cb1b；uv0.12.19；同wrapper用自有合成資料七次真實child完成。')
claim('c20','software','native只接受同架構、已完成tool4/numeric4 weighted selected best及其一致回執；wrapper保留真命令、結果與SHA；未完成attempt不能升為fresh來源。','course/chapters/19.md:242、248',[ref('s_nativegate','727-854','selected best命名、同架構4/4/1、completed exact source metadata、文件SHA及inference/训练身份交叉核對。'),ref('s_train','474-516','實際載入checkpoint的step、policy、options、history與來源metadata绑定。'),ref('s_wrapper','52-85、176-251','來源verify與真實subprocess/execution/receipt記錄；fresh禁止不完整来源。')],['a_cpu','a_gate','a_raw'],'只支持genuine local wrapper/原runner产出的自有checkpoint；SHA確定內容身份，品質要另查验证題。completed意指來源達到它宣告的目标步數，不是保證達到生成阈值。',observed='真實local weighted44→native414正例通过；failed source fresh init、錯架構dense、best完整bytes/SHA改變均拒絕；checkpoint和来源receipt SHA保留。')
claim('c21','software','公開safe export只有選定模型tensor及推論契約，沒有optimizer、RNG或sampler；本訓練鏈使用自有完整PT checkpoint。','course/chapters/19.md:244',[ref('s_train','235-281、849-878','safe writer只取checkpoint.model；完整PT另保存optimizer/RNG/sampler/計數。'),ref('s_wrapper','52-85','只接受自有best.pt/latest.pt與local execution sidecars。'),ref('s_checkpoint','256-307','一般完整续训checkpoint須包含optimizer等。')],['a_cpu'],'格式與本管線的加载契約；不声稱所有safetensors使用方式都不能承載任意tensor，而是本案公開檔的內容。',observed='本機safe_open看到74個model tensor keys，等於完整checkpoint.model keys；沒有optimizer/RNG/sampler。')

body=(BASE/'inputs/19.4.md').read_bytes()
current=(ROOT/'course/chapters/19.md').read_bytes()
heading=re.search(rb'^## 19\.4 .+$',current,re.M);endmatch=re.search(rb'^## ',current[heading.end():],re.M)
end=heading.end()+endmatch.start() if endmatch else len(current)
assert current[heading.start():end]==body
report={'schema_version':1,'review_stage':'technical','lesson_id':'19.4','source':'course/chapters/19.md#19.4','reviewer_task':'/root/p6_fact_19_4','reviewer_context':'fresh','source_sha256':hashlib.sha256(body).hexdigest(),'figure_sha256':{'course/figures/p6-19-start-lineage.svg':digest(ROOT/'course/figures/p6-19-start-lineage.svg')},'verdict':'pass','claims':claims,'sources':sources,'artifacts':artifacts,'issues':[],
 'inspection':{'read_text':'原稿19.4完整小節159-249；必要操作頁docs/selftrained/TRAINING.md僅1-140；方法規約與checker完整schema。原章byte快照不代表閱讀其他小節。','frozen_input':{'path':PREFIX+'/inputs/19.md','sha256':digest(BASE/'inputs/19.md'),'meaning':'最初取得的完整Markdown原始byte快照；正式source_sha256只對应19.4。'},'own_summary':'用完整checkpoint與真正的完成/選定紀錄建立自有stage lineage，分開fresh init、exact resume、teacher-forced選版與能力驗收。','raw_data_policy':'先keys/types後named pointers；完整原始資料副本不刪改；没有讀notes/review/作者勝敗摘要。stage index與v2-jobs只定位或核對原命令，不當成既有成績證據。','figures':'librsvg/Cairo渲染640x884與360x497，兩張均實際view_image。圖示主鏈是MoE；Dense止於weighted由正文及raw/publish紀錄說明。','external':'官方PyTorch原文已直接取得、定位與保存；docs.pytorch.org教程頁最初403，随后通过官方GitHub原始檔核對，未關閉TLS。','tool_limitations':'Chromium兩次未在限時內完成，ImageMagick所需rsvg-convert執行檔缺失；最後直接使用已安装librsvg/Cairo成功真渲染。這些工具限制未当成教材錯誤。','executed_scope':'只執行7個1-3步合成CPU wrapper算例、函式負例、原JSON短程式、歷史Git/資料核對及圖渲染。未做原資料完整訓練、付费/GPU、权重下載、heldout重评或上傳。'},
 'checks':{
  'factual_accuracy':{'status':'pass','details':'21項實質主張分别核對；source鏈、目標、凍結、init/resume、驗證與發布來源均有原始證據及個別支持範圍。','claim_ids':[c['id'] for c in claims]},
  'numeric_verification':{'status':'pass','details':'依原train/inference/metrics親算15段完成/選定步數、native4000/1000；本機head3/12/3及loss倍率mask精確核對；原index不是單獨證據。','claim_ids':['c02','c03','c06','c07','c08','c10','c11','c12','c16','c17']},
  'figure_consistency':{'status':'pass','details':'本節唯一SVG已真渲染與親看640/360兩尺寸；8段順序、向下箭頭、父best與新段reset標籤符合MoE原始訓練鏈；沒有未查數字。','claim_ids':['c02','c14']},
  'source_verification':{'status':'pass','details':'親讀權威原文、現trainer/wrapper及必要模型/encoder/gate；原始15個execution revision的歷史trainer另由local Git取得並核對；原件與保存副本SHA逐一吻合。','claim_ids':[c['id'] for c in claims]},
  'limitations':{'status':'pass','details':'把原實測核對、合成CPU契約算例、全量配方解析與生成能力分開。原目標、loss選版、head分類與fingerprint不當生成考卷通過證據；未做全量/heldout重跑。','claim_ids':[c['id'] for c in claims]}
 }}
(ROOT/'docs/technical-reviews/19.4.json').write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n')
print('Wrote fresh 19.4 pass: '+str(len(claims))+' claims, '+str(len(sources))+' sources, '+str(len(artifacts))+' persistent artifacts; section '+report['source_sha256'])
