from pathlib import Path
from datetime import datetime,UTC
import json,hashlib,shutil,platform,re
R=Path.cwd();A=R/'docs/technical-reviews/artifacts/phase4-13_15-independent';start_path=R/(A/'context-reinspection/latest-start-path.txt').read_text().strip();meta=json.loads(start_path.read_text());O=R/meta['reinspection_path'];prior_path=R/meta['prior_report_history_path'];prior=json.loads(prior_path.read_text());check=json.loads((O/'context-check.json').read_text());preview=json.loads((O/'preview-render-result.json').read_text());stamp=O.name
assert prior['reviewer_task']=='/root/phase4_factual_coordinator/factual_13_15' and check['provisional_verdict']=='pass' and not check['open_questions'] and preview['status']=='completed'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def write(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2,allow_nan=False)+'\n')
# Snapshot each actual command/code/output by its own name, never a workspace copy.
for source,destination in [(A/'context-reinspection/check-context.py',O/'check-context-executed.py'),(A/'context-reinspection/context-check.stdout',O/'context-check.stdout'),(A/'context-reinspection/context-check.stderr',O/'context-check.stderr'),(A/'context-reinspection/preview-render.stdout',O/'preview-render.stdout'),(A/'context-reinspection/preview-render.stderr',O/'preview-render.stderr'),(Path(__file__),O/'build-context-report-executed.py'),(R/'docs/review-tools/factual-reviewer-instructions.md',O/'factual-reviewer-instructions-current.md')]:shutil.copyfile(source,destination)
receipt_id='context-reinspection-'+stamp
receipt={'schema_version':1,'kind':'same_original_owner_necessary_context_reinspection','reviewer_task':prior['reviewer_task'],'started_on_utc':meta['started_on_utc'],'completed_on_utc':datetime.now(UTC).isoformat(),'source':'course/chapters/13.md#13.15','source_sha256':meta['section_context_comparison']['13.15']['current_sha256'],'verdict':'pass','prior_report':{'path':meta['prior_report_history_path'],'sha256':meta['prior_report_sha256'],'preservation':'Exact previous canonical bytes backed up before read or replacement; original owner reinspection, not another reviewer report'},'current_context_slices':meta['section_context_comparison'],'current_context_frozen_input':{'path':str((O/'chapter-13-current-context-frozen.md').relative_to(R)),'sha256':meta['frozen_current_context_chapter_sha256'],'meaning':meta['snapshot_meaning']},'actual_new_read_scope':check['actual_new_read_scope']+['Current docs/review-tools/factual-reviewer-instructions.md in full','Actual exported 13.15 preview at 1280x800 and 390x844, top and expanded original code, via Chromium screenshots and own view'],'fingerprint_only_scope':check['hash_only_scope'],'personally_classified_changes':check['semantic_changes'],'executable_fence_comparison':check['fence_checks'],'repository_sources':check['repository_sources'],'immutable_source_snapshots':check['immutable_source_snapshots'],'prerequisite_svg_checks':check['prerequisite_figures'],'prior_artifact_integrity_checked':check['prior_artifact_integrity'],'claim_support_reuse':{'claim_ids':check['reused_claim_ids'],'reason':check['reuse_support'],'new_cpu_execution':False,'new_primary_source_download':False,'new_training_or_weight_evaluation':False},'visual_inspection':{'actual_url':meta['preview_url'],'html_snapshot_path':str((O/'13.15-preview.html').relative_to(R)),'html_sha256':preview['html_sha256'],'renderer':'Chromium '+preview['chromium_version'],'viewed_files':[s['file'] for s in preview['screenshots']],'own_observation':'Actual exported page shows the current 13.15 title, feature mapping, finite task limits and four update steps coherently at desktop/mobile sizes. Expanded code is visible with horizontal scrolling for long lines on mobile. Visible CPU output matches the previously executed own fence; it is not treated as a new execution. No 13.15 figure is present. Unchanged prerequisite SVG/raster evidence remains applicable.','scope_limit':'Actual preview was visually inspected for factual correspondence; this does not replace a full independent reader acceptance session.'},'open_questions':[],'canonical_artifact_id':receipt_id,'planned_next_check':'.venv/bin/python scripts/check_technical_reviews.py --lesson 13.15 after this updated canonical is generated and confirmed'}
receipt_path=O/'reinspection-receipt.json';write(receipt_path,receipt)
report=prior
new_artifacts=[]
def artifact(identifier,p,kind,description,command=None,result=None,environment=None):
 a={'id':identifier,'path':str(p.relative_to(R)),'sha256':sha(p),'kind':kind,'description':description}
 if kind=='execution':a.update(command=command,result=result,environment=environment or {'python':platform.python_version(),'device':'CPU; hash/AST/context inspection only'})
 new_artifacts.append(a)
artifact(receipt_id,receipt_path,'source_snapshot','Own necessary-context reinspection receipt: current raw slices/locators, semantic classification, source/evidence reuse justification and true visual scope')
artifact('prior-own-report-'+stamp,prior_path,'source_snapshot','Exact prior own canonical report backed up before this context reinspection')
for name in ['13.12-current.md','13.14-current.md','13.15-current.md','13.12-original-frozen.md','13.14-original-frozen.md','13.15-original-frozen.md','13.12-actual-diff.txt','13.14-actual-diff.txt','chapter-13-current-context-frozen.md','context-check.json','preview-render-result.json','factual-reviewer-instructions-current.md','13.15-preview.html','start.json']:
 artifact('context-'+stamp+'-'+name.replace('.','-'),O/name,'source_snapshot','Actual current/own-frozen context evidence: '+name)
for name in ['check-context-executed.py','render-current-preview-executed.py','build-context-report-executed.py']:
 artifact('context-code-'+stamp+'-'+name.replace('.','-'),O/name,'code','Executed code snapshot for this narrow context reinspection')
artifact('context-check-run-'+stamp,O/'context-check.stdout','execution','True stdout of context hash/AST/own-source integrity check','.venv/bin/python docs/technical-reviews/artifacts/phase4-13_15-independent/context-reinspection/check-context.py','Exit 0: current own section unchanged; 13.12 spelling and 13.14 blank-line edits only; executable AST, relevant implementation, primary-source snapshots, SVGs and all 47 previous artifacts unchanged')
artifact('context-preview-run-'+stamp,O/'preview-render.stdout','execution','True stdout of current exported preview rendering','.venv/bin/python docs/technical-reviews/artifacts/phase4-13_15-independent/context-reinspection/render-current-preview.py','Exit 0: desktop/mobile top and expanded code captured; all four images personally viewed',{'python':platform.python_version(),'Chromium':preview['chromium_version'],'device':'CPU/headless'})
for s in preview['screenshots']:artifact('context-view-'+stamp+'-'+s['file'].replace('.','-'),O/s['file'],'figure_render','Personally viewed actual exported current-page screenshot '+s['file'])
report['artifacts']=report['artifacts']+new_artifacts
report['context_reinspection']={'receipt_artifact_id':receipt_id,'receipt_path':str(receipt_path.relative_to(R)),'receipt_sha256':sha(receipt_path),'prior_report_path':meta['prior_report_history_path'],'prior_report_sha256':meta['prior_report_sha256'],'reviewer_task':prior['reviewer_task'],'actual_new_scope':receipt['actual_new_read_scope'],'fingerprint_only_scope':check['hash_only_scope'],'current_context_sha256':{sid:v['current_sha256'] for sid,v in meta['section_context_comparison'].items()},'support_reuse':'Original owner personally classified and verified unchanged semantics and support; no unrelated rerun or source refetch. All 14 previously substantiated claims remain valid.','open_questions':[]}
report['actual_read_scope']=prior['actual_read_scope']+['Context reinspection '+stamp+': '+s for s in receipt['actual_new_read_scope']]
report['source_sha256']=receipt['source_sha256'];report['verdict']='pass';report['reviewed_on']='2026-10-05'
report['checks']['factual_accuracy']['details']+=' Same original owner now reread current 13.15 and necessary 13.12/13.14, compared own frozen counterparts and exact diffs: spelling and one blank line only; no changed substantive claim or unresolved question.'
report['checks']['numeric_verification']['details']+=' Original execution evidence is explicitly reused, not rerun: changed prerequisite fences have identical executable AST, while the own fence bytes and all relevant implementation/evidence fingerprints are unchanged.'
report['checks']['source_verification']['details']+=' During context reinspection, personally checked every original immutable snapshot/implementation and previous artifact against its recorded SHA; unchanged semantics leave each original source supporting the same claim scope. No primary-source refetch was needed.'
report['checks']['figure_consistency']['details']='13.15 has no image/SVG reference. Unchanged prerequisite SVGs match the previously actually rendered/viewed originals by byte equality and SHA. During this same-owner context reinspection, actually viewed the current exported 13.15 page at 1280x800 and 390x844, top and expanded code. Current text, role/update explanation and code presentation agree with the own reviewed section. This narrow factual visual check is not a new full reader acceptance session.'
report['checks']['limitations']['details']+=' A later narrow context check also viewed the actual exported current preview; it did not rerun any CPU model experiment, training or evaluation. Original standalone visual evidence remains historical evidence, not the scope of this new page check.'
report['limitations'].append('Same-owner context reinspection '+stamp+': current actual exported preview viewed at desktop/mobile sizes; only own 13.15 and necessary changed 13.12/13.14 were reread. Original CPU/paper/SVG evidence reused after actual semantics and fingerprint checks; no new model experiment, training or weight evaluation.')
# Validate current source bytes and ownership before replacing own canonical.
raw=(R/'course/chapters/13.md').read_bytes();hs=list(re.finditer(rb'(?m)^## [^\r\n]+',raw));i=next(i for i,h in enumerate(hs) if h[0].startswith(b'## 13.15 '));end=hs[i+1].start() if i+1<len(hs) else len(raw);assert hashlib.sha256(raw[hs[i].start():end]).hexdigest()==report['source_sha256'];assert report['reviewer_task']=='/root/phase4_factual_coordinator/factual_13_15'
canonical=R/'docs/technical-reviews/13.15.json';write(canonical,report);saved=json.loads(canonical.read_text());assert saved['reviewer_task']==receipt['reviewer_task'] and saved['context_reinspection']['receipt_sha256']==sha(receipt_path) and saved['source_sha256']==receipt['source_sha256']
result={'canonical_generated_and_confirmed':True,'verdict':saved['verdict'],'reviewer_task':saved['reviewer_task'],'source_sha256':saved['source_sha256'],'report_sha256':sha(canonical),'prior_history_path':meta['prior_report_history_path'],'prior_history_sha256':meta['prior_report_sha256'],'canonical_artifact_id':receipt_id,'receipt_path':str(receipt_path.relative_to(R)),'receipt_sha256':sha(receipt_path),'actual_new_scope':receipt['actual_new_read_scope']};write(O/'canonical-generation-confirmation.json',result);print(json.dumps(result,ensure_ascii=False,indent=2))
