import runpy,pathlib,json,hashlib,datetime,re
B=pathlib.Path('/workspace/work/tutorial-audit-20261008');W=B/'technical-modalities-work';ns=runpy.run_path(str(W/'build_report.py'));rows=ns['rows'];M=ns['M'];I=ns['I'];ids=M['groups']['modalities']['pages']
assert [p['page_id'] for p in rows]==ids
now=datetime.datetime.now(datetime.timezone.utc).isoformat()
small=json.load(open(W/'small-check-results.json'))
for row in rows:
 pid=row['page_id'];assert row['source_sha256']==I[pid]['source_sha256']
 row['classification']='adequate_in_checked_technical_scope' if pid!='13.3' else 'adequate_with_optional_wording_improvement'
 row['figures']=dict(I[pid]['figures_sha256'])
 row['unverified'].append('未獨立重做訓練或用原checkpoint重新評測；原實測只回查下列JSON與實作，不把JSON數字當新重現。')
 if pid in small['results']:
  row['checks'].append({'execution_evidence':'technical-modalities-work/small-check-results.json#/results/'+pid,**small['results'][pid]})
 if not re.search(r'```python', (B/'freeze/sources'/f'{pid}.md').read_text()):
  row['unverified']=[v for v in row['unverified'] if '未完整執行本頁' not in v]
actual=[]
for pid,reason,quote in [('5.17','核凍結/eval/no_grad與固定核心向前端傳梯度','第三個設定requires_grad=False只凍結相應參數。'),('7.4','核多模態展開後next-token shift責任','`render_chat` 已完成這個配對，TinyLM和loss按同一位置比較，不能再移一次。'),('7.1','核對話角色、BOS/EOS與跨入口歷史','多輪則按消息順序保留角色，不能靠內容中的標記拼寫猜誰說話。'),('7.17','核有限選卡從隨機監督訓練與LLM SFT差別','接在底座後的學習叫後訓練，SFT是其中一種。'),('8.3','核DPO content.pt共同弱起點與風格對照來源','這個基模本來也沒有答對這七題，不能把結果描述成原先會算、改文風才被破壞。')]:
 s=(B/'freeze/sources'/f'{pid}.md').read_text();assert quote in s;actual.append({'page_id':pid,'source_sha256':hashlib.sha256(s.encode()).hexdigest(),'reason':reason,'read_scope':'全文含details；必要前文回查，未作分組外全章診斷','quoted_basis':quote})
visual=[]
for src in sorted({s for p in rows for s in p['figures']}):
 name=pathlib.Path(src).stem;png=B/'renders'/(name+'-640.png');orig=B/'freeze/original'/src
 visual.append({'source':src,'source_sha256':M['figures_sha256'][src],'render':str(png),'render_sha256':hashlib.sha256(png.read_bytes()).hexdigest(),'seen':True,'width_px':640,'reading_order':'先由view_image取得畫面，後續回合才寫各頁對應判斷','pages':[p['page_id'] for p in rows if src in p['figures']]})
assert len(visual)==28
external=json.load(open(W/'originals/manifest.json'))
locations={
'ppo.pdf':{'locations':'ppo.txt lines 104–132, 232–245；PDF第3節eq6/7與Algorithm1','quote':'we only ignore the change in probability ratio when it would make the objective improve, and we include it when it makes the objective worse.'},
'dpo.pdf':{'locations':'dpo.txt lines 141–208, 220–262；第3節eq1–3與第4節eq7','quote':'This change-of-variables approach avoids fitting an explicit, standalone reward model'},
'minds-paper.pdf':{'locations':'minds-paper.txt lines 68–98, 140–163；收集流程與pretrained sentence encoders/GoogleASR','quote':'human subjects are first provided with the particular intent class, a description of the intent, and three examples for the intent class.'},
'minds-card.md':{'locations':'lines 1–28, 868–920, 929–987, 987–1011, 1020–1034','quote':'num_examples: 502','note':'zh-CN意圖含address/app_error/card_issues；cc-by-4.0；列出的schema無speakerID，不宣稱跨說話者'},
'fashion-readme.md':{'locations':'lines 1–25與64–81','quote':'Each example is a 28x28 grayscale image, associated with a label from 10 classes.','note':'1 Trouser、8 Bag、9 Ankle boot'},
'fashion-license.txt':{'locations':'全文','quote':'The MIT License (MIT) Copyright © 2017 Zalando SE'},
'noto-license.txt':{'locations':'lines 1–68','quote':'The requirement for fonts to remain under this license does not apply to any document created using the fonts or their derivatives.'},
'instructgpt.pdf':{'locations':'instructgpt.txt lines 300–338, 482–507；3步與eq2','quote':'we add a per-token KL penalty from the SFT model at each token'}}
for x in external:x.update(locations[x['file']])
# 只投影實際回查的證據分支；不把history全部讀過或checkpoint重評冒充完成。
repo=pathlib.Path('/workspace/tiny-perceptron-vlm')
def raw(n):return json.load(open(W/'originals'/('result-'+n+'.json')))
emp=[]
def evidence(name,pages,pointers,denominator,conditions,findings,unverified='未重訓、未載checkpoint重新評估；GPU/平台與原始資料取得未重驗。'):
 d=raw(name);emp.append({'source':f'docs/course-experiments/results/{name}.json','snapshot':f'technical-modalities-work/originals/result-{name}.json','source_sha256':hashlib.sha256((W/'originals'/('result-'+name+'.json')).read_bytes()).hexdigest(),'version':d.get('revision'),'device':d.get('device'),'seed':d.get('seed'),'pages':pages,'actually_read_json_pointers':pointers,'denominators':denominator,'comparison_conditions':conditions,'findings':findings,'unverified':unverified})
evidence('encoders',['10.5','12.8','12.12'],['/results/vision/config','/results/vision/training (scalar fields)','/results/vision/data','/results/audio/config','/results/audio/data/splits'],{'vision':6,'audio':14},'視覺六色形類、width16；音訊frequency family不同amplitude/duration共同；各自預訓練獨立於正文width8梯度例。','視覺250步有weights_changed；joint test260/340在audio train，教材未見限定成立。')
evidence('contrastive',['10.9','10.10','10.11'],['/results/config','/results/data','/results/scope','/results/variants/*/training scalar fields','/results/variants/*/validation','/results/variants/*/test'],{'image_queries_each':6,'text_queries_each':6},'one_way/two_way同seed、250步、1500有效targets、唯一屬性batch；非自由caption。','两版两个test方向6/6，validation图找文5/6、文找图6/6，没有观察答对优势。')
evidence('projector',['11.3'],['/results/training scalar fields','/results/test','/results/data','/results/language_weights_unchanged','/results/scope'],{'test':6},'凍結已訓入口與文字、只训接头；保留teacher forcing与生成区别。','initial_loss4.147989→1.209308，weights_changed=True，test0/6；红方只red、綠圓reeeeeeeeen。')
evidence('vqa',['11.4','11.5','11.6','11.7'],['/results/data','/results/variants/*/training scalar fields','/results/variants/*/validation','/results/variants/*/test','/results/variants/*/text_before scalar fields','/results/variants/*/text_after scalar fields','/results/two_stage_alignment_training scalar fields','/results/direct_vs_two_stage_budget','/results/text_data'],{'vision_validation':12,'vision_test':12,'old_text_test':10},'同一projector起點，scope三版各3830target；replay4214不是同预算；直接方案18256對兩階段18238、末批超18；未另列直接旧文本分數。','參數1088/50816/145664；vision test3/12,12/12,9/12；旧文本5/10→5,2,1；replay4/10；directvision10/12。')
evidence('vision_ablation',['11.8','11.9','11.10','11.11'],['/results/interventions','/results/patch_variants','/results/patch_budget','/results/crop_note','/results/data/split_policy'],{'test':12,'shape':6,'color':6,'paired_shape':6},'同問換shape重標與shuffle按原label不同；crop殘留色；patch4/8fresh-specificencoders不能改推論旗標。','none9/12=colour6/6+shape3/6；形狀一律circle，替換两端同對0/6；crop9/12；patch4/8均9/12。')
evidence('ocr',['11.12','11.13'],['/results/data','/results/test','/results/training scalar fields','/results/scope'],{'test_strings':30,'reference_characters':57},'0–99固定5x7字形字符串家族拆分；train240/validation30/test30，各來源變體同側；train已含0–9字元，完整字符串train/test不相交。','EOS30/30，內容2/30，40edits/57CER=.701754；非另一字體/手寫或新字類。')
evidence('real_modal',['12.2'],['/results/fsdd/resampling/0'],{'waveform_resampling_samples_before':4591,'after':9182},'source0_jackson_5.wav8000→16000，windowed-sinc interpolation16-sample radius。','時長兩者=.573875秒，非改metadata。','只回查首筆記錄與算術，未重新下載WAV或執行resampler；不審其他真人數字辨識結果。')
evidence('audio',['12.9','12.10'],['/results/test','/results/blank','/results/shuffle','/results/data/splits/test','/results/data/split_policy','/results/training scalar fields'],{'test':14,'low':8,'high':6},'high iff frequency>300；每frequency amplitude.25/.5與seconds.1/.12共變；shuffle donor7位置移動，按新舊真值分判。','原11/14；错290/300；blank全部high6/14；shuffle旧label3/14、新donor真值11/14；仅2label不變。')
evidence('joint',['12.12'],['/results/evaluations','/results/validation scalar fields','/results/data/splits/test','/results/data/split_policy','/results/scope'],{'test':12,'validation':12},'shape/pitch獨立交叉配，移去模態仍按原答案，swap按新答案；test频260/340与前置audio训练有重叠。','none12/12，blank_image6/12，blank_audio6/12，bothblank3/12；每路swap12/12；validation8/12。')
evidence('dpo',['13.1','13.2','13.3','13.4','13.5','13.6','13.7','13.9'],['/results/data','/results/before','/results/runs/*/training (history未逐项审)','/results/runs/*/preference','/results/runs/*/arithmetic','/results/reference_unchanged','/results/format_only','/results/ultrafeedback_pilot/source_records','/results/ultrafeedback_pilot/data','/results/ultrafeedback_pilot/sft_training scalar fields','/results/ultrafeedback_pilot/training scalar fields','/results/ultrafeedback_pilot/evaluation'],{'train_pairs':49,'validation_pairs':8,'test_pairs':7,'test_families':4,'ultra_train':80,'ultra_validation':10,'ultra_test':10},'content.pt弱共同起點、sum含EOS；beta.1與1同seed各250步/8pair/.001學習率及9448两侧有效target；format200步；ultra32width1layer先SFT80再DPO80、每段120UTF8byte上限。','13.6完整表核到；3+5相对+2.445567仍错candidate较高；4+2排序6>7但生成8；format7/7排序相對却0/7生成，0+3chosenlog下降亦margin改善；ultra6/10vs7/10与8/10vs4/10。','未重训或载权重复评；Ultra原完整回答label是否适用于片段仍未验证；未审安全/反附和/自由自然chat质量。')
evidence('posttraining',['13.10','13.11','13.12','13.13','13.14','13.15','13.16','13.17'],['/results/config','/results/parameters','/results/splits','/results/sft','/results/reward (history未逐项审)','/results/ppo (history未逐项审)','/results/dpo (history未逐项审)','/results/clipping_probe','/results/evaluations/train','/results/evaluations/test','/results/reference_state_sha256_before','/results/reference_state_sha256_after','/results/comparison_limits','/results/experiment_seconds','/results/effective_tokens'],{'families':55,'train_families':44,'validation_families':5,'test_families':6,'train_contexts':132,'validation_contexts':15,'test_contexts':18,'test_preference_pairs':90},'作者固定規則/预制卡，四人工contextfeatures；SFT148参数numberonly；reward241/value97；KL独立加入policy、critic只估normalizedRM；PPO/DPO起点hash逐项同。','SFTtest6/18→两分支12/18，number6/6/explain0/6/missing6/6；RM90/90；PPO7680新动作/23040重用及policy/critic各360更新，DPO23040pair/360更新；.657001/.343356段秒，RM.270443，全2.109786；不是LLM/RLHF或公平等总预算SFT比较。','只回查原JSON、實作及正文单步更新；未重跑完整2秒CPU实验，也未检查所有history或first_rollout_trace各数值；原JSON與正文固定commit1df3353版本已比對一致。')
(W/'empirical-evidence.json').write_text(json.dumps(emp,ensure_ascii=False,indent=2))
issues=[{'id':'T-M-01','page_id':'13.3','quoted_basis':'前文和補長用的空格不計分。','already_taught':'原文已限定補長用途，labels=-100忽略位置與sum指定答案在本頁及前文清楚。','minimal_missing_relation':'措辭可再分清padding專用格與答案中的普通空白字元；並非演算法缺漏。','current_impact':'少量文字歧義：ByteTokenizer會把正常空白編成byte+8，答案空白仍是有效目標；讀者一般能由「補長用」推回PAD，故不列必要負擔。','severity':'optional','minimal_patch':'將「補長用的空格」改成「補齊用的PAD位置」，不另加段落。','rewrite_scale':'paragraph','discovery_time':now,'discovery_phase':'獨立技術輪全文閱讀13.3與alignment.py/data.py核對','unprompted_source':'只看凍結正文、凍結程式及必要前文；未看其他reports/notes/traces或舊問題','source_sha256':I['13.3']['source_sha256']}]
report={'schema_version':1,'reviewer':'/root/technical_modalities','role':'technical','group':'modalities','kind':'來源獨立AI輔助技術診斷，非首讀盲讀或真人學生測試，非發布驗收','baseline_commit':M['baseline_commit'],'created_at':now,'criteria_sha256':{k:M['criteria_sha256'][k] for k in ['SKILL.md','references/review-protocol.md','references/calibration.md','references/project-context.md']},'actual_prerequisites':actual,'pages':rows,'issues':issues,'coverage':{'assigned_pages':66,'fully_read_pages':66,'page_ids':ids,'full_source_including_details_read':True,'source_hashes_verified':True,'missing_pages':[],'source_initial_judgments_preserved_independently':True,'other_reviewer_or_historical_judgments_seen':False,'necessary_issues':0,'optional_issues':1,'technical_blockers_found':0,'technical_burdens_found':0,'unverified_not_counted_as_pass':['實際網站桌面/手機布局及折疊/跳轉路徑','28張圖的360px渲染與頁內縮放可讀性','全部短程式/練習与反例變體的執行','既有完整訓練重演、checkpoint獨立評測、GPU與平台泛化','真人錄音素材播放与原始資料重新取得','直接語音意圖/共享跨輪歷史設計的實際從零訓練效果','12.15引用1904.03670研究未讀，未拿其預訓練成績保證本模型']},'visual_scope':{'figures_assigned':28,'figures_seen_at_640':28,'figures':visual,'actual_website_viewed':False,'mobile_360_render_viewed':False,'limits':'親看PNG內容與正文對應，只核圖意；不能據此稱实际頁面或首讀路径通過。'},'execution_scope':{'python':'/workspace/tiny-perceptron-vlm/.venv/bin/python','torch_version':small['torch'],'device':'cpu','threads':1,'snippets_executed':list(small['results']),'snippet_count':13,'all_selected_snippets_completed':all(x['status']=='completed' for x in small['results'].values()),'optimizer_steps':'只13.15随机微型網路的一次SGD step，其餘選定例為前向/反向/算術；沒有整段模型訓練','long_training_rerun':False,'small_check_evidence':'technical-modalities-work/small-check-results.json','default_python_note':'系統python无torch，后使用repo既有.venv；没有安装或更改依赖','implementation_sha256_verified_against_source_manifest':True},'empirical_evidence':emp,'raw_result_version_manifest':'technical-modalities-work/result-source-manifest.json','external_originals':external,'repair_scale_assessment':{'necessary_rewrite':'未由本技術輪發現必要重寫；不能代替reader/continuity或網站驗收。','optional_rewrite':'13.3一句PAD措辭，paragraph範圍；原文可保留。','chapter_or_order_rewrite_indicated':False,'limitations':'教材中明確示意或設計例沒有實測不是缺陷；所有主要實測數字在列明來源與分母内吻合，未重跑训练。'},'working_evidence':['technical-modalities-work/build_report.py','technical-modalities-work/working-pages.json','technical-modalities-work/small_checks.py','technical-modalities-work/small-check-results.json','technical-modalities-work/empirical-evidence.json'],'isolation_record':'本輪只讀本組凍結來源、5份實際必要前文、技術背景/凍結實作/來源manifest、直接引用原始JSON與官方原文；不讀reports、synthesis、notes、traces、checks人類判斷或repo歷史審閱。root提供過可用.venv提示，無主題/答案提示。'}
# 每頁具體引文與checked/unchecked皆已齊備，最後一次範圍驗證才產生coverage及seal。
for p in rows:assert p['quoted_basis'] and p['checks'] and p['unverified']
(W/'working-pages.json').write_text(json.dumps(rows,ensure_ascii=False,indent=2))
reports=B/'reports';reports.mkdir(exist_ok=True);target=reports/'technical-modalities-initial.json';target.write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n')
h=hashlib.sha256(target.read_bytes()).hexdigest(); seal={'schema_version':1,'reviewer':report['reviewer'],'report':str(target),'sha256':h,'sealed_at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'phase':'source-independent initial','coverage_pages':66,'no_other_judgments_seen_before_seal':True,'no_self_revision_after_seal':True};sp=reports/'technical-modalities-initial-seal.json';sp.write_text(json.dumps(seal,ensure_ascii=False,indent=2)+'\n');print(json.dumps({'report':str(target),'seal':str(sp),'sha256':h,'pages':len(rows),'necessary':0,'optional':1,'figures640':len(visual),'short_checks':13},ensure_ascii=False))
