"""Write this reviewer's new report; never reads a pre-existing report."""
import hashlib
import json
from pathlib import Path

OUT=Path(__file__).resolve().parent
ROOT=OUT.parents[3]
PREFIX=OUT.relative_to(ROOT).as_posix()
TASK='/root/phase4_factual_coordinator/factual_19_10'
assert TASK=='/root/phase4_factual_coordinator/factual_19_10'
sha=lambda path:hashlib.sha256(path.read_bytes()).hexdigest()
data=json.loads((OUT/'verify.results.json').read_text())
assert 'metadata_normalization' in data
environment=data['environment']
source_hash=sha(OUT/'section.md')
assert source_hash=='5544ad0495ce62855055bd4f5091cf75a9c5d804f311bf36b5465a5f56e8371c'
commands={
 'original':'.venv/bin/python docs/technical-reviews/artifacts/phase4-factual-19_10-independent/run_original.py',
 'verify':"CUDA_VISIBLE_DEVICES='' PYTHONDONTWRITEBYTECODE=1 OMP_NUM_THREADS=1 MKL_NUM_THREADS=1 .venv/bin/python docs/technical-reviews/artifacts/phase4-factual-19_10-independent/verify.py > docs/technical-reviews/artifacts/phase4-factual-19_10-independent/verify.stdout.txt 2> docs/technical-reviews/artifacts/phase4-factual-19_10-independent/verify.stderr.txt",
 'inspect':'.venv/bin/python docs/technical-reviews/artifacts/phase4-factual-19_10-independent/inspect_inputs.py > docs/technical-reviews/artifacts/phase4-factual-19_10-independent/input-inspection.stdout.txt',
 'fetch':'.venv/bin/python docs/technical-reviews/artifacts/phase4-factual-19_10-independent/fetch_sources.py > docs/technical-reviews/artifacts/phase4-factual-19_10-independent/sources/fetch.stdout.txt 2> docs/technical-reviews/artifacts/phase4-factual-19_10-independent/sources/fetch.stderr.txt',
}
(OUT/'commands.json').write_text(json.dumps({'cwd':str(ROOT),'bash_login':False,'commands':commands,'execution_scope':'CPU, one thread, bounded arithmetic and stored-record inspection; no GPU/training/model download.'},ensure_ascii=False,indent=2)+'\n')
scope={
 'reviewer_task':TASK,'reviewer_context':'fresh','nonblind_factual_review':True,
 'frozen_inputs':[{'path':PREFIX+'/frozen/course/chapters/19.md','sha256':sha(OUT/'frozen/course/chapters/19.md'),'meaning':'Actual whole-chapter bytes frozen at first extraction; this is not a claim that the whole chapter was reviewed.'}],
 'context_snapshots':[{'path':PREFIX+'/frozen/course/chapters/'+name,'sha256':sha(OUT/'frozen/course/chapters'/name),'meaning':'Actual preserved whole-file context input; only the stated section ranges were read.'} for name in ['15.md','17.md','18.md']],
 'read_ranges':{
 'course/chapters/19.md':['19.10 entire raw section, lines 458-505; no other chapter-19 section read'],
 'course/chapters/17.md':['17.2 lines 50-77','17.5 lines 136-160'],
 'course/chapters/18.md':['18.8 lines 275-303','18.9 lines 304-344'],
 'course/chapters/15.md':['15.1 lines 5-42, as Dense-definition context only'],
 'tiny_perceptron/quantization.py':['lines 1-81; AST function locations first, then original methods'],
 'tiny_perceptron/capstone_quantization.py':['lines 1-189; original packing, serialized fields, reload and reconstruction methods'],
 'scripts/course_experiments/capstone_student.py':['lines 1-147 and 150-220; calculation, sampling, teacher freezing, cloning, steps and evaluation branches; did not read result scope string'],
 'scripts/course_experiments/capstone_deployment.py':['lines 1-80 and 272-365; saving/reloading/test protocol; AST dictionary keys located without reading author interpretation/recommendation values'],
 'tiny_perceptron/alignment.py':['lines 35-63; distillation_kl and distillation_loss'],
 'scripts/course_experiments/capstone.py':['lines 58-70; _balanced_sample contract'],
 'tiny_perceptron/capstone.py':['lines 34-48, 139-282, 499-610 and 655-694; config, synthetic data family splits, exact evaluation/runtime protocol, inference fields'],
 'scripts/capstone_release.py':['lines 44-68, 79-93 and 121-168; metadata whitelist and cleaned inference payload'],
 'primary_sources':['Hinton 1503.02531v1 pages 1-3 (Introduction and Section 2)','PyTorch immutable linear.py lines 53-140; module.py register_buffer 528-590 and buffers 2731-2752; functional.py kl_div 3401-3475','PyTorch _tensor_docs.py element_size 1726-1744 and nbytes 6753-6768; _torch_docs.py amax 7064-7106, numel 8815-8832, round 9898-9917, dequantize 3620-3638, quantize_per_tensor/per_channel 13808-13904','PyTorch v2.8.0 quantization.rst Introduction lines 12-40 and Post Training Dynamic Quantization lines 152-163'],
 },
 'json_inspection':'Exact schemas and named raw/provenance pointers are saved in input-inspection.json. Verification additionally scans all four /records lists for documented booleans, IDs, by_task counts and thresholds; no author result-interpretation fields were read.',
 'locator_only_indices':['outputs/course-revision-20261005/original-source-locators.json /locators matching primary API URLs','outputs/course-revision-20261005/original-paper-locators.json /records/16 original PDF locator'],
 'figure_scope':'This section contains no Markdown or HTML figure reference; helper found zero SVG references. No figure render is applicable.',
 'excluded':'No old technical/reader report body, author correction summary, result interpretation/recommendation values, model quality rerun, GPU operation or new weight file.',
 'method_limitations_classification':'Ordinary docstrings, recipe objectives, split policies, synthetic-data limitations and API documentation were read as original methods and checked against actual calculations. They contained no prior review verdict.',
 'tool_history':['First isolated helper attempt failed during torch/dill temporary-directory probes before fence 1; original stderr/environment retained. Setting TMPDIR inside extraction directory and disabling bytecode writes allowed exact fence execution, exit 0, no guard events.','An official generated HTML request returned HTTP 403. Independently fetched immutable official GitHub source/docstrings instead; final source-fetch exit 0.'],
 'communication_correction':'One progress message misstated the 8-bit error before inspecting the saved value. The next message corrected it to the actual 0.0037038326263427734; formal evidence uses only the observed value.',
}
(OUT/'read-scope.json').write_text(json.dumps(scope,ensure_ascii=False,indent=2)+'\n')

artifacts=[]
def art(id,rel,kind,description,command=None,result=None):
 a={'id':id,'path':PREFIX+'/'+rel,'sha256':sha(OUT/rel),'kind':kind,'description':description}
 if kind=='execution':a.update(command=command,result=result,environment=environment)
 artifacts.append(a)
art('a_original','original-fence.stdout.txt','execution','Exact unchanged fence output, with environment/command companions.',commands['original'],'exit 0; attempted fence [1], no guard events; 144 bytes, 48 bytes, max difference 0.046346306800842285.')
art('a_cpu','verify.stdout.txt','execution','Reviewer bounded CPU arithmetic, axis/unit checks, KL expression, metadata method and raw-record assertions.',commands['verify'],'exit 0; all arithmetic, packing, loss, dataset and stored-record assertions passed.')
art('a_values','verify.results.json','derivation','Full observed values, shapes, buffer bytes, output coordinates, original record pointers and provenance matches.')
art('a_math','calculation.md','derivation','Independent byte arithmetic, output-axis/units and KL denominator derivation.')
art('a_inspection','input-inspection.json','source_snapshot','Original input schemas, exact necessary raw/provenance pointers and AST function locations.')
art('a_scope','read-scope.json','source_snapshot','Actual read ranges, frozen whole-chapter meaning, exclusions and tool history.')
art('a_commands','commands.json','code','Actual commands and bounded execution scope.')
art('a_fence','fence-1.py','code','Raw UTF-8 fence, unmodified.')
art('a_section','section.md','source_snapshot','Raw section bytes, with original line boundaries.')
art('a_frozenchapter','frozen/course/chapters/19.md','source_snapshot','Actual whole chapter input frozen with the initial extraction SHA; only19.10 was reviewed.')
art('a_bootstrap','bootstrap.py','code','Actual build-course bootstrap used unchanged by the original-fence worker.')
for id,rel,desc in [('a_env','verify.environment.json','Verification Python/PyTorch CPU versions.'),('a_orig_env','original-fence.environment.json','Exact fence environment and attempted fences.'),('a_orig_record','original-fence.execution.json','Original execution argv and exit code.'),('a_extract','extraction.json','Raw extraction/fence/SVG/hash facts.'),('a_first_failure','helper-first-attempt.stderr.txt','Retained initial helper restriction failure before any fence.'),('a_first_env','helper-first-attempt.environment.json','Retained initial helper guard events.'),('a_receipts','sources/receipts.json','Official primary source HTTPS/version/access/SHA receipts.')]:art(id,rel,'source_snapshot',desc)
for id,rel in [('a_verify_code','verify.py'),('a_original_code','run_original.py'),('a_inspect_code','inspect_inputs.py'),('a_fetch_code','fetch_sources.py'),('a_report_code','write_report.py')]:art(id,rel,'code','Actual reviewer code for reproduction; contains no training or deployment action.')
sources=[]
def repo(id,rel,title,note):
 frozen='frozen/'+rel
 sources.append({'id':id,'kind':'repository_code','title':title,'verified':True,'path':PREFIX+'/'+frozen,'sha256':sha(OUT/frozen),'version':'This review frozen original bytes; SHA identifies the exact version. Relevant computation sources match both raw experiment code_sha256 maps.','inspection_note':note})
 art('a_'+id,frozen,'source_snapshot' if rel.endswith(('.json','.md')) else 'code',title+' original snapshot; copied bytes and SHA verified.')
repo('s_quant','tiny_perceptron/quantization.py','Original QuantizedLinear and int4 packing','AST located methods first; read lines 8-17, 29-64. Reduction is last input axis; scales/bias are buffers; forward reconstructs floating weights.')
repo('s_loss','tiny_perceptron/alignment.py','Original forward-KL distillation objective','Read lines 45-63; teacher detach, common temperature, vocabulary sum, mean valid labels and one T² factor.')
repo('s_train','scripts/course_experiments/capstone_student.py','Original CE/KD student recipe','Read _train_student and run computation lines 35-147,150-220; deep copy same initial model, same local sampler seed, 24-row batch, fixed teacher and 350-step recipe; no author result scope value read.')
repo('s_sampler','scripts/course_experiments/capstone.py','Original balanced sampling helper','Read _balanced_sample lines 62-67; category and row choices use provided Random instance.')
repo('s_core','tiny_perceptron/capstone.py','Original synthetic data, evaluation and tool runtime methods','Read default_config, build_dataset, evaluate_rows, parse_action, calculator_runtime and export_inference at read-scope locators; no model was reevaluated.')
repo('s_capquant','tiny_perceptron/capstone_quantization.py','Original capstone PTQ serialization and float reconstruction','Read quantizable_weights, tensor_bytes, quantize_capstone, restore_quantized_payload and load_quantized_capstone. Serialized bytes are reloaded; linear weights excluded from FP32 state but routers/biases/norms stay float32; reconstruction creates float32 model.')
repo('s_deploy','scripts/course_experiments/capstone_deployment.py','Original recommended-joint PTQ test protocol','Read run computation lines 272-310; joint source exported to packed bytes, reloaded and evaluated on same test split; omitted author interpretation/recommendation values.')
repo('s_public','scripts/capstone_release.py','Original public inference metadata normalization','Read PROVENANCE_KEYS subset and _metadata/clean_capstone_payload lines 79-93,121-168; allowlist changes metadata and clones contiguous tensor storage.')
for id,rel,title,note in [
 ('s_depraw','docs/course-experiments/results/capstone_deployment.json','Raw deployment receipt and measurements','Read only recorded schemas and named pointers in input-inspection.json; bytes equal the chapter-linked immutable GitHub version, SHA e1b37a0ec3b0aefa67254c1113813bfcef1e0f07874461c8a35d98a8486951e9.'),
 ('s_sturaw','docs/course-experiments/results/capstone_student.json','Raw student receipt and training provenance','Read only named raw/provenance pointers; bytes equal linked immutable version, SHA e724ae3fbe2aa967534a5d52da6a07cc7739121d0846f18a86936b8d0f73f993.'),
 ('s_prefraw','docs/course-experiments/results/capstone_preference.json','Raw DPO teacher export provenance','Read /results/stage and /results/inference_export/sha256; teacher SHA matches student report.'),
 ('s_joint','docs/course-experiments/capstone-evidence/deployment/test-joint.json','Original joint FP32 per-question test records','Read named record 20 and all raw record criteria/booleans/IDs for reaggregation; SHA matches deployment artifacts/24.'),
 ('s_ptq','docs/course-experiments/capstone-evidence/deployment/test-joint-ptq4.json','Original joint PTQ4 per-question test records','Read named record 20 and raw aggregates; SHA matches deployment artifacts/22.'),
 ('s_ce','docs/course-experiments/capstone-evidence/student/test-ce.json','Original CE student per-question test records','Read named record 6 and raw aggregates; SHA matches student artifacts/10.'),
 ('s_kd','docs/course-experiments/capstone-evidence/student/test-kd.json','Original KD student per-question test records','Read named record 6 and raw aggregates; SHA matches student artifacts/12.')]:repo(id,rel,title,note)
receipts=json.loads((OUT/'sources/receipts.json').read_text())
def official(id,file,title,note,version=None,kind='official_source',url=None):
 record=next((r for r in receipts if r['file']==file),None)
 sources.append({'id':id,'kind':kind,'title':title,'verified':True,'url':url or record['url'],'version':version or 'PyTorch installed 2.14.1+cpu immutable git revision 5c4886908584029761b579af026dcfb627c84070','authority_reason':'Original authors paper' if kind=='paper' else 'PyTorch maintainers official repository; source/docstring contract, not a search summary.','checked_original':True,'accessed_on':'2026-10-05','inspection_note':note,'snapshot_artifact_id':'a_'+id})
 art('a_'+id,'sources/'+file,'source_snapshot',title+' primary source; inspected locators recorded in the source and claims.')
official('s_qtdocs','pytorch-quantization.rst','PyTorch original quantization documentation','Read Introduction lines 12-40 and PTQ dynamic definition lines 152-163. Version 2.8.0 docs describe mature method categories; installed custom execution uses 2.14.1+cpu and is not equated to official INT8 kernels.','PyTorch v2.8.0 release tag docs/source/quantization.rst')
official('s_linear','pytorch-linear.py','Official installed-version Linear contract','Read Linear lines 53-140: y=x A transpose+b; weight(out,in), bias(out); official fetched bytes exactly match installed source.')
official('s_module','pytorch-module.py','Official installed-version buffer contract','Read register_buffer 528-590 and buffers 2731-2752; ordinary persistent tensor buffers are iterated. Fetched bytes exactly match installed source.')
official('s_tensor','pytorch-tensor-docs.py','Official tensor byte-size documentation','Read element_size 1726-1744 and nbytes 6753-6768; bytes per element, nbytes=numel*element_size for dense tensor views.')
official('s_api','pytorch-torch-docs.py','Official quantization and reduction API docstrings','Read amax 7064-7106, numel 8815-8832, round 9898-9917, dequantize 3620-3638, quantize_per_tensor/per_channel 13808-13904; grouped ordinary API coverage, axes and scale representation.')
official('s_klapi','pytorch-functional.py','Official installed-version KL API contract','Read kl_div lines 3401-3475; input log probabilities, target probabilities, reduction none retains per-coordinate values.')
official('s_hinton','hinton-1503.02531v1.pdf','Hinton, Vinyals and Dean: Distilling the Knowledge in a Neural Network','Personally read extracted original PDF pages 1-3, arXiv v1 first-page identifier, Introduction and Section 2; small student, common softmax temperature, weighted hard/soft objectives and T² scaling. Original PDF bytes copied unchanged from locator and SHA verified.','arXiv:1503.02531v1, 9 March 2015','paper','https://arxiv.org/pdf/1503.02531v1')
art('a_hinton_text','sources/hinton-1503.02531v1.txt','source_snapshot','Actual pdftotext -layout original extraction; pages 1-3 personally read.')
sources.extend([{'id':'s_original_execution','kind':'execution','title':'Exact original fence CPU execution','verified':True,'artifact_id':'a_original'},{'id':'s_cpu','kind':'execution','title':'Bounded independent reviewer verification','verified':True,'artifact_id':'a_cpu'},{'id':'s_math','kind':'derivation','title':'Independent axes, bytes, output-error and KD algebra','verified':True,'details':'See calculation.md. FP32=(32+4)*4=144; int4=32/2+4*4+4*4=48; int8=32+16+16=64; weight axes(out,in)=(4,8); output max over one sample and four output coordinates; KL sums vocabulary and averages valid positions, multiplied once by T².'}])
claims=[]
def evidence(source,locator,supports):return {'source_id':source,'locator':locator,'supports':supports}
def claim(id,kind,statement,location,scope,evidences,artids,expected=None,observed=None,details=None,tolerance=None,denominators=None):
 c={'id':id,'kind':kind,'statement':statement,'location':location,'scope':scope,'status':'verified','evidence':evidences,'artifact_ids':artids}
 if kind in ['numeric','software','empirical']:
  c['verification']={'method':'executed','expected':expected,'observed':observed,'details':details}
  if kind=='numeric':c['verification']['tolerance']=tolerance
  if kind=='empirical':c['verification']['denominators']=denominators
 claims.append(c)
claim('c1','concept','量化以較低位元近似同一結構的數值；蒸餾讓較小學生學教師訊號。刻度及反量化在本節沿用對稱整數碼乘刻度的意義。','19.10 opening and scale paragraph','Method distinction and this symmetric scale example; no guarantee every compression method preserves architecture or all capabilities.',[evidence('s_qtdocs','Introduction lines 15-39; PTQ lines 152-159','Lower-bit representation and quantizing already trained weights.'),evidence('s_hinton','Introduction p1-2 and Section 2 p2-3','Transfer teacher output distributions to a smaller model.'),evidence('s_api','dequantize 3620-3638; quantize_per_tensor/per_channel 13808-13904','Original quantization scale/zero-point and restored FP32 contracts.'),evidence('s_quant','quantize_symmetric lines 8-17; forward lines 58-61','Custom symmetric reconstruction q*scale, with zero offset.'),evidence('s_math','calculation.md scale paragraph','2*0.5=1.0.')],['a_math','a_s_hinton','a_s_qtdocs'])
claim('c2','numeric','FP32的32個權重加4個bias共144 bytes；逐输出列的4個FP32刻度與4個FP32 bias各16 bytes；4-bit總48 bytes，8-bit總64 bytes。','19.10 fence, storage explanation and bits=8 exercise','Dense buffer/parameter payload only. Weight=(4,8); scales=(4,1), not eight input-column scales. Neither Python object overhead nor file metadata is counted.',[evidence('s_linear','Linear docstring and __init__ lines 53-115','Weight axes(out,in) and four bias values.'),evidence('s_quant','quantize_symmetric 8-17, packing29-44, __init__50-56, storage_bytes63-64','Last-axis per-output scale and two int4 nibbles per uint8; buffer sum.'),evidence('s_tensor','element_size 1726-1744; nbytes 6753-6768','FP32/uint8 bytes and numel*element_size accounting.'),evidence('s_api','numel8815-8832; amax7064-7106','Element count and reduction axis.'),evidence('s_cpu','verify.results.json /fp32_bytes and /quantization/{4,8}/buffers','Observed byte/dtype/shape breakdown.'),evidence('s_math','calculation.md first three paragraphs','144/48/64 hand arithmetic.')],['a_original','a_cpu','a_values','a_math'],'144,48,64 bytes; values16/32 bytes, scales16,bias16.','Exact: 144,48,64; scale shape4x1 FP32.','Counts were recomputed independently from actual buffers and asserted; packing roundtrip checked including odd padding.','Exact integer equality; reconstructed floating outputs tolerance1e-7.')
claim('c3','software','原程式在固定種子的一層Linear上做前向差值檢查，沒有訓練；最大輸出差僅針對八個1這一筆輸入的四個輸出座標。','19.10 original fence and single-input caution','No rate or model-wide quality metric. Error unit is absolute linear activation difference, and .max has no sample-accuracy denominator.',[evidence('s_original_execution','original-fence stdout/environment; attempted_fences=[1]','Exact unchanged fence ran with no guard events on CPU.'),evidence('s_linear','Linear equation and output shape lines53-80','One1x8 input gives1x4 output.'),evidence('s_quant','forward58-61','Same bias; output computed using restored weights.'),evidence('s_cpu','verify.results.json /input and /quantization/{4,8}/absolute_output_error,max_error,manual_output','Independent x@weight.T+b reconstruction and error-axis check.')],['a_original','a_cpu','a_values','a_math'],'One1x8 sample, four output coordinates, no optimizer/update; max differs after quantization.','FP32 output1x4; int4 max0.046346306800842285; int8 max0.0037038326263427734.','Exact fence executed; independent formula agrees within1e-7. Higher-bit error was smaller for this fixed input only.')
claim('c4','software','此可讀量化forward先還原浮點權重；舊capstone打包載入也重建FP32，不能從檔案縮小直接推出低位元kernel加速或峰值記憶體八分之一。','19.10 storage caution, deployment paragraph and supplemental packing paragraph','Implementation limitation, not a speed benchmark or new deployment acceptance.',[evidence('s_quant','QuantizedLinear forward58-61','q*scale restored to x dtype before F.linear.'),evidence('s_capquant','restore_quantized_payload117-184 and load187-189','Float32 architecture/state reconstruction; routers and unquantized states retained FP32.'),evidence('s_qtdocs','Introduction15-39','Official speed benefits describe actual hardware lower-precision operations, not custom float reconstruction.'),evidence('s_cpu','verify.results.json buffers/manual outputs and independent activation calculation','Observed FP32 scale/bias and reference float operation match.')],['a_cpu','a_values'],'Custom kernel path uses floating reconstruction and does not measure speed/peak memory.','Original computation matches independent FP32 matrix expression; no specialized integer kernel call in inspected forward or restore.','Read actual computation branches and checked forward numerically. Whole-assistant storage/loading/peak requirements remain future work.')
claim('c5','software','舊KD配方是0.5 CE+0.5 T² KL(teacher||student)，T=2；教師固定，內部只乘一次T²。','19.10 Dense-student recipe paragraph','This repository objective, not a universal recommended alpha. KL sums vocabulary and averages only valid answer tokens; CE uses ground-truth labels.',[evidence('s_hinton','Section2 pages2-3','Common teacher/student temperature and weighted hard/soft targets; T² scaling.'),evidence('s_loss','distillation_kl45-55 and distillation_loss58-63','Teacher detach, KL direction, answer-token denominator and internal T².'),evidence('s_klapi','kl_div3401-3475','log-q input and p target; reduction none retains values.'),evidence('s_train','run teacher.freeze167-176; objective96-106','No teacher gradients, alpha0.5 and temperature2.0 in original recipe.'),evidence('s_cpu','verify.results.json /distillation','Independent explicit p*(logp-logq) expression and teacher-gradient check.')],['a_cpu','a_values','a_math'],'Mixed loss equals0.5 CE+0.5*4*mean_valid(sum_vocab p(logp-logq)); teacher.grad=None.','Independent expression and helper match within1e-7; valid-token count2, vocab3, T2; teacher.grad=None.','Tiny CPU expression check ran without optimizer; teacher entropy difference explains Hinton soft-CE/forward-KL equivalence for fixed teacher.')
claim('c6','empirical','舊推薦joint量化已存檔重載並檢查同一最後題目；原本請算1加0的最終答案111，4-bit為11，兩者皆錯而總分仍同。','19.10 supplemental PTQ paragraphs','Original saved experiment only; all90 rows reaggregated, not new inference. Equality of total score does not imply equality of generated tokens.',[evidence('s_deploy','run272-310','Quantize source, reload saved file, evaluate same splits[test].'),evidence('s_capquant','quantize_capstone87-114; load187-189','Save bytes, reload bytes; finite-logit validation in original method.'),evidence('s_depraw','/artifacts/22,/artifacts/24; /results/joint_ptq/joint-int4','Original exact per-question file hashes and aggregate/provenance.'),evidence('s_joint','/records/20/runtime,/final_trace/raw,/answer,/end_to_end_correct; /count','FP32 calculator result1 but final DIRECT:111, wrong.'),evidence('s_ptq','same /records/20 pointers; /source_checkpoint_sha256','Int4 calculator result1 but DIRECT:11; same joint source, wrong.'),evidence('s_cpu','verify.results.json /saved_evaluations and /named_records/{joint,int4}','All raw criteria, by-task counts and source/SHA matches independently checked.')],['a_cpu','a_values','a_inspection'],'Same90 IDs; equal aggregates can accompany different generated final answers, both wrong for expected1.','Both80/90 exact actions and78/90 end-to-end; named row20 gives111 versus11; source checkpointSHA identical.','Recomputed raw booleans, aggregate sums, per-task counts and tool runtime outputs. Exact original record-file SHAs match pinned deployment receipt.',denominators={'saved_test_rows_per_version':90,'named_example_records_per_version':1,'model_inference_reruns':0})
claim('c7','software','CE/KD學生使用DPO教師分支，同一份隨機Dense起點、相同抽樣種子和24筆批次規則，各350次更新；報告没有逐批GPU取樣清單，KD多了教師前向。','19.10 supplemental student protocol paragraphs','Original recipe and stored provenance support these controls; no claim of independently replaying or verifying every historical GPU batch.',[evidence('s_train','_train_student35-55,91-106; run150-187','Deepcopy initial each branch, local Random(seed+5000), batch24, frozen DPO teacher, width48 Dense config,350 steps.'),evidence('s_sampler','_balanced_sample62-67','Same provided sampler applied to same rows and task grouping.'),evidence('s_sturaw','/results/initial_student_state_sha256,/teacher_checkpoint_sha256,/steps_per_branch,/branches/{ce,kd}/{steps,parameters,effective_tokens}','Shared initialization/teacher provenance;350 actual/requested steps, Dense experts0, both145163 effective tokens.'),evidence('s_prefraw','/results/stage and /results/inference_export/sha256','DPO inference SHA equals student teacher SHA.'),evidence('s_cpu','verify.results.json /student_provenance,/code_provenance_matches,/dataset_method_check','Recorded code hashes match originals; student manifests match deterministic data method.')],['a_cpu','a_values','a_inspection'],'Both Dense48 branches350 steps with common teacher/input recipe; teacher forward onlyKD; original logs contain aggregates/history but no per-step sampled IDs.','Both requested/completed350; same Dense79,920 params, common teacherSHA b2428be8..., common initial-stateSHA, both145,163 valid training tokens.','Checked source computation and actual raw provenance; original per-batch GPU sample trace was not present or claimed. No training occurred in this review.')
claim('c8','empirical','原1+8例中CE請求calculator:1+8、讀回9並答9；KD請求1+9、讀回10並答11，請求參數與讀回答案兩層均錯。','19.10 supplemental named CE/KD example','One original held-out example. It illustrates a failure mechanism and does not rank every Dense or distillation recipe.',[evidence('s_ce','/records/6/action_trace/raw,/runtime,/final_trace/raw,/answer','CE action1+8, return9, answer9.'),evidence('s_kd','same /records/6 pointers, /expected_action,/expected_final','KD action1+9, return10, answer11 while truth9.'),evidence('s_core','calculator_runtime564-574 and evaluate_rows499-547','Runtime adds requested integers; exact expected action and final answer are distinct criteria.'),evidence('s_sturaw','/artifacts/10 and /artifacts/12','Exact original per-question SHAs.'),evidence('s_cpu','verify.results.json /named_records/{ce,kd}; saved_evaluations','Named row and independently reaggregated raw records.')],['a_cpu','a_values','a_inspection'],'For expected1+8 final9,CE action/final correct; KD wrong ordered arguments and wrong readback10→11.','CE record6 actionTOOL:calculator:1+8,runtime9,answer9; KD record6 actionTOOL:calculator:1+9,runtime10,answer11.','Actual calculator runtime recomputed from parsed actions; four original record sets checked by documented criteria. No model scores reevaluated.',denominators={'test_records_per_student':90,'named_example_per_student':1,'trained_student_updates_per_branch':350,'review_training_updates':0})
claim('c9','software','測試包包含容器、結構與來源metadata；公開整理附加資訊後檔案bytes/指紋可能不同，应依正式清單核下載。','19.10 supplemental public-file paragraph','Packaging/metadata contract only. This review does not accept new public model weights, test a download, or claim a particular public file size.',[evidence('s_capquant','quantize_capstone payload61-90','Config/tokenizer/model/stage/quantization and metadata serialized together.'),evidence('s_core','export_inference655-694','Inference export has controlled metadata and source SHA.'),evidence('s_public','_metadata79-93; clean_capstone_payload121-168','Whitelist, data-manifest digest and contiguous cloned storage normalise public contents.'),evidence('s_cpu','verify.results.json /metadata_normalization','Actual metadata method invoked; before/after dictionaries differ in in-memory serialization.')],['a_cpu','a_values'],'Metadata normalization removes training history/full manifest and retains selected provenance; serialized bytes may change.','Actual whitelist retainedseed anddataset_manifest_sha256, removed training_history/data_manifest; BytesIO bytes differed.','Only metadata dictionaries were serialized in memory; no .pt/model file or public release was created.19.11 manifest acceptance is outside this section review.')
claim('c10','software','舊實驗僅為固定預算合成任務；本節未量學生推論速度或生成峰值，完整新助手壓縮驗收及新路線仍是待做設計。','19.10 deployment requirements and final supplemental limitations','Original evidence scope and future instructions, with no new-model capability acceptance. Smaller parameter count does not identify latency or peak generation memory.',[evidence('s_core','build_dataset139-282; default_config34-48','Synthetic0..9 templates, RGB shapes/tones and family splits define bounded old task.'),evidence('s_train','run150-220 and _train_student metrics125-147','Student reports training elapsed, params/tokens and quality records, not generation-speed/peak benchmarks.'),evidence('s_deploy','benchmark methods AST locations150-269; run323-358','Deployment benchmarks concern separate recommended model/mechanism comparisons, not new student inference metrics.'),evidence('s_cpu','verify.results.json /dataset_method_check and /student_provenance','Original data construction matches both saved manifests; training/test scope preserved.')],['a_cpu','a_values','a_scope'],'Old deterministic synthetic manifests and existing metrics only; no new compression capability claim.','Manifest counts and family separation matched original reports;90 test records each; student350 steps each; review0 training/model reruns.','Read general data/method restrictions and independently checked underlying generation/data matching. New assistant storage/reload/EOS/modal/tool checks were not undertaken.')

report={'schema_version':1,'review_stage':'technical','lesson_id':'19.10','source':'course/chapters/19.md#19.10','source_sha256':source_hash,'figure_sha256':{},'verdict':'pass','reviewer_task':TASK,'reviewer_context':'fresh','reviewed_on':'2026-10-05','read_scope_artifact_id':'a_scope','frozen_input':scope['frozen_inputs'][0],'sources':sources,'artifacts':artifacts,'claims':claims,'issues':[],
 'checks':{
 'factual_accuracy':{'status':'pass','details':'All substantive section claims independently checked: representation/teacher distinction, exact storage, output-error scope, float reconstruction, KD direction/denominator, old PTQ/student examples, packaging and limits. No substantive correction needed.','claim_ids':[c['id'] for c in claims]},
 'numeric_verification':{'status':'pass','details':'Exact144/48/64 byte counts and4x1 scale axis; one1x4 output max, CPU4-bit0.046346306800842285 and8-bit0.0037038326263427734. All90 original records per file and per-task totals reaggregated;350 branch steps and teacher/source provenance checked.','claim_ids':['c2','c3','c5','c6','c7','c8']},
 'figure_consistency':{'status':'not_applicable','details':'No figure is referenced in19.10; raw section inspected and helper returnedzero SVG references. No render/view is applicable.','claim_ids':[]},
 'source_verification':{'status':'pass','details':'Personally read original Hinton v1 pages1-3 and official PyTorch source/docstrings at immutable installed revision; v2.8 quantization method docs kept distinct. Primary URL/version/hash receipts and exact pinned linked-report matches preserved. Old source locators were used only to locate originals.','claim_ids':['c1','c2','c3','c4','c5','c6','c7','c8','c9','c10']},
 'limitations':{'status':'pass','details':'One-layer CPU demo is not assistant accuracy; bytes count tensor payload rather thanfile/object overhead. Stored old synthetic results are not retraining, per-batch GPU replay, new model acceptance, student inference benchmarks or a universal distillation comparison. All future checks remain plans.','claim_ids':['c3','c4','c6','c7','c8','c9','c10']}
 }}
assert report['reviewer_task']==TASK
(ROOT/'docs/technical-reviews/19.10.json').write_text(json.dumps(report,ensure_ascii=False,indent=2,allow_nan=False)+'\n')
print(json.dumps({'canonical_reviewer_task_asserted':TASK,'source_sha256':source_hash,'verdict':'pass','report_sha256':sha(ROOT/'docs/technical-reviews/19.10.json'),'claims':len(claims),'unresolved':0},ensure_ascii=False))
