"""Create this review's complete canonical report without reading its predecessor."""
import hashlib
import json
from pathlib import Path
import re

A=Path(__file__).resolve().parent
ROOT=A.parents[3]
def sha(p): return hashlib.sha256(p.read_bytes()).hexdigest()
def rel(p): return p.relative_to(ROOT).as_posix()
raw=(ROOT/'course/chapters/13.md').read_bytes()
headers=list(re.finditer(rb'(?m)^## [^\r\n]+',raw))
i=next(i for i,h in enumerate(headers) if h[0].startswith(b'## 13.10 '))
section=raw[headers[i].start():headers[i+1].start() if i+1<len(headers) else len(raw)]
assert section==(A/'inputs/section-13.10.md').read_bytes()
source_sha=hashlib.sha256(section).hexdigest()
cpu=json.loads((A/'execution/cpu-results.json').read_text())
env=json.loads((A/'execution/environment.json').read_text())
render=json.loads((A/'render/render-result.json').read_text())
assert render['exit_code']==0 and not render['timed_out']
assert cpu['original_fence_exit_code']==0
artifacts=[]
def artifact(id,file,kind,description,**kw):
    p=A/file
    artifacts.append(dict(id=id,path=rel(p),sha256=sha(p),kind=kind,description=description,**kw))
artifact('frozen_section','inputs/section-13.10.md','source_snapshot','完整原始 UTF-8 小節 bytes，包含標題與原換行。')
artifact('frozen_chapter','inputs/chapter-13.frozen-input.md','source_snapshot','初次讀取當次的 full-file frozen input snapshot；不是聲稱後來的整章版本或整章親讀。')
artifact('extraction','inputs/extraction.json','source_snapshot','原 bytes 擷取事實；source_file_sha256 僅對應 frozen_chapter 當次快照。')
artifact('fence_code','inputs/fence-1.py','code','親跑的未改動原 Python fence。')
artifact('method_code','inputs/posttraining-experiment.py','code','完整原方法 bytes；實際親讀 AST 限定行段詳 own_inspection，未讀結果說明字典。')
artifact('helper_code','inputs/posttraining-module.py','code','偏好代價與有限評分模型的原始契約。')
artifact('raw_results','inputs/posttraining-results.raw.json','source_snapshot','未刪改的既有原 JSON；只檢查 cpu_results 指定 pointers，沒有讀附加摘要。')
artifact('paper_pdf','sources/instructgpt-2203.02155v1.pdf','source_snapshot','原論文 v1 PDF，與本次 arXiv 下載原 bytes/hash 相同。')
artifact('paper_method','sources/instructgpt-pages6-7.txt','source_snapshot','原論文 printed pp.6–7 的方法與真人 labeler 原文。')
artifact('paper_loss','sources/instructgpt-pages8-9.txt','source_snapshot','原論文 §3.5 Eq.(1)、score 差的 log odds 和 reward shift invariance 原文。')
artifact('torch_functional','sources/torch-functional.py','source_snapshot','親取 PyTorch 安裝 git revision 的官方 functional.py；親讀 logsigmoid 精確定位。')
artifact('torch_docs','sources/torch-docs.py','source_snapshot','親取相同 revision 官方 API 原文；tensor/sigmoid/mean 合組 coverage。')
artifact('cpu_code','execution/verify_cpu.py','code','本人的有界 CPU 原 fence、變體、資料契約與原測量重算程式；不載入既有模型。')
artifact('cpu_results','execution/cpu-results.json','execution','原 fence 子程序與獨立數值/樣本/分母/凍結契約實跑結果。',command='.venv/bin/python docs/technical-reviews/artifacts/phase4-13_10-independent/execution/verify_cpu.py > docs/technical-reviews/artifacts/phase4-13_10-independent/execution/cpu.stdout.txt 2> docs/technical-reviews/artifacts/phase4-13_10-independent/execution/cpu.stderr.txt',result='exit 0；全部 assertion 通過；原 fence stdout 精確相等；沒有完整訓練或既有模型評測。',environment=env)
artifact('cpu_stdout','execution/cpu.stdout.txt','source_snapshot','真執行完整 stdout，包含具名原測量重算、實際指標與 pointers。')
artifact('cpu_stderr','execution/cpu.stderr.txt','source_snapshot','真執行 stderr（空）。')
artifact('fence_stdout','execution/fence.stdout.txt','source_snapshot','原 fence 子程序真 stdout；兩行教材輸出精確相同。')
artifact('environment','execution/environment.json','source_snapshot','實際 .venv/Python/PyTorch/git/device/CPU threads。')
artifact('commands','execution/commands.json','source_snapshot','實際擷取、CPU、原文下載與 pdftotext 命令/exit 記錄。')
artifact('own_inspection','own-inspection.md','derivation','本人讀取範圍、逐主張原文支持、推導、畫面觀察與限制。')
artifact('render_code','render/render_section.py','code','本人只渲染 frozen section 的有界 Playwright 程式。')
artifact('render_html','render/section.html','source_snapshot','本人實際載入 Chromium 的 section-only HTML。')
artifact('desktop','render/section-1280.png','figure_render','真 Chromium 1280×800 viewport 截图（完整頁），已用 view_image 親看。')
artifact('mobile','render/section-390.png','figure_render','真 Chromium 390×844 viewport 截圖（完整頁），已用 view_image 親看。')
artifact('render_success','render/render-result.json','execution','page.set_content 載入同份 HTML 後成功渲染，未 timeout。',command='.venv/bin/python docs/technical-reviews/artifacts/phase4-13_10-independent/render/render_section.py',result='exit 0；Chromium 151.0.7922.173；兩份 PNG 完成並親看。',environment=dict(python='3.13.5',playwright='1.63.0',markdown='3.11',chromium='151.0.7922.173',device='CPU/headless'))
artifact('render_stdout','render/chromium.stdout.txt','source_snapshot','真 Chromium stdout 的 viewport、內容字數、page height 及版本。')
artifact('render_attempt1','render/attempt1-render-result.json','execution','第一個真 Chromium 嘗試：browser 成功啟動，file URL 被 administrator block；不是 timeout。',command='.venv/bin/python docs/technical-reviews/artifacts/phase4-13_10-independent/render/render_section.py (first implementation used page.goto(file URI); exact known code retained in render-attempt1.py)',result='worker exit 1；net::ERR_BLOCKED_BY_ADMINISTRATOR；1.44 秒，timed_out=false。',environment=dict(python='3.13.5',playwright='1.63.0',markdown='3.11',device='CPU/headless'))
artifact('attempt1_code','render/render-attempt1.py','code','第一次真嘗試的原 page.goto 程式：依已記錄的一行 patch 還原，詳 own_inspection。')
artifact('attempt1_stderr','render/attempt1-chromium.stderr.txt','source_snapshot','第一個真失敗的完整錯誤 trace，未改写为 timeout。')
artifact('generation_code','generate_report.py','code','本人產生完整新 canonical 的程式，不讀前任報告。')

sources=[
 dict(id='instructgpt',kind='paper',title='Ouyang et al., Training language models to follow instructions with human feedback',verified=True,url='https://arxiv.org/pdf/2203.02155v1',version='arXiv:2203.02155v1 [cs.CL], 4 Mar 2022',accessed_on='2026-10-05',authority_reason='原作者發布的 arXiv 精確 v1 原論文；第一頁版本獨立親核，重抓 PDF bytes 與永久原檔相等。',checked_original=True,inspection_note='親讀標題/版本和原紙 §3.1 pp.6、§3.4 p.7、§3.5 pp.8–9（Eq.(1)、reward difference log odds、shift invariant loss）。逐 claim 支持範圍在各 evidence 明列。'),
 dict(id='torch_functional_source',kind='official_source',title='PyTorch functional.logsigmoid official implementation and docstring',verified=True,url='https://raw.githubusercontent.com/pytorch/pytorch/5c4886908584029761b579af026dcfb627c84070/torch/nn/functional.py',version='pytorch/pytorch immutable commit 5c4886908584029761b579af026dcfb627c84070; installed torch 2.14.1+cpu',accessed_on='2026-10-05',authority_reason='PyTorch 官方 repo，git revision 與本次 .venv 安裝 torch.version.git_version 相同。',checked_original=True,inspection_note='本次親取 raw 原檔；AST 定位後讀 lines 2049–2058 的 logsigmoid 原文與公式，不以最新版未釘版文件推定安裝契約。'),
 dict(id='torch_api_source',kind='official_source',title='PyTorch tensor/sigmoid/mean related API group',verified=True,url='https://raw.githubusercontent.com/pytorch/pytorch/5c4886908584029761b579af026dcfb627c84070/torch/_torch_docs.py',version='pytorch/pytorch immutable commit 5c4886908584029761b579af026dcfb627c84070; installed torch 2.14.1+cpu',accessed_on='2026-10-05',authority_reason='PyTorch 官方 repo 同安裝 git revision 的原 API docstrings。',checked_original=True,inspection_note='本次親取 raw；AST 定位並讀 tensor 9582–9616（default requires_grad=False）、sigmoid 10211–10218（expit alias）、mean 7195–7228（whole tensor/all elements reduction）；相關 API 同組並逐項明列 coverage。'),
 dict(id='local_helper',kind='repository_code',title='Original preference_loss and FiniteRewardModel contracts',verified=True,path='tiny_perceptron/posttraining.py',sha256=sha(ROOT/'tiny_perceptron/posttraining.py'),version='Original current file bytes frozen as inputs/posttraining-module.py',inspection_note='親讀 lines 1–86；實質核查 preference_loss 8–12 和 FiniteRewardModel 64–75。'),
 dict(id='local_method',kind='repository_code',title='Original finite preference task data, training and evaluation method',verified=True,path='scripts/course_experiments/posttraining.py',sha256=sha(ROOT/'scripts/course_experiments/posttraining.py'),version='Original current bytes frozen as inputs/posttraining-experiment.py; matching saved results code_sha256',inspection_note='AST 限定後親讀 31–129、188–253、256–272、299–365；只執行 data/rule/split helper definitions；沒有讀結果説明字典 461–533 或呼叫 run_posttraining。'),
 dict(id='raw_saved_measurement',kind='repository_code',title='Original saved finite preference experiment measurements',verified=True,path='docs/course-experiments/results/posttraining.json',sha256=sha(ROOT/'docs/course-experiments/results/posttraining.json'),version='Raw unchanged JSON frozen as inputs/posttraining-results.raw.json; code hashes and installed CPU versions matched',inspection_note='先 key/type，後只按 cpu-results.json /raw_json_pointers 親讀具名原測量/樣本/方法/provenance；重算 owners、660/75/90 對、score comparisons、300×64 processed draws；未讀額外 author scope/notes/summary。'),
 dict(id='own_math',kind='derivation',title='Independent scalar preference and quantity ambiguity derivation',verified=True,details='d=c-r; p=1/(1+exp(-d)); L=log(1+exp(-d)); dL/dd=-1/(1+exp(d))<0; common shift cancels. For unit price 1 yuan, shipping 2 yuan, quantity q=1 vs q=2 gives totals 3 vs 4 yuan, proving supplied inputs do not imply a unique total. 詳 own-inspection.md，數值由 math 與 CPU 交叉核。'),
 dict(id='cpu_execution',kind='execution',title='Fresh bounded .venv CPU verification and original-measurement recomputation',verified=True,artifact_id='cpu_results'),
]
def ev(source,locator,supports):return dict(source_id=source,locator=locator,supports=supports)
claims=[]
def claim(id,kind,statement,location,scope,evidence,artifact_ids,verification=None):
    c=dict(id=id,kind=kind,statement=statement,location=location,scope=scope,status='verified',evidence=evidence,artifact_ids=artifact_ids)
    if verification is not None:c['verification']=verification
    claims.append(c)
def verification(expected,observed,details,**kw):return dict(method='executed',expected=expected,observed=observed,details=details,**kw)

claim('reward_role','concept','偏好比較可訓練另一個獎勵模型；它接收問題和回答，輸出估計偏好適合度的 scalar 分數，與未來回答的 policy 分開。','13.10 第一段','一般 reward modeling 概念；有限示範的特徵輸入另由 finite_features 限定。',[ev('instructgpt','§3.1 printed p.6 Steps 2–3; §3.5 printed p.8 Reward modeling','比較資料訓練 RM，prompt+response 輸入 scalar reward，再由 PPO 更新回答 policy，角色分開。')],['paper_method','paper_loss','own_inspection'])
claim('pair_objective','concept','同題較佳與較差分數之差 d 的 sigmoid 是較佳被偏好勝出的模型機率；取負 log 作偏好代價，這不是內容正確率。','13.10 第二段','Bradley–Terry 型 pairwise preference model 的語義，沒有將預測 preference 機率當實測 content correctness。',[ev('instructgpt','§3.5 printed p.8 Reward modeling and Eq.(1)','reward 差是 preferred choice log odds，標籤是 human comparison；負 log sigmoid reward difference。'),ev('local_helper','preference_loss lines 8–12','本示範實作 -F.logsigmoid(chosen-rejected).mean()。')],['paper_loss','helper_code','own_inspection'])
claim('numbers_and_exercise','numeric','差 0 和 2 的機率/代價約為 (0.5,0.6931)、(0.8808,0.1269)；rejected 改 1 時差為 -1、1，機率約 0.2689、0.7311；双分數加 10 結果不變。','13.10 第二段、原 fence、輸出段與練習','每個 fence tensor 只有一對分數；浮點算例，不是訓練或模型 accuracy。',[ev('cpu_execution','cpu-results.json /original_fence_stdout, /variants, /mean_reduction','原 float32 fence 實跑精確印兩行；float64 與獨立 Python math 親算四個 d，shift 同值；另核全元素 mean 分母 4。'),ev('own_math','own-inspection.md Independent calculation','p(d) 與 L(d) 的獨立公式。'),ev('torch_functional_source','functional.py lines 2049–2058','官方 elementwise log-sigmoid 定義。'),ev('torch_api_source','_torch_docs.py 7195–7228; 10211–10218','全元素 mean reduction、sigmoid expit alias。')],['fence_code','fence_stdout','cpu_code','cpu_results','torch_functional','torch_docs'],verification('正文 4-decimal values 與 shift invariance','0.5/0.6931471805599453；0.8807970779778823/0.1269280110429725；0.2689414213699951；0.7310585786300049；shift losses exactly equal','原 fence 原封親跑，再獨立 float64/math；mean grid 0.6116496416598409 vs expected 0.6116496416598408，分母 4。',tolerance='float64/math abs_tol=1e-14；正文四捨五入 abs_tol=0.00005；shift 精確相等。'))
claim('score_interpretation','concept','較佳相對分數提高會降低偏好代價；分數共同平移不改代價，因此原分數 3 不能解讀為三成正確或比 1 多懂三倍。','13.10 輸出段','latent scalar 的偏好相對量；不聲稱以玩具數據證明全面 calibration 結論。',[ev('instructgpt','§3.5 printed pp.8–9: log odds and loss invariant to reward shifts','pairwise loss 只約束相對 reward 差，原文明說 shift invariance。'),ev('own_math','own-inspection.md derivative dL/dd and shift equation','dL/dd<0；絕對零點任意，不能推導概率百分比或比率式語義。'),ev('cpu_execution','cpu-results.json /gradient_check and /variants','gradient 方向與共同 shift 不變實際核對；零參數更新。')],['paper_loss','cpu_results','own_inspection'])
claim('fence_scope','software','原 Python fence 用手設 score 示範概率與偏好代價，只做計算與 print，沒有訓練 reward model。','13.10 原 Python fence','完整原 fence 行為與 preference_loss 契約；不把 backward 示範或更低代價寫成學會。',[ev('local_helper','preference_loss lines 8–12','輸入 score tensors 並做平均負 log sigmoid，沒有 optimizer。'),ev('torch_api_source','_torch_docs.py tensor lines 9582–9616','torch.tensor 默認沒有 autograd history/requires_grad=False。'),ev('cpu_execution','cpu-results.json /original_fence_command, /original_fence_exit_code, /original_fence_stdout','真執行原 fence，只印分數差、機率和代價。')],['fence_code','fence_stdout','cpu_results'],verification('只印两行算例，无更新','exit 0；两行精確相等；原碼沒有 backward/optimizer','原 fence 使用 repository helper；另補梯度檢查明確 parameter_updates=0，不冒充 training。'))
claim('finite_features','software','四張候選由 Python 預寫與預算答案；number 選 0、explain 選 1；小網路讀人工題目條件和卡號特徵，不讀中文，偏好由固定作者規則產生，沒有招募真人。','13.10 四卡表、選卡規則與小網路段','有限候選選擇任務；這些候選含正確答案不表示 policy 自行加法或生成答案。',[ev('local_method','rule_best_action 58–60; build_records 63–106; _features 124–125','best actions、完整候選 templates、預算 a+b、四 numeric features 和規則 pair labels。'),ev('local_helper','FiniteRewardModel 64–75','context features concat candidate_identity one-hot；輸入沒有中文字串。'),ev('cpu_execution','cpu-results.json /samples and /feature_contract','pair:1:2 四卡逐字相同，best actions [0,1,3]；hook 親驗 3×4×8 numeric context+identity，輸出 3×4。')],['method_code','helper_code','cpu_code','cpu_results'],verification('table cards and rule outputs match; no text input','四卡 3 / 1 加 2 是 3。 / 4 / 請再提供更多資訊。；context (3,4), first input (3,4,8), scores (3,4)','只執行原 data helpers、fresh untrained network forward hook，不載入既有模型或跑訓練。'))
claim('missing_quantity','numeric','單價 1 元、運費 2 元而未給數量，應選求補數量的 3 號卡；單價加運費不足以確定總價。','13.10 四卡表後的缺數量例子','正單價簡單總價情境：缺 quantity；missing-mode 卡 3 與 addition-mode 泛問資訊卡 3 是不同模板。',[ev('own_math','own-inspection.md quantity q=1 vs q=2','總價 1×q+2；q=1 為 3 元，q=2 為 4 元，題面无法排除其中任一個。'),ev('local_method','build_records 68–79 and rule_best_action 60','missing template、最佳卡 3 請補充購買數量、候選其他卡擅自用 a+b。'),ev('cpu_execution','cpu-results.json /samples/2','原 record 的 quantity clarification candidate 和 expected_action=3 親核。')],['cpu_results','own_inspection'],dict(method='hand_calculation',expected='未知 q 導致至少兩個可行不同總價；missing 卡 3 求數量',observed='q=1: 1元/件×1件+2元=3元；q=2: 1元/件×2件+2元=4元；原 record best=3',details='本人獨立代入並核單位：單價不是總商品額，运费为固定2元；原数据模板由 CPU 親核。',tolerance='整數算術與卡號精確相等。'))
claim('training_and_split_contract','software','原方法用訓練家族偏好對更新 RM，再凍結供 PPO 使用；數字對調不會將同一加數家族分到 train 和 final test 兩邊。','13.10 補充第一、二句','檢查原資料與訓練方法契約，以及保存結果的 provenance；没有重新訓練或評測既有模型。',[ev('local_method','build_records 67–68, family line 94; split_records 109–121; run_posttraining 265–270, 303–314, 335–345','a≤b only enumerates unordered families；整家族 split；x/pairs 只來 train；更新後 requires_grad_(False).eval()；PPO no_grad 讀 frozen RM scores。'),ev('local_helper','FiniteRewardModel.forward 72–75','numeric feature score forward 契約。'),ev('cpu_execution','cpu-results.json /measurements and /feature_contract; /provenance/code_sha256','AST helper 真產 44/5/6 家族、132/15/18 contexts、660/75/90 pairs，无跨 split 家族；pair:1:2 reserved test；fresh freeze 合約實跑；來源碼 hash 相同。')],['method_code','helper_code','cpu_results','raw_results'],verification('same family remains together; train-only pairs; frozen RM supplies PPO','分割 owners 不相交；pair:1:2 只在 test；原程式 train x/pairs 更新且 line314凍結；fresh model 全參數 requires_grad=False','數字對調透過 a≤b canonical enumeration 排除另一側另生 family；資料沒有額外生成 2+1 row。只做契約、有界替代，不執行完整訓練。'))
claim('saved_loss_vs_ordering','empirical','既有紀錄把 RM 訓練代價和未見家族偏好排序分開保存，預寫正確答案不等於模型能自行寫答案。','13.10 補充最後一句','核既有 raw result 記錄和分母，沒有使用 training loss 當 held-out accuracy，没有把保存 metric 回算寫成重跑模型。',[ev('local_method','_evaluate 188–203; run_posttraining 303–314','training history 保存 step/loss_before_update；evaluate 另以 strict winner score>loser score / all preference pairs 計算排名。'),ev('raw_saved_measurement','/results/reward/history; /results/evaluations/{train,validation,test}/reward_model_pairwise_accuracy and rows/*/{preference_pairs,reward_model_raw_scores}; /code_sha256','原 loss、raw scores、labels、split owners 和 provenance 存在且支持獨立保存；具名 pointers 完整列表另存。'),ev('cpu_execution','cpu-results.json /reward_history, /processed_reward_pair_draws, /measurements','history step 300；300×64=19,200 draws；重算 stored raw pair comparisons 分母660/75/90，與metric精確匹配。'),ev('local_method','build_records 69–86','預寫候選答案而非 policy 自行生成。')],['method_code','raw_results','cpu_results'],verification('Separate loss history and held-out pair ordering; stored denominators and code provenance consistent','history ends300；660/660 train,75/75 validation,90/90 test reconstructed from saved rows；code hashes match','仅重算原測量與合約：未載入 checkpoint、不调用 model eval runner、未重新訓練。',denominators={'training_unique_pairs':660,'training_pair_draws':19200,'reward_steps':300,'reward_batch_size':64,'train_contexts':132,'validation_contexts':15,'test_contexts':18,'train_pairs':660,'validation_pairs':75,'test_pairs':90}))
claim('human_feedback_limit','concept','這個作者規則產生偏好、非中文小網路與預寫選卡任務只教流程，不能視為完整人類回饋 RLHF 實證。','13.10 小網路段與補充最後一句','成熟 reward modeling 概念由原論文支持；本節有限 demo 的证据边界由原 methods 支持。',[ev('instructgpt','§3.1 Steps2–3 printed p.6; §3.4 printed p.7 human data collection','原始 RLHF 方法需人類 comparison labels 訓練 RM 及 policy optimization；原方法 hired labelers，與固定規則例子不同。'),ev('local_method','build_records lines63–106','資料/偏好由 Python規則生成且預算答案；沒有 labeler collection 機制。'),ev('local_helper','FiniteRewardModel lines64–75','numeric context+candidate identity input，不是自然語言理解/生成能力驗收。')],['paper_method','method_code','helper_code','own_inspection'])

checks={
 'factual_accuracy':dict(status='pass',claim_ids=[c['id'] for c in claims],details='全節親讀、逐 claim 核原論文/公式、AST 限定原方法與具名原測量；未发现错误或未确定的实质主张。'),
 'numeric_verification':dict(status='pass',claim_ids=['numbers_and_exercise','missing_quantity','saved_loss_vs_ordering'],details='原 fence+rejected=1+共同shift 真CPU；float64/math abs_tol1e-14，4decimals0.00005，mean grid四對；數量例子核元/件×件+元。重算既有raw排行660/75/90與19,200 draws，沒有重训。'),
 'figure_consistency':dict(status='not_applicable',claim_ids=['finite_features'],details='本節沒有引用SVG/圖片。四卡文字table已核原record，scalar比較與表格足夠。另真Chromium渲染1280×800/390×844，兩PNG用view_image親看；第一嘗試file URL被block（非timeout）完整保留；第二set_content成功。僅local wrapper + course.css，非full site验收。'),
 'source_verification':dict(status='pass',claim_ids=[c['id'] for c in claims],details='arXiv v1 personally read §3.1/3.4/3.5 Eq1、shift invariant；本次URL下载PDF exact bytes/hash match。亲取PyTorch安裝commit原始API组。原local scripts/result bytes、SHA、精确读范围和JSON pointers全部保存。'),
 'limitations':dict(status='pass',claim_ids=['fence_scope','finite_features','training_and_split_contract','saved_loss_vs_ordering','human_feedback_limit'],details='手設score fence没有gradient/update；補梯度有零更新。此輪只boundedCPU helper/contract/raw重算；未完整訓練、GPU、weights加载、資料下載、recipe、既有模型重測或工程準備。没有声称非中文選卡任務支持language generation或human RLHF能力。')
}
report=dict(schema_version=1,review_stage='technical',lesson_id='13.10',source='course/chapters/13.md#13.10',source_sha256=source_sha,verdict='pass',reviewer_task='/root/phase4_factual_coordinator/factual_13_10',reviewer_context='fresh',author_tasks=[],figure_sha256={},artifacts=artifacts,sources=sources,claims=claims,issues=[],checks=checks,
 reviewed_on='2026-10-05',read_scope=dict(section='13.10 full original section incl fence/table/exercise/expanded details',prerequisites='No prior section needed for the self-contained scalar example.',chapter_introduction='Not applicable: 13.10 is not first section.',implementation_ranges='own-inspection.md',raw_json_pointers_artifact='cpu_results'),
 frozen_input_snapshot=dict(path=rel(A/'inputs/chapter-13.frozen-input.md'),sha256=sha(A/'inputs/chapter-13.frozen-input.md'),meaning='Initial whole-file frozen input/snapshot only; not a claim of later current whole-chapter state or whole-chapter reading.'),
 visual_inspection=dict(section_only=True,actual_render=True,actual_view=True,desktop=[1280,800],mobile=[390,844],published_full_site='not checked; local section-only wrapper with course.css',first_attempt='Chromium file URI administrator block, not timeout',second_attempt='page.set_content successful'),
 execution_limitations='No run_posttraining call, full training, GPU, dataset or weight download, existing model re-evaluation, source/figure edit or commit.')
target=ROOT/'docs/technical-reviews/13.10.json'
temporary=A/'new-report.complete.json'
encoded=(json.dumps(report,ensure_ascii=False,indent=2)+'\n').encode()
temporary.write_bytes(encoded)
assert json.loads(temporary.read_bytes())['source_sha256']==source_sha
target.write_bytes(encoded)
assert target.read_bytes()==encoded
(A/'report-generation.json').write_text(json.dumps(dict(canonical_path=rel(target),source_sha256=source_sha,report_sha256=sha(target),canonical_confirmed=True,claims=len(claims),verdict=report['verdict']),ensure_ascii=False,indent=2)+'\n')
print((A/'report-generation.json').read_text())
