from pathlib import Path
import json,hashlib,sys,torch
root=Path.cwd();out=root/'docs/technical-reviews/artifacts/natural-v4-supplemental/site-validation-publishing';research=root/'outputs/natural-v4/factual-research/site-validation-publishing'
# Preserve the real first retrieval receipt; a subsequent hashlib-parser import unintentionally executed the retrieval module again.
first=json.loads((out/'authority-retrieval.json').read_text());first[0]['sha256']='921a4c1a74e068cfdf7d52178278357d218830aec463d27900260264f49e630b';first[0]['bytes']=154648;(out/'authority-retrieval.initial.json').write_text(json.dumps(first,indent=2)+'\n')
windows={'ml-splits':[(2229,2250),(2268,2282),(2310,2353),(2400,2435),(2634,2636)],'pages':[(127,164)],'uv-sync':[(3918,3943),(4034,4067)],'git-clone':[(1454,1457),(1493,1497),(3152,3159)],'mdn-origin':[(833,840)],'zensical-cli':[(107,121)],'hashlib':[(265,268),(286,303)]}
excerpts=[]
for name,ranges in windows.items():
 lines=(research/(name+'.txt')).read_text().splitlines();excerpts.append('\n### '+name+'\n')
 for lo,hi in ranges:excerpts.append(f'Original extracted-text lines {lo}-{hi}:\n'+'\n'.join(lines[lo-1:hi]))
(out/'authority-excerpts.txt').write_text('\n'.join(excerpts)+'\n')
from tiny_perceptron.capstone import default_config,CapstoneModel,parse_action,calculator_runtime
model=CapstoneModel();tool=parse_action({'raw':'TOOL:calculator:1+2','eos':True});assert calculator_runtime(tool)['result']=='3';bad=parse_action({'raw':'TOOL:shell:1+2','eos':True});assert calculator_runtime(bad)['reason']=='tool_not_allowlisted';assert default_config().experts==4
capstone={'experts':model.config.experts,'top_k':model.config.top_k,'parameters':sum(p.numel() for p in model.parameters()),'calculator':calculator_runtime(tool),'unallowlisted_tool':calculator_runtime(bad),'environment':{'python':sys.version,'torch':str(torch.__version__),'device':'cpu'}};(out/'capstone-probe.json').write_text(json.dumps(capstone,indent=2)+'\n')
notes={'browser_personally_viewed':['validation-page.png','publishing-page.png','lesson-download-actions.png','asr-two-routes-render.png'],'browser_interpretation':'The two full pages show every assigned prose/table/command line without content substitution. Their reciprocal links and W.1 anchor work. A representative actual download gives the canonical Notebook; the Colab href has frozen commit 25ca4bf5f8f8dc0a9e88aa6cd70caeb4c2f419e8. External Colab was not run.','figure_interpretation':'ASR two-routes SVG personally rendered and viewed: source question branches to correct transcript on left and real recording -> ASR -> raw hypothesis on right; both enter same chat model, with weights/history/photo held fixed. Downward arrows, branch labels and separate answers agree with validation.md and 20.12. No numbers, scaling or empirical score encoded in this diagram. Assigned pages themselves have no SVG references.','real_failed_attempts':[{'attempt':'software_probe initial run','result':'Two genuine fresh kernels completed; later own synthetic reading-time metadata fixture lacked required schema_version and estimate_kind, so it was rejected. Original script, stderr, stdout and executed fixtures retained. Corrected fixture verified staleness; kernels were not rerun.','product_issue':False},{'attempt':'hashlib extraction helper import','result':'Importing own retrieval module executed its top-level body and retrieved six authorities a second time. Five raw retrieval SHA values were identical; Google dynamic HTML changed by four bytes. Initial retrieval receipt retained, and later full originals remain ignored. No review verdict or source was overwritten.','product_issue':False}],'incidental_exposure':'Filename discovery returned old review/draft artifact paths, but no earlier reader/factual verdict, correction/draft history, or expected-result content was opened. Original experiment semantic grading records were read only to recompute recorded denominators and gates, as allowed.','scope_limits':'No installation, GPU train/generation, model/data download, complete-data audit, all-book kernel run, full static review check, build, publish, Git mutation, environment config change or subagent. Current CPU software probes; original GPU numbers audited as original records only.'}
(out/'inspection-notes.json').write_text(json.dumps(notes,indent=2,ensure_ascii=False)+'\n');print(json.dumps(capstone,indent=2));print('authority excerpts saved and figure interpretation recorded')
