from pathlib import Path
import json,hashlib
root=Path.cwd();rel='docs/technical-reviews/artifacts/natural-v4-supplemental/site-validation-publishing';out=root/rel
sha=lambda p:hashlib.sha256((root/p).read_bytes()).hexdigest()
read=lambda p:json.loads((root/p).read_text())
provenance=read(rel+'/provenance.json');browser=read(rel+'/browser-receipt.json');software=read(rel+'/software-receipt.json');audit=read(rel+'/record-audit.json');env={'python':'3.13.5','torch':'2.14.1+cpu','device':'cpu','nbclient':'0.11.0','ipykernel':'7.4.0','zensical':'0.0.67','browser':'Chromium 151.0.7922.173 / Playwright 1.63.0'}
artifacts=[]
def artifact(ident,kind,file,desc,command=None,result=None):
 p=rel+'/'+file;item={'id':ident,'kind':kind,'path':p,'sha256':sha(p),'description':desc}
 if kind=='execution':item.update(command=command,result=result,environment=env)
 artifacts.append(item)
artifact('input_validation','source_snapshot','snapshots/validation.md','Complete personally read UTF-8 assigned validation source, exactly matching frozen 25ca blob.')
artifact('input_publishing','source_snapshot','snapshots/publishing.md','Complete personally read UTF-8 assigned publishing source, exactly matching frozen 25ca blob.')
artifact('provenance','source_snapshot','provenance.json','Source byte counts, full hashes, absence before own report, allowed frozen blob equality, current version probes and actual preview build-info.')
artifact('browser','execution','browser-receipt.json','Real browser full-page content correspondence and link/download/Colab target observations.',' .venv/bin/python '+rel+'/probes/browser_probe.py','Exit 0; both pages HTTP 200 and match served disk bytes; 52 and 34 authored content units found; reciprocal links and W.1 work; actual 1.1 download JSON equals current canonical notebook; frozen Colab href.')
artifact('software','execution','software-receipt.json','Bounded current CPU model count, bootstrap branches, exporter rejection and metadata fixture checks; version and help receipts.','.venv/bin/python '+rel+'/probes/software_probe.py > '+rel+'/software-stdout.txt 2> '+rel+'/software-stderr.txt','Corrected metadata fixture run exit 0. Parameter count 31584; valid execution accepted; stale/unexecuted/error copies rejected; reading-time source SHA mismatch rejected; all four help commands exit 0. The two kernels completed in initial run and are recorded separately, not rerun.')
artifact('kernels','execution','kernel-receipt.json','Two genuine initial-run separate NotebookClient kernels, each asserting no prior namespace variable and saving execution outputs.','.venv/bin/python '+rel+'/probes/software_probe.py (initial bytes retained in probes/software_probe.initial.py); run_kernel(a), run_kernel(b); later receipt reads retained outputs','Both kernel outputs have execution_count 1 and stdout new_namespace 17; assertion of fresh namespace passed in each. Initial later metadata fixture failure is retained; these are own tiny fixtures, not all 266 notebooks.')
artifact('record_audit','execution','record-audit.json','Own recomputation of original raw token conditions, recorded semantic-grade counts, exact OCR checks, integer macro, gates, paired routes and sample units.','.venv/bin/python '+rel+'/probes/record_audit.py > '+rel+'/record-audit-stdout.txt 2> '+rel+'/record-audit-stderr.txt','Exit 0. All three candidates have 132 LM answers; macro numerators 53277,52285,52705 /75600; adapters fail both voice gates and have three non-EOS cap answers each. Selection recomputes base. Final set has 42 shared photo images and four paired voice questions; pretest selection SHA still matches.')
artifact('capstone','execution','capstone-probe.json','Own bounded CPU construction of small MoE and restricted calculator action.','.venv/bin/python '+rel+'/probes/closure_notes.py','Exit 0; model has 4 experts/top_k 2 and 328128 parameters; calculator 1+2 returns 3; unallowlisted shell tool is rejected.')
artifact('authority_receipt','source_snapshot','authority-retrieval.json','Real latest original external retrieval URLs, full downloaded HTML SHA/bytes; originals remain ignored research files.')
artifact('authority_excerpts','source_snapshot','authority-excerpts.txt','Small personally read original authority excerpts with exact extracted-text line locators; not complete third-party texts.')
artifact('hashlib_receipt','source_snapshot','hashlib-retrieval.json','Actual Python hashlib official documentation original retrieval SHA and version.')
artifact('notes','source_snapshot','inspection-notes.json','Personal page/SVG observations, exposure scope, genuine fixture/helper failure attempts and execution boundaries.')
artifact('software_initial','code','probes/software_probe.initial.py','Exact first software probe bytes before own synthetic metadata fixture correction; includes two real kernel calls.')
artifact('software_initial_failure','execution','software-stderr.initial.txt','Preserved real first-run stderr after both kernels completed, identifying missing fields in own metadata fixture.','.venv/bin/python '+rel+'/probes/software_probe.py (then current initial bytes)','Exit 1 after kernel a and b completed; reading_time.load_estimates rejected missing schema_version / estimate_kind in own fixture. This is not a product issue.')
artifact('record_code','code','probes/record_audit.py','Actual independent count/arithmetic/condition recomputation code.')
for i,s in enumerate(browser['screenshots']):
 artifact('view_'+str(i),'figure_render' if 'asr-two' in s['path'] else 'source_snapshot',Path(s['path']).name,'Personally viewed browser capture at '+s['url']+'; interpretation in inspection-notes.json.')
# Search capture, if completed, is a direct bounded functional check.
if (out/'search-receipt.json').exists():
 artifact('search','execution','search-receipt.json','Actual HTTP browser search interaction and displayed results.','.venv/bin/python '+rel+'/probes/search_probe.py','Exit 0 after opening actual search button; queried 教材發布 and inspected visible results and successful local search resource responses.')
 artifact('search_view','source_snapshot','search-result.png','Personally viewed actual search result, not a second full-page capture.')
 artifact('search_initial_failure','source_snapshot','search-failure.initial.txt','Actual unsuccessful first search selector and premature image view retained; correction opens the real search control.')
sources=[]
def repo(ident,p,title,note,version='current source personally inspected 2026-10-04'):
 sources.append({'id':ident,'kind':'repository_code','title':title,'path':p,'sha256':sha(p),'version':version,'verified':True,'inspection_note':note})
repo('build','scripts/build_course.py','Canonical Markdown-to-Notebook generator','Read notebook(), BOOTSTRAP and build(): prose/figures/Python are derived from source sections; first setup cell precedes diagram or visible Python; clone has no revision/branch flag; local repo bootstrap and controlled Colab branch personally executed.')
repo('export','scripts/export_course.py','Canonical source and executed-output web exporter','Read checked_notebook(), reading_markdown(), build(), CLI: cell type/source equality, execution_count and error checks precede output mutation; strict Zensical subprocess; revision labels links rather than snapshotting files; build-info fields inspected.')
repo('kernel','scripts/check_notebooks.py','Independent-kernel notebook runner','Read complete run_kernel and main; each file gets new NotebookClient.execute() with Tiny Perceptron kernelspec and writes corresponding executed copy and validation-kernel JSON. Own two-fixture execution saved.')
repo('site','scripts/check_site.py','Site link/download checker','Read complete checker: local HTML anchors/assets, search coverage, notebook JSON/current-code visibility/lesson_id and revision-specific Colab URL checked. This verifies structure, not remote Colab execution or semantic understanding.')
repo('times','scripts/reading_time.py','AI time metadata and inventory implementation','Read method disclosure, chapter_introduction, inventory, load_estimates and CLI: AI audience/exclusions, unique page IDs, intro-only chapter slices, source and figure SHA guards; bounded own metadata probe executed.')
repo('project','pyproject.toml','Existing dependency declarations and group meanings','Read CPU extra source and dev/notebook/site groups; verify current environment versions independently. No install run; uv help supports frozen/extra/group syntax.')
repo('workflow','.github/workflows/pages.yml','Pages build and deployment workflow','Read full current workflow: main push/manual trigger, LFS prerequisite, frozen CPU sync, current review/kernel steps, strict executed export with reading-time requirement, link check, upload Pages artifact, dependent deploy with pages/id-token write. No workflow/deploy executed.')
repo('ignore','.gitignore','Outputs storage exclusion','Read outputs/, runs/, data/, checkpoints/, caches and model-file ignores; web and executed outputs stay outside tracked evidence.')
repo('technical','scripts/check_technical_reviews.py','Factual-report integrity checker','Read source/artifact/claim components and schema logic: current local file hashes, identity/evidence shape and explicit limitations; cannot observe reviewer comprehension. Only unchanged component functions applied to this own supplemental report.')
repo('technical_guide','docs/technical-review-guide.md','Current factual review protocol','Read full protocol and standards, including independence, original authorities, bounded numeric/software evidence and distinction from AI reader/test results.')
repo('editorial_guide','docs/editorial-guide.md','Reader review protocol','Read current guide: actual reader subagent scope, background/terms/examples/code/exercise checks, re-read requirement, separate AI review from program execution and human student testing.')
repo('smoke','scripts/gpu_smoke_check.py','Original smoke training/resume measurement implementation','Read train_and_measure and resume_and_compare: max_length 64/default model, 80 updates with save every40, copied step 40 before 41, compare all resumed state tensors with max(abs difference), step and history checks; no GPU run.')
repo('modal_smoke','scripts/modal_smoke.py','Original Modal/private HF roundtrip implementation','Read full source: L4 training, private repo preflight, upload/download at commit.oid, SHA match before resume, volume verification; no private network action performed.')
repo('smoke_record','docs/gpu-smoke-result.json','Original CUDA L4 smoke execution record','Original numerical fields and fixed HF paths/revisions read; byte/content equality to outputs/modal-smoke/remote-result.json checked; own CPU default model has same 31584 parameters. Zero tensor difference audited as original record only.','Original run gha-37028829401-1; source revision b75ae446797e138a7ab733ae3c9b02d5ab7fbda4, Torch 2.14.1+cu126')
repo('capstone_code','tiny_perceptron/capstone.py','Small-world MoE and calculator-only assistant','Read default_config, model modality projectors, generated trace plumbing, parse_action and calculator_runtime. Own CPU construction and allowlist probes confirm small synthetic RGB/tone/text model with narrow tools; no natural-language quality inference.')
repo('natural_code','tiny_perceptron/natural_assistant.py','Natural assistant fixed model and two-route evaluation','Read normalized, score_output, ASR transcript summary and evaluate audio two-route code: actual hypothesis replaces user only on spoken path; typed reference route enters same model/context/options.')
repo('selection_protocol','docs/natural-assistant/v4/validation-protocol-lower-lr.json','Frozen validation gates and units','Read lower-LR protocol before computation: 132 generations per candidate; declared groups; three acceptance conditions, exact macro/75600 and fixed ASR/small-sample limits.')
repo('selection','docs/natural-assistant/v4/selection.json','Current chosen base configuration','Read complete original selection and independently recompute candidate gates instead of trusting decision string; source SHA also matches original pretest guard.','Selected from gha-37219466611-1')
repo('manifest','docs/natural-assistant/v4/manifest.json','Original frozen task/split metadata','Own extraction inspected task, split, family, question/reference, image and scoring fields used by original 132-answer records; no media/release or complete dataset audit. Split family intersections are zero in manifest metadata.')
repo('validation_scorer','scripts/score_natural_v4_validation.py','Original validation scoring conditions','Read expected_cases, eos_complete and score_blind; independently reproduce group counts, exact-match normalization, token/EOS predicates, integer macro and gates rather than merely calling passed/status fields.')
repo('original_grades','docs/natural-assistant/evidence/v4-runtime/validation-37219466611/blind-review/combined/grades.json','Original recorded semantic grades','Original experimental grades used for reaggregation, not treated as a previous factual verdict or independently fresh image regrading. Full raw decoder suffixes separately tested and exact OCR counted independently.','Original blinded validation gha-37219466611-1')
repo('original_raw','docs/natural-assistant/evidence/v4-runtime/validation-37219466611/blind-review/raw/generations-adapter-step-001039.json','Original candidate raw generated answers','Inspected all raw record count, task/split/id/token/EOS/cap fields via own recomputation; used paired reference/ASR user strings and image/history equality. Other variants and raw hashes in record-audit.json.','Original L4 bfloat16/Torch 2.8.0+cu128 run gha-37219466611-1')
repo('pretest','docs/natural-assistant/evidence/v4-runtime/evaluate-37221188153/source-selection-guard-before-test.json','Original selection freeze before final test','Read original guard and recompute current selection/manifest SHA equality; no history walk or claim of independently recreating pretest chronology.','Observed original pretest guard 2026-10-04T17:36:35.401768+00:00')
repo('final_raw','docs/natural-assistant/evidence/v4-runtime/evaluate-37221188153/blind-review/generations-base.json','Original final-test answer identities','Own count of groups, unique image paths, four paired voice IDs, reference and actual-ASR routes; no new final-test generation or population inference.','Original selected-base final test gha-37221188153-1')
retrievals=read(rel+'/authority-retrieval.json');extra=read(rel+'/hashlib-retrieval.json');retrievals.append(dict(extra,id='hashlib',final_url=extra['url']))
infos={
'ml-splits':('Google ML Crash Course: datasets, generalization and test reuse','Last updated 2025-12-03 UTC; retrieved 2026-10-04','Google publishes the original instructional guidance.','Training, validation, and test sets; Figure10 development workflow; wear-out/reuse paragraphs; Additional problems with test sets. I read that fitting decisions to a reused test weakens new-data inference, duplicates break heldout evidence, and evaluation depends on representative conditions.'),
'pages':('GitHub Pages custom workflows','Live GitHub docs retrieved 2026-10-04; templates @v4, not a promise of same action version as this repo','GitHub is the original publisher/operator of the Pages workflow API.','About custom workflows; upload-pages-artifact; deploying artifacts and separate jobs. Requirements include build dependency, pages/id-token permission, environment and uploaded static artifact; this matches repo pipeline structure without claiming it ran.'),
'uv-sync':('uv project locking and syncing','Live Astral uv docs retrieved 2026-10-04; current uv CLI help personally executed','Astral publishes the tool behavior.','Locking/syncing and frozen option; optional and development groups. Frozen uses current lockfile without an update check; --extra/--group select declared subsets. I did not sync or change environment.'),
'git-clone':('Git clone manual','git-clone manual last updated 2.54.0, dated 2026-04-20; retrieved 2026-10-04','Git publishes the original command contract.','--branch: absent override uses branch pointed to by remote HEAD. The inspected bootstrap omits branch/revision, so fixed Colab notebook ref does not pin the subsequently cloned project.'),
'mdn-origin':('MDN same-origin policy: file origins','Live MDN defense page retrieved 2026-10-04','Mozilla documents browser origin behavior at its original publication.','File origins: modern browsers usually treat file:/// as opaque and same-directory inclusion can yield CORS errors; exact file behavior is implementation-dependent. This supports serving over HTTP as documented, not a universal guarantee of identical browsers.'),
'zensical-cli':('Zensical Build usage','Live original docs retrieved 2026-10-04; installed CLI verified 0.0.67','Zensical publishes its CLI contract.','Build usage/options: --config-file, --clean, --strict; generates configured site_dir. Own help and current preview generator confirm available builder version; no build executed.'),
'hashlib':('Python hashlib: secure message digests','Python 3.13.16 official docs retrieved 2026-10-04; runtime Python3.13.5','Python publishes the standard library digest API.','Hash algorithms: sha256 accepts byte-like inputs and returns digest/hexdigest of concatenated bytes; SHA256 always present. Identity checks here pair fixed paths/versions with full size/hash; they do not establish model answer quality.')}
for r in retrievals:
 title,version,authority,note=infos[r['id']];sources.append({'id':r['id'],'kind':'official_docs','title':title,'url':r['final_url'],'version':version,'verified':True,'checked_original':True,'accessed_on':'2026-10-04','authority_reason':authority,'inspection_note':note,'retrieval_sha256':r['sha256'],'retrieval_bytes':r['bytes'],'retrieval_receipt_artifact_id':'hashlib_receipt' if r['id']=='hashlib' else 'authority_receipt','excerpt_artifact_id':'authority_excerpts'})
claims=[]
def claim(ident,kind,statement,location,evidence,artids,scope,expected=None,observed=None,details=None,den=None):
 c={'id':ident,'kind':kind,'statement':statement,'location':location,'status':'verified','evidence':[{'source_id':i,'locator':l,'supports':s} for i,l,s in evidence],'artifact_ids':artids,'scope':scope}
 if kind in ['software','numeric','empirical']:
  c['verification']={'method':'executed','expected':expected,'observed':observed,'details':details}
  if kind=='numeric':c['verification']['tolerance']='exact integer equality'
  if kind=='empirical':c['verification']['denominators']=den
 claims.append(c)
claim('evidence_boundaries','concept','Execution, numeric mechanism checks, parameter updates, file identity and heldout task performance answer different questions; capability evidence requires heldout conditions and cannot be replaced by file hashes or program success.','validation.md opening, six-row table and closing explanation',[('ml-splits','Training, validation, and test sets; Additional problems with test sets','Heldout/new examples and representative test conditions support performance scope.'),('hashlib','Hash algorithms / sha256 and digest','Byte digest APIs support integrity comparison, not task capability.')],['record_audit','software'],'Methodological distinction; no population-level or all platform capability claim.')
claim('task_worlds','software','Chapter19 combines limited synthetic RGB/tone/text and calculator tools in small MoE; Chapter20 uses a pretrained image-text core and frozen ASR; scores from those distinct task worlds and correlated samples are not interchangeable.','validation.md 小實驗、正式訓練與成品 scope',[('capstone_code','default_config, CapstoneModel.forward, calculator_runtime','Synthetic projectors, four-expert config and restricted calculator are actual implementation.'),('natural_code','evaluate two-route audio code; runtime fixed-model definitions','ASR and image-text core have separate roles.'),('final_raw','task/image/id fields','Photo and paired-voice samples share inputs.')],['capstone','record_audit'],'Own CPU structure/tool probe plus original natural-run record identity audit; no natural-model inference or speed claim.','Four-expert synthetic model and limited tool allowlist; final photo/voice answers share inputs.','Own model confirms experts4/top_k2; permitted calculator returns3 and shell rejected; final 42 summary images are shared across84 fact answers and four voice IDs across both routes.','Instantiate current small model and probe allowlist; count original final record task/image/id identities.')
claim('split_method','concept','Training updates weights, validation compares candidate recipes, and final testing follows selection; using test results to alter a model calls for new untouched evaluation data.','validation.md 驗證選版，最後測試驗收',[('ml-splits','Figure10 workflow; test-set reuse and wear-out paragraphs','Validation guides changes, final test double-checks choice; repeated adaptation to a test weakens untouched evaluation.')],['record_audit'],'Standard protocol description, not proof of every unseen upstream pretrained example. Own manifest metadata intersections and original pretest source guard corroborate this project boundary without a complete data audit.')
claim('candidate_outcome','empirical','The referenced LoRA comparison improves some photo answers but fails chat preservation/EOS acceptance and selects the original base, so saved checkpoints and lower training loss do not ensure delivery capability.','validation.md paragraph linking20.8 and v4selection',[('selection_protocol','score, adapter_nonregression_gates_vs_base, selection and uncertainty','Three eligibility conditions and exact denominator/macro.'),('original_raw','all 132 raw answer task/token/EOS fields','Completion predicates independently checked.'),('original_grades','grades by blind alias and case_id','Original semantic decisions reaggregated with independent raw completion conditions.'),('pretest','committed_pretest_selection_sha256 and files','Current chosen selection still matches pretest recorded freeze.')],['record_audit'],'Original L4 bfloat16 generated records/recorded semantic grades audited on CPU, not own GPU replication or fresh image regrading. Small, correlated denominators; base fallback also has failures.','Candidates accepted only if all complete, each gate holds and exact primary strictly exceeds base.','Recomputed primary53277,52285,52705 /75600. Step1039 photo16→23 /28 and31→53 /56; typed voice4→2 /4 and actualASR3→2 /4. Both adapters have3 incomplete384-token answers and fail both voice gates; selected base.','Independently classify original records, apply exact OCR normalization, reaggregate original manual decisions only when token/EOS predicates hold, compare fraction macro to integer numerator, then recompute gates and selection.',{'candidates':3,'lm_answers_each':132,'photo_summary_questions_each':28,'photo_fact_questions_each':56,'text_chat_questions_each':9,'typed_voice_questions_each':4,'actual_asr_voice_questions_each':4,'exact_primary_units':75600,'generation_cap_new_tokens':384,'seed':42})
claim('asr_routes','software','Checking the ASR transcript separately and feeding the correct transcript to the same assistant distinguishes transcription errors from downstream answer errors; four paired recorded questions do not imply broad speech competence.','validation.md ASR paragraph and correlated-sample caution',[('natural_code','evaluate spoken/typed branches around914-939','Actual transcript replaces only spoken user; same variant/model and history/image inputs.'),('final_raw','speech_chat and typed_chat records','Paired identities and manifest reference strings corroborate procedure.')],['record_audit','view_3','notes'],'Own raw record/control-flow verification, not live ASR or voice-generation experiment. Both routes may fail even with correct transcription.','Typed input equals reference; spoken input equals actualASR hypothesis; other paired inputs stay same.','All three validation variants contain four paired question IDs and matched image/history; four final pairs have matching reference/actual hypotheses as recorded. SVG correctly depicts the two separate stations.','Compare paired record id/task/user/history/image fields; personally render/view necessary original SVG and verify branches/arrows/labels.')
claim('reviews_and_time','software','Reader understanding, factual checks and connected reading have separate purposes; reports and AI time estimates depend on current source/figures, and checks cannot prove understanding or measured human learning. AI times exclude setup/download/hands-on/waiting, count chapter introduction only and deduplicate pages.','validation.md 教材審閱與閱讀時間; publishing.md current-source review/time prerequisites',[('technical_guide','independence, actual checks, final scope statement','Current protocol separates evidence and AI review from execution/human testing.'),('editorial_guide','reader checks and revision paragraphs','Terms/background/example/code/exercise and reread requirements.'),('times','METHOD, chapter_introduction, build_inventory, load_estimates','Audience/exclusions/unique page inventory and current hash requirements.'),('technical','_sources/_artifacts/_claims and version validation','Static metadata integrity does not observe comprehension.')],['software','software_initial_failure'],'Protocol and implementation behavior; no audit of earlier peer verdicts, no new time estimate, no assertion all reviews/time metadata currently complete.','AI disclosure and source/figure identity guards; old source metadata rejected.','Source staleness fixture is rejected. Actual preview has reading_time_pages0 / reading_time_completefalse. Current code explicitly defines audience/exclusions and introduction-only slices.','Read current protocol/code; execute corrected bounded one-page stale-metadata fixture. Preserve initial fixture format rejection separately; never use it as product failure.')
claim('gpu_smoke','empirical','The original Modal/private HF smoke reports a 31584-parameter model updated to 80, recovered step 40 at pinned HF revision, resumed 40 more updates and recorded maximum weight difference 0 versus uninterrupted route; this is workflow evidence, not natural-model quality.','validation.md Modal GPU與HF checkpoint',[('smoke','train_and_measure and resume_and_compare','Save/copy step 40 before 41; compare every model state tensor via max absolute difference; check resumed 80 and first resumed history 41.'),('modal_smoke','train upload_folder/hf_hub_download revision and SHA comparison','Original roundtrip uploads and downloads fixed commit before resume.'),('smoke_record','parameters, hf revisions/checkpoint_path and resume numeric fields','Original CUDA L4 result gives numerical record and scope; not merely aggregate passed.')],['software'],'Original Torch 2.14.1+cu126 CUDA/L4 record audit. Own Torch 2.14.1+cpu model/count/arithmetic only; no original GPU tensor reread, remote private download or GPU replication. Zero remains original recorded tensor-comparison outcome.','Current defaultmax_length 64 small model should have31584 parameters; resume from40 to 80 means40 further updates; original comparator reports0.','31,584 independently counted;80−40=40; numerical original maximum0 in matching original returned record; implementation scans full original/resumed tensor keys.','Instantiate current default small model onCPU, count parameters, compare original returned record with durable doc, audit exact checkpoint/compare algorithm and recover pinned-version/size/hash conditions.',{'original_gpu_runs':1,'model_parameters':31584,'uninterrupted_updates':80,'checkpoint_step':40,'resumed_additional_updates':40,'batch_size':4,'max_length':64,'seed':42})
claim('shared_source_and_notebook','software','Webpages and lesson notebooks derive from canonical Markdown; first code prepares tools, local download is canonical, fixed Colab notebook commit differs from bootstrap cloning default branch and using Colab Python / pip.','publishing.md opening and all reader-use items/Colab scope paragraph',[('build','notebook and BOOTSTRAP','Single source conversion and first prep; default clone plus sys.executable pip.'),('export','reading_markdown, build notebook/render/action URL code','Canonical source links/figures/code, current executed output, frozen action href.'),('git-clone','--branch contract','Clone without override uses branch pointed to by remote HEAD.')],['browser','software','kernels'],'Own current local browser/bootstrap/deterministic fixture checks. Controlled Colab branch intercepted subprocess calls; no Colab runtime or actual clone/pip installation performed. Code-free sections are reading-oriented even if diagram rendering requires setup.','Both assigned pages current; representative notebook firstcode setup; fixed notebook ref and unpinned clone differ.','Every 52 / 34 authored page units found. Actual 1.1 download equals canonical JSON and first code_setup true. Href contains frozen 25ca; controlled clone has no revision/branch override and pip follows Python executable. Two genuinely independent kernels pass namespace assertion.','Read actual generator/exporter; browserclick download; compare canonical; run local bootstrap, safely intercept Colab branch subprocess invocation, and use runner on two tiny fixtures.')
claim('environment_and_commands','software','The shown frozenCPU/dev/notebook/site setup selects declared groups; validation commands check current generation/review/time identity, kernel command starts independentCPU executions, and pytest checks repository mechanisms. Outputs/notebooks contains working execution copies/check totals, not capability scores.','validation.md 在自己的版本重跑 and publishing.md setup/preflight command blocks',[('project','dependency-groups and CPU uv source','Actual dependencies/grouproles and declaredCPU extra.'),('uv-sync','Frozen, extras and development groups','Original command meaning.'),('kernel','run_kernel/main output and kernel configuration','Independent clients/current copies/resultcounts.'),('export','checked_notebook','Sources/execution/errorconditions.'),('times','load_estimates','Current time source/figure requirement.')],['software','kernels'],'Commands and current software contracts reviewed with bounded probes/help only. No install, ipykernel registration, all-book execution, whole review suite or pytest suite run; full pipeline remains user-facing rerun instructions, not this review claimed completion. Windows activation is standard environment-specific path, not personally executed.','Frozen/group/extra and export/kernel flags exist; actual stale/error/unexecuted data cannot serve as current execution evidence.','uv sync / export / kernel/Zensical help all exit0; declaredgroups match roles; stale source, missing execution_count, error output rejected; genuine two-client outputs retained.','Inspect actual current parser/functions and dependency declarations; execute only helpers/tiny fixtures/help; distinguish full unrun commands from own bounded validations.')
claim('strict_export_and_revision','software','Exporter organizes source prose/figures/current executed cells, invokes strict realZensical, requires current time records when requested, and revision annotates links rather than saving uncommitted files. Commit-before-export is necessary for revision-labelled source links to represent committed material.','publishing.md 從正文產生網站 prose and final command block',[('export','build preflight / checked_notebook / Zensical subprocess/build-info/CLI','Real strict builder and identity/time guard paths; revision used inhrefmetadata only.'),('zensical-cli','Build/options','Original CLI contract.'),('site','check links, anchors, notebook downloads and Colab','Postbuild structure checks.')],['software','browser','provenance'],'Current code/CLI and actual supplied preview; no build, Git commit or publish performed. Executed-output flag records use of matched execution copies, not independent proof of hardware. Reading-time page count equals site inventory only for required complete formal build.','Strict build options available; revision does not perform Git snapshot; executed source / conditions checked before output mutation.','InstalledZensical0.0.67 help supports --clean/--strict/--config-file; preview generator matches0.0.67 and revision25ca; bad execution copies fail bounded helpers. Current preview reading-time incomplete, so it is not formal publicationready.','Read exporter/controlflow; actualhelp/bounded guardprobe; inspect browsermeta and servedbuild-info. Conditional publicationinstructions do not assert current whole pipeline passing.')
claim('http_preview','software','HTTP preview enables normal browser resource loading/search; directly openingfileHTML has different origin constraints, and127.0.0.1 points to the server machine.','publishing.md HTTP preview paragraph',[('mdn-origin','File origins','file origins often opaque and browser-specific, supporting HTTP serving.'),('workflow','sitebuild/uploadpath','Localserver views generated staticsite, distinct fromremotePagesdeployment.')],['browser','search'],'Own actual assigned HTTP preview/search, no cross-platform or file:/// experiment. Loopback semantics identify local execution machine; not a remote public URL.','Actual HTTP pages/resources load and searchworks; originlimits supportHTTP recommendation.','AssignedHTTP200pagesrender withcorrectcontent; actual searchopens via searchbutton and returns local results.','Personal browseruse and HTTP resource observations; originalMozilla file origin conditions, without inventing universal browserbehavior.')
claim('pages_and_artifact_scope','software','Pages workflow triggers on main / manual, obtains prerequisite assets, enforces reviews/current CPU outputs/strict site/link checks, uploads ignoredsite artifact and deploys dependent job. Notebook count follows current index; build-info records revision/lessons/CPU flag/builder and reading-time completeness. Data/model/web release routes remain distinct.','publishing.md 發布到GitHubPages all prose',[('workflow','triggers, build steps, upload/deploy jobs','Currentactualworkflow pipeline and permissions.'),('pages','customworkflows/upload/deployrequirements','Original Pages API supports staticartifactdependentdeployment.'),('export','build-info creation and index/notebook iteration','Dynamic266index notebooks; revision andbuildermetadata.'),('ignore','outputs/ ignore','Generatedartifactstorage is ignored.')],['provenance','browser','software'],'Readonlyworkflow/config inspection and dynamic current index count266, not executedpipeline or confirmation of currentlive deployment. build-info does not contain a separate total HTML page field: reading_time_pages gives fullinventory size only when reading_time_complete true under formal --require-reading-times build. Current preview pages0 time entries/false correctly treated as incomplete. Separate data / model routes verified structurally from current storage instructions/workflow headers without release audit.','Build and deploy relationship and publication metadata align with commands; counts derivecurrent index.','Currentindex266 andpreview lessons 266; generator version0.0.67; executed flag true; reading_time_pages0/completefalse. Workflowhasmain push/manual trigger, review / kernel / export checks, outputs/site artifact and dependent Pagesdeploy permission.','Read current workflow / config / ignore / export source; compare index length with actual preview metadata; inspect links / download. Instruction to verify commit needs committed inputs because --revision itself is an arbitrary link label.')
ids=[c['id'] for c in claims];checks={
'factual_accuracy':{'status':'pass','details':'All assigned prose, table entries, commands and stated scope read; substantive groups independently checked against original authorities, current implementation and original numerical records. No unresolved/contradicted claim.','claim_ids':ids},
'numeric_verification':{'status':'pass','details':'31,584 independently counted;80−40=40; raw record 132-groupdenominators and exact 75600 macro/gates recomputed; shared 42 image/four question final units verified. ZeroGPUdifference remains original recorded outcome, explicitly not own GPU tensorreplication.','claim_ids':['candidate_outcome','gpu_smoke','task_worlds']},
'figure_consistency':{'status':'pass','details':'Assigned two pages have no SVG references. Necessary20.12ASRprerequisite SVG personally rendered/viewed: branchlabels/arrows/same chat model and separateoutputs agree; hashrecorded and originalcapture retained.','claim_ids':['asr_routes']},
'source_verification':{'status':'pass','details':'Original Google/Python/Git/Astral/Mozilla/GitHub/Zensical authorities personally inspected with exactlocators/versions/date/fullretrievalSHA and small excerpts; repository originals/currentcode hashed. Previousfactual/reader verdicts/drafts never opened.','claim_ids':ids},
'limitations':{'status':'pass','details':'Scope remains current local CPU/browserfixtures and audit of original GPU records/semanticgradecounts. No live Colab,full pipeline,GPUreplication,heavy download,data audit orpublication. Current time metadata incomplete; pass applies onlyto these two assigned documents andtheir stated conditional procedures.','claim_ids':ids}}
report={'schema_version':1,'review_stage':'technical','reviewer_task':'/root/v4_review_coordinator/factual_site_validation_publishing','reviewer_context':'fresh','assigned_document_scope':{'kind':'complete_documents','documents':['docs/validation.md','docs/publishing.md'],'extent':'Every line of prose, table cell, command and stated support/limitation in both current canonical files; no invented numbered lesson ID. Linked prerequisites read only as needed, not reviewed as assigned whole-document expansions.'},'complete_documents':['docs/validation.md','docs/publishing.md'],'current_document_sha256':{r['path']:r['sha256'] for r in provenance['sources']},'actual_complete_reading_order':['outputs/natural-v4/review-plan/supplemental-factual-contract.md','docs/technical-review-guide.md','docs/validation.md','docs/publishing.md'],'complete_read_receipt':provenance['sources'],'necessary_prerequisite_read_scope':['pyproject.toml / .github/workflows/pages.yml / .gitignore','docs/gpu-smoke-result.json and matching original Modal return','docs/natural-assistant/v4/selection.json, lowerLRprotocol, manifest fields used by original records','scripts/build_course.py / check_notebooks.py / export_course.py / check_site.py relevant actual functions and complete small files','scripts/check_technical_reviews.py unchanged source/artifact/claim components; scripts/reading_time.py relevant method/inventory/staleness functions','scripts/gpu_smoke_check.py measurement/resume and scripts/modal_smoke.py roundtrip','course/chapters/19.md intro/19.1; course/chapters/20.md20.8/20.12/20.13; docs/natural-assistant/v4/TRAINING.mdsections1-4; no earlier draft/history','originalvalidation grades/mapping/rawtokenrecords and finalsampleidentity/route records; current natural_assistant and scorer implementation','necessary ASRtwo-routesSVG personal render/view; docs/editorial-guide.md and docs/asset-storage.mdcurrent protocol/routestext, data/model workflowheaders','sevenoriginalexternalauthorities, actual assignedbrowserpages/download and onefunctionalHTTPsearch'], 'figure_sha256':{'course/figures/natural-v4-asr-two-routes.svg':browser['svg_original_sha256']},'direct_assigned_svg_references':[],'verdict':'pass','claims':claims,'sources':sources,'artifacts':artifacts,'checks':checks,'issues':[],'review_scope_limits':json.loads((out/'inspection-notes.json').read_text()),'publication_readiness':'Not claimed; supplied executedpreview has unfinished reading-time metadata and this reviewer did not run fullpublication gates or deploy.','initial_report_state':'Absent before this fresh review; no assigned earlier verdict was read or replaced.','reviewed_on':'2026-10-04'}
(out/'report.json').write_text(json.dumps(report,indent=2,ensure_ascii=False)+'\n');print('report',sha(rel+'/report.json'),'claims',len(claims),'sources',len(sources),'artifacts',len(artifacts))
