import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[4]
ART = Path(__file__).resolve().parent
REL = ART.relative_to(ROOT).as_posix()
sha = lambda p: hashlib.sha256(p.read_bytes()).hexdigest()
env = {'python': '3.13.5', 'torch': '2.14.1+cpu', 'device': 'cpu', 'threads': '1'}
artifacts = []
def artifact(identifier, filename, kind, description, **kwargs):
    artifacts.append(dict(id=identifier, kind=kind, path=f'{REL}/{filename}', sha256=sha(ART/filename), description=description, **kwargs))
artifact('a_cpu', 'cpu-output.txt', 'execution', '獨立參數計數、untied/top-k/路由小變化、固定資料指紋及train-only字表重建。', command='PYTHONPATH=. /workspace/tiny-perceptron-vlm/.venv/bin/python docs/technical-reviews/artifacts/p6-19.2/verify_cpu.py > docs/technical-reviews/artifacts/p6-19.2/cpu-output.txt 2>&1', result='exit 0; all bounded CPU assertions passed; 0 optimizer updates; 539 ordinary+11 special IDs=550; no generation or training.', environment=env)
artifact('a_fence', 'original-fence-output.txt', 'execution', '原稿Python fence原樣擷取後實際執行的六行輸出。', command='PYTHONPATH=. /workspace/tiny-perceptron-vlm/.venv/bin/python docs/technical-reviews/artifacts/p6-19.2/original-fence.py > docs/technical-reviews/artifacts/p6-19.2/original-fence-output.txt 2>&1', result='exit 0; moe 5447107/5140224/3036928/True; dense 2288067/1981184/1981184/True.', environment=env)
artifact('a_receipts', 'receipts-output.txt', 'execution', '按白名單JSON pointer核對15段原始execution/train/outer receipts，並核公開best來源及原碼SHA。', command='PYTHONPATH=. /workspace/tiny-perceptron-vlm/.venv/bin/python docs/technical-reviews/artifacts/p6-19.2/inspect_receipts.py > docs/technical-reviews/artifacts/p6-19.2/receipts-output.txt 2>&1', result='exit 0; all15 execution return codes0; config and parameter counts match; final public best.pt SHA matches original outer table; source core SHA matches.', environment=env)
for i, file, desc in [('a_cpu_code','verify_cpu.py','本輪CPU驗證程式'),('a_fence_code','original-fence.py','從19.2原始fence擷取，沒有改模型或原稿'),('a_receipt_code','inspect_receipts.py','原始receipt白名單抽取及SHA核對程式'),('a_model','code/tiny_perceptron/selftrained/model.py','原始模型完整byte副本；實際讀取定位見inspection-record'),('a_modern','code/tiny_perceptron/modern.py','原始FFN與router完整byte副本'),('a_base','code/tiny_perceptron/model.py','原始TinyLM tied賦值與共用Block完整byte副本'),('a_dataset','code/tiny_perceptron/selftrained/dataset.py','原始train_tokenizer完整byte副本'),('a_tokenizer_code','code/tiny_perceptron/selftrained/tokenizer.py','原始字元tokenizer完整byte副本')]:
    artifact(i,file,'code',desc)
for i, file, desc in [('a_checked','receipts-checked.json','45原始檔指紋、實際查閱pointers、15段配置/計數/完成與歷程；避開review/notes/作者解釋值'),('a_tokenizer','public-tokenizer.json','既存公開tokenizer原檔永久副本，與固定train-only重建definition精確相同'),('a_manifest','v2-manifest.json','固定manifest完整原件byte副本；只查model_config、records和資料來源規約'),('a_public','v2-final-public-results.json','公開記錄完整原件byte副本；僅查配置、容量數字與selected_source pointers'),('a_public_sha','source-core31-before.json','原公共CPU source SHA表原件永久副本'),('a_witnesses','train-character-witnesses.json','固定SHA核對後train訊息中首個字元出現的必要原始metadata'),('a_input','19.2.md','本次19.2原始UTF-8 bytes'),('a_frozen','frozen-19.md','初次frozen整章原始byte副本，非目前整章版本宣告'),('a_inspection','inspection-record.json','實際讀取範圍、獨立性、JSON與AST使用範圍'),('a_history','verification-history.txt','第一輪驗證器序列化SHA誤比及修正原因；不是教材問題'),('a_mixtral','mixtral-v1.pdf','親自取得並閱讀Mixtral原論文arXiv v1'),('a_mixtral_text','mixtral-v1.txt','原PDF經pdftotext -layout所得定位文本'),('a_tying','press-wolf-v3.pdf','親自取得並閱讀Press/Wolf原論文arXiv v3'),('a_tying_text','press-wolf-v3.txt','原PDF經pdftotext -layout所得定位文本'),('a_fetch','authority-fetch.json','原始權威HTTPS URL/version/date/取得狀態與PDF SHA')]:
    artifact(i,file,'source_snapshot',desc)
for stage in ['moe-native','dense-weighted','moe-pretrain','dense-pretrain']:
    for leaf in ['raw/train-receipt.json','raw/execution.json','receipt.json']:
        artifact('a_raw_'+stage.replace('-','_')+'_'+leaf.replace('/','_').replace('.json',''),f'raw-snapshots/{stage}/{leaf}','source_snapshot','原始'+stage+'/'+leaf+'完整byte副本；完整SHA同原件，僅白名單pointer參與核實，作者附註未讀。')

sources = [
dict(id='s_moe',kind='paper',title='Mixtral of Experts',url='https://arxiv.org/pdf/2401.04088v1',version='arXiv:2401.04088v1, 2024-01-08',verified=True,checked_original=True,accessed_on='2026-10-06',authority_reason='Mixtral作者發表的原始SMoE架構論文，直接給出router/FFN/weighted sum及total-active-memory區別。',inspection_note='親讀PDF pp1-3 abstract/Figure1/§2.1 weighted-sum與Softmax(TopK(xWg))公式，以及p4 §3 Size and Efficiency關於完整權重記憶體與routing overhead；不採用論文品質數值證成本專案效益。'),
dict(id='s_tying',kind='paper',title='Using the Output Embedding to Improve Language Models',url='https://arxiv.org/pdf/1608.05859v3',version='arXiv:1608.05859v3, 2017-02-21',verified=True,checked_original=True,accessed_on='2026-10-06',authority_reason='Press/Wolf作者原論文定義輸入/輸出embedding和weight tying。',inspection_note='親讀PDF p1 §1 h3=Vh2及enforcing U=V；p2-3 §3 tied NNLM U=V=S。只支持共用參數的定義，不宣稱本成品品質改善。'),
]
for i,path,note in [('s_model','tiny_perceptron/selftrained/model.py','AST先定位；讀SelftrainedConfig25-53、PaddingSafeMoE56-105、MaskedBlock108-130、LM133-185、感知188-282、LimitedAssistant295-382、description421-457；只核構造、路由、scope/count方法。'),('s_ffn','tiny_perceptron/modern.py','AST先定位DenseFFN35-53及MoEFFN56-84；nn.Linear bias、trainable expert ModuleList、無bias router與gate-weight合併。'),('s_base','tiny_perceptron/model.py','AST定位後讀Block31-50和TinyLM54-66；每層attention/norm共用結構，output.weight=embedding.weight。'),('s_dataset','tiny_perceptron/selftrained/dataset.py','AST定位後讀read_records48-81、train_tokenizer84-91；只取split=train內容，固定ASCII32..126和OCR_CHARACTERS。'),('s_tokenizer','tiny_perceptron/selftrained/tokenizer.py','AST定位後讀1-77；SPECIALS11個、OCR字元12個、build去重排序、逐字encode未知字元ID10、literal角色字串不當控制token。'),('s_train','scripts/selftrained/train.py','AST定位後讀tokenizer_sha80-81、main689-803；首次由train_tokenizer建詞表，後續來源definition沿用；stage/resume與模型配置契約。')]:
    sources.append(dict(id=i,kind='repository_code',title=path,path=path,sha256=sha(ROOT/path),version='checkout HEAD b3a6684a1af47f1086c1b9e56ed090ff6699220a; 本次完整檔案SHA為版本依據',verified=True,inspection_note=note))
sources += [dict(id='s_cpu',kind='execution',title='本輪有界CPU數字及變化核對',verified=True,artifact_id='a_cpu'),dict(id='s_fence',kind='execution',title='原稿參數計数fence執行',verified=True,artifact_id='a_fence'),dict(id='s_receipts',kind='execution',title='本輪原始訓練/public provenance核對，非重新訓練',verified=True,artifact_id='a_receipts'),dict(id='s_count',kind='derivation',title='FFN與共享文字參數的結構推導',verified=True,details='DenseFFN two biased Linear: 256*512+512+512*256+256=262912 per expert. MoE4 layers*4 experts=4206592; router4 layers*(256*4)=4096. Actual independently counted shared LM=933632; total LM=933632+4206592=5140224; top2 logical=933632+4*2*262912=3036928. Dense shared=933632-4096=929536; Dense LM=929536+4*262912=1981184. Perception91907+126829+88147=306883; total MoE5447107, Dense2288067. Tied full vocabulary matrix550*256=140800 included once; untied adds140800. These are allocated weight counts, not per-token FLOPs or memory measurements.')]

claims = []
def ev(s,where,supports): return {'source_id':s,'locator':where,'supports':supports}
def claim(i,kind,text,location,evidence,ids,scope,expected=None,observed=None,details=None,denominators=None):
    row=dict(id=i,kind=kind,statement=text,location=location,status='verified',evidence=evidence,artifact_ids=ids,scope=scope)
    if kind!='concept':
        row['verification']=dict(method='executed',expected=expected,observed=observed,details=details)
        if kind=='numeric':row['verification']['tolerance']='整數及identity精確相等；路由浮點manual-vs-code最大差容忍1e-6，實際0。'
        if kind=='empirical':row['verification']['denominators']=denominators
    claims.append(row)
claim('c1','concept','Dense每層一組FFN；本章MoE每層四組可訓練expert，router為每個有效位置選兩組並按gate合併；沒有預写模態專家規則。','19.md:76',[ev('s_moe','§2.1, PDF pp2-3；Figure1','expert是standard FFN；每token top-k sparse gate weighted sum的一般定義'),ev('s_model','MaskedBlock109-130；PaddingSafeMoE78-94','本成品每層MoE、四選二與valid rows gate合併'),ev('s_ffn','DenseFFN36-53；MoEFFN59-65','expert都是同類可訓練Linear/GELU FFN，router是Linear')],['a_mixtral','a_cpu','a_model','a_modern'],'Mixtral原論文是8選2/SwiGLU，本成品是4選2/GELU；只引用機制，不移植論文容量或品質。CPU反向只核可求梯度，未更新權重。')
claim('c2','empirical','Dense與MoE均有完整成品訓練路線，配置同width256/layers4/heads4/kv_heads2/hidden512與三個感知入口。','19.md:78',[ev('s_receipts','receipts-checked.json#/stages/*/train/config及原始execution returncode；/public_configuration_and_selection','15段完成紀錄和兩份public best来源配置'),ev('s_model','MaskedBlock109-116；LimitedAssistant296-302','架構差異只在FFN選型，perception以共同width構建')],['a_receipts','a_checked','a_public','a_cpu'],'這是兩條真實訓練路線的結構匹配；並非控制其他條件後的MoE因果效益實驗。',expected='兩份同骨幹設定及原始完成紀錄',observed='8段MoE+7段Dense=15段，全部returncode0；兩份公開best SHA皆吻合；感知參數逐項相同。',details='只讀白名單raw/config/status/pointers；用原outer best.pt SHA核對public selected_source，未跑訓練。',denominators={'stages':15,'moe_stages':8,'dense_stages':7,'seed':20261006,'architectures':2})
claim('c3','software','本節fence建立與公開成品同結構的隨機模型，description只數參數，不載入權重、訓練或生成答案。','19.md:80-95',[ev('s_model','SelftrainedConfig25-53；LimitedAssistant296-302；description421-457','構造module及count行為'),ev('s_fence','original-fence.py和original-fence-output.txt','原稿fence原樣實際執行'),ev('s_receipts','receipts-checked.json#/public_configuration_and_selection/architectures/*/capacity/config及/source_code_identity','公開配置及source SHA吻合')],['a_fence','a_fence_code','a_checked'],'只核本次CPU建模与配置，不能驗證成品生成能力。',expected='原樣fence可執行且不含checkpoint/load/backward/optimizer/generate',observed='六行計數輸出符合表；MoE、Dense最後各True。',details='從凍結19.2 bytes擷取唯一Python fence，執行未改動的程式；查公開config所有欄位及defaults tied/backend/auxiliary/version。')
claim('c4','numeric','整個助理參數MoE5,447,107，Dense2,288,067。','19.md:102',[ev('s_count','total LM+three perception encoders公式','總量完整分母'),ev('s_cpu','COUNT行獨立module.parameters計數','不只複讀description結果')],['a_cpu','a_fence'],'全部唯一Parameter物件所儲存的元素，含perception與共享權重；不代表同等FLOPs。',expected='5447107/2288067',observed='5447107/2288067',details='獨立遍歷model.parameters；LM counts加306883；tied物件只一次。')
claim('c5','numeric','文字核心參數MoE5,140,224，Dense1,981,184。','19.md:103',[ev('s_count','共享LM+FFN公式','分母不含任何perception encoder'),ev('s_cpu','COUNT language_parameters與shared_lm','獨立遍歷lm.parameters')],['a_cpu','a_fence'],'文字LM包含完整字表、attention、norm、router/expert；三感知入口排除。',expected='5140224/1981184',observed='5140224/1981184',details='MoE933632+4206592；Dense929536+1051648，精確吻合description。')
claim('c6','numeric','每位置邏輯啟用文字參數MoE3,036,928，Dense1,981,184；是全共享LM加選中expert的結構數。','19.md:80,104',[ev('s_count','active=933632+4*2*262912','按4層兩組FFN計算'),ev('s_model','description421-448','從total LM扣未選expert'),ev('s_cpu','COUNT independently_active及TOPK_VARIATION','獨立排除expert參數並加k份；變k驗公式')],['a_cpu','a_fence'],'共享部分刻意計整張embedding/output矩陣，非每個token實讀的格數；perception不在per-token分母。',expected='3036928/1981184',observed='3036928/1981184；MoEtop1=1985280、top4=5140224，總參數仍5447107。',details='不使用description來定義預期；從named_parameters排expert再加入每層實際expert.numel。')
claim('c7','concept','tied weights使輸入字元embedding與輸出候選分數使用同一張權重表。','19.md:98',[ev('s_tying','PDF p1 §1 U=V與h3=Vh2；pp2-3 §3 U=V=S','weight tying的原始定義'),ev('s_base','TinyLM61-66','本模型直接指定同一Parameter物件')],['a_tying','a_cpu','a_base'],'只核共享參數定義；不宣稱本成品因tying提高品質。')
claim('c8','software','兩架構的embedding.weight is output.weight皆True，計數只算一次。','19.md:95,98',[ev('s_base','TinyLM65-66','共享物件賦值'),ev('s_cpu','COUNT與UNTIED_VARIATION行','物件identity、named_parameter去重及實際untied對照')],['a_cpu','a_fence'],'本次模型建構與PyTorch2.14.1+cpu；共享是字表矩陣，無額外輸出bias。',expected='True、True；untied各多550*256',observed='True、True；untied各多140800且identity False。',details='named_parameters(remove_duplicate=False)多列一份名稱但unique parameter id少一；sum(parameters())只數唯一物件。')
claim('c9','software','attention、字表、norm等共同零件由各位expert共用，而非複製到每組expert。','19.md:98',[ev('s_model','MaskedBlock109-130；SelftrainedLanguageModel134-151','block共用attention/norm，僅ffn ModuleList分expert'),ev('s_ffn','MoEFFN59-65','experts只含DenseFFN')],['a_cpu','a_model','a_modern'],'每層有自己的attention/norm；共用是同一層experts之間及共用LM字表，不說全層使用同一attention權重。',expected='expert參數只在.ffn.experts；共享LM與router獨立',observed='expert4206592，router4096，共享LM933632；Dense無expert/router ModuleList。',details='讀實際module契約和named_parameters，CPU獨立分組計數。')
claim('c10','numeric','三個感知入口與接頭合計兩架構皆306,883。','19.md:105',[ev('s_model','VisionEncoder188-214、OCREncoder217-244、AudioEncoder247-282','計數覆蓋CNN/GRU/head/projections/position/norm'),ev('s_cpu','COUNT perception_parameters','三module獨立計數')],['a_cpu'],'全部感知模組儲存量，含head/接頭；不是每個文字位置同時必算三入口。',expected='306883/306883',observed='image91907+ocr126829+audio88147=306883，两架構完全相同。',details='按model.vision_encoder/ocr_encoder/audio_encoder.parameters獨立求和，與全部减LM差相同。')
claim('c11','concept','邏輯啟用數不能當運算次數、分派花費或執行時記憶體；所有experts仍儲存，不同位置可選不同expert。','19.md:107',[ev('s_moe','abstract p1；§2.1 pp2-3；§3 Size and Efficiency p4','不同token路由、active/total區別、服務memory按全部參數且routing有overhead'),ev('s_cpu','TOPK_VARIATION和ROUTING_VARIATION','k變化總量不變；兩位置分別選[0,1]/[2,3]')],['a_mixtral','a_cpu'],'一般方法由原論文支持；本地不做latency、peak-memory或FLOP實測，不把小模型時間外推。')
claim('c12','numeric','本章MoE每位置每層兩FFN，Dense一FFN；這對模型未匹配計算量或儲存量。','19.md:107',[ev('s_count','MoE active/shared與Dense公式','相同hidden512時兩組FFN對一組，router另增'),ev('s_moe','§2.1 pp2-3 K controls amount of compute；p4 routing/memory limits','k影響工作量、total影響memory，不可用active数直接報真成本')],['a_cpu','a_fence'],'確定結構沒有匹配；不聲稱實際速度恰好兩倍、RAM精確比值或峰值記憶體。',expected='每層MoE2*262912對Dense262912且總儲存數不同',observed='top2 choice shapes各[1,3,2]；total5447107對2288067。',details='CPU完整forward核四層路由形狀；參數推導和實數計數共同核匹配範圍。')
claim('c13','empirical','兩路最終訓練目標與選定歷程不同，得分差不足以直接歸因MoE；本節計數不證生成能力。','19.md:109',[ev('s_receipts','receipts-checked.json#/stages moe-native/dense-weighted /train/{tool_loss_weight,numeric_run_loss_weight,native_voice_loss_weight,stage_history}及public selected_source','最終目標4/1/4對4/4/1；歷史SFT選8000對6000，MoE另加native段'),ev('s_fence','original-fence.py','只構造及description，沒有生成/評分流程')],['a_receipts','a_checked','a_public','a_fence'],'只核兩份原始成品訓練與provenance；不重跑原heldout、不認定任何得分優劣或整體能力pass。未控制目標/歷程，不能作架構因果效果結論。',expected='原始final objective及選版歷程不相同',observed='MoE native4000 completed steps、tool4/numeric1/native4；Denseweighted10000、tool4/numeric4/native1。SFT選定8000對6000；best權重SHA各與public match。',details='按raw receipts計數/配置/history與outer best table自主核對，未讀public final_test/capability_acceptance或作者comparison摘要。',denominators={'moe_final_steps':4000,'dense_final_steps':10000,'moe_final_input_tokens':7977108,'dense_final_input_tokens':19945149,'moe_final_target_tokens':2048891,'dense_final_target_tokens':5126644,'train_rows_each':28876,'validation_rows_each':2435,'seed':20261006,'test_used_for_selection':False})
claim('c14','numeric','固定成品字表總編號550，是539個普通字元加11個特殊編號。','19.md:87,114',[ev('s_tokenizer','SPECIAL_NAMES7-8；CharacterTokenizer15-27','固定specials與普通字元總和'),ev('s_cpu','TOKENIZER_FIXED_DATA行','12檔SHA吻合後重建與公開tokenizer definition精確相同'),ev('s_receipts','/stages/*/train/config/vocab_size','原始訓練配置皆550')],['a_cpu','a_tokenizer','a_manifest','a_witnesses'],'普通字元包含非中文字元和ASCII；550不是中文字數或完整中文詞彙規模。',expected='550',observed='539+11=550；train28876 rows127700 messages；public definition一致。',details='驗12份JSONL byte及SHA後，對train messages獨立set union；與helper產生字表和public tokenizer逐項相等；SHA採實际training serializer。')
claim('c15','software','普通字表只由train文字加固定ASCII32..126及12個OCR字元建立；validation/test不擴字表。','19.md:114',[ev('s_dataset','train_tokenizer84-91','明確篩split=train並只加入固定字元'),ev('s_tokenizer','build30-36、OCR_CHARACTERS9','set union來源及12OCR字元'),ev('s_train','main728-753','首次train_tokenizer，後續採source tokenizer并核SHA')],['a_cpu','a_dataset','a_tokenizer_code','a_manifest'],'固定ASCII與OCR字元來自預設格式/任務規約，非heldout文字。重建字表不是重跑訓練或heldout成績。',expected='train-only union；改test-only新增字符不變字表',observed='95ASCII+12OCR與train union=539；synthetic追加test 💡後definition不變；val 🦄保留UNK。',details='實際原fixed資料重建，再以train/validation/test三分小變化核helper分支；公開tokenizer逐项吻合。')
claim('c16','software','普通文字逐字編碼；字表外字符變未知字元，小字表不能當完整中文詞彙。','19.md:114',[ev('s_tokenizer','encode38-41、decode43-56；SPECIAL_NAMES7','每Unicode字符一ID，未見字符get(default unk_id)，顯示為�')],['a_cpu','a_tokenizer_code'],'這是有限character tokenizer，沒有完整中文覆蓋的宣稱；role/modal控制ID由程式插入而非普通literal字串自動解析。',expected='未見字元ID10；literal <user>照普通逐字編碼',observed='🦄->[10]->�；<user>->[39,96,94,80,93,41]，並非control user_id3。',details='實際執行原encode/decode與required_chars小字表；未要求合成unicode全覆蓋。')

report = dict(schema_version=1,review_stage='technical',lesson_id='19.2',source='course/chapters/19.md#19.2',reviewer_task='/root/p6_fact_19_2',reviewer_context='fresh',source_sha256=sha(ART/'19.2.md'),figure_sha256={},verdict='pass',claims=claims,sources=sources,artifacts=artifacts,issues=[],checks={
'factual_accuracy':dict(status='pass',details='逐主張核FFN/router/tied/config/tokenizer，原始配置及兩路完成來源均吻合；未把設計動機或count當能力成績。',claim_ids=['c1','c2','c3','c7','c8','c9','c13','c15','c16']),
'numeric_verification':dict(status='pass',details='原稿fence原樣執行；全部、LM、active、perception數均精確吻合，另獨立FFN公式/untied/top-k反例與固定資料字表重建。',claim_ids=['c4','c5','c6','c10','c12','c14']),
'figure_consistency':dict(status='not_applicable',details='19.2沒有Markdown引用圖、SVG或需要畫面判讀的素材；表格逐數核對完成。',claim_ids=[]),
'source_verification':dict(status='pass',details='親取並讀Mixtralv1和Press/Wolfv3原始PDF定位；AST先定位再讀原碼；JSON keys後只取明列raw pointers；永久存raw原件/公開tokenizer/source SHA。',claim_ids=[c['id'] for c in claims]),
'limitations':dict(status='pass',details='logical active包含全共享字表，排除perception、分派/FLOP/峰值memory；4選2對Dense1不是計算/儲存匹配；最終目標及選定歷程不同，不能作MoE因果優勢或生成能力驗收。',claim_ids=['c2','c3','c6','c10','c11','c12','c13','c14','c15','c16'])},inspection_artifact_id='a_inspection',initial_frozen_input={'artifact_id':'a_frozen','sha256':sha(ART/'frozen-19.md'),'meaning':'初次保存的整章frozen input，不用作目前整章hash'},verification_history_artifact_id='a_history')
(ROOT/'docs/technical-reviews/19.2.json').write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n')
print('WROTE', 'docs/technical-reviews/19.2.json', 'claims',len(claims),'artifacts',len(artifacts),'verdict',report['verdict'],'source_sha256',report['source_sha256'])
