from pathlib import Path
import hashlib,json,re,shutil,datetime
ROOT=Path.cwd();BASE=Path('docs/technical-reviews/artifacts/p6-public-a');ORIG=BASE/'originals'
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def load(p):return json.loads(Path(p).read_bytes())
sources=[];artifacts=[];pages=[]
def repo(sid,path,note,kind='repository_code'):
 sources.append({'id':sid,'kind':kind,'title':path,'path':path,'sha256':sha(path),'version':'current working-tree bytes inspected 2026-10-06','verified':True,'checked_original':True,'inspection_note':note})
def original(sid,match,note,kind='official_source',url=None,version=None):
 p=next(ORIG.glob(match));records=[]
 for f in ORIG.glob('*download-index.json'):records.extend(load(f))
 row=next((x for x in records if x.get('path')==str(p)),{})
 sources.append({'id':sid,'kind':kind,'title':p.name,'url':url or row.get('url'),'path':str(p),'sha256':sha(p),'version':version or ('immutable Git commit in URL' if re.search(r'[a-f0-9]{40}',row.get('url','')) else 'official source accessed 2026-10-06; SHA-bound snapshot'),'accessed_on':'2026-10-06','verified':True,'checked_original':True,'authority_reason':'Original maintainer/publisher repository, official documentation, original paper, or original hosting API as identified by the HTTPS URL.','inspection_note':note})
def art(aid,path,kind,description,command=None,result=None):
 a={'id':aid,'path':path,'sha256':sha(path),'kind':kind,'description':description}
 if command:a.update(command=command,result=result,environment={'python':'3.13.5','torch':'2.14.1+cpu','device':'cpu'})
 artifacts.append(a)
def claim(cid,kind,statement,loc,refs,scope,status='verified',pointers=None,denominators=None,artifact_ids=None):
 c={'id':cid,'kind':kind,'statement':statement,'location':loc,'status':status,'evidence':[{'source_id':s,'locator':l,'supports':support} for s,l,support in refs],'artifact_ids':artifact_ids or [],'scope':scope}
 if pointers:c['measurement_pointers']=pointers
 if denominators:c['denominators']=denominators
 return c
def addpage(path,claims,summary):
 frozen=BASE/'initial-input'/path
 assert sha(path)==sha(frozen),path
 figs={}
 for rel in re.findall(r'!\[[^\]]*\]\(([^)]+\.svg)\)',Path(path).read_text()):
  p=(Path(path).parent/rel).resolve().relative_to(ROOT);figs[str(p)]=sha(p)
 bad=any(c['status']!='verified' for c in claims);verdict='revise' if bad else 'pass'
 pages.append({'source':path,'source_sha256':sha(path),'frozen_input_path':str(frozen),'frozen_input_sha256':sha(frozen),'read_scope':'Full current UTF-8 Markdown, all headings, tables, prose and fences; direct figures rendered and viewed at 640 and 360 px.','reviewer_summary':summary,'figure_sha256':figs,'verdict':verdict,'claims':claims,'checks':{'factual_accuracy':{'status':verdict,'details':'Original source and implementation checks; unresolved/contradicted claims stay revise.','claim_ids':[c['id'] for c in claims]},'numeric_verification':{'status':'revise' if any(c['status']!='verified' and c['kind'] in ['numeric','empirical'] for c in claims) else 'pass','details':'Original denominator/count/hash reaggregation and bounded CPU execution; no new model evaluations.','claim_ids':[c['id'] for c in claims if c['kind'] in ['numeric','empirical']]},'figure_consistency':{'status':'pass' if figs else 'not_applicable','details':'Referenced figure bytes rendered and personally viewed at both widths; labels/arrows/numbers checked.' if figs else 'This page has no directly referenced figure.','claim_ids':[c['id'] for c in claims if c['kind']=='figure']},'source_verification':{'status':verdict,'details':'Each substantive claim has its own original source locator and support scope; historical readback record remains unresolved where stated.','claim_ids':[c['id'] for c in claims]},'limitations':{'status':'pass','details':'Finished training, validation-selected demonstrations, final-test ability, historical auxiliary experiments, and future/design instructions are kept distinct.','claim_ids':[c['id'] for c in claims]}}})
repo('inventory','course/lesson-index.json','Counted 283 generated lessons; cross-checked numbered headings and all notebooks in verify_public_evidence.py.','original_record')
repo('pyproject','pyproject.toml','requires-python, cpu/cu126/cu130 conflict group and wheel indexes; notebook/dev/site/selftrained groups.')
repo('lock','uv.lock','Recorded current pinned lockfile, including CPU Torch and Zensical; no lock or package mutation performed.')
repo('build','scripts/build_course.py','BOOTSTRAP lines 25-62; notebook lines122-172; build175-236. Code-generated lesson source, setup cell, indexes and --check contract.')
repo('export','scripts/export_course.py','DOCUMENTS, checked_notebook96-108, reading_markdown111-180, build212-368. Revision links, rejection of stale/unexecuted/error cells, strict Zensical and build-info.')
repo('site','scripts/check_site.py','check32-123: internal links/fragments, figures, notebook content, search and exact revision Colab URLs.')
repo('notebooks','scripts/check_notebooks.py','run_kernel34-50 and main53-103; distinct NotebookClient per file, allow_errors=False, output receipts and nonzero failure exit.')
repo('pages',' .github/workflows/pages.yml'.strip(),'Full current workflow: main/manual triggers, 40-minute build, required LFS object, separate review checks, serial independent CPU kernels, strict site build/link checks, artifact/deploy jobs.')
repo('ci','.github/workflows/ci.yml','Full matrix: Linux/Windows CPU and macOS, check_env and pytest. Whole-course Notebook kernels run separately.')
repo('fetchassets','scripts/fetch_training_assets.py','main13-42: all is exactly eight manifest IDs, detects pointer, calls git lfs pull, then verified unpack.')
repo('unpack','tiny_perceptron/assets.py','unpack_asset20-83: archive bytes/hash; allowlisted regular files; file hashes; existing identical files skipped, differing files rejected before copying.')
repo('assetmanifest','assets/training/manifest.json','/assets/*/{id,archive_bytes,training_records,license,files}; 8 archives 30,854,837 bytes, 1,447 pilot train records; entities and member bytes independently checked.','original_record')
repo('v2manifest','docs/selftrained/v2-manifest.json','/package,/records,/assets,/model_config. Every archive member checked against records+assets, split counts computed from immutable tar.','original_record')
repo('train','scripts/train.py','main188-393: default args.train=False, one forward/backward batch, optimizer.step and saving gated by --train.')
repo('v2train','scripts/selftrained/train.py','stage_records84-103; export235-281; validation_loss611-628; main689-793; checkpoint850-876; selection878-901. From-random initialization, train/validation selection and full checkpoint versus safe export.')
repo('localstage','scripts/selftrained/train_local_stage.py','local_source52-85 and main118-251; owns local full best.pt/latest.pt and their execution/training/receipt sidecars; refuses unsafe or tampered state.')
repo('v2model','tiny_perceptron/selftrained/model.py','Config25-53; sparse forward59-105; LimitedAssistant init296-302 and modality embedding308-355. Separate perception encoders feed shared LM; no mature ASR import.')
repo('inference','tiny_perceptron/selftrained/inference.py','verify_export74-98; fetch_public_export101-136: exactly three payloads plus manifest, fixed 40-hex revision, token=False, integrity before allocation; custom model loader.')
repo('evaluate','scripts/selftrained/evaluate.py','THRESHOLDS39-49; score branches270-302; original per-task aggregation and voice continuation. Tool roundtrip demands matching parameters, executed calculator and final reply.')
repo('plan','docs/course-experiments/plan.json','/sequence; 30 experiments and explicit module/function/assets mapping for all seven source adapters.','original_record')
repo('run','scripts/course_experiments/run.py','experiment_spec17-23/list_assets26-30 and execute58-163: resolves plan entrypoint and explicit dependency/assets context.')
repo('textadapters','scripts/course_experiments/text.py','run_real_text317-345; _natural_chat_pilot518-553. Complete story/poem grouping and first-turn UTF-8 excerpts, then own splits and saved fingerprints.')
repo('behavioradapters','scripts/course_experiments/behavior.py','_pku_pilot467-500 selects safer only if also marked safe; _natural_dpo_pilot668-707 chosen/rejected extraction, grouping, UTF-8 excerpts and fixed reference.')
repo('modaladapters','scripts/course_experiments/modalities.py','_resample_8_to_16985-993; run_real_modal996-1097 reads actual PNG/WAV and enforces mono8kHz before explicit sinc16kHz transformation.')
repo('legacyexports','docs/course-experiments/public-models.json','/models/*/files: 30 model groups and exactly120 .pt checkpoint entries; other manifest/license files not counted as checkpoints.','original_record')
repo('capstoneexports','docs/course-experiments/capstone-public.json','/models/*/files: 11 .pt checkpoints, eight phase/quantized and three student entries.','original_record')
repo('release','scripts/course_release.py','inference_payload170-257 allowlists inference fields, strips optimizer and stochastic training state; model formats and companions stay paired.')
repo('v2release','docs/selftrained/v2-jobs/release-final-four-exports.json','/release/exports/*/files: four groups with exactly four fixed bytes/hashes each, explicit per-file MIT and approved redistribution. Only licensing/file-identity metadata read.','original_record')
repo('transport','scripts/selftrained/hf_transport.py','approved_public_files304-328 and validate_batch_release383-406 enforce bounded approved safe files, exact source identities and explicit licenses.')
repo('checkenv','scripts/check_env.py','pick_device and main: selected-device 256x256 matrix forward/backward. Actual local environment executed; no cross-device extrapolation.')
repo('envtests','tests/test_env.py','test_accelerator_matches_cpu29-32 is a32x32 accelerator/CPU comparison; no whole-course MPS training check.')
repo('checks','scripts/check_technical_reviews.py','_validate212-267 reads raw source/figure/artifact hashes, schema/status and distinct reviewer declarations; cannot prove actual reading or human learning.')
repo('readerchecks','scripts/check_course_reviews.py','main47-88 checks current source/figure fingerprints, pass and independent reader task declarations; publishing invokes it.')
repo('naturalrelease','docs/natural-assistant/v4/public-release.json','/selected_variant=base,/adapter_parameters=0,/base_model,/asr_model,/dependency_versions,/files; selected official repositories/revisions, not copied model weights.','original_record')
repo('naturalmanifest','docs/natural-assistant/v4/manifest.json','/archives size/hash; /counts has no audio train rows; fixed audio rows remain validation/test. Checked all3 local LFS objects.','original_record')
repo('naturalrequirements','requirements-natural.txt','Full fixed dependency list; Torch2.8.0/torchvision0.23.0 independent from main uv lock.')
repo('naturalcli','scripts/natural_assistant.py','CLI audio branch118-132 calls original Whisper transcriber and sends transcript to shared chat assistant.')
repo('scorer','scripts/score_natural_v4_validation.py','score_blind352-476; predeclared counts/EOS/nonregression gates choose only eligible strict improvements; no new answer scoring executed.')
repo('license','LICENSE','Original copyright holder MIT terms for own code/docs/artwork; external source data retain individual licenses.','legal_notice')
repo('webconfig','zensical.toml','Full site options and fixed MathJax3.2.2 external CDN; no claim of offline formula rendering.')
repo('webcss','course/web/course.css','SVG zoom styling and prefers-reduced-motion rule inspected; labels remain in the static SVG.')
repo('webjs','course/web/course.js','Existing diagram zoom mechanism read; no new frontend behavior added.')
for sid,match,note in [
 ('uv','*astral-sh__uv__main__docs__concepts__projects__sync.md','Automatic sync lines7-32; frozen uses existing lock without refreshing/checking lock; extras/groups selection sections.'),
 ('lfs','*github__docs__main*about-git-large-file-storage.md','About section and pointer format: Git stores pointers, remote LFS stores payload; oid SHA256 and size.'),
 ('lfsbilling','*github__docs__main*product-billing__git-lfs.md','Billing/storage/bandwidth sections: new file contents occupy storage and downloads use billed bandwidth; no permanent quota promised.'),
 ('hfstorage','huggingface.co__docs__hub__storage-limits','Original official storage limits: paid private storage and responsible public repository use; no unlimited private backup guarantee.'),
 ('hfapi','huggingface.co__api__models*__v2_recursive_true','Anonymous original HF API result: 16 files under4 export directories; safe weight LFS SHA256 matches original manifest/freeze/test.'),
 ('cudadocs','docs.nvidia.com__deploy__cuda-compatibility__index.html','Official compatibility and minimum driver explanations; version/hardware/driver pairing, no speed ranking inferred.'),
 ('pytorchinstall','pytorch.org__get-started__locally__','Official platform/package selection instructions; hardware and CUDA availability need runtime verification.'),
 ('githubpages','*github__docs__main*using-custom-workflows-with-github-pages.md','Configure Pages to GitHub Actions and use uploaded Pages artifact/deploy workflow; publication is separate from local build.'),
 ('fashionlicense','*zalandoresearch__fashion-mnist__master__LICENSE','Full original Zalando MIT permission/copyright; archive original Fashion-MNIST license retains same notice.'),
 ('mindslicense','huggingface.co__datasets__PolyAI__minds14__raw__main__README.md','Original dataset creator card lines22-23/1029 grantsCC BY4.0; feature metadata does not supply known per-record speaker IDs.'),
 ('sanslicense','*googlefonts__noto-cjk__main__Sans__LICENSE','Full SIL OFL1.1 notice from original font publisher.'),
 ('seriflicense','*googlefonts__noto-cjk__main__Serif__LICENSE','Full SIL OFL1.1 notice from original font publisher.'),
 ('storieslicense','huggingface.co__datasets__roneneldan__TinyStories__raw__main__README.md','Original creators dataset card frontmatter: CDLA-Sharing1.0.'),
 ('poetrylicense','*chinese-poetry__chinese-poetry__master__LICENSE','Full original repository MIT terms.'),
 ('chatlicense','huggingface.co__datasets__HuggingFaceH4__ultrachat_200k__raw__main__README.md','Original distributor card line4 MIT; independently checked, not inherited project MIT.'),
 ('feedbacklicense','huggingface.co__datasets__HuggingFaceH4__ultrafeedback_binarized__raw__main__README.md','Original distributor card line4 MIT; independently checked.'),
 ('pkulicense','huggingface.co__datasets__PKU-Alignment__PKU-SafeRLHF__raw__main__README.md','Original owner card line39 CC-BY-NC4.0; noncommercial qualifier confirmed.'),
 ('gsml','*openai__grade-school-math__master__LICENSE','Full original OpenAI MIT grant; original GSM human-written solution data are not per-example generated teacher targets.'),
 ('fsdd','*Jakobovski__free-spoken-digit-dataset__master__README.md','Original repository lines4/53 8kHz WAV, lines87-88CC-BY-SA4.0. Separate LICENSE URL404; README is the original grant.'),
 ('nano_cpu','*nanochat__92d*__runs__runcpu.sh','Full runnable CPU recipe, depth6 base training, base evaluation and chat SFT. Recipe read, not executed.'),
 ('nano_speed','*nanochat__92d*__runs__speedrun.sh','Tokenizer training, base pretraining/evaluation and chat SFT/evaluation sequence; depth24 primary scale control.'),
 ('nano_tok','*nanochat__92d*__scripts__tok_eval.py','Tokenization compression/roundtrip at lines180-235.'),
 ('nano_bpb','*nanochat__92d*__nanochat__loss_eval.py','evaluate_bpb9-65; valid target bytes denominator, ignored/special tokens excluded, total nats/(ln2*bytes).'),
 ('nano_gpt','*nanochat__92d*__nanochat__gpt.py','MLP139 ReLU squared; embedding174 and separate lm_head177 untied; full Dense block definition.'),
 ('nano_mask','*nanochat__92d*__nanochat__tokenizer.py','render_conversation140-224 returns IDs and assistant-supervision mask; visualize_tokenization226-238.'),
 ('mmv_readme','*minimind-v__186*__README.md','Original pinned README239-260 directSFT/optionalcaptionPretrain,450-507text-only rehearsal and frozenSigLIP2 setup.'),
 ('mmv_model','*minimind-v__186*__model__model_vlm.py','Vision projector23-43; originalSiglip model loading52-58 frozen; placeholder-to-feature replacement76-127; shiftedCE157-160.'),
 ('mmv_data','*minimind-v__186*__dataset__lm_dataset.py','generate_labels75-91 starts with-100 and only assistant content/EOS labels enabled.'),
 ('mmv_freeze','*minimind-v__186*__trainer__trainer_utils.py','init_vlm_model66-96 loads priorMiniMindLLM; projector and first/last layers trainable forfreeze_llm1.'),
 ('mmv_sft','*minimind-v__186*__trainer__train_sft_vlm.py','argfreeze_llm default1 at102, callinit133; directSFT from_weightllm.') ,
 ('mmv_config','*minimind-v__186*__model__model_minimind.py','Defaults hidden_act=silu25,tie_word_embeddings=True30; gatedFFN and tiedweight assignment247;Dense/MoE block choice.'),
 ('mm_readme','*minimind__f659*__README.md','Original737-755 separates hard answer imitation from temperature/CE+KL;776-802 domain/identityLoRA.'),
 ('mm_moe','*minimind__f659*__model__model_minimind.py','MoE148-185 routes top-k per token to ModuleList experts and computes auxiliary balance; all experts remain stored.'),
 ('mm_dpo','*minimind__f659*__trainer__train_dpo.py','Original hand-written sequence-log-probability preference objective and frozen reference.'),
 ('mm_distill','*minimind__f659*__trainer__train_distillation.py','distillation_loss24-36,T-scaled soft targets and KL; teacher frozen and shifted supervision mask47-54; CE+KL mixture.'),
 ('smol_sft','*smol-course__f445*__unit1__1.md','Original official instruction tuning unit12-20/51-60 distinguishes pretrained next-token objective and supervised instruction adaptation.'),
 ('smol_pref','*smol-course__f445*__unit2__1.md','Original official preference alignment unit19-28 separatesSFT thenDPO, without a separately trained reward model.'),
 ('pku_reward','*safe-rlhf__e8*__README.md','Original reward/cost formulation58-79: helpful highreward and harmless lowcost.'),
 ('ao_quant','*ao__a701*__quantization_overview.rst','Originalquantizationstack1-49; lowprecisionnumerics, tensor/storagetypes and kernels are distinct components.'),
 ('ao_qat','*ao__a701*__qat.md','OriginalQAT1-26 fakequant retains floating dtype during training; prepare/convert distinction.'),
 ('torchupdate','*pytorch__tutorials__main*optimization_tutorial.py','Original tutorial140-142 explains accumulate,zero_grad,backward,step; either zeroing before backward or after previousstep satisfies no stalegrad contract.'),
 ('official_cs','cs336.stanford.edu__','Original course page Spring2026; evaluation,datafiltering/dedup/synthetic and multimodality schedule.'),
 ('official_mit','introtodeeplearning.com__','OriginalMIT6.S1912026 page, computer vision/language/reinforcement modules; no videos viewed.'),
 ('official_harvard25','harvard-iacs.github.io__2025-AC215__','Original2025 official course description includesRAG/LLMtools/agents.'),
 ('official_harvard26','harvard-iacs.github.io__2026-AC215__','Original2026 official course description includesRAG/agentic workflows andLoRA; nohistorical teaching completion inferred.'),
 ('official_ntu25','speech.ee.ntu.edu.tw__~hylee__ml__2025-spring.php','Original2025 course index listsPost-trainingandForgetting/reasoning; only currentofficialtopicindexread.'),
 ('official_ntu26','speech.ee.ntu.edu.tw__~hylee__ml__2026-spring.php','Original2026 course index/assignmentFinetuningwithoutForgetting; nofilmviewingoruploaddatereverified.')]: original(sid,match,note)
original('lora','arxiv.org__html__2106.09685v2','OriginalLoRAabstract andlow-rankupdate sections: pretrainedweights frozen, trainablerankdecomposition injected; no guarantee allhardware memoryimproves.',kind='paper',version='arXiv2106.09685v2',url='https://arxiv.org/html/2106.09685v2')
original('distill','arxiv.org__html__1503.02531v1','OriginalAbstract/Introduction/Distillation: teacher knowledge transfers into smallerstudent; softtargettemperature is method, not guaranteed quality.',kind='paper',version='arXiv1503.02531v1',url='https://arxiv.org/html/1503.02531v1')
# APIs fetched directly, independently of any old repository review summary.
for sid,name,url,note in [('ciapi','api.github.com__repos__birdhackor__tiny-perceptron-vlm__actions__runs__37071683289__jobs','https://api.github.com/repos/birdhackor/tiny-perceptron-vlm/actions/runs/37071683289/jobs','All4 originalCI jobs completed/success,includingmacOS; inspected originaljob names/outcomes.'),('lfsrun','api.github.com__repos__birdhackor__tiny-perceptron-vlm__actions__runs__36946663981','https://api.github.com/repos/birdhackor/tiny-perceptron-vlm/actions/runs/36946663981','Originalruncreated2026-10-02 at3fbe689... completed/success; pairedfixedworkflowonlyrebuild/hash/upload.')]:original(sid,name,note,url=url)
original('lfsuploadworkflow','raw.githubusercontent.com__birdhackor__tiny-perceptron-vlm__3fbe*__ci.yml','Full immutableoriginalworkflow: rebuild pinnedall8withSHAverification then git-lfs push; does not perform anonymous coldcache readback.',url='https://raw.githubusercontent.com/birdhackor/tiny-perceptron-vlm/3fbe6897818cf96d673cc790c5ee5fdc8a90e848/.github/workflows/ci.yml',version='3fbe6897818cf96d673cc790c5ee5fdc8a90e848')
repo('measurements',str(BASE/'verified-measurements.json'),'This reviewer executed the saved standard-library/CPU structural check; independently calculated allcount/hash denominators and retained allnamed original measurement pointers.','execution')
for name in ['gpu-smoke-result.json','course-experiments/results/capstone_deployment.json','course-experiments/results/capstone_student.json','validation-artifacts/release-compatibility-ci.json','natural-assistant/evidence/v4-research/student-selected-public-ui/actual-ui/report.json','natural-assistant/evidence/v4-research/student-selected-public-ui/actual-ui/disk-observation.json','natural-assistant/evidence/v4-runtime/validation-37219466611/blind-review/scored/scores.json','natural-assistant/evidence/v4-runtime/validation-37219466611/blind-review/raw/result.json','natural-assistant/evidence/v4-runtime/validation-37219466611/blind-review/combined/grades.json']:
 sid={'gpu-smoke-result.json':'gpu','course-experiments/results/capstone_deployment.json':'olddeploy','course-experiments/results/capstone_student.json':'oldstudent','validation-artifacts/release-compatibility-ci.json':'mpsrecord'}.get(name,'raw_'+str(len(sources)))
 repo(sid,'docs/'+name,'Top-level keys first; only numerical results, configuration/method or original provenance pointers described in the per-claim evidence. No notes/review/scope-correction or old teaching-review verdict read.','original_record')
raw_ui=next(s['id'] for s in sources if s.get('path','').endswith('actual-ui/report.json'))
raw_disk=next(s['id'] for s in sources if s.get('path','').endswith('actual-ui/disk-observation.json'))
raw_score=next(s['id'] for s in sources if s.get('path','').endswith('blind-review/scored/scores.json'))
for a in ['moe','dense']:
 for file in ['test/metrics.json','test/evaluation-receipt.json','freeze/frozen.json','freeze/metrics.json']:
  sid=a+'_'+file.replace('/','_').replace('.json','');repo(sid,f'docs/selftrained/results/public-raw/{a}/{file}','Top-levelkeys first; checked only raw counts,completion,thresholds,weights/protocol hashes and generation/method configuration, excluding notes.','original_record')
for d in load(BASE/'verified-measurements.json')['training']:
 repo('train_'+Path(d['path']).parents[1].name,d['path'],'Top-levelkeys first; /steps,/total_parameters,/trainable_parameters,/completed_requested_steps,/test_used_for_selection,/origin/kind and stagehistory source hashes. Original complete trainreceipt; no author added result commentary read.','original_record')
art('execution',str(BASE/'verified-measurements.json'),'execution','Own count/hash/shape/receipt checks of original artifacts.','/workspace/tiny-perceptron-vlm/.venv/bin/python docs/technical-reviews/artifacts/p6-public-a/verify_public_evidence.py','Allassertions passed. 283notebooks/309numberedsections;8938media/12JSONL/12supportfiles;15trainreceipts;both3734tests;8chat+1append;meta-onlyparametercounts5447107/2288067.')
art('execstdout',str(BASE/'verify-public.stdout.txt'),'source_snapshot','Originalstdoutfromsuccessfulboundedmeasurementcheck.')
art('execscript',str(BASE/'verify_public_evidence.py'),'code','Executedalgorithm, namedJSONpointers and assertions; notraining,generation,newanswergradingorremotedownload.')
for i,desc in enumerate(['CurrentCPU environment basicforward/backward and versionlist.','Actual first8 assetlist.','283Notebook/source synchronization check.','Fourexistingassetintegrity/idempotence/no-overwritecontracts.']):
 cmd=load(BASE/'executed/commands.json')['commands'][i]['argv'];art('cmd'+str(i),str(BASE/f'executed/command-{i}.txt'),'execution',desc,' '.join(cmd),'Exit0; actualoutput retained.')
for aid,p,command,result in [('sitecontracts','executed/site-contract-tests.stdout.txt','/workspace/tiny-perceptron-vlm/.venv/bin/python -m pytest -q tests/test_course_export.py','17passed; five stale/error variants and navigation/revision contracts.'),('dryrun','executed/minimal-dryrun.stdout.txt','/workspace/tiny-perceptron-vlm/.venv/bin/python scripts/train.py --task text --width 16 --layers 1 --heads 2 --batch-size 1 --max-length 32 --device cpu','Exit0, oneforward/backward, mode=dry-run-no-weight-update,27effective tokens; nooptimizer.step or checkpointwrite.')]:art(aid,str(BASE/p),'execution',result,command,result)
for f in ['rewrite-01-character-ids','curriculum_learning_flow']:
 for width in [640,360]:art(f+str(width),str(BASE/f'figures/{f}-{width}.png'),'figure_render',f'SystemChromium rendered currentSVG at{width}px; personally viewed labels/arrows/numbers.')
R=lambda s,l,x:(s,l,x)
M=R('measurements','verify_public_evidence.py / verified-measurements.json','Own arithmetic/hashes over the namedoriginal records and manifests; no newmodel predictions.')
V=R('v2manifest','/package,/records,/assets','FixedLFS package and per-fileinventory; immutabletar record counts and data scope.')
T=R('v2train','main689-793,checkpoint850-876,select878-901','Fromrandommodel initialization,fullstatecheckpoints and validation-onlyselection; unweightedobjective defaults for validation.')
F=[R('moe_test_metrics','/count,/per_task_final_reply,/thresholds','RawMoEfinaltestcounts andoriginalmetricthresholds.'),R('dense_test_metrics','samepointers','RawDensefinaltestcounts andoriginalmetricthresholds.'),M]
H=[R('hfapi','16fileentries andlfs.oid','ActualanonymousfixedHFexporttree.'),R('v2release','/release/exports/*/files','Fourexactexportgroupsandper-fileMITgrant.'),M]
S='Supports this fixed finite task/data/version and recorded execution; does not establish general natural-input ability or a matched Dense/MoE efficiency comparison.'
addpage('README.md',[
 claim('r1','numeric','20章、A/B/C三支线、283逐课Notebook与309个编号小节。','教材提供什么 ¶1',[R('inventory','allentries','283generatedchapterlessons.'),M],'Currentheading/indexinventory,not a permanentlyfixedcount.',artifact_ids=['execution','cmd2']),
 claim('r2','software','Notebook由正文生成；有程序的课首个代码格包含准备程序，Colab运行未被本机验证替代。','预览段与安装段',[R('build','BOOTSTRAP/notebook122-172','Sameprose/codegenerationandpreparationcell.'),R('notebooks','run_kernel34-50','LocalCPUexecutionroute,not remoteColab.')],'Repository/currentlocalcontract; nofreshColabmachinewasused.',artifact_ids=['cmd2']),
 claim('r3','empirical','v2自行训练文字、视觉/OCR、语音与接头，MoE5447107参数、Dense2288067参数，完成训练但两版均未全达标。','第19章介绍段',F+[T,R('v2model','init296-302','NeuralencodersandsharedLMinitializedinthisimplementation.'),R('train_moe-native','/steps,/completed_requested_steps,/origin/kind','FinalMoE4000stepscompletedfromrandomlineage.'),R('train_dense-weighted','same','FinalDense10000stepscompletedfromrandomlineage.')],S,denominators={'final_test_per_architecture':3734,'training_stage_receipts':15},artifact_ids=['execution']),
 claim('r4','empirical','v2任务限三类服饰/两格位置、12字指定1–4字区域、三个客服语音主题和有限文字/计算器任务。','第19章范围段',[V,R('v2model','modalities308-355','FiniteinputsenterthesharedLM.'),M],S,artifact_ids=['execution']),
 claim('r5','software','第20章另由Qwen3-VL与Whisper现有官方权重组成图文/语音延伸。','第20章介绍段',[R('naturalrelease','/base_model,/asr_model,/selected_variant,/adapter_parameters','SelectedbaseQwen2B/Whisperturbo,noLoRA.'),R('naturalcli','118-132','Audioistranscribedbeforechat.')],'Distinctmaturemodelroute,not evidenceforfrom-scratchv2quality.'),
 claim('r6','software','uv的cpu/cu126/cu130与notebook群组、selftrained safe读取配套和独立natural环境有配对安装选择。','安装表与CPU成品入口',[R('pyproject','optional-dependencies/dependency-groups/tool.uv','ExplicitindexesandmutuallyexclusiveCUDAextras.'),R('uv','Automaticlockandsync/extrassections','uvrunsynchronizesselectedextras.'),R('naturalrequirements','fixedversions','SeparateTorch2.8environment.')],'Read/installcontractverified; nofreshinstallation,CUDAorMacenvironmentexecuted.',artifact_ids=['cmd0']),
 claim('r7','empirical','既有L4/cu126正式训练与MPS基本运算范围分开，整套MPS训练未声称验证。','安装表后说明',[R('gpu','/device,/gpu,/torch','ActualsmokeNVIDIAL4/Torch2.14.1+cu126.'),R('ciapi','/jobs names/status/conclusion','ActualmacOSCIjobcompleted.'),R('mpsrecord','/jobs/*/environment_check,/successful_pytest_step','OriginalMPSenvironment/CIrecord.'),R('checkenv','main','Basic256x256backward.'),R('envtests','29-32','32x32CPUcomparison.')],'BoundedoriginalCIchecks,not fullMPSbook/trainingoruniversalhardwareclaim.'),
 claim('r8','software','最小train命令默认单batch forward/backward且不更新权重；正式更新需要--train。','最小流程代码后',[R('train','main300-309/354-393','Onebatchdryrun; optimizer.stepandsavesgatedby--train.')],'CPUwidth16sampleverified; thisisnot productiontraining.',artifact_ids=['dryrun']),
 claim('r9','numeric','HF v2四组共16配对文件，选joint1000步与完成MoE4000/Dense10000步分开；推论无完整续训状态。','v2公开材料两段',H+[T,R('localstage','52-85','Freshbest versus exactlatest fullstatesidecarcontract.')],S,artifact_ids=['execution']),
 claim('r10','numeric','v2包67862431bytes、8962文件，训练/验证/test为28876/2435/3734题。','自己重做段',[V,M],'Countsinclude12JSONLand12source/provenance/legalfiles,not8962independentmedia.',artifact_ids=['execution']),
 claim('r11','numeric','原30组共120 .pt权重，旧整合另11 .pt权重，推论字段清理后不能精确续训。','历史模型段',[R('legacyexports','/models/*/files','Exactly120 .ptentries.'),R('capstoneexports','/models/*/files','Exactly11 .ptentries.'),R('release','170-257','Allowliststripsoptimizer/RNG/sampler.'),M],'Historicalfixedversions; nofreshdownloadorgenerationoftheseweights.',artifact_ids=['execution']),
 claim('r12','software','Zensical严格建置提供搜索/下载/Colab；MathJax需连网，SVG放大并支持减少动态效果。','网站段与维护命令',[R('export','212-368','ActualZensicalstrictbuildandColab/downloadgeneration.'),R('site','32-123','Localdownloads/search/Colabcontract.'),R('webconfig','extra_javascript','ExternalMathJaxCDN.'),R('webcss','prefers-reduced-motion','MotionpreferenceCSS.'),R('webjs','diagramzoomhandler','ZoomcontrolsretainSVGlabels.')],'Currentconfigurationandcontracttests; no deployed-currentcommit claim.',artifact_ids=['sitecontracts']),
 claim('r13','software','版本不符阻止发布，AI理解/技术审阅与CPU验证是不同工作。','维护段',[R('pages','buildsteps','Bothreviewcheckersaremandatorybeforedeployment.'),R('checks','212-267','Versionhashandreviewstatusschema.'),R('readerchecks','47-88','Separatecurrentreaderreport/figureidentity.')],'Checkerformats/identitiesaredeclarations; notproof ofhumanstudentlearning.'),
 claim('r14','figure','字符与ID双向对应：猫3、狗1、看2、句号0、逗号4；编号不表示字义大小。','README唯一图',[R('nano_mask','tokenizerID/renderingcontract','TokenIDsindexsymbolsnotsemanticmagnitudes.')],'Illustrativesmallvocabularyonly,notv2realvocab.',artifact_ids=['rewrite-01-character-ids640','rewrite-01-character-ids360'])
], '项目入口将教材、本机短检查、自行训练v2、成熟模型延伸和历史权重分开，数值与原始记录相符。')
addpage('docs/environment.md',[
 claim('e1','software','小模型.venv与第20章.venv-natural使用两套固定配套。','导言、第2节',[R('pyproject','requires-python/groups','Mainenvironmentcontract.'),R('naturalrequirements','fixedversions','SeparateTorch2.8.0requirements.')],'Environmentseparation,notnewinstallationproof.'),
 claim('e2','software','uv.lock与frozen固定现有配套，uv run会同步并需保持同extra。','第2节',[R('uv','lines7-32/extrassections','Automaticlocking/syncand--frozenmeaning.'),R('pyproject','tool.uv.sources','ChangingselectedextraaltersTorchindex.')],'frozenusesexistinglockwithoutrefreshing; doesnotitselfprovemetadatacompatibility.'),
 claim('e3','software','cpu/cu126/cu130互斥；CUDA套件、驱动与GPU硬件须匹配，不能由版本号判断快慢。','第3节',[R('pyproject','tool.uv/conflicts/indexes','Explicitpackagechoices.'),R('cudadocs','CUDACompatibility/MinorVersionCompatibility','Officialdriver/runtimecompatibilityconditions.'),R('pytorchinstall','installationselector','Chooseplatform/computeplatform.')],'Documentation/contract,notfreshCUDAinstallationorperformancecomparison.'),
 claim('e4','empirical','公开v2 validation示范完成8chat+1append，支持下载/载入/介面，不是未知题质量。','第2节v2段',[R('inference','101-136','token=Falsefixedrevisiondownloadandhashverification.'),M],'Originalchosenvalidationsamples; nopredictionsre-run.',denominators={'chat':8,'append':1},artifact_ids=['execution']),
 claim('e5','software','局部实验Pillow/soundfile读媒体；第20章Whisper转文字后由图文助手答复。','第4节',[R('modaladapters','996-1097','ActualpixelsandWAVread/resample,notlabel-onlyinputs.'),R('naturalcli','118-132','Transcribefirstthenchat.')],'MatureASRroutebelongs to20chapter; not generalASRfromlocalexamples.'),
 claim('e6','empirical','v2声学特征直接进入共享文字核心；OCR两字体已训练、词表与ROI有限，无Whisper或语音输出。','第4节v2段',[R('v2model','296-355','NeuralAudioEncoder/OCREncoderfeedsharedLM,nomatureASR.'),V,M],S,artifact_ids=['execution']),
 claim('e7','empirical','第20章一次Linux CPU操作证明可执行，资源需求不被说成所有电脑最低要求。','第1节CPU段',[R(raw_ui,'/mode,/interaction,/torch_threads,/server_cpu_resources,/headless_browser_interaction_complete','OriginalCPUChromiuminteractionandprocessresourceobservation.')],'OnecachedLinuxCPUconfiguration; not minimumhardwareorallOS/GPU readiness.'),
 claim('e8','concept','压缩包、解包、模型磁盘与运行内存是不同量；LoRA修正仍需完整底座。','第5节最后段',[R('lora','abstract/low-rankupdate','LoRAaddsupdatebranchtoexistingpretrainedmatrix.'),R('hfstorage','Storage limits','Storedartifactbytesdescribestorage.'),V],'No numericminimum inferred frompackage/adapter size.')
], '环境页是按用途选择工具的操作契约，CPU示范与跨设备能力都明确限定。')
addpage('docs/asset-storage.md',[
 claim('s1','concept','普通Git存代码/文本/清单，LFS存固定大文件实体；pointer含SHA256与size。','第1–2节',[R('lfs','AboutLFS/Pointerfileformat','Officialpointer/payloadseparation.'),R('pyproject','trackedcodecontract','Repositoryconfiguration.'),R('v2manifest','/package','LFSpackageidentity.')],'LFSisstorageindirection,notfilecompression.'),
 claim('s2','concept','LFS不同内容版本占额外储存，下载占流量；HF公共库不是无限私有备份。','第2、4节',[R('lfsbilling','storage/bandwidthbillingsections','Eachchangedpayloadanddownloadconsumesquota.'),R('hfstorage','public/private limits','Storagepolicyandresponsiblepublicuse.')],'Currentofficialpolicyread; nofixedforeverquotaorpricingpromise.'),
 claim('s3','numeric','首批8包30854837bytes、v2一包67862431bytes、自然助理三包146543309bytes。','第3节大小表',[R('assetmanifest','/assets/*/archive_bytes','Eightbaselinearchives.'),V,R('naturalmanifest','/archives/*/bytes','Threenaturalarchives.'),M],'Compressedpackagebytesonly; notunpacked/RAM/modelweights.',artifact_ids=['execution']),
 claim('s4','numeric','v2共8962文件被说明为12JSONL与8950素材。','第3节表后v2句',[V,M],'Actual8950non-JSONLfilesinclude8938mediaand12source/provenance/legalfiles; 素材 classification is inaccurate.','contradicted',artifact_ids=['execution']),
 claim('s5','numeric','v2训练/验证/test为28876/2435/3734题，题数不等于独立媒体；自然助理语音不进LoRA更新。','第3节表后',[V,R('naturalmanifest','/counts train versusvalidation/test audio','Noaudiotrainingrows.'),M],'Questioncountand correlatedmediaareseparate; fixeddataset/recipeonly.',artifact_ids=['execution']),
 claim('s6','software','公开HF四组16 safe文件，使用自订PyTorch类加载，缺optimizer/RNG/sampler。','第4节',H+[R('v2train','235-281','Onlymodeltensors/config/tokenizer/manifestexported.'),R('inference','verify_export/InferenceAssistant','CustomloadernotAutoModelremote-code.')],'Fixedexportsforinference; exacttrainingstateisnotpresent.',artifact_ids=['execution']),
 claim('s7','software','从随机初始化重做后续阶段接自己的best.pt，同段精确续训接自己的latest.pt和完整sidecars。','第4节重做段',[T,R('localstage','52-85/main118-251','Matchinglocalexecution/receipt/statefiles required; noauthorVolumeinput.')],'Implementationcontractandoriginalwidth16CPUwrapperreceipts; nofullproductionretraining.'),
 claim('s8','software','下载核对只是相同文件；网站/模型/数据发布互不替代，版本与配套清单须固定。','第5节',[R('inference','74-136','Hashverifieddownloadispreconditionforinference.'),R('pages','build/deploy','WebsiteartifactdeploymentdoesnotupdateHFexports.'),R('evaluate','270-302','Capabilitiesrequireseparateanswer/toolscoring.')],'Noquality inferred fromsamehashorexit0.')
], 'Git/LFS/HF分工和续训说明符合实现；v2非JSONL文件误称媒体素材需修。')
addpage('assets/training/README.md',[
 claim('a1','numeric','首批8包约29.4MiB、1447 training记录，无模型成果；all只选这八包。','导言与取得段',[R('assetmanifest','/assets and totals','30,854,837bytes/2^20=29.4254656MiB;records1447.'),R('fetchassets','13-42','all is manifestIDs only.'),M],'Pilotdatarecords,nottrainingcompletedmodelorfullupstreamdataset.',artifact_ids=['execution','cmd1']),
 claim('a2','empirical','2026-10-02八包已重建、SHA完全一致并上传，另声称当时冷cache匿名逐包逐档回读。','发布状态段',[R('lfsrun','/head_sha,/created_at,/conclusion','Originalsuccessful2026-10-02uploadrun.'),R('lfsuploadworkflow','fullworkflow','Rebuild/hashall8thenLFSupload; noanonymousreadbackstep.'),M],'CurrenteightcachedLFSentitiesandallfilehashesmatch; exacthistoricalcoldcacheanonymousreadbackhasnocheckedoriginalreceipt.','unresolved',artifact_ids=['execution']),
 claim('a3','concept','八来源授权分别CDLA、MIT、CC-BY-NC4.0与CC-BY-SA4.0，不能统一称repo MIT。','来源授权表',[R('storieslicense','frontmatter','TinyStoriesCDLA-Sharing1.0.'),R('poetrylicense','MITnotice','PoetryMIT.'),R('chatlicense','line4','UltraChatMIT.'),R('feedbacklicense','line4','UltraFeedbackMIT.'),R('pkulicense','line39','PKUnoncommercialCC-BY-NC4.0.'),R('fashionlicense','fullnotice','FashionMIT.'),R('gsml','fullnotice','GSM8KMIT.'),R('fsdd','87-88','FSDDCC-BY-SA4.0.')],'Originalsource-specificgrants,notgenerallegaladviceorinheritancefromrepositorylicense.'),
 claim('a4','empirical','FSDD各20录音/8kHz；Fashion另保留60000来源trainingparquet而50为pilot；GSM解答非教师蒸馏。','表后说明',[R('assetmanifest','/assets/*/files,/training_records','Originalfiles/countsverifiedagainstcachedarchives.'),R('fsdd','4/53','Original8kHzrecordingcontract.'),R('modaladapters','996-1097','Explicit8to16kHz transformation.')],'Tinyhuman/sourcepilot; notcaption/VQAbenchmark or teacher-generatedanswers.',artifact_ids=['execution']),
 claim('a5','software','fetch_assets核对包和成员SHA后解到ignoreddata；相同跳过、不同停止，不更新权重。','取得资料代码后',[R('fetchassets','13-42','Fetchandunpackonly.'),R('unpack','20-83','Allmembersverifiedbeforecopy; preserveedits.')],'Fourexistingofflinecontracttests; historicalremoteanonymousreadbackseparate.',artifact_ids=['cmd1','cmd3']),
 claim('a6','software','不同上游格式需任务适配；七组实验ID可由plan module/function查到真正实现。','使用方式与表格',[R('plan','mapped_entrypoints','real_text/sft/dpo/safety/real_modal/distillation/reasoning assetfunctions.'),R('run','17-30/58-163','Plan-drivenentrypointresolution.'),R('textadapters','317-345/518-553','Story/poem/sftformatconversion.'),R('behavioradapters','467-500/668-707','Preferenceand safelabeltransformation.'),R('modaladapters','996-1097','Pixels/WAVresampling.'),M],'Notinterchangeable rawrecords; whole-source trainingidentitydoesnotdefinecourseholdout.',artifact_ids=['execution']),
 claim('a7','concept','安全偏好不自动是安全SFT正例；自己新实验按故事/题/媒体/近重复家族建立holdout。','使用范围最后两段',[R('behavioradapters','467-500','Saferselectedresponseadditionallymust beexplicitlysafe.'),R('textadapters','317-345/518-553','Ownsourcegroup split construction.')],'Requirementforfutureexperiments; doesnotclaimallhistoricalpilots performednear-duplicateclustering.'),
 claim('a8','numeric','v2 67862431压缩bytes、127161811解包bytes、8962文件，被说成12JSONL与8950素材。','v2段第1段',[V,M],'Actually12JSONL+8335PNG+603WAV+12supportfiles; 8950素材 wordinginaccurate.','contradicted',artifact_ids=['execution']),
 claim('a9','empirical','v2三类服饰、12字两字体、三种语音主题，原录音train/validation/test为62/15/30且speaker ID未知。','v2段第2段',[V,R('mindslicense','datasetfeaturemetadata','Sourcecardlistsaudio/transcripts/intents,notknownpersample speakerIDs.'),M],S,denominators={'original_recordings_train':62,'validation':15,'test':30},artifact_ids=['execution']),
 claim('a10','concept','v2自己的文字/任务与服饰MIT，录音CC-BY4.0，字体SIL-OFL1.1；许可原件保留在immutable包。','v2来源授权句',[R('license','MITgrant','ProjectauthoredcontentownMIT.'),R('fashionlicense','MITnotice','Fashionlicense.'),R('mindslicense','22-23/1029','PolyAIgrant.'),R('sanslicense','fullOFL1.1','Sansfontlicense.'),R('seriflicense','fullOFL1.1','Seriffontlicense.'),V],'WeightMITdoesnotrelicenseallupstreamdata/fonts.'),
 claim('a11','software','v2用自己的完整checkpoint重做，不需要作者Volume；第20章/旧v3另有各自数据入口。','v2末段与第20章段',[R('localstage','52-85/main118-251','Ownlocalstagecheckpointsource.'),R('naturalmanifest','dataset_version/archives','Separatev4fixeddataarchivefamily.'),R('fetchassets','13-42','all doesnotincludev2/v4.')],'Navigationandoperationcontract; noproductiontrainingorv3score borrowedforv2.')
], '素材、记录、来源格式、授权及重做路径可核；v2媒体分类错误与历史匿名冷cache原收据不足保留revise。')
addpage('docs/publishing.md',[
 claim('p1','software','正文由build_course产生Notebook，export_course整理图与CPU结果并呼叫真实严格Zensical。','第1–2节',[R('build','122-236','Generatedsameprose/code.'),R('export','212-368','Strictbuild,outputsanddownloadcopy.')],'Actualcodecontract; notclaimcurrentdeploymentcompleted.',artifact_ids=['cmd2','sitecontracts']),
 claim('p2','software','Colab URL固定网站revision，但准备代码第一次clone默认分支；本机uv lock与Colab pip不同。','第1节最后段',[R('export','ColabURLgeneration','Notebookurlusesexactrevisionargument.'),R('build','BOOTSTRAP','gitclone--depth1 without checkoutrevision; pip-e repo.')],'Oldrevisionusersmust checkoutcorrectproject; noColabcloudrunclaimed.',artifact_ids=['sitecontracts']),
 claim('p3','software','--executed拒绝不同/未执行/错误cell，readingtime要求当前来源；revision标记不保存未commit修改。','第2节命令说明',[R('export','96-108,212-368','Source/executionchecksandrevisionpassedtolinks/build-info.'),R('site','32-123','Downloads/bookmarks/revisionlinkschecked.')],'Softwarevalidationonly; commit/staging areusersactionsseparatefrombuild.',artifact_ids=['sitecontracts']),
 claim('p4','software','main/manual Pages workflow执行必要LFS、独立串行CPU kernels、审阅、严格建置、links、artifact/deploy。','第3节',[R('pages','fullworkflow','Current40minute buildcontractanddeploypermissions.'),R('notebooks','34-50/53-103','Oneindependentclientpernotebook,workers1serial.')],'Currentworkflowcontractwith40minbudget; no new remoteworkflowtrigger/deployment.'),
 claim('p5','software','build-info记录revision、lessons、CPU输出及Zensical版本，部署成功仍需核读者版本。','第3节最后段',[R('export','build-infoendofbuild','Actualfieldswritten.'),R('githubpages','artifact/deploysections','Platformdeploymentseparatefromsourcebuild.')],'Instructionsforfuturepublication,notclaimpublishedcurrentcommit.'),
 claim('p6','numeric','v2 LFS数据与HF四组16固定输出和网站发布彼此独立，文章变化不更新权重。','第4节',H+[V,R('pages','deploymentartifactpath','Website onlyuploadsoutputs/site.')],'Immutableexistingexports; noneupdatedoruploadedbythisreview.',artifact_ids=['execution']),
 claim('p7','software','本地repository-README稿的修改不等于HF根卡更新，根卡发布不改固定safe exports。','第4节最后段',[R('transport','repository-card separatefunction682ff andsafe batch484ff','Rootcardandsafeexportsseparateboundedpublishingfunctions.'),R('hfapi','fixedtree','Existingexportsboundto979cdfcommit.')],'Operationseparation; no assertionHFrootcardalreadycontainscurrentdraft.')
], '网站建置与Notebook/输出版本契约一致，Pages当前是40分钟构建；未把本机建置说成已发布。')
addpage('docs/validation.md',[
 claim('v1','concept','能执行、梯度更新、文件一致、质量和原理验证是不同证据，测试须有未参与更新的分母与规则。','检查表与范围导言',[R('v2train','train/validationselection','Trainupdateseparatefromvalidationchoice.'),R('evaluate','39-49/270-302','Frozenqualityrubricsandexplicittoolroundtrip.'),R('export','96-108','Executability/versionnotsemanticquality.')],'Methodandfixedcontract,notclaimgeneralsafetyquality.'),
 claim('v2','empirical','v2两版各3734最后test，MoE工具0/276、语音42/90、后续26/60、服饰357/360、OCR252/324；均未全达标。','成品范围第2段',F,'Rawfrozenfinal-testnumbers,notnewgeneration; toolroundtripbelow0.95alone establishesbothfailallcriteria.',denominators={'test_per_arch':3734,'tool':276,'voice_qa':90,'voice_continuation':60,'vision_clothing':360,'ocr':324},artifact_ids=['execution']),
 claim('v3','empirical','公开CPU挑选validation成功题8chat+1append不改变最后test分数。','成品范围第3段',[M,R('inference','101-136','Fixedanonymouspublicexportload.')],'Sameweights,chosenvalidationexamples; notunseenaccuracy.',artifact_ids=['execution']),
 claim('v4','software','本机stage wrapper检验的是width16合成CPU契约、自己的best/latest与sidecars，而非全量production重训。','成品范围第3段',[R('localstage','52-85/main118-251','Localprovenanceandfullcheckpoints; ownnewstage/exactresumeseparate.')],'Readoriginalimplementation; didnotreadlinkedpriorindependentreviewverdict or re-runfulltraining.'),
 claim('v5','empirical','v2 28876 train与2435validation选候选，冻结后各3734test；选MoE/Dense joint1000不同于完成4000/10000。','验证选版节第2段',F+H+[T],'Auditboundedby15originalstage/freeze/testreceipts; testnotusedbythecheckedtrainerselectionpath.',denominators={'train':28876,'validation':2435,'final_test':3734},artifact_ids=['execution']),
 claim('v6','empirical','LoRA候选改善部分照片但未保住聊天/完整结束，因此交付base；Whisper与助手可用正确逐字稿对照。','验证选版节第3–4段',[R(raw_score,'/variants/*/correct_counts,/incomplete_case_ids','Originalphotocountsimproved; voicechatcountsdegraded; incompleteEOS remains.'),R('scorer','352-476','FrozenEOS/nonregressionandstrictimprovementselection.'),R('naturalrelease','/selected_variant,/adapter_parameters','Publishedbase0adapter.'),R('naturalcli','118-132','ASRthenchat,typedtranscriptcontrolshareschatpath.')],'Originalvalidationgradesandgenerationcompletiononly; no new holdoutanswergrading.',denominators={'primary_denominator':75600}),
 claim('v7','concept','AI审阅不等于真人学生学习测量；checker只能检查版本、证据与报告；阅读时间不含安装/下载/等待训练。','教材审阅与阅读时间节',[R('checks','212-267','Mechanicalhash/schema/identitydeclarations.'),R('readerchecks','47-88','Versionandreportpresenceonly.')],'Method/reportingdefinitions; nohumanlearningeffectclaimed.'),
 claim('v8','empirical','早期GPU smoke31584参数、80步，从HF第40步续到80、与不中断最大权重差0。','Modal/HF节',[R('gpu','/parameters,/checks,/resume,/device,/gpu,/torch','Originalexact80-stepand40-to80resumerecord.')],'ThatsingleNVIDIAL4tinymodelonly; notnatural-inputabilityorallversionreproducibility.'),
 claim('v9','software','kernel检查用独立NotebookClient并保存outputs/notebooks结果，单元测试与能力分数分开。','自己的版本重跑节',[R('notebooks','34-103','Kernelcount/errors/receipt/outputroot.'),R('export','96-108','Requirescurrentexecutedcellmatching.')],'LocalCPUcontractandcurrentsourcecheck; nofull283-kernelrerunbythisreview.',artifact_ids=['cmd2','sitecontracts'])
], '验证页的层次、v2原分母与原结果可核，训练完成与能力达标、精选示范与最后测试保持分开。')
addpage('docs/curriculum.md',[
 claim('c1','numeric','283逐课Notebook/309小节与v2两版参数、题数、选1000/完成4000与10000相符。','导言前两段',[M,V,T]+F,'Currentinventoryandfixedproductionrecords; notmatchedmodelbudgetcomparison.',artifact_ids=['execution']),
 claim('c2','numeric','v2四组16 safe输出MIT，无完整续训状态；旧30组120和11阶段/学生权重分开。','导言第3–4段',H+[R('legacyexports','/models/*/files .pt','120historicalcheckpoints.'),R('capstoneexports','same','11historicalcapstonecheckpoints.'),R('v2train','235-281','Safeexportscontainmodelonly.')],S,artifact_ids=['execution']),
 claim('c3','empirical','旧joint/DPO78/90与Dense示范62/90、蒸馏61/90仅为历史辅助证据。','导言第4段',[R('olddeploy','/results/stages/{joint,dpo}/{count,end_to_end_correct}','78of90inbothhistoricalbranches.'),R('oldstudent','/results/evaluations/{test_ce,test_kd}/{count,end_to_end_correct}','62and61of90.'),M],'Originalsyntheticworldprotocol,notv2finaltestorcontrollednaturalqualitycomparison.',denominators={'per_old_branch':90},artifact_ids=['execution']),
 claim('c4','software','第20章固定Qwen3-VL2B与Whisperlarge-v3-turbo，不加LoRA。','导言第5段',[R('naturalrelease','/selected_variant,/base_model,/asr_model,/adapter_parameters','basevariant andofficialimmutablemodelrevisions.')],'Matureupstreamextension,notfrom-scratchv2ability.'),
 claim('c5','concept','top-2 MoE选两个FFN，Dense一个；全专家仍储存，不能推断小硬件必省时/内存或同参/同算比较。','导言MoE段',[R('mm_moe','148-185','ExpertsModuleListandtokenleveltop-kforward.'),R('v2model','59-105','Actualvalidrow sparseMoE computation.'),R('measurements','parameter_shape_check and downloadedconfigs','Actualv2top_k2/configurationanddifferenttotalparameters.')],S,artifact_ids=['execution']),
 claim('c6','software','nanochat串tokenizer/pretrain/eval/SFT，CPU与depth入口、BPB/切词压缩/监督mask，ReLU²与未共享输入输出。','参考项目表nanochat各行与表后',[R('nano_cpu','runcpu fullrecipe','CPUanddepth6.'),R('nano_speed','67-76','Train/eval/SFTchain.'),R('nano_tok','180-235','Compressionandroundtrip.'),R('nano_bpb','9-65','Bitspervalidtargetbyte,notmeanlossacrosstokenizers.'),R('nano_mask','140-238','Conversationrenderandassistantmask.'),R('nano_gpt','139/174-177','ReLU²anduntiedweights.')],'Pinned92d63...originalcode,notreproducedtrainingorefficiencyresult.'),
 claim('c7','software','MiniMind-V使用预训MiniMind、冻结SigLIP2/projector替换图片位置，assistant-only labels；直接SFT与可选对齐。','参考表MiniMind-V行',[R('mmv_model','23-58/76-127','Officialvisionencoder/projector/slotreplacement.'),R('mmv_data','75-91','Ignorednon-assistantlabels.'),R('mmv_freeze','66-96','LoadLLMweightandfreezevision.'),R('mmv_sft','102/133','Defaultfreezellm1.'),R('mmv_readme','239-260','OptionalcaptionpretrainanddirectSFT.')],'Pinned1862b...implementationcontract,notgeneralclaimprojectoralignmentguaranteesquality.'),
 claim('c8','software','MiniMind-V保留纯文字以维持语言；默认SiLU gating/共享输入输出，SFT解冻projector与首末层。','表后与冻结表行',[R('mmv_readme','450-507','Text-onlyrehearsalstatedbyoriginalmaintainer.'),R('mmv_config','25/30/FFN/247','SiLUgatingandtie.'),R('mmv_freeze','76-91','First/lastlayers/trainableprojector.')],'Describestheoriginalchosenstrategy; notproofitpreservesalllanguageabilities.'),
 claim('c9','software','MiniMind含身份/领域LoRA、手写DPO、teacher硬回答与CE+KL蒸馏；Smol指令/偏好分开；PKU reward/cost分开。','参考表相应三行',[R('mm_readme','737-802','Originalhard/softdistillationandLoRAexamples.'),R('mm_dpo','reference/preferenceloss','HandwrittenDPO.'),R('mm_distill','24-54','Teacherfreeze,temperatureKLandsupervisionmask.'),R('smol_sft','12-20/51-60','SFTinstructionadaptation.'),R('smol_pref','19-28','DPOafterSFT.'),R('pku_reward','58-79','Helpfulreward/safetycost.')],'Pinnedoriginalprojectfeatures; classdesigndoesnotclaimfullRLHFimplementationorreproducedresearchbenefits.'),
 claim('c10','concept','量化降低数值位宽通常保留参数数目；蒸馏用教师信号与较小学生；MoE部分专家与LoRA少量可训参数各量测。','参考表TorchAO行与后段',[R('ao_quant','1-49','Numericalflow/dtypes/storage/kernelseparate.'),R('ao_qat','1-26','Fakequant/prepare/convert.'),R('distill','Introduction/Distillation','Teacher-to-smallstudentdesign.'),R('lora','abstract/low-rank update','Frozenbaseplusfewtrainablematrices.'),R('mm_moe','148-185','Per-tokensparseexpertselection.')],'Methoddefinitions,notguaranteedquality/memory/speed; quantizationmayaddmetadata and kernelconstraints.'),
 claim('c11','software','网站/Notebook同源，notebook群组含ipykernel/matplotlib/JupyterLab/nbclient，代码核验与Colab分开。','教材呈现方式',[R('build','122-236','Generatednotebooksfromcurrentprose/fences.'),R('pyproject','dependency-groups.notebook','Actualpackages.'),R('export','96-108/212-368','Actualsitesource/codeandverifiedoutputs.'),R('notebooks','34-50','Independentlocalkernels.')],'Currentsoftwarecontract,notnewfullNotebook/Colabexecution.',artifact_ids=['cmd2','sitecontracts']),
 claim('c12','concept','X与下一步Y、可读前文mask与计分mask分开；不累积旧梯度时zero_grad、backward、optimizer.step。','文字训练图与图后解释',[R('nano_mask','140-224','Separateassistanttrainingmaskfromconversationinputs.'),R('torchupdate','140-142','GradientaccumulationandupdateAPI.')],'Figureisone nonaccumulatingupdate; intentionalgradientaccumulationneedsa differentzeroing schedule.',artifact_ids=['curriculum_learning_flow640','curriculum_learning_flow360']),
 claim('c13','empirical','v2有限范围、两字体已见、银行主题直接声学回答、无speaker隔离及一般听写宣称。','当前教材与新增主题末段',[V,R('v2model','296-355','SharedLMwithcustomaudio/image/OCRencoders.'),R('mindslicense','originalmetadatafeatures','Noavailableknownper-recordspeakerIDs.'),M],S,artifact_ids=['execution']),
 claim('c14','scope','近期课程线索对应evaluation/data/multimodality、CV/posttraining、RAG/agents与遗忘/推理；历史代理/镜像/未看影片的文字作为规划记录。','参考来源与近期公开课段',[R('official_cs','currentschedule','Data/evaluation/multimodalityoriginalindex.'),R('official_mit','currentschedule','Vision/language/RLmodules.'),R('official_harvard25','courseoverview','RAG/agents.'),R('official_harvard26','courseoverview','RAG/agenticworkflows.'),R('official_ntu25','topicindex','Posttraining/forgetting/reasoning.'),R('official_ntu26','assignments','Finetuningwithoutforgetting.')],'Currentoriginaltopicpageschecked; noverificationofpastproxyfailures/video-viewingorhistoricaluploaddates isclaimed. Pedagogicalordering/designintentisnotanempiricalmodelresult.'),
 claim('c15','scope','局部机制例子不保证一般收益，设计/未来实作要求与已完成训练各自验收；AI审阅不能只换hash。','呈现/实作原则',[R('checks','212-267','Version/evidence/identitychecks requirecurrenthashes.'),R('pages','review/buildsteps','Publicationgatesincludeindependentreviewcontracts.')],'Instruction/limitationclassification; thisreviewdoesnotcertifyhistoricalotherreviewersreadorrealhumanstudentlearning.')
], '教学策略表按固定原repo亲核，研究方法由原始来源支持；设计要求与有限成品实测分开。')
issues=[{'id':'i1','claim_ids':['s4','a8'],'status':'unresolved','details':'把8,950非JSONL文件全称为素材。immutabletar/manifest逐档核对得到8,335PNG+603WAV=8,938媒体；其余12是来源、授权及provenance说明文件；另12JSONL合计8,962。','suggested_revision':'两页改为12JSONL、8,938媒体与12来源/授权/provenance说明文件，或12JSONL与8,950其他文件。','reported_to_root':True},{'id':'i2','claim_ids':['a2'],'status':'unresolved','details':'指定2026-10-02run和immutableworkflow只有重建/hash/上传。八包现在的cachedLFS实体及全部成员SHA本人已核，但未取得当日新cache、匿名逐包逐档回读的原收据。此处是历史操作证据未核，不是断言操作没有发生。','suggested_revision':'提供可追查原冷cache匿名回读receipt，或把该历史句收敛到原run可证明的固定来源重建、指纹一致及LFS上传。','reported_to_root':True}]
# Supplemental checks read only original runtime metadata, archive headers, and fixed export configs.
supplement = load(BASE / 'supplemental-measurements.json')
repo('supplement', str(BASE / 'supplemental-measurements.json'),
     'Independent archive-header/runtime-metadata/config checks; every original path, SHA, and inspected JSON pointer is recorded.', 'execution')
art('supplement', str(BASE / 'supplemental-measurements.json'), 'execution',
    'Read-only checks of the 30 original experiment runtimes, Fashion parquet row count, FSDD split/sample-rate headers, and v2 expert configuration.',
    '/workspace/tiny-perceptron-vlm/.venv/bin/python docs/technical-reviews/artifacts/p6-public-a/verify_supplement.py',
    '29 original CUDA runs used NVIDIA L4/Torch 2.14.1+cu126; one original CPU run used that Torch build. Fashion parquet has 60,000 rows and pilot has 50; FSDD has 20 records per split, all 60 WAV files are 8 kHz. MoE config uses four experts/top-2.')
art('supplement_script', str(BASE / 'verify_supplement.py'), 'execution_code', 'Reproducible read-only supplemental metadata/header checks.')
art('supplement_stdout', str(BASE / 'verify-supplement.stdout.txt'), 'execution_stdout', 'Actual successful supplemental command output.')
original('gsmreadme', 'gsm8k-original-readme.md',
         'Original dataset details: human problem writers; line 49 names ground-truth contractor-provided solution steps, distinguished from model-generated Socratic subquestions.',
         url='https://raw.githubusercontent.com/openai/grade-school-math/master/README.md')
original('hf_moe_config', '*__moe-joint__model-config.json', 'Fixed export architecture=moe, experts=4, top_k=2.')
original('hf_dense_config', '*__dense-joint__model-config.json', 'Fixed export architecture=dense; actual model chooses the single Dense FFN branch rather than expert routing.')
by_claim = {c['id']: c for p in pages for c in p['claims']}
for e in supplement['course_execution']:
    sid = 'course_runtime_' + e['experiment_id']
    repo(sid, e['path'], 'Only /experiment_id,/revision,/device,/torch_version,/python_version,/gpu,/status were inspected after enumerating top-level keys.', 'original_record')
    by_claim['r7']['evidence'].append({'source_id': sid,
        'locator': ','.join(e['inspected_pointers']),
        'supports': 'Original experiment device/GPU/Torch fields; this is an execution record rather than author result commentary.'})
for cid in ['r7', 'a4', 'c5']:
    by_claim[cid]['artifact_ids'].append('supplement')
by_claim['r7']['scope'] = 'Original 30 course runtime records: 29 CUDA runs on NVIDIA L4/Torch 2.14.1+cu126 and one CPU run. MPS evidence covers bounded CI operations, not the full course or formal training.'
by_claim['a4']['evidence'].extend([
    {'source_id': 'supplement', 'locator': '/pilot_media', 'supports': 'Actual parquet header counts 60,000 source rows; pilot JSONL counts 50. FSDD JSONL counts 20 per split and original WAV headers are all 8 kHz.'},
    {'source_id': 'gsmreadme', 'locator': 'Dataset Details lines 15–22; line 49', 'supports': 'Human-created original GSM8K problems and contractor-provided ground-truth solution steps; model-generated Socratic questions are a separate dataset.'}])
by_claim['c5']['evidence'].extend([
    {'source_id': 'hf_moe_config', 'locator': '/architecture,/experts,/top_k', 'supports': 'The fixed MoE export config has four stored experts and routes top-2.'},
    {'source_id': 'hf_dense_config', 'locator': '/architecture; v2 model FFN branch', 'supports': 'The fixed Dense export chooses one Dense FFN; unused expert-count fields do not instantiate MoE routing.'}])
# Source snapshots are preserved; old pedagogy reviews and author result-commentary were not read.
report={'schema_version':1,'schema_name':'public-pages-factual-review-v1','review_stage':'technical','review_round':'phase6-fresh-public-a','reviewer_task':'/root/p6_fact_public_a','reviewer_context':'fresh','reviewed_at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'verdict':'revise','source_files':{p['source']:p['source_sha256'] for p in pages},'figure_sha256':{k:v for p in pages for k,v in p['figure_sha256'].items()},'pages':pages,'sources':sources,'artifacts':artifacts,'issues':issues,'independence':{'old_reader_or_technical_report_bodies_read':False,'author_extra_result_notes_read':False,'input_procedure':'Fullcurrentsevenpages; officialoriginalsourcesandpinnedrepos; rawJSONtopkeys before namedmeasurement/method/provenancepointers; excludednotes/review/scope_correction. Originaldatasetlicense/notices readaslegal/methodprovenance, notpriorreviewanswers.','no_delegation_by_reviewer':True},'execution_boundary':{'installed_packages':False,'uploads':False,'paid_compute':False,'full_training':False,'model_generation':False,'new_holdout_answer_grading':False,'performed':'Hash/count reaggregation, meta-only architectureparametercount, existingasset/sitecontracttests, environmentcheck,source/Notebookcheck, one randomtinyCLIforward/backwarddryrun, systemChromiumSVG rendering.'},'method_sources':['docs/review-tools/factual-reviewer-instructions.md','docs/technical-review-guide.md'],'tool_adaptations':[{'event':'Firstcheckassumedallarchivepathscontainedmaterializedpayloads;baselinefilesareLFSpointers.','correction':'Preservedfirstattemptstderr/code; thenverifiedpointeridentityandusedexistinggit-common-dirLFSobjects withoutnetworkfetch/hydration.','artifact_paths':[str(BASE/'verify-public-first-attempt.stderr.txt'),str(BASE/'verify_public_evidence-first-attempt.py')]},{'event':'BundledPlaywrightbrowsernotavailable.','correction':'Usedalreadyinstalled/usr/bin/chromium; noinstallation. Fourrealrenderingspersonallyviewed.'}],'reinspection':{'status':'pending','reason':'Coordinatorrequestedcompleteinitialreviseandwillpreserveopaquehistorybeforerevising; thisreportdoesnotpre-markfixedclaimsorupdatehashes.'},'checks':{'factual_accuracy':{'status':'revise','details':'Twofileclassificationclaimscontradicted; onehistoricalreadbackclaimunresolved.'},'numeric_verification':{'status':'revise','details':'Allcount/hash/shapecheckscompleted;8,950mediawordingcontradicted.'},'figure_consistency':{'status':'pass','details':'BothSVGsrendered640/360andpersonallyviewed.'},'source_verification':{'status':'revise','details':'Originalofficial/pinnedreposchecked;historicalanonymouscoldcacheoriginalreceiptmissing.'},'limitations':{'status':'pass','details':'Concepts,operatingcontracts,originalproductionmeasurementsanddesign/futureworkdistinguishedperclaim.'}}}
Path('docs/technical-reviews/public-pages-p6-a.json').write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n')
print(json.dumps({'pages':len(pages),'claims':sum(len(p['claims']) for p in pages),'sources':len(sources),'artifacts':len(artifacts),'verdict':report['verdict'],'page_verdicts':{p['source']:p['verdict'] for p in pages}},ensure_ascii=False))
