"""Write this independent review from its personally inspected evidence."""
import hashlib
import importlib.util
import json
from pathlib import Path

OUT = Path(__file__).resolve().parent
ROOT = OUT.parents[3]
PREFIX = OUT.relative_to(ROOT).as_posix()
def sha(p):
    return hashlib.sha256(p.read_bytes()).hexdigest()
def rel(p):
    return p.relative_to(ROOT).as_posix()
def dump(p, v):
    p.write_text(json.dumps(v, ensure_ascii=False, indent=2) + "\n")

spec = importlib.util.spec_from_file_location("section_facts", ROOT / "docs/review-tools/section_facts.py")
module = importlib.util.module_from_spec(spec)
spec.loader.exec_module(module)
section, _, first_line = module.original_section(ROOT / "course/chapters/06.md", "6.9")
assert section == (OUT / "original-run/section.md").read_bytes()
for path, lesson in (("course/chapters/06.md", "6.3"), ("course/training.md", "T.4")):
    raw, _, _ = module.original_section(ROOT / path, lesson)
    (OUT / "inputs" / f"prerequisite-{lesson}.md").write_bytes(raw)

bounded = json.loads((OUT / "bounded-result.json").read_text())
provenance = json.loads((OUT / "provenance.json").read_text())
assert all(item["matches"] for item in provenance["historical_code"] + provenance["original_artifacts"])
assert all(item.get("status") == 200 for item in provenance["sources"])
env = {"python": "3.13.5", "tokenizers": "0.23.2", "torch": "2.14.1+cpu", "device": "CPU; CUDA_VISIBLE_DEVICES=''", "cwd": str(ROOT)}
commands = {
    "original": ".venv/bin/python docs/review-tools/section_facts.py course/chapters/06.md#6.9 --execute --timeout 30 --output /tmp/phase4-6_9-independent-original",
    "prepare": f".venv/bin/python {PREFIX}/prepare_evidence.py > {PREFIX}/prepare-stdout.jsonl 2> {PREFIX}/prepare-stderr.txt",
    "bounded": f"CUDA_VISIBLE_DEVICES='' HF_HUB_OFFLINE=1 HF_DATASETS_OFFLINE=1 TRANSFORMERS_OFFLINE=1 OMP_NUM_THREADS=1 MKL_NUM_THREADS=1 PYTHONDONTWRITEBYTECODE=1 .venv/bin/python {PREFIX}/bounded_check.py > {PREFIX}/bounded-stdout.json 2> {PREFIX}/bounded-stderr.txt",
    "report": f".venv/bin/python {PREFIX}/build_report.py",
    "checker": ".venv/bin/python scripts/check_technical_reviews.py --lesson 6.9",
}
dump(OUT / "commands.json", {"shell": "bash", "login": False, "cwd": str(ROOT), "commands": commands, "original_exit_code": 0, "prepare_exit_code": 0, "bounded_exit_code": 0, "scope": "Only the original tokenizer fence and short tokenizer/decoder/input checks; no linked training shell command was executed."})

artifacts = []
artifact_ids = {}
for p in sorted(OUT.rglob("*")):
    if not p.is_file() or p.name.startswith("checker-") or p.name in ("manifest.json", "report-summary.json"):
        continue
    key = p.relative_to(OUT).as_posix()
    identifier = "A-" + str(len(artifacts) + 1).zfill(3)
    artifact_ids[key] = identifier
    if key in ("original-run/stdout.txt", "original-run/execution.json"):
        artifact = {"kind": "execution", "command": commands["original"], "result": "exit 0; original fence printed 整段 [8] 分段後相接 [6, 7]; assert passed", "environment": env}
    elif key in ("bounded-result.json", "bounded-stdout.json"):
        artifact = {"kind": "execution", "command": commands["bounded"], "result": "exit 0; exact exercise, 4 interior cuts, 12 safe Whitespace cuts, UTF8 incremental state, ByteLevel roundtrip, iterator boundary, original artifact/source audits all passed", "environment": env}
    elif key == "prepare-stdout.jsonl":
        artifact = {"kind": "execution", "command": commands["prepare"], "result": "exit 0; eight pinned official sources fetched via verified HTTPS; three historical code and six original tokenizer/data hashes match", "environment": env}
    elif p.suffix in (".py", ".rs") and not key.startswith("sources/"):
        artifact = {"kind": "code"}
    else:
        artifact = {"kind": "source_snapshot"}
    purpose = "Frozen original bytes or personally acquired primary-source evidence"
    if key == "bounded_check.py": purpose = "Actual bounded CPU verification source; all assertions and original-input audit are reproducible"
    elif key == "prepare_evidence.py": purpose = "Actual primary-source acquisition, original input copying and historical git/hash verification code"
    elif key == "build_report.py": purpose = "This report's evidence registration and claim construction source"
    elif key == "provenance.json": purpose = "Original paths, authoritative HTTPS URLs, dates, revisions, hashes and acquisition results"
    elif key == "commands.json": purpose = "Exact commands and shell/cwd/device scope"
    elif key.startswith("inputs/original-sources/"): purpose = "Original existing source records; matching the 192 saved prefixes, without creating training input"
    artifact.update(id=identifier, path=rel(p), sha256=sha(p), description=f"{key}: {purpose}")
    artifacts.append(artifact)

def aid(key): return artifact_ids[key]
sources = []
primary = {
    "S-whitespace": ("hf-whitespace.rs", "Hugging Face tokenizers Whitespace and WhitespaceSplit", "v0.23.2", "Whitespace.pre_tokenize lines 20–28; source tests lines 48–87 personally read. Whitespace matches \\w+|[^\\w\\s]+ and removes whitespace; it also separates punctuation, unlike WhitespaceSplit."),
    "S-bytelevel": ("hf-byte_level.rs", "Hugging Face tokenizers ByteLevel pretokenizer and decoder", "v0.23.2", "Regex lines 40–47, ByteLevel options/alphabet lines 51–110, pre_tokenize lines 116–151 and decode_chain lines 153–171 personally read; regex includes optional preceding space and terminal whitespace lookahead, add_prefix_space is configurable, decoder assembles bytes before UTF8 conversion."),
    "S-bpe-model": ("hf-bpe-model.rs", "Hugging Face tokenizers BPE model", "v0.23.2", "merge_word lines 465–550 personally read: start symbols and optional unknown fallback are gathered before merge_all; tokenize lines 597–611 and cache semantics inspected. Cache memoizes complete inputs, it does not concatenate earlier encode input."),
    "S-bpe-trainer": ("hf-bpe-trainer.rs", "Hugging Face tokenizers BPE trainer", "v0.23.2", "do_train lines 455–550 and feed lines 646–674 personally read: special symbols, alphabet, within-word pair counts, merge queue, vocab-size limit and per-sequence preprocessing counts."),
    "S-tokenizer": ("hf-tokenizer.rs", "Hugging Face tokenizers model and tokenizer pipeline", "v0.23.2", "Model.tokenize_in_pretokenized lines 67–120, encode_single_sequence lines 761–792, encode lines 871–890, do_tokenize lines 1178–1200 and train lines 1492–1538 personally read: each encode independently preprocesses its sequence, BPE operates on each pretoken, training iterator strings are separate sequences."),
    "S-python-api": ("hf-python-tokenizer.rs", "Hugging Face tokenizers Python bindings", "v0.23.2", "Tokenizer.encode signature/return around lines 1182 onward; train_from_iterator doc/signature and iterator flattening lines 1765–1818 personally read; the iterable supplies sequences or batches of sequences, not a UTF8/BPE stream context."),
    "S-codecs": ("python-codecs.rst", "CPython codecs official library documentation", "v3.13.5", "Incremental Encoding and Decoding lines 564–579, IncrementalDecoder.decode/getstate lines 641–698 and replace_errors lines 469–475 personally read. Joined incremental output equals one-shot decode, undecoded bytes are part of state, final=True flushes, decoding replacement uses U+FFFD."),
    "S-io": ("python-io.rst", "CPython io official library documentation", "v3.13.5", "TextIOBase.encoding/errors/buffer lines 869–890, TextIOBase.read lines 908–914, TextIOWrapper lines 949–982 personally read. Text read size counts characters; binary I/O produces bytes and TextIOWrapper handles encoding/error/newline translation."),
}
for identifier, (name, title, version, note) in primary.items():
    item = next(s for s in provenance["sources"] if s["snapshot"].endswith("/" + name))
    sources.append({"id": identifier, "kind": "official_source", "title": title, "url": item["url"], "version": version, "accessed_on": "2026-10-05", "authority_reason": "Official upstream repository's release-tag source/documentation, inspected directly; no search summary or prior review used.", "verified": True, "checked_original": True, "inspection_note": note, "snapshot_artifact_id": aid("sources/" + name)})
for identifier, key, version, note in (
    ("S-course-recipe", "inputs/historical/scripts/course_experiments/text.py", "a253d1262bf5f361f9ac4e19232ae752f0ecc7a3", "Personally read lines 348–451 and run_tokenizer through its return. _utf8_prefix intentionally crops the document at at most 256 bytes and drops only an incomplete final codepoint; complete documents split before crop, tokenizer fits on train record strings, added-token parsing removed for content. This is an explicit excerpt recipe, not arbitrary streaming read chunks."),
    ("S-course-records", "inputs/historical/scripts/course_experiments/common.py", "a253d1262bf5f361f9ac4e19232ae752f0ecc7a3", "Personally read text_examples lines 77–98: each record gets [BOS]+encode(text)+[EOS] before token-ID training windows are formed. Those windows split an already encoded record rather than re-encoding I/O chunks."),
    ("S-saved-tokenizer", "inputs/current/tiny_perceptron/tokenization.py", provenance["current_git_head"], "Personally read ByteLevelBPE.__init__/encode/decode: requires full 256-byte alphabet, normalizer=None and add_prefix_space=False; ordinary text disables special added-token parsing; decode filters only role IDs before ByteLevel decoder."),
):
    p = OUT / key
    sources.append({"id": identifier, "kind": "repository_code", "title": key, "path": rel(p), "sha256": sha(p), "version": version, "verified": True, "inspection_note": note})
sources.extend([
    {"id": "S-original-run", "kind": "execution", "title": "Original 6.9 fence executed unchanged", "verified": True, "artifact_id": aid("original-run/stdout.txt")},
    {"id": "S-bounded", "kind": "execution", "title": "Bounded CPU decoder, tokenizer boundary and original-input verification", "verified": True, "artifact_id": aid("bounded-result.json")},
    {"id": "S-derivation", "kind": "derivation", "title": "Counts and composition contracts personally derived", "verified": True, "details": "A single hello pretoken has four initial letters h,e,l,o and four merges to reach hello (5 positions because l repeats); with [UNK] the resulting vocab has 9 items, below requested cap 20. Whole hello is one ID; independently encoding two nonempty known-letter strings hel/lo gives at least two IDs. 貓 is 3 UTF8 bytes, 🙂 is 4, hello hello is 11 ASCII bytes: 18 bytes total. Whitespace drops the separating blank; two complete hello pretokens yield [8,8]. No ratio, tensor axis or model quality metric is claimed in 6.9."},
])
def evidence(source, locator, supports): return {"source_id": source, "locator": locator, "supports": supports}
claims = [
    {"id": "C1-chunk-is-not-boundary", "kind": "concept", "statement": "讀檔分塊不自動代表詞或文件邊界；同文件任意 chunk 分別編碼後相接可能和完整文件編碼不同。", "location": "section lines 3, 24–26", "scope": "General distinction between storage chunks and a chosen tokenizer/document contract; no guarantee that every split changes IDs or that chunk IDs are always longer.", "status": "verified", "evidence": [evidence("S-tokenizer", "encode_single_sequence 761–792; encode 871–890; Model 67–120", "Each encode operates on the supplied sequence and models tokenize each pretoken; storage boundaries are not recovered automatically."), evidence("S-bpe-model", "merge_word 465–550", "BPE merges adjacent symbols only within the provided sequence/pretoken, so an independently committed split can remove merge opportunities."), evidence("S-bounded", "original_example; interior_cuts; exercise", "A word-internal split differs, while the stated Whitespace exercise agrees.")], "artifact_ids": [aid("bounded-result.json")]},
    {"id": "C2-example-and-api", "kind": "software", "statement": "Tokenizer(models.BPE(unk_token='[UNK]'))、Whitespace、BpeTrainer(vocab_size=20,special_tokens=['[UNK]'])、train_from_iterator、encode(...).ids 可執行本節示範；訓練的是切分規則，沒有語言模型更新。", "location": "section lines 5, 8–19, 22", "scope": "Installed tokenizers 0.23.2, Python 3.13.5, exact original code. [UNK] is an explicit vocabulary item for unseen base symbols; the English alphabet is not full byte coverage.", "status": "verified", "evidence": [evidence("S-python-api", "train_from_iterator 1765–1818; encode signature around 1182", "Iterator strings and trainer arguments are valid APIs and encode produces an Encoding exposing IDs."), evidence("S-bpe-trainer", "do_train 455–550; feed 646–674", "The trainer learns a vocabulary and within-pretoken pair merges, starts with special symbols and treats vocab_size as an upper stopping budget."), evidence("S-original-run", "stdout and execution.json exit_code", "Exact fence executed without change and original assertion passed.")], "artifact_ids": [aid("original-run/stdout.txt"), aid("original-run/execution.json"), aid("bounded-result.json")], "verification": {"method": "executed", "expected": "Original code runs and whole != chunks; reserved unknown item exists; no model training call.", "observed": "exit 0; whole=[8], chunks=[6,7]; [UNK] ID 0, actual vocab 9 under requested cap 20.", "details": "section_facts executed original bytes in the CPU/offline helper; bounded script additionally verifies unknown IDs and learned vocabulary. show_progress=False is presentation only."}},
    {"id": "C3-numeric-example", "kind": "numeric", "statement": "此固定範例 whole 是一個 ID，hel/lo 各自編碼後相接至少兩項、較長且 ID 序列不同；精確編號只屬本份詞表。", "location": "section lines 16–19, 22", "scope": "This fixed no-dropout toy tokenizer and known nonempty substrings. Not a universal length ordering across all BPE tokenizers, arbitrary inputs or splits.", "status": "verified", "evidence": [evidence("S-bpe-trainer", "do_train pair queue and vocabulary stop 505–550", "Repeated hello provides pairs and sufficient vocabulary budget to learn a complete hello symbol."), evidence("S-derivation", "Count derivation", "The claimed comparison counts ID-list entries, not Unicode characters or UTF8 bytes."), evidence("S-original-run", "stdout", "Observed one whole ID [8] and two chunk IDs [6,7].")], "artifact_ids": [aid("original-run/stdout.txt"), aid("bounded-result.json")], "verification": {"method": "executed", "expected": "len(whole)=1, len(chunks)>=2, whole!=chunks", "observed": "1 versus 2; [8] versus [6,7]. Four other internal cuts also differ.", "details": "Counted list entries directly; all original IDs belong to the same trained tokenizer. No tensor axes or denominator are implicit.", "tolerance": "Exact integer and list equality; no numerical tolerance."}},
    {"id": "C4-whitespace-exercise", "kind": "software", "statement": "本節 Whitespace 規則下，hello hello 一次編碼等於 hello 加尾空白與 hello 分別編碼後相接；改回 hel/lo 又不同。", "location": "section lines 22, 28", "scope": "The specified Whitespace instance without normalization or postprocessing. Whitespace also splits punctuation; the text's statement that it splits at blanks is true for its all-letter example, not an exhaustive regex definition.", "status": "verified", "evidence": [evidence("S-whitespace", "pre_tokenize 20–28; official test basic 48–87", "Whitespace separates word/nonword matches and removes whitespace, leaving two complete hello pretokens."), evidence("S-bounded", "exercise; interior_cuts; pretokenizer_space_rules", "Exercise returns [8,8] on both paths; internal cut produces [6,7].")], "artifact_ids": [aid("bounded-result.json")], "verification": {"method": "executed", "expected": "The stated whitespace exercise agrees, word-internal hel/lo differs.", "observed": "[8,8] == [8,8]; [8] != [6,7].", "details": "Ran the exact proposed exercise and also all four internal hello cuts. Equality concerns ID sequence; Whitespace decode is not a general exact text roundtrip because whitespace is discarded."}},
    {"id": "C5-stream-and-record-contract", "kind": "concept", "statement": "同文件應按完整文件編碼，或保留尾段上下文並確認 tokenizer 安全邊界再提交；不同文件應明確保留其邊界，不為縮短而跨文件合併。", "location": "section lines 24–26", "scope": "Contract recommendation for a pipeline that treats records as distinct documents. It neither asserts HF encode preserves streaming state, nor specifies a universal fixed tail length, nor mandates a global BOS/EOS convention for every model. Boundary representation must match the chosen model/recipe.", "status": "verified", "evidence": [evidence("S-tokenizer", "Model 67–120; train 1492–1538", "Tokenizer pretoken boundaries govern merge independence, while iterator elements are explicitly separate sequences; arbitrary chunks are not concatenated automatically."), evidence("S-bytelevel", "regex 40–47; pre_tokenize 116–151", "Whether a tail is safe depends on the complete pretokenizer rule, including space attachment and lookahead."), evidence("S-course-records", "text_examples 77–98", "Actual course recipe inserts BOS/EOS per record before slicing already-encoded token windows, preserving record boundaries without re-encoding raw I/O chunks."), evidence("S-bounded", "safe_whitespace_stream; training_iterator_boundaries", "Retaining an incomplete word works on all 12 cut positions of this exact exercise; training separate hel/lo iterator entries never learns hello.")], "artifact_ids": [aid("bounded-result.json"), aid("inputs/historical/scripts/course_experiments/common.py")]},
    {"id": "C6-space-rules-and-roundtrip", "kind": "concept", "statement": "Whitespace 與 byte-level 的空白規則不同；byte-level 的整段與拆段還原相同也不保證 ID 序列或長度相同。", "location": "section lines 22, 26, 28 and referenced 6.3", "scope": "Whitespace uses its regex and discards separators. HF ByteLevel(add_prefix_space=False) with regex preserves bytes and may attach a blank to the next word. The second clause is a verification of the first's practical boundary contract, not an extra claim attributed to the text.", "status": "verified", "evidence": [evidence("S-whitespace", "20–28", "Whitespace removes blanks from the model input."), evidence("S-bytelevel", "40–47; 116–171", "ByteLevel uses optional leading-space regex matching and reconstructs bytes through its decoder."), evidence("S-bounded", "pretokenizer_space_rules; roundtrip_limitations", "ByteLevel whole=[259,260], chunks=[259,220,259] differ, but both decode to hello hello; Whitespace chunk decode is hel lo and unknown symbols are lossy.")], "artifact_ids": [aid("bounded-result.json")]},
    {"id": "C7-utf8-separate-state", "kind": "concept", "statement": "binary 讀取切到多 byte 字中間時，須保留未完成 bytes 到下一塊；先用 replacement character 會改變內容。解碼與 tokenizer 兩層邊界都要守住。", "location": "section lines 5, 26", "scope": "Valid UTF8 input read as byte chunks. TextIOWrapper.read(size) already returns characters; it does not require users to buffer half characters, but text chunks can still bisect a tokenizer pretoken. Incremental UTF8 state does not provide regex/BPE context.", "status": "verified", "evidence": [evidence("S-codecs", "564–579; IncrementalDecoder.decode/getstate 641–698; replace_errors 469–475", "Incremental decoder keeps unfinished byte input and joined output matches one-shot decoding; replace substitutes U+FFFD on invalid/incomplete stateless byte sequences."), evidence("S-io", "TextIOBase.read 908–914; TextIOWrapper 949–982", "Text read counts characters and wrapper handles underlying encoding; the half-character risk concerns raw bytes."), evidence("S-bounded", "utf8_decoder_and_tokenizer_states", "One-byte incremental reads preserve 貓🙂hello hello; stateless replacements corrupt its first seven bytes; per-decoded-piece BPE IDs still differ despite exact text reconstruction.")], "artifact_ids": [aid("bounded-result.json")]},
    {"id": "C8-recipe-scope", "kind": "software", "statement": "本節是短 tokenizer 示範，讀例子無須先完成訓練配方；簡化英文表與 6.3 的完整 byte-level 規則不同。", "location": "section lines 22, 33; referenced 6.3 and T.4", "scope": "Personally checked standalone execution plus immutable existing original measurement provenance. tokenizer.json's model results cover 6.3–6.7 and are not measurements of 6.9 streaming correctness. Existing excerpt preparation is intentional document prefix cropping, not an assertion of complete-document I/O streaming.", "status": "verified", "evidence": [evidence("S-original-run", "execution.json and environment.json", "Original fence succeeds with its local toy tokenizer only and does not load model weights or any training dataset."), evidence("S-course-recipe", "_utf8_prefix 376–377; run_tokenizer 409–451", "The fixed recipe is separate: document split first, one prefix per document, full byte alphabet, train-only tokenizer fit, then model training."), evidence("S-saved-tokenizer", "ByteLevelBPE.__init__/encode/decode", "The saved full-byte tokenizer carries a distinct contract from this UNK-based Whitespace example."), evidence("S-bounded", "original_measurement_audit", "Original code hashes and six tokenizer/data hashes match tokenizer.json; all 192 saved prefixes match original source records; saved roundtrip IDs and validation content lengths reproduce exactly.")], "artifact_ids": [aid("bounded-result.json"), aid("provenance.json"), aid("inputs/current/docs/course-experiments/results/tokenizer.json")], "verification": {"method": "executed", "expected": "Original 6.9 example needs no long recipe. Existing original tokenizer/data identities agree with their saved provenance and remain a separate experiment.", "observed": "Original CPU fence exit 0; code SHA checks 3/3 and saved artifact SHA checks 6/6; source prefixes 192/192; records 153/19/20 and no family overlaps; tokenizer hash ec08c61e…; exact saved roundtrips reproduced.", "details": "Only loaded tokenizer JSON and existing text inputs. No neural model, weights, evaluation generation, optimizer steps, data preparation, downloads of datasets/models, or GPU work were run. Original model scores were not newly measured or used to infer streaming correctness."}},
]

report = {"schema_version": 1, "review_stage": "technical", "lesson_id": "6.9", "source": "course/chapters/06.md#6.9", "source_sha256": hashlib.sha256(section).hexdigest(), "verdict": "pass", "reviewer_task": "/root/phase4_factual_coordinator/factual_6_9", "reviewer_context": "fresh", "author_tasks": [], "figure_sha256": {}, "artifacts": artifacts, "sources": sources, "claims": claims, "issues": [], "checks": {"factual_accuracy": {"status": "pass", "claim_ids": [c["id"] for c in claims], "details": "親讀目前 6.9 全節、原 Python fence、必要的 6.3、T.4 與原/歷史 helper；逐項核對 HF v0.23.2 和 CPython v3.13.5 原文件/原碼。未讀任何舊技術或讀者報告正文/判定。本節提的是明確契約下的分段差異，沒有宣稱每次切分均改變 ID 或任何有限尾段對所有 tokenizer 安全。"}, "numeric_verification": {"status": "pass", "claim_ids": ["C3-numeric-example"], "details": "親數 hello 整段 ID 1 項、hel/lo 合共 2 項；練習兩邊 2 項且完全同序列。參數 20 是詞表目標預算而非實際項數，本例實際 9。IDs 是一維序列，長度單位是 token/ID 項數，非字數/bytes；無均值、比率、tensor 軸或圖中分母。額外 UTF8 檢查為 3+4+11=18 bytes，不作教材模型成績。"}, "figure_consistency": {"status": "not_applicable", "claim_ids": [], "details": "親讀 raw section bytes 和 helper extraction：svg_references=[]、figure_sha256={}，正文沒有 Markdown/HTML 圖引用、數字圖、軸或素材。無圖可 render/view；不是章首導言 NA，本節實質程式與概念已逐項核對。"}, "source_verification": {"status": "pass", "claim_ids": [c["id"] for c in claims], "details": "8 份官方 tag snapshot 親讀，記 HTTPS URL、v0.23.2/v3.13.5、2026-10-05、定位、實際支持範圍與 SHA；原 tokenizer result SHA=4da2ceb4…，git revision a253d126… 的3份原 code SHA 與原結果相符，6份 saved tokenizer/data SHA相符，192份 prefix 回查原來源。所有 formal artifact 位於 docs/technical-reviews/artifacts/phase4-6_9-independent，ignored outputs 不是唯一或 required artifact。"}, "limitations": {"status": "pass", "claim_ids": ["C1-chunk-is-not-boundary", "C4-whitespace-exercise", "C5-stream-and-record-contract", "C6-space-rules-and-roundtrip", "C7-utf8-separate-state", "C8-recipe-scope"], "details": "明確區分 I/O byte chunks、UTF8 增量解碼狀態、pretokenizer/regex/BPE 尾段及文件/record 界線。Whitespace 有 unknown/空白丟失，不宣稱完整 roundtrip；ByteLevel roundtrip 相同仍可 ID/長度不同。安全提交只可按完整工具規則證明，本節未實作通用 streaming tokenizer。原配方先按完整文件分側再選 prefix，非 arbitrary chunk stream。沒有重訓、模型推論、GPU 或新資料/模型下載；不執行 linked 長 shell 配方。"}}, "read_scope": {"primary": "6.9 original UTF8 bytes, lines 1–35 of saved section; original repository start line " + str(first_line), "necessary_prerequisites": ["6.3 full section", "T.4 full section (contracts only; shell recipes not executed)", "original/historical text.py relevant tokenizer functions", "historical common.py text_examples", "current data.py ByteTokenizer and tokenization.py ByteLevelBPE"], "chapter_intro": {"applicable": False, "reason": "Not the first numbered section of chapter; 6.9 has its own substantive code and claims."}, "prior_reviews_read": False}, "environment_setup": {"skill": "cloud-environment-onboarding:setup", "skill_package": "c0/setup", "configuration_changes": "none required", "verified_workflow": "Existing .venv Python 3.13.5, torch 2.14.1+cpu and tokenizers 0.23.2 support this original fence and bounded review workflow."}}
dump(ROOT / "docs/technical-reviews/6.9.json", report)
dump(OUT / "manifest.json", {"files": [{"path": a["path"], "sha256": a["sha256"]} for a in artifacts], "report": {"path": "docs/technical-reviews/6.9.json", "sha256": sha(ROOT / "docs/technical-reviews/6.9.json")}, "source_sha256": report["source_sha256"], "claims": len(claims), "scope": "New independent review; no content or figures edited, no commit made."})
print(json.dumps({"verdict": report["verdict"], "claims": len(claims), "artifacts": len(artifacts), "source_sha256": report["source_sha256"], "report_sha256": sha(ROOT / "docs/technical-reviews/6.9.json")}, ensure_ascii=False))
