from pathlib import Path
import ast,hashlib,json,re,sys,subprocess
OUT=Path(__file__).parent; ROOT=OUT.parents[3]
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
# Capture actual extraction/version facts without reading any existing canonical report.
raw=(ROOT/'course/training.md').read_bytes();matches=list(re.finditer(rb'(?m)^## [^\r\n]+',raw));n=next(i for i,m in enumerate(matches) if m.group().startswith(b'## T.11 '));end=matches[n+1].start() if n+1<len(matches) else len(raw);body=raw[matches[n].start():end]
assert body==(OUT/'section.md').read_bytes()
(OUT/'context/training-current-at-scope.md').write_bytes(raw)
loader=ast.parse((ROOT/'tiny_perceptron/natural_assistant.py').read_text()); calls={}
for name in ['load_core','load_asr']:
 node=next(n for n in loader.body if isinstance(n,ast.FunctionDef) and n.name==name)
 calls[name]=[ast.unparse(n.func) for n in ast.walk(node) if isinstance(n,ast.Call) and isinstance(n.func,ast.Attribute) and n.func.attr=='from_pretrained']
assert set(calls['load_core'])=={'AutoProcessor.from_pretrained','Qwen3VLForConditionalGeneration.from_pretrained','PeftModel.from_pretrained'}
assert set(calls['load_asr'])=={'WhisperProcessor.from_pretrained','WhisperForConditionalGeneration.from_pretrained'}
read_ranges={'course/training.md':['T.11 complete raw UTF-8 section; T.9 complete earlier snapshot and complete current targeted reread; T.10 complete necessary context'],'course/chapters/19.md':['19.4 complete section; 19.7 complete section'],'course/chapters/20.md':['20.1 complete section'],'instructions':['docs/review-tools/factual-reviewer-instructions.md complete','scripts/check_technical_reviews.py complete schema','docs/review-tools/section_facts.py complete','docs/review-tools/check_review_round.py complete','.agents/skills/clear-tutorial/references/review-protocol.md complete'],'implementation':['Exact functions/ranges saved in code-inspection.txt, additional-code-inspection.txt, calculation-code-inspection.txt, stage-contract-inspection.txt; applications.run_rag 335-404, run_tools 608-636; model.py 1-53; applications._TOOLS_SYSTEM AST ordinary protocol literal'],'raw_data':['Top keys/types first, then only pointers preserved in raw-pointer-shapes-and-provenance.json, raw-nested-shapes.json and named-original-leaves.json; recomputation accesses saved sample metric/truth/trace leaves only; no recursive raw display'],'history_index':['Only README Markdown result-link destinations via regular expression; no README prose displayed/read'],'external':['Official original pages/snippets in original-source-inspection.json; upstream Qwen initial main bytes personally checked against pinned commit bytes']}
facts={'source':'course/training.md#T.11','source_sha256':hashlib.sha256(body).hexdigest(),'section_first_line':raw[:matches[n].start()].count(b'\n')+1,'current_whole_file_sha256_at_final_scope':hashlib.sha256(raw).hexdigest(),'current_whole_observed_snapshot':'context/training-current-at-scope.md','frozen_initial_whole_file_snapshot':'frozen/course/training.md','frozen_initial_whole_file_sha256':sha(OUT/'frozen/course/training.md'),'initial_whole_is_historical_named_input':True,'actual_read_scope':read_ranges,'original_fences':0,'original_figures':0,'figure_not_applicable_reason':'T.11 consists of a record-fields table, stated integer/fraction example, and prose hyperlinks. It has no image reference, spatial mapping or hidden material needed for its record comparison. The paired-question logic is explicit in text.','context_figures_personally_viewed':['context/19.7-render.png: downward request->program execution->returned result->same-core final generation; return 3 is distinct from model answer','context/20.1-render.png: typing/transcription/photos merge to pretrained Qwen; Whisper produces transcript, no LoRA shown'],'pretrained_loader_ast_checks':calls,'fresh_reviewer_task':'/root/phase4_factual_coordinator/factual_t_11','old_reports_read':False,'canonical_old_report_read':False,'extra_author_results_or_correction_answers_read':False,'method_literals_classification':'The displayed evaluate note, quantize note, capstone scope/limitation and automatic selection criterion describe scoring/provenance/method restrictions; none was used as an empirical verdict. Automatic selection raw candidate leaves were inspected as original machine record.','training_or_mature_model_execution':False,'check_scope':'Only T.11; dependencies used to establish its record/provenance contract, not to issue their separate verdicts.'}
(OUT/'actual-scope-and-version.json').write_text(json.dumps(facts,ensure_ascii=False,indent=2)+'\n')
# Numbered official excerpts retain exact extracted lines personally inspected.
selected={'neurips-checklist.html.txt':[(89,96),(102,119),(130,133),(144,153)],'python313-hashlib.html.txt':[(60,67),(171,178)],'git-2.48.1-commit.txt':[(20,25)],'sklearn-1.7.2-cross-validation.rst':[(9,20),(59,72)],'openai-function-calling.html.txt':[(763,785)],'whisper-readme.md':[(1,15)],'qwen3vl-pinned-readme.md':[(16,24)]}
records=[]
for name,ranges in selected.items():
 p=OUT/'official'/name;lines=p.read_text().splitlines();parts=[]
 for a,b in ranges:
  part='\n'.join(f'{i+1}: {lines[i]}' for i in range(a-1,min(b,len(lines))));parts.append(part)
 target=OUT/'official'/(name+'.inspected-excerpts.txt');target.write_text('\n\n'.join(parts)+'\n')
 records.append({'source_file':'official/'+name,'source_sha256':sha(p),'inspected_ranges':ranges,'excerpt':'official/'+target.name,'excerpt_sha256':sha(target)})
(OUT/'original-source-inspection.json').write_text(json.dumps(records,indent=2)+'\n')
# Own observed failure history; no invented rerun or revise event.
history=OUT/'history';history.mkdir(exist_ok=True)
failures=[{'order':1,'tool_chunk':'01bb90','command':'convert -background white course/figures/rewrite-19-tool-roundtrip.svg .../context/19.7-render.png; same for rewrite-20-input-routes.svg','exit_code':1,'observed_stderr_excerpt':"convert: delegate failed `'rsvg-convert' --dpi-x %x --dpi-y %y -o '%o' '%i'' @ error/delegate.c/InvokeDelegate/1919.",'classification':'Missing SVG renderer dependency; not source error.'},{'order':2,'tool_chunk':'18dc18','command':'convert -background white MSVG:course/figures/rewrite-19-tool-roundtrip.svg PNG:.../context/19.7-render.png; same for rewrite-20-input-routes.svg','exit_code':1,'observed_stderr_excerpt':'Same missing rsvg-convert delegate even with MSVG input prefix.','resolution':'Installed CairoSVG 2.9.1 and dependencies into isolated /tmp/phase4-t11-svg; rendered in .venv Python and viewed both PNGs.'},{'order':3,'tool_chunk':'7f8c0e','command':'Inline raw-final-shapes inspector selected /results/samples/0/trace/1 in tools.json','exit_code':1,'observed_stderr_excerpt':'IndexError: list index out of range','classification':'Sample zero is direct copy and has one trace event; no assumption about tool execution allowed.','resolution':'verify_t11.py selects first actually executed trace by executed=True; original example is samples/1 with two events. Own failure retained.'}]
(history/'observed-local-failures.json').write_text(json.dumps(failures,ensure_ascii=False,indent=2)+'\n')
commands={'working_directory':str(ROOT),'shell':'bash login:false','verification_command':'.venv/bin/python docs/technical-reviews/artifacts/phase4-t11-factual-independent-20261005/verify_t11.py > docs/technical-reviews/artifacts/phase4-t11-factual-independent-20261005/verify-stdout.txt 2> docs/technical-reviews/artifacts/phase4-t11-factual-independent-20261005/verify-stderr.txt','source_capture':'section_facts.py extraction to /tmp/phase4-t11-own-extraction-20261005 followed by original-byte copies to this permanent directory','official_download':'fetch_originals.py; qwen original commit API sha-only lookup and exact pinned README byte comparison','render_command':'.venv/bin/python with sys.path.insert(0, /tmp/phase4-t11-svg), cairosvg.svg2png(url=source, write_to=permanent_png)','installation_command':'uv pip install --python .venv/bin/python --target /tmp/phase4-t11-svg cairosvg','cli_commands':'cli-commands-and-results.json contains exact argv and original stdout/stderr for all three bounded commands; temporary fixture paths removed','final_scope_command':'.venv/bin/python docs/technical-reviews/artifacts/phase4-t11-factual-independent-20261005/final_scope_and_sources.py'}
(OUT/'commands.json').write_text(json.dumps(commands,indent=2)+'\n');print(json.dumps({'source_sha256':facts['source_sha256'],'frozen_whole_sha256':facts['frozen_initial_whole_file_sha256'],'current_whole_at_scope':facts['current_whole_file_sha256_at_final_scope'],'checks':'Original T.11 bytes unchanged; pretrained loader AST matches; context renders personally viewed; required permanent proof files present.'},ensure_ascii=False))
