import hashlib,json
from pathlib import Path
A=Path('docs/technical-reviews/artifacts/p6-R.4')
def h(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
V=json.loads((A/'checks/verification.json').read_text())
CAT=json.loads((A/'checks/raw-catalog.json').read_text())
env=V['environment']
artifacts=[];sources=[];claims=[]
def artifact(i,rel,kind,desc,command=None,result=None):
 p=A/rel;x={'id':i,'kind':kind,'path':p.as_posix(),'sha256':h(p),'description':desc}
 if kind=='execution':x.update(command=command,result=result,environment=env)
 artifacts.append(x);return i
artifact('a_input','inputs/R.4.md','source_snapshot','本次實際讀取 R.4 的原始 UTF-8 bytes；不是舊審閱報告。')
artifact('a_frozen','checks/frozen-input-manifest.json','source_snapshot','首次讀取的完整檔案與 frozen copies 的原始 SHA-256；全章指紋只代表本次輸入。')
artifact('a_code','checks/verify.py','code','本人寫的有界查核：指定原始 JSON pointers、15 收據、兩版 freeze/test、公用 CPU 舊執行記錄，以及合成輸入的 CPU 前向計算；無訓練、無留出題生成。')
artifact('a_run','checks/verification.json','execution','實際完成的原始收據重算、結構與 autograd 查核輸出。','/workspace/tiny-perceptron-vlm/.venv/bin/python docs/technical-reviews/artifacts/p6-R.4/checks/verify.py > docs/technical-reviews/artifacts/p6-R.4/checks/verify.stdout.txt 2> docs/technical-reviews/artifacts/p6-R.4/checks/verify.stderr.txt','exit 0；15 stages、各3734題、9個原CPU操作（8推論+1加入歷史）；兩種模型全部感知入口共用一個lm；未更新參數。')
artifact('a_stdout','checks/verify.stdout.txt','source_snapshot','上述當次執行的原始 stdout。')
artifact('a_catalog','checks/raw-catalog.json','source_snapshot','47個親自核對的原始 JSON 全檔 rawbytes SHA-256、先列出的 topkeys/types 與實際 inspected pointers；不讀 notes/review/*scope_correction。')
artifact('a_public','originals/anonymous-public-probe.json','execution','本人匿名取得兩版固定 revision 配置，核對 HF safetensors 的 immutable commit/linked SHA 與原評測紀錄。','/workspace/tiny-perceptron-vlm/.venv/bin/python docs/technical-reviews/artifacts/p6-R.4/checks/probe_public.py > docs/technical-reviews/artifacts/p6-R.4/checks/probe_public.stdout.txt','兩個配置 HTTP200；兩個 safetensors HTTP302，x-repo-commit 與 x-linked-etag 均與固定 release／final receipts 一致。')
artifact('a_license','checks/license-inspection.json','execution','本人直接核對本repo MIT與上游原始授權檔／發布者 metadata，不把上游資料與模型改稱本repo MIT。','/workspace/tiny-perceptron-vlm/.venv/bin/python docs/technical-reviews/artifacts/p6-R.4/checks/verify_licenses.py > docs/technical-reviews/artifacts/p6-R.4/checks/verify_licenses.stdout.txt','原始 LICENSE／metadata與專案授權宣告相符；此檢查只確認宣告來源，不冒稱完成全專案法律稽核。')
artifact('a_publiccode','checks/probe_public.py','code','本人实际执行的固定revision匿名probe脚本。')
artifact('a_licensecode','checks/verify_licenses.py','code','本人实际执行的原许可bytes/header检查脚本。')
artifact('a_paperlog','checks/original-paper-inspection.json','source_snapshot','本人實際讀原始 arXiv abstracts 與 submission history 的文字定位，對應原始 HTML rawbytes SHA。')
artifact('a_nav','checks/navigation.json','source_snapshot','本節11個本地相對連結實際存在。')
artifact('a_inspection_history','checks/inspection-history.json','source_snapshot','本人早期过宽protocol identity查询被截断的真实记录与分类；后续定向查询完整核对。')
artifact('a_initial_script','checks/verify-initial.py','code','保留本人首次檢查脚本；當時把只加入歷史的第二個操作誤當推論，後依原argv修正。')
artifact('a_initial_failure','checks/verify-initial.stderr.txt','source_snapshot','本人首次執行的真實失敗：history append argv不含--device；沒有把工具檢查假設錯誤當作教材錯誤。')
def external(i,kind,title,url,version,authority,note,rel):
 aid='a_'+i;artifact(aid,rel,'source_snapshot',title+'：本人實際取得的原始bytes。')
 sources.append({'id':i,'kind':kind,'title':title,'url':url,'version':version,'verified':True,'checked_original':True,'accessed_on':'2026-10-06','authority_reason':authority,'inspection_note':note,'snapshot_artifact_id':aid,'raw_sha256':h(A/rel)})
external('s_attention','paper','Attention Is All You Need','https://arxiv.org/pdf/1706.03762v7','arXiv1706.03762v7 (2023-08-02)','作者提交的原論文。','讀§3、§3.2/3.2.1 Eq(1)、§3.4：query/key compatibility經softmax得到value權重，混合後經learned output transformation形成next-token分布；不把attention比例等同詞彙概率。','originals/attention-v7.pdf')
external('s_embedding','official_docs','torch.nn.Embedding','https://docs.pytorch.org/docs/2.8/generated/torch.nn.Embedding.html','PyTorch2.8 versioned documentation; read2026-10-06','PyTorch官方API契約。','讀Embedding定義、Variables weight與Shape：index查表，learnable [num_embeddings,embedding_dim]；本次CPU2.14.1+cpu，只驗實際相容行為，不聲稱重跑所有版本。','originals/torch-embedding.html')
external('s_parameter','official_docs','torch.nn.parameter.Parameter','https://docs.pytorch.org/docs/2.8/generated/torch.nn.parameter.Parameter.html','PyTorch2.8 versioned documentation; read2026-10-06','PyTorch官方API契約。','讀Parameter及requires_grad：module parameter是被註冊的Tensor，支持以數字表述可學參數；不是所有中間Tensor或每個值都叫權重。','originals/torch-parameter.html')
external('s_autograd','official_docs','Automatic Differentiation with torch.autograd','https://docs.pytorch.org/tutorials/beginner/basics/autogradqs_tutorial.html','官方tutorial快照2026-10-06/rawSHA；本次torch2.14.1+cpu','PyTorch官方autograd教程。','讀Tensors/Functions/Computational graph與Computing Gradients：w,b是待優化參數，loss.backward取得梯度；梯度計算與實際更新是不同操作。','originals/torch-autograd.html')
external('s_optimization','official_docs','Optimizing Model Parameters','https://docs.pytorch.org/tutorials/beginner/basics/optimization_tutorial.html','官方tutorial Last Updated2026-07-31；快照2026-10-06','PyTorch官方訓練與評測教程。','讀開頭、Optimization Loop與Full Implementation：反覆prediction/loss/backward/optimizer.step；test_loop在no_grad下做evaluation，沒有optimizer.step。','originals/torch-optimization.html')
for i,title,num,ver,note in [
 ('s_moe','Outrageously Large Neural Networks: The Sparsely-Gated Mixture-of-Experts Layer','1701.06538','v1 (2017-01-23)','讀abstract：trainable gate按例子選稀疏FFN expert組合，屬架構／conditional computation；不引用其速度為本成品保證。'),
 ('s_ppo','Proximal Policy Optimization Algorithms','1707.06347','v2 (2017-08-28)','讀abstract：環境互動取樣與policy-gradient surrogate優化，屬RL訓練訊號。'),
 ('s_dpo','Direct Preference Optimization: Your Language Model is Secretly a Reward Model','2305.18290','v3 (2024-07-29)','讀abstract：以偏好分類loss求RLHF對應policy，明確比較PPO-basedRLHF；支持存在替代安排，不支持每任務都應採DPO。'),
 ('s_quantization','Quantization and Training of Neural Networks for Efficient Integer-Arithmetic-Only Inference','1712.05877','v1 (2017-12-15)','讀abstract：integer-only inference與保持量化後accuracy的training procedure，屬表示／部署問題；不證明本小模型實際加速。'),
 ('s_distillation','Distilling the Knowledge in a Neural Network','1503.02531','v1 (2015-03-09)','讀abstract：把ensemble知識壓入單一較容易部署的model，與MoE gating架構不同。')]:
 external(i,'paper',title,'https://arxiv.org/abs/'+num,ver,'作者直接提交於arXiv的原始摘要與版本資訊。',note,'originals/'+i[2:]+'.html')
external('s_qwen','official_source','Qwen3-VL official usage source','https://raw.githubusercontent.com/QwenLM/Qwen3-VL/main/README.md','main取得2026-10-06；rawSHA '+h(A/'originals/qwen3vl.md'),'Qwen模型發布者官方repo。','讀release entry Qwen3-VL-2B以及lines140–179官方from_pretrained圖文例子；只支持成熟權重載入路線，不採納行銷式性能宣告。','originals/qwen3vl.md')
external('s_whisper','official_source','OpenAI Whisper load_model','https://raw.githubusercontent.com/openai/whisper/main/whisper/__init__.py','main取得2026-10-06；rawSHA '+h(A/'originals/whisper.py'),'Whisper作者官方原始碼。','讀lines103–160：Load a Whisper ASR model；load checkpoint then model.load_state_dict，支持已有ASR權重起點；未載入／執行大模型。','originals/whisper.py')
external('s_fashionlicense','official_source','Fashion-MNIST original license','https://raw.githubusercontent.com/zalandoresearch/fashion-mnist/master/LICENSE','取得2026-10-06；SHA13ef4788476d292858fa60eb9a5f74aeca5c65770bc885ccaa05823a17ef7be1','Fashion-MNIST發布者Zalando Research原始授權檔。','全文MIT授權及copyright，與prep pinned license SHA相符。','originals/fashion-license.txt')
external('s_notolicense','official_source','Noto CJK original license','https://raw.githubusercontent.com/notofonts/noto-cjk/f8d157532fbfaeda587e826d4cd5b21a49186f7c/Sans/LICENSE','commit f8d157532fbfaeda587e826d4cd5b21a49186f7c / OFL1.1','Noto字型發布者原始授權檔。','讀開頭和OFL1.1 PREAMBLE/conditions：字型及其衍生檔遵守OFL，使用字型生成的文件不因此需OFL；不把字型改成教材MIT。','originals/noto-license.txt')
external('s_minds','official_source','PolyAI MInDS-14 official dataset metadata','https://huggingface.co/datasets/PolyAI/minds14/raw/40ce77cb32a384e4d50a568e1ec39ac804019d33/README.md','commit40ce77cb32a384e4d50a568e1ec39ac804019d33','資料發布者PolyAI之固定官方資料頁。','讀frontmatter cc-by-4.0/crowdsourced、zh-CN502例metadata、Dataset Description spoken e-banking intents與Data Fields；只支持真人spoken需求來源與原授權。','originals/minds-pinned-source.txt')
external('s_qwenlicense','official_source','Qwen3-VL-2B-Instruct official license metadata','https://huggingface.co/Qwen/Qwen3-VL-2B-Instruct/raw/main/README.md','main取得2026-10-06；rawSHA '+h(A/'originals/qwen-2b-official-card.md'),'Qwen官方模型發布頁；非本repo作者成品modelcard。','只讀frontmatter license:apache-2.0與pipeline_tag；沒有用此modelcard的性能敘述證明教學或本成品成績。','originals/qwen-2b-official-card.md')
external('s_whisperlicense','official_source','OpenAI Whisper original MIT license','https://raw.githubusercontent.com/openai/whisper/main/LICENSE','main取得2026-10-06；rawSHA '+h(A/'originals/whisper-license.txt'),'Whisper作者官方授權檔。','讀MIT grant/copyright/保留授權文字条件，支持上游保留自己的授權。','originals/whisper-license.txt')
def repo(i,name,note):
 p=A/'inputs'/name;artifact('a_'+i,'inputs/'+name,'code' if name.endswith('.py') else 'source_snapshot','本次所查原實作／授權完整原始bytes；實際讀取範圍見source.inspection_note。')
 sources.append({'id':i,'kind':'repository_code','title':name,'path':p.as_posix(),'sha256':h(p),'version':'2026-10-06本次frozen input；完整rawbytes SHA已保存','verified':True,'inspection_note':note})
repo('s_model','tiny_perceptron/selftrained/model.py','先AST列類別／函式，再讀25–53 config、56–130 gate/FFN、133–185 core、188–282 encoders、295–382 modality insertion。均為計算分支及契約；沒有借作者結果字串判定。')
repo('s_lm','tiny_perceptron/model.py','先AST定位TinyLM，讀53–89 nn.Embedding、nn.Linear、tied weight及forward輸出logits。')
repo('s_modern','tiny_perceptron/modern.py','先AST定位DenseFFN/MoEFFN，讀35–84單FFN、router/expert建立及weighted dispatch。')
repo('s_train','scripts/selftrained/train.py','先AST列函式；讀84–103 stage_records split filter、689–810 own checkpoint schema/origin/初始化/AdamW、878–984 validation選版和training gradient/update分支。未讀結果評語常數。')
repo('s_eval','scripts/selftrained/evaluate.py','先AST列函式；讀318–380固定protocol身分／threshold比對、495–560 aggregate分母計算、733–823 test不能limit及test-started marker。未讀作者結果評語。')
repo('s_inference','tiny_perceptron/selftrained/inference.py','先AST列函式；讀74–136固定40hex、token=False、hash核對，以及218–265完整神經權重載入；不重跑生成。')
repo('s_natural','tiny_perceptron/natural_assistant.py','AST定位後只讀load_core263–306和load_asr687–710；from_pretrained Qwen3VL/Whisper分支，與scratch管線不同。')
repo('s_preparevoice','scripts/selftrained/prepare_voice.py','先AST定位main及常數；讀REVISION/SELECTED/ANSWERS規約與308–370固定PolyAI來源parquet／waveform metadata讀取，未讀作者結果摘要。')
repo('s_preparevision','scripts/selftrained/prepare_vision_ocr.py','先AST定位，讀26–56來源revision、三類Fashion與12字、pinned license SHA。')
repo('s_license','LICENSE','直接读2026 birdhackor MIT许可全文；授权对象包含software及associated documentation。')
repo('s_pyproject','pyproject.toml','讀project license=MIT与torch依賴；只支持授權／工具宣告，不用環境名替代實跑。')
sources.append({'id':'s_run','kind':'execution','title':'本人原始收據核對及短CPU檢查','verified':True,'artifact_id':'a_run'})
sources.append({'id':'s_public','kind':'execution','title':'本人固定revision匿名HF檔案probe','verified':True,'artifact_id':'a_public'})
sources.append({'id':'s_licenseexec','kind':'execution','title':'本人授權原始檔與metadata核對','verified':True,'artifact_id':'a_license'})
def ev(s,loc,sup):return {'source_id':s,'locator':loc,'supports':sup}
def raw(prefix):return [{'path':x['path'],'sha256':x['sha256_rawbytes'],'inspected_pointers':x['inspected_pointers']} for x in CAT if prefix in x['path']]
def claim(i,kind,statement,loc,evidence,scope,arts,expected=None,observed=None,details=None,den=None,raws=None):
 x={'id':i,'kind':kind,'statement':statement,'location':loc,'status':'verified','evidence':evidence,'artifact_ids':arts,'scope':scope}
 if kind in ['software','empirical','numeric']:
  x['verification']={'method':'executed','expected':expected,'observed':observed,'details':details}
  if kind=='empirical':x['verification']['denominators']=den
 if raws:x['raw_evidence']=raws
 claims.append(x)
claim('c1','concept','查表得到向量，依位置比對得到比例、混合內容，再形成下一字的候選分數。','R.4第1–2段',[ev('s_embedding','Embedding定義、Variables weight、Shape','index查表得到向量。'),ev('s_attention','§3.2/3.2.1 Eq(1)、§3.4','query-key相容程度、softmax權重、value加權混合與next-token輸出映射。')],'這是機制摘要；attention的比例是位置間權重，混合後仍有輸出映射；不把人類讀書譬喻當模型心理機制。',['a_s_embedding','a_s_attention'])
claim('c2','concept','真正訓練反覆用例子更新參數，保留不參與更新的題目評估能力。','R.4第1段',[ev('s_optimization','Optimization Loop；Full Implementation train_loop/test_loop','训练backward/step，评测no_grad且无step。'),ev('s_train','stage_records84–103、main726–764、select_and_save878–900','成品程式分離train/validation並以validation loss選版。')],'定義與本管線相符；保留題是方法需要，存在留出題不自動證明一般泛化。',['a_s_optimization','a_s_train'])
claim('c3','software','文字核心生成回答；圖像／聲音入口提取特徵並透過可學投影接為同一核心接收的向量。','R.4第3段',[ev('s_model','encoders188–282、LimitedAssistant295–382','三種神經入口輸出core width；slots填入同一lm。'),ev('s_run','verification.json /structure；/cpu','合成前向可跑通三種入口；原CPU记录共用同一MoE权重。')],'人工零像素／特徵前向只驗連接和維度；原CPU記錄支持有實際成品流程；不證明任意圖像／語音答對。',['a_s_model','a_code','a_run','a_catalog'],'三種入口的向量都交給同一lm','兩版前向logits[1,52,550]；image/ocr/audio对应2/32/16个width256向量','以公開結構的隨機模型和人工合成輸入作torch.no_grad前向；沒有生成或更新。',raws=raw('public-cpu-raw'))
claim('c4','concept','模型中可由訓練調整的數值称為權重。','R.4第4段',[ev('s_parameter','Parameter；requires_grad','神經模型可學參數是被module註冊的tensor。'),ev('s_autograd','Tensors/Functions/Computational graph；Computing Gradients','以w,b說明參數／權重及梯度。')],'入門稱呼可涵蓋bias、norm可學參數；不指所有中間值或buffer。部分參數可在某訓練stage凍結，不改變其模型參數身分。',['a_s_parameter','a_s_autograd'])
claim('c5','software','本成品先由程式建立初始神經權重，再學提供資料，未借用成熟模型的已學神經權重。','R.4第4段',[ev('s_model','LimitedAssistant.__init__296–302及各encoder constructors','以本地神經module constructor建立模型。'),ev('s_train','main733–797 source schema/model constructor/load_state_dict/origin','後續只接受本scratch管線checkpoint；無成熟from_pretrained分支。'),ev('s_run','verification.json /training/*/origin；/history','15份原收據保留scratch origin、seed及own-stage selected SHA鏈。')],'支持這兩版既有訓練的神經權重來源；從零不表示每個scalar都隨機（norm/bias可用固定初值），也不表示工具和前處理算法沒有既有實作。',['a_s_model','a_s_train','a_code','a_run','a_catalog'],'15份原收据源于own随机初始化并仅沿own stage权重链延续','15/15 origin=all-neural-weights-random；无test选版；原始pretrain origin/seed一致','核对每个原train-receipt origin/kind,seed,stage_history选版SHA，再核训练初始化与own schema约束；没有重训。',raws=raw('training-raw'))
claim('c6','software','主線是MoE，另保留較簡單的Dense對照設計。','R.4第4段',[ev('s_model','SelftrainedConfig、MaskedBlock109–116','architecture選擇router多expert或單DenseFFN。'),ev('s_modern','DenseFFN35–53、MoEFFN56–84','两者FFN结构差异。'),ev('s_run','verification.json /structure、/training','兩版實際結構及各自原訓練記錄。')],'較簡單指單FFN相對router+多expert；不宣稱MoE比較公平、速度更快或得分差由架構造成。',['a_s_model','a_s_modern','a_code','a_run','a_public'],'公开MoE/Dense配置构造相应FFN','MoE为PaddingSafeMoE；Dense为DenseFFN；参数各5447107/2288067','固定revision配置，合成前向及class检查；结构参数只支持配置事实。',raws=raw('training-raw'))
claim('c7','empirical','兩種v2模型已完成訓練。','R.4第5段',[ev('s_train','receipt961–1004、训练while904–959','completed_requested_steps对比实际step和requested steps。'),ev('s_run','verification.json /training','15原stage receipts的实际步数和execution argv一致。')],'完成指既定stage／所請求步數完成，且selected/export可得；不等同已把任務學好。',['a_s_train','a_code','a_run','a_catalog'],'15份正式stage均完成各自requested steps','15/15 completed且execution returncode0，累计64400更新步／129670158输入token','实际核对步数和原execution命令--steps，不拿receipt布林值单独替代过程核对。',{'stage_runs':15,'actual_update_steps_total':64400,'input_tokens_across_stage_runs':129670158,'seed':20261006},raw('training-raw'))
claim('c8','software','兩版v2已公開可下載的純推論權重。','R.4第5段',[ev('s_inference','fetch_public_export101–136；verify_export74–98','固定commit/token=False/4個safe payload與hash核對。'),ev('s_public','anonymous-public-probe.json兩版model-config及model.safetensors','目前匿名配置HTTP200、safetensors固定commit連結SHA。'),ev('s_run','verification.json /final/public_revision；/cpu/public_source','原public test收据与匿名CPU已经完整取得并使用同一safe weights。')],'公开事实由固定revision原匿名执行和当前对象probe合证；当前probe没有再次下载所有权重，更没有用modelcard自述证明性能。',['a_s_inference','a_public','a_code','a_run','a_catalog'],'两版release revision固定并对应final safe SHA','revision979cdfacc588ad0536f1c64fff96f264571cf054；MoE26102d2e…、Dense5f8b5b04…','核对完整64hex SHA和原receipt public_export，HEAD x-linked-etag精确一致；CPU原推论authentication disabled。',raws=raw('public-raw')+raw('public-cpu-raw'))
claim('c9','empirical','兩版已完成固定最後測試。','R.4第5段',[ev('s_eval','protocol_contents318–353/validate_protocol356–380；main733–811','freeze binds weights/data/code/budget/threshold；正式test不能limit且须once marker。'),ev('s_run','verification.json /final；raw-catalog.json公开freeze/test pointers','freeze SHA与journal protocol SHA相符，completed_count各3734，权重等身份不变。')],'支持这一次固定公共推论权重的原最后考卷完成；收据及代码只能支持记录的执行过程，不是不可伪造的数学证明。',['a_s_eval','a_code','a_run','a_catalog'],'两版各完成同一冻结协议规定的全部test记录','各3734/3734，status complete，evaluation_complete true，非limited smoke、无teacher forcing generation','核对freeze/test/journal/export中的权重和threshold身份，sum各task count=3734，各比率由numerator/denominator重算。',{'questions_per_architecture':3734,'architectures':2,'test_split':'test','generation_budget':128},raw('public-raw'))
claim('c10','empirical','兩版仍未通過全部原定能力判準。','R.4第5段',[ev('s_run','verification.json /final/tool_roundtrip与/original_tool_threshold','MoE0/276及Dense7/276均低于freeze原0.95。'),ev('s_eval','protocol_contents thresholds／validate_protocol threshold equality','固定判准与final指标绑定。')],'只需要一项未达就能否定全项通过；未在R.4重数全部15/12失败项，也不以高分任务补偿工具失败。',['a_s_eval','a_code','a_run','a_catalog'],'至少一个原冻结数值判准不达标','真正往返MoE0/276=0，Dense7/276=0.025362318840579712；要求0.95','直接从原per_task_final_reply/tool_call/tool_roundtrip读取分子分母，独立除法，并与原freeze阈值比对。',{'actual_tool_roundtrip_questions_per_architecture':276,'required_rate':0.95},raw('public-raw'))
claim('c11','empirical','成品任務限教過類型的文字請求、商品與位置、已知中文字卡、真人客服語音需求與計算工具。','R.4第5段',[ev('s_run','verification.json /final/tasks','原最终任务／分母确属这些范围，没有任意照片或通用语音的测验。'),ev('s_preparevision','常數26–56','Fashion三类、12字與固定素材來源。'),ev('s_preparevoice','SELECTED constants；main来源308–370','address/app_error/card_issues及原波形來源，不是成熟ASR生成的文字输入。'),ev('s_minds','frontmatter; Dataset Description; Data Fields','发布者spoken e-banking原录音与真人crowdsourced来源。')],'仅支持指定范围下的部分表现；R.4下一句已明确未全通过。问题数不等于独立素材／人；不外推通用中文、任意照片、通用听写。',['a_s_preparevision','a_s_preparevoice','a_s_minds','a_code','a_run','a_catalog'],'原测题task集合落在这五类有限能力范围','原12任务列含text/ocr/vision/voice/tool及边界条件，合计3734问题／版','核对task标签和分母，配合固定资料准备常数、原数据发布者说明，不拿教学限制句当证据。',{'questions_per_architecture':3734,'task_buckets':12,'fashion_classes':3,'ocr_glyphs':12,'voice_intents':3},raw('public-raw'))
claim('c12','software','第20章Qwen／Whisper是接手已有能力模型的成熟延伸，與本章自己的從零路線不同。','R.4第5段末句',[ev('s_natural','load_core263–306；load_asr687–710','本repo自然路線調用Qwen3VL和Whisper from_pretrained。'),ev('s_qwen','official usage lines140–179及2B release entry','發布者已有圖文權重。'),ev('s_whisper','load_model103–160','發布者已有ASR checkpoint與state_dict。'),ev('s_run','verification.json /mature_route','独立AST确认各函数的from_pretrained调用。')],'核對起點／程式路線，不把成熟底座能力當成本MoE的接續訓練或加分；沒有重下載／執行成熟大模型。',['a_s_natural','a_s_qwen','a_s_whisper','a_code','a_run'],'mature route separate loaders use existing Qwen/Whisper weights','load_core/load_asr均有model及processor from_pretrained调用；scratch LimitedAssistant无此调用','读两个真实函数计算／构造分支，AST调用核验；章20导言作为待查主张而非证明。')
claim('c13','concept','MoE、PPO、DPO、量化與蒸餾處理不同問題，部分方法有替代安排；首次助理不必全用。','R.4第6段',[ev('s_moe','abstract','conditional-computation architecture。'),ev('s_ppo','abstract','RL policy-gradient optimization。'),ev('s_dpo','abstract','preference classification objective可代PPO-basedRLHF安排。'),ev('s_quantization','abstract','整数表示／推论部署。'),ev('s_distillation','abstract','ensemble知识转到可部署单model。')],'这些方法并非一条全部必经的流水线，也不是互相全部可替代；不同目标可以组合。只支持方法角色选择，不用本小成品替成熟研究重判效益。',['a_s_moe','a_s_ppo','a_s_dpo','a_s_quantization','a_s_distillation'])
claim('c14','software','本課使用PyTorch進行數字表計算、梯度與參數更新。','R.4details第1句',[ev('s_lm','TinyLM53–89','nn.Embedding/Linear等PyTorch计算。'),ev('s_train','optimizer759附近及loop904–940','AdamW、loss.backward、optimizer.step。'),ev('s_autograd','Computing Gradients','官方梯度契約。'),ev('s_run','verification.json /autograd及/structure','实际CPU forward/autograd版本结果。')],'本人短CPU检查只计算梯度、没有参数更新；更新行为由真实训练分支加原已完成收据支持，不声称本次训练。',['a_s_lm','a_s_train','a_s_autograd','a_code','a_run'],'PyTorch前向／autograd实际可用，原训练程序有更新步骤','torch2.14.1+cpu；w=[2,3]，loss13，grad=[4,6]，w保持原值；原训练15 stages完成','合成前向与独立二次函数梯度；精确比较导数；另读真实optimizer.step计算分支。',raws=raw('training-raw'))
claim('c15','software','本repo程式、文字與自製圖解採MIT授權。','R.4details第2句',[ev('s_license','完整MIT grant与copyright','repo作者对software及associated documentation的授权。'),ev('s_pyproject','project.license与license-files','项目许可宣告与LICENSE路径。'),ev('s_licenseexec','license-inspection.json /project','本人核对原文件与metadata。')],'这是一项repo许可宣告核实；不把嵌入或引用的外部素材默认纳入MIT，不冒称作者权属的法律审计。',['a_s_license','a_s_pyproject','a_license'],'项目LICENSE和pyproject均声明MIT','MIT License／Copyright2026 birdhackor；project.license=MIT','直接读原grant bytes并由tomllib核project许可，完整SHA保留。')
claim('c16','software','公開資料、字型與上游模型保留各來源授權。','R.4details第2句',[ev('s_fashionlicense','完整MIT license','商品來源原许可。'),ev('s_notolicense','OFL1.1 PREAMBLE及conditions','Noto字型自有许可及生成文件条件。'),ev('s_minds','frontmatter license','MInDS语音CCBY4。'),ev('s_qwenlicense','frontmatter license','Qwen2B权重来源Apache2。'),ev('s_whisperlicense','完整MIT grant','Whisper来源MIT。'),ev('s_licenseexec','license-inspection.json','原bytes/header核对。')],'按该段语义核对的是来源许可政策，不替全书所有数据作全面合规保证；没有把上游统一改为教材MIT。',['a_s_fashionlicense','a_s_notolicense','a_s_minds','a_s_qwenlicense','a_s_whisperlicense','a_license'],'上游不同来源许可分开保留','Fashion MIT、Noto OFL1.1、MInDS CCBY4、Qwen2B Apache2、Whisper MIT','以发布者原LICENSE或固定dataset/官方model metadata检查；Qwen LICENSE路径404后转读官方frontmatter，Noto改用固定实际Sans/LICENSE。')
report={'schema_version':1,'review_stage':'technical','lesson_id':'R.4','source':'course/README.md#R.4','reviewer_task':'/root/p6_fact_r4','reviewer_context':'fresh','source_sha256':h(A/'inputs/R.4.md'),'figure_sha256':{},'verdict':'pass','claims':claims,'sources':sources,'artifacts':artifacts,'issues':[],
 'checks':{'factual_accuracy':{'status':'pass','details':'逐条16项主张经原始论文／官方API、真实计算分支及原收据核对；从零起点、共同core与有限能力区分成立。','claim_ids':[x['id'] for x in claims]},'numeric_verification':{'status':'pass','details':'独立重算15 stages步数/token、各3734题task合计与原比率；真正工具往返两版低于冻结0.95，未全能力通过结论成立。','claim_ids':['c7','c9','c10','c11']},'figure_consistency':{'status':'not_applicable','details':'R.4本身无图像／SVG引用；19.6链接是导航，不在本节冒充实渲图核对。','claim_ids':[]},'source_verification':{'status':'pass','details':'本人读原始PDF/API/发布者源码及许可；外部快照、47原JSON的rawbytes SHA及实际pointers留存。未用本repo modelcard、教学内容或旧审阅解释证明成品。','claim_ids':[x['id'] for x in claims]},'limitations':{'status':'pass','details':'完成训练／公开weights／最后test与全能力通过分开；有限任务、与成熟Qwen/Whisper不同起点、MoE不保速度和公平因果比较等范围均保留；没有训练或再生留出题。','claim_ids':['c3','c5','c6','c7','c8','c9','c10','c11','c12','c13']}},
 'review_scope':{'read_sections':['course/README.md#R.4','course/chapters/19.md#19.2','course/chapters/19.md#19.6','course/chapters/19.md#19.12','course/chapters/20.md chapter introduction'],'read_as_unverified_claims':True,'frozen_full_markdown':{'path':str(A/'inputs/course/README.md'),'sha256':h(A/'inputs/course/README.md'),'meaning':'首次读取本轮frozen input的全文件fingerprint；正式source_sha256仅R.4原bytes'},'navigation_and_pedagogical_intent':'方法选择建议、每节限制说明承诺、操作页导航及阅读无需全下载是导读安排；11本地链接存在。没有据此宣称重新审过全书实验。','excluded_inputs':['old reader/technical reports and verdicts','author supplemental results explanations','notes/review/*scope_correction in raw JSON','project selftrained modelcards','controller review in public-cpu-raw index'],'initial_protocol_query_history':'见a_inspection_history：一次frozen identity metadata查询过宽且stdout被截断，无作者结果摘要；后以具名pointers完整核验。','verification_boundaries':'原成品数据核对；CPU只做人工合成前向与参数梯度，无optimizer更新、无训练、无留出题生成、无上传。','first_execution_history':'初次检查误要求history-append操作带--device而失败；保留初始script/stderr，按原argv确认它不推论后修正，最终exit0。没有教材revise问题。'}}
p=Path('docs/technical-reviews/R.4.json');p.write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n');((A/'initial-report.json').write_bytes(p.read_bytes()) if not (A/'initial-report.json').exists() else None);print('wrote',p,'claims',len(claims),'sources',len(sources),'artifacts',len(artifacts),'source',report['source_sha256'])
