from pathlib import Path
import hashlib,json,copy
OUT=Path(__file__).resolve().parent;PRIOR=OUT.parent;ROOT=OUT.parents[5];BASE=OUT.relative_to(ROOT).as_posix()+'/'
def sha(p):return hashlib.sha256((ROOT/p).read_bytes()).hexdigest()
def read(p):return json.loads(p.read_text())
old=read(PRIOR/'report.json');cur=read(OUT/'current-record.json');browser=read(OUT/'browser-record.json');r=copy.deepcopy(old)
assert sha((PRIOR/'report.json').relative_to(ROOT))=='d9482cdfc38766e00160b823235f819090b24d7e512c88103cf6d94a25abb5c5'
env=cur['environment'];env['browser_executable']='/usr/bin/chromium'
artifacts=r['artifacts']
for a in artifacts:a['description']='Preserved previous-round evidence, explicitly reused only where unchanged-byte checks establish applicability: '+a['description']
def artifact(id,kind,name,description,command=None,result=None):
 a={'id':id,'kind':kind,'path':BASE+name,'sha256':sha(BASE+name),'description':description}
 if kind=='execution':a.update(command=command,result=result,environment=env.copy())
 artifacts.append(a)
artifact('a_r2current','execution','current-record.json','Actual current four-source snapshots and own dependency/archive/authority/empirical-record byte comparisons, current torch version, 266-notebook ordered-cell inventory, numeric section recount and previous c05 removal check.','.venv/bin/python '+BASE+'current_probe.py','Exit0. All unchanged-byte assertions and source identity checks passed; actual first-cell inventory contradicts English line9.')
artifact('a_r2browser','execution','browser-record.json','Actual8784 current pinned source/browser/figure navigation, English GitHub link, local notebook downloads, CPU-output visibility, search/copy/theme/zoom/reduced-motion actions.','.venv/bin/python '+BASE+'browser_probe.py','Exit0. Current four files match literal f43b393431d4908f0ea38a2375f8cae9c4320d12; real browser reached pinned English GitHub README and retrieved1.1/20.2 notebooks.')
for stem in ['current','browser']:
 artifact('r2_script_'+stem,'code',stem+'_probe.py','Exact own bounded current-round probe; no claim of prior GPU or training rerun.')
 for suffix in ['stdout.txt','stderr.txt']:artifact('r2_'+stem+'_'+suffix.replace('.','_'),'source_snapshot',stem+'.'+suffix,'Actual successful current-round '+stem+' command '+suffix+'.')
artifact('a_r2buildinfo','source_snapshot','build-info.receipt.json','Specific8784build-info response SHA and relevant revision/lesson/output fields; no preview-wide JSON or search-index reading.')
for f in cur['complete_documents']:
 artifact('r2_snapshot_'+f.replace('/','_').replace('.','_'),'source_snapshot',f.replace('/','__')+'.read-snapshot','Exact complete current assigned source personally read; English is first complete factual reading.')
for name in ['character_ids-render','readme-browser','english-link-browser','course-browser','assets-browser','lesson1-browser','lesson20-2-browser','diagram-zoom','dark-mode','search-browser']:
 artifact('r2_view_'+name.replace('-','_'),'figure_render',name+'.png','Actual current-round Chromium screenshot. All assigned-page/figure/lesson screenshots were personally viewed; feature screenshots retain execution provenance.')
for name in ['readme-browser','course-browser','assets-browser','lesson1','lesson20-2-browser']:
 artifact('r2_visible_'+name.replace('-','_'),'source_snapshot',name+'.visible.txt','Actual selected current-page article text saved by browser, not a preview-wide index.')
artifacts.append({'id':'a_prior_final_report','kind':'source_snapshot','path':str((PRIOR/'report.json').relative_to(ROOT)),'sha256':cur['prior_report']['sha256'],'description':'Genuine previous first FINAL revise report remains byte-identical, including original three hashes and c05 failure. This is own history, not another reviewer judgment.'})
r['schema_version']=1;r['review_round']=2;r['review_type']='independent_factual_complete_document_supplement';r['reviewer_task']='/root/v4_review_coordinator/factual_whole_entries';r['reviewer_context']='fresh'
r['reviewer_context_details']='Same original independent factual owner, current-source rerecheck plus explicitly expanded first complete English factual reading. No other reader/factual report, author notes or review verdict were read. Previously personally executed/researched evidence is reused only with explicit exact-byte identity and unchanged applicability.'
r['assigned_document_scope']='Entire raw unnormalized UTF-8 bytes of exactly README.md, README_en.md, course/README.md and assets/training/README.md; all headings, tables, code blocks, substantive factual/technical claims and the single referenced SVG. README_en.md is first complete factual reading in this round. Neutral navigation and maintenance command listings are considered in context, without fabricated numbered lesson IDs.'
r['complete_documents']=list(cur['complete_documents']);r['current_document_sha256']={p:v['sha256'] for p,v in cur['complete_documents'].items()}
r['source_read_order']=['Previously read unchanged supplemental-factual-contract.md and technical-review-guide.md (exact SHA checked again)']+r['complete_documents']+['Actual current Notebook cells and build_course.notebook()/check_notebooks.run_kernel()/train.main inspected for English statements','Previously personally read complete prerequisite sections and original sources, exact current bytes verified in a_r2current','Actual8784 pinned-page browser navigation and current SVG render personally viewed']
r['source_read_scope']='All349current assigned document lines were fully read. All91English lines are a first whole-document factual reading; the former outside-scope single-sentence observation was not used as an English approval. Prior prerequisite sections, local code, fixed record audits and original authority fulltext have explicit byte comparisons in a_r2current. Current necessary first-cell/build/kernel/save code was directly inspected; current ordered notebook inventory and numeric counts actually executed. No other reviewer judgment was read.'
r['preview']={'url':'http://127.0.0.1:8784/','path':'outputs/site-reader-executed-v4-entry-links','literal_revision':browser['literal_revision'],'all_assigned_source_bytes_equal':True,'browser_execution_artifacts':['a_r2browser'],'english_entry':'Actual README English click navigated to GitHub blob/f43b393431d4908f0ea38a2375f8cae9c4320d12/README_en.md; no standalone English export exists or is presumed.','scope':'Assigned Chinese pages, actual pinned English GitHub entry, relevant route/lesson/data navigation, notebook retrieval, controls and original SVG personally checked.'}
r['figure_inspection']='Personally viewed newly rendered current8784character_ids.svg and its README embed: eight characters/arrows map to[3,2,1,4,1,2,3,0], both orange cats map3, reverse lookup restores貓看狗，狗看貓。. Current served/source/previous personally executed SVG bytes match; IDs are labels rather than semantic magnitudes.'
english_locations={'c01':'README_en.md:7,11','c02':'README_en.md:9,39,69,85 (first-cell wording separately assessed in c28)','c03':'README_en.md:9,43','c04':'README_en.md:11,13','c06':'README_en.md:15','c08':'README_en.md:17','c09':'README_en.md:19','c10':'README_en.md:17,58','c11':'README_en.md:58–65','c12':'README_en.md:27–43','c13':'README_en.md:41,56,85','c14':'README_en.md:21','c15':'README_en.md:11','c16':'README_en.md:19','c18':'README_en.md:23,52,65','c21':'README_en.md:54,91','c24':'README_en.md:54','c26':'README_en.md:23,54,65','c27':'README_en.md:45–52'}
r['claims']=[c for c in r['claims'] if c['id']!='c05']
for c in r['claims']:
 if c['id'] in english_locations:c['location']+='; '+english_locations[c['id']]
 c['scope']+=' Current-round applicability checked independently against the complete four documents; prior bounded execution or original-authority inspection is explicitly reused with matching bytes in a_r2current.'
 if c['kind'] in ['software','numeric','empirical']:
  c['artifact_ids'].append('a_r2current')
  c['verification']['details']+=' Current round: own prior input/evidence/source bytes and relevant original records remain exact; reused execution is not represented as a rerun.'
 if 'a_browser' in c['artifact_ids']:c['artifact_ids']=[x for x in c['artifact_ids'] if x not in ['a_browser','a_features']]+['a_r2browser']
 if c['id']=='c02':
  c['verification']['expected']='266 notebooks; code-containing notebooks have bootstrap in first code cell; current1.1 local download succeeds. Literal English first-cell claim is assessed separately in c28.'
  c['verification']['observed']='Current266notebooks: all first cells Markdown;264have first-code setup,20.2/20.8have no code. Actual8784downloads:1.1HTTP200,first code index2;20.2HTTP200,zero code. Previous own1.1execution passed and its notebook bytes remain exact.'
  c['verification']['details']='Actually inventoried all current ordered notebook cells and retrieved current1.1/20.2downloads through Chromium; independently inspected notebook generator. Reused only prior actual1.1execution after exact byte comparison; no fresh cloud run.'
 if c['id']=='c03':
  c['scope']='Current8784specific-page actual Chromium checks. English link reaches fixed GitHub README_en rather than a standalone export. MathJax is configured as a network dependency; static SVG/reduced-motion behavior and real zoom/search/theme/copy actions were inspected. No universal offline-rendering claim.'
  c['verification']['expected']='Current pinned preview matches all four assigned files and relevant documented browser controls operate; English entry follows the actual exported link.'
  c['verification']['observed']='All four source hashes match f43b393431d4908f0ea38a2375f8cae9c4320d12; actual pinned English GitHub entry, visible1.1CPU output, real route/lesson/data clicks, search hits, slate/default toggle, inline SVG expansion and copied installation code.'
  c['verification']['details']='New current-round Chromium execution and screenshots;1.1/20.2notebook downloadsHTTP200; UI search used without accessing search-index JSON. Current original SVG was rendered and personally viewed.'
 if c['id']=='c27':
  c['statement']='The minimal text flow prepares synthetic toy-text and defaults to one forward/backward batch without optimizer update or checkpoint write; --train explicitly enables training updates/saves.'
  c['verification']['details']+=' Direct current inspection: scripts/train.py:355–417 guards optimizer.step and both save paths under args.train; no default checkpoint write is reachable.'
r['claims'].append({'id':'c28','kind':'software','statement':'README_en.md says each complete lesson notebook prepares the repository and packages in its first cell.','location':'README_en.md:9, phrase “with repository and package setup in its first cell”','status':'contradicted','scope':'New issue from first complete English factual reading. Literal first cell is materially different from first code cell. All266current notebooks start with title Markdown;264have a later setup code cell and20.2/20.8have no code/setup cells. No real Colab runtime was executed.','evidence':[{'source_id':'r_build','locator':'notebook(), lines106–145; cells initialized to title markdown at110, conditional bootstrap appended at119–127','supports':'Generator always places the title Markdown before setup, and inserts setup only when a Python/figure block exists.'},{'source_id':'s_nb','locator':'Top-level structure and Cell types in official nbformatv5.10.4 format_description.rst','supports':'Notebook cells are an ordered array with explicit markdown/code types; the first array item is a cell.'}],'artifact_ids':['a_r2current','a_r2browser'],'verification':{'method':'executed','expected':'If the literal English assertion were true, cell0 of each lesson would perform repository/package preparation.','observed':'266/266cell0 entries are title Markdown,0/266first cells perform setup;264notebooks have a later bootstrap code cell,while20.2/20.8have no code cells. Actual8784download1.1 has Markdown cell0 and first code index2;20.2 has2Markdown cells and0code cells.','details':'Executed complete current ordered-cell inventory with per-file SHA and first-cell source, inspected current generator and original cell-format specification, and retrieved actual current1.1/20.2notebooks through the browser. This is not a Colab cloud execution.'}})
r['resolved_prior_issues']=[{'claim_id':'c05','previous_report_path':cur['prior_report']['path'],'previous_report_sha256':cur['prior_report']['sha256'],'previous_document_sha256':cur['prior_report']['document_sha256'],'previous_verdict':'revise','resolution':'Current README.md:17 removes the unsupported video-helper assertion. Exact old/current full source snapshots and executable removal check are preserved in a_r2current. This records deletion, not implementation of a helper.'}]
r['issues']=[{'claim_id':'c28','status':'contradicted','details':'README_en.md:9 incorrectly locates repository/package setup in the first Notebook cell, although all266first cells are Markdown and two notebooks contain no code.','required_correction':'Describe notebooks with executable examples as preparing the repository/packages in their first code cell; do not promise a setup cell for prose-only lessons.','scope':'First full English factual review. Chinese first-code-cell wording retains the documented conditional interpretation where code exists.'}]
r['verdict']='revise'
r['checks']={'factual_accuracy':{'status':'revise','details':'Full current4file factual inventory completed; priorc05removed, new literal English first-cell assertionc28contradicted. Other grouped current claims remain supported within stated actual-execution and record-audit limits.','claim_ids':[c['id'] for c in r['claims']]},'numeric_verification':{'status':'pass','details':'Fresh current counts23chapterfiles/266lessonnotebooks/26frontsections/292total and264code-bearing notebooks; original verified328128params,8archives/1447trainingrecords/29.4MiB,public30/120+11counts andfixed90-row results reused with byte checks.','claim_ids':['c01','c07','c08','c09','c10','c20','c23']},'figure_consistency':{'status':'pass','details':'Only assigned SVG reference is README character_ids.svg. Newly rendered8784served bytes match source and prior verified bytes; personally viewed arrows/IDs/colors/reverse lookup agree. English has no referenced SVG.','claim_ids':['c02','c03']},'source_verification':{'status':'revise','details':'Previously personally inspected original authorities/code have current exactSHA comparisons; current notebook generator and real ordered cells contradict Englishc28. Prior unsupported video sentence was removed. No other reviewer judgment or secondary source inventory was substituted for originals.','claim_ids':['c28']},'limitations':{'status':'pass','details':'Actual current-source/browser/count checks are separated from unchanged priorCPU execution and fixedGPU record audits. No new optimizer updates,GPU/model downloads,anonymousassetnetworkrepeat,platforminstall,Colabcloudrun,fullMPSvalidation,readingtimeestimate or publisher approval. Natural semantic grades remain unregraded.','claim_ids':[c['id'] for c in r['claims']]}}
r['execution_limits']={'own_device':'Actual current torch2.14.1+cpu,Python3.13.5; CUDA false; installed Chromium actual current browser','current_execution':'Four fullsource snapshots, exactdependency/authority/archive/original-generation-record checks, complete ordered266Notebook inventory, current numeric recount, current8784browser/navigation/download/controls/SVG render.','previous_execution_reused':'Bounded actualCPU mechanism/defaultdryrun/one1.1Notebook results, archive repack/member audit, fixedGPU record recomputation and anonymous public metadata reconciliation from own prior successful execution; unchanged bytes verified, no rerun claimed.','training':'No current optimizer updates/model inference or GPU training. Prior formal GPU outcomes are original-record audits, not reviewer training.','models':'No model weights downloaded/loaded; prior remote publication metadata checks reused with exact fixed manifest/source/evidence identity.','data':'No new dataset download; current hash-only reread of existing eight archive bytes; previous member/repack/row audits explicitly reused.','browser':'Actual8784latest pinnedrevision, actualEnglishGitHublink; no assumed standaloneEnglishsite, searchindexJSON or Colabcloudrun.','publication':'Current technical supplement revise; no reading-minute calculation or publisher approval.'}
r['initial_report_preservation']='Original report.json d9482cdfc38766e00160b823235f819090b24d7e512c88103cf6d94a25abb5c5, prior three fullfile hashes, oldsource snapshots, c05contradiction and all previous evidence remain byte-identical. Earlier pre-transcription-correction report643499b31af9bff11021e6b163814db8e8e8efc4aef81c57d41a0cef6f4f1329also remains preserved. This round writes only round2 evidence/report; it does not rewrite the original first FINAL.'
(OUT/'report.json').write_text(json.dumps(r,ensure_ascii=False,indent=2)+'\n')
print('Genuine round2 verdict',r['verdict'],'claims',len(r['claims']),'sources',len(r['sources']),'artifacts',len(r['artifacts']))
print('ReportSHA256',sha(BASE+'report.json'))
print('Old firstFINAL unchanged',sha(str((PRIOR/'report.json').relative_to(ROOT))))
