"""Write this reviewer's initial revise report; no imported review judgments."""
import hashlib
import json
from pathlib import Path

ROOT = Path('/workspace/tiny-perceptron-vlm')
BASE = Path('docs/technical-reviews/artifacts/phase4-6_4-independent')
OUT = ROOT / BASE
REV = 'a253d1262bf5f361f9ac4e19232ae752f0ecc7a3'
original = json.loads((OUT / 'original/extraction.json').read_text())
env = json.loads((OUT / 'bounded-environment.json').read_text())
environment = {key: str(env[key]) for key in ['python', 'executable', 'torch', 'torch_git_version', 'tokenizers', 'device', 'cuda_build']}
artifacts = []


def artifact(identifier, rel, kind, description, **extra):
    path = BASE / rel
    artifacts.append({'id': identifier, 'path': path.as_posix(), 'sha256': hashlib.sha256((ROOT / path).read_bytes()).hexdigest(), 'kind': kind, 'description': description, **extra})


original_command = '.venv/bin/python docs/review-tools/section_facts.py course/chapters/06.md#6.4 --output /tmp/phase4-6_4-original-fence --execute --timeout 45'
bounded_command = '.venv/bin/python docs/technical-reviews/artifacts/phase4-6_4-independent/verify_bounded.py > docs/technical-reviews/artifacts/phase4-6_4-independent/bounded.stdout.txt 2> docs/technical-reviews/artifacts/phase4-6_4-independent/bounded.stderr.txt'
artifact('original-section', 'original/section.md', 'source_snapshot', '原始UTF-8 6.4 bytes，未正規化換行；first line129。')
artifact('original-fence-code', 'original/fence-1.py', 'code', '原fence：只計V×width和bytes，沒有模型訓練。')
artifact('original-fence', 'original/stdout.txt', 'execution', '原始fence的真正CPU stdout。', command=original_command, result='exit0；9600/32000/96000，38400/128000/384000 bytes，19200/64000/192000兩表參數。', environment=environment)
for identifier, rel, description in [('original-environment', 'original/environment.json', 'CPU原fence Python/Torch版本、裝置、guard記錄。'), ('original-extraction', 'original/extraction.json', '原始章節與fence指紋、figure inventory=0。'), ('original-execution', 'original/execution.json', 'helper的真實執行argv、exit0、時間與stdout指紋。'), ('input-provenance', 'input-provenance.json', '所有23歷史程式與8所需原輸入的hash對照；永久副本位置。'), ('bounded-environment', 'bounded-environment.json', 'CPU有界驗證的實際環境與範圍。'), ('source-acquisition', 'sources/acquisition-receipts.json', 'HTTPS原來源URL/回應/下載日期/hash及原PDF定位；沒有引用他人判定。')]:
    artifact(identifier, rel, 'source_snapshot', description)
for identifier, rel in [('prepare-code', 'prepare_evidence.py'), ('acquire-code', 'acquire_sources.py'), ('bounded-code', 'verify_bounded.py'), ('review-code', 'write_review.py')]:
    artifact(identifier, rel, 'code', '本審閱者實際執行的證據取得／驗證／報告程式。')
artifact('bounded-results', 'bounded-results.json', 'execution', '原算例變化、資料分割bytes、token長度、參數數、roundtrip與兩個有界反例。', command=bounded_command, result='exit0；所有assert通過，原分割原bytes相等，token3894/2112，参数41824/57696，固定V反例T3→1而參數不變。', environment=environment)
artifact('bounded-stdout', 'bounded.stdout.txt', 'execution', '有界驗證真正stdout；不是新訓練成績。', command=bounded_command, result='status=pass；history_not_retrained=true；原數值與有界反例核實。', environment=environment)
artifact('bounded-stderr', 'bounded.stderr.txt', 'source_snapshot', '有界驗證真正stderr，空檔。')
artifact('result-record', 'inputs/tokenizer-result.json', 'source_snapshot', '指定原GPU實驗的原JSON，含revision/code_sha256/assets/數值分母；不是本輪新成績。')
for name in ['tokenizer-bpe512.json', 'tokenizer-byte.json', 'data/manifest.json', 'data/train.jsonl', 'data/validation.jsonl', 'data/test.jsonl']:
    artifact('input-' + name.replace('/', '-').replace('.', '-'), 'inputs/experiment/' + name, 'source_snapshot', '已和原結果artifacts hash完全對上的歷史實驗輸入永久副本。')
for name in ['tinystories-train-512.jsonl', 'chinese-classical-train-365.jsonl']:
    artifact('asset-' + name.replace('.', '-'), 'inputs/assets/' + name, 'source_snapshot', '原資料包輸入永久副本，親核和原JSON assets的hash相符。')
for name in ['tiny_perceptron/model.py', 'tiny_perceptron/data.py', 'tiny_perceptron/attention.py', 'tiny_perceptron/modern.py', 'scripts/course_experiments/common.py', 'scripts/course_experiments/text.py']:
    artifact('historical-' + name.replace('/', '-').replace('.', '-'), 'historical/' + name, 'code', '由git show指定revision抽取並親核code_sha256的原實作。')
for name in ['sennrich-P16-1162.pdf', 'sennrich-P16-1162.txt', 'sennrich-P16-1162.html', 'attention-v7.pdf', 'attention-v7.txt', 'attention-v7-origin.html', 'torch-v2.11.0-sparse.py', 'torch-v2.11.0-linear.py', 'torch-2.11-tensor-attributes.html', 'tokenizers-v0.22.2-bpe-trainer.rs', 'tokenizers-v0.22.2-byte-level.rs']:
    artifact('source-' + name.replace('.', '-'), 'sources/' + name, 'source_snapshot', '親讀的原論文／官方文件／官方實作快照，provenance見source-acquisition。')


def upstream(identifier, kind, title, url, version, authority, inspection):
    return {'id': identifier, 'kind': kind, 'title': title, 'url': url, 'version': version, 'authority_reason': authority, 'accessed_on': '2026-10-05', 'verified': True, 'checked_original': True, 'inspection_note': inspection}


def local(identifier, rel, title, inspection, version=REV):
    path = BASE / rel
    return {'id': identifier, 'kind': 'repository_code', 'path': path.as_posix(), 'sha256': hashlib.sha256((ROOT / path).read_bytes()).hexdigest(), 'title': title, 'version': version, 'verified': True, 'inspection_note': inspection}


sources = [
    upstream('sennrich', 'paper', 'Neural Machine Translation of Rare Words with Subword Units', 'https://aclanthology.org/P16-1162.pdf', 'ACL 2016 published version P16-1162, pp1715–1725', 'ACL出版機構的Anthology原論文；頁首作者/標題與頁腳會議、頁碼相符，親讀原PDF轉文字。', '親讀Abstract、§1、§3、§3.1及§3.2 pp1715–1718：rare/unknown words以subwords組合；詞彙數與文本長度效率取捨；subword選擇task-specific；BPE合併頻繁相鄰符號，V=initial alphabet+merges。沒有拿其中翻譯分數泛推中文LM。'),
    upstream('attention', 'paper', 'Attention Is All You Need', 'https://arxiv.org/pdf/1706.03762v7', 'arXiv:1706.03762v7, 2023-08-02 (NIPS2017論文)', '作者提交於arXiv的原PDF；親核PDF首頁v7與原arXiv指定版本頁的作者、提交歷史與PDF href；locator index只找PDF。', '親讀§3.2.1 Eq(1) p4、§3.4 p5、Table1及§4 p6：QK^T為序列兩軸矩陣；self-attention O(n²d)；embedding與輸出pre-softmax可共享weight。不將T²解釋成全機總記憶體或固定wall-clock收益。'),
    upstream('embedding-api', 'official_source', 'PyTorch nn.Embedding原始實作', 'https://raw.githubusercontent.com/pytorch/pytorch/v2.11.0/torch/nn/modules/sparse.py', 'PyTorch v2.11.0 source tag; executed installed2.14.1+cpu', 'pytorch/pytorch官方repository的具名release tag原碼。', '親讀Embedding類docstring Attributes/Shape及__init__：weight(num_embeddings,embedding_dim)，詞表種類與特徵寬度是不同軸。也存inspect.getsource本機2.14.1+cpu並真執行確認契約相同；沒有宣稱本機是2.11。'),
    upstream('linear-api', 'official_source', 'PyTorch nn.Linear原始實作', 'https://raw.githubusercontent.com/pytorch/pytorch/v2.11.0/torch/nn/modules/linear.py', 'PyTorch v2.11.0 source tag; executed installed2.14.1+cpu', 'pytorch/pytorch官方repository原release tag。', '親讀Linear docstring及__init__：weight(out_features,in_features)，bias=False不建立bias參數；此節只算兩個V×width weight表。也真執行本機2.14.1 API而未以版本名稱混同。'),
    upstream('fp32', 'official_docs', 'PyTorch Tensor attributes: floating point dtypes', 'https://docs.pytorch.org/docs/2.11/tensor_attributes.html', 'PyTorch docs2.11, torch.dtype表', 'PyTorch官方具名2.11文件，不引用搜尋摘要。', '親讀HTML torch.dtype浮點表，原snapshot L6458–6460：float32=32-bit floating point。32bits÷8=4bytes，且本機float32 tensor.element_size()真返回4。'),
    upstream('bpe-trainer', 'official_source', 'Hugging Face tokenizers BpeTrainer', 'https://raw.githubusercontent.com/huggingface/tokenizers/v0.22.2/tokenizers/src/models/bpe/trainer.rs', 'tokenizers v0.22.2 source tag; executed installed0.23.2', 'huggingface/tokenizers官方repository具名版本原碼。', '親讀add_special_tokens、compute_alphabet、count_pairs、do_train：先加入specials/alphabet，以訓練word_counts計pair頻率，合併加入新符號直到V上限或無pair可合併。檢查小字串用本機0.23.2，版本明分；歷史saved JSON沿用不重訓。'),
    upstream('byte-level', 'official_source', 'Hugging Face tokenizers ByteLevel pretokenizer/decoder', 'https://raw.githubusercontent.com/huggingface/tokenizers/v0.22.2/tokenizers/src/pre_tokenizers/byte_level.rs', 'tokenizers v0.22.2 source tag; executed installed0.23.2', 'huggingface/tokenizers官方repository原碼。', '親讀bytes_char() 0..255、alphabet()、pre_tokenize與decode_chain：完整byte映射、add_prefix_space可改原字串，decoder先合bytes再from_utf8_lossy。無損還原需完整alphabet、未加改寫normalizer/prefix、完整編碼序列；任意LM生成或切斷UTF8並無保證。'),
    local('historical-text', 'historical/scripts/course_experiments/text.py', '指定歷史run_tokenizer/_BPE/片段分割原實作', '親讀L348–515及_deduplicate_text/_save_splits：raw各前96篇，完整篇先family切側；再≤256 bytes UTF8安全截；train153學BPE；19 validation/20 test不學merges；ordinary token長度不含BOS/EOS；new_lm width32,layers1,max_length384；400step每batch8相同原文schedule。'),
    local('historical-model', 'historical/tiny_perceptron/model.py', '指定歷史ModelConfig/TinyLM', '親讀L14–27、L53–66：V/d/layers/max_length；position384×32；untied默認False、output無bias；參數量由sum(numel)記錄。親讀配套attention/modern：q,k,v,out無bias，FFN32→128→32有bias，三個LayerNorm。'),
    local('historical-data', 'historical/tiny_perceptron/data.py', '指定歷史ByteTokenizer與special IDs', '親讀L11–29：八個SPECIALS IDs0..7、256byte加offset8、decode還原完整bytes。不是256總V，普通文字不含邊界標記。'),
    local('result-record', 'inputs/tokenizer-result.json', '原tokenizer GPU實驗JSON', '親讀revision a253d126…、原device cuda/seed42/Python3.13.3/Torch2.14.1+cu126、code_sha256、assets、data/runs/validation_text_token_lengths/parameters。原所有相關输入與23程式hash由程式逐個核實；這是既有實驗紀錄而非本輪training。'),
    local('original-code', 'original/fence-1.py', '6.4原始fence', '亲讀原fence：width32，V300/1000/3000，純整數乘法與print；不建立模型、不算loss、不更新參數。', '6.4原始section SHA ' + original['source_sha256']),
    {'id': 'original-execution', 'kind': 'execution', 'title': '6.4原fence CPU真執行', 'verified': True, 'artifact_id': 'original-fence'},
    {'id': 'bounded-execution', 'kind': 'execution', 'title': '本審閱者有界CPU核對', 'verified': True, 'artifact_id': 'bounded-results'},
    {'id': 'table-derivation', 'kind': 'derivation', 'title': '兩表與歷史模型參數公式', 'verified': True, 'details': 'input_weight=Vd；FP32 input bytes=4Vd；untied無bias output=Vd，所以兩weight表=2Vd。width32,layers1,heads1,max_length384：position=384×32=12288；attention4×32²=4096；FFN(32×128+128)+(128×32+32)=8352；3 LayerNorm各2×32=192。固定非詞表24928；V264兩表16896+24928=41824，V512两表32768+24928=57696。差2×(512−264)×32=15872；總普通tokens除19，3894/19=204.947368≈205，2112/19=111.157895≈111。'},
]


def evidence(source_id, locator, supports):
    return {'source_id': source_id, 'locator': locator, 'supports': supports}


claims = [
    {'id': 'piece-size-versus-V', 'kind': 'concept', 'statement': '原開場：「大token可能讓句子用較少格，也需保存更多輸入特徵與輸出候選。」', 'location': 'course/chapters/06.md:131，6.4開場第一句', 'scope': '前半可能減T成立；後半須V增加才成立。token字符串較長本身不能推出詞表項數或V×width表格更多。', 'status': 'needs_revision', 'evidence': [evidence('sennrich', '§3.1–3.2 p1717', 'BPE添加合併時V增加；詞彙大小與文本長度是不同變量。'), evidence('embedding-api', 'Embedding Attributes及__init__', '保存的表格大小由V與d決定，不由token拼寫長度決定。'), evidence('linear-api', 'Linear Attributes及__init__', '輸出weight亦由V與d決定。'), evidence('bounded-execution', 'bounded-results.json fixed_v_piece_length_counterexample', '兩套完整256-byte+4合併V都260；abcde的T3→1、最大token2→5bytes，weight成本相等。')], 'artifact_ids': ['bounded-results', 'bounded-code']},
    {'id': 'table-cost-and-exercises', 'kind': 'numeric', 'statement': 'width32的輸入V×32、FP32每數4bytes、無共享且無bias兩weight表2V×32；V300/1000/3000對應9600/32000/96000數、38400/128000/384000bytes與19200/64000/192000兩表數。width64或第一項V600對應翻倍，但寬度軸與詞表種類軸意義不同；程式只是成本計算。', 'location': 'course/chapters/06.md:133–149（原fence及算例、練習）', 'scope': '只有weight數值payload，包含V中的所有ID；沒有把它當整模型/整機、gradient、optimizer history、activations、序列計算預算。output無bias契約和本課模型相符。', 'status': 'verified', 'evidence': [evidence('embedding-api', 'Embedding docstring Shape/Attributes, __init__ weight', '逐項核V為行數、width為特徵列數。'), evidence('linear-api', 'Linear weight(out_features,in_features), bias=False', '逐項核輸出表V×width與無bias約定；未共享則加第二表。'), evidence('fp32', 'torch.dtype floating point table, snapshot L6458–6460', 'FP32=32bits=4bytes，單位是十進制bytes，沒有聲稱MiB。'), evidence('original-execution', 'original/stdout.txt三行', '原fence三組輸出真正執行一致。'), evidence('bounded-execution', 'original_and_width_variation、vocab_600_variation', 'width64與V600變化逐項assert核翻倍，真torch float32 element_size和weight.numel一致。'), evidence('table-derivation', 'Vd/4Vd/2Vd公式', '計weight payload且排除其他budget項。')], 'artifact_ids': ['original-fence', 'original-fence-code', 'bounded-results'], 'verification': {'method': 'executed', 'expected': '3組原數值吻合；width64各翻倍；V600首項為19200數/76800bytes/38400兩表數。', 'observed': '原stdout與全部assert通過；本機nn.Embedding shape[V,d]、nn.Linear shape[V,d]、element_size=4。', 'details': '原fence由section_facts worker真執行；有界驗證實例化FP32表並逐項核numel，不用模型訓練。', 'tolerance': '所有整數與shape精確相等，無浮點容忍差。'}},
    {'id': 'matching-merges-and-attention', 'kind': 'concept', 'statement': '新增合併項剛好覆蓋當前原文時，可能減少token序列長度T，完整自注意力的兩個序列軸T×T因此變小。', 'location': 'course/chapters/06.md:145，成本另一邊是實際T', 'scope': '本課manual dense self-attention完整[B,H,T,T]矩陣；固定batch/heads/width，談attention矩陣大小與運算，不宣稱全模型wall-clock或總記憶體必定減少，也沒有將所有19篇合計T當成一個attention序列。', 'status': 'verified', 'evidence': [evidence('sennrich', '§3.2 p1717', 'BPE以常見pair建立合併，匹配文字以更少符號表示。'), evidence('attention', '§3.2.1 Eq(1) p4、Table1 p6', 'QK^T的兩序列軸，各單篇長T時矩陣T×T，密集attention複雜度O(T²d)。'), evidence('bounded-execution', 'fixed_v_piece_length_counterexample與per_record_lengths', '微小同文T3→1能見合併減長機制；歷史長度是逐篇後再求和，不能把3894²當本實驗attention成本。')], 'artifact_ids': ['bounded-results']},
    {'id': 'coverage-heldout-and-roundtrip', 'kind': 'concept', 'statement': '字表變大不保證當前中文切得短；主要英文訓練產生的合併可能覆蓋不到中文。應對同一未參與詞表學習的原文記實際token數、完整還原與模型品質。', 'location': 'course/chapters/06.md:145，中文字表、未見原文與還原核對', 'scope': '不將較大V當全語種長度保證。完整roundtrip依ByteLevel完整alphabet、無改寫normalizer/prefix、完整encoded普通文字序列；不聲稱任意模型生成ID或截斷多byte文字也可還原。示範只支持機制與已存片段的還原，模型品質留6.5。', 'status': 'verified', 'evidence': [evidence('bpe-trainer', 'compute_alphabet、count_pairs、do_train merge loop', '新增合併來自訓練語料pair頻率，而非自動改善所有字串。'), evidence('byte-level', 'bytes_char/alphabet/pre_tokenize/decode_chain', '完整256byte映射和整序列decoder；還原規則條件由完整工具組合決定。'), evidence('bounded-execution', 'bounded_noncoverage_counterexample', '自備兩句英文字串訓練V264/300，actual264/300，但同一中文emoji文本均22tokens且完整還原；存在反例支持不保證，不能推一般中文壓縮率。'), evidence('historical-text', 'run_tokenizer L412–440及_BPE L354–371', '正式保存資料先按完整篇分侧，僅153train學merges；validation19/test20不參與，普通內容remove added_tokens維持角色邊界。'), evidence('bounded-execution', 'split_reconstruction與historical_saved_tokenizer_recomputation', '從固定原輸入重建三側原bytes，family互斥，192篇saved byte/BPE往返全部完全相等。')], 'artifact_ids': ['bounded-results', 'input-provenance']},
    {'id': 'rare-pieces-and-no-universal-V', 'kind': 'concept', 'statement': '罕見大token直接出現的學習例子可能少；較細片段能在不同詞中復用，但序列可較長。詞表大小需按任務、資料、模型品質和成本選擇，沒有這個兩預算實驗能提供的通用最佳V。', 'location': 'course/chapters/06.md:147，罕見大token及通用V', 'scope': '「很少受訓」指少直接觀察例子與少input-row選取，不解讀成未出現的dense output rows完全沒有softmax梯度。片段共享是組合機制，不是所有切詞都增品質；最佳V還受語種/模型/資源影響。', 'status': 'verified', 'evidence': [evidence('sennrich', 'Abstract p1715；§3及§3.1 p1716–1717', 'rare/unknown words以共享subwords表示並能產生未見詞；最佳subword choice task-specific；文本長度和V各有成本。'), evidence('embedding-api', 'Embedding input indices、weight Shape及forward契約', '輸入表以實際ID查行，罕見行直接例子少；沒有用這點推dense輸出無梯度。'), evidence('bounded-execution', 'rare_row_scope', '短反傳中未觀測input row梯度0、同ID dense output row仍有非0梯度，界定原文支持範圍。')], 'artifact_ids': ['bounded-results']},
    {'id': 'historical-19-record-tradeoff', 'kind': 'empirical', 'statement': '指定歷史byte/BPE實驗在同19篇validation的普通文字token由3894降2112，均值約205降111；byte256+8specials總V264，BPE總V512；width32/layers1模型總參數41824增57696。開始/結束標記未納入普通token計數。', 'location': 'course/chapters/06.md:147及154，主文與補充原始紀錄', 'scope': '原a253d126… GPU結果核對，不是本輪新training。固定篇章/片段与400step原文曝光相同，但兩模型參數、有效token、FLOPs和詞表不同；未由T短或參數多單独斷言整機更省、品質更好或推薦最佳V。', 'status': 'verified', 'evidence': [evidence('result-record', 'results.data、runs.{byte256,bpe512}.validation_text_token_lengths/parameters/vocab_size_including_8_specials，code_sha256/assets/artifacts', '原分母与各逐篇長度、V、參數量均可追到指定版本與原輸入hash。'), evidence('historical-text', 'L412–440、L457–463、L491–514', '153/19/20完整篇分側、UTF8≤256bytes，V包含specials，width32/layer1/max_length384，普通文字不含BOS/EOS，按同raw schedule400step。'), evidence('historical-model', 'ModelConfig及TinyLM L14–27、L53–66', '原模型不共享兩V×32表，position384×32及其他固定層；兩模型差2×248×32。'), evidence('historical-data', 'ByteTokenizer L11–29', '256普通byte ID和8special ID=264，還原完整原文。'), evidence('bounded-execution', 'split_reconstruction、historical_saved_tokenizer_recomputation、matched_schedule', 'original split bytes精確相同；保存tokenizer重算lengths；fresh historical CPU模型只初始化/count，不載入權重/訓練；普通3894/2112、target3913/2131。'), evidence('table-derivation', 'means與historical parameter公式', '3894/19≈205，2112/19≈111；非詞表24928+兩表给41824/57696。')], 'artifact_ids': ['result-record', 'bounded-results', 'input-provenance'], 'verification': {'method': 'executed', 'expected': '原19筆tokens3894/2112；V264/512；平均四捨五入205/111；參數41824/57696；差15872。', 'observed': 'saved tokenizer重算逐筆與原JSON完全一致，模型參數精確吻合；mean204.94736842105263/111.15789473684211；8所需輸入hash與23歴史codehash全一致，原分割bytes完全相等。', 'details': '本輪親核正式JSON+git show历史code与固定assets，运行AST抽出纯split/dedup/prefix/_BPE helpers，不run_tokenizer、不訓練tokenizer原語料、不fit、不model checkpoint。仅微小自備字串trained tokenizer反例。', 'denominators': {'source_assets': '固定TinyStories512與中文古詩365原包各取前96篇，共192篇', 'splits': '153train、19validation、20test；先完整篇family分侧，再每篇≤256 UTF8 bytes', 'validation': '19篇共同原片段，raw UTF8 bytes3894，普通token3894/2112不含BOS/EOS；next-token targets3913/2131含每篇EOS', 'training_schedule_original': '400step×8篇/batch；共同raw schedule SHA0198fcf909d8b754ddc3a7ffbf6aae3f2b483f583295f0a0aeea6b614a54ecf2，raw bytes exposure664759 each', 'model_config': 'width32/layers1/heads1/max_length384/untied/output biasFalse；V264/512；original devicecuda，CPU只重算未訓練config參數'}, 'tolerance': 'hash/bytes/token/V/parameters精確相等；均值按一般最近整數四捨五入，误差≤0.5token/篇。'}},
]

issue = {'id': 'I-6.4-1', 'status': 'open', 'severity': 'substantive_condition_missing', 'claim_ids': ['piece-size-versus-V'], 'location': 'course/chapters/06.md:131', 'original_quote': '大token可能讓句子用較少格，也需保存更多輸入特徵與輸出候選。', 'problem': '無條件把token字符串長度與表格成本連起來；後文正確V×width公式需要首句也說V增加這個條件。固定V=260兩個BPE可把abcde從3tokens切成1token且所有V×32表成本不變。', 'evidence': 'bounded-results.json fixed_v_piece_length_counterexample；PyTorch Embedding/Linear shape原契約；Sennrich§3.2 V=alphabet+merge項。', 'impact': '初學者可能誤以為只把每個token內容變長就必需更多參數，混淆V（種類數）、width（特徵寬度）、T（實際序列格數）。', 'recommendation': '首句改成「增加詞表、加入更多合併項，可能讓句子用較少格，也需保存更多輸入特徵與輸出候選。」或等效明示V增加的條件；不用改已核實數字。', 'resolution': '待協調者改稿後，本審閱者親讀新版本並重新freeze/fence/checker；目前不能pass。'}
report = {'schema_version': 1, 'review_stage': 'technical', 'lesson_id': '6.4', 'source': 'course/chapters/06.md#6.4', 'source_sha256': original['source_sha256'], 'figure_sha256': {}, 'reviewer_task': '/root/phase4_factual_coordinator/factual_6_4', 'reviewer_context': 'fresh', 'author_tasks': [], 'verdict': 'revise', 'review_date': '2026-10-05', 'review_scope': {'independence': '本節全新獨立context；沒有讀任何舊技術/讀者報告或他人判定、未spawn。來源locator只尋immutable原PDF並自行核authority/version/原段。', 'actually_read': ['course/chapters/06.md#6.4完整原bytes（129起31行，無圖）', '必要前置course/chapters/06.md#6.3完整文字與19篇背景', 'course/training.md#T.4：長recipe契約讀取，不執行下載/長訓練', '四份指定review方法/checker/helper完整親讀', '現行tokenization.py、歷史text.py run_tokenizer/_BPE/split helpers、historical model/data/attention/modern相關契約', '原JSON/code_sha256/assets與8個已存所需輸入；原紙/官方來源具體讀取範圍逐source記錄'], 'chapter_intro': {'status': 'not_applicable', 'reason': '6.4不是章首第一節，不需另交章導言指紋。'}, 'figures': {'status': 'not_applicable', 'reason': '親讀本節並核原helper抽取SVG=0，沒有引用圖像/軸/箭頭；表格公式與逐行文字足以回答此節所需成本比較，無圖可render/view。'}, 'execution': '原Python fence真CPU執行；width/V短變化、原saved tokenizer token長度、原split bytes重建、historical config fresh CPU參數計數；兩個微小自備字符串BPE機制反例與短gradient限定。', 'not_executed': '未重跑任何原課程GPU訓練、長recipe、資料/模型下載或checkpoint評估；沒有新語言模型成績。'}, 'artifacts': artifacts, 'sources': sources, 'claims': claims, 'issues': [issue], 'checks': {'factual_accuracy': {'status': 'revise', 'details': '其餘主張已逐source/原code/實跑核實；首句缺少V增加條件，需修訂才能pass。', 'claim_ids': [claim['id'] for claim in claims]}, 'numeric_verification': {'status': 'pass', 'details': '原fence及width64/V600逐項精確吻合；19篇tokens/均值/ordinary與EOS分母、V264/512、41824/57696與差15872完全核實。', 'claim_ids': ['table-cost-and-exercises', 'historical-19-record-tradeoff']}, 'figure_consistency': {'status': 'not_applicable', 'details': '本節沒有圖；親核section.md及原extraction引用圖0，沒有圖解座標或render驗證待做。', 'claim_ids': []}, 'source_verification': {'status': 'pass', 'details': '所有概念有親讀原論文或official docs/source；版本/authority/實讀locator/support明列，來源URL真正HTTPS取得與PDF版本核對，未讀旧review判定。', 'claim_ids': [claim['id'] for claim in claims]}, 'limitations': {'status': 'pass', 'details': '保持原GPU歷史實測身分；same raw19篇/400step曝光非same tokens/parameters/FLOPs；attention T²只谈单篇dense矩陣；rare rows少正例不等于output无gradient；roundtrip需要完整規則与encoded字串，沒有宣稱生成能懂句意。', 'claim_ids': ['matching-merges-and-attention', 'coverage-heldout-and-roundtrip', 'rare-pieces-and-no-universal-V', 'historical-19-record-tradeoff']}}}
(ROOT / 'docs/technical-reviews/6.4.json').write_text(json.dumps(report, ensure_ascii=False, indent=2) + '\n')
(OUT / 'initial-review.json').write_text(json.dumps(report, ensure_ascii=False, indent=2) + '\n')
print(json.dumps({'verdict': report['verdict'], 'source_sha256': report['source_sha256'], 'claims': len(claims), 'sources': len(sources), 'artifacts': len(artifacts), 'open_issue': issue['id']}, ensure_ascii=False))
