from pathlib import Path
import json,hashlib,re
ROOT=Path('/workspace/tiny-perceptron-vlm')
OUT=ROOT/'docs/reader-reviews/artifacts/natural-v4-supplemental/training-course'
BASE='docs/reader-reviews/artifacts/natural-v4-supplemental/training-course/'
SOURCE=ROOT/'course/training.md'
raw=SOURCE.read_bytes(); fullsha=hashlib.sha256(raw).hexdigest()
snapshot='training.3e8fe04b5d84b0dfd2c7a0c8b45c41532d20818ddbe6397a6097a365e0cdac4d.md'
assert raw==(OUT/snapshot).read_bytes()
text=raw.decode();lines=text.splitlines()
# Preserve all lesson code blocks exactly; inventory records reading and execution limits, not technical verification.
blocks=[];current='intro';i=0
while i<len(lines):
 if lines[i].startswith('## T.'):current=lines[i].split()[1]
 if lines[i].startswith('```'):
  lang=lines[i][3:];start=i+1;j=i+1
  while j<len(lines) and not lines[j].startswith('```'):j+=1
  snippet='\n'.join(lines[i+1:j])+'\n'
  blocks.append({'ordinal':len(blocks)+1,'section':current,'language':lang,'source_line_start':i+1,'source_line_end':j+1,'raw_code':snippet,'sha256':hashlib.sha256(snippet.encode()).hexdigest(),'read_completely':True,'execution':'Only T.2 text and sft invocations in its three-line bash block executed, with existing .venv interpreter. All remaining commands/snippets read and explained, not executed under this assignment.' if current=='T.2' and lang=='bash' else 'read, not executed'})
  i=j
 i+=1
(OUT/'command-read-inventory.json').write_text(json.dumps(blocks,ensure_ascii=False,indent=2)+'\n')
prereqs=json.loads((OUT/'prerequisite-read-receipt.json').read_text())+json.loads((OUT/'prerequisite-additional-read-receipt.json').read_text())
figs=json.loads((OUT/'figure-render-receipt.json').read_text())+[json.loads((OUT/'figure-additional-render-receipt.json').read_text())]
figure_notes={
 '1.5':'我從「目前是貓」列看到七個下一字欄。看那欄橘框是3與3/9，其他是1與1/9，底部說初始1再加兩次觀察。分母9是這一列，沒有把全表總數拿來除。文字、數字、框線可辨。',
 '7.17':'一般文章的箭頭先到共用預訓練底座，再分叉成客服、程式、圖文三條；每條有自己的資料和更新後評測。底部提醒能力由新題驗證，圖沒有把箭頭當成成績保證。',
 '7.18':'三張上方材料卡分別是一份好回答、兩篇回答比較、作答後得分。下方對應SFT、DPO、PPO等方法；比較卡還可先教評分員再評新回答。真人與程式回饋來源另外標示，沒有要求逐項全跑。',
 '12.8':'三欄讓jackson20段訓練、nicolas20段驗證5/20、theo20段測試3/20分開。兩邊EOS都是20/20但辨識仍弱。下方8kHz4591點到16kHz9182點，時長同0.573875秒；插值不增加4kHz以上資訊。',
 '13.1':'同一「只回數字2+2」分到A4與B4加筷子比喻。右邊A數字和格式都通過，B內容正確但格式未過；圖清楚把這次任務條件放在排序之前。',
 '17.2':'兩列0.7、1.2依序除0.5、取最近整數1或2、乘回0.5得到0.5或1.0。最右不同於最左，下方兩項差0.2，能看見量化有損。',
 '17.8':'第一碼綠色虛線去右側低四位，第二碼橘線去左側高四位；-8與-1加8變0000與0111，合成01110000即112。第二例0與1合成152。交叉箭頭和底部順序說明一致。',
 '18.6':'左右都是二維但教師ID0是貓、學生ID0是狗。綠線貓與橘線狗交叉，按身份重排學生[ID1,ID0]得到[0.8,0.2]；同大小不代表同欄意思。',
 '18.5':'三條完整長度都100%，固定色彩對候選4、3、5。T從1到2到4，第一名4仍最大，但3與5份量增加；93.62/4.66/1.71到54.34/25.67/19.99的標示與這個意思一致。'}
for f in figs:
 f['personally_rendered']=True;f['personally_viewed_with']='functions.exec → tools.view_image, then visible image inspection';f['own_view_note']=figure_notes[f['section']]
(OUT/'figure-view-notes.json').write_text(json.dumps(figs,ensure_ascii=False,indent=2)+'\n')
training_browser=json.loads((OUT/'browser-training-receipt.json').read_text())
guides=json.loads((OUT/'browser-guide-receipt.json').read_text())
nav=json.loads((OUT/'browser-remaining-navigation-receipt.json').read_text())
scroll=json.loads((OUT/'browser-code-scroll-receipt.json').read_text())
cpu=[]
for task in ['text','sft']:
 stdout=OUT/f'cpu-T2-{task}.stdout.txt';stderr=OUT/f'cpu-T2-{task}.stderr.txt'
 records=[json.loads(x) for x in stdout.read_text().splitlines()]
 cpu.append({'command':f'.venv/bin/python scripts/train.py --task {task} --device cpu','cwd':'/workspace/tiny-perceptron-vlm','bounded_invocation':f'OMP_NUM_THREADS=1 MKL_NUM_THREADS=1 timeout 45s .venv/bin/python scripts/train.py --task {task} --device cpu','exit_code':0,'stdout':BASE+stdout.name,'stdout_sha256':hashlib.sha256(stdout.read_bytes()).hexdigest(),'stderr':BASE+stderr.name,'stderr_empty':stderr.read_bytes()==b'','prediction_saved_before_run':BASE+'cpu-predictions-before-execution.json','original_lesson_command_excerpt':BASE+'cpu-original-T2-command-excerpt.md','mode':records[1]['mode'],'task':records[1]['task'],'device':records[1]['device'],'effective_tokens':records[0]['effective_tokens'],'loss':records[0]['loss'],'grad_norm':records[0]['grad_norm'],'interpretation':'吻合事前預測，有限loss和正梯度只證明一批前向／反向通路；模式明示未更新權重。沒有把它當成答對率或训练成功。'})
(OUT/'cpu-execution-receipt.json').write_text(json.dumps(cpu,ensure_ascii=False,indent=2)+'\n')
section_summaries=[
 {'section':'intro','lines':'1–8','own_summary':'這是第1–19章動手時的操作橋樑，先讀任務相關正文再用指令。根目錄有pyproject.toml；W.1教環境和執行。本頁的小CPU機制檢查、自己的訓練配方、課程固定版本實測有不同用途。第20章另用已有圖文能力底座、.venv-natural及專用資料，試成品直接20.2。'},
 {'section':'T.1','lines':'9–39','own_summary':'先定義一件能判對錯的任務，再分資料家族。A與B同屬red:square:low所以一起教，不能拿B算新能力；C留作新家族應答circle。對話messages:user是題、assistant是理想答，family是切分單位；故事用text。512故事和365古詩是小型樣本，留出是自己的切分。50服飾圖按每類3/1/1成30/10/10；60錄音按說話者20/20/20。8kHz到16kHz需要實際重採樣，不能只改檔名。'},
 {'section':'T.2','lines':'40–74','own_summary':'text、sft、vision各用CPU走一次batch；沒有--train就前向、反向但不更新、不存訓練權重。loss是平均猜錯代價，grad_norm是全部梯度合計長度，正值不表示每格都有梯度。SFT只有回答與EOS計分；預設有效位置由text111變sft8。vision null是未統計目標數，不是零目標。NaN或Infinity不能算通過。'},
 {'section':'T.3','lines':'75–218','own_summary':'接字表看1字；固定窗口MLP拼接幾個前文向量再混合。12篇中文規則短文先去重、按文件切9/1/2，字表只看train。先存未更新JSON，再--train200步、存匹配模型，最後一次更新後重算代價；last_batch_loss_before_update不可混用。比較程式讀真實前後報告，負change是代價下降。四模型不是等參數；5字MLP練習代價最好，但驗證/test都比3字差。生成是否合格式和逐字loss各自看。簡單模型用infer_simple，不與TinyLM互換。公開30組120份存檔按模型卡匹配；HF下載、text_foundation推論與完整學生核對我只讀命令未執行。'},
 {'section':'T.4','lines':'219–438','own_summary':'toy-text是9/1/2篇，attributes-sft是45/5/10題、每家族五問，家族9/1/2。prepare_data先產生manifest及三側JSONL，train.py讀指定train不另切。先保存step0模型才可評估前後生成；dry-run不存檔且steps0不可用。CPU width32一層200/500步與L4 width64兩層600/900步正式實報分開。故事409/51/52、古詩292/36/37，各自新模型和800步；BPE模型必須配自己的tokenizer指紋。evaluate完整JSON才含samples，mean_token_nll、effective_tokens、內容match、completed_match、EOS、選題及跳過各有分母。比較程式assert固定data/split/有效目標/無skip/題順序，失敗應修評估條件。resume才恢复optimizer、步數和隨機狀態，steps是整段總數且不能改原排程再說逐步一致。'},
 {'section':'T.5','lines':'439–529','own_summary':'風格、內容真值、格式、安全要分欄。產生style/safety、SFT各500步只是探索；samples row0要回同一JSONL第一行找user題。完整匹配不替代人工風格規則。正式style從新加法content起點開始，八/七新題均零答對，條件式185/28/27題只三日期題完整匹配。盒子True/False是玩具權限，不含真秘密；缺權限澄清需另加人工題，拒絕多並非成功。正式兩版17題15/17與16/17，但換措辭全錯且6不是所需澄清。LoRA僅更新9504補充參數，141568基模凍結仍計算；匹配原基模指紋，合併模型不能再疊一次adapter。CPU示例風格可變但兩者把4答3。'},
 {'section':'T.6','lines':'530–644','own_summary':'先給圖片/聲音編碼器有標準答案的小任務，CLI兩保留題全對才繼續；有檔案和300步不保證過關。再以attributes文字底座接encoder，projector只開接頭、partial開首末文字塊、none全开；沒參與輸入的零件不會因此有梯度。原生multimodal-v1保留恢復狀態，resume時不再重新載encoder；文字保留評估取model.language。固定encoders→projector→vqa另有排程和partial範圍，不能套CLI成績。真實服飾/录音重新入口、低測試成績、縮16×16和重採樣限制各列。OCR需自己的read-digits訓練；none/blank/shuffle同題同模型，donor_row找換入圖，match仍對原答案所以需要另人工看是否讀到換入內容。'},
 {'section':'T.7','lines':'645–700','own_summary':'偏好是一題兩候選，chosen/rejected由真值或明定規則選，不是兩道不同題。DPO保留固定起點reference，更新policy；參考不是正確性老師。T.5 style.pt的200步探索和正式content.pt的兩beta各250步分開。候選絕對排序、相對參考差距提高、自由生成匹配是三件事：4+2候選6贏7仍可能生成8。PPO選讀例子有獎勵模型、價值估計員和選擇模型，但只選預寫卡且標籤來自作者規則，所以不是語言模型RLHF。19章生成DPO與選卡權重獨立；學生用DPO支線教師，不能稱推薦聯合成品的縮版。'},
 {'section':'T.8','lines':'701–809','own_summary':'先固定資料/步數/種子，再改正規化或MoE一條條比較，成本和留出品質並排。Dense用整套零件，4專家top2只啟部分；同寬非同儲存或算力。正式modern六組409/51/52故事各240步，MoE七組另180步，代理不是FLOPs且未等參數。現有實測中代價降或多參數都不保證合格故事，更不保證快。效率以SFT来源比較MHA/GQA、累積、重算、SDPA，不是故事模型；packed/padded目標改為短文字，不能當原問答保留。記憶體只計PyTorch tensor配置，速度範圍各自列。Flash_probe只測QKV固定核心和精度，不訓練權重；AMP各200次嘗試与成功/skip分列。'},
 {'section':'T.9','lines':'810–841','own_summary':'先同一SFT底座續120次更新再分別转4/8位，或quantize.py另独立转换而不更新，不能套同成績。只動13個Linear權重，查表/Norm/bias/scale仍浮點，所以参数141568不變。tensor bytes566272→168736/226336與私有file bytes是不同量。三版測試同6/10、69目標且EOS10/10，驗證FP32/4/8是2/1/2，不能宣稱全部新題保持。推論先還原FP32，檔案小不保證記憶體或速度較少。QAT是模擬誤差與近似梯度，需要另有支援格式/硬體才低位元加速。'},
 {'section':'T.10','lines':'842–895','own_summary':'學生小由架構决定，教师信号是否有帮助用同架構CE比较。需要SFT、条件风格、MoE三来源model和原dataset；全部11学生支线共3900更新，CPU也完整，非短check。屬性宽16/32学生各一层13744/33632参数，CE真值、teacher_hard实际回答、CE+KL分布各400步，词表264ID和同前文有效回答位置对齐。T=2是双边logits除2后softmax，KL(p||q)按教师p加权，helper只乘一次T²=4；生成仍greedy不是T2抽样。十题宽32 CE/KL均4/10，单题改对并非整体赢；packed4降3/10。风格都3/27、MoE KL NLL较低但生成仍重复；GSM8K200题仅2完整可放且都失败，不是完整benchmark。多模态教師GPU完整來源不能改CPU短来源后套分数；四学生图/音干预说明保留能力仍未全过。'},
 {'section':'T.11','lines':'896–936','own_summary':'紀錄要接同一來源模型、validation及manifest指紋、程式版本、命令、事先判準和結果。假想8/4位表明標為未實測；同答對數也需逐題才能知道是不是同題正確。4位60000bytes且3/5時，少20000bytes但匹配0.6−0.8=−0.2，不符合保住答對數。RAG要看 paired 公告/来源变化，Tools要完整請求→真正执行→回填→最終答，Reasoning的候選集合命中、多數决、合法步驟不同分母；有限REINFORCE按動作而非自回歸token算。備份檔存在不代表存了baseline/抽題状態可逐次續訓。'}]
checks=[
 {'name':'background_and_links','verdict':'pass','own_assessment':'頁首明定先讀正文、根目錄與W.1；每節相關先備可點到需要的背景。我實際完整補讀29個明示段落，未靠搜尋隱藏說明。第20章另環境/資料/成品分工由頁首和三份指引開場交叉說清楚。瀏覽點進確認功能，不把可達當完整guide已讀。'},
 {'name':'terminology_and_symbols','verdict':'pass','own_assessment':'loss/NLL是有效目標負log機率平均，match是回答內容ID，EOS是正常結束；batch數、篇數/家族/目標數/參數/bytes不混用。--steps是總排程還是新階段步數在相應位置說清楚。CE、KL、T及T²在顯式18.6→18.8→18.5鏈補足；RMS/MoE等選項能按正文入口再學，其具體運算非本頁要求重推。'},
 {'name':'examples_and_figures','verdict':'pass','own_assessment':'A/B同家族與C新家族、5字訓練最好卻新題較差、答案3但風格改變、錯配圖對donor而非原答案、縮檔却品質下降，讓抽象限制都有具體對照。所有示意或假想數字均與實測分開。本頁直接SVG為0；需要的29段包含9張SVG，均親自從原字節render並view_image，圖中文字/箭頭/數字能支持自己的理解。'},
 {'name':'programs_and_commands','verdict':'pass','own_assessment':'55個程式/命令/JSON區塊全部讀完。T.3前後比較、T.4manifest與assert比較程式有逐步解說，能說清輸入檔和输出報告；checkpoint格式與續訓用途各明示。CPU/GPU正式配方與教學操作不混抄。實際執行只T.2text/sft，預測、原文命令、stdout/stderr/exitstatus已保存；其他全部標為未執行。瀏覽實際橫捲一条長命令CODE區至scrollLeft688，右側--output及重導向能看到。'},
 {'name':'exercises_and_workflow','verdict':'pass','own_assessment':'每節有先預測、實際或紙上核對、保存和如何判成功/失敗。可不用訓練做T.1分家族、T.3選模型、T.5拆內容格式比喻、T.7選5而非6、T.11假想4位品質下降。若真的動手，有manifest/固定題/分母/skip/原始ID/EOS/成本/續訓限制可查。大段GPU支線較密集，但頁首不要求初開網站全跑、T.7有明示選讀，讀者可循任務選路。'}]
issue={'id':'training-navigation-number-visibility','severity':'nonblocking','status':'open','location':{'document':'course/training.md','source_headings':['T.1–T.11'],'page':'http://127.0.0.1:8769/training.html','rendered_elements':'h2及右側目錄','example_source_lines':[219,701],'evidence':[BASE+'training-top.png',BASE+'T-4-browser-final.png',BASE+'T-8-browser-final.png',BASE+'browser-training-receipt.json']},'own_issue':'Markdown的章節標題含T.1–T.11，實際網頁標題和右側目錄只顯示題目文字。正文很多地方用T.4或T.8稱呼，所以按編號找節時不能直接從可見目錄對上。點正文連結和11次目錄跳轉都成功，故沒有阻止閱讀。','proposed_correction':'在訓練頁的可見h2和目錄保留T.1–T.11編號，或提供可見的編號與題名對照；保留現有可用anchor。'}
report={
 'reviewer_task':'/root/v4_review_coordinator/reader_whole_training_course',
 'fresh_context':{'reader_role':'具高中／大學基礎數學、第一次遇到這個專案的讀者','review_type':'READABILITY ONLY, independent whole-document supplemental read','old_review_content_read':False,'author_reasoning_read':False,'expected_verdict_consulted':False,'source_or_checker_implementation_inspected':False,'agents_spawned':False,'product_or_environment_configuration_edited':False,'previous_report_existed':False,'prior_report_preserved_unread_if_present':True,'role_contract':'outputs/natural-v4/review-plan/supplemental-reader-contract.md','required_environment_skill_read':'cloud-environment-onboarding:setup; existing environment used, no install/config changes'},
 'actual_assignment':'Repo /workspace/tiny-perceptron-vlm。獨立fresh whole-document READABILITY ONLY：完整 course/training.md（全部936行與intro/T1–11，請自己核current行數）＋真正browser http://127.0.0.1:8769/training.html 必要route/navigation/3guide入口dest。先讀 /workspace/tiny-perceptron-vlm/outputs/natural-v4/review-plan/supplemental-reader-contract.md 唯一role/schema/tools，不舊review/authorreason/expectedverdict。高中/大學基礎數學首次讀者逐段/表/命令/完整各節文字都讀，必要explicitprereqs若needed再完整相應段落，不search隱藏解釋。保存rawfullfilehash/snapshot/readorder、自述summary/5checks/ownissues/verdict；actual所需SVG真render+view_image。existing.venv Playwright Chromium executable_path=/usr/bin/chromium真browser，保存URL/screens/heading/navigationclick與用途；HTMLsource-only不是browser。currentpreview未發布、未finaltimes、尚無CPUoutputs；root正在真正實跑266kernels，未來actualexecutedexport需原owner必要reinspection，不能futureplanclosure。禁止install/download/GPU長訓練或重跑整書，只必要boundedofflineCPU可（保存預測+輸出/原碼）。不source/checker/Git/time、不spawn。只写自己 docs/reader-reviews/artifacts/natural-v4-supplemental/training-course/report.json與smallownread/browser/CPU證據，不虛構lessonID/別人identity。真正FINAL附verdict/fullsourceSHA/figmap/remainingissues/actualevidencepaths。',
 'scope_clarification':'3guide是本機新版site第20章側欄natural-v4-student.html / natural-v4-data.html / natural-v4-training.html；確認可見導航label、實際click目的頁heading/前段用途。三guide沒有必要為理解本訓練頁全文讀，故只讀landing開場，不作全文guide review。',
 'documents':[{'repository_relative_file':'course/training.md','full_file_raw_utf8_sha256':fullsha,'raw_bytes':len(raw),'actual_line_count':len(raw.splitlines()),'preserved_snapshot':BASE+snapshot,'complete_read':True,'actual_read_order':[{'ordinal':1,'lines':'1–250','scope':'intro,T.1–T.3及T.4開頭'},{'ordinal':2,'lines':'251–500','scope':'T.4剩餘和T.5前段'},{'ordinal':3,'lines':'501–750','scope':'T.5剩餘,T.6,T.7,T.8前段'},{'ordinal':4,'lines':'751–936','scope':'T.8剩餘,T.9,T.10,T.11全部'}],'current_source_exact_byte_recheck':'At report creation, current course/training.md matches preserved initial snapshot exactly; same SHA and 936 lines.','own_summary':'從有限、可判對錯的任務開始，按整篇或家族分三側，先核對一批通路再保存可比起點、更新、以固定新題和生成判斷；架構、格式壓縮與教师訊號各把品質及成本分開。保存完整來源和實際分母，可讓失敗也重做並辨清能否精確續訓。不是一般聊天能力或自然第20章训练的保證。','understanding_assessment':'我能說清楚每節路線的輸入、前置存檔、輸出報告、保存格式和練習判準。大段資料/模型/實驗數量不是同一模型的一條成長史。這是閱讀理解，非重現全部成績或技術正確性審查。'}],
 'source_read_sections':section_summaries,
 'necessary_prerequisites':{'complete_section_count':len(prereqs),'receipts':prereqs,'record_order_note':'Primary receipt order is explicit-reference map order, not a claim that truncated tool output was read. First extraction displayed W.1/1.2/5.1/1.5 then later7.1/7.3/7.11/7.17/7.18; truncated 2.2/1.8/2.3/4.7 were completely reread in a dedicated output. Next displayed8.1/9.1/part10.5/11.1/12.8/13.1/13.4;10.5 was completely reread separately. Then4.5/15.13/17.2, then17.8/18.1/18.6/5.15. Finally followed18.6→18.8→18.5 explicitly for KL and temperature. Every claimed prerequisite section was displayed and personally read completely, including exercises and links.','purpose':'Only explicitly linked sections necessary for tool setup, data grouping, numerical path, fixed-context model, next-target alignment, SFT/stage roles, modality features, preference reference, fair comparison, storage and teacher signals. No recursive full-book read or hidden explanation search.'},
 'original_svg_figure_map':{'direct_training_document_figures':[],'direct_figures_not_applicable_reason':'完整training.md沒有SVG reference；實際渲染頁article也0張SVG。必要明示前置的9張圖另列且全已render/view。','necessary_prerequisite_figures':figs,'render_receipts':[BASE+'figure-render-receipt.json',BASE+'figure-additional-render-receipt.json'],'view_receipt':BASE+'figure-view-notes.json','render_command_files':[BASE+'render_figures.py',BASE+'render_additional_figure.py'],'render_limit':'file:// attempt was blocked by browser administration and did not render; final successful renders used exact preserved SVG bytes through Playwright set_content. XML inspection/hash alone is not counted as view.'},
 'pages':[{'page_id':'training.html','url':'http://127.0.0.1:8769/training.html','actual_browser':'Existing .venv Playwright + Chromium executable_path=/usr/bin/chromium','status':200,'full_page_inspected':True,'full_visible_article_read_and_viewed':True,'provenance':'Actual browser goto, rendered DOM extraction, 11 actual visible anchor clicks, 19 consecutive overlapping article viewport captures personally viewed with view_image, all13 tables and55 code blocks in article','rendered_evidence':BASE+'training.browser-final-rendered.html','rendered_html_sha256':training_browser['rendered_html_sha256'],'visible_text':BASE+'training.browser-article-complete.txt','visible_text_sha256':training_browser['visible_text_sha256'],'receipt':BASE+'browser-training-receipt.json','article_paragraphs':227,'tables':13,'code_blocks':55,'viewed_tile_order':[x['screenshot'] for x in training_browser['tiles']],'view_notes':'我按tile01→19看了整頁；段落和示意表順序完整，T.4較長但列表、程式、欄位表與逐段解說相鄰。T.6的partial表、T.8现代六组表、T.9 storage与T.10学生表可讀，T.11假想表明示非實測。長命令橫向可捲，代表T.3command的實際右側視圖另保存。可見h2/TOC隱去T編號是唯一小建議。'},
 {'page_id':'natural-v4-student.html','url':'http://127.0.0.1:8769/natural-v4-student.html','scope':'heading and opening paragraphs only','visible_navigation_label':'操作指引','own_destination_meaning':'操作第20章成品，先文字、再照片、最後語音，不要求重新訓練；圖文Qwen3-VL與Whisper轉寫兩站、保留底座不加修正。','evidence':BASE+'natural-v4-student.browser-rendered.html','screenshot':BASE+'natural-v4-student.png'},
 {'page_id':'natural-v4-data.html','url':'http://127.0.0.1:8769/natural-v4-data.html','scope':'heading and opening paragraphs only','visible_navigation_label':'資料與來源','own_destination_meaning':'先把照片問答、原樣讀字、聊天示範各對上用途；LoRA候選与底座一起验证；真人音訊作两站验收而非LoRA或Whisper訓練資料。','evidence':BASE+'natural-v4-data.browser-rendered.html','screenshot':BASE+'natural-v4-data.png'},
 {'page_id':'natural-v4-training.html','url':'http://127.0.0.1:8769/natural-v4-training.html','scope':'heading and opening paragraphs only','visible_navigation_label':'自行重訓','own_destination_meaning':'用自己的NVIDIA GPU、Linux/Python3.12在指定底座上重做照片/讀字/聊天的LoRA候選比較；保留原底座是本版選擇，建立候選不等於最後採用；不重訓語音辨識器。','evidence':BASE+'natural-v4-training.browser-rendered.html','screenshot':BASE+'natural-v4-training.png'}],
 'actual_navigation':{'guide_receipt':BASE+'browser-guide-receipt.json','guide_clicks':'training→可見「教材」→chapter-01→展開「第20章」→可見三份guide label→實際click目的頁及heading。首頁guide landing screenshots已親自view。','explicit_article_links':'暖身W.1→first-steps.html#W.1；自然助理重訓指引→natural-v4-training；專用資料指引→natural-v4-data；20.2→20.2.html，均從article可見link實際點入。W.1 source段完整讀，20.2僅入口heading。','other_navigation_receipt':BASE+'browser-remaining-navigation-receipt.json','other_navigation_meaning':'training上的開始閱讀→course.html導讀；其側欄訓練操作→training.html；footer上一頁名詞對照→glossary.html，為術語查閱入口，未當完整glossary閱讀。','long_command_scroll_receipt':BASE+'browser-code-scroll-receipt.json','long_command_scroll_result':'CODE overflowX auto，client688/scroll1376，實際scrollLeft688後可見--train --steps200 --output checkpoint及>outputs報告尾部；初次選錯PRE無scroll，未把0當已捲成功。'},
 'own_workflow_data_and_models':'資料不是學好權重，train更新、validation選設定、test最後評。bigram/MLP各四個簡單模型，TinyLM文字/SFT、故事/詩、byte/BPE、風格/安全、模態入口及正式比較各有獨立配方；不能把120公開存檔當120獨立能力或一個模型逐步成長。本頁CPU操作配方与L4正式報表的宽度/层数/目标量和输出路径相区别。同一模型的LoRA、量化、学生大小也分别改变可訓練數字、保存格式和架構。',
 'five_checks':checks,
 'own_exercise_predictions_and_checks':[{'section':'T.1','prediction':'A教B答對不能算新家族，C應circle','check':'A/B相同red:square:low，C不同blue:circle:high；按文中表手上核對，不訓練。'},{'section':'T.2','prediction':'換sft後mode仍dry-run、有效目標111→8，loss和gradnorm有限正值','check':'兩條真正CPU原命令成功，保存原始輸出，吻合；未跑vision命令。'},{'section':'T.3','prediction':'只按練習代價會選5字MLP','check':'source与browser表0.19883低於3字0.21302；驗證0.51252却高於0.30577，test0.61287也高於0.31105。手讀表，沒有重跑。'},{'section':'T.5','prediction':'两份0+5例子內容5、JSON兩欄均對，只有後者有貼切空盒/五塊積木比喻','check':'文中雙欄示例人工拆欄核對；雙欄是練習另加，生成器只有answer不能混。'},{'section':'T.7','prediction':'0+5兩候選5/6依真值選5；排序不等於自由生成','check':'正文候選和4+2生成8反例可辨二選一和自由輸出差異。沒有DPO訓練。'},{'section':'T.11','prediction':'60000bytes/3-of-5未保住原4-of-5品質','check':'80000−60000=20000bytes；0.6−0.8=−0.2，所以保存变小達標，保住答對數不達標。紙上算例，非實測模型。'}],
 'execution_evidence':{'bounded_offline_cpu_commands':cpu,'cpu_receipt':BASE+'cpu-execution-receipt.json','command_read_inventory':BASE+'command-read-inventory.json','unexecuted_scope':'除了T.2text/sft，本文其餘53個程式/JSON/指令區塊以及同區塊vision命令均未執行。下載清單/fetch、HF模型核對、Git版本、所有200/500及更長更新、CUDA、Flash、DPO/PPO、量化、蒸餾、模態/OCR、續訓、推論均只讀；29前置段的程式也只讀。没有安装、下载、GPU、整書rerun。','known_inputs_outputs_from_text':'詳見intro/T.1–T.11逐節自述和55個原碼inventory；prepare_data产三侧JSONL/manifest，train干run或更新checkpoint/report，evaluate产完整samples/denominators，infer产新生成与JSON IDs/EOS，experiment入口产自己的result和固定model格式。每种checkpoint要匹配入口/字表/基模指紋。','does_not_claim':'沒有重現benchmark、验证全部教科数据/技術正確性、複驗正式GPU成績、验证全部未執行命令或认领266kernel执行。'},
 'verdict':'pass','verdict_reason':'在頁首定位為按任務使用的操作橋樑後，完整文本、必要前置及實際網頁能支持第一次讀者理解輸入、更新/不更新、固定新題、品質/成本、失敗與保存；我未遇到需要修改才可繼續理解的阻擋。唯一可見編號建議不阻擋現有連結跳轉。',
 'own_issues':[issue],'remaining_issues':[issue['id']],
 'scope_limits':['只檢查這份raw SHA的936行訓練文及當前localhost實際頁面。','三份自然guide仅landing heading和用途，非full-document读；course/glossary/20.2也只必要導航入口。','無發佈、建站或閱讀時間／final-times審核；現在實際瀏覽的頁面是未發佈preview。','未來包含266kernels實际输出的重新匯出頁面没有在本报告中被檢查；需要原owner依實際變動必要重看，不能由本次或未來計畫結案。','正文中的GPU表、所有模型存檔及外部完整報告只是閱讀其引用與本文說明；未下載或逐源驗數。'],
 'actual_evidence_paths':[BASE+snapshot,BASE+'prerequisite-read-receipt.json',BASE+'prerequisite-additional-read-receipt.json',BASE+'figure-render-receipt.json',BASE+'figure-additional-render-receipt.json',BASE+'figure-view-notes.json',BASE+'browser-training-receipt.json',BASE+'training.browser-final-rendered.html',BASE+'training.browser-article-complete.txt',BASE+'browser-guide-receipt.json',BASE+'browser-remaining-navigation-receipt.json',BASE+'browser-code-scroll-receipt.json',BASE+'command-read-inventory.json',BASE+'cpu-predictions-before-execution.json',BASE+'cpu-original-T2-command-excerpt.md',BASE+'cpu-execution-receipt.json',BASE+'cpu-T2-text.stdout.txt',BASE+'cpu-T2-sft.stdout.txt']
}
reportfile=OUT/'report.json'
if reportfile.exists():
 prior=reportfile.read_bytes();preserved=OUT/('previous-own-report.'+hashlib.sha256(prior).hexdigest()+'.json')
 if not preserved.exists():preserved.write_bytes(prior)
reportfile.write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n')
print(json.dumps({'report':str(reportfile),'verdict':report['verdict'],'full_source_sha256':fullsha,'line_count':len(lines),'complete_code_blocks':len(blocks),'prerequisite_sections':len(prereqs),'necessary_svg_figures_rendered_and_viewed':len(figs),'browser_complete_tiles_personally_viewed':len(training_browser['tiles']),'remaining_issues':report['remaining_issues']},ensure_ascii=False))
