import hashlib,json
from pathlib import Path
R=Path(__file__).resolve().parents[3];O=R/'docs/technical-reviews/artifacts';N=R/'docs/natural-assistant';P='natural-final-fact-20.5-'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def artifact(identifier,path,kind,description,**extra):return {'id':identifier,'path':str(path.relative_to(R)),'kind':kind,'sha256':sha(path),'description':description,**extra}
audit=json.loads((O/(P+'audit.json')).read_text());prep=json.loads((O/(P+'prepare.json')).read_text())
artifacts=[];lookup={}
for p in sorted(O.glob(P+'*')):
 if not p.is_file() or p.name.endswith('checker.txt'):continue
 suffix=p.name[len(P):];identifier='a-'+suffix.replace('.','-');lookup[suffix]=identifier
 kind='code' if p.suffix=='.py' else 'figure_render' if p.suffix=='.png' else 'source_snapshot'
 extra={};desc='本fresh correctness reviewer新增的可追溯來源／初讀／核對檔案：'+suffix
 if suffix=='audit.json':
  kind='execution';desc='真正執行CPU正文／練習、原始JSON逐record比對、分母／選版／TRAIN對照重算的結果；沒有新模型推論。'
  extra={'command':'.venv-natural/bin/python docs/technical-reviews/artifacts/'+P+'audit.py > docs/technical-reviews/artifacts/'+P+'audit.stdout.txt','result':'exit 0；所有assertions通過；表16/36→17/36、六域83/216→106/216與gentle100/216重算一致。','environment':{'python':audit['python'],'torch':audit['torch'],'device':'CPU only; no model forward or GPU'}}
 if suffix=='prepare.json':
  kind='execution';desc='直接取得原作者／維護者sources，核對內嵌JPEG bytes，Chromium實際render三SVG720/358；CC legalcode HTTP403單獨保留、不當已查來源。'
  extra={'command':'.venv/bin/python docs/technical-reviews/artifacts/'+P+'prepare.py','result':'exit 0；5個原始來源取得、6個SVG瀏覽器render；完整JPEG bytes相等、所有text在viewBox內；6renders已view。','environment':{'python':prep['python'].split()[0],'browser':prep['renders'][0]['browser'],'device':'CPU/headless Chromium; no neural inference'}}
 artifacts.append(artifact(identifier,p,kind,desc,**extra))
ae=lookup['audit.json'];ar=lookup['prepare.json'];ai=lookup['independent-semantics.json'];an=lookup['post-inspection.json']
sources=[]
def original(identifier,title,url,version,note,snapshot,kind='official_source'):
 p=O/(P+snapshot);sources.append({'id':identifier,'kind':kind,'title':title,'url':url,'version':version,'verified':True,'checked_original':True,'accessed_on':'2026-10-04','authority_reason':'原作者／發布者／實作維護者的第一手原文；實際取得與閱讀，不沿用review conclusions。','inspection_note':note,'snapshot_path':str(p.relative_to(R)),'sha256':sha(p)})
original('s-docci-paper','DOCCI原作者論文','https://arxiv.org/pdf/2404.19753','arXiv:2404.19753，2026-10-04實際取得PDF；確切bytes由snapshot SHA固定','讀§1、§2 collection、§3人工標註、§4.2 side-by-side precision/recall及Table1。物件、空間、活動和新增幻覺須分項；人寫英文、Jason與家人拍攝；此論文不證明本課成績。','docci-paper.pdf','paper')
original('s-docci-web','DOCCI官方發布網站固定原文','https://raw.githubusercontent.com/google/docci/c190366529943195d90c141899abb2ec68dc345d/index.html','官方網站commit c190366529943195d90c141899abb2ec68dc345d','實讀Abstract lines150–162、download與License lines253–257。Google LLC授權annotations及images CC BY4.0；這不把本課中文題當官方人工中文。','docci-website.txt')
original('s-python','Python sets官方契約','https://docs.python.org/3.13/library/stdtypes.html#set-types-set-frozenset','Python3.13文件；CPU例子另實跑3.12.14','實讀Set types：unordered distinct elements、same members equality、set.add。沒有從集合 equality 推出照片自動判讀能力。','python-sets.txt','official_docs')
original('s-generation','Transformers generation設定原始碼','https://raw.githubusercontent.com/huggingface/transformers/v4.57.6/src/transformers/generation/configuration_utils.py','Transformers v4.57.6','實讀max_new_tokens lines107–111：忽略prompt的新增上限；greedy mode lines88–91及do_sample default。384是上限，非每筆都384。','transformers-config.txt')
original('s-stop','Transformers decoder stopping原始碼','https://raw.githubusercontent.com/huggingface/transformers/v4.57.6/src/transformers/generation/stopping_criteria.py','Transformers v4.57.6','實讀MaxLengthCriteria lines59–80、EosTokenCriteria lines452–473。停止條件檢查長度及最後token，無語意真偽判定。','transformers-stop.txt')
original('s-public','實際公開選定版本的固定發布provenance','https://huggingface.co/birdhackor/tiny-perceptron-course-models/resolve/8dab26b439499188149b7ac5b861dab4f6c0755a/natural-v3/assistant-2b-v3/release-provenance.json','public immutable revision8dab26b439499188149b7ac5b861dab4f6c0755a','匿名實際取得686 bytes，SHA5f2456…與公開清單相等；來源prefix綁定原LR1e-4 train run，底座pin相同。只下載此小型JSON，未下載全模型。','public-release-provenance.json')
def local(identifier,path,title,note):
 p=R/path;sources.append({'id':identifier,'kind':'repository_code','title':title,'path':path,'sha256':sha(p),'version':'本次實際讀取snapshot SHA-256；原執行run/revision於檔內保留','verified':True,'inspection_note':note})
local('s-core','tiny_perceptron/natural_assistant.py','實際訊息建構、生成與訓練程式','讀messages_for111–130、generate308–363、run_train469起：參考答案只assistant=True時送入；greedy、suffix、EOS與truncation；新建修正與resume是不同路徑。CPU只呼叫pure message／score functions。')
local('s-gate','scripts/modal_natural.py','最後測試前綁定selection的程式','讀validate_selection183–202與selection_gate205–234；manifest、completed validation、adapterrun/weightSHA綁定。沒有發起任何遠端工作。')
for identifier,name,title,note in [
('s-manifest','manifest.json','凍結資料／題目清單','直接重數照片家族120/12/12與120/36/36題；同圖三問不跨split；原圖實際SHA相符。'),
('s-rubric','rubric.json','事前固定整段語意與completion規則','完整讀scene.object/activity/relation/open_description/short_facts及completion.acceptance，不可用keyword取代。'),
('s-rule','selection-rule-gentle.json','事前第二候選選版規則','完整讀六domain／eligibility／嚴格較高均值／tie／不得final選版；只在原驗證之後、gentle和final之前聲明。'),
('s-selected','selection.json','最後前已鎖定之選版','重算實際SHA為c7e4dff…並與finalexecution和已選權重一致；不重新選模型。'),
('s-train','evidence/train/result.json','原LR1e-4訓練原始記錄','真正CPU重讀180history、360visits、272IDs、5791位置與112hash，未重訓GPU。'),
('s-train-gentle','evidence/train-gentle/result.json','fresh LR3e-5訓練原始記錄','與原版所有事先設定、初始tensor、每步id及target數直接比對；只LR不同；未被選。'),
('s-val-raw','evidence/validation/generations.json','初版paired384驗證全部原始生成','先獨立讀72場景全文，之後CPU對所有128records逐一token/score/semantic embeddedraw exact核對；不是96token baseline。'),
('s-gentle-raw','evidence/validation-gentle/generations.json','gentle paired384驗證原始生成','另完整讀36gentle場景答；CPU驗128records原始suffix、score、stop。'),
('s-final-raw','evidence/final/generations.json','最後兩版180筆原始生成','先獨立讀72場景全文與12原圖，再與semanticreport原記錄完全比對；保留新增錯誤、五份adapter截斷。'),
('s-final-exec','evidence/final/execution.json','最後原始執行與pretest selection鎖','runnerarguments test/384/adapterpath；selection SHA c7e4…；未聲稱這位reviewer重新推論。'),
('s-sem-val','evidence/semantic-validation/paired-384-semantic-review.json','既有独立整段驗證逐題記錄','在保存新reviewer144初判後才讀；逐record raw equality、completed counts及邊界再核對。不以其pass決定本technical pass。'),
('s-sem-gentle','evidence/semantic-validation/gentle-384-semantic-review.json','既有gentle整段驗證逐題記錄','重算六域成功數，核對128embeddedraw；資料／規則沒更動。'),
('s-sem-final','evidence/semantic-final/final-semantic-review.json','既有完整最後語意核對記錄','獨立原圖/raw初判後才讀；逐record180原文相等、36scene分類／完成成功重數；gold_uncertainties和borderlines明確保留。'),
('s-control','evidence/image-control/result.json','原CPU兩TRAIN圖控制實測','讀完整兩rows/原回答/token/stop/question/history/system條件；CPU重建message路徑不漏入答案；沒有新模型生成。'),
('s-control-protocol','image-control.json','事前image-control條件','相同問題／空history／default system與兩TRAIN圖身份；hash直接與controlresult相等。'),
('s-release','public-release.json','公開選定模型固定檔案清單','run與adapter077866…绑定selection、CPUcontrol的publicrevision8dab…；只驗小型publicprovenance，未驗全部模型download。'),
]:local(identifier,'docs/natural-assistant/'+name,title,note)
local('s-original-desc','data/natural/vision/selected-descriptions.jsonl','實際DOCCI原始人工英文描述與publisher thumbnail身分','逐讀用於例子與邊界的原記錄；原JPEG hash及GCSgeneration由manifest固定。原文不是本課AI中文GT。')
sources.extend([{'id':'s-audit','kind':'execution','title':'新reviewer實際CPU執行與獨立重數','verified':True,'artifact_id':ae},{'id':'s-render','kind':'execution','title':'實際原JPEG核對與SVG browser render','verified':True,'artifact_id':ar}])
claims=[]
def claim(identifier,kind,statement,location,evid,arts,scope,expected=None,observed=None,denom=None):
 c={'id':identifier,'kind':kind,'statement':statement,'location':location,'status':'verified','evidence':[{'source_id':s,'locator':l,'supports':t} for s,l,t in evid],'artifact_ids':arts,'primary_source_ids':[s for s,_,_ in evid],'scope':scope,'validation':{'evidence_ids':arts,'method':'先原圖／raw獨立初判，再原作者來源／固定規則與CPU重數核對'}}
 if kind!='concept':
  c['verification']={'method':'executed','expected':expected or statement,'observed':observed or statement,'details':'真正執行a-audit，原始資料不變；數值不是僅抄summary。視覺／語意另見144初判及post-inspection；沒有新模型推論。','tolerance':'整數、records、SHA與Fraction精確相等；语意依已揭露固定判準，非唯一数学答案。'}
  if kind=='empirical':c['verification']['denominators']=denom or {'scope':'此固定小型實驗與題目數，不外推'}
 claims.append(c)
E=lambda s,l,t:(s,l,t)
claim('c1','concept','相同人／腳踏車物件不保證活動／位置關係相同；新增物件或不可見目的可使整答失敗。','開頭三段及整答原則',[E('s-docci-paper','Table1、§1、§4.2 precision/recall','物件、空間／活動與幻覺／資訊不足分開'),E('s-rubric','scene各欄','固定本課判準')],[ai,an],'人工示意與方法原則，不宣稱原論文直接驗本課模型。')
claim('c2','concept','正式自然語言答案可用合理同義措辭；整句逐字相等或幾個名詞命中都不等於圖像語意正確。','Python後一段',[E('s-docci-paper','§4.2 SxS human evaluation','precision/recall評核與referencebased proxy有別'),E('s-rubric','open_description與short_facts','不需逐字一致、保存具體不支持內容')],[ai,an],'詞組代理可另外報告；不主張任意同義詞自動評分可靠。')
claim('c3','software','集合比較忽略順序；兩卡objects均True，activity依序True、False。','Python唯一fence及解釋',[E('s-python','set equality／unordered','同成員相等'),E('s-audit','example_output','exact fence CPU輸出')],[ae,lookup['example.py'],lookup['example.txt']],'人工truth；未讀照片、未生成模型答。','True/True與True/False','CPU完整四行精確一致')
claim('c4','software','練習只替第二card.objects加狗後，第二物件也False，activity仍False。','末段練習',[E('s-python','set.add及same-member equality','新增member改變相等性'),E('s-audit','exercise_output','真正執行最小變更')],[ae,lookup['exercise.py'],lookup['exercise.txt']],'沒有偷偷改原truth／activity。','第一卡True/True；第二False/False','CPU四行一致')
claim('c5','concept','同題換真實圖片並用各自真值核對，才可檢查圖像條件；TRAIN兩圖示範不是泛化證明。','換圖段與TRAIN控制限制',[E('s-docci-paper','§2與related/contrasting image設計','相近主體差異需圖像grounding'),E('s-control-protocol','scope／criterion','固定問題、圖不同；TRAIN限制')],[ai,an],'有限因果示範；不能排除訓練圖记憶或預訓練overlap。')
claim('c6','empirical','初版完整驗證照片通過19/36、底座11/36。','驗證兩把尺段',[E('s-val-raw','72scene raw生成','真正原回答'),E('s-sem-val','records.completed_task_success','被引用的事前整答判定'),E('s-audit','recomputed_semantic_counts.validation','直接重數')],[ae,ai,an],'本課小型留出驗證，AI助理整句評閱；不是人類多人盲評。','19/36與11/36','逐36record completed成功19與11',{'per_variant_questions':36,'unique_validation_photos':12})
claim('c7','empirical','初版短事實詞組命中15/24、底座21/24，與整段語意方向不同。','驗證兩把尺段',[E('s-core','score_output','固定詞組函數'),E('s-val-raw','fact score欄位','原phrase分數'),E('s-audit','phrase_proxy.validation','實際函數重算')],[ae],'分母24短題；不是所有36題或全部圖理解。','15/24與21/24','actual score_output與全部原score字典exact相等',{'short_questions_per_variant':24})
claim('c8','empirical','初版驗證五份scene描述反覆到384上限，失敗仍留分母。','驗證兩把尺段',[E('s-val-raw','五份scene complete suffix','反覆未EOS'),E('s-audit','token_audit.validation.adapter','末token與長度重新核對')],[ae,ai],'只描述原已存輸出，沒有重試／裁掉失敗。','5份截斷','5個384 suffix均無EOS且truncated；19成功分母仍36',{'open_descriptions':12,'all_scene_questions':36})
claim('c9','empirical','第二候選從同底座fresh跑180步，只把LR1e-4降3e-5。','較輕更新段',[E('s-train','initial_adapter_tensors/history','原180步證據'),E('s-train-gentle','完整設定與初始／每step record','LR唯一差異'),E('s-core','run_train/load_core','无adapter路径重新建分支'),E('s-audit','training及all_settings_equal_except_learning_rate','真正112initialhash與180step id/target比對')],[ae],'新訓練GPU記錄的CPU核驗；reviewer未重訓，loss不同不是品質證據。','180、360、272、5791相同；LR1e-4/3e-5','exact112初始相同、settings逐欄相同且每步順序位置數相同',{'steps_per_candidate':180,'visits':360,'train_records':272,'initial_tensors':112})
claim('c10','numeric','兩candidate驗證與final兩版共用384新增token上限。','兩次比較段、final段',[E('s-generation','max_new_tokens API lines107–111','上限排除prompt'),E('s-final-exec','runnerarguments --max-new-tokens384','final固定上限'),E('s-audit','token_audit各stage','所有suffix<=384、非都恰384')],[ae],'不是舊96token基線；正常EOS可早停。','384','全validation、gentle、final suffix長度<=384；所有cap失敗無EOS')
claim('c11','empirical','按已宣告eligibility與六類平均，較輕版未超過初版；在final前鎖定原版。','選版段',[E('s-rule','domains/adapter_eligibility/decision','六domain算術平均與tie規則'),E('s-selected','decision及c7e4…原bytes','選定原版'),E('s-sem-val','records','base及original逐domain成功'),E('s-sem-gentle','records','gentle逐domain成功'),E('s-audit','recomputed_selection','Fractions重算')],[ae,an],'選到一版是教學規則結果，未證一般優越／統計顯著。','83/216、106/216、100/216','Fraction83/216、53/108、25/54；gentle上界101/216仍低原版；兩adapter均eligible',{'domains':6,'scene':36,'ocr':9,'presence':3,'text_chat_and_dialogue':4,'typed_chat':6,'speech_chat':6})
claim('c12','software','final用c7e4…selection与077866…原adapter，沒有用final分數重新選候選。','final段與選版鏈',[E('s-selected','selected_variant/run/adaptersha','原候選固定'),E('s-final-exec','selection_sha256/pretest_selection','實際執行綁定同SHA'),E('s-gate','selection_gate','綁定validation與selectedweight'),E('s-audit','selection_sha256','實際checksum與run對照')],[ae],'可信原始執行收據與固定規則核對，不聲稱能證所有未公開人的思想歷程。','c7e4dff552012cd18593f3708dc9f6fbf11292511894a9ac70c1bb86558e76fa','本地selection實際SHA與final完全相等；原trainrun同selectedrun')
claim('c13','numeric','final12張留出DOCCI照片每圖3題：12描述+24短題=36，而非36獨立圖。','final資料段',[E('s-manifest','test task=scene rows/families','固定題與圖'),E('s-audit','split_counts','實際重數及train/val/test不交叉')],[ae],'本課來源照片split互斥；不能證上游預訓練沒見過。','12/12/24/36','12imagefamilies，36scene records，suffix scene12/fact24')
claim('c14','concept','整段成功須所問內容與新增敘述支持且正常完成；EOS不是正確性證明，截斷不算完成。','final驗收條件段',[E('s-stop','EosTokenCriteria/MaxLengthCriteria','停止只查token與長度'),E('s-rubric','completion.acceptance、scene各欄','本課整段完成標準'),E('s-docci-paper','§4.2 precision/recall','對/錯內容與資訊不足核對')],[ai,an],'decoder完成、語意正確各自記；不將EOS用作可靠性證書。')
claim('c15','empirical','final物件及屬性8/13→10/13。','分項表第一列',[E('s-sem-final','all_records scene_primary_criterion=object','每題只歸一欄'),E('s-final-raw','對應全部原回答','整段輸出'),E('s-audit','final.scene_categories object','逐13重數')],[ae,ai,an],'固定既有review的完成整句數；特定物種與車型附加未支持仍fail。','8/13→10/13','exact重數8與10，各denom13',{'object_questions_per_variant':13})
claim('c16','empirical','final活動0/2→1/2。','分項表第二列',[E('s-sem-final','activity rows','玻璃活動與狗姿勢題'),E('s-final-raw','兩題×2原答','動作及新增錯誤'),E('s-audit','final.scene_categories activity','逐題重數')],[ae,ai,an],'2題不足概括一般活動理解。','0/2→1/2','exact0與1，各2',{'activity_questions_per_variant':2})
claim('c17','empirical','final位置／互動關係7/9→6/9。','分項表第三列',[E('s-sem-final','relation rows與borderlines','台座詞解讀公開'),E('s-final-raw','9題×2原答','完整錯誤保留'),E('s-audit','final.scene_categories relation','逐題重數')],[ae,ai,an],'test00039 base理由onlytwo過窄另記；回指三車句形成錯誤足保留fail，不改raw或GT。','7/9→6/9','exact7與6，各9',{'relation_questions_per_variant':9})
claim('c18','empirical','final整體場景1/12→0/12，全部照片16/36→17/36。','分項表末兩列及解讀段',[E('s-sem-final','all_records、category','唯一主要類別分割'),E('s-final-raw','12整體描述與24fact全句','對圖全答'),E('s-audit','recomputed_semantic_counts.final','8+0+7+1=16，10+1+6+0=17')],[ae,ai,an],'17比16多1僅此36題的結果；描述0不是零物件辨識。','1/12→0/12；16/36→17/36','四分類denom13+2+9+12=36，分子精確求和',{'photos':12,'open_questions':12,'short_questions':24,'total_questions':36})
claim('c19','empirical','final選定版5描述截斷，另7描述正常結束仍錯／不足／unsupported；全90回答85EOS。','0/12解讀段與raw停止證據',[E('s-final-raw','adapter scene/open suffix与stop','五反覆完整原文'),E('s-audit','token_audit.final.adapter','85EOS/5cap，sceneopen7EOS')],[ae,ai,an],'85/90屬全部生成含文字／typedcontrol／speechroutes，不是照片分母。','5/12截斷+7/12EOS失敗；85/90EOS','count90，EOS85、384無EOS5均scene open；12 open none completed task pass',{'all_adapter_generated_records':90,'open_descriptions':12})
claim('c20','empirical','final短事實詞組底座23/24、微調21/24，不能取代整句表。','0/12解讀段末句',[E('s-core','score_output','phrase proxy'),E('s-final-raw','24facts scores','原分數'),E('s-audit','phrase_proxy.final','实际函数重算')],[ae],'回報獨立代理分數，未稱整體圖片理解。','23/24、21/24','全部facts rawscore與重新scoreexact一致',{'short_questions_per_variant':24})
claim('c21','empirical','bike fact1微調完整答前輪抬起通過；同圖scene雙腳踩兩輪錯誤，因此兩題EOS不使scene通過。','bike原圖與例子段',[E('s-final-raw','test00729 fact1/scene adapter','逐字引文原樣'),E('s-original-desc','test00729 record','左腿接地、右腿onbike；前輪向上'),E('s-render','bike JPEG original bytes/render','實際完整原圖'),E('s-audit','raw/stop核對','17token與105token均EOS')],[ae,ar,ai,an],'單圖不能推出速度／完整特技序列或精確防護材質。','fact1pass、scenefail、2EOS','引文exact；原圖一腳接地、沒有雙腳各踩前後輪',{'image':1,'quoted_questions':2})
claim('c22','empirical','glass兩短題完整引文把手握桿柄誤成直接握玻璃，並漏活動／位置；均fail。','glass原圖與例子段',[E('s-final-raw','test01103 fact1/fact2 adapter','20與27token原答exact'),E('s-original-desc','test01103人工原記錄','玻璃／工具／熱爐來源'),E('s-render','glass JPEG原bytes','手、桿、玻璃、爐口真圖'),E('s-audit','兩suffixEOS核對','正常停止仍錯')],[ae,ar,ai,an],'玻璃球是概括，不要求完美球體；沒有可見吹氣，不能由工藝名推出吹氣動作或全加工階段。','2fail且EOS','原圖手握黑柄，玻璃在桿端亮爐口；第二答機器不是位置',{'image':1,'questions':2})
claim('c23','empirical','兩TRAIN圖同一問題／空history／default system，原CPU完整回蘑菇與車廂，均EOS；沒有答案輸入。','兩TRAIN換圖實測段',[E('s-control-protocol','全部固定條件','事前相同非物件提示問題'),E('s-control','cases.row/result/attempts','實際CPU原回原suffix'),E('s-core','messages_for defaultassistantFalse','不塞reference／expectedsubject'),E('s-release','revision與adapterhash','公開原candidate'),E('s-public','固定公開provenance','實際匿名來源綁定'),E('s-audit','image_control','兩inputhash与messages真正重建核對')],[ae,an],'reviewer核驗已有CPU實測，沒有新推論。未序列化的整個舊processor message只能用固定程式／row佐證，未聲称完整運行instrumentation。','一個藍色的蘑菇。／一列鐵路車廂。；TRAIN2、EOS2','fulltext exact、question/history identical、no system/answer、input mediahash相等',{'train_images':2,'actual_original_generations':2})
claim('c24','empirical','原蘑菇可見藍灰色，原鐵路圖可見車廂；主要回答隨圖改變，靜態車廂未證行駛。','兩TRAIN實測段末句',[E('s-control','兩input_image sha','所view正是原CPUinput'),E('s-audit','control image/hash','兩TRAIN圖identity核對')],[ae,an],'圖條件示範只此2TRAIN cases；既非blindheldout亦非可靠全scene或因果泛化證明。','兩主體匹配','原JPEG實看：藍灰菌帽、鐵路車身；回答未宣稱motion',{'train_images':2})
claim('c25','concept','DOCCI照片由Jason Baldridge與家人拍攝，描述為人工英文，Google CC BY4.0；本課縮圖與AI中文題另說明。','final來源署名段',[E('s-docci-paper','§2 lines186–200及§3','攝影與人工標註來源'),E('s-docci-web','license253–257／Abstract150–162','image與annotation CC BY4.0'),E('s-original-desc','publisher thumbnail/path/generation','此圖包版本'),E('s-manifest','source/course-authored rows','中文題不偽裝官方標註')],[ar,an],'下載發布者thumbnail不是full-resolutionZIP；授權與攝影署名正確，不證所有第三方權利。')
claim('c26','software','兩actual SVG完整內嵌原JPEG、等比無裁切，標題提示觀察、credit與license清楚；人工示意另明示其身份。','三圖與alt/字幕',[E('s-render','jpeg_proof與6renders','embedded bytes原圖exactequal；720/358實際瀏覽器看'),E('s-docci-web','CC BY4.0 license','署名來源'),E('s-audit','input images sha','與模型原素材一致')],[ae,ar,an]+[lookup[x] for x in ['natural_actual_bike-720.png','natural_actual_bike-358.png','natural_actual_glass-720.png','natural_actual_glass-358.png','natural_photo_evidence-720.png','natural_photo_evidence-358.png']],'手機縮小仍可觀察全圖；教材無額外畫新動作來替原圖證實。','2原JPEGexactequal；3SVG×2尺寸','base64 decode与原JPEG bytes相等；6text bounds inside，6PNG已實際view')
figures={f:sha(R/f) for f in ['course/figures/natural_photo_evidence.svg','course/figures/natural_actual_bike.svg','course/figures/natural_actual_glass.svg']}
checks={
'factual_accuracy':{'status':'pass','details':'完整讀20.3–20.5；先獨立144場景全答初判，再對照原record與事前規則；bike/glass引用和false关系直接確認，generation／TRAIN控制與候選範圍均保守。','claim_ids':[c['id'] for c in claims]},
'numeric_verification':{'status':'pass','details':'真正CPU執行fence與exercise；重數128+128+180tokens、recordequality、36分母、13/2/9/12分項；Fraction均值與selectionSHA；數值與正文精確一致。','claim_ids':[c['id'] for c in claims if c['kind']!='concept']},
'figure_consistency':{'status':'pass','details':'原bike/glass JPEG實看；SVGbase64與完整原bytesexact相等；三SVG720/358 Chromium實際render及view，文字不出viewBox，credit明示，人工與實圖身份清楚。','claim_ids':['c1','c21','c22','c26']},
'source_verification':{'status':'pass','details':'DOCCI原作者PDF、固定官方website、Python官方sets、Transformers4.57.6 originalsource和HF固定publicprovenance實際取得／讀取。CClegalcode403未當已讀source；許可由DOCCI發布者直接聲明支持。原始evidence／來源SHA与真实当前版本绑定。','claim_ids':[c['id'] for c in claims]},
'limitations':{'status':'pass','details':'數字是固定AI全答審查，不是唯一語意判斷、多人盲評或統計結論；邊界初判與再讀保留。訓練照片控制、12圖36問非獨立36圖、EOS與內容、上游overlap、單帧動態／種名都限定。只read-only Git誤用一次如實記，無mutation。','claim_ids':[c['id'] for c in claims]}}
report={'schema_version':1,'review_stage':'technical','lesson_id':'20.5','source':'course/chapters/20.md#20.5','reviewer_task':'/root/natural_factual_final_20_5','reviewer_context':'fresh','author_tasks':['/root','/root/natural_curriculum_v3','/root/natural_results_author_20_5','/root/natural_final_photo_diagrams'],'source_sha256':audit['source_sha256'],'figure_sha256':figures,'verdict':'pass','claims':claims,'sources':sources,'primary_sources':sources,'artifacts':artifacts,'independent_checks':{'fresh_context':True,'read_reader_conclusions':False,'read_other_technical_conclusions_for_this_lesson':False,'original_semantic_reports_read_only_after_independent_snapshot':True,'execution_evidence_ids':[ae,ar],'independent_semantic_snapshot':ai,'post_inspection_boundaries':an,'gpu_used':False,'large_model_inference_used':False,'new_test_inference_used':False,'ground_truth_or_selection_changed':False,'tracked_course_or_runtime_changed':False,'git_used':'一次read-only status/rev-parse誤用；如實保留，未mutation；後續不使用','actual_checks':['20.3–20.5完整閱讀','exact正文CPU與加狗練習','12final+12validation原圖及144rawanswer独立初判','另36gentle完整scene原答','比對128+128+180semantic embeddedraw與raw exact','每個suffix length／EOS／truncation重算','initial112tensor与180step順序／targets對照','fixed六域eligibility及Fraction mean重算','c7e4…selection與077866…adapter鎖','兩TRAIN控制原图／问题／history／无答案message建构／fixed公开provenance','三SVG×720/358实际render／view']},'issues':[{'id':'boundary-source-support','status':'resolved','details':'初判若干來源／模糊用詞有疑義，不能用後來review pass取代確認。','resolution':'保留144初版snapshot並重新讀原DOCCI描述與必要1024px图，逐項寫post-inspection。表中固定判定可在已揭露解讀下成立，沒有修改GT/生成/selection。','evidence_ids':[ai,an]},{'id':'truck-count-reason-scope','status':'resolved','details':'原semantic理由onlytwo不能當JPEG所有車的全景精確數。','resolution':'原JPEG最右淺色車完整保留；這個row fail用原生成前文三車集合含皮卡的回指自相矛盾支持。數值是被引用固定completed審查的重算結果，不為原reason每個措辭背書；已向root告知，原始JSON未改。','evidence_ids':[ai,an,ae]}],'checks':checks,'summary':'pass：正文數值、固定訓練／選版／final鏈、原圖與原引文、CPU範例及TRAIN控制範圍核對成立。保存先獨立後比對的語意邊界；不重新選模型、不修GT、不將EOS／keyword／2TRAIN示範外推。'}
(R/'docs/technical-reviews/20.5.json').write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n')
print('Wrote fresh technical report:',len(claims),'claims',len(sources),'sources',len(artifacts),'artifacts')
