from pathlib import Path
import json,hashlib,re,platform
R=Path.cwd();P='docs/technical-reviews/artifacts/natural-final-fact-20.7-'
def digest(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
read=lambda n:json.loads(Path(P+n).read_text())
audit=read('audit.json');supp=read('supplement.json');render=read('render.json');fetch=read('fetch-receipt.json')
artifacts=[];sources=[];claims=[]
def art(id,path,kind,description,execution=None):
 d={'id':id,'kind':kind,'path':path,'sha256':digest(path),'description':description}
 if execution:d.update(execution)
 artifacts.append(d)
def ownart(id,name,kind,description,execution=None):art(id,P+name,kind,description,execution)
env=audit['environment']
ownart('a_audit','audit.json','execution','独立 full-matrix Levenshtein、原TSV与42条reference、12 WAV SF metadata/hash、三组token/EOS、人工卡与练习的实际CPU核对。',{'command':'.venv/bin/python '+P+'audit.py','result':'Exit 0; raw150/481=31.185031185%; NFKC+whitespace129/464=27.801724138%; WAV2111680/16000=131.98s; ASR/typed/voice EOS each12; card False/15/5 and exercise True/15/15.','environment':env})
ownart('a_supp','supplement.json','execution','实际调用messages_for核12对上下文；读取真实Git执行版本；固定HF header求参；核rubric时间与验证6题；逐答比对自己的先判结果。',{'command':'PYTHONPATH=. .venv/bin/python '+P+'supplement.py','result':'Exit 0; 12 same expected prior system contexts, no prior user/image;479 header tensor shapes total241734912; frozen rubric08:36 before final09:46; 24/24 full-success choices agree; validation typed0/6,0/6; ASR0/6,1/6. Full original serialized prompts were not saved.','environment':supp['environment']})
ownart('a_fetch','fetch-receipt.json','execution','独立读取固定主要cards、papers、Unicode/Python官方文件及只限safetensors头部的网络收据。',{'command':'.venv/bin/python '+P+'fetch.py','result':'Exit 0; all10 primary documents HTTP200; header range HTTP206, total55432 bytes (8-byte length+55424-byte JSON), not full weights.','environment':{'python':env['python'],'device':'CPU HTTPS metadata/document reading; no inference'}})
ownart('a_render','render.json','execution','实际渲染必要前置的共用两站图，原SVG尺寸及720/358宽度记录。',{'command':'.venv/bin/python '+P+'render.py','result':'Exit 0; original SVG rendered720x1010 and358x502.1875; both images later viewed by reviewer.','environment':render['environment']})
ui=read('ui-execution.json');assert ui['exit_code']==0
ownart('a_ui','ui-execution.json','execution','既有3个HTTP/UI契约测试：同history/图、独立辨识站与送出更正文、页面原稿显示。',{'command':ui['command'],'result':'Exit 0; 3 passed in1.52s. Real local HTTP with mocked ASR/generate; neither speech nor model quality is measured.','environment':ui['environment']})
ownart('a_manual_before','independent-semantic-before-comparison.json','derivation','本审阅者先读24个原回答自行固定逐答完整成功判断及理由，之后才打开semantic-final报告。')
ownart('a_manual','manual-dimensions.json','derivation','24答原意、原始全文、原稿忠实/实际输入忠实/无据内容/回复行为/繁体/停止独立列项；初判不改变，分维度表在对照后展开。')
ownart('a_notes','reading-and-view-notes.json','derivation','实际全节与前置阅读、两宽图像visual inspection及scope记录。')
for w in [720,358]:ownart('a_fig'+str(w),'render-'+str(w)+'.png','figure_render','本人实际view的共同两站架构图 '+str(w)+'px，非性能证据。')
for n in ['audit.py','supplement.py','fetch.py','render.py','sum-card.py','exercise.py','build-report.py']:
 ownart('a_code_'+n.replace('.','_'),n,'code','审阅者实际核对/持久化脚本；无大模型重跑、GPU或训练。')
for n in ['audit.stdout.json','audit.stderr.txt','audit-execution.json','supplement.stdout.json','supplement.stderr.txt','supplement-execution.json','fetch.stdout.json','fetch.stderr.txt','fetch-execution.json','render.stdout.json','render.stderr.txt','render-execution.json','ui.stdout.txt','ui.stderr.txt','sum-card.stdout.txt','sum-card.stderr.txt','exercise.stdout.txt','exercise.stderr.txt']:
 ownart('a_log_'+n.replace('.','_'),n,'source_snapshot','实际command stdout/stderr/exit或子示例输出；对应execution有明确scope。')
for n in ['20.1','12.11','12.13','12.14','19.7']:ownart('a_prereq'+n,'read-'+n+'.md','source_snapshot','本人实际读过的必要前置全文；不沿用旧审阅结论。')
for v in supp['source_versions']:art('a_version_'+str(len(artifacts)),v['path'],'source_snapshot','git show实际版本快照：'+v['command']+'; exit0; SHA核对，核心当前与执行版本相同，CLI96/384版本各自保留。')
for n in ['whisper-card.md','whisper-config.json','whisper-generation-config.json','whisper-header.json','transformers-whisper.py','fleurs-card.md','fleurs-loader.py','fleurs-v1.pdf','fleurs-v1.txt','whisper-v1.pdf','whisper-v1.txt','uax15.html','python-unicodedata.rst','python-stdtypes.rst']:
 ownart('a_primary_'+n.replace('.','_'),n,'source_snapshot','本人读取的原始官方来源/原论文快照；URL、版本、locator与支持条件在sources。')
for name,path in [('final_transcripts','docs/natural-assistant/evidence/final/transcripts.json'),('final_generations','docs/natural-assistant/evidence/final/generations-adapter.json'),('final_result','docs/natural-assistant/evidence/final/result.json'),('final_execution','docs/natural-assistant/evidence/final/execution.json'),('semantic_final','docs/natural-assistant/evidence/semantic-final/final-semantic-review.json'),('validation_generations','docs/natural-assistant/evidence/validation/generations.json'),('validation_execution','docs/natural-assistant/evidence/validation/execution.json'),('semantic_validation','docs/natural-assistant/evidence/semantic-validation/paired-384-semantic-review.json'),('pre_output','docs/natural-assistant/evidence/semantic-validation/pre-output-review.json'),('baseline_execution','docs/natural-assistant/evidence/baseline/execution.json'),('train_execution','docs/natural-assistant/evidence/train/execution.json'),('speech_manifest','data/natural/speech/manifest.json'),('tsv_test','data/natural/speech/official-sources/test.tsv'),('tsv_train','data/natural/speech/official-sources/train.tsv'),('tsv_dev','data/natural/speech/official-sources/dev.tsv')]:art('a_'+name,path,'source_snapshot','原项目实际数据/执行记录；只读核对，非新推理。semantic报告仅作先判后的对照，未替代自己的逐答阅读。')
for id,aid,title in [('s_audit','a_audit','独立CPU数值/原资料核对'),('s_supp','a_supp','独立CPU route/source/header/semantic核对'),('s_ui_execution','a_ui','既有UI HTTP契约测试')]:sources.append({'id':id,'kind':'execution','title':title,'verified':True,'artifact_id':aid})
def official(id,kind,title,url,version,authority,note):sources.append({'id':id,'kind':kind,'title':title,'url':url,'version':version,'verified':True,'checked_original':True,'accessed_on':'2026-10-04','authority_reason':authority,'inspection_note':note})
WH='973afd24965f72e36ca33b3055d56a652f456b4d';FL='d7c758a6dceecd54a98cac43404d3d576e721f07'
official('s_whisper_card','official_docs','openai/whisper-small pinned original model card','https://huggingface.co/openai/whisper-small/blob/'+WH+'/README.md',WH,'OpenAI checkpoint card with model/task/provenance details; partly authored by HF, distinguished from original paper.','Read Model details/Usage/context tokens/Performance and Limitations: pretrained ASR/translation encoder-decoder; transcribe same language, translate another language; zh and transcribe task selection; accents/noise/contexts require domain evaluation. small244M table is coarse, not exact checkpoint tensor count.')
official('s_whisper_paper','paper','Robust Speech Recognition via Large-Scale Weak Supervision','https://arxiv.org/pdf/2212.04356v1','arXiv2212.04356v1,2022','Original OpenAI authors’ architecture/training paper.','Read §§2.2–2.3 and Figure1:16kHz Mel encoder, cross-attention acoustic decoder, task/language tokens and segment ending. This supports the ASR definition and existence of trained acoustic-decoder route; does not certify native audio chat for this Qwen application.')
official('s_whisper_header','official_source','Exact pinned Whisper-small serialized tensor header','https://huggingface.co/openai/whisper-small/resolve/'+WH+'/model.safetensors',WH,'Original publicly served checkpoint tensor metadata; raw range header independently read.','Read479 tensors, multiply each shape and sum241734912, no full weights downloaded or loaded; exact header excludes duplicate shared projection, checked official Transformers tie declaration. Primary card rounded244M is not used for this exact count.')
official('s_whisper_config','official_source','Pinned Whisper generation configuration','https://huggingface.co/openai/whisper-small/blob/'+WH+'/generation_config.json',WH,'Original model’s task/language/decoder token configuration.','Read lang_to_id zh50260, task_to_id transcribe50359, decoder_start50258, no_timestamps50363, eos50257, all raw prefix/suffix counts/EOS checked against records.')
official('s_whisper_source','official_source','Transformers actual-version Whisper model implementation','https://github.com/huggingface/transformers/blob/v4.57.6/src/transformers/models/whisper/modeling_whisper.py','transformers4.57.6','Official versioned model implementation for recorded inference package.','Read WhisperForConditionalGeneration,_tied_weights_keys=[proj_out.weight], decoder embed input and shared output projection. Used to interpret independent safetensors shape count without double counting tied parameter.')
official('s_fleurs_card','official_docs','FLEURS pinned official dataset card','https://huggingface.co/datasets/google/fleurs/blob/'+FL+'/README.md',FL,'google/fleurs official publication dataset description.','Read Dataset Description, Data Fields/Splits/Creation and Other Known Limitations: FLoRes sentence speech, raw transcription and transcription distinct; train/validation/test; train speakers differ dev/test, no proof dev vs test speaker disjointness; read-speech/noisy-domain mismatch. Download SHA matches localcard878990a8…; no assistant response field.')
official('s_fleurs_paper','paper','FLEURS: Few-shot Learning Evaluation of Universal Representations of Speech','https://arxiv.org/pdf/2205.12446v1','arXiv2205.12446v1,2022','Original FLEURS authors’ corpus paper.','Read §2.1/Table1 and script footnote: Wikipedia/FLoRes sentences read by native human speakers, workers validate recordings,16kHz, raw recordings kept; new sentence splits1509/150/350; Mandarin renamed from Chinese(Simp), Cantonese from Chinese(Trad). No inference of Taiwan accent/speaker balance in12-case subset. The primary texts’ split wording is not expanded into dev/test individual-speaker proof.')
official('s_fleurs_loader','official_source','FLEURS original version loader','https://huggingface.co/datasets/google/fleurs/blob/'+FL+'/fleurs.py',FL,'Official loader specifies cmn_hans_cn and TSV semantics.','Read config list and _get_data lines168–199, _generate_examples201–229: raw_transcription is field3, normalized transcription field4, frames field6; no chat-question/assistant-answer field. Compare all42 selected local reference strings to original localtrain/dev/test TSV; original double quotation marks preserved, not CSV-unquoted.')
official('s_uax15','official_docs','Unicode Standard Annex15 normalization forms','https://www.unicode.org/reports/tr15/tr15-55.html','UAX15revision55,Unicode16.0.0,2024-07-16','Unicode Consortium normative normalization annex.','Read §1.1,§1.2 and NFKC table: compatibility decomposition followed canonical composition; width compatibility folding. Tested actual Python3.13.5 UCD15.1 symbols１５→15,没/沒remain unequal; no Simplified/Traditional translation or punctuation deletion rule. Compatibility punctuation may change width/form.')
official('s_py_unicode','official_docs','Python3.13.5 unicodedata docs','https://github.com/python/cpython/blob/v3.13.5/Doc/library/unicodedata.rst','CPythonv3.13.5,UCD15.1runtime','CPython maintainers’ pinned standard library documentation.','Read normalize(form,unistr), NFKC compatibility decomposition then canonical composition. Actual examples recorded independently; no general script converter is invoked.')
official('s_py_strings','official_docs','Python3.13.5 str split/whitespace docs','https://github.com/python/cpython/blob/v3.13.5/Doc/library/stdtypes.rst','CPythonv3.13.5','CPython maintainers’ pinned Unicode string contract.','Read str.split(sep=None) consecutive-whitespace removal and str.isspace Unicode whitespace definition; joined split removes spaces,newlines,tabs,U+3000 after NFKC; codepoint sequence, not UTF8 bytes/tokens/graphemes.')
def repo(id,path,title,note,version='Current working file; SHA exact; recorded runtime revision638dc13c1598fb1cbfc097598081b0c27c35de55 checked separately'):
 sources.append({'id':id,'kind':'repository_code','title':title,'path':path,'sha256':digest(path),'version':version,'verified':True,'inspection_note':note})
repo('s_core','tiny_perceptron/natural_assistant.py','Actual common core/evaluation/ASR implementation','Read messages_for111–131/encode_messages133–147/generate308–360/train469ff/load_asr620–631/transcribe634–703/run_evaluate718–815. Training only LoRA core tensors; ASR eval and inference_mode, no update optimizer; no native wave input. ASR once outside both variant loops; typed uses row user, spoken uses hypothesis with same other fields. Actual638dc13c core is hash-identical. No serialized history in generate return.')
repo('s_cli','scripts/natural_assistant.py','Pinned CLI and interactive route','Read parser pin defaults, --history, max-new-token96 in96af0243 versus384 in213496fe/current; final and validation args explicitly384. chat audio calls ASR first then samecore; CLI preserves full interactivehistory but generation artifacts do not.')
repo('s_ui','tiny_perceptron/natural_ui.py','UI two-station/transcript-correction implementation','Read transcribe route168–175/chat179–214/client432–444: keep original ASRrecord, permit edited user prompt, append allhistory/images; text-only model prediction,noTTS; independent3 mocked-modelHTTPtests passed.')
repo('s_manifest','docs/natural-assistant/manifest.json','Actual frozen paired context and official refs','SHA7604526c…; every12 audio testrow has same system history 繁體簡短不要只重複, image absent,no previoususerturn, answer null, raw official reference; combined42 inspected. Frozen runtime638dc13c copy hash identical.')
repo('s_rubric','docs/natural-assistant/rubric.json','Pre-output grading contract','SHAa9d95ded…; commit96af0243 dated08:36:09 before pre-output review08:45 and finalresult09:46; chat relevance beyond replay,faithfulness,noinvented facts,instruction,history,stoprequired. summaries operational strict interpretation disclosed in final report. No rubric change by reviewer.')
repo('s_prepare','scripts/prepare_natural_speech.py','Official immutable speech source preparation','Read metadata split-tab parser69–90 and original WAV/exactsource selection/answer=null notes. FLEURS pin and source SHA validation; selected subset is not full-corpus download proof.')
sources.append({'id':'s_cer_math','kind':'derivation','title':'CER independent recurrence and micro denominator','verified':True,'details':'For reference r and hypothesis h, D[i,0]=i,D[0,j]=j,D[i,j]=min(D[i-1,j]+1,D[i,j-1]+1,D[i-1,j-1]+[r[i-1]!=h[j-1]]). Unit insertion/deletion/substitution distance is symmetric, so converting hypothesis→reference uses same minimum. MicroCER=sum distances/sum len(original reference), not mean per-sentenceCER. All exact per-record raw and normalized numerators and reference denominators are retained in audit.final12; totals independently checked150/481 and129/464. No project metric import.'})
def ev(id,locator,supports):return {'source_id':id,'locator':locator,'supports':supports}
def add(id,kind,statement,location,evidence,arts,scope,expected=None,observed=None,details=None,denom=None):
 c={'id':id,'kind':kind,'statement':statement,'location':location,'assessment':'supported','status':'verified','evidence':evidence,'artifact_ids':arts,'scope':scope}
 if kind in ['numeric','software','empirical']:
  c['verification']={'method':'executed','expected':expected or statement,'observed':observed or 'Independent saved-source/CPU audit matches this claim.','details':details or scope}
  if kind=='numeric':c['verification']['tolerance']='Integers and strings exact; CER floating ratio within1e-12 and percentage rounded to2 decimal places.'
  if kind=='empirical':c['verification']['denominators']=denom or {'test_recordings':'12','typed_replies':'12','speech_replies':'12','ASR_runs':'12 shared once','generation_cap':'384 chat/128 ASR','selected_variant':'adapter','split':'test','seed':'42','source_revision':'638dc13c1598fb1cbfc097598081b0c27c35de55','recorded_environment':'torch2.8.0+cu128;transformers4.57.6;chat NVIDIA L4 bfloat16;ASR CPU float32'}
 claims.append(c)
add('c1','concept','ASR转写说话内容与聊天作答是两种任务；上游改错题，可靠下游仍可能答另一题。','opening and前置paragraph',[ev('s_whisper_card','Model details/Usage','Transcription same-language audio→text, not an assistant answer.'),ev('s_whisper_paper','§2.3','Task specification and predicted spoken words.'),ev('s_core','run_evaluateactual/typed construction','Downstream receives actualhyp or ref separately.')],['a_manual','a_audit'],'Transparent artificial error-card explains error propagation; no measured sum-model ability implied.')
add('c2','software','本应用语音先ASR再同一图文聊天核心，波形不直接进入core；没有TTS。','second andlast applicationparagraphs',[ev('s_core','encode_messages/load_asr/run_evaluate','core accepts text/images, independent transcribe route.'),ev('s_ui','transcribe andchat endpoint/client','Outputs textualprediction and editable transcript.')],['a_supp','a_ui','a_notes'],'Applies to this fixed application; direct acoustic LM route remains another trained architecture, no native-chat capability claim.')
add('c3','numeric','人工卡输出False、15、5；Python sum实际算数，字串与两个数字组均人工写入。','Python fence/next paragraph',[ev('s_audit','sum_and_exercise[0]','Literal code extracted from currentsection executed.')],['a_audit','a_code_sum-card_py','a_log_sum-card_stdout_txt'],'No parsing,ASR recording,LM generation or tool-selection/readback measured.',observed='False;sum(13,2)=15;sum(3,2)=5.')
add('c4','numeric','只补recognized与recognized_numbers的练习输出True、15、15。','lastparagraph exercise',[ev('s_audit','sum_and_exercise[1]','Independent literalexercise actual execution.')],['a_audit','a_code_exercise_py','a_log_exercise_stdout_txt'],'Repairs manualcard only; not secretly correcting formalASR outputs.',observed='True;15;15.')
add('c5','concept','同样原意的正确文字、实际ASR聊天与转写CER应分开保存；CER低和两路相同不足以证明回答正确。','正式验收paragraph',[ev('s_whisper_card','Performance andLimitations','ASR can hallucinate and is domain dependent.'),ev('s_whisper_paper','§2.3','Recognition predictions are not assistant-response evaluation.'),ev('s_rubric','speech/chat/completion','Actualhyp, same criteria, stopping vs semantictruth separate.')],['a_manual','a_audit'],'This case’s source/transcript/reply failure modes support diagnostic separation, not universal causal estimates.')
add('c6','concept','真人朗读成绩不能代表合成人声之外所有口音/噪声/长语音，朗读转写不等于聊天监督。','真人data andlast limitations paragraphs',[ev('s_fleurs_card','Other Known Limitations/Data Fields','read-speech/noisyproduction mismatch; transcript fields only.'),ev('s_whisper_card','Performance andLimitations','Different language/accents and conditions vary.'),ev('s_fleurs_paper','§2.1/Table1','Read human sentence corpus.')],['a_notes'],'No audio playback/accent/quality judgment. No untested Taiwan/spontaneous/multi-speaker performance claim.')
add('c7','software','两路接回同样历史与照片的比较原则在本12题落实为同一system设置、无图、无此前userturn。','historyparagraph andchat comparisonparagraph',[ev('s_core','messages_for/run_evaluate','Only user andtask are changed; allother row contextshared.'),ev('s_manifest','12testaudio rows history/image','Single same system instruction,no images/prioruser.')],['a_supp','a_audit'],'Verified by frozenmanifest/runtime638dc13c source hash and raw input/image fields. Raw generations do not save complete serialized prompts, so not separately instrumented inference-time history replay.',observed='messages_for executed12pairs; priorcontexts identical,images0,previoususerturns0.')
add('c8','empirical','最后12段cmn_hans_cn真实人类朗读WAV总131.98秒。','最后测试 paragraph',[ev('s_fleurs_paper','§2.1/scriptfootnote','Humanread Mandarin/Simplified origin.'),ev('s_audit','original42 andfinal12 SFmetadata','Exact bytes,reference source anddurations independently checked.')],['a_audit','a_tsv_test','a_speech_manifest'],'Only these12 selected officialtestWAV, not wholecorpus or verified accent/speaker representativity.',observed='12mono WAV;all16000Hz;2111680frames/16000=131.98s.')
add('c9','software','Whisper-small固定973afd…且chinese/transcribe，实际ASR在CPU float32；其权重没有由本课录音训练更新。','Whisper paragraph',[ev('s_whisper_card','Model details','Originalpretrained ASR origin.'),ev('s_core','load_asr/transcribe/run_train','Fixedrevision,eval/inference_mode;ASR notoptimizer andnoASRtrainpath.'),ev('s_cli','modelpins/runner options','Immutablepins match recordedprovenance.')],['a_supp','a_final_result','a_final_execution','a_train_execution'],'Operationallyfrozen; does not mean load_asr callsrequires_grad_(False),which it does not. No inference rerun/weight-state forensic guarantee.',observed='Fixedprimary card/config,actualruntimecore/CLI,result.asr deviceCPU,readtrainoptimizer onlyLoRA.')
add('c10','numeric','精确固定Whisper-small参数总241,734,912。','Whisperparagraph exactcount',[ev('s_whisper_header','479serializedtensor shape products','Exactindependent count.'),ev('s_whisper_source','WhisperForConditionalGeneration._tied_weights_keys','Shared output projection excluded from duplicate count.')],['a_fetch','a_supp','a_primary_whisper-header_json'], 'Exactspecifiedcheckpoint,notcoarse244Mfamilylabel;modelweightsnotloaded.',observed='sum479shape products=241734912 matches actualresult.asr.parameters.')
add('c11','concept','FLEURS选材为公开真人朗读陈述，有原转写但无本子集官方助手回覆标注；不是即兴日常对话。','sameparagraph dataset scope',[ev('s_fleurs_card','Dataset Description/Data Fields/Other Known Limitations','Readspeech andtranscription fields.'),ev('s_fleurs_loader','_get_data/_generate_examples','Noassistantanswerlabels.'),ev('s_fleurs_paper','§2.1/Table1','PublicFLoRes readsentences.')],['a_audit','a_speech_manifest'],'All42selectedrefs exact rawTSV;train/dev/test officialsplits retained;speaker null,not devtestspeaker-disjointness proof;rawquotesnotrewritten.')
add('c12','numeric','CER为最少插删替换次数/原参考字元数；原始microCER150/481=31.19%。','CERdefinition/rawpercentageparagraph',[ev('s_cer_math','FullWagner-Fischer recurrence/microdefinition','Minimumunitcodepointeditdistance and reference denominator.'),ev('s_audit','final12/totals','Independentfullmatrix notprojectfunction.')],['a_audit','a_final_transcripts'],'OriginalUnicodecodepoints includingwhitespace/punctuation,notbytes,tokens,graphemes,oraverageofperutteranceratios.',observed='150/481=0.31185031185031187;31.19%.')
add('c13','numeric','NFKC后移除Unicode空白得到129/464=27.80%；没有删除标点或繁简转换。','same CERparagraph',[ev('s_uax15','§1.2NFKCtable','Compatibilitydecomposition+canonicalcomposition.'),ev('s_py_unicode','normalize','ActualPythonAPI semantics.'),ev('s_py_strings','str.split/str.isspace','JoinedUnicodewhitespace splits.'),ev('s_audit','normalizedref/prediction/totals','Actualindependent codepoint result.')],['a_audit','a_final_transcripts'],'NFKC may change compatibilitypunctuationwidths e.g，→, but punctuation isretained after normalization. ActualUCD15.1;noassumed globallyunchangedscript.',observed='129/464=0.27801724137931033;27.80%.')
add('c14','numeric','NFKC将１５变15；没与沒仍不相等，形成一字替换计分。','CERparagraph width andscript example',[ev('s_uax15','§1.1/§1.2','Widthcompatibility folding doesnotdefineTraditional/Simplifiedtranslation.'),ev('s_py_unicode','normalize','APIusedinactualexample.'),ev('s_audit','unicode_examples','Actualvalues FF11FF15→00310035,6CA1and6C92unaltered.')],['a_audit'],'Theseexactsymbols tested under3.13.5/UCD15.1;notallCJKcompatibilitycharacters unchanged.',observed='１５→15;没→没;沒→沒;independentdistance1.')
add('c15','software','12个ASR序列都EOS结尾，未截断/未知结尾；正常停止不等于准确转写。','CERparagraph stop statement',[ev('s_whisper_config','generationconfigEOS/promptids','PrimaryexpectedEOS50257.'),ev('s_core','transcriberawModelOutput andflags','Prompt/suffix stoppingrecordingcontract.'),ev('s_audit','12tokenrows','Countedrawprefix/suffix,EOSandlimits.')],['a_audit','a_final_transcripts'],'ASREOS decoderstoppingonly,notcomplete recognition or audiointelligibility.',observed='12suffixlast50257;allprefix50258/50260/50359/50363,allcounts<128,noflags.')
add('c16','empirical','正文字直接同核聊天与真实ASR文字聊天分别完整成功4/12、1/12。','pairedtable',[ev('s_supp','finalsuccesscomparison24items','Ownchoices savedbeforeexistingreportcomparison.'),ev('s_rubric','chat/speech/completion','Samefaithfulness/relevance/instruction/stopcriteria.')],['a_manual_before','a_manual','a_supp','a_final_generations','a_semantic_final'],'Manualjudgmentsofsavedoutputs,notnewASR/LMtest.4typedwinnersnewbeginning/metals/telescope/animal;1ASRwinnernewbeginning. Generalchat4/4andhistory1/2excluded.',observed='Own24rawanswer choicesexactlyagreeall24withreportedtaskoutcomes.')
add('c17','software','两路聊天各12个EOS结尾，但停止正常仍不能使语义/要求失败变成功。','aftertableparagraph',[ev('s_core','generatesuffix/EOS/flags','Chatstoppingseparatefromscore.'),ev('s_audit','typed/speech tokenrows','Each12rawlasttokenallowedEOS.')],['a_audit','a_manual'],'12recordsperspokenrouteandtypedroute,not24ASRruns;allmax384,noneofthese24truncated.',observed='12typed and12speech stop=eos,noneunknown/truncated;fullsuccess4 and1.')
add('c18','software','只重播/同命题摘要判任务未完成，忠实与回复要求分开；此要求输出前固定。','aftertablegradingparagraph',[ev('s_rubric','relevance/instruction/speechpairedreview','Frozenno-only-replaycontract.'),ev('s_manifest','speechhistory','Explicit繁體简短不要只重複.'),ev('s_supp','preoutputchronology','08:36commit/preoutput08:45 beforefinal09:46.')],['a_manual_before','a_manual','a_supp','a_pre_output'],'Blog/organizationfaithfulsummaryborderlinespreserved.Operationalstrictinterpretationnotuniversalconversationmetric;EOScannotrescuewrongcontent.',observed='Independentdimensiontypedfaithful10/12,beyondreplay6/12,traditional10/12;ASR4/12,8/12,10/12;intersections4 and1.')
add('c19','empirical','桥下净空/项目完工先在ASR损坏，语音答照抄错误；正文字答内容忠实但只重述仍未完成。','bridgeexampleparagraph',[ev('s_audit','row10048525650290665384','Originalrefandactualhyp exactlyverified.'),ev('s_supp','sameID24answercomparison','Wholeanswers/readbackseparated.')],['a_audit','a_supp','a_final_transcripts','a_final_generations','a_manual'],'原桥下15米2011/8完工2017/3通车，hyp乔夏进空盖像墨鱼晚供；notlistening-basedcause claim.',observed='Allquotedref/hyp/bothanswers verbatimmatched source;typedfaithful=true/beyond=false;ASRfaithful=false/beyond=false.')
add('c20','empirical','海滩树名/树荫被ASR写错；语音答新增新西兰所在地与树鹰判断；正文字答也新增热带/半球，无据聊天错误独立存在。','beachexampleparagraph',[ev('s_audit','row10134195680525011353','Exactoriginaltree/shadeandactualhyp.'),ev('s_supp','sameIDwholeanswers','Bothcompletedanswersreadindependently.')],['a_audit','a_supp','a_final_transcripts','a_final_generations','a_manual'],'Noassertionwhichhemisphere/climatetheunlocatedsiteactuallyhas;onlysource-groundingfailure,noaudioqualityclaim.',observed='Ref新西兰圣诞树的树荫;hyp新西兰生难受的树鹰;spokenNewZealandbeachlocationandtyped熱帶/not南半球 unsupported.')
add('c21','empirical','此前384-token相同6题验证：文字base0/6 adapter0/6，原始语音base0/6 adapter1/6。','validationcomparisonparagraph',[ev('s_supp','validationrecords andtotals','Independentlyreadall24rawvalidationanswersandstops.'),ev('s_core','ASRsharedbeforevariantloop','Same6ASRhypothesisusedbothvariants.')],['a_supp','a_validation_generations','a_validation_execution','a_semantic_validation'],'Onlypredeclared6readstatements.validationnotfinal12.OnlyadapterASRAmazonreacheslimitationresponsepasses;noworldriverwidthtruthestablished.',observed='Raw384args/6eachvariant;typed0,0;ASR0,1.',denom={'officialdevcases':'6','typedpersavedvariant':'6','ASRreplypersavedvariant':'6','ASRruns':'6 once shared','chatcap':'384','split':'validation','seed':'42','run':'gha-37190445616-1','revision':'213496fe63f338a16026c2eb131e3e39faa24721'})
add('c22','software','96-token原试跑和384-token成对验证是不同预算；换上限不能凭本记录宣称训练增益。','samevalidationparagraph',[ev('s_cli','actual96af0243 vs213496fe parserdefaults/executionargs','Initial96defaultandexplicit384validation/final.'),ev('s_supp','sourceversions','Recoveredexacthistoricalsourceandbudget.')],['a_supp','a_baseline_execution','a_validation_execution'],'Nocrossbudgetcausaltrainingeffectinferred;onlymatched384comparisonsstated,notASRimprovement.',observed='HistoricalCLIdefault96;validationexplicit384;finalexplicit384;sameASRoutsidevariantloops.')
add('c23','software','两聊天版本共用同一次ASR原稿，不存在微调前后ASR改善可报。','validationparagraph end',[ev('s_core','run_evaluate746–805','transcribeonce thenbothvariantcontexts;coreLoRAonly.'),ev('s_supp','actualcode/hypothesispairedinputs','Recordedversionandactualuserstrings.')],['a_supp','a_final_transcripts','a_validation_execution'],'NoASRfine-tuningrun. ThisexcludesaclaimedbeforeafterASRchangefromtheseoutputs,notallpossiblefuturetraining.',observed='SharedoneASRsetperstage;bothversions use samehypstrings.')
add('c24','software','UI显示原ASR后让用户明确更正送出，原稿保留；当前文本答，无波形core或TTS。','applicationparagraph',[ev('s_ui','API168–214/client432–444','ASRrawkeptandcorrectedflag,editedprompttosamecore.'),ev('s_ui_execution','existing3HTTPtests','Originaltranscript/correction/history/imagecontract exercised.')],['a_ui','a_notes'],'StubbedASR/chatHTTPtestsproveapplicationwiringonly,notmodelquality;formalevaluation still usesuncorrectedASRhyp.',observed='3existingtestsactualpassed;noASR/chatmodelloaded.')
# Optional tokenizer audit additionally ties every actualhyp string to primary rawtoken IDs, no model.
if Path(P+'tokenizer-audit.json').exists():
 ta=read('tokenizer-audit.json');te=read('tokenizer-execution.json');assert te['exit_code']==0
 ownart('a_tokenizer','tokenizer-audit.json','execution','12个ASR原token序列由固定primary tokenizer独立解码，与实际hyp逐字相同；原prompt/EOS名字明确核对。',{'command':te['command'],'result':'Exit0;12/12rawtoken sequences decodeexactlytosavedhyp;allzh/transcribe/no-timestamps andendoftextverified,no modelweightsloaded.','environment':ta['environment']})
 for n in ['tokenizer-audit.py','tokenizer-audit.stdout.json','tokenizer-audit.stderr.txt','tokenizer-execution.json','whisper-tokenizer.json']:ownart('a_tok_'+n.replace('.','_'),n,'code' if n.endswith('.py') else 'source_snapshot','固定primaryTokenizeronly核对脚本/下载与执行证据；未载模型。')
 official('s_tokenizer','official_source','Pinned Whisper tokenizer','https://huggingface.co/openai/whisper-small/blob/'+WH+'/tokenizer.json',WH,'Originalcheckpointtoken vocabulary/decoder.','Independenttokenizersdecodeofeach12rawsequenceexactlysavedspeechhyp;specialprefixstartoftranscript/zh/transcribe/notimestamps;finalendoftext,noaudio/modelcall.')
 for c in claims:
  if c['id'] in ['c9','c15']:c['artifact_ids'].append('a_tokenizer');c['evidence'].append(ev('s_tokenizer','12rawtoken sequences/prefix/EOS','DecodedhypandtasktokensmatchsavedactualASRdata.'))
report={'schema_version':1,'review_stage':'technical','lesson_id':'20.7','source':'course/chapters/20.md#20.7','reviewer_task':'/root/natural_factual_final_20_7','reviewer_context':'fresh','author_tasks':['/root','/root/natural_curriculum_v3','/root/natural_results_author_20_7'],'source_sha256':audit['source_sha256'],'figure_sha256':{'course/figures/natural_shared_chat.svg':render['figure_sha256']},'verdict':'pass','claims':claims,'sources':sources,'artifacts':artifacts,'issues':[], 'checks':{
'factual_accuracy':{'status':'pass','details':'24substantiveclaims independentlysupported; ASR/core/taskanddata scopekeepseparate. Allraw24selectedanswersread andownoutcomescompared afterinitialjudgment.','claim_ids':[c['id'] for c in claims]},
'numeric_verification':{'status':'pass','details':'Executedmanualsum/exercise;42rawTSVrefsunchanged;12WAVhash/SFmetadata;independentfull-matrixCER150/481 and129/464;header241734912;EOS12perroute;own4/12 and1/12;validation0/6,0/6 and0/6,1/6. NoGPU/training/modelrerun.','claim_ids':['c3','c4','c8','c10','c12','c13','c14','c16','c21']},
'figure_consistency':{'status':'pass','details':'20.7hasnodirectSVG,butactual720/358rendersoftheexplicit20.1/12.14prerequisitecommonsystemdiagramviewed.TextbypassesASR,speechusesactualtranscript,bothjoinhistoryandonecore,photoonlyenterscore,outputtext,noTTS. Architectureisnotqualityevidence.','claim_ids':['c2','c7']},
'source_verification':{'status':'pass','details':'OriginalfixedWhisper/FLEURScards,papers,officialFLEURSloader,Whisperheader/config/tokenizer,Transformers4.57.6,UAX15rev55andCPython3.13.5docsactuallyread;exactruntimeGitcode andlocalTSV independentlychecked. Semanticreport issecondarycross-checkonly.','claim_ids':['c1','c6','c8','c9','c10','c11','c12','c13','c14','c15','c16','c18','c21']},
'limitations':{'status':'pass','details':'Nohearing/accentspontaneity/worldknowledgetest,nohiddenASRGTsubstitution,noASRtraining,TTS,nativewavecoreorbudgetswapgain.Nooriginalfullserializedmessages;contextclaimrests onfrozenmanifest/sourceandrawinputs,clearlylimited. Smallstrictreplycontractandborderlinespreserved,otherchat4/4/history1/2excluded. NFKCcompatibilitypunctuationfoldingnotdeletionorTrad/Simpconversion;EOSnottruth.','claim_ids':['c2','c5','c6','c7','c9','c11','c13','c15','c16','c18','c20','c21','c22','c23','c24']}},'review_limits':{'audio_played':False,'ASR_or_chat_inference_rerun':False,'GPU_used':False,'training_performed':False,'serialized_original_inference_history_available':False,'own_independent_full_answer_judgments_before_comparison':True,'only_selected_adapter24_final_speech_related_answers_regraded':True,'validation24_speech_related_answers_read':True,'source_chapter_and_source_code_modified':False,'assessment_mapping':'supported=>schema statusverified; revise/uncertain would requireverdictrevise.'}}
# Keep review text readable; schema status words are unchanged.
def spaces(x):
 return x
Path('docs/technical-reviews/20.7.json').write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n');print(json.dumps({'verdict':report['verdict'],'claims':len(claims),'sources':len(sources),'artifacts':len(artifacts),'source_sha256':report['source_sha256']},indent=2))
