"""Write this reviewer's complete new report; never read the old report."""
import hashlib
import json
from pathlib import Path

out=Path(__file__).resolve().parent
root=out.parents[3]
rel=out.relative_to(root).as_posix()
def sha(p): return hashlib.sha256(p.read_bytes()).hexdigest()
inspection=json.loads((out/'inspection-receipt.json').read_text())
frozen=json.loads((out/'frozen-inputs.json').read_text())
ex=json.loads((out/'extraction.json').read_text())
cpu=json.loads((out/'cpu-check.stdout.txt').read_text())
env={k:str(v) for k,v in cpu['environment'].items()}
artifacts=[]
def art(identifier,file,kind,description,**extras):
    p=out/file
    artifacts.append({'id':identifier,'path':rel+'/'+file,'sha256':sha(p),'kind':kind,'description':description,**extras})

for identifier,file,kind,description in [
 ('section','section.md','source_snapshot','本次 11.10 原始 UTF-8 bytes，含標題到下一節前，無換行正規化。'),
 ('chapter-frozen','inputs/course/chapters/11.md','source_snapshot','2026-10-05 當次 frozen input 整章 bytes；實際閱讀只為 11.10，非目前全章審閱宣稱。'),
 ('frozen-inputs','frozen-inputs.json','source_snapshot','當次 frozen input 日期、快照、全檔 SHA、Git HEAD 與真實閱讀 scope。'),
 ('inspection','inspection-receipt.json','source_snapshot','本人真實 AST/code line ranges、raw JSON pointers、官方來源讀取定位、視覺查看與支持界線。'),
 ('raw-result','inputs/docs/course-experiments/results/vision_ablation.json','source_snapshot','完整未改原始歷史實驗 bytes；本人只查 raw config/history/samples/provenance，未讀額外作者結果解釋。'),
 ('fence-code','fence-1.py','code','原 fence 的完整未修改 code bytes。'),
 ('fence-extraction','extraction.json','source_snapshot','原小節與原 fence 擷取的事實 metadata；整檔 SHA 只對應當次 frozen chapter input。'),
 ('fence-bootstrap','bootstrap.py','code','原 helper 實際執行的 repository BOOTSTRAP bytes。'),
 ('fence-environment','environment.json','source_snapshot','實際 .venv/CPU/offline guard 環境、版本、嘗試 fence 1、無 guard events。'),
 ('fence-receipt','execution.json','source_snapshot','原 helper 真實 command、exit0、stdout/stderr SHA 和執行 environment locator。'),
 ('fence-stderr','stderr.txt','source_snapshot','原 fence 實際空 stderr。'),
 ('cpu-code','verify_cpu.py','code','本人有界 CPU axis/count/capacity/projection 與原歷史 raw record audit 程式；零 optimizer steps、零既有 checkpoint 讀取。'),
 ('cpu-stderr','cpu-check.stderr.txt','source_snapshot','本人有界 CPU audit 實際空 stderr。'),
 ('command-runner','run_checks.py','code','真實 command/stdout/stderr/exit 及 source/figure render receipts 的執行程式。'),
 ('commands','command-receipts.json','source_snapshot','各實際命令及 stdout/stderr SHA；包含 direct Chromium timeout124，保留工具限制。'),
 ('detail-code','detail_control.py','code','本人條件可能性的手設線性入口反例：細分可保留某些小尺度差異，零訓練。'),
 ('detail-receipt','detail-control-receipt.json','source_snapshot','手設入口反例 command、exit0、stdout/stderr SHA。'),
 ('browser-code','render_browser.py','code','本人以 Playwright 驅動 /usr/bin/chromium，核原七段正文與原 fence 後擷取現存单節頁面。'),
 ('browser-receipt','browser-render-receipt.json','source_snapshot','成功頁面 command 與 stdout/stderr SHA。先前工具失敗另存，不以失敗宣稱已驗證。'),
 ('patch-figure','inputs/course/figures/rewrite-10-patch-order.svg','source_snapshot','必要前置 10.2 原 SVG bytes。'),
 ('patch-render','render/patch-order.png','figure_render','Inkscape 真實渲染並用 view_image 查看：4x4=16 row-major patches；每塊48個 RGB 值。'),
 ('page-desktop','render/page-desktop.png','figure_render','現存 11.10 頁面，1280x800 viewport/full-page capture，真實查看數字、正文與程式呈現。'),
 ('page-mobile','render/page-mobile.png','figure_render','現存 11.10 頁面，390x844 viewport/full-page capture，真實查看；程式長行為橫向 code overflow。'),
 ('page-html','render/desktop-served.html','source_snapshot','現存單節 server response bytes，七段正文與原 fence 都核對相同；未全課程 export。'),
 ('vit-original','sources/vit-v2.pdf','source_snapshot','ViT 作者原論文 arXiv2010.11929v2 原 PDF bytes；親核版本及內容。'),
 ('vit-text','sources/vit-v2.txt','source_snapshot','本次對原 ViT PDF pdftotext -layout 產物；原檔未改，讀取位置另記。'),
 ('vit-render','render/vit-page3.png','figure_render','原 ViT p3 真實 render/view，直接核 N=HW/P^2 與 patch embedding 說明。'),
 ('attention-original','sources/attention-v7.pdf','source_snapshot','Attention Is All You Need 作者原論文 arXiv1706.03762v7 原 PDF bytes。'),
 ('attention-text','sources/attention-v7.txt','source_snapshot','本次原 Transformer PDF 的 pdftotext -layout 產物，Eq1、decoder mask、Table1 定位。'),
 ('attention-render','render/attention-page4.png','figure_render','原 Transformer p4 真實 render/view，直接核 QK transpose、softmax 與 attention 公式。'),
 ('linear-original','sources/linear.py','source_snapshot','官方 PyTorch immutable commit 的原 Linear API source，AST 後讀原形狀契約。'),
]: art(identifier,file,kind,description)
art('fence-execution','stdout.txt','execution','本人實際執行原 11.10 fence，三組輸出與原稿完全一致。',command='.venv/bin/python docs/review-tools/section_facts.py course/chapters/11.md#11.10 --output /tmp/phase4-11_10-clean-fence --execute --timeout 60',result='exit0; fence1 executed; (visual,total,cells) = (4,24,576),(16,36,1296),(64,84,7056); raw permanent stdout/environment/execution receipts copied without content changes.',environment=env)
art('cpu-execution','cpu-check.stdout.txt','execution','本人真實有界 CPU 檢查與原始歷史樣本 audit 的完整結果。',command='.venv/bin/python docs/technical-reviews/artifacts/phase4-11_10-clean/verify_cpu.py',result='exit0; all assertions passed; 32x32 result276/76176; dense/query-key axes and causal cells checked;48-to12 projection rejected;84 rejected at limit64; historical 4/8 both9/12,200updates,4765training answer tokens,72test target tokens; no training, checkpoints or model retest.',environment=env)
art('detail-execution','detail-control.stdout.txt','execution','本人手設線性入口的可能性證明，核「可能」而非已測能力。',command='.venv/bin/python docs/technical-reviews/artifacts/phase4-11_10-clean/detail_control.py',result='exit0; same local bright/dark detail leaves0changed coarse mean features and2changed fine mean features; fixed map,zero learning; no trained encoder or task accuracy claim.',environment=env)
art('browser-execution','browser-render.stdout.txt','execution','本人單節頁面 source match 與真實 browser capture receipt。',command='.venv/bin/python docs/technical-reviews/artifacts/phase4-11_10-clean/render_browser.py',result='exit0; both served pages HTTP200; original7paragraphs and originalfence exact match; Chromium151.0.7922.173; desktop1280x800/mobile390x844 screenshots actually viewed.',environment={'python':env['python'],'device':'CPU browser rendering','chromium':'151.0.7922.173','renderer':'Playwright with /usr/bin/chromium; external requests aborted,local assets allowed'})

sources=[]
for s in inspection['official_originals']:
    sources.append({'id':s['id'],'kind':'official_source' if s['id']=='linear' else 'paper','title':{'vit':'An Image is Worth 16x16 Words: Transformers for Image Recognition at Scale','attention':'Attention Is All You Need','linear':'torch.nn.Linear official source'}[s['id']],'url':s['url'],'version':s['version'],'authority_reason':s['authority'],'accessed_on':'2026-10-05','verified':True,'checked_original':True,'inspection_note':s['inspected']+' 支持界線：'+s['support_boundary']})
for identifier,path,title,note in [
 ('multimodal','tiny_perceptron/multimodal.py','Repository image entry and multimodal expansion','AST first; personally read12-41,84-135,139-190: actual patch coordinate/shape, projection and position config, marker expansion/shift, capacity check and scene generator.'),
 ('model','tiny_perceptron/model.py','Repository TinyLM capacity contract','AST first; personally read15-28,54-86: configured max_length, input/embedding last axis, guard on offset+t,random-model structural forward only.'),
 ('attention-code','tiny_perceptron/attention.py','Repository dense manual attention','AST first; personally read10-74: query/source axes, N by N score allocation,softmax over key columns,causal mask,heads/cache branches.'),
 ('tokenizer','tiny_perceptron/data.py','Repository ByteTokenizer scoring contract','AST first; personally read14-28: special IDs,encode UTF8 bytes+8,decode; used only to recompute recorded exact content and EOS.'),
 ('experiment','scripts/course_experiments/modalities.py','Original vision-ablation experiment methods','Recorded original revision22a0bb1b870e4df4af76630243ef55b7ca27840c; git show bytes SHA matches original result/code_sha256 and current file. AST then personally read27-29,37-53,56-192,219-283,287-384,772-821. Original split/target/update/sample/score/budget methods inspected; author-added explanatory return literals822-830 not read. Patch variants inherit SFT language, fresh vision encoders; same seed and answer-sampling/update budget, unequalparameter/FLOP budgets.'),
]:
    sources.append({'id':identifier,'kind':'repository_code','title':title,'path':path,'sha256':sha(root/path),'version':'Frozen original bytes inspected2026-10-05; '+frozen['git_head']+' checkout, historical experiment revision22a0bb1b870e4df4af76630243ef55b7ca27840c where applicable','verified':True,'inspection_note':note})
for identifier,artifact,title in [('fence-run','fence-execution','Original arithmetic fence actual execution'),('cpu-run','cpu-execution','Independent CPU axis/capacity and historical raw measurements audit'),('detail-run','detail-execution','Constructive conditional-detail calculation'),('browser-run','browser-execution','Original single-section page actual rendering')]:
    sources.append({'id':identifier,'kind':'execution','title':title,'artifact_id':artifact,'verified':True})
sources.append({'id':'counts','kind':'derivation','title':'Independent position and matrix-cell arithmetic','verified':True,'details':'For square H divisible by P, patches=(H/P)^2; each RGB patch has3P^2 values; full unshifted material positions=20+patches; full logical dense score table per head=total^2. H16:P8=>4/24/576,P4=>16/36/1296,P2=>64/84/7056. H32=>16/36/1296,64/84/7056,256/276/76176. Causal allowed entriesN(N+1)/2 differ from full logical tableN^2; neither is measured seconds. Weight shape(out,in) for width16 is(16,48),(16,12),(16,192); projection weight counts768,192,3072 excludebias andpositional parameters.'})

def evidence(s,l,support):return {'source_id':s,'locator':l,'supports':support}
claims=[
 {'id':'patch-mechanism','kind':'concept','statement':'每個 visual token 在本節是整塊圖片的一個特徵位置；細切增加位置，可能保留入口壓縮後的小尺度差異，但本節沒有宣稱已測得小物件／小字能力。','location':'course/chapters/11.md:353,367','scope':'Square RGB patch representation and conditional local-detail possibility; patchify itself retains pixels; learned-feature quality is not implied by patch count. ViT classification token is outside the lesson arithmetic.','status':'verified','evidence':[evidence('vit','section3.1 pp3-4,Eq1; section4 Model Variants p5','Patch flattened P^2 C input projected into one latent vector; N=HW/P^2; smallerP makes more sequence positions.'),evidence('multimodal','patchify12-17;VisionEncoder31-41','Actual repo output positions represent patches,not UTF8 characters; learnable projection follows pixel grouping.'),evidence('detail-run','detail-control.stdout.txt/results and scope','A hand-set linear average realizes a case where finer grouping retains small-scale contrast erased by coarser grouping; this is only a possibility proof.')],'artifact_ids':['detail-code','detail-execution','inspection','vit-original']},
 {'id':'position-arithmetic','kind':'numeric','statement':'原 fence 的4/16/64視覺位置、24/36/84總長、576/1296/7056格，以及32×32練習的16/64/256位置、最後276與76176均正確。','location':'course/chapters/11.md:357-364,367,377','scope':'Square16/32 images exactly divisible by patch8/4/2 and20extra text positions. Pure material-count example; not exact byte count of the historical prompt or shifted LM training length.','status':'verified','evidence':[evidence('fence-run','original fence1,source line358;stdout.txt','Original code truly ran,producing all three printed counts.'),evidence('counts','HW/P^2,20+patches,(20+patches)^2','Independent exact integer arithmetic,units are positions and logical attention cells.'),evidence('cpu-run','cpu-check.stdout.txt/arithmetic_and_axes and rectangular_control','Coordinate tensor patch sizes corroborate counts; H32 and nonsquare16x32 control checked,nondivisible17 rejects.')],'artifact_ids':['fence-code','fence-execution','cpu-code','cpu-execution'],'verification':{'method':'executed','expected':'H16:(4,24,576),(16,36,1296),(64,84,7056);H32:(16,36,1296),(64,84,7056),(256,276,76176).','observed':'All expected integer triples and actual tensor shapes matched; original fence exit0,independent CPU checks exit0.','details':'Direct row-major RGB coordinate checks rather than only patch/unpatch round trip;32exercise actually calculated; rectangular case exposes square-only scope; raw fence and commands preserved.','tolerance':'Exact integer equality; no rounding.'}},
 {'id':'attention-table','kind':'concept','statement':'完整注意力表每列為查詢／讀取位置，每欄為來源位置；圖片和文字共N個位置時完整表N×N。平方格數是dense注意力成本線索，不能當精確秒數。','location':'course/chapters/11.md:355,367','scope':'One head's logical full dense self-attention score table withoutcache. Causal permission count,heads/layers,featurewidth,FFN,backend/hardware and cached generation are separate cost factors.','status':'verified','evidence':[evidence('attention','section3.2.1 p4,Eq1;section3.2.3 p5;Table1 p6','QK transpose produces query rows by key columns; decoder masks illegal future sources; full self-attention asymptotic complexityO(n^2 d),not a wall-time measurement.'),evidence('attention-code','manual_attention21-28;CausalAttention48-74','Actual explicit matrix scores and source-axis softmax;causal mask and cache branches separate fromfull squaretable.'),evidence('cpu-run','cpu-check.stdout.txt/attention','Actual square tables576/1296/7056 cells checked; causal visible cells300/666/3570;2query-by3source control confirmsaxis mapping.')],'artifact_ids':['cpu-execution','attention-original','attention-render','inspection']},
 {'id':'entry-capacity-contract','kind':'software','statement':'RGB patch4與patch2的入口分別48和12值，舊48欄權重不能直接吃12值；patch8入口較大而位置較少。上限64放不下84位置，截斷可能把答案目標截光；加上限只驗結構容納，沒有證明任務已學好。','location':'course/chapters/11.md:369,371,373','scope':'This repo VisionEncoder/TinyLM/expand_modalities contracts. Weight columns are inputfeatures; sequence count and parametercount separate. Transfer via an explicit adapted/trained configuration is outside simple inference parameter change. Fullmaterial84 versus shifted83 is explicitly distinguished in the bounded illustrative target trace.','status':'verified','evidence':[evidence('linear','Linear53-88,constructor96-115,forward130-134','Official affine map's last-axis input contract and weight(out_features,in_features) shape.'),evidence('multimodal','VisionEncoder31-41;expand_modalities84-100;generate_modal148-160','Patch-specific projection/position dimensions; source-answer label expansion and shift;generation expanded-length guard.'),evidence('model','ModelConfig15-28;TinyLM54-86','Configured maximum is a guard on actual forward length,not a trained capability test.'),evidence('cpu-run','cpu-check.stdout.txt/entry_matrices,old_projection_rejected_new_patch,max_length,truncation_control','Actual shapes/rejections;64accept and84reject atlimit64;max128structurally accepts84;synthetic answer trace drops4targets to0 underprefix truncation.')],'artifact_ids':['cpu-code','cpu-execution','linear-original'],'verification':{'method':'executed','expected':'Projection weights(16,48)/(16,12)/(16,192); old48input projection rejects12;84>64 rejects;possible target truncation4=>0.','observed':'All expected contracts verified. Weight counts768/192/3072;patch4/8positions16/4. Actual TinyLM64accept,84reject andlarger128accept. Synthetic unshifted84 becomes shifted83;all4effective targets lie beyond first64.','details':'Small CPU forward/shape and errors only,no training or checkpoints. Shape/config mismatch established directly;no task accuracy attributed to random-model forward. Position embeddings and wholemodel parameters checked separately.'}},
 {'id':'historical-patch-contrast','kind':'empirical','statement':'既有patch4/8小對照兩者最後都是9/12，未測出細切優勢，也未測小字；它是有限合成形狀／顏色題的歷史紀錄。','location':'course/chapters/11.md:373,384','scope':'Recorded single seed42,offset2 test families;6images each asked shape/color=>12questions;shape3/6 andcolor6/6 bothvariants. Same200update and4765answer-token sampling budget;fullmodels145664/147776parameters,unequalFLOP/time budget. Not model rerun,equivalence proof,smalltext result,or general patchsize ranking.','status':'verified','evidence':[evidence('experiment','_vision_records171-192;_sequence246-257;_loss_fn260-283;_evaluate287-364;_fit73-168;run_vision_ablation804-821','Original target/split/score/paired variant construction and update budgets verified at recordedrevision. SFTlanguage inherited,fresh visionencoders,all parameters configured trainable; optimizer loop actually updates rather than just backward.'),evidence('tokenizer','ByteTokenizer14-28','Exact byte-token content beforefirstEOS is recomputed from rawgenerated IDs,target andencoder;EOS checked separately.'),evidence('cpu-run','cpu-check.stdout.txt/historical_audit and json_inspection_pointers','Rawrecords,splithashes,200history rows/variant,seededsampling targetcounts,24sample predictions andgroupcounts independently audited;no checkpoint evaluated.')],'artifact_ids':['raw-result','cpu-code','cpu-execution','inspection'],'verification':{'method':'executed','expected':'Both variants9correct/12questions=.75;testeffective targets72;shape3/6,color6/6;200updates and4765effective trainingtargets each;only4and8patch variants.','observed':'All raw samples/IDs andgroups reproduced those counts;EOS12/12,zero generationerrors/special-tokenerrors/skips. Family splits36/12/12 records and18/6/6families,offsets[-2,-1,0]/[1]/[2]disjoint;rawSHA andoriginal codeSHA match.','details':'Audit of existing original CUDA record2.14.1+cu126,Python3.13.3;bounded verification environment2.14.1+cpu,Python3.13.5. Sampling andhistory counts independently recomputed;no GPU,download,model training/model retest or neural.pt writing. Whole-model parameter counts recomputed withoutloading weights;all trainable is a configuration count,notproof everyparameter changed.','denominators':{'train_records':36,'train_image_families':18,'validation_records':12,'validation_image_families':6,'test_questions_per_variant':12,'test_image_families':6,'shape_questions':6,'color_questions':6,'test_answer_plus_eos_tokens':72,'updates_per_variant':200,'sampled_examples_per_update':4,'training_effective_answer_tokens_per_variant':4765,'seed':42,'runs_per_patch_size':1}}}
]
report={'schema_version':1,'review_stage':'technical','lesson_id':'11.10','source':'course/chapters/11.md#11.10','source_sha256':ex['source_sha256'],'reviewer_task':'/root/phase4_factual_coordinator/factual_11_10_clean','reviewer_context':'fresh','reviewed_at':'2026-10-05','verdict':'pass','figure_sha256':{'course/figures/rewrite-10-patch-order.svg':sha(root/'course/figures/rewrite-10-patch-order.svg')},'frozen_input':{'date':'2026-10-05','chapter_snapshot':rel+'/inputs/course/chapters/11.md','chapter_frozen_sha256':sha(out/'inputs/course/chapters/11.md'),'scope':'當次 frozen input 整章原始 bytes；真正本節讀取351-384及必要10.2/3.1。此全章 SHA 不冒稱 current 全章已查核。小節 source_sha256 對原始 bytes。','receipt':rel+'/frozen-inputs.json'},'independence':inspection['independence'],'inspection_receipt':rel+'/inspection-receipt.json','sources':sources,'artifacts':artifacts,'claims':claims,'issues':[],'checks':{'factual_accuracy':{'status':'pass','details':'整節實質主張按5個機制/計算/API/既有實测群組核對；未拿玩具對照替成熟方法下結論。','claim_ids':[c['id'] for c in claims]},'numeric_verification':{'status':'pass','details':'原fence真跑；16/32圖片各patch形狀和坐標直接查；完整注意力與因果允許格數、RGB欄/參數、max_length、target truncation與原樣本/更新分母均有CPU證據。','claim_ids':['position-arithmetic','entry-capacity-contract','historical-patch-contrast']},'figure_consistency':{'status':'pass','details':'11.10無直接嵌圖；N×N兩軸和方格計數由原文清楚定義，無必要缺圖。必要10.2原SVG真渲染查看16塊順序與48值；現存桌面/手機11.10正文與fence核版本並真view，非建置成功代替視覺。','claim_ids':['patch-mechanism','position-arithmetic','attention-table']},'source_verification':{'status':'pass','details':'親讀原作者ViT v2與Transformer v7 PDF版本頁、公式/段落/表，officialPyTorch immutableLinear source；來源庫僅定位原bytes。code先AST、JSON先key/type後rawpointers；額外作者結果解釋未讀。','claim_ids':['patch-mechanism','attention-table','entry-capacity-contract','historical-patch-contrast']},'limitations':{'status':'pass','details':'N²是full logicaldense per-headtable線索，不是seconds或cache/sparse算法承諾。patchify不丟像素；小尺度差異為条件可能性，歷史未測小物件/小字。12questions只有6images，單seed兩方案同分不是等效/普遍優勢；update/answer-token预算相同但params/FLOPs不同。整次未訓練/重測既有模型/下載模型資料/GPU/付費/.pt保存。','claim_ids':[c['id'] for c in claims]}},'tool_limitations':inspection['visual_inspection']['tool_limitations']}
target=root/'docs/technical-reviews/11.10.json'
target.write_text(json.dumps(report,ensure_ascii=False,indent=2,allow_nan=False)+'\n')
print(json.dumps({'report':str(target.relative_to(root)),'verdict':report['verdict'],'source_sha256':report['source_sha256'],'report_sha256':sha(target),'claims':len(claims),'artifacts':len(artifacts)},ensure_ascii=False))
