from pathlib import Path
import hashlib,json
ROOT=Path(__file__).resolve().parents[4]
ART=Path(__file__).resolve().parent
REL=ART.relative_to(ROOT).as_posix()
def sha(path):return hashlib.sha256(Path(path).read_bytes()).hexdigest()
env={'python':'3.13.5','torch':'2.14.1+cpu','numpy':'2.5.3','device':'cpu'}
artifacts=[]
def artifact(identifier,name,kind,description,**extra):
 a={'id':identifier,'kind':kind,'path':f'{REL}/{name}','sha256':sha(ART/name),'description':description,**extra};artifacts.append(a)
artifact('a1','verification-output.txt','execution','逐檔固定archive/record核對、分群、來源像素、字串/字型/ROI、錄音來源、輸入排除、原始15段metadata及test總數。',command='/workspace/tiny-perceptron-vlm/.venv/bin/python docs/technical-reviews/artifacts/p6-19.3/verify.py > docs/technical-reviews/artifacts/p6-19.3/verification-output.txt 2>&1',result='exit 0；verification_complete=true。archive全部8962項相符；local cache 6項差異另記。OCR原始像素train/validation交集1，沒有把此項說成零。',environment=env)
artifact('a2','helper-checks-output.txt','execution','原stage_records有界CPU執行、常數bag分類基線、size不變hash變動的拒絕及精確原始碰撞record副本。',command='/workspace/tiny-perceptron-vlm/.venv/bin/python docs/technical-reviews/artifacts/p6-19.3/helper-checks.py > docs/technical-reviews/artifacts/p6-19.3/helper-checks-output.txt 2>&1',result='exit 0；各stage train/validation數量吻合raw收據；固定bag分類600/1800；修改內容被verify_file拒絕；2條原始record已保存。',environment=env)
artifact('a_verify','verify.py','code','本輪實際執行的CPU資料查核程式，沒有訓練、模型generation或heldout評測。')
artifact('a_helpers','helper-checks.py','code','本輪實際執行的有限helper與基線查核程式。')
artifact('a_fig640','splits-640.png','figure_render','Inkscape 1.4實際render並view 640px：A三個衍生箭頭留train，boot明示train，B/C另留，與本文方法一致。')
artifact('a_fig360','splits-360.png','figure_render','實際render並view 360px，所有來源、用途、箭頭與標籤無裁切且一致。')
artifact('a_sklearn','sklearn-cross-validation.rst','source_snapshot','scikit-learn 1.7.2作者官方原始文件，親讀L60–82與L628–656。')
artifact('a_minds','minds14-original-README.md','source_snapshot','PolyAI/minds14固定40ce77cb版本原始dataset card，親讀L958–1005；與包中來源README原bytes一致。')
artifact('a_external','external-sources.json','source_snapshot','本輪原始權威URL、存取日期、完整檔SHA/size。')
artifact('a_voice','voice-audit.jsonl','source_snapshot','原始voice來源audit完整bytes副本；原件/副本SHA均c6e09647…；僅用source/分群/轉寫/錄音計數規約，非模型输入。')
artifact('a_collision','ocr-pixel-collision.json','execution','獨立查得train/validation完整PNG與decoded pixel相同的2條record來源與ROI。',command='/workspace/tiny-perceptron-vlm/.venv/bin/python docs/technical-reviews/artifacts/p6-19.3/collision-check.py',result='exit 0；唯一train/validation完整canvas碰撞為「左」：兩PNG SHA均908ce16c…、pixel SHA均32c5b9aa…；train ROI[16,8,52,44]，validation ROI[18,8,54,44]；兩原PNG副本bytes與原件相等。',environment=env)
artifact('a_collision_code','collision-check.py','code','本輪精確保存並執行的逐OCR完整canvas像素/SHA/來源記錄查核程式。')
artifact('a_collision_records','collision-original-records.jsonl','source_snapshot','OCR train L4122與validation L217原始JSONL行bytes的精確副本。')
artifact('a_collision_provenance','collision-record-provenance.json','source_snapshot','兩原record檔manifest SHA、原始JSONL行號、原行SHA，副本比對實際執行見a2。')
artifact('a_collision_png0','ocr-pixel-collision-0.png','source_snapshot','一張原始碰撞PNG的精確bytes副本，實際view可见左字；兩來源原PNG全檔SHA相同。')
artifact('a_collision_png1','ocr-pixel-collision-1.png','source_snapshot','另一來源碰撞PNG精確副本，SHA與第一张及兩原件完全一致。')
artifact('a_cache_failure','initial-cache-verification-failure.txt','execution','保留第一個本機cache整包驗證失敗，未修補資料或刪掉失敗。',command='/workspace/tiny-perceptron-vlm/.venv/bin/python docs/technical-reviews/artifacts/p6-19.3/verify.py > docs/technical-reviews/artifacts/p6-19.3/verification-output.txt 2>&1 (first run; preserved before later runs)',result='exit 1：DATA-NOTICE.md與manifest size/hash不同。後續獨立確認固定archive正確。',environment=env)
artifact('a_cache_list','local-file-mismatches.json','source_snapshot','本機cache全部6項difference的expected/actual SHA與bytes；不是正文錯誤或資料包不符。')
artifact('a_scope_failure','first-archive-verification-scope-failure.txt','execution','保留本輪第一版驗證腳本把全部notice也當原媒體不變的過寬assertion。',command='/workspace/tiny-perceptron-vlm/.venv/bin/python docs/technical-reviews/artifacts/p6-19.3/verify.py > docs/technical-reviews/artifacts/p6-19.3/verification-output.txt 2>&1 (archive verification run; preserved before corrected scope)',result='archive8962項全pass後，過寬assertion失敗。獨立查兩manifest後確認只有2個非媒體notice更新；正文承諾原record/media不變，修正查核範圍後a1完成。',environment=env)
artifact('a_frozen','frozen-19.md','source_snapshot','最初讀取的整章原始bytes frozen input；此全檔SHA只指這份快照，正式source_sha256使用本節bytes。')
artifact('a_section','section-19.3.md','source_snapshot','本節未正規化UTF-8原始bytes，SHA對應正式source_sha256。')

sources=[
 {'id':'s_sklearn','kind':'official_source','title':'scikit-learn official cross-validation documentation','url':'https://raw.githubusercontent.com/scikit-learn/scikit-learn/1.7.2/doc/modules/cross_validation.rst','version':'1.7.2 tagged original source','verified':True,'checked_original':True,'accessed_on':'2026-10-06','authority_reason':'scikit-learn官方作者维护的原始doc source；分份与group CV方法契约。','inspection_note':'親讀L60–82：test調參會造成leakage，train/validation/final test角色；L628–656：dependence groups须整群保留在一份。僅支持此一般分群原则，不能证明特定模型读取材料。'},
 {'id':'s_minds','kind':'official_source','title':'PolyAI MInDS-14 original dataset card and features','url':'https://huggingface.co/datasets/PolyAI/minds14/raw/40ce77cb32a384e4d50a568e1ec39ac804019d33/README.md','version':'40ce77cb32a384e4d50a568e1ec39ac804019d33','verified':True,'checked_original':True,'accessed_on':'2026-10-06','authority_reason':'來源dataset作者PolyAI发布的固定revision原始card。','inspection_note':'親讀L958–1005：all configs same structure；Data Fields列path/audio/transcription/english_transcription/intent_class/lang_id，無speaker/session id。與原始parquet schema及voice audit獨立比對；不能用無ID推出實際人数或speaker disjoint。'},
 {'id':'s_execution','kind':'execution','title':'19.3 fixed-data original measurements and family verification','verified':True,'artifact_id':'a1'},
 {'id':'s_helpers','kind':'execution','title':'19.3 executed original helper contracts and source-free baseline','verified':True,'artifact_id':'a2'},
 {'id':'s_baseline_derivation','kind':'derivation','title':'Zero family overlap does not prove material dependence','verified':True,'details':'固定test中vision category targets每類600，總1800。完全不讀image且永遠猜bag的分類器仍能命中600/1800=1/3；此分類器与是否group交集为零無關。因此零交集排除指定来源泄漏，不能单独证明对image有依赖。该值是category基线，不是带位置/格式的final-reply模型成績。'}
]
code_specs=[
 ('s_dataset','tiny_perceptron/selftrained/dataset.py','AST read_records L48–81、train_tokenizer L84–91、RecordEncoder L108–241；实际negative split/metadata CPU检查。'),
 ('s_text','scripts/selftrained/prepare_text_tools.py','先AST定位；精讀split_for_family L433–434、text_records L497–612、numeric_families L615–628、tool_records L635–782、audit_records L785–834計算、audit_voice_overlap L874–937；不把返回文字或已有判定當實測證據。'),
 ('s_visionocr','scripts/selftrained/prepare_vision_ocr.py','先AST定位；prepare_vision L167–293、word_pools L296–310、draw_line L313–326、prepare_ocr L329–456、verify L523–623；只依方法規約/原標註，不沿用結果解釋。'),
 ('s_voice','scripts/selftrained/prepare_voice.py','先AST定位；normalized_transcript/Groups L102–119、acoustic_duplicate_edges L143–175、split_groups L178–205、history L208–216、main原source讀取/分群/衍生L308–550；算法實際CPU重查。'),
 ('s_augmenttext','scripts/selftrained/augment_text_tools_v2.py','先AST定位；new_record/operand_family/selected_pairs L73–122、build_additions L134–215、verify_and_copy_base L369–416、augment L419–442；只追加train且排除heldout operands/templates。'),
 ('s_augmentocr','scripts/selftrained/augment_ocr_v2.py','先AST定位；style L55–83、frozen_parent_files L110–147、augment L150–256的parent读取、绘制、deepcopy与suffix拼接；没有把先存作者结论当成自己的验证。'),
 ('s_augmentvoice','scripts/selftrained/augment_voice_v2.py','先AST定位；frozen_parent_files L239–271、main L274–370：只读原train，父record deep copy，augmentation不是新独立录音。'),
 ('s_train','scripts/selftrained/train.py','先AST定位；stage_records L84–103、main L724–750 train/validation选择、L868–962 validation checkpoint selection与backward/optimizer.step；仅CPU执行stage_records，未训练。'),
 ('s_eval','scripts/selftrained/evaluate.py','先AST定位；protocol_contents/validate_protocol L318–380、Generator L383–492、main test guards L733–742、split L820附近、continuation branch L855–893、controls L925–950；只执行原continuation branch与stub，未eval模型。'),
 ('s_wrapper','scripts/selftrained/train_local_stage.py','先AST定位；main L120–163：manifest逐檔verified_file在trainer调用前，固定记录/asset/config注入。'),
 ('s_modal','scripts/selftrained/modal_runner.py','先AST定位；validate_manifest L151–177、prepared_records_gate/readiness/local_readiness L573–630；实际15段raw execution identity/provenance另外CPU核對。'),
 ('s_transport','scripts/selftrained/hf_transport.py','先AST定位；relative_path L222–226、verify_file L229–235，实际manifest hash/size核对和size不变内容变动negative测试。'),
 ('s_inference','tiny_perceptron/selftrained/inference.py','先AST定位；_public_history L139–173、attach_public_metadata L176–212；实际intent私有字段negative拒绝。')
]
for identifier,path,note in code_specs:
 sources.append({'id':identifier,'kind':'repository_code','title':path,'path':path,'sha256':sha(ROOT/path),'version':'working-tree original inspected 2026-10-06; Git HEAD b3a6684a1af47f1086c1b9e56ed090ff6699220a; full SHA is authoritative','verified':True,'inspection_note':note})
def ev(s,l,supports):return {'source_id':s,'locator':l,'supports':supports}
claims=[]
def claim(identifier,kind,statement,location,evidence,scope,observed='',expected='',details='',ids=None,status='verified',denominators=None):
 c={'id':identifier,'kind':kind,'statement':statement,'location':location,'status':status,'evidence':evidence,'artifact_ids':ids or ['a1'],'scope':scope}
 if kind!='concept':
  c['verification']={'method':'executed','expected':expected or statement,'observed':observed,'details':details or '实际运行a1/a2中的有限CPU检查；原始输入完整SHA与实际读取指针保存在输出。'}
  if kind=='numeric':c['verification']['tolerance']='精确整数/字串集合相等；SHA逐字节相等；比率为精确分数1/3。'
  if kind=='empirical':c['verification']['denominators']=denominators
 claims.append(c)
claim('c1','concept','同来源/情境及衍生题先按家族分份，可避免依赖样本被随机拆散而造成指定家族泄漏。','19.md L120、L134',[ev('s_sklearn','cross_validation.rst L628–656','相关样本须按domain-specific group隔离；不是按独立record ID随意拆分。')],'只支持group split原则；不能声称排除所有语意重复、所有shortcut或所有模型泄漏。',ids=['a_sklearn'])
claim('c2','numeric','固定train/validation/test对话记录数是28876/2435/3734，非原素材数。','19.md L126–132',[ev('s_execution','verification-output record_counts, record_files, task_counts, original_test_count','12原record文件逐项manifest hash相符并直接计数；双模型原test aggregate的count也3734。')],'这些是固定V2的记录数。商品同source、多ROI/同audio多format/continuation/augmentation各为不同记录；没有用record数代替material数。',observed='train=28876，validation=2435，test=3734；35045 records。',ids=['a1'])
claim('c3','software','train参与参数更新，validation用于监控与选checkpoint，test依冻结protocol最终核对且不选权重。','19.md L130–132',[ev('s_train','stage_records L84–103; main L724–750,L868–962','train过滤后才进入sampler/backward/optimizer；validation_loss改进才存best。'),ev('s_eval','main L733–742; protocol_contents L318–353; validate_protocol L356–380','test不能limit、重新freeze；固定权重/数据/规则身份。'),ev('s_helpers','helper-checks-output stage_records_original_function','实际原函数各stage取出的全是指定train或validation。'),ev('s_execution','training_selection_receipts, frozen_test_protocol, original_test_count','15原训练收据test_used_for_selection=false、选择validation；两原test protocol身份匹配固定记录。')],'仅审核这条实际管线与原收据；没有重新训练或test评测，且teacher-forced validation loss不等于generation成功。',observed='6种stage筛选计数吻合；15段raw selection收据都为validation；两个frozen test protocol绑定同record SHA。',ids=['a1','a2'])
claim('c4','software','文字改述家族/客服树及格式、范围、历史衍生记录留在同份。','19.md L138',[ev('s_text','text_records L497–612; split_for_family L433–434','customer tasks及format_change共用tree group；template先指定split后展开style/history。'),ev('s_execution','group_cross_split, template_family_cross_split, text_exact_public_prompt_cross_split','所有指定group/template与exact public prompt跨份交集均0。')],'按准备程序明定的原创family/tree切分；未宣称机器检查了所有自由语言语意等价关系。',observed='group/template family/exact prompt各train-val/train-test/val-test交集0。')
claim('c5','software','计算题canonical数字对、交换、operation、可用性与result返填共留一份，问法家族也隔离。','19.md L139',[ev('s_text','numeric_families L615–628; tool_records L635–782','先canonical operand pair分份，再expand方向/运算/style/call/reply；template分split。'),ev('s_augmenttext','selected_pairs L101–122; build_additions L134–215','train增补避开heldout operands，使用train templates。'),ev('s_execution','operand_cross_split, template_family_cross_split','实际canonical operands和template交集0。')],'针对有真实expected_call的数字家族；独立数字copy/result-reading协议练习不是声称执行了新计算器调用。',observed='canonical sorted(a,b)与问法template三种跨份交集均0。')
claim('c6','software','商品图先按原始ID/像素去重切分，单物件与pair/swap/orientation所有source只在原source份内。','19.md L122、L140',[ev('s_visionocr','prepare_vision L167–293','全局used_pixels在scene生成前去重；selected[split]内取得pair两个source。'),ev('s_execution','vision_source_check','读原IDX亲自hash所有1800个source，再比对16200个canvas slots及source split。')],'Fashion-MNIST选定三类、固定112×112 canvas；示意提到缩放的可能性并不等于原管线实际对28×28source缩放。',observed='source数量1200/240/360；sourceID及原像素跨份交集0；16200slots逐像素吻合。')
claim('c7','software','交换同一配对的左右/上下位置应改变对应位置题答案，且不跨份。','19.md L122、L148',[ev('s_visionocr','prepare_vision L235–282','两个orientation、两个swapped顺序、两个query_slot；pair_id保留swap控制配对。'),ev('s_execution','vision_controls','3600 pair_id各两条同split且target不同。')],'证实的是数据目标随位置改变，未声称模型已做到。',observed='3600 swap control对全部两order、同份、target改变。')
claim('c8','software','字卡表声称同一画布的区域问题及训练增強版本不跨份。','19.md L141「同一畫布的區域問題及訓練增強版本不跨份」',[ev('s_augmentocr','augment L180–243','家族/原ROI deep copy；这只保留生成谱系，并无全局decoded pixel去重。'),ev('s_execution','verification-output ocr_pixel_cross_split','train/validation完整canvas像素交集1，train/test及validation/test 0。'),ev('s_helpers','helper-checks-output raw_collision_record_copy; collision-record-provenance.json','保存train L4122与validation L217原始记录；两PNG完整file SHA亦相同。')],'若「同一画布」只指原render谱系，其group/render ID隔离成立；但目前措辞足以让读者理解成相同canvas内容不跨份，比实际固定数据保证强。此碰撞仅既知单字「左」，不涉及2–4字组合或test。',observed='相同PNG SHA908ce16cd96eda59cdfe77bc108a0b37f5c6a81d29ca4ff6373e35b1d1339549跨train/validation；不同group/render，ROI[16,8,52,44] vs[18,8,54,44]。',expected='同一完整画布不跨份，或正文清楚限定为render来源谱系。',ids=['a1','a2','a_collision','a_collision_records','a_collision_provenance','a_collision_png0','a_collision_png1'],status='contradicted')
claim('c9','software','2–4字组合按完整target字串隔离；同render家族/增强记录的group与image lineage留在同份。','19.md L141',[ev('s_visionocr','word_pools L296–310; prepare_ocr L329–416','各长度先划word pool，再按texts成对render及ROI派生。'),ev('s_augmentocr','augment L180–243','只对train父record deepcopy group/split并保存其ROI。'),ev('s_execution','ocr composition_cross_split, render_source_cross_split, group_cross_split','target串690/104/150，三种组合target交集0；标记/来源ID交集0。')],'只支持2–4字target字符串与来源谱系隔离；不能据image path不同推出所有单字canvas像素不同，c8给出反例。',observed='composition unique strings train690、validation104、test150；三种跨份字串交集0。')
claim('c10','numeric','12个已知单字在训练与单字检查共同出现，不是未知字符测试。','19.md L144',[ev('s_execution','ocr shared_single_characters, single_counts','直接从原target集合计算三份各12及交集12。'),ev('s_visionocr','prepare_ocr L414–456','单字诊断有意用相同CHARACTERS，但render来源不同。')],'已知12个字；不是任意字库扩展、新字符识别或所有样貌都未见过。',observed='三份单字集合均12且共同集合为上下人入出口右大小左開關。')
claim('c11','numeric','V2 train含Sans与Serif，test Serif不能称为陌生字型。','19.md L144',[ev('s_augmentocr','style L55–83; augment L180–231','每父canvas固定augmentation variants含Sans/Serif。'),ev('s_execution','ocr font_families','直接数原记录font_family。')],'固定Noto Sans/Serif家族训练曝光；size/layout变化不等于字体家族未见。',observed='train Sans2749/Serif1967；validation各116；test各162。')
claim('c12','software','给定OCR ROI是连续1–4格，pipeline识别公开框内字，没有另外训练文字检测。','19.md L144',[ev('s_dataset','RecordEncoder._modality L133–154; encode L179–206','只依据public ROI裁图等比缩放padding，无gold字数/glyph box作为输入。'),ev('s_visionocr','prepare_ocr L355–390,L424–450','每ROI宽36×len(target)，高36、1–4字符水平连续格；glyph_boxes为监督。'),ev('s_execution','ocr records_verified; encoder_checks','5272条ROI及glyph范围实际校验；修改supervision/current answer不会改变OCR inputs。')],'只是给定ROI recognition；没有检测框提议或自由场景检测器。',observed='5272条target长度1–4、ROI尺寸36*n×36吻合且在canvas内；模型输入shape1×32×128，不读取监督box/target长度。')
claim('c13','numeric','来源录音train62、validation15、test30，数字是原录音而非人数或增强wave数。','19.md L146',[ev('s_execution','voice_originals; voice_family_cross_split','502-row audit中selected原录音107，prepared_split计数62/15/30。'),ev('s_augmentvoice','main L304–340','train派生wave不是new_independent_human_recording。')],'仅固定三个intent选择的107条来源录音；train增强及多问法records不增加独立人类录音。',observed='原录音62/15/30，总107；voice records2790/75/150。',ids=['a1','a_voice'])
claim('c14','concept','来源没有speaker ID，不能把录音数写成人数或声称test说话人从未出现于train。','19.md L146',[ev('s_minds','Data Fields L990–1000; Data Instances L975–987','原始作者features没有speaker/session字段，path属于文件路径不是人物ID。'),ev('s_execution','source_parquet; voice_originals','固定parquet实际schema与官方features相同；所有原audit speaker/session值null。')],'未知speaker身份，不等于同speaker、不同speaker或人数；录音群组只保证所定义重复隔离。',ids=['a1','a_minds','a_voice'])
claim('c15','software','录音来源、重复/近重复语句及其format/continuation/augmentation衍生留同份。','19.md L142',[ev('s_voice','normalized_transcript L102–105; main L401–520; split_groups L178–205','hash、decoded audio、normalized/near transcript union，然后赋group/split，生成format和continuation。'),ev('s_augmentvoice','main L304–370','深拷贝parent同group/split/messages/supervision。'),ev('s_execution','voice_lexical_duplicate_verification, voice_acoustic_duplicates, voice_family_cross_split','5671 pairs中48 lexical duplicate edge都同group/split；acoustic>=.995 edge0；所有原与增补parent/group/split校验。')],'只针对固定重复算法和阈值；不承诺语意完全重复或speaker聚类。',observed='群组和原audio SHA跨份交集0；48 lexical edge无违规；0 near-acoustic edge；全部augmentation沿原train家族。',ids=['a1','a_voice'])
claim('c16','software','源转写用于重复群组与文字泄漏检查；推论只读声音/公开对话，不附transcript、intent或current gold；续聊使用actual first reply。','19.md L146',[ev('s_text','audit_voice_overlap L874–937','transcripts仅用于lexical exclusion，有限繁简规范化及.90 threshold。'),ev('s_dataset','RecordEncoder.encode L177–221','prompt仅messages和四种public modality字段，不将supervision或transcription接入输入。'),ev('s_inference','_public_history L139–173','公开messages仅允许public字段，拒绝intent。'),ev('s_eval','main continuation L855–893','第一答生成后重建第二答history；gold first reference只用于score。'),ev('s_execution','text_voice_lexical_overlap, encoder_checks, continuation_contract, public_input_rejection','实际bounded CPU契约检验：4892 queries against30 source transcripts，无≥.9 collision；metadata/current-gold置换无输入变化；原continuation branch stub无gold进入history。')],'词面审计不是母语者语意重复审查；stub验证history契约而非heldout模型能力。公开历史可含过去真实回答，当前gold不入prompt。',observed='source重复/词面检查已执行；2个encoder记录对supervision/transcript/current-answer置换不变；原续聊branch2 calls用SELF_GENERATED_FIRST；public intent被拒绝。',ids=['a1'])
claim('c17','numeric','零家族交集本身不能证明模型读取材料；仍须检查答案分布与变位对。','19.md L148',[ev('s_helpers','constant_bag_category_guess','即使group交集0，一个完全不读image的bag类别常数基线仍600/1800。'),ev('s_baseline_derivation','600/1800=1/3推导','证明group隔离与输入依赖是两件独立事项。'),ev('s_execution','vision_controls','数据本身具3600换位answer-changing pairs，可与model outputs比较。')],'这里的1/3是source-free类别基线，非模型成績、非带方向/格式的完整reply成功率；数据生成正确也不保证模型使用输入。',observed='不读图的常数类别guess命中600/1800=1/3，且3600变位对target改变。',ids=['a1','a2'])
claim('c18','software','manifest列12 records和全部固定素材path/bytes/fullSHA，wrapper在训练启动前逐项查核，各15段训练沿同一manifest。','19.md L153',[ev('s_wrapper','main L136–163','declared=records+assets；每item先verified_file再装载trainer。'),ev('s_modal','local_readiness L604–630','所有record/assets full verification，完整timing/provenance。'),ev('s_transport','verify_file L229–235','file路径、安全性、size及完整SHA查核。'),ev('s_execution','manifest, all_manifest_files_verified, training_stage_frozen_data','archive SHA0976073a…、67862431bytes吻合；8962项全部原member吻合；15raw stages同3443e3d3…与12/8950 verified counts。'),ev('s_helpers','manifest_negative','相同size内容变更被拒绝。')],'核对的是immutable固定archive与训练规约/原raw metadata。当前本机cache6项不同，未把它叫作完整verified package；正文没有承诺当前cache本身已全部安装正确。',observed='12records+8950assets都有path/bytes/fullSHA；fixed archive8962全吻合；15训练段同manifest；tampered file被拒绝。',ids=['a1','a2','a_cache_failure','a_cache_list'])
claim('c19','software','V2 text/tool/OCR/voice追加train记录/媒体，原validation/test records及媒体原bytes不变。','19.md L153',[ev('s_augmenttext','verify_and_copy_base L369–416','frozen parent fingerprints；train byte prefix及heldout byte identity。'),ev('s_augmentocr','frozen_parent_files L110–147; augment L233–256','train suffix附加；其余data identity保持。'),ev('s_augmentvoice','frozen_parent_files L239–271; main L340–364','parent固定且train原bytes prefix保持。'),ev('s_execution','v1_v2_preservation','两个固定manifest逐项比对：8heldout record与6250原媒体SHA/size不变；四train原prefix hash相同。')],'此承诺是records/media；2个非media notice在V2更新，不能据此扩写为所有notice原bytes不变。',observed='8heldout记录/6250原media全bytes identity；OCR/text-tools/voice新增suffix，vision train原檔相同。')
claim('c20','software','数据reader拒绝同group_id跨split；来源pixel/string/recording隔离需各prepare method另外检查。','19.md L155',[ev('s_dataset','read_records L48–81','同group不同split触发ValueError；单一group ID不包含原pixels/string/speaker完整信息。'),ev('s_visionocr','prepare_vision L167–205; word_pools L296–310; verify L523–623','原pixels、来源、字串各独立规约检查。'),ev('s_voice','main L401–449','录音/转写group构造另由准备器执行。'),ev('s_execution','reader_negative','只改一条distinct-ID记录为同group跨份，实际reader拒绝。')],'read_records只验证传入记录集合；必须传全部记录才能覆盖全split。跨份不同ID/不同group且相同pixels不会由这个标记检查发现，c8恰为例子。',observed='实际negative输入出现ValueError group跨split；全部35045条current记录通过。',ids=['a1','a_collision_records'])
claim('c21','concept','图示A及boot取自train，单物件/pair/swap全留train，B/C另留用于validation/final test。','19.md L122–124及p6-19-start-splits.svg',[ev('s_sklearn','cross_validation.rst L60–82,L628–656','来源group隔离和validation/final-test角色。'),ev('s_visionocr','prepare_vision L167–282','project配对只取selected[split]并生成变位版本。')],'示意非真实bag样本编号或模型成绩；没有把训练28×28的paste误标成实际resize。实际render/view两宽度已核对标记、箭头和语义。',ids=['a_fig640','a_fig360'])

method={'reviewer_task':'/root/p6_fact_19_3','reviewer_context':'fresh','primary_read_scope':'仅19.3原稿完整节L118–157；整章bytes只作frozen snapshot保存，未以其他章节或旧审阅结论为证据。','frozen_full_chapter_sha256':sha(ART/'frozen-19.md'),'raw_json_policy':'先读取top-level key/types，再具名pointer读取方法规约、source、测量；未读取原始结果notes/review/作者修正摘要。原训练/raw测量指针及完整源SHA各见a1。','actual_data_scope':'fixed manifest records/assets；12 record JSONL全量只读取原始records/labels/provenance/方法字段；完整source audit的source/group/transcript/split/speaker字段；Fashion raw IDX selected pixels；MInDS原parquet只查schema与完整hash/size。','archive_check':'固定archive SHA/size与全部8962成员逐项唯读核对；cache6 mismatch保留并未修补。原cache记录与实际image/audio/font source都是匹配archive的member。','ocr_collision_scope':'完整PNG与decoded canvas碰撞只在train/validation单字左；ROI不同，但同canvas内容跨份。组合string/test隔离独立验证，不扩大为全部OCR像素隔离。','source_artifact_permanence':'精确原voice audit、2条原OCR collision record及两原PNG保存，并核对original/copy SHA；其余大数据维持固定manifest Git LFS archive可取规范，不把整包training data加入普通Git。','figure_render_commands':['inkscape course/figures/p6-19-start-splits.svg --export-width=640 --export-filename=docs/technical-reviews/artifacts/p6-19.3/splits-640.png','inkscape course/figures/p6-19-start-splits.svg --export-width=360 --export-filename=docs/technical-reviews/artifacts/p6-19.3/splits-360.png'],'figure_renderer':'Inkscape 1.4 (e7c3feb100, 2024-10-09); actual view640 and view360 completed. Pango/Gtk init warnings did not impair output.','no_model_work':'无GPU、训练、heldout模型评测、付費、上传、正文修改、commit。有限encoder/原continuation branch stub不是原模型能力测试。'}
(ART/'inspection-record.json').write_text(json.dumps(method,ensure_ascii=False,indent=2)+'\n')
artifact('a_inspection','inspection-record.json','source_snapshot','本轮真实读取范围、独立性、失败/更正说明、固定包查核范围、SVG实际render/view命令。')
report={'schema_version':1,'review_stage':'technical','lesson_id':'19.3','source':'course/chapters/19.md#19.3','reviewer_task':'/root/p6_fact_19_3','reviewer_context':'fresh','source_sha256':sha(ART/'section-19.3.md'),'figure_sha256':{'course/figures/p6-19-start-splits.svg':sha(ROOT/'course/figures/p6-19-start-splits.svg')},'verdict':'revise','claims':claims,'sources':sources,'artifacts':artifacts,'issues':[{'claim_id':'c8','status':'unresolved','details':'L141「同一画布…不跨份」比当前数据能支持的谱系隔离强。完整PNG SHA908ce16c…的左字卡分别存在train augmentation和validation；render/group ID不同，ROI不同，不会被group_id或image path交集侦测。此处并非2–4字组合或test泄漏，也不是62/15/30录音计数问题。','suggestion':'把该行明确限定为「同一render来源及其区域题/增强衍生按家族留同份」，并说明这不承诺所有单字诊断canvas像素零重複（现有固定V2含1个train/validation同图）。不改数据、不重训；若作者希望承诺完整画布像素隔离，应另行修正固定数据版本，不能只换hash或图。'}],'checks':{'factual_accuracy':{'status':'revise','details':'21项独立核对，20项支持；字卡完整canvas隔离措辞受到1个train/validation同PNG反例影响。','claim_ids':[c['id'] for c in claims]},'numeric_verification':{'status':'pass','details':'各records/录音/字串/字型/ROI数实际CPU核对；28876/2435/3734、62/15/30、12共同字及Sans/Serif曝光均吻合；碰撞数字真实保留。','claim_ids':['c2','c10','c11','c13','c17']},'figure_consistency':{'status':'pass','details':'已实际render/view640/360，来源A三个train后代、同份boot、B/C用途及箭头一致，无正文数值误标。','claim_ids':['c6','c7','c21']},'source_verification':{'status':'pass','details':'原作者官方1.7.2 scikit source与固定MInDS card已亲读定位；原source bytes SHA、代码AST定位与读取、15段raw training provenance/test aggregate pointers及archive全量member已核对。无旧review/作者结果解读作为证据。','claim_ids':[c['id'] for c in claims]},'limitations':{'status':'revise','details':'已正确限制已知字元/已见Serif、给定ROI recognition、录音不是人数、group隔离不等于使用材料；L141仍应限定render谱系，并明确单字诊断不保证完整canvas像素零重複。','claim_ids':['c8','c9','c10','c11','c12','c13','c14','c15','c16','c17','c18','c19','c20']}}}
(ROOT/'docs/technical-reviews/19.3.json').write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n')
print('wrote',ROOT/'docs/technical-reviews/19.3.json','verdict',report['verdict'],'claims',len(claims),'issue c8 L141')
