"""Current owner reinspection; construct claims from this actual source review."""
from pathlib import Path
from datetime import datetime, UTC
import hashlib, json, importlib.util

R=Path(__file__).resolve().parents[4]
D=Path(__file__).resolve().parent
P=R/'docs/technical-reviews/artifacts/phase4-13_12-independent'
TASK='/root/phase4_factual_coordinator/factual_13_12'
ID='reinspection-13_12-10591ac-owner'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def rel(p):return p.relative_to(R).as_posix()
def out(p,o):p.write_text(json.dumps(o,ensure_ascii=False,indent=2,allow_nan=False)+'\n')
today=datetime.now(UTC).date().isoformat()
spec=importlib.util.spec_from_file_location('sf',R/'docs/review-tools/section_facts.py');sf=importlib.util.module_from_spec(spec);spec.loader.exec_module(sf)
b,_,line=sf.original_section(R/'course/chapters/13.md','13.12')
assert b==(D/'13.12-current.md').read_bytes()
assert sha(D/'13.12-current.md')=='10591ac40861f01e2f54ee4542070d2de7de45faea502c6528f11decd0ac8575'
prior=json.loads((D/'prior-evidence-opaque-manifest.json').read_bytes())
for name,expected in prior['prior_files'].items():assert sha(R/name)==expected,(name,'prior history changed')
assert sha(D/'prior-report-opaque.json')=='f302305c0b2b4ee79c2e3b702aa151f831570519cea5ad2e195ab97a455e3139'
# No prior report verdict or claims are read as evidence.
execution=json.loads((D/'current-fence.execution.json').read_bytes());env=json.loads((D/'current-fence.environment.json').read_bytes())
assert execution['exit_code']==0 and (D/'current-fence.stderr.txt').read_bytes()==b''
assert (D/'current-fence.stdout.txt').read_text().strip()=='更新前後的機率比 [2.0, 0.5]'
assert (D/'current-fence.fence-1.py').read_bytes()==(P/'frozen-input/fence-1.py').read_bytes()
for n in ['tiny_perceptron/posttraining.py','scripts/course_experiments/posttraining.py']:
 assert (R/n).read_bytes()==(P/'frozen-input'/n).read_bytes()
assert (D/'preview-render.stderr.txt').read_bytes()==b''
assert len(json.loads((D/'preview-render.result.json').read_bytes())['renders'])==2
scroll=json.loads((D/'mobile-code-scroll.result.json').read_bytes())
assert scroll[0]['overflowX']=='auto' and scroll[0]['scrollWidth']>scroll[0]['clientWidth']

authority_reads=[
 {'source':'PPO original','version':'arXiv:1707.06347v2, 2017-08-28','url':'https://arxiv.org/pdf/1707.06347v2','path':rel(P/'ppo-1707.06347v2.pdf'),'sha256':sha(P/'ppo-1707.06347v2.pdf'),'read_locator':'page-1 identifier; section 3 definition and equations 6–7, PDF p3, text 104–160; Algorithm 1 PDF p5, text 236–249','own_support':'Selected-action new/collecting-old ratio; fixed-advantage surrogate; favorable-direction clipping incentive; K optimization epochs before new collection.'},
 {'source':'InstructGPT original','version':'arXiv:2203.02155v1, 2022-03-04','url':'https://arxiv.org/pdf/2203.02155v1','path':rel(P/'instructgpt-2203.02155v1.pdf'),'sha256':sha(P/'instructgpt-2203.02155v1.pdf'),'read_locator':'page-1 identifier; section 3.2 RL paragraph and equation 2, PDF p9, text 484–507','own_support':'Starting SFT reference differs from learned RL policy; this supports the chapter SFT-to-PPO setting, not a universal fixed-reference requirement.'},
]
fetch=json.loads((P/'official-fetch-provenance.json').read_bytes())
for n in ['detach','log','exp']:
 q=P/(n+'-2.9.html');record=next(x for x in fetch if x['path']==q.name)
 authority_reads.append({'source':'PyTorch '+n+' official API','version':'PyTorch 2.9 docs, executed CPU runtime 2.14.1+cpu','url':record['url'],'path':rel(q),'sha256':sha(q),'read_locator':'Complete API article reopened from preserved original: '+rel(P/(n+'-2.9.api.txt')),'own_support':{'detach':'Detached graph has no gradients but shares storage; saving history requires persistence.','log':'Elementwise natural logarithm.','exp':'Elementwise exponential.'}[n]})
commit='20921137141b154454c0a2698709d9f9a0302101'
authority_reads.append({'source':'OpenAI Spinning Up original PPO','version':commit,'url':f'https://github.com/openai/spinningup/blob/{commit}/spinup/algos/pytorch/ppo/ppo.py','path':rel(P/'openai-spinningup-ppo.py'),'sha256':sha(P/'openai-spinningup-ppo.py'),'read_locator':'PPOBuffer __init__/store 19–40; compute_loss_pi 227–234','own_support':'Collection logp is saved, new logp recomputed and its difference exponentiated; minimized loss is negative mean surrogate.'})
receipt={
 'id':ID,'schema_version':1,'reviewer_task':TASK,'stage':'owner_current_version_reinspection','date':today,
 'source':'course/chapters/13.md#13.12','source_sha256':sha(D/'13.12-current.md'),
 'actual_read_scope':['complete current 13.12 including supplement','complete current 13.11; support uses advantage and contextual-bandit definition only','complete current 13.4; support uses fixed-reference definition only','current factual-reviewer instructions, checker schema, clear-tutorial skill and protocol'],
 'current_dependencies':[{ 'source':'course/chapters/13.md#'+s,'path':rel(D/(s+'-current.md')),'sha256':sha(D/(s+'-current.md')),'changed_from_prior_review':False} for s in ['13.11','13.4']],
 'intro':{'applicable':False,'reason':'13.12 is not chapter-first section'},'figure_sha256':{},
 'prior_history':{'report_path':rel(D/'prior-report-opaque.json'),'report_sha256':sha(D/'prior-report-opaque.json'),'evidence_path':rel(P),'evidence_manifest_path':rel(D/'prior-evidence-opaque-manifest.json'),'evidence_manifest_sha256':sha(D/'prior-evidence-opaque-manifest.json'),'preserved_unchanged':True,'prior_report_content_used_as_evidence':False},
 'source_delta':'Only prose typo 迴答→回答; all nine substantive claims, equations, fence, sample/action axes, units and denominators unchanged.',
 'current_code_checks':{'fence_sha256':sha(D/'current-fence.fence-1.py'),'fence_identical_to_original_review':True,'method_reads':{'tiny_perceptron/posttraining.py':'AST function ranges then bandit_advantage 24–28 and ppo_clipped_objective 31–50','scripts/course_experiments/posttraining.py':'AST function/assignment ranges then reference 289–290 and rollout/epoch method 335–356; result dictionary excluded'},'method_sha256':{n:sha(R/n) for n in ['tiny_perceptron/posttraining.py','scripts/course_experiments/posttraining.py']}},
 'fresh_execution':{'command':'.venv/bin/python docs/review-tools/section_facts.py course/chapters/13.md#13.12 --output outputs/reviewer-tools/phase4-13_12-reinspection-10591ac --execute --timeout 30','worker_command':execution['command'],'code_path':rel(D/'current-fence.fence-1.py'),'stdout_path':rel(D/'current-fence.stdout.txt'),'stdout_sha256':sha(D/'current-fence.stdout.txt'),'exit_code':0,'output':'更新前後的機率比 [2.0, 0.5]','environment_path':rel(D/'current-fence.environment.json'),'environment_sha256':sha(D/'current-fence.environment.json')},
 'reused_execution':{'confirmation_path':rel(D/'evidence-reuse-confirmation.json'),'confirmation_sha256':sha(D/'evidence-reuse-confirmation.json'),'own_program_reread':'verify_bounded_cpu.py complete; arithmetic/axes, gradient isolation, saved clone and underflow branches','reason':'Current claim/source/fence/method identities and their exact support scopes personally confirmed unchanged. Prior raw measurement pointers were directly reopened. No new numerical example needs another training or variant run.'},
 'authority_reads':authority_reads,
 'visual':{'url':'http://127.0.0.1:8765/13.12.html','render_command':'timeout 60s .venv/bin/python '+rel(D/'render_current_preview.py'),'viewports':[[1280,800],[390,844]],'views_actually_opened':['preview-1280x800.png','preview-expanded-1280x800.png','preview-390x844.png','preview-expanded-390x844.png','mobile-code-scrolled-right.png'],'scope':'Actual course theme, current source text, executed CPU output, and expanded supplement. Zero images/figure references. Mobile code block itself is horizontal-scrollable and was actually scrolled to inspect the right side.','attempt1':'Tool initially waited for h2; actual page title is h1. 10-second selector timeout retained in attempt1 files. Corrected h1,h2 selector and repeated render exit0.','mobile_probe_attempt1':'Initially checked PRE/ancestors, which did not include the actual scrolling CODE element. Retained probe, then selected CODE, verified overflowX=auto and scrolled it.'},
 'unresolved_dependencies':[],'issues':[],'verdict':'pass',
 'limits':['No GPU, model/data download, full training, model reevaluation or deployment.','Original fence is arithmetic only, not an optimizer update.','API docs version 2.9 and installed torch 2.14.1+cpu are explicitly distinguished.','No posttraining quality or token-level LM RLHF ability claim is inferred from the example.'],
}
out(D/'reinspection-receipt.json',receipt)

artifacts=[];aid={}
def add(p,kind='source_snapshot',description=None,command=None,result=None,environment=None):
 identifier=(ID if p.name=='reinspection-receipt.json' else 'current13_12-'+rel(p).replace('/','-').replace('.','-'))
 value={'id':identifier,'path':rel(p),'sha256':sha(p),'kind':kind,'description':description or ('Actual current owner reinspection source/code/output: '+p.name)}
 if kind=='execution':value.update(command=command,result=result,environment=environment)
 artifacts.append(value);aid[rel(p)]=identifier;return identifier
old_files=['ppo-1707.06347v2.pdf','ppo-1707.06347v2.txt','instructgpt-2203.02155v1.pdf','instructgpt-2203.02155v1.txt','detach-2.9.html','detach-2.9.api.txt','log-2.9.html','log-2.9.api.txt','exp-2.9.html','exp-2.9.api.txt','openai-spinningup-ppo.py','official-fetch-provenance.json','verify_bounded_cpu.py','bounded-cpu.result.json','bounded-cpu.environment.json','frozen-input/tiny_perceptron/posttraining.py','frozen-input/scripts/course_experiments/posttraining.py']
for n in old_files:add(P/n,'code' if n.endswith('.py') else 'source_snapshot','Personally reopened original authority or unchanged method/raw measurement retained from the original owner review: '+n)
bounded_env={k:str(v) for k,v in json.loads((P/'bounded-cpu.environment.json').read_bytes()).items()}
bounded_id=add(P/'bounded-cpu.stdout.txt','execution','Previously actually executed owner CPU variants, reused only after code/source/support identities and raw values were personally rechecked.',command="CUDA_VISIBLE_DEVICES='' HF_HUB_OFFLINE=1 HF_DATASETS_OFFLINE=1 TRANSFORMERS_OFFLINE=1 PYTHONDONTWRITEBYTECODE=1 OMP_NUM_THREADS=1 .venv/bin/python "+rel(P/'verify_bounded_cpu.py'),result='Original execution exit0; reused, not claimed as newly executed. Ratios, independent axes, gradients, clone/history and small-log example match unchanged current claims.',environment=bounded_env)
for p in sorted(D.rglob('*')):
 if not p.is_file() or p.name in {'generation.stdout.txt','generation.stderr.txt','canonical-written.json','checker.stdout.txt','checker.stderr.txt','completion.json'} or '__pycache__' in p.parts:continue
 kind='figure_render' if p.suffix=='.png' else ('code' if p.suffix=='.py' else 'source_snapshot')
 if p.name=='current-fence.stdout.txt':
  current_id=add(p,'execution','New actual CPU execution of unchanged current source fence.',execution['command'],'exit0; 更新前後的機率比 [2.0, 0.5]',{k:str(env[k]) for k in ['python','python_executable','torch','device_requested','cuda_build','cuda_available']})
 elif p.name in ['preview-render.stdout.txt','mobile-code-scroll.stdout.txt']:
  code='render_current_preview.py' if p.name.startswith('preview') else 'check_mobile_code.py'
  add(p,'execution','Actual current course preview render/probe, screenshots personally opened.','timeout '+('60s' if code.startswith('render') else '40s')+' .venv/bin/python '+rel(D/code),'exit0; current theme rendered, desktop/mobile and expanded supplement inspected; mobile CODE scroll works.',{'Chromium':'151.0.7922.173','Playwright':'1.63.0','device':'CPU/headless'})
 else:add(p,kind)

sources=[]
for sid,record,kind in [('ppo',authority_reads[0],'paper'),('instructgpt',authority_reads[1],'paper')]:
 sources.append({'id':sid,'kind':kind,'title':record['source'],'url':record['url'],'version':record['version'],'accessed_on':today,'authority_reason':'Original method paper, exact arXiv version identified from the original PDF','verified':True,'checked_original':True,'inspection_note':'Reopened original personally during this current reinspection: '+record['read_locator']})
for n in ['detach','log','exp']:
 q=next(x for x in authority_reads if x['source']=='PyTorch '+n+' official API')
 sources.append({'id':n,'kind':'official_docs','title':q['source'],'url':q['url'],'version':q['version'],'accessed_on':today,'authority_reason':'Official PyTorch versioned API original','verified':True,'checked_original':True,'inspection_note':q['read_locator']+'; preserved HTML SHA rechecked. No new network fetch is claimed.'})
q=authority_reads[-1]
sources.append({'id':'openai','kind':'official_source','title':q['source'],'url':q['url'],'version':q['version'],'accessed_on':today,'authority_reason':'Original OpenAI official repository implementation','verified':True,'checked_original':True,'inspection_note':q['read_locator']+'; exact original source SHA rechecked.'})
for sid,n,loc in [('helper','tiny_perceptron/posttraining.py','AST located then read bandit_advantage 24–28 and ppo_clipped_objective 31–50'),('rollout','scripts/course_experiments/posttraining.py','AST located then read reference 289–290 and rollout/epoch 335–356')]:
 q=P/'frozen-input'/n
 sources.append({'id':sid,'kind':'repository_code','title':n,'path':rel(q),'sha256':sha(q),'version':'Frozen original byte-identical to current source '+sha(R/n),'verified':True,'inspection_note':loc+'; no author result dictionary read; current bytes directly compared with retained original.'})
sources.extend([{'id':'fresh-cpu','kind':'execution','title':'Current original fence actual CPU run','verified':True,'artifact_id':current_id},{'id':'reused-cpu','kind':'execution','title':'Own previously executed unchanged independent variants','verified':True,'artifact_id':bounded_id},{'id':'math','kind':'derivation','title':'Owner selected-probability derivation','verified':True,'details':'For positive old probabilities exp(log(new)-log(old))=new/old. .4/.2=2; .1/.2=.5; .3/.2=1.5; new/new=1. Two samples, separate normalized action-distribution rows. Ratio dimensionless, advantage in reward units, 2*.6=1.2 is an objective term, not quality. Current claims and raw values checked in reinspection receipt.'}])
def evidence(s,l,x):return {'source_id':s,'locator':l,'supports':x}
def a(p):return aid[rel(p)]
def v(expected,observed,details):return {'method':'executed','expected':expected,'observed':observed,'details':details,'tolerance':'Prior float64 variants 1e-12; current float32 fence exact after four-decimal rounding.'}
def c(cid,kind,text,loc,scope,ev,files=(),verify=None):
 x={'id':cid,'kind':kind,'statement':text,'location':loc,'scope':scope,'status':'verified','evidence':ev,'artifact_ids':[ID]+[a(p) for p in files]}
 if verify:x['verification']=verify
 return x
claims=[
 c('C1','concept','old policy collected the batch; ratio is the current/old probability for the same selected card and context.','13.12 paragraphs 1–2','Ratio=1 means this selected likelihood is unchanged, not that every policy probability is unchanged; recorded old probability is positive.',[evidence('ppo','Section 3 definition and equation6, PDF p3; Algorithm1 p5','Collecting policy is denominator and sample reuse precedes another collection.'),evidence('openai','PPOBuffer.store 30–40, compute_loss_pi 227–233','Saved logp compared to current selected logp.')]),
 c('C2','numeric','Two independent sampled entries .2→.4 and .2→.1 yield [2,.5], and need not sum to one.','13.12 fence and explanatory paragraph','Sample axis length2; each underlying categorical row is normalized separately; ratio is dimensionless.',[evidence('math','receipt arithmetic and unchanged normalized-row variant','Independent sample/action axis and .4/.2=2, .1/.2=.5.'),evidence('fresh-cpu','current-fence.stdout.txt','Current original fence output [2.0,.5].'),evidence('reused-cpu','bounded-cpu.result.json /ratio,/old_distribution_batch_action,/new_distribution_batch_action,/per_context_probability_sums','Personally reopened own raw measurements after confirming identical code/method claims.')],[D/'current-fence.stdout.txt',P/'bounded-cpu.stdout.txt'],v('[2,.5]; normalized distribution rows each sum1','Fresh fence [2.0,.5]; reused float64 [2,.5000000000000001], row sums [1,1]','No new mathematical example; reused axis construction explicitly confirmed to support the same current scope.')),
 c('C3','software','The fence applies natural log, detach, exponentiation and display rounding to calculate the probability ratio.','13.12 fence, source lines380–388','Arithmetic demonstration only; no backward or optimizer. Separate unchanged enabled-gradient variation checks old/new graph separation.',[evidence('log','Official API full article','Natural logarithm.'),evidence('exp','Official API full article','Elementwise exponential.'),evidence('detach','Official API graph/storage contract','No old gradient; shared storage differs from historical persistence.'),evidence('fresh-cpu','current-fence execution/environment/stdout','Actual current unmodified fence execution on CPU torch2.14.1.'),evidence('reused-cpu','verify_bounded_cpu.py old/new requires_grad branch; raw /old_log_gradient,/new_log_gradient','Own unchanged variation demonstrates old None and new [1.2,-.2].')],[D/'current-fence.stdout.txt',P/'bounded-cpu.stdout.txt'],v('Fresh printed [2.0,.5]; detached-old grad None','Fresh exact output; prior unchanged variant old None/new [1.2,-.20000000000000007]','Grouped API coverage: torch.tensor, Tensor.log/exp/detach/tolist and rounding. Official docs2.9 versus executed2.14.1+cpu explicitly recorded.')),
 c('C4','concept','Detach alone is not saved history; old likelihood must be preserved and not recomputed from the updated strategy.','13.12 post-fence paragraph','Autograd isolation and historical storage are distinct. Current method clones sampled old values once per rollout.',[evidence('detach','Shared-storage note','Detached alias can reflect in-place edits.'),evidence('openai','PPOBuffer.store30–40 and loss227–233','Original implementation retains collection logp.'),evidence('rollout','Current run_posttraining335–353','Saved clone before epochs; new selected logp within each epoch.'),evidence('reused-cpu','raw /detached_shares_storage_observed,/saved_clone_retained_history','Own unchanged alias/clone branch measures the distinction.')],[P/'bounded-cpu.stdout.txt']),
 c('C5','concept','Log probabilities are commonly retained to make very small likelihoods easier to handle.','13.12 post-fence paragraph','This postpones probability underflow; it does not guarantee arbitrary exp/log differences are safe.',[evidence('openai','Buffer19–40 and ratio227–233','Stores logp and exponentiates only the difference.'),evidence('log','Natural logarithm definition','Log representation of likelihood.'),evidence('exp','Exponential definition','Recover ratio from retained log difference.'),evidence('reused-cpu','verify_bounded_cpu.py underflow branch and raw /small_log_ratio','Own unchanged -1000/-999 example yields exp1; separate conversion to probabilities underflows.')],[P/'bounded-cpu.stdout.txt']),
 c('C6','numeric','Fixed advantage .6 multiplied by ratio2 gives target term1.2; it is not a doubling of measured quality.','13.12 advantage paragraph','Surrogate single term in reward/advantage units, not model performance.',[evidence('ppo','Equation6 PDFp3','Objective term r*A.'),evidence('math','2*.6=1.2','Dimensionless ratio times reward-unit advantage.'),evidence('reused-cpu','raw /ratio_times_advantage','First unclipped term1.2 confirmed from unchanged measured program.')],[P/'bounded-cpu.stdout.txt'],v('First target term1.2','1.2 in retained unchanged CPU result','No optimizer or evaluation; current source example unchanged.')),
 c('C7','concept','Old collection-policy snapshot refreshes next collection; fixed reference can remain the posttraining starting model.','13.12 old/reference paragraph and supplement','Chapter SFT-to-PPO/fixed-reference setting; not universal fixed-reference requirement.',[evidence('ppo','Algorithm1 PDFp5','Collect, optimize K epochs, theta_old←theta.'),evidence('instructgpt','Section3.2 and equation2 PDFp9','Learned RL policy compared to starting SFT policy.'),evidence('rollout','Current reference289–290 and rollout335–353','Fixed frozen reference and rollout-specific old_selected retained separately.')]),
 c('C8','numeric','First new likelihood .3 gives [1.5,.5]; replacing old denominator with current likelihood yields [1,1].','13.12 exercise','Positive same selected-action/context likelihoods; wrong denominator erases the measured change.',[evidence('math','Independent .3/.2 and new/new calculation','1.5,.5 and two ratios1.'),evidence('reused-cpu','raw /exercise_ratio,/wrong_denominator_ratio','Personally read unchanged executed values and code branch.')],[P/'bounded-cpu.stdout.txt'],v('[1.5,.5] and [1,1]','[1.4999999999999996,.5000000000000001] and [1,1]','Prior variant code/method identity confirmed, no new changed example.')),
 c('C9','concept','PPO clipping removes incentive to keep pushing the same old sample farther in a favorable direction.','13.12 clipping preview','A clipped-objective incentive statement, not a hard bound on resulting probabilities.',[evidence('ppo','Equation7 and explanation below, PDFp3','Min clipped/unclipped surrogate ignores additional change only when it would improve objective.'),evidence('helper','ppo_clipped_objective37–47','Detached advantage and minimum of clipped/unclipped terms.')]),
]
ids=[x['id'] for x in claims]
report={'schema_version':1,'review_stage':'technical','lesson_id':'13.12','source':'course/chapters/13.md#13.12','source_sha256':sha(D/'13.12-current.md'),'verdict':'pass','reviewer_task':TASK,'reviewer_context':'fresh','author_tasks':[],'figure_sha256':{},'reviewed_on':today,'owner_reinspection':{'id':ID,'artifact_id':ID,'path':rel(D/'reinspection-receipt.json'),'sha256':sha(D/'reinspection-receipt.json'),'kind':'original independent owner reinspection, not a new reviewer identity'},'prior_history':receipt['prior_history'],'read_scope':{'current_complete_section':rel(D/'13.12-current.md'),'current_dependency_sections':receipt['current_dependencies'],'intro':receipt['intro'],'current_frozen_chapter':{'path':rel(D/'chapter13-current-frozen-input.md'),'sha256':sha(D/'chapter13-current-frozen-input.md'),'meaning':'Current reinspection frozen input only, not an ongoing whole-chapter version assertion'},'original_frozen_chapter':{'path':rel(P/'frozen-input/chapter13-frozen-input.md'),'sha256':sha(P/'frozen-input/chapter13-frozen-input.md'),'meaning':'Original owner review frozen input preserved unchanged'}},'independence':{'prior_other_reviewer_conclusions_read':False,'author_revision_summaries_read':False,'exposure_event':None,'prior_report_claims_used_as_evidence':False},'artifacts':artifacts,'sources':sources,'claims':claims,'issues':[],'checks':{'factual_accuracy':{'status':'pass','claim_ids':ids,'details':'Complete current source and necessary context personally read; all nine claims rechecked against exact original authority/method, with no new substantive examples.'},'numeric_verification':{'status':'pass','claim_ids':['C2','C3','C6','C8'],'details':'Current original fence newly executed exit0. Prior independent numeric/gradient/axis checks reused only after personal code/source/byte/support confirmation; samples2, ratio dimensionless and target reward units, same denominators.'},'figure_consistency':{'status':'not_applicable','claim_ids':[],'details':'No figure references or images. Actual current course theme desktop/mobile collapsed+expanded renders opened with view_image. Mobile CODE horizontal scrolling actually exercised and screenshot opened.'},'source_verification':{'status':'pass','claim_ids':ids,'details':'Personally reopened original PPOv2 equations6–7/Algorithm1, InstructGPTv1 equation2, official PyTorch API articles and OpenAI precise commit ranges; current AST-located method reads and hashes recorded in own receipt.'},'limitations':{'status':'pass','claim_ids':ids,'details':'No GPU, training, data/model download, evaluation or deployment. Docs2.9/runtime2.14.1+cpu distinct. First preview h2-selector timeout retained; corrected actual h1 title and render succeeded. Old results explicitly retained/reused, not described as newly executed.'}},'limitations':receipt['limits'],'unresolved_dependencies':[]}
canonical=R/'docs/technical-reviews/13.12.json';out(canonical,report);assert json.loads(canonical.read_bytes())==report
out(D/'canonical-written.json',{'canonical':rel(canonical),'report_sha256':sha(canonical),'source_sha256':report['source_sha256'],'reinspection_id':ID,'receipt_path':rel(D/'reinspection-receipt.json'),'receipt_sha256':sha(D/'reinspection-receipt.json'),'written_and_readback_confirmed':True})
print(json.dumps({'verdict':'pass','report_sha256':sha(canonical),'source_sha256':report['source_sha256'],'receipt_sha256':sha(D/'reinspection-receipt.json'),'claims':len(claims),'artifacts':len(artifacts)},ensure_ascii=False))
