from pathlib import Path
from datetime import datetime,UTC
import json,hashlib,shutil,re,platform
R=Path.cwd();A=R/'docs/technical-reviews/artifacts/phase4-13_15-independent';M=json.loads((R/(A/'context-reinspection-v4/latest-start-path.txt').read_text().strip()).read_text());O=R/M['inspection_path'];stamp=O.name;history=R/M['prior_report_history_path'];report=json.loads(history.read_text());inspection=O/'v4-inspection-result.json';I=json.loads(inspection.read_text());render=json.loads((O/'roles-render-command.json').read_text())
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def write(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2,allow_nan=False)+'\n')
assert sha(history)=='aaf54861dc6196fa9fb26cadcbb75f3a7b04db668c334637885a8e4d0c321001';assert I['verdict']=='pass' and not I['unresolved_questions'] and I['visual_inspection']['actually_viewed'];assert report['reviewer_task']=='/root/phase4_factual_coordinator/factual_13_15'
inspection_id='context-v4-inspection-'+stamp;receipt_id='context-v4-receipt-'+stamp
receipt={'schema_version':1,'kind':'same_original_owner_v4_necessary_context_reinspection','reviewer_task':report['reviewer_task'],'verdict':'pass','started_on_utc':M['started_on_utc'],'completed_on_utc':datetime.now(UTC).isoformat(),'source':'course/chapters/13.md#13.15','source_sha256':M['section_context_comparison']['13.15']['current_sha256'],'inspection_artifact_id':inspection_id,'inspection_path':str(inspection.relative_to(R)),'inspection_sha256':sha(inspection),'prior_opaque_report':{'path':M['prior_report_history_path'],'sha256':M['prior_report_sha256'],'meaning':'Exact own canonical aaf548... backed up before inspection/replacement; all existing own proof/PASS/history retained unchanged'},'current_context_slices':M['section_context_comparison'],'current_context_frozen_input':{'path':str((O/'chapter-13-v4-frozen-input.md').relative_to(R)),'sha256':M['frozen_current_chapter_sha256'],'meaning':M['snapshot_meaning']},'previous_context_input':{'path':M['previous_context_snapshot_path'],'sha256':M['previous_context_snapshot_sha256'],'meaning':'The previous context inspection historical frozen input is retained with its actual original version, not repurposed as current V4'},'actual_scope':I['actual_scope'],'fingerprint_only_scope':I['fingerprint_only_context'],'changed_semantics_assessment':I['changes_personally_assessed'],'own_claim_support_assessment':I['claim_support_assessment'],'updated_figure':I['visual_inspection'],'reuse_limits':{'new_neural_network_cpu_execution':False,'primary_source_download':False,'gpu_training_or_weight_evaluation':False,'reason':'Code and executable fences are unchanged. Existing actual CPU and original measurement evidence remain applicable; only changed reference timing context required own original authority/implementation reread and new SVG render/view.'},'unresolved_questions':[],'planned_following_command':'.venv/bin/python scripts/check_technical_reviews.py --lesson 13.15 only after new canonical is generated and ownership asserted'}
receipt_path=O/'v4-reinspection-receipt.json';write(receipt_path,receipt);shutil.copyfile(Path(__file__),O/'build-v4-report-executed.py')
artifacts=[]
def add(identifier,p,kind,description,command=None,result=None,environment=None):
 a={'id':identifier,'path':str(p.relative_to(R)),'sha256':sha(p),'kind':kind,'description':description}
 if kind=='execution':a.update(command=command,result=result,environment=environment or I['environment'])
 artifacts.append(a)
add(inspection_id,inspection,'source_snapshot','Own actual V4 semantics/source/AST/figure inspection result, full evidence fingerprints, actual scope and source reuse limits')
add(receipt_id,receipt_path,'source_snapshot','V4 receipt retaining exact previous report and historical input meanings; links to own inspection artifact')
add('prior-v4-own-report-'+stamp,history,'source_snapshot','Opaque exact previous own canonical aaf548... preserved before this reinspection')
for name in ['start.json','13.12-current.md','13.14-current.md','13.15-current.md','13.12-previous-input.md','13.14-previous-input.md','13.15-previous-input.md','13.12-actual-diff.txt','13.14-actual-diff.txt','roles-svg-actual-diff.txt','chapter-13-v4-frozen-input.md','rewrite-13-model-roles.svg','rewrite-13-clip-cases.svg','authority-reread.json','implementation-reread.json']:
 add('v4-input-'+stamp+'-'+name.replace('.','-'),O/name,'source_snapshot','Actual immutable V4 inspection input/diff/primary-source own reread: '+name)
for name in ['check-v4-executed.py','build-v4-report-executed.py','roles-render-inline.py']:
 add('v4-code-'+stamp+'-'+name.replace('.','-'),O/name,'code','Exact executed V4 inspection code; roles-render-inline.py preserves actual earlier heredoc stdin without claiming a second render run')
add('v4-check-run-'+stamp,O/'inspection.stdout','execution','True stdout of V4 fingerprint/AST and claim-support check','.venv/bin/python docs/technical-reviews/artifacts/phase4-13_15-independent/context-reinspection-v4/check-v4.py','Exit 0: code/fences/primary snapshots/previous own proof unchanged; changed context supported by original authority and actual implementation; updated SVG actually viewed')
add('v4-render-run-'+stamp,O/'roles-render-command.json','execution','Actual Inkscape command, stdout/stderr and environment from changed role SVG render','Inkscape command_argv captured in this JSON, invoked through the preserved roles-render-inline.py stdin code','Exit 0; new roles PNG generated and personally viewed; source SHA d7589ab9e44118540111e8f331b555d4d6c4db3f548e7d373bf7d40750eba406',render['environment'])
add('v4-roles-view-'+stamp,O/'rewrite-13-model-roles.png','figure_render','Actually viewed current role SVG raster; reference states PPO起點 and整段PPO期間不更新')
report['artifacts']=report['artifacts']+artifacts
# Preserve earlier metadata as historical inspection, never make its frozen input pretend to be V4.
report.setdefault('context_reinspection_history',[]).append(report['context_reinspection'])
report['context_reinspection']={'version':'V4 same original owner necessary-context reinspection','reviewer_task':report['reviewer_task'],'inspection_artifact_id':inspection_id,'inspection_path':str(inspection.relative_to(R)),'inspection_sha256':sha(inspection),'receipt_artifact_id':receipt_id,'receipt_path':str(receipt_path.relative_to(R)),'receipt_sha256':sha(receipt_path),'prior_report_path':M['prior_report_history_path'],'prior_report_sha256':M['prior_report_sha256'],'actual_new_scope':I['actual_scope'],'fingerprint_only_scope':I['fingerprint_only_context'],'current_context_sha256':{s:d['current_sha256'] for s,d in M['section_context_comparison'].items()},'current_context_frozen_input':receipt['current_context_frozen_input'],'updated_prerequisite_figure_sha256':{'course/figures/rewrite-13-model-roles.svg':I['visual_inspection']['svg_sha256']},'support_reuse':I['claim_support_assessment'],'open_questions':[]}
report['actual_read_scope']+=['V4 '+stamp+': '+s for s in I['actual_scope']]
report['figure_sha256']={'course/figures/rewrite-13-model-roles.svg':I['visual_inspection']['svg_sha256']}
report['reviewed_on']='2026-10-06';report['verdict']='pass';report['source_sha256']=receipt['source_sha256']
for c in report['claims']:
 if c['id'] in I['claim_support_assessment']['affected_claim_ids']:c['artifact_ids'].append(inspection_id)
 if c['id']=='reference-value':
  c['scope']='Explicit finite-card KL/value recipe, with distinct references by demonstration scope: the untrained short fence clones its random policy before its miniature PPO update; the saved full experiment freezes a copy after demonstration training and initializes PPO from it. Both references stay fixed during their respective PPO phase. This is distinct from rollout-old probabilities and does not assert every earlier posttraining stage is frozen.'
  c['evidence'].append({'source_id':'experiment','locator':'run_posttraining278–289,326–339, personally reread during V4','supports':'Original unchanged code trains SFT before cloning/freeze at289, starts PPO from that trained reference at326, and captures new old-selected probabilities each rollout at338–339. This directly supports the corrected necessary context. The original random short fence remains clearly labeled an untrained flow example.'})
for s in report['sources']:
 if s['id']=='instructgpt':s['inspection_note']+=' V4 same-owner reread on2026-10-06: Section3.1 steps1–3 and Section3.5 RL/equation2 personally inspected again from own original immutable source; these locate the supervised policy before PPO and piSFT reference. No source download or version substitution.'
 if s['id']=='experiment':s['inspection_note']+=' V4 actual unchanged SHA verified and run_posttraining278–294/314–344 personally reread for SFT-reference construction and PPO rollout capture.'
report['checks']['factual_accuracy']['details']='All 14 own substantive claims retain their original primary-source, implementation and true execution support. In V4 the same original reviewer personally reread current13.15 and necessary13.12/13.14, actual changed SVG, original InstructGPT3.1/3.5 and exact reference/rollout implementation. The corrected PPO-start/period context is supported. The short random-flow reference and saved SFT-trained reference are explicitly distinguished; no unresolved question remains.'
report['checks']['numeric_verification']['details']+=' V4 fences are byte-identical and AST-identical to the previous own input, and every relevant code/raw measurement/source/artifact fingerprint was actually verified. Original true numeric/model execution evidence is explicitly reused; no numerical behavior changed or new model experiment was run.'
report['checks']['figure_consistency']={'status':'pass','details':'13.15 itself has no SVG reference; the explicitly declared necessary13.14 roles SVG changed and is now version-pinned here at d7589ab9e44118540111e8f331b555d4d6c4db3f548e7d373bf7d40750eba406. Personally rendered current bytes with Inkscape and viewed the raster. Reference says PPO起點/整段PPO期間不更新, while old remains a per-rollout log-probability record. All five role labels agree with original code and the current necessary context. Previous SVG and page-render evidence remain historical; unchanged clipping figure evidence is explicitly reused.','claim_ids':['ppo-cycle','reference-value','autograd-apis']}
report['checks']['source_verification']['details']+=' V4 personally reread the already verified immutable InstructGPT original passages supporting the new PPO-start reference wording, and reread the exact unchanged SFT/reference/PPO code. No peer/root assessment, other report, primary-source redownload or replacement of previous historical fingerprints was used.'
report['checks']['limitations']['details']+=' V4 is a same-owner declared-context reinspection. Only affected context, original primary passages/implementation and changed role SVG were substantively reread/viewed; all original CPU/saved measurement evidence is retained as original evidence, not reported as a rerun.'
report['limitations'].append('V4 '+stamp+': ownbody13.15 unchanged. Changed13.12/13.14 reference timing wording and changed necessary roles SVG personally checked against own original primary source and implementation. Original CPU/measurement proof reused after actual fingerprints; no model rerun, full training, GPU, weight evaluation or source download.')
# Current own source and affected context must still equal this actual frozen input.
raw=(R/'course/chapters/13.md').read_bytes();hs=list(re.finditer(rb'(?m)^## [^\r\n]+',raw))
for sid in ['13.12','13.14','13.15']:
 i=next(i for i,h in enumerate(hs) if h[0].startswith(('## '+sid+' ').encode()));end=hs[i+1].start() if i+1<len(hs) else len(raw);assert hashlib.sha256(raw[hs[i].start():end]).hexdigest()==M['section_context_comparison'][sid]['current_sha256']
assert sha(R/'course/figures/rewrite-13-model-roles.svg')==I['visual_inspection']['svg_sha256']
canonical=R/'docs/technical-reviews/13.15.json';write(canonical,report);saved=json.loads(canonical.read_text());assert saved['reviewer_task']=='/root/phase4_factual_coordinator/factual_13_15' and saved['source_sha256']=='e376567c6581561ce0590ca5987621219b13ec5a3bba2619fb250f2a3df2e0d8' and saved['context_reinspection']['inspection_sha256']==sha(inspection)
confirmation={'canonical_generated_and_confirmed':True,'verdict':saved['verdict'],'report_path':str(canonical.relative_to(R)),'report_sha256':sha(canonical),'source_sha256':saved['source_sha256'],'reviewer_task':saved['reviewer_task'],'inspection_artifact_id':inspection_id,'inspection_path':str(inspection.relative_to(R)),'inspection_sha256':sha(inspection),'receipt_path':str(receipt_path.relative_to(R)),'receipt_sha256':sha(receipt_path),'prior_opaque_path':M['prior_report_history_path'],'prior_opaque_sha256':M['prior_report_sha256'],'actual_scope':I['actual_scope']};write(O/'canonical-generation-confirmation.json',confirmation);print(json.dumps(confirmation,ensure_ascii=False,indent=2))
