"""Write this reviewer's newly authored report from its own permanent proof."""
import hashlib
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[4]
OUT = pathlib.Path(__file__).resolve().parent
REL = OUT.relative_to(ROOT).as_posix()
def sha(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()
def rel(name):
    return f"{REL}/{name}"
def evidence(source, locator, supports):
    return {"source_id": source, "locator": locator, "supports": supports}
results = json.loads((OUT / "independent-results.json").read_text())
metadata = json.loads((OUT / "extraction.json").read_text())
env = {k: str(v) for k, v in results["environment"].items()}
original_command = json.loads((OUT / "original-execution.json").read_text())["command"]
check_command = "env CUDA_VISIBLE_DEVICES='' HF_HUB_OFFLINE=1 HF_DATASETS_OFFLINE=1 TRANSFORMERS_OFFLINE=1 OMP_NUM_THREADS=1 MKL_NUM_THREADS=1 .venv/bin/python docs/technical-reviews/artifacts/phase4-16_2-independent/check_section.py"

notes = """# 16.2 independent factual inspection

Reviewer: /root/phase4_factual_coordinator/factual_16_2; fresh task, only 16.2 adjudicated.

Read scope: current 16.2 original section bytes, lines 62–102; preceding 16.1 lines 10–61 for timing terminology. A targeted search of the current chapter for source/report/JSON URLs exposed source-lookup snippets elsewhere in that chapter; those sections were not adjudicated. No chapter-introduction adjudication. No old technical/reader reports, author review, or author correction summaries were read. The source catalogue was inspected only for top-level types and an empty coverage lookup, never for a judgement. Ordinary method comments and the original fixed-cost benchmark rule were read as method contracts, then independently checked.

The frozen full chapter is an input snapshot from this inspection, not a claim about any subsequently edited whole chapter. Its exact bytes are in frozen-input-chapter-16.md; source_sha256 is the section's original UTF-8 bytes. This is a non-first section reviewer; chapter introduction is present in the frozen whole-file bytes but was not separately reviewed.

Code inspection first used AST to locate methods. Personally read model.py 15–86 and 109–131; attention.py 10–74; data.py 11–28; common.py 243–304; architecture.py current 496–557, 918–945, 99–105, 289–290. For the raw experiment, retrieved the immutable revision 48a4f3e912b483d70aee57c42c2aac226534a9a6; its architecture.py SHA exactly matches the raw JSON code_sha256. Personally read original _benchmark 494–510, _fixed_decode 514–521, _cache_probe 525–555, and run_efficiency 916–943; checked _sync contract. Did not execute training, GPU timing, download datasets/models, load checkpoints, or evaluate language quality.

Raw JSON inspection began with top-level keys/types and then the named pointers retained in independent-results.json /raw_pointers_read. Only provenance, MHA configuration, prompt/output counts, generated IDs/text, and three timing records were inspected. No author result explanation was read. The full original JSON is preserved without deleting notes. Original nine-sample medians independently give 2.421216000001891 ms, 29.034201000001758 ms and 27.915452999998536 ms; seconds × 1000; three-decimal text tolerance is 0.0005 ms. Each record has three warmup calls and nine synchronized measured calls. This is an audit of existing L4 measurements, not reproduced GPU performance.

Primary documentation personally read: Hugging Face Transformers v4.57.1 Caching (Caching, Attention matrices, Cache class, Cache storage implementation; the rest of the small raw document was also viewed); tokenizer summary introduction/subword paragraphs and byte-level lines 203–211; PyTorch 2.14 Module.eval and no_grad; NVIDIA NIM LLM benchmarking latest Metrics TTFT/e2e/ITL/TPS definitions. Exact useful primary fragments and their original line ranges are retained. Downloaded raw-document hashes and URLs are in source-fetch-log.json. NVIDIA latest is a rolling document, explicitly frozen at access 2026-10-05; it is not claimed to be an immutable release. External documentation examples were read, never run.

Source support limits: HF documents support causal attention reuse and increasing full-context cache, not this repo's precise API or benchmark speeds. PyTorch documents support eval/gradient-mode semantics, checked against installed 2.14.1+cpu; GPU report uses 2.14.1+cu126/Python 3.13.3, distinct from CPU Python 3.13.5. NVIDIA definitions support metric endpoints and why prompt/output/concurrency conditions matter, not any reproduced service TTFT. This full-cache path has no sliding-window truncation.

Bounded CPU evidence: original fence execution exit 0, no audit-guard events; independent 4/6-token forward variations, projection-input hooks, no_grad state and unchanged parameter check; one Chinese character encodes as three byte tokens; exact historical _fixed_decode AST run with an always-EOS CPU control generates all 12 IDs (calls 25 then 11 × 1 with cache), while normal generate stops at its first EOS. These are shape/control checks, not trained-model results. Neither backward nor optimizer steps were run.

Figure applicability: 16.2 references no image/SVG and makes no claim about a displayed screen or spatial layout. The complete tensor shapes and labelled axes are stated in text. Figure rendering is specifically not applicable; no render or desktop/mobile screenshot is claimed. Diagrams on the official metric web page were not used as visual evidence; only its written definitions were used.

No unresolved substantive claim found. This pass is limited to current 16.2 and the original evidence inspected above.
"""
(OUT / "inspection-notes.md").write_text(notes)
(OUT / "commands.txt").write_text(
    ".venv/bin/python docs/review-tools/section_facts.py 'course/chapters/16.md#16.2' --output /tmp/phase4-16_2-independent-extract\n"
    ".venv/bin/python docs/review-tools/section_facts.py 'course/chapters/16.md#16.2' --output /tmp/phase4-16_2-independent-run --execute --timeout 40\n"
    + original_command + "\n" + check_command + " > docs/technical-reviews/artifacts/phase4-16_2-independent/independent-stdout.txt 2> docs/technical-reviews/artifacts/phase4-16_2-independent/independent-stderr.txt\n"
    "git show 48a4f3e912b483d70aee57c42c2aac226534a9a6:scripts/course_experiments/architecture.py (captured as bytes via Python subprocess; SHA checked against original JSON)\n"
)

artifacts = []
for file in sorted(OUT.rglob("*")):
    if not file.is_file() or file.name in {"artifact-manifest.json", "checker-stdout.txt", "checker-stderr.txt"}:
        continue
    name = file.relative_to(OUT).as_posix()
    kind = "code" if file.suffix == ".py" else "source_snapshot"
    item = {"id": "proof-" + name.replace("/", "-").replace(".", "-"), "path": rel(name), "sha256": sha(file), "kind": kind, "description": f"Actual preserved {name}; see inspection-notes.md for reading and support scope."}
    if name == "original-execution.json":
        item.update(id="original-execution", kind="execution", command=original_command, result="Exit 0; original fence produced logits (1,4,264)/(1,1,264), K (1,1,4,8)/(1,1,5,8); no guard events.", environment=env)
    if name == "independent-results.json":
        item.update(id="independent-execution", kind="execution", command=check_command, result="Exit 0; independent short CPU shape/control checks, exact raw medians and source-code SHA assertions passed.", environment=env)
    if name == "inspection-notes.md":
        item.update(id="inspection-record", kind="derivation", description="This reviewer's scope, inspected source locators, unit/median reasoning and support limits.")
    artifacts.append(item)
artifact_by_name = {pathlib.Path(a["path"]).relative_to(OUT.relative_to(ROOT)).as_posix(): a["id"] for a in artifacts}

sources = []
def official(identifier, title, url, version, reason, note):
    sources.append({"id": identifier, "kind": "official_docs", "title": title, "url": url, "version": version, "authority_reason": reason, "accessed_on": "2026-10-05", "checked_original": True, "verified": True, "inspection_note": note})
official("hf-cache", "Transformers: Caching", "https://huggingface.co/docs/transformers/v4.57.1/cache_explanation", "Transformers v4.57.1; versioned official source Markdown", "Maintainer documentation and version-tagged source in the Hugging Face Transformers repository.", "Personally read Caching/Attention matrices/Cache class/Cache storage implementation, plus remaining source document; useful original fragment and original line ranges preserved. Supports causal full-context KV reuse; not TinyLM API equivalence or measured performance.")
official("hf-tokenizer", "Transformers: Summary of tokenizers", "https://huggingface.co/docs/transformers/v4.57.1/tokenizer_summary", "Transformers v4.57.1; versioned official source Markdown", "Tokenizer library maintainer's official documentation with version-tagged original Markdown.", "Personally read original lines 1–150 and 203–211, including word/subword ID mapping and byte-level base symbols; useful raw fragments retained. No pretrained tokenizer downloads executed.")
official("torch-eval", "PyTorch Module.eval", "https://docs.pytorch.org/docs/2.14/generated/torch.nn.Module.html#torch.nn.Module.eval", "PyTorch documentation 2.14; installed CPU wheel 2.14.1+cpu", "Official PyTorch API documentation.", "Personally read Module.eval method body: evaluation mode equals train(False), affects certain modules and does not itself disable gradients. Exact HTML method fragment retained.")
official("torch-no-grad", "PyTorch torch.no_grad", "https://docs.pytorch.org/docs/2.14/generated/torch.no_grad.html", "PyTorch documentation 2.14; installed CPU wheel 2.14.1+cpu", "Official PyTorch gradient-mode API documentation.", "Personally read no_grad description, requires_grad behavior, factory-function and forward-mode exceptions, and examples. Supports reverse-mode gradient recording here; no claim to disable forward AD.")
official("nvidia-metrics", "NVIDIA NIM LLM benchmarking: Metrics", "https://docs.nvidia.com/nim/benchmarking/llm/latest/metrics.html", "Rolling latest documentation accessed 2026-10-05; full HTML SHA 2b915a813b8ec38598e6710a28a7a326f453d53a8feb2abf7a6e63fbc1e1e0b2", "NVIDIA's official inference-benchmarking definitions.", "Personally read TTFT, e2e, ITL and TPS definitions, including queuing/prefill/network, output_tokens−1 ITL denominator and concurrency effects. Original main HTML and text preserved; written definitions only, no external diagram visual audit.")
def code(identifier, path, version, note):
    sources.append({"id": identifier, "kind": "repository_code", "title": path, "path": path, "sha256": sha(ROOT / path), "version": version, "verified": True, "inspection_note": note})
code("tiny-model", "tiny_perceptron/model.py", "Content SHA matches raw experiment revision 48a4f3e912b483d70aee57c42c2aac226534a9a6", "AST located ModelConfig/Block/TinyLM/generate; read 15–86,109–131. Checked defaults, positions offset, per-layer cache, logits, and EOS stop.")
code("tiny-attention", "tiny_perceptron/attention.py", "Content SHA matches raw experiment revision 48a4f3e912b483d70aee57c42c2aac226534a9a6", "AST located methods then read 10–74: Q/K/V projections, cache concat axis 2, head reshape, causal mask and attention contraction.")
code("byte-tokenizer", "tiny_perceptron/data.py", "Content SHA matches raw experiment revision 48a4f3e912b483d70aee57c42c2aac226534a9a6", "AST located ByteTokenizer, read 11–28: eight specials, UTF-8 byte IDs, BOS=1 and EOS=2, special-ID omission on decode.")
code("heldout-contract", "scripts/course_experiments/common.py", "Content SHA matches raw experiment revision 48a4f3e912b483d70aee57c42c2aac226534a9a6", "AST located evaluate_lm; read 243–304. SFT prompt ends assistant role, generate receives eos_id, and generated sequence is cut at EOS before scoring.")
code("original-benchmark", rel("code-snapshots/architecture-at-raw-revision.py"), "Immutable git revision 48a4f3e912b483d70aee57c42c2aac226534a9a6; SHA exactly matches raw JSON /code_sha256/scripts~1course_experiments~1architecture.py", "AST located original _sync, _benchmark 494–510, _fixed_decode 514–521, _cache_probe 525–555, run_efficiency 916–943; personally checked timing boundaries and fixed-step/no-EOS rule. Only _fixed_decode was run with a bounded CPU control.")
sources += [{"id": "original-run", "kind": "execution", "title": "Original 16.2 Python fence on CPU", "artifact_id": "original-execution", "verified": True}, {"id": "independent-run", "kind": "execution", "title": "Independent CPU variations and existing raw-measurement audit", "artifact_id": "independent-execution", "verified": True}]

def claim(identifier, kind, statement, location, scope, ev, arts=None, verification=None):
    c = {"id": identifier, "kind": kind, "statement": statement, "location": location, "scope": scope, "status": "verified", "evidence": ev, "artifact_ids": arts or []}
    if verification is not None:
        c["verification"] = verification
    return c
def verification(expected, observed, details, **kw):
    return {"method": "executed", "expected": expected, "observed": observed, "details": details, **kw}
claims = [
    claim("C1", "concept", "Token is a generation unit mapped to an ID; it need not be an entire written character or word.", "16.2 opening paragraph (line 64)", "General word/subword/byte tokenization; this TinyLM uses the repository ByteTokenizer rather than a pretrained tokenizer.", [evidence("hf-tokenizer", "Introduction/Subword tokenization; original source lines 25–35,100–137,203–211", "Words/subwords become IDs; byte-level units can represent character pieces."), evidence("byte-tokenizer", "ByteTokenizer.encode/decode, data.py 14–25", "This tokenizer maps each UTF-8 byte to its own ID; independently checked 字 uses three IDs.")], ["independent-execution"]),
    claim("C2", "concept", "Prefill processes prompt positions; cached decode computes a new query and new K/V for the added token while attending to retained K/V, and each layer retains its own cache.", "16.2 paragraphs 1–2 and cache-work explanation (lines 64–66,86)", "Ordinary causal autoregressive full-context caching, as implemented here; no claim about sliding-window, chunked prefill or speculative decoding variants.", [evidence("hf-cache", "Caching; Attention matrices; Cache storage implementation", "Stored past K/V are reused, current query attends to concatenated past/current K/V, appended per layer; cache sequence dimension grows."), evidence("tiny-attention", "CausalAttention.forward 48–74; manual_attention 21–28", "Projection inputs are new positions; concat/cache/attention retain full context."), evidence("nvidia-metrics", "Inter-token Latency", "Full-context KV memory and attention work increase with output length; does not guarantee a particular wall-time slowdown on every device.")], ["independent-execution"]),
    claim("C3", "software", "The fence builds an untrained TinyLM(width=8), switches eval mode, creates integer ID tensors, runs no_grad forward calls, passes per-layer cache and prints shapes; eval and no_grad serve different purposes.", "16.2 explanation and original Python fence (lines 68–82)", "API coverage: TinyLM/ModelConfig defaults and width, torch.tensor IDs, Module.eval, torch.no_grad, TinyLM forward cache keyword, logits/cache keys, layer/K indexing and Tensor.shape/tuple/print. This is shape inspection with forced ID5, not generated-language evidence; no backward or update.", [evidence("torch-eval", "torch.nn.Module.eval", "Evaluation mode is train(False), not a gradient-disable mechanism."), evidence("torch-no-grad", "torch.no_grad class description", "Disables reverse-mode gradient calculation for forward tensor results here."), evidence("tiny-model", "ModelConfig 15–28; TinyLM.forward 68–86", "Exact local defaults and forward return/cache contract."), evidence("original-run", "original-stdout.txt and original-environment.json; attempted_fences=[1]", "Original fence executed successfully on CPU."), evidence("independent-run", "independent-results.json /eval_alone_requires_grad,/parameters_unchanged,/shape_variants", "eval alone leaves grad recording active; no_grad outputs have no recorded gradient; parameters unchanged.")], ["original-execution", "independent-execution"], verification("Successful forward-only fence; eval distinct from no_grad and no updates.", "Original exit 0; eval-only logits requires_grad=true; no_grad outputs false; parameters exactly unchanged.", "No backward or optimizer was invoked; forced ID5 is not sampled from the random model.")),
    claim("C4", "numeric", "Four prompt IDs yield logits (1,4,264), one added ID yields (1,1,264); first-layer K grows (1,1,4,8)→(1,1,5,8). Six prompt IDs give (1,6,264) and K lengths 6→7.", "16.2 printed shapes and exercise (lines 84,90)", "Axes are batch, position, vocabulary for logits and batch, KV head, retained position, per-head feature for K. Defaults one head, width=8, vocab=264, no padding/packing; all dimensions are counts, not timing units.", [evidence("tiny-model", "ModelConfig 15–28; TinyLM.forward 68–86", "Defaults vocab=264/head=1; logits preserve current positions and cache offset."), evidence("tiny-attention", "CausalAttention.forward 50–63", "K reshape [B,Hkv,T,width/H] and append along retained position axis."), evidence("original-run", "original-stdout.txt", "Actual four-position output matches each stated shape."), evidence("independent-run", "independent-results.json /shape_variants", "Executed six-position variation and hooks verifying new projection lengths=1.")], ["original-execution", "independent-execution"], verification("Exact integer dimensions for four/six prompt positions and one new ID.", "Four: logits [1,4,264]/[1,1,264], K [1,1,4,8]/[1,1,5,8]; six: [1,6,264]/[1,1,264], K [1,1,6,8]/[1,1,7,8].", "width/head=8/1=8; total retained positions L+1. Old K slice remained exactly identical.", tolerance="Exact integer shape equality; exact torch.equal for retained K.")),
    claim("C5", "concept", "TTFT spans request submission to the first received token and may include preprocessing, transport and queuing; it differs from a model-only prefill call. Prompt/output lengths and concurrency are comparison conditions; subsequent decode rate uses its own interval.", "16.2 service-metric paragraph (line 88)", "Service endpoints and metric distinctions, not a measured service TTFT or a claim about a specific server implementation. No single undocumented tokens/s denominator is endorsed.", [evidence("nvidia-metrics", "Time to First Token; End-to-End Request Latency; Inter-token Latency; Tokens Per Second", "TTFT includes queue/prefill/network and tokenization figure caption; ITL=(e2e−TTFT)/(output_tokens−1); lengths and concurrency affect performance and throughput definitions.")]),
    claim("C6", "empirical", "The existing L4 MHA record uses four Q/KV heads, the prompt with BOS for 25 input positions and 12 fixed new IDs; medians are prefill 2.421 ms, full path 29.034 ms and cached path 27.915 ms.", "16.2 optional raw-measurement paragraph (line 95)", "Audit of existing record at revision 48a4f3e912b483d70aee57c42c2aac226534a9a6, not new GPU measurements. GPU Python3.13.3/PyTorch2.14.1+cu126; CPU audit Python3.13.5/PyTorch2.14.1+cpu. Times characterize this prompt, model/config and method only.", [evidence("independent-run", "independent-results.json /raw_provenance,/original_measurements,/raw_generation; raw-efficiency.json named pointers in /raw_pointers_read", "Recomputed all three nine-sample medians, prompt byte/BOS count, generated-ID lengths, GPU provenance and four-head config from original data."), evidence("original-benchmark", "_cache_probe 525–555; _benchmark 494–510; run_efficiency 916–935", "Prompt construction and four-head MHA group; three warmups, nine synchronized measurements and median aggregation."), evidence("byte-tokenizer", "data.py 11–25", "BOS=1 and 24 UTF-8 prompt bytes yield 25 positions.")], ["independent-execution", artifact_by_name["raw-efficiency.json"]], verification("25 input positions, 12 new IDs; rounded medians 2.421/29.034/27.915 ms.", "25 and 12 exact; recomputed medians 2.421216000001891/29.034201000001758/27.915452999998536 ms.", "Three independent timing arrays, each 9 samples; statistics.median equals recorded seconds exactly, multiply by1000 and round to3 decimal places. Full/cached ID lists each contain12 entries. Original architecture SHA recovered and matched.", denominators={"input_positions_including_BOS":25,"new_IDs_per_fixed_call":12,"warmup_calls_per_path":3,"measured_calls_per_path":9,"Q_heads":4,"KV_heads":4}, tolerance="For stated three-decimal milliseconds, absolute error ≤0.0005 ms; integer counts and recorded median seconds exact.")),
    claim("C7", "software", "Both total generation timing paths include prefill and ignore EOS to run 12 steps, while normal heldout generation stops at EOS; fixed-cost text is not language-quality evidence and 12/total_seconds is not pure subsequent-decode throughput.", "16.2 optional method limits (lines 95–97)", "Exact historical benchmark loop and repository SFT evaluation contract, tested using a bounded always-EOS CPU control rather than model-score reevaluation. No training, checkpoint loading or GPU rerun.", [evidence("original-benchmark", "_fixed_decode 514–521; _cache_probe 525–555", "State starts None; first call includes whole prompt; loop is fixed range(tokens), with no EOS break; timed lambdas enclose entire fixed loop."), evidence("heldout-contract", "evaluate_lm common.py 243–278", "Normal SFT evaluation calls generate with tokenizer EOS and trims generated content at EOS."), evidence("tiny-model", "generate 109–131", "Normal single-sequence generation breaks at EOS."), evidence("independent-run", "independent-results.json /fixed_cost_control,/normal_generation_EOS_control,/raw_generation", "Exact historical loop produced12 EOS IDs with first-call length25; normal generate produced one EOS and stopped. Existing raw output contains4 EOS IDs and12 total IDs."), evidence("nvidia-metrics", "ITL denominator and TTFT/e2e separation", "Subsequent decode interval excludes first-token waiting; dividing fixed count by inclusive total does not isolate that interval.")], ["independent-execution"], verification("Cached fixed loop calls lengths [25,1×11], full loop [25…36], no EOS stop; normal generation stops on first EOS.", "All expected call lengths/counts passed; fixed control outputs12 EOS IDs; normal outputs1 EOS ID. Original 12-ID MHA samples have4 EOS IDs.", "Only the AST-extracted original _fixed_decode method and local generate were executed against a deterministic lightweight CPU control. Raw decoded text was checked for faithful recording, not judged for language quality.")),
]
report = {
    "schema_version":1, "review_stage":"technical", "lesson_id":"16.2", "source":"course/chapters/16.md#16.2",
    "source_sha256":metadata["source_sha256"], "reviewer_task":"/root/phase4_factual_coordinator/factual_16_2", "reviewer_context":"fresh", "verdict":"pass",
    "figure_sha256":{}, "artifacts":artifacts, "sources":sources, "claims":claims, "issues":[],
    "frozen_input_full_chapter":{"meaning":"Full chapter frozen at this review's first reading; not a claim about a later whole-file version.","path":rel("frozen-input-chapter-16.md"),"sha256":sha(OUT/"frozen-input-chapter-16.md")},
    "actual_read_scope":{"section":"16.2 original bytes lines62–102","preceding":"16.1 lines10–61; raw snapshot saved","source_lookup":"Targeted source/report/JSON URL match snippets from current chapter; no other section adjudicated.","chapter_intro":"Not reviewed by this non-first reviewer.","forbidden_summary_exposure":False,"detail_record":rel("inspection-notes.md")},
    "checks":{
        "factual_accuracy":{"status":"pass","claim_ids":["C1","C2","C3","C5","C7"],"details":"Each material concept/API checked against personally read primary documentation, exact helper contracts and bounded CPU executions; no claim of model language ability."},
        "numeric_verification":{"status":"pass","claim_ids":["C4","C6"],"details":"Original4/six-position shapes exact; all27 original timing samples audited with nine-sample median and seconds→milliseconds conversion; prompt/BOS/generated counts exact."},
        "figure_consistency":{"status":"not_applicable","claim_ids":[],"details":"16.2 references no image/SVG and asserts no displayed screen or spatial layout. The needed data axes are explicit in text; no render or screenshot was performed or claimed."},
        "source_verification":{"status":"pass","claim_ids":[c["id"] for c in claims],"details":"Personally read official versioned HF/PyTorch documents and frozen rolling NVIDIA definitions; raw data pointers scoped; historic architecture SHA matches original provenance; source snapshots and per-claim locators retained."},
        "limitations":{"status":"pass","claim_ids":["C2","C3","C5","C6","C7"],"details":"Shapes only, forcedID5, no gradient/update or language-quality claim; full-context cache caveat; existing L4 observations separated from CPU checks; timing includes prefill, not service TTFT or pure subsequent decode TPS. No full training, GPU rerun or score reevaluation."},
    },
}
target=ROOT/'docs/technical-reviews/16.2.json'
target.write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n')
saved=json.loads(target.read_text())
assert saved['reviewer_task']=='/root/phase4_factual_coordinator/factual_16_2'
assert saved['source_sha256']==sha(OUT/'section.md')
manifest=[{'path':a['path'],'sha256':a['sha256']} for a in artifacts]
(OUT/'artifact-manifest.json').write_text(json.dumps(manifest,indent=2)+'\n')
print(json.dumps({'verdict':saved['verdict'],'reviewer_task':saved['reviewer_task'],'source_sha256':saved['source_sha256'],'report_sha256':sha(target),'proof':REL,'claims':len(claims)},ensure_ascii=False))
