from pathlib import Path
from hashlib import sha256
from datetime import datetime, timezone
import json
repo=Path.cwd();base=repo/'docs/reader-reviews/artifacts/natural-v4-supplemental/site-validation-publishing';run=base/'round2';pres=base/'preserved-first-pass'
def rel(p):return str(p.relative_to(repo))
def h(p):return sha256(p.read_bytes()).hexdigest()
def check(status,details):return {'status':status,'details':details}
first_sha='dac739e31534d8b55f8136a18a99519b216cac16296855a7254c65018a339956'
assert h(pres/'report.json')==first_sha
assert h(base/'report.json')==first_sha
first=json.loads((pres/'report.json').read_text())
expected={'docs/validation.md':'812c4fe7b25cc73fd5a2538f5ece9061bcabc021fc7bf96899d344ff47d0f60e','docs/publishing.md':'1e53b063584358fc6bd6d79ac3cb7f3ca8efa75465764f42a867fa88e9a758fa'}
for path,sha in expected.items():
    assert h(repo/path)==sha
    assert (repo/path).read_bytes()==(run/'snapshots'/path).read_bytes()
    (repo/path).read_bytes().decode('utf-8')
comparison=json.loads((run/'exact-byte-comparison-and-reuse.json').read_text())
assert all(x.get('equal_full_bytes',True) and x.get('equal_bytes',True) and x.get('equal_blocks',True) for x in comparison)
notes={
 'same_reviewer':'This is my corrective second complete-document read, not a new blind reader. I retained my original understanding and low issue, preserved my own first report and all raw evidence, then personally reread both complete current source documents and both new browser articles.',
 'validation_new_views':'Personally viewed new viewport captures 0, 1, 2 and 3 from 8788, covering the intro, all six table rows, distinct experiment scopes, selection/test and speech control, AI-review/reading-time limits, smoke record, literal commands, output path and final local-CPU/Colab limitation. Also personally viewed the new right-scrolled command capture. The unchanged raw source did not substitute for this renewed complete read.',
 'publishing_new_views':'Personally viewed new viewport captures 0, 1, 2 and 3 from 8788, including the learner route, pinned-Notebook/default-branch split, generation roles, the new direct W.1 setup sentence, all literal setup/check/export/server commands, version flag and commit-before-export explanation, Pages workflow, catalog-derived Notebook count, ignored work outputs, build-info and three release routes. Personally viewed both new right-scrolled long-command captures.',
 'W1_route':'Clicked the new actual W.1 link in publishing section 2, landed at first-steps.html#W.1 with visible heading W.1 第一次開啟教材, personally viewed the new screenshot and read the entire rendered W.1 section. It teaches obtaining Git/uv, using a terminal, clone then cd, frozen CPU/Notebook setup, .venv activation, Windows direct-Python fallback, environment check, kernel registration, Jupyter, cells and clean restart. The pyproject.toml cue in publishing identifies the repository root. This is meaningful setup guidance, not just an existing anchor.',
 'renewed_figure_views':'After exact-byte comparison against preserved original SVG and PNG, personally viewed the reused original Inkscape PNG again and the fresh 8788 Chromium 20.12 image-element capture. The common question splits to correct transcript on the left and true recording through ASR/raw transcript on the right, then each reaches the same chat model. The note holds weights/history/photo fixed and asks to check transcription followed by both complete answers. Labels and arrows remain legible. No new Inkscape render was run; the browser screenshot is new. Current preview SVG bytes equal current and first original source bytes.',
 'other_navigation':'New browser clicks reached the reading guide, complete asset-storage article and reciprocal validation link. I reread R.1/R.2 route context and the full rendered asset-storage article; I personally viewed their new screenshots. Other first-pass chapter/example, external GitHub, Notebook-download and Colab-entry evidence is preserved historical evidence, not falsely relabeled as new current-reference navigation.',
 'execution_reuse':'No CPU or help probe was rerun in this round. Preserved harness, pre-execution predictions, actual text/hash/count outputs and five help-probe receipts were copied byte-for-byte. The necessary 20.8/20.12/20.13 source sections and publishing Bash command blocks also match the first pass exactly. Historical outputs help explain the unchanged examples; they are not a claim of a new execution or a current whole-workflow test. The first pass did not record hashes for imported implementation or CLI script files, so no exact implementation identity or current runtime validation is inferred from those preserved receipts.'
}
(run/'personal-reread-and-view-notes.json').write_text(json.dumps(notes,ensure_ascii=False,indent=2)+'\n')
validation_checks={
 'background_and_links':check('pass','On the full renewed read, the bicycle comparison and six-row table still explain which question each kind of evidence answers. The new publishing transition is understandable. I renewed the direct W.1 setup and 20.12 speech-control route in the actual 8788 browser; the other necessary first-pass sources are exact-byte identical and retained as my existing background, not claimed freshly read or clicked.'),
 'terminology':check('pass','Training/validation/final-test roles are defined in the prose. W.1 again supplies Notebook, cell, kernel and .venv meanings. LoRA candidates, ASR two-stage responsibility, fingerprint matching and checkpoint/resume roles remain understandable through the unchanged necessary context. A beginner need not reconstruct model architecture to follow the scope of the evidence.'),
 'examples':check('pass','I can still distinguish wheel/vehicle capability, specific mechanism checks, fixed files, actual updates and held-out task scores. The LoRA acceptance example and correct-transcript control have clear reasons and limits. The cited 31,584-parameter, step-40 to step-80, max-difference-0 record remains a reported flow test. The historical negation/hash/arithmetic probes are expressly reused, not new results or model benchmarks.'),
 'program_explanation':check('pass','The full current block names .venv/project-root prerequisites, four source/review checks, kernel registration, independent notebook execution and unit tests. Outputs/notebooks/ is explained as work products rather than capability scores. I reread every command, including its right-scrolled browser tail, and can identify input/output and scope. No full checker, notebook, pytest, installation or training command was executed.'),
 'exercise':check('not_applicable','The assigned validation page has no separate student exercise. Its rerun procedure is assessed as an operational command sequence, not marked completed. The linked 20.12 repair remains understandable and its own first-pass bounded output is preserved; there was no new exercise execution.')
}
publishing_checks={
 'background_and_links':check('pass','The current opener still separates learning from maintenance. The new setup sentence links directly to W.1 beside the commands, names Git/uv and identifies the root by pyproject.toml. I personally followed and read that complete actual section, which teaches obtaining the tools and project, so the earlier standalone-setup gap is closed. The actual guide and asset-storage destinations remain meaningful routes, not mere existence checks.'),
 'terminology':check('pass','The roles of Zensical, GitHub Pages, dependency groups, uv.lock, .venv, fixed commit and default branch are still understandable. W.1 now supplies terminal/project/tool preparation directly at the point of use. The text distinguishes fixed Notebook source from a preparation clone and source records from generated outputs sent as Pages artifact.'),
 'examples':check('pass','The pinned-Notebook/default-branch example, Windows activation alternative, same-machine 127.0.0.1 explanation and post-deploy build-info check have concrete purposes. I understand what is being fixed, checked and viewed. The first-pass Notebook download/Colab entry is historical entry evidence; neither that nor the new local browser read claims successful Colab execution.'),
 'program_explanation':check('pass','I can follow the full sequence: W.1 tool/project preparation, group installation and activation, current source/review/output/estimate checks, committing intended material, strict export with revision, site checks and HTTP preview, Pages deployment and received-version inspection. The new prerequisite sentence appears before the setup code and makes the starting folder concrete. All command blocks and long tails were personally reread in the current browser. Notebook count is catalog-derived, not a fixed number to type.'),
 'exercise':check('not_applicable','The assigned publishing page contains a maintenance procedure, not a separate student exercise. I explained the steps and actual route but did not install, register a kernel, build, use Git or deploy. Those actions remain unexecuted under this readability assignment.')
}
documents=[]
for order,path,summary,assessment,checks,page in [
 (1,'docs/validation.md','Six evidence questions separate material matching, local execution, mechanism correctness, recorded updates, file identity and held-out capability. Small demonstrations, formal experiments and differently scaled assistants have their own scopes. Validation selects a version before the final test; ASR and chat are tested separately. AI review/time estimates and the cited GPU/HF smoke test have explicit limits, followed by a local rerun route.','After rereading every paragraph/table row/command/link label/limitation, I can explain what each evidence class supports, what it cannot replace, why the candidate is rejected, how the transcript control isolates answering, what the smoke numbers compare and what the local work outputs mean.',validation_checks,'validation'),
 (2,'docs/publishing.md','One source produces paired web and Notebook forms. Students use pages and per-section workbooks; maintainers now receive direct W.1 tool/project preparation before installing locked CPU/notebook/site/dev tools. Current checks, committing intended source, strict executed-output/version/estimate export, HTTP inspection and Pages deployment form a concrete sequence. Counts come from the subsection catalog; source records, site artifacts, data and model releases remain distinct.','After rereading the complete current source and browser page, I can begin from the actual W.1 route, identify the pyproject.toml root and explain all inputs/outputs/steps/count roles. The added route fixes the first-pass low issue without changing my interpretation of version binding, unchanged commands, result limits or the separate asset routes.',publishing_checks,'publishing')]:
    snap=run/'snapshots'/path
    documents.append({'file':path,'source_sha256':expected[path],'fullsource_sha256':expected[path],'hash_method':'Full raw original UTF-8 bytes; no whitespace/newline normalization; UTF-8 decoding succeeded.','snapshot':rel(snap),'snapshot_sha256':h(snap),'complete_document':True,'read_order':order,'own_read_order':['Current complete source from first heading through final limitation.','New actual browser article in the same validation then publishing order; all source prose/table rows/commands/link labels/limitations personally reread.','Personally viewed new overlapping viewport captures 0 through 3 and fresh right-scrolled command captures; meaningful renewed prerequisite navigation followed.'],'own_summary':summary,'understanding_assessment':assessment,'checks':checks,'page_id':page,'actual_browser_url':'http://127.0.0.1:8788/'+page+'.html','browser_provenance':'Existing newly ready executed local preview supplied by coordinator; Chromium /usr/bin/chromium via existing Playwright. This reviewer did not build, start, publish or replace the site.','browser_evidence':{'article_text':rel(run/'browser'/f'{page}.txt'),'rendered_dom':rel(run/'browser'/f'{page}.html'),'full_capture':rel(run/'browser'/f'{page}-full.png'),'personally_viewed_viewport_indices':[0,1,2,3],'navigation_and_code_scroll_receipts':rel(run/'browser/browser-records.json')},'figure_sha256':{},'fullfigure_sha256':{},'no_svg_explanation':'No embedded SVG or figure in either complete assigned document/article. The sole actually necessary linked 20.12 SVG is separately recorded.'})
# Retain my own full unchanged command map with explicit historical probe labeling.
command_map=first['command_workflow']
for command in command_map:
    if 'bounded_probe' in command:
        command['bounded_probe']='Historical first-pass evidence only; not rerun in corrective round: '+command['bounded_probe']
    if 'actual_reader_inspection' in command:
        command['actual_reader_inspection']='Personally reread the existing new preview on port 8788; did not execute the documented port-8000 server command.'
command_map[0]['inputs']='First follow the new direct W.1 route for Git/uv and project retrieval, then enter the directory containing pyproject.toml. Current uv.lock, CPU extra and dev/notebook/site groups supply the local tool environment.'
figure='course/figures/natural-v4-asr-two-routes.svg'
prereq=[]
for c in comparison:
    if 'path' in c:
        p=c['path']
        original=next((x for x in first['necessary_prerequisites'] if x['file']==p),None)
        scope=('Complete actual W.1 renewed through the new publishing link.' if p=='course/first-steps.md' else 'Complete 20.12 renewed in the browser; own earlier chapter introduction/20.8/20.13 understanding retained after exact full-file and section comparison.' if p=='course/chapters/20.md' else 'Complete rendered article renewed; source byte-identical.' if p=='docs/asset-storage.md' else 'Actual R.1/R.2 route context renewed; remainder not newly reviewed.' if p=='course/README.md' else 'Renewed actual image viewing, preserved render reused after exact-byte comparison.' if p==figure else 'Supporting own first-pass read scope retained after exact-byte comparison; no new full read claimed.')
        prereq.append({'file':p,'source_sha256':c['current_full_sha256'],'fullsource_sha256':c['current_full_sha256'],'snapshot':c['current_snapshot'],'read_scope_this_round':scope,'own_original_read_scope':original['source_read_scope'] if original else None,'byte_comparison_receipt':rel(run/'exact-byte-comparison-and-reuse.json')})
report={
 'schema_version':1,'group_id':'site-validation-publishing','reviewer_task':'/root/v4_review_coordinator/reader_site_validation_publishing','review_type':'same original owner corrective complete-document readability only','corrective_round':2,
 'created_utc':datetime.now(timezone.utc).isoformat(),
 'target_reader':'Mathematically capable high-school or basic-college student encountering the project; this corrective assessment is by the same original reader, not a new blind student.',
 'fresh_context':{'kind':'same original reviewer corrective context','statement':'I retained my original knowledge and own first report/low issue, then performed a genuine full current reread of both assigned documents and their new actual browser pages. I did not invent a fresh independent identity or consult another reviewer verdict/author-correction note.','same_original_reviewer':True,'prior_own_report':rel(pres/'report.json'),'prior_own_report_sha256':first_sha,'prior_own_verdict':'pass with one low nonblocking setup-link issue','role_contract':'outputs/natural-v4/review-plan/supplemental-reader-contract.md, already read for this assignment; its preserved first source remains in the preserved evidence.'},
 'preservation':{'receipt':rel(run/'first-pass-preservation.json'),'previous_report':rel(pres/'report.json'),'previous_report_sha256':first_sha,'previous_full_evidence':rel(pres/'fresh-read-20261004T230718Z'),'preserved_before_new_read_and_report':True,'all_old_evidence_copied_and_compared_byte_for_byte':True,'original_root_report_and_original_first_run_untouched':True,'contents':'Genuine first PASS+low issue, both old full raw source snapshots, all own first browser HTML/text/screens, predictions/CPU/help receipts, SVG source/render/view notes and failed evidence-harness attempts.'},
 'assigned_scope':{'source_commit_as_supplied':'25ca4bf5f8f8dc0a9e88aa6cd70caeb4c2f419e8','commit_provenance':'Coordinator supplied freeze; no Git verification performed. Actual full source hashes independently checked at snapshot and report serialization.','files':['docs/validation.md','docs/publishing.md'],'new_actual_preview':'http://127.0.0.1:8788/','preview_kind':'Existing executed local current preview, not a publication; no reading estimates were inserted by this reviewer.','scope':'Complete current source and actual browser pair, all introductions/table rows/commands/link labels/limitations, actual new W.1 setup route meaning, necessary current SVG renewed view and truthful archived-evidence reuse.'},
 'documents':documents,
 'checks':{'background_and_links':check('pass','The complete new browser pair was personally read, and the new direct setup destination was followed and read for its full meaning. The former low issue is closed on that evidence.'),'terminology':check('pass','The current prose and meaningful W.1/unchanged necessary context make evidence roles, local tooling and version/output distinctions understandable.'),'examples':check('pass','All analogies/cited selection, transcript, fingerprint and flow examples remain bounded. Own historical probes are separated from cited results and from this round’s renewed browser views.'),'program_explanation':check('pass','The full command sequence and inputs/outputs/count roles were reread and explained; all commands remain unexecuted as a pipeline. Historical help receipts are not relabeled as new executions.'),'exercise':check('not_applicable','Neither assigned document has a separate student exercise. Operational check steps are understood but not claimed executed; archived small linked exercise probes remain historical.')},
 'own_current_understanding':{
  'validation_evidence':'Matching source/Notebook material, CPU execution, mechanism checks, recorded weight updates and byte identity each answer their own question. Held-out useful-task scoring is separate and cannot be inferred by combining the first five table rows. Small mechanisms do not stand in for natural-input capability; the chapter-19 synthetic model and chapter-20 mature base have different scopes.',
  'splits_and_control':'Training updates weights; validation compares recipes/candidates; final test assesses a fixed selected configuration. Correct transcripts sent to the same chat model check answering independently; true ASR transcripts check the full route. If the correct-text path already fails, recognition alone cannot explain it. A new version tuned on final errors needs a new unseen final test.',
  'numbers_and_roles':'The smoke paragraph cites 31,584 parameters, step 40 retrieval and completion to 80, compared with uninterrupted 80 and recorded max weight difference 0; no such GPU/HF run was done by me. The byte-identical necessary card names separate Qwen base and Whisper ASR counts (2,127,532,032 and 808,878,080), with no active LoRA. Its response denominators 42+84+18+10+3+13+4+4 total 178; 171 endings plus 7 truncations also total 178. Twenty-two transcription clips use character-error rates, not an added generated-chat denominator; shared photos/questions prevent treating all answers as independent situations. These are cited card counts and historical arithmetic, not a new scoring run.',
  'new_setup_route':'A first-time maintainer is now directed from the actual publishing command paragraph to W.1 for Git/uv installation and project retrieval. W.1 defines terminal, clone, cd, local environment and Notebook operation; returning to publishing, pyproject.toml makes the starting root identifiable. The later uv sync adds dev/notebook/site tooling to that project. I did not treat an anchor response as proof of instruction content.',
  'publishing_input_output_sequence':'One Markdown source plus navigation produces paired Notebook/index/web forms. Preparation is followed by source/review/current output/time checks, committing intended material, strict export with executed copies/current estimates/revision, site resource checks and HTTP preview, then Pages deployment and inspection of the received commit/pages/section/output/builder info. The commands write/check work products in outputs/notebooks and outputs/site; count comes from the current subsection catalog. Source and review evidence remain in Git, ignored outputs transfer as artifact. LFS data packages and HF model/configuration releases are separate routes.',
  'version_and_limits':'The fixed Colab Notebook link and a first preparation clone of the default branch are different versions to control. --revision labels/source-links the site but does not save uncommitted edits. 127.0.0.1 denotes the server’s own machine and HTTP preview supports normal browser mechanisms. AI reviews are not human learning tests, and the described reading quantity excludes setup/downloads/hands-on/training waits. No reading-time estimate or Colab runtime success is asserted.'},
 'command_workflow':command_map,
 'necessary_prerequisites':prereq,
 'actual_browser_navigation':{'browser':'Actual /usr/bin/chromium through existing Playwright, 1440x1000 viewport, headless','records':rel(run/'browser/browser-records.json'),'entry':'New home 驗證範圍 click → validation.html with heading 教材實作驗證; final 教材發布 click → publishing.html with heading 教材發布.','new_setup':'Publishing section-2 W.1 click → first-steps.html#W.1, heading W.1 第一次開啟教材; complete section personally read and meaning explained.','other_new_navigation':'Actual 20.12 destination and fresh necessary diagram capture; reading-guide R.1/R.2 route, full asset-storage destination, reciprocal publishing→validation.','historical_navigation_limits':'First-pass external GitHub, Notebook download and Colab popup evidence is preserved at its original commit/port. Those entries were not newly opened for 25ca/8788. Current link labels and rendered URLs were read on the full pair, but the old entry result is not claimed as a current-reference test.','page_doms_and_images':'New full HTML/text/viewport captures are in round2/browser. Only personally viewed captures are identified in the documents and own notes; captured unread later warm-up content is not claimed reviewed.'},
 'figure_sha256':{figure:h(repo/figure)},'fullfigure_sha256':{figure:h(repo/figure)},
 'figure_evidence':[{'original_path':figure,'original_sha256':h(repo/figure),'current_snapshot':rel(run/'snapshots'/figure),'preserved_original_png':rel(run/'reused-first-pass/asr-two-routes.png'),'png_sha256':h(run/'reused-first-pass/asr-two-routes.png'),'original_render_receipt':rel(run/'reused-first-pass/figure-render-receipt.json'),'render_reused':True,'new_inkscape_render':False,'renewed_original_png_personal_view':True,'new_browser_personal_view':rel(run/'browser/20-12-renewed-figure.png'),'new_browser_svg_bytes':rel(run/'browser/asr-two-routes-current-preview.svg'),'comparison_receipt':rel(run/'exact-byte-comparison-and-reuse.json'),'interpretation':notes['renewed_figure_views']}],
 'bounded_execution':{'new_cpu_or_help_execution':False,'archived_original_predictions':rel(run/'reused-first-pass/predictions-before-execution.json'),'archived_actual_outputs':rel(run/'reused-first-pass/bounded-execution.json'),'archived_harness':rel(run/'reused-first-pass/bounded_checks.py'),'archived_help_receipts':[rel(run/'reused-first-pass/CLI-help-receipts.json'),rel(run/'reused-first-pass/reading-time-validate-help-receipt.json')],'exact_byte_reuse':rel(run/'exact-byte-comparison-and-reuse.json'),'original_result_summary':'First-pass text example produced edits 1 / 9 reference characters / 11.1% CER / false; repaired text 0 / 9 / 0% / true. Hash pairs differed then matched; generated-response and ending arithmetic both totalled 178. Five original --help probes exited 0. Those outputs remain byte-identical archived executions, not a rerun.','original_environment_scope':'Historical original .venv run recorded Python 3.13.5 and torch 2.14.1+cpu, no CUDA. This round did not revalidate runtime or imported implementations.','reuse_limit':notes['execution_reuse']},
 'personal_reread_and_view_notes':rel(run/'personal-reread-and-view-notes.json'),
 'verdict':'pass','verdict_reason':'After a genuine complete current source and new browser reread of both documents, I can explain their evidence limits and workflow. The added direct W.1 route contains the needed preparation teaching and closes my initial low issue. No new readability blocker or unresolved issue was found.',
 'issues':[{'key':'publishing-direct-setup-link','file':'docs/publishing.md','location':'Section 2 setup sentence immediately before uv sync.','severity':'low','prior_status':'open_nonblocking','status':'closed','blocking':False,'current_source_text':'先依[W.1](../course/first-steps.md#W.1)取得專案並安裝Git與uv，再到有`pyproject.toml`的專案根目錄安裝工具、啟用環境：','own_closure':'I clicked the actual new W.1 link and read the complete destination, which explains Git/uv, terminal, obtaining/entering the project, .venv and Notebook startup. The publishing sentence now puts that preparation before its commands and identifies the root via pyproject.toml. A reader arriving here directly can find the required starting instructions; my earlier suggestion is resolved.','closure_evidence':[rel(run/'browser/W1-direct-route.txt'),rel(run/'browser/W1-direct-route.png'),rel(run/'browser/browser-records.json')]}],
 'unresolved_issues':[],'unresolved_blocking_issues':[],
 'scope_limits':['Same original AI reader performing a corrective reread, not a new fresh-context reader or human-student outcome study.','Readability only: cited GPU/HF/model counts/task scores/asset sizes/existing CPU outputs were not factually reaudited or replicated.','Both assigned documents and actual new browser pages were fully reread. W.1/20.12 and necessary SVG views were renewed; other unchanged prerequisites are truthfully separated into original read scope and exact-byte reuse.','No new CPU/help probe, new Inkscape render, Colab runtime, model inference, installation/kernel registration, data/model download, training, full tests/checkers, site build, Git action, publication or reading-time estimate.','Current external frozen-reference destinations, Notebook download and Colab entry were not retested in this round; preserved first-pass entry evidence remains historical.','No product source/checker/navigation/time/global plan/index/environment configuration edit. Own new evidence/report are confined to this supplemental folder; all first raw evidence and first report remain preserved.'],
 'self_revision_history':{'kind':'genuine same-owner corrective round 2 after the publishing setup correction','prior_report_sha256':first_sha,'prior_report_preserved':rel(pres/'report.json'),'old_validation_source_sha256':first['documents'][0]['source_sha256'],'old_publishing_source_sha256':first['documents'][1]['source_sha256'],'new_source_sha256':expected,'full_two_document_reread_completed':True,'new_actual_browser_pair_reread_completed':True,'no_expected_verdict':'The current pass and closure are my own judgement from the actual complete reread and meaningful destination inspection.'}
}
receipts=[]
for p in sorted(run.rglob('*')):
    if p.is_file():receipts.append({'path':rel(p),'sha256':h(p),'bytes':p.stat().st_size})
report['artifact_receipts']=receipts
out=run/'report.json';assert not out.exists()
out.write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n')
loaded=json.loads(out.read_text())
for receipt in loaded['artifact_receipts']:assert h(repo/receipt['path'])==receipt['sha256']
for doc in loaded['documents']:assert set(doc['checks'])=={'background_and_links','terminology','examples','program_explanation','exercise'}
for receipt in json.loads((run/'first-pass-preservation.json').read_text())['preservation_receipts']:
    assert h(repo/receipt['original'])==receipt['sha256'];assert h(repo/receipt['preserved'])==receipt['sha256']
report_sha=h(out);(run/'report-sha256.txt').write_text(report_sha+'  '+rel(out)+'\n')
print(json.dumps({'report':rel(out),'sha256':report_sha,'verdict':loaded['verdict'],'current_source_hashes':expected,'issue_status':loaded['issues'][0]['status'],'new_browser':'http://127.0.0.1:8788/','round2_artifact_receipts':len(receipts),'first_report_still_exact':h(base/'report.json')==first_sha,'all_receipts_match':True},ensure_ascii=False,indent=2))
