from pathlib import Path
import copy,hashlib,json
OUT=Path(__file__).resolve().parent;PRIOR=OUT.parent;ROOT=OUT.parents[5];R3=PRIOR/'round3';BASE=OUT.relative_to(ROOT).as_posix()+'/'
def read(p):return json.loads(Path(p).read_text())
def sha(p):return hashlib.sha256((ROOT/p).read_bytes()).hexdigest()
old=read(R3/'report.json');delta=read(OUT/'delta-record.json');r=copy.deepcopy(old)
assert sha((R3/'report.json').relative_to(ROOT))=='4db9ccf8364d5e9b425f2dbe9811edbc5c6efd9c3b565c7db87c2b133cc1455e'
def artifact(id,kind,name,description,command=None,result=None):
 a={'id':id,'kind':kind,'path':BASE+name,'sha256':sha(BASE+name),'description':description}
 if kind=='execution':a.update(command=command,result=result,environment=delta['environment'].copy())
 r['artifacts'].append(a)
artifact('a_r4delta','execution','delta-record.json','Own actual workflow before/after/current exact-byte comparison,independent delta assessment,prior fullreview/authority/evidence identity checks,actualpytesthelp and exact current summary Python execution on two explicitly synthetic local fixtures.','.venv/bin/python '+BASE+'delta_probe.py','Exit0. Only registered r_ci changed; current SHA52290167…; all4authored documents/currentSVG/priorregistered evidence andothercode/authority texts remain exact. Actual pytest9.1.1help supports JUnit argument; exactsummary body handles absentXML andfailure/error/pass/skip fixtures as recorded.')
artifact('r4_probe','code','delta_probe.py','Exact own bounded reviewer probe; not a hosted CI/fulltest rerun.')
artifact('r4_summary_code','code','actual-workflow-summary.py','Current workflow Python body extracted verbatim by dedenting only its YAMLindentation; actually executed on synthetic fixtures.')
for name in ['delta.stdout.txt','delta.stderr.txt','ci.before.read-snapshot.yml','ci.after.read-snapshot.yml','prior-round3-report.read-snapshot.json','ci.actual-delta.diff.txt','missing_report.summary.md','failure_error_pass_skip.summary.md']:
 artifact('r4_'+name.replace('.','_').replace('-','_'),'source_snapshot',name,'Own exact source/delta/originalreport or actualbounded-execution output; previous actualreports/failure findings remain immutable.')
for s in r['sources']:
 if s['id']=='r_ci':
  s['sha256']=delta['own_delta_assessment']['current_sha256']
  s['version']='Current .github/workflows/ci.yml bytes independently read2026-10-05; SHA25652290167d796430e3c0685e17b8369061a2588175689423f87dfc5c43464aff3. Declared source freeze d9dc678a57c381c8b57ebf7912e8175d9eef9cc3; no Git command was used.'
  s['inspection_note']='Personally read complete before/current workflow source bytes and independently compared their actual delta. Lines27–47 retain Linux/Windows/macOS matrix,uv sync,check_env andpytest;line47adds--junitxml=outputs/pytest-results.xml. Lines48–78add onlyif:failure() diagnostic summary:parsefailure/error XML nodes,escape HTML,skip other nodes,appendGITHUB_STEP_SUMMARY,andhandle missingXML. Actualpytest9.1.1help verifies argument syntax; exactPythonbody executed on2synthetic local fixtures. No Windows root-cause repair/currenthostedCI success/fullCI rerun is asserted. Originalregisteredff06…bytes preserved in r4_ci_before_read_snapshot_yml.'
for c in r['claims']:
 if c['id']=='c13':
  c['scope']='Audit of retained original GPU/MPS/configuration/CI receipts and original GitHub run/job APIs; their historical numerators/denominators remain unchanged. Same-ownerround4independently checked currentr_ci diagnostics delta. No local GPU/MPS replication,Windows root-cause repair ornewhostedCI success is inferred. ManualGPUworkflow remains conditional on credentials/trigger.'
  for e in c['evidence']:
   if e['source_id']=='r_ci':e.update(locator='Current .github/workflows/ci.yml:27–47test strategy/matrix/check_env/pytest;48–78failure-onlydiagnostics appendix',supports='CurrentworkflowstillretainsWindows/Linux/macOScoretests. JUnitreportargument andfailure-onlysummaryadddiagnostics; neither changesoriginaltestfailureintonormalpassnorconstitutesnewCIexecutionevidence.')
  c['artifact_ids'].append('a_r4delta')
  c['verification']['details']='Own original record audit/APIinspection established immutablehistoricalCIrun37071683289successon3OSjobs andseparateGPU/MPSlimits; these fixedrecord/evidence bytes remainexact. Round4actualbefore/currentfullworkflow comparison proves unchangedmatrix/check_env/pytestselection plusonlynewJUnitarg/failure-summaryappendix. Actualpytesthelp andexactsummaryPython on2synthetic local fixtures checked thediagnosticcommands; nohostedCI/Windows/GPU/MPSreplicationornewsuccessclaim. All original claim statement,numbers,observedhistoricalresults anddenominators are preserved.'
r['review_round']=4;r['reviewer_task']='/root/v4_review_coordinator/factual_whole_entries';r['reviewer_context']='fresh'
r['reviewer_context_details']='Same original independent factual owner necessaryregistered-authoritydelta review; actualfour-file fullread/currentPASS andcorrectedc05/c28history retained from ownimmutablepreviousreports. No peer verdict/author diagnosis/predictedresult was read. Before/after artifacts were read only as original workflow source bytes.'
r['declared_source_freeze']='d9dc678a57c381c8b57ebf7912e8175d9eef9cc3'
r['reviewed_change_scope']='Only registered repository_code authorityr_ci:.github/workflows/ci.yml changedfromff06a806d38f66f3805205e9b46003e87b411fd884d04eee54c300da3c6dd03cto52290167d796430e3c0685e17b8369061a2588175689423f87dfc5c43464aff3. Necessaryaffectedclaimc13reassessed personally; allfour completeauthored-document bytes,currentassignedSVG,otherregisteredcode/authoritytexts,originalfixedrecords andretained evidence matchownpriorverifiedbytes. No unnecessaryfullbody/kernel/CI/browserrerun.'
r['source_read_order']=['Own genuine completefour-document reading/authorities/numeric/software/empirical/browser/figure review retained from immutable round3report4db9ccf8… after exactbytecomparison','Original ci.before.yml.source.txt completebytes;actualcurrentci.yml/ci.after.yml.source.txt completebytes','Actualworkflowlines47–78newJUnitargument/failure()summaryPython inspected','Installedpytest9.1.1CLIhelp;exactsummaryPythonexecutedwith2explicitlysynthetic local fixtures']
r['source_read_scope']='All4owned whole-document readings remain actually complete andbyte-current; no newwholefile read is invented for thisworkflow-onlydelta. CompletechangedCIbefore/current source personallyread andindependentlycompared; onlyc13usesr_ci. Other21registeredcodeauthorities/originalauthoritytexts/4bodyfiles/SVG/prior78registeredartifactbytes/fixedoriginalrecords verifiedunchanged; priorresearch/executionjudgments explicitlyreused withtheir limits.'
r['figure_inspection']='Retained ownactualround3personallyviewed8785render/READMEembed:8characters/arrowsmap[3,2,1,4,1,2,3,0],bothcats3,reverse lookuprestoressentence. CurrentassignedSVGbytesremainexact at9010be747c5159d87bdf0abda52408dd41a7b780bd9c2fff94a3f7dfa44fab86. CI diagnosticdelta hasnofigure effect; no newrender isclaimed.'
r['preview']['evidence_reuse_round4']='Own actualround3browserat8785/literal045ca23… retained asactualpriorinspection; fourauthoredfiles/SVG remainbyteexact andCI diagnosticdelta doesnotaffectthosedocumentclaims. No new8789browserexecution isclaimed orneeded for thisauthority-onlydelta.'
r['checks']['factual_accuracy']['details']='Own genuine full4filefactualPASS remainsapplicableafterexactauthored-bytecomparison. ChangedCIauthorityr_ci waspersonallyread/diffed/assessed; c13configurationandhistoricalresultscope remainvalid. Diagnosticsdelta introducesnounresolvedassignedfactualissue; noWindowsrepair/currentCI success inferred.'
r['checks']['source_verification']['details']='Changedr_ci currentfullSHA boundonlyafter actualownercompletebefore/current workflowreading,independentdiff/relatedc13assessment andboundedcommand/parserverification. Otherregisteredcode/authoritytext/evidencebytes remainexact andtheir originalowninspections arereused. Nopeer/authorjudgment ormechanicalunreviewedhashrebind used.'
r['checks']['limitations']['details']='Currentroundactualexecution islimited tohash/deltaidentity,pytestCLIhelp,andexactnewsummaryPython on2synthetic localXMLfixtures. PriorCPU/GPUrecord-audit/browser/fullread scope retained honestly. NohostedCI/fullkernel/Windowsroot-causerepair/newsuccess,model/data download,training,reading-time estimate orpublisherapproval.'
r['checks']['numeric_verification']['details']+=' All original authorednumbers/claimstatements/observedhistoricalresults/denominators remainunchanged; thisdiagnosticdelta addsnone.'
r['checks']['figure_consistency']['details']+=' Round4actualSVGbytecomparison preservesownpriorpersonallyviewedrender; nonewfigure/browserexecution claimed.'
r['execution_limits']={'current_round':'Only own necessaryworkflowsource/delta/relatedc13review,exactpreservationandbytechecks,pytest9.1.1CLIhelp,exactcurrentfailure-summaryPython on2synthetic localfixtures; actualPython3.13.5/torch2.14.1+cpu CUDAfalse.','original_fullreview':'Own actuallycompleted four-whole-file read/PASS,numeric/software/empirical/originalauthority/browser/figure evidence retained atimmutable round3report; all4currentauthoredfiles/SVG andotherregisteredcode/authority/evidencebytes match. Nofakefullreread/rerun.','diagnostic_limit':'ParserfixturesarenotrealCI failures orhostedrunner executions. CurrentworkflowstillhasthreeOSmatrix; originalhistoricalCIrun37071683289numbersareunchanged. Not aWindowsroot-cause repair ornewCIsuccessclaim.','browser':'No newbrowservisit/render forworkflow-onlydelta. Ownround3actual8785browser evidence explicitlyreused;current8789notrepresented asvisited.','models_training':'No install,heavydata/modeldownload,modelinference,optimizerupdate,GPU,longtraining,fullCI/kernel/bookrerun orGitaction.','publication':'Passonlyfor exact four-document factualsupplement withpersonallyreviewedcurrentCIauthoritydelta andretainedlimits; noreadingminuteestimate orpublisherapproval.'}
r['initial_report_preservation']+=' Round4also preservesgenuine round3PASS4db9ccf8364d5e9b425f2dbe9811edbc5c6efd9c3b565c7db87c2b133cc1455e andregisteredoldr_ci ff06…exactbeforebytes inown snapshots; all priorreports/probes/browserreceipts checkedbyte-exact. New report/evidence writtenonlyinround4.'
r['verdict']='pass';r['issues']=[]
(OUT/'report.json').write_text(json.dumps(r,ensure_ascii=False,indent=2)+'\n')
print('Genuine round4 authority-delta verdict',r['verdict'],'claimcount',len(r['claims']),'sources',len(r['sources']),'artifacts',len(r['artifacts']))
print('ActualreportSHA256',sha(BASE+'report.json'))
print('Preservedpreviousreports',[p['sha256'] for p in delta['preserved_prior_reports']])
