"""Write only this fresh review from its own completed inspection and execution evidence."""
from pathlib import Path
import hashlib,json,shutil
ROOT=Path(__file__).resolve().parents[5]
ART=ROOT/'docs/technical-reviews/artifacts/natural-v4-factual/19.6'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def rel(p):return p.relative_to(ROOT).as_posix()
result=json.loads((ART/'verification-results.json').read_text())
assert json.loads((ART/'verification-receipt.json').read_text())['returncode']==0
inputsha=json.loads((ART/'registered-input-sha256.json').read_text())
for path,digest in inputsha.items():assert sha(ROOT/path)==digest
receipts=json.loads((ART/'original-retrieval-receipts.json').read_text())
retrieved={r['name']:r for r in receipts}
sources=[]
def external(id,kind,title,name,version,note,authority):
 r=retrieved[name]
 sources.append({'id':id,'kind':kind,'title':title,'url':r['url'],'version':version,'verified':True,'checked_original':True,'accessed_on':r['accessed_on'],'retrieval_sha256':r['retrieval_sha256'],'authority_reason':authority,'inspection_note':note})
external('s_vqa','paper','Making the V in VQA Matter: Elevating the Role of Image Understanding in Visual Question Answering','vqa-v2.pdf','arXiv:1612.00837v3, 15 May 2017','Read abstract, §1 pp.1–2 and §3 pp.4–5: same Q with complementary I/I′ and different truths A/A′; language-only constants cannot answer both. Supports intervention/bias logic, not project performance. Full original is ignored; receipt retains download SHA.','Original paper by the authors who introduced complementary-image VQA evaluation.')
external('s_dpo','paper','Direct Preference Optimization: Your Language Model Is Secretly a Reward Model','dpo.pdf','arXiv:2305.18290v3, 29 July 2024','Read §4 pp.4–5, Eq.(7), gradient interpretation and DPO outline: preferred/rejected policy/reference likelihood differences. Compared with alignment.py and capstone preference branch. This toy recipe adds replay CE and uses synthetic preferences.','Original DPO method paper, supporting the meaning of the preference-comparison branch.')
external('s_no_grad','official_docs','torch.no_grad','torch-no-grad-2.14.html','PyTorch 2.14 versioned documentation; actual runtime 2.14.1+cpu','Read class torch.no_grad API body, factory-function exception, thread locality and forward-mode AD note. The lesson performs ordinary reverse-mode inference without a backward call. Stable response was a redirect, followed to /2.14/.','PyTorch maintainers document the exact API used by the lesson.')
external('s_pool','official_docs','torch.nn.AdaptiveAvgPool2d','torch-pool-2.14.html','PyTorch 2.14 versioned documentation; actual runtime 2.14.1+cpu','Read output_size and Shape: N,C,H,W to N,C,S0,S1, channel count preserved. 16×16 to 4×4 here gives 3×4×4=48. Independent manual block averages agree within 1e-6 float32 tolerance.','Official PyTorch pooling contract.')
external('s_mean','official_docs','torch.mean','torch-mean-2.14.html','PyTorch 2.14 versioned documentation; actual runtime 2.14.1+cpu','Read mean(input,dim,keepdim=False) reduction contract; time-axis mean removes that axis. Own permutation derivation limits the time-order claim; not a speech-quality benchmark.','Official PyTorch reduction contract.')
external('s_mel','official_docs','torchaudio.transforms.MelSpectrogram','audio-melspectrogram.html','Torchaudio 2.11 documentation, title verified from retrieved HTML','Read composition of Spectrogram and MelScale, power=2, n_mels and forward output (...,n_mels,time). Project has its own torch implementation, 16 bands and log clamp; no torchaudio execution or compatibility guarantee is asserted.','Official audio representation/API documentation from the PyTorch audio maintainers.')
external('s_mel_source','official_source','torchaudio.functional original HTK mel/filter-bank implementation','audio-functional-2.11.html','Torchaudio 2.11 versioned original source','Read _hz_to_mel HTK branch, _mel_to_hz HTK inverse, _create_triangular_filterbank and melscale_fbanks. Equally spaced mel centers map through 2595 log10(1+f/700) and inverse; triangular weights operate on STFT power. Compared to project mel_filter_bank and own CPU reconstruction.','Maintainers publish original source for the frequency-to-mel and triangular-bank formulas.')
code_notes={
 'tiny_perceptron/capstone.py':('s_capstone','Capstone model, data, preprocessing, targets and generation','Read default_config and CapstoneModel.__init__/forward, build_dataset family splits, modality_tensors, prompt_ids, encode_record/prepare_batch, preference_pairs/preference_loss, generate_trace/generate_traces/evaluate_rows, and save/load/export functions. Actual marker replacement, mask/next-byte shift and trace scoring verified on CPU/records.'),
 'tiny_perceptron/multimodal.py':('s_multimodal','Synthetic media and earlier multimodal encoders','Read tone, mel_filter_bank/log_mel, scene, VisionEncoder/AudioEncoder, expand_modalities and MultiModalLM. Real RGB/tone tensors, STFT/log-mel dimensions and distinct many-vector route checked.'),
 'tiny_perceptron/data.py':('s_data','ByteTokenizer and IGNORE','Read IGNORE=-100 and ByteTokenizer special IDs 0..7, vocab_size=264, UTF-8 byte encoding/decoding; used independent arithmetic byte decoding rather than stored raw strings alone.'),
 'tiny_perceptron/model.py':('s_model','TinyLM input embeddings/output and masked loss','Read ModelConfig, Block, TinyLM.__init__/forward and loss_sum/masked_loss. Vocabulary axis 264, 64-wide capstone embeddings, external embeddings accepted, ignored targets excluded from loss.'),
 'scripts/course_experiments/capstone.py':('s_stage','Frozen integrated stage training and official deployment','Read train_stage parent validation, text-only pretrain/SFT rows, full joint/DPO rows, frozen-reference preference branch and explicit CE replay, completed-step reports and run_deployment. Test evaluation performs no retraining and occurs after fixed schedules.'),
 'scripts/course_experiments/capstone_deployment.py':('s_deploy','Official joint image/audio interventions','Read image_counterfactuals, counterfactual_pairs and run lines272–334: joint recommendation fixed before official test, green→blue/square→circle images, separate pitch swaps, independent generation and source checkpoint SHA fields. No modality-zeroing score is produced here.'),
 'scripts/course_experiments/modalities.py':('s_old_joint','Earlier independent MultiModalLM joint experiment','Read _evaluate lines287–349, _modal/_freeze lines366–385 and run_joint lines913–977: separate trained encoders, >300Hz truth boundary, 12-question original/blank-image/blank-audio/blank evaluations and swaps. This is distinct from CapstoneModel.'),
 'tiny_perceptron/modal_data.py':('s_modal_data','Earlier file-based modality preprocessing','Read modal_example and its RGB conversion, 16kHz mono waveform contract, marker and IGNORE/answer target sequence, supporting trace of the earlier route rather than an unseen dependency.'),
 'tiny_perceptron/alignment.py':('s_alignment','Original repository DPO computation','Read sequence_log_probability lines29–35 and dpo_loss lines38–42: sum valid answer log-probabilities, detach reference margin and negative logsigmoid(beta*relative_margin), matching DPO Eq.(7).')}
for path,(id,title,note) in code_notes.items():
 sources.append({'id':id,'kind':'repository_code','title':title,'path':path,'sha256':inputsha[path],'version':'Current repository source inspected 2026-10-04; exact full-file SHA-256 recorded','verified':True,'inspection_note':note})
sources.append({'id':'s_audit','kind':'execution','title':'Own exact-section CPU execution and independent original-record recomputation','verified':True,'artifact_id':'a_stdout'})
sources.append({'id':'s_derivation','kind':'derivation','title':'Pooling, ordering, baselines and paired success derivations','verified':True,'details':'Image 3×4×4=48; 16-band log-mel [16,T] averaged along time gives [16]; each Linear maps to width64 in one marker slot. Mean m_b=(1/T)Σ_t M_b,t is invariant to a permutation of time frames (apart from floating reduction rounding), so cannot retain their ordering. Balanced single-pitch high/low=3+3 gives constant-answer 3/6; fixed blue gives 9/9. Pair success is correct(original) AND correct(swapped), not just swapped correctness. Hence image totals original 9+0+18=27/36, swapped 9+9+18=36/36, both 9+0+18=27/36 pairs. DPO 18−4=14/18. These are finite task arithmetic and do not infer an internal error cause.'})
artifacts=[]
def artifact(id,kind,filename,description,**extra):
 p=ART/filename;artifacts.append({'id':id,'kind':kind,'path':rel(p),'sha256':sha(p),'description':description,**extra})
artifact('a_stdout','execution','verification.stdout.txt','Actual exact-section CPU output and all original-record score/feature/provenance checks.',command='.venv/bin/python docs/technical-reviews/artifacts/natural-v4-factual/19.6/verify_section.py',result='Actual subprocess return code 0; exact snippet, deterministic preprocessing, all row token/EOS flags, raw scores, stage parent fields, 36 image pairs and 18 audio pairs verified. GPU records independently audited; no training or GPU replication.',environment=result['environment'])
artifact('a_results','derivation','verification-results.json','Own structured finite scores, distributions, regressions, generated-input changes, run provenance and limits.')
artifact('a_code','code','verify_section.py','Own bounded deterministic CPU and independent record audit implementation; successful execution script hash in receipt.')
artifact('a_execution_receipt','source_snapshot','verification-receipt.json','Actual subprocess return code, command and stdout/stderr/script hashes.')
artifact('a_stderr','source_snapshot','verification.stderr.txt','Successful audit stderr, empty; preserved separately from earlier failed probes.')
artifact('a_analysis','derivation','analysis.md','Own read locators, derivations, interpretation, personally viewed figure observations and honest empirical scope.')
artifact('a_originals','source_snapshot','original-retrieval-receipts.json','Own original-authority URL/version retrieval receipt; full third-party responses stay ignored.')
artifact('a_source','source_snapshot','section-19.6-original.md','Complete initial assigned raw UTF-8 section, including every blank line.')
artifact('a_initial','source_snapshot','initial-source-receipt.json','Own canonical task, original source/prerequisite hashes and introduction applicability.')
artifact('a_registered','source_snapshot','registered-input-sha256.json','Actual full-file hashes of all locally inspected code and original raw experiment records.')
artifact('a_exact_code','code','exact-lesson.py','Unmodified Python fence extracted from the current section and actually executed.')
artifact('a_render_run','execution','render.stdout.txt','Actual successful unchanged prerequisite-SVG rendering output.',command='.venv/bin/python docs/technical-reviews/artifacts/natural-v4-factual/19.6/render_prerequisites.py',result='Actual subprocess return code 0, Chromium 151.0.7922.173; all three unchanged SVGs rendered with page.set_content and PNGs personally viewed via view_image.',environment={'python':'3.13.5','chromium':'151.0.7922.173','device':'cpu'})
render_receipts=json.loads((ART/'render-receipts.json').read_text());figure_sha={}
for i,r in enumerate(render_receipts,1):
 figure_sha[r['source']]=r['source_sha256']
 p=ROOT/r['render'];artifact('a_fig'+str(i),'figure_render',p.name,'Personally viewed rendering of necessary prerequisite '+r['source']+'; observations compared with its full current prerequisite text and relevant CPU checks in analysis.md.')
# Register existing original records by their actual paths and full SHA; do not copy/rewrite them.
for i,(path,digest) in enumerate((item for item in inputsha.items() if item[0].endswith('.json')),1):
 artifacts.append({'id':'a_record'+str(i),'kind':'source_snapshot','path':path,'sha256':digest,'description':'Original retained repository experiment/data record actually parsed and independently audited by verify_section.py; relevant raw IDs, splits, run fields and aggregate results are in verification-results.json.'})
def ref(s,l,support):return {'source_id':s,'locator':l,'supports':support}
def claim(id,kind,statement,location,evidence,ids,scope,verification=None):
 d={'id':id,'kind':kind,'statement':statement,'location':location,'status':'verified','evidence':evidence,'artifact_ids':ids,'scope':scope}
 if verification:d['verification']=verification
 return d
def verify(expected,observed,details,denominators=None,tolerance=None):
 d={'method':'executed','expected':expected,'observed':observed,'details':details}
 if denominators:d['denominators']=denominators
 if tolerance:d['tolerance']=tolerance
 return d
common_scope='Deterministic synthetic RGB shapes/two pitch groups and fixed questions in capstone-small-world-v2. This is CPU preprocessing and retained GPU-record validation, not independently repeated GPU training or general visual/speech competence.'
claims=[]
claims.append(claim('c1','concept','A fixed color/pitch label or high score on unbalanced originals does not establish modal use; hold the question and other input fixed, change one answer-relevant modality and its truth, and score both ends and complete joint answers.','Opening paragraph; counterfactual definition and joint-part explanation; last two table/interpretation paragraphs.',[ref('s_vqa','§1 pp.1–2; §3 pp.4–5, complementary (I,Q,A)/(I′,Q,A′)','Original same-question/different-image construction isolates visual evidence and defeats question-only constants.'),ref('s_derivation','Mean, constant-baseline and Boolean pair definitions','Both-correct conjunction and complete payload prevent one strong subpart or swapped-only success from masking failures.')],['a_analysis','a_results'],'Supports diagnostic logic within controlled pairs; it does not identify an internal causal mechanism or prove natural multimodal understanding.'))
claims.append(claim('c2','software','The actual RGB image is spatially averaged 16×16→4×4 per channel (48 numbers); actual 16-band log-mel is time-averaged to 16 numbers; both project to width64 and each replaces one supplied prefix marker. No general pretrained encoder is loaded. Averaging loses detail/time order and differs from the earlier many-vector route.','Feature-summary paragraph; 64-feature/one-position paragraph.',[ref('s_capstone','CapstoneModel.__init__/forward lines74–108; modality_tensors lines285–296; prompt_ids lines299–305','Real material tensors and the actual one-slot projectors/marker replacements.'),ref('s_multimodal','tone, mel_filter_bank/log_mel lines52–84; VisionEncoder and MultiModalLM/expand_modalities','Real STFT/log-mel pipeline and earlier expanded vector route.'),ref('s_pool','AdaptiveAvgPool2d Shape and output_size API','Spatial size and preserved channels.'),ref('s_mean','mean(input,dim,keepdim=False)','Reduction removes the time axis.'),ref('s_mel','MelSpectrogram class composition and forward return shape','Frequency-band representation preserves time frames before averaging.'),ref('s_mel_source','_hz_to_mel, _mel_to_hz, _create_triangular_filterbank, melscale_fbanks','Original HTK and triangular-filter formulas match project and independent reconstruction.')],['a_stdout','a_results','a_code','a_analysis','a_fig2','a_fig3'],common_scope+' Fewer slots are a structural reduction, not a measured GPU speed claim.',verify('Image [3,16,16] → [48] → [64]; audio [16,T] → [16] → [64]; one marker per present modality; unchanged parameters.','Image [3,16,16], 48 pooled values, waveform640/STFT[201,5]/mel[16,5], audio16; hooks output[1,64] in each marker position; manual pooling max difference1.1920928955078125e-7; no parameter changes.','Independent 4×4 block means, HTK triangular bank reconstruction and power/log/time reduction; hooks prove actual prefix vector injection. Averaging spectral frames under reversal checked within float32 tolerance. Pool tolerance1e-6, mel tolerance1e-6, frame mean tolerance2e-6.')))
claims.append(claim('c3','numeric','Low/high here are relative pure-tone groups around 440/880Hz with small offsets, while the earlier >300Hz task labels 440Hz high. The capstone generates new features and does not reuse that classifier output.','low/high versus earlier 300Hz paragraph.',[ref('s_capstone','build_dataset audio specifications lines169–194; modality_tensors line294','Capstone frequency formula and small offsets.'),ref('s_old_joint','run_joint lines913–938, frequency>300 truth','Actual earlier boundary.'),ref('s_multimodal','tone lines52–54','Frequency becomes actual sampled sinusoid, not a text label.')],['a_stdout','a_results','a_analysis'],common_scope+' The group names are data conventions, not universal human pitch categories.',verify('Separate base groups 440/880 plus delta+(variation−1)*2; older threshold300 labels440 high.','All frozen records give low378–482Hz and high818–922Hz; exact selected low row is475Hz from440+37−2. Earlier run_joint uses frequency>300.','Computed every frozen audio spec frequency; inspected both label rules and direct tone/log_mel path. No import/call of the earlier classifier supplies capstone answers.',tolerance='Frequency arithmetic is exact integer arithmetic; grouping and boundary logic exact.')))
claims.append(claim('c4','software','The exact snippet creates an untrained model, uses teacher-forced next-byte answer/EOS targets with ignored prompt targets, returns 264-candidate logits aligned with labels, runs under no_grad without updating, and the image_color exercise needs no audio slot and returns audio=None.','Python fence; prepare_batch/result/labels/no_grad explanation; final exercise.',[ref('s_capstone','encode_record/prepare_batch lines308–338; CapstoneModel.__init__/forward','One shift, answer-only targets, actual batch fields and no checkpoint load.'),ref('s_data','ByteTokenizer lines14–29; IGNORE line10','264 candidates, actual byte/special-ID decoding and −100 ignore value.'),ref('s_model','TinyLM.__init__/forward lines53–88; loss_sum/masked_loss lines94–109','Logits layout and ignored target loss convention.'),ref('s_no_grad','no_grad API body and exceptions','Ordinary reverse-mode computation here creates no gradient graph; no_grad itself is not an optimizer/update prohibition.')],['a_stdout','a_exact_code','a_results','a_code'],common_scope+' Sizes prove the connector executes; no generated quality is inferred from this forward pass.',verify('Image(3,16,16), audio(16,), aligned logits with final axis264; labels only answer/EOS; no update; image-only has no audio marker.','Exact output logits(1,82,264), aligned True; 16 answer/EOS targets; first answer predicted at assistant prefix position; no gradients/graph, all parameters unchanged; image-only audio=None and zero audio markers.','Extracted and executed the complete Python fence unchanged, independently checked byte targets and ignore prefix, used hooks/snapshot comparison, and executed the suggested image_color branch with None-safe handling.')))
claims.append(claim('c5','software','DIRECT is the direct-answer protocol; the joint row task and joint update stage are different namespaced roles. SFT uses text rows, joint uses the full multimodal rows, and the later DPO branch compares preferences from joint. The earlier 12.12 occlusion results are a separate MultiModalLM; this capstone recipe has no reported zeroing score.','Prerequisite/stage/task explanation; DIRECT labels; zeroing paragraph.',[ref('s_capstone','STAGES/DEFAULT_STEPS; build_dataset task joint; parse_action lines550–562; preference_pairs/preference_loss lines341–367','Task labels, direct protocol and preference comparisons.'),ref('s_stage','train_stage rows/reference lines108–121; DPO objective lines204–211; run_deployment lines304–369','Actual stage input continuity, text/full rows, synthetic comparison plus replay.'),ref('s_dpo','§4 pp.4–5, Eq.(7), DPO outline','Preference method meaning; project recipe adds replay CE.'),ref('s_alignment','sequence_log_probability/dpo_loss lines29–42','Masked sequence likelihood and policy/reference margin agree with Eq.(7).'),ref('s_old_joint','_modal lines366–375; _evaluate lines287–298; run_joint lines913–977','Distinct trained-encoder route has earlier masking records.'),ref('s_deploy','run lines272–334 and returned diagnostic fields','Capstone publishes swaps and generation diagnostics without a zeroing score.')],['a_stdout','a_results','a_analysis','a_fig1'],'Only the actual frozen project stages/protocol and inspected official records are claimed. Synthetic DPO is not human-preference RLHF and does not guarantee improvement.',verify('SFT text rows→joint full rows→DPO fixed-reference preference branch; distinct earlier masking experiment; no capstone zeroing metric.','Original completed stage reports/parent SHAs form the described lineage. Earlier separate joint records decode to12/12,6/12,6/12,3/12 across masking conditions; capstone code/records inspected supply no such masking scores.','Read actual source paths and raw run records; verified completed schedules and predecessor export hashes. Independently decoded the old model’s12-question masking samples solely to establish distinct evidence; no old score transferred to capstone.')))
claims.append(claim('c6','empirical','On the fixed validation split, SFT/joint/DPO modal scores are exactly those in the table, with blue-only color baselines and balanced pitch. All nine joint blue-circle shape cases terminate as square; train blue images appear only with square, but that correlation alone does not identify the model’s internal error cause.','Validation table and following shape/pitch/joint limitations paragraphs.',[ref('s_audit','verify_section.py audit(), validation loops, dataset distributions and structured validation_scores','Recomputed scores from original generated token IDs/EOS, labels and regenerated inputs.'),ref('s_capstone','build_dataset modality families and split selection; evaluate_rows scoring lines499–547','Task identities, held-out families and exact complete-action/EOS scoring.'),ref('s_derivation','Fixed-answer baseline arithmetic','blue9/9, constant pitch3/6; joint asks color and pitch only.')],['a_stdout','a_results','a_registered','a_analysis'],common_scope+' One seed and finite correlated visual family; neither baseline success nor these failures establish an internal cause.',verify('SFT0/9,0/9,0/6,0/18; joint9/9,0/9,6/6,18/18; DPO9/9,0/9,6/6,14/18; all color blue, pitch3+3, joint pitch9+9; nine EOS-terminated square errors.','All table entries and distribution counts match independent raw-token/EOS recomputation; all9 shape outputs DIRECT:square versus circle; train blue shapes only square.','Regenerated official splits with seed42 and matched deployment data/manifest exactly; audited every row, not just aggregate by_task flags. Variants3×offsets3=9 image cases. Original validation artifacts are individually registered with full SHA.',{'split':'validation','all_rows':84,'modal_rows':42,'image_color':9,'image_shape':9,'audio':6,'joint':18,'pitch_per_class_audio':3,'pitch_per_class_joint':9,'seed':42,'completed_updates':{'sft':1400,'joint':600,'dpo':100}})))
claims.append(claim('c7','empirical','DPO changes four previously correct validation joint outputs from blue to red with pitch still correct, lowering full-string joint accuracy from18/18 to14/18.','DPO regression paragraph and linked individual outputs.',[ref('s_audit','Matched validation IDs in dpo_joint_regressions and raw validation audit','Four genuine same-row regressions, exact strings and EOS are independently checked.'),ref('s_derivation','18−4=14','Whole-answer decrement follows from four color failures; pitch success alone does not make a joint answer correct.')],['a_stdout','a_results','a_analysis'],common_scope+' Evidence is observed branch regression, not a universal DPO result or a causal explanation from loss.',verify('Exactly4 same-ID joint regressions, all red errors with original correct pitch, resulting14/18.','Two blue,low→red,low and two blue,high→red,high changes, all EOS-terminated; all four exact IDs stored;14/18.','Joined complete original joint and DPO validation records by stable ID, independently decoded IDs and compared complete expected payloads and pitch components.',{'split':'validation','all_rows_per_stage':84,'compared_joint_rows':18,'regressions':4,'correct_after':14,'seed':42,'joint_updates':600,'dpo_updates':100})))
claims.append(claim('c8','empirical','On the separate fixed final green-square family, recommended joint and DPO both score color9/9,shape0/9,audio6/6,joint18/18. Joint shape outputs are all circle with normal EOS. The official frozen deployment keeps the recommendation based on validation and preserves failures without a test-driven retraining step.','Final-exam paragraph; fixed validation/final-data distinction; final sentence about preserving failure after formal check.',[ref('s_audit','test_scores, test_distributions, frozen manifest and deployment provenance checks','Final split/family, identical per-task modal counts, raw shape traces and source stage association.'),ref('s_stage','run_deployment lines304–369','Fixed completed stages are evaluated; function contains no training update call.'),ref('s_deploy','run lines272–277, source selection lines294–331','Joint choice is declared before official test and swap diagnostics cite the joint source SHA.')],['a_stdout','a_results','a_registered','a_analysis'],common_scope+' Historical freeze/non-retraining claim is supported within the retained official records and inspected deployment program. No hidden outside actions or checkpoint tensor replication are asserted.',verify('Separate90-row test; green square visual family; both stages9/9,0/9,6/6,18/18; all9 joint shape generations DIRECT:circle and EOS; recommendation remainsjoint.','Regenerated and matched90 test rows; both raw score matrices match;9 circle errors with EOS; recipe_frozen_before_test=true, recommended_stage=joint, recorded source SHA binds test and diagnostics.','Independently recomputed every raw test row. Checked completed-stage ancestry and explicit source checkpoint SHA; deployment re-export is a separate container with a different SHA and is not incorrectly treated as byte-identical to its source. The deployment has no retraining call.',{'split':'test','all_rows_per_stage':90,'image_color':9,'image_shape':9,'audio':6,'joint':18,'seed':42,'joint_updates':600,'dpo_updates':100})))
claims.append(claim('c9','empirical','For joint image interventions, original/swapped/both-correct totals are27/36,36/36,27/36 pairs, with color9/9 pairs,shape0/9 pairs,joint18/18 pairs. All shape pairs retain circle on both ends. Keeping the image and swapping joint pitch yields18/18 swaps and18/18 both-correct pairs.','Image intervention table and all remaining counterfactual interpretation/evidence paragraphs.',[ref('s_audit','image_pair_scores, image_input_changes and audio_swap_scores/audio_both_correct','Each actual regenerated input and all original/swap token traces independently joined and scored.'),ref('s_deploy','image_counterfactuals lines35–54; counterfactual_pairs lines57–79; pitch-swap loop lines321–331','Changed material/truth, unchanged question/other modality, and proper pair definition.'),ref('s_derivation','9+0+18=27;9+9+18=36; both-correct conjunction','Pair arithmetic distinguishes swapped-only shape correctness from successful dependence.')],['a_stdout','a_results','a_analysis','a_registered'],common_scope+' Supports input dependence for color/pitch in these controlled cases; shape fails and general photos, spoken language or unrestricted questions remain untested.',verify('Image color original/swapped/both9,9,9 of9;shape0,9,0 of9;joint18,18,18 of18; totals27,36,27 of36. Audio18 swaps and18 original+swap pairs correct.','All expected counts match. Questions/prompts identical across interventions; actual pixels change for all36 image rows with acoustic summary preserved. All18 pitch changes preserve image but change actual acoustic summary. Shape raw output circle unchanged across every pair.','Independently rebuilt swaps from frozen source rows, regenerated features with actual modality_tensors, checked unchanged question/other material, decoded raw token sequences/EOS, rebuilt Boolean pairs, and matched the retained pair-file fields row by row.',{'split':'test interventions from fixed90 originals','image_pairs':36,'image_color_pairs':9,'image_shape_pairs':9,'joint_image_pairs':18,'audio_pairs':18,'seed':42,'joint_updates':600})))
report={'schema_version':1,'review_stage':'technical','lesson_id':'19.6','source':'course/chapters/19.md#19.6','reviewer_task':'/root/v4_review_coordinator/factual_v4_19_6','reviewer_context':'fresh','source_sha256':sha(ART/'section-19.6-original.md'),'introduction_applicability':'not_applicable: section19.6 is not first section','direct_figure_sha256':{},'figure_sha256':figure_sha,'verdict':'pass','claims':claims,'sources':sources,'artifacts':artifacts,'issues':[],'checks':{
 'factual_accuracy':{'status':'pass','details':'Complete current body, all necessary prerequisites and grouped substantive claims checked against original authorities, actual project code, independent CPU feature/target probes and all retained raw traces. No factual contradiction or unresolved section claim found.','claim_ids':[c['id'] for c in claims]},
 'numeric_verification':{'status':'pass','details':'Verified48/16/64/264 dimensions, frequency rules and counts, every validation/test modal score, constant baselines, four regressions,36 image pairs and18 audio pairs. Float32 manual pooling tolerance justified by measured1.1920928955078125e-7 difference; retained failed-probe records and corrected provenance distinction.','claim_ids':['c2','c3','c4','c6','c7','c8','c9']},
 'figure_consistency':{'status':'pass','details':'No SVG directly referenced by19.6. Rendered and personally viewed necessary19.4 pipeline,10.7 image expansion and12.5 spectral-axis SVGs; arrows,7→6-position target shift, frequency/amplitude/time labels and numerical frame scales agree with relevant text/code. These optional prerequisites are explicitly hashed.','claim_ids':['c2','c3','c4','c5']},
 'source_verification':{'status':'pass','details':'Downloaded/read original VQA-v2/DPO PDFs and PyTorch2.14 docs, Torchaudio2.11 representation/original HTK-bank source with versioned locators and retrieval SHA receipts. Registered actual full-file SHA for all inspected repo code and original data/run records. Earlier review content stayed unread.','claim_ids':[c['id'] for c in claims]},
 'limitations':{'status':'pass','details':'Kept untrained shape check separate from generated quality, fixed-color baseline separate from image dependence, complete answer/pair scores separate from better subparts/swapped-only success, old occlusion model separate from capstone, single synthetic seed/fixed prompts separate from natural-image/speech ability. GPU training/quality was not replicated; official records and CPU deterministic preprocessing were independently audited.','claim_ids':[c['id'] for c in claims]}}}
assert report['source_sha256']=='7554c7e68ea49a77c7130045150550d517ff374402970140776d51123e2043d6'
out=ROOT/'docs/technical-reviews/19.6.json';out.write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n')
shutil.copyfile(out,ART/'first-own-report.json')
print('WROTE',rel(out),'CLAIMS',len(claims),'SOURCES',len(sources),'ARTIFACTS',len(artifacts),'SOURCE_SHA',report['source_sha256'],'REPORT_SHA',sha(out),'VERDICT',report['verdict'])
